// CompTIA A+ Drill Sets — high-yield rote memorization

const NOW = new Date().toISOString()

export const SEED_DRILL_SETS = [
  {
    id: 'ds-ports',
    title: 'Common Ports',
    slug: 'common-ports',
    icon: '🔌',
    examCode: 'core1',
    description: 'Protocol → port number',
    orderIndex: 0,
    published: true,
    source: 'seed',
    createdAt: NOW,
    updatedAt: null,
  },
  {
    id: 'ds-raid',
    title: 'RAID Levels',
    slug: 'raid-levels',
    icon: '💾',
    examCode: 'core1',
    description: 'RAID level → min disks & fault tolerance',
    orderIndex: 1,
    published: true,
    source: 'seed',
    createdAt: NOW,
    updatedAt: null,
  },
  {
    id: 'ds-ram',
    title: 'RAM / DDR Generations',
    slug: 'ram-ddr',
    icon: '🧠',
    examCode: 'core1',
    description: 'Memory type → key spec',
    orderIndex: 2,
    published: true,
    source: 'seed',
    createdAt: NOW,
    updatedAt: null,
  },
  {
    id: 'ds-wifi',
    title: 'Wi-Fi Standards',
    slug: 'wifi-standards',
    icon: '📶',
    examCode: 'core1',
    description: '802.11 standard → band & max rate',
    orderIndex: 3,
    published: true,
    source: 'seed',
    createdAt: NOW,
    updatedAt: null,
  },
  {
    id: 'ds-connectors',
    title: 'Cables & Connectors',
    slug: 'cables-connectors',
    icon: '🔗',
    examCode: 'core1',
    description: 'Connector → use',
    orderIndex: 4,
    published: true,
    source: 'seed',
    createdAt: NOW,
    updatedAt: null,
  },
]

export const SEED_DRILL_FACTS = [
  // ─── Common Ports ────────────────────────────────────────────────────────────
  {
    id: 'df-port-ftp-data',
    drillSetId: 'ds-ports',
    term: 'FTP (data)',
    value: '20',
    hint: 'file transfer — data channel',
    aliases: null,
    orderIndex: 0,
  },
  {
    id: 'df-port-ftp-ctrl',
    drillSetId: 'ds-ports',
    term: 'FTP (control)',
    value: '21',
    hint: 'file transfer — control channel',
    aliases: null,
    orderIndex: 1,
  },
  {
    id: 'df-port-ssh',
    drillSetId: 'ds-ports',
    term: 'SSH',
    value: '22',
    hint: 'secure shell / SFTP / SCP',
    aliases: '["SFTP","SCP"]',
    orderIndex: 2,
  },
  {
    id: 'df-port-telnet',
    drillSetId: 'ds-ports',
    term: 'Telnet',
    value: '23',
    hint: 'insecure remote terminal',
    aliases: null,
    orderIndex: 3,
  },
  {
    id: 'df-port-smtp',
    drillSetId: 'ds-ports',
    term: 'SMTP',
    value: '25',
    hint: 'send mail between servers',
    aliases: null,
    orderIndex: 4,
  },
  {
    id: 'df-port-dns',
    drillSetId: 'ds-ports',
    term: 'DNS',
    value: '53',
    hint: 'domain name resolution (UDP & TCP)',
    aliases: null,
    orderIndex: 5,
  },
  {
    id: 'df-port-dhcp',
    drillSetId: 'ds-ports',
    term: 'DHCP',
    value: '67, 68',
    hint: 'IP assignment — server 67, client 68',
    aliases: '["67","68","67/68"]',
    orderIndex: 6,
  },
  {
    id: 'df-port-http',
    drillSetId: 'ds-ports',
    term: 'HTTP',
    value: '80',
    hint: 'unencrypted web traffic',
    aliases: null,
    orderIndex: 7,
  },
  {
    id: 'df-port-pop3',
    drillSetId: 'ds-ports',
    term: 'POP3',
    value: '110',
    hint: 'receive mail — downloads and deletes from server',
    aliases: null,
    orderIndex: 8,
  },
  {
    id: 'df-port-netbios-ns',
    drillSetId: 'ds-ports',
    term: 'NetBIOS Name Service',
    value: '137',
    hint: 'Windows name resolution over NetBIOS',
    aliases: null,
    orderIndex: 9,
  },
  {
    id: 'df-port-netbios-dgm',
    drillSetId: 'ds-ports',
    term: 'NetBIOS Datagram',
    value: '138',
    hint: 'connectionless NetBIOS messaging',
    aliases: null,
    orderIndex: 10,
  },
  {
    id: 'df-port-netbios-ssn',
    drillSetId: 'ds-ports',
    term: 'NetBIOS Session',
    value: '139',
    hint: 'connection-oriented NetBIOS (file sharing pre-SMB direct)',
    aliases: null,
    orderIndex: 11,
  },
  {
    id: 'df-port-imap',
    drillSetId: 'ds-ports',
    term: 'IMAP',
    value: '143',
    hint: 'receive mail — syncs, leaves mail on server',
    aliases: null,
    orderIndex: 12,
  },
  {
    id: 'df-port-snmp',
    drillSetId: 'ds-ports',
    term: 'SNMP',
    value: '161, 162',
    hint: 'network device management — polls 161, traps 162',
    aliases: '["161","162"]',
    orderIndex: 13,
  },
  {
    id: 'df-port-ldap',
    drillSetId: 'ds-ports',
    term: 'LDAP',
    value: '389',
    hint: 'directory services (Active Directory, OpenLDAP)',
    aliases: null,
    orderIndex: 14,
  },
  {
    id: 'df-port-https',
    drillSetId: 'ds-ports',
    term: 'HTTPS',
    value: '443',
    hint: 'encrypted web (TLS)',
    aliases: null,
    orderIndex: 15,
  },
  {
    id: 'df-port-smb',
    drillSetId: 'ds-ports',
    term: 'SMB',
    value: '445',
    hint: 'Windows file and print sharing (direct TCP, no NetBIOS needed)',
    aliases: '["CIFS"]',
    orderIndex: 16,
  },
  {
    id: 'df-port-smtps',
    drillSetId: 'ds-ports',
    term: 'SMTP (secure / submission)',
    value: '587',
    hint: 'mail submission with STARTTLS; legacy 465 also seen',
    aliases: '["587","465"]',
    orderIndex: 17,
  },
  {
    id: 'df-port-ldaps',
    drillSetId: 'ds-ports',
    term: 'LDAPS',
    value: '636',
    hint: 'LDAP over TLS',
    aliases: null,
    orderIndex: 18,
  },
  {
    id: 'df-port-imaps',
    drillSetId: 'ds-ports',
    term: 'IMAPS',
    value: '993',
    hint: 'IMAP over TLS',
    aliases: null,
    orderIndex: 19,
  },
  {
    id: 'df-port-pop3s',
    drillSetId: 'ds-ports',
    term: 'POP3S',
    value: '995',
    hint: 'POP3 over TLS',
    aliases: null,
    orderIndex: 20,
  },
  {
    id: 'df-port-mysql',
    drillSetId: 'ds-ports',
    term: 'MySQL / MariaDB',
    value: '3306',
    hint: 'default relational database port',
    aliases: null,
    orderIndex: 21,
  },
  {
    id: 'df-port-rdp',
    drillSetId: 'ds-ports',
    term: 'RDP',
    value: '3389',
    hint: 'remote desktop protocol (Windows)',
    aliases: null,
    orderIndex: 22,
  },
  {
    id: 'df-port-http-alt',
    drillSetId: 'ds-ports',
    term: 'HTTP alternate',
    value: '8080',
    hint: 'common alt web / proxy port',
    aliases: '["8080","8443"]',
    orderIndex: 23,
  },

  // ─── RAID Levels ─────────────────────────────────────────────────────────────
  {
    id: 'df-raid-0',
    drillSetId: 'ds-raid',
    term: 'RAID 0',
    value: 'Striping — 2 disks min, no fault tolerance',
    hint: 'speed only; one drive failure = total data loss',
    aliases: null,
    orderIndex: 0,
  },
  {
    id: 'df-raid-1',
    drillSetId: 'ds-raid',
    term: 'RAID 1',
    value: 'Mirroring — 2 disks min, 1 disk can fail',
    hint: 'identical copy on each disk; usable capacity = 50%',
    aliases: null,
    orderIndex: 1,
  },
  {
    id: 'df-raid-5',
    drillSetId: 'ds-raid',
    term: 'RAID 5',
    value: 'Striping + distributed parity — 3 disks min, 1 disk can fail',
    hint: 'parity rotates across all drives; usable = (n-1) disks',
    aliases: null,
    orderIndex: 2,
  },
  {
    id: 'df-raid-6',
    drillSetId: 'ds-raid',
    term: 'RAID 6',
    value: 'Striping + double parity — 4 disks min, 2 disks can fail',
    hint: 'two parity blocks per stripe; usable = (n-2) disks',
    aliases: null,
    orderIndex: 3,
  },
  {
    id: 'df-raid-10',
    drillSetId: 'ds-raid',
    term: 'RAID 10',
    value: 'Mirror + stripe — 4 disks min, 1 disk per mirrored pair can fail',
    hint: 'speed + redundancy; usable = 50%; best write performance of redundant RAID types',
    aliases: '["RAID 1+0"]',
    orderIndex: 4,
  },

  // ─── RAM / DDR Generations ───────────────────────────────────────────────────
  {
    id: 'df-ram-ddr',
    drillSetId: 'ds-ram',
    term: 'DDR (DDR1)',
    value: '184-pin DIMM / 200-pin SODIMM, 2.5V',
    hint: 'original double data rate; keyed differently from DDR2+',
    aliases: '["DDR1","DDR SDRAM"]',
    orderIndex: 0,
  },
  {
    id: 'df-ram-ddr2',
    drillSetId: 'ds-ram',
    term: 'DDR2',
    value: '240-pin DIMM / 200-pin SODIMM, 1.8V',
    hint: 'notch offset differs from DDR; not interchangeable with DDR',
    aliases: null,
    orderIndex: 1,
  },
  {
    id: 'df-ram-ddr3',
    drillSetId: 'ds-ram',
    term: 'DDR3',
    value: '240-pin DIMM / 204-pin SODIMM, 1.5V (DDR3L = 1.35V)',
    hint: 'same pin count as DDR2 DIMM but different notch position; DDR3L is low-voltage variant',
    aliases: '["DDR3L"]',
    orderIndex: 2,
  },
  {
    id: 'df-ram-ddr4',
    drillSetId: 'ds-ram',
    term: 'DDR4',
    value: '288-pin DIMM / 260-pin SODIMM, 1.2V',
    hint: 'curved PCB edge on DIMM; notch shifted again; not backward compatible',
    aliases: null,
    orderIndex: 3,
  },
  {
    id: 'df-ram-ddr5',
    drillSetId: 'ds-ram',
    term: 'DDR5',
    value: '288-pin DIMM / 262-pin SODIMM, 1.1V',
    hint: 'on-module PMIC; two 32-bit sub-channels per DIMM; higher speeds/density than DDR4',
    aliases: null,
    orderIndex: 4,
  },
  {
    id: 'df-ram-ecc',
    drillSetId: 'ds-ram',
    term: 'ECC RAM',
    value: 'Error Correcting Code — detects and corrects single-bit memory errors',
    hint: 'extra chip per module; used in servers; requires chipset/CPU support',
    aliases: null,
    orderIndex: 5,
  },
  {
    id: 'df-ram-dimm-vs-sodimm',
    drillSetId: 'ds-ram',
    term: 'DIMM vs SODIMM',
    value: 'DIMM = full-size desktop module; SODIMM = small-outline for laptops',
    hint: 'SODIMM is roughly half the length of a DIMM',
    aliases: null,
    orderIndex: 6,
  },
  {
    id: 'df-ram-channels',
    drillSetId: 'ds-ram',
    term: 'Single vs Dual Channel',
    value: 'Dual channel uses two matched DIMMs in paired slots to double memory bandwidth',
    hint: 'check mobo manual for paired slots (commonly A2+B2); mismatched modules fall back to single-channel',
    aliases: null,
    orderIndex: 7,
  },

  // ─── Wi-Fi Standards ─────────────────────────────────────────────────────────
  {
    id: 'df-wifi-a',
    drillSetId: 'ds-wifi',
    term: '802.11a',
    value: '5 GHz only, up to 54 Mbps',
    hint: 'older; 5 GHz = less interference but shorter range than 2.4 GHz',
    aliases: null,
    orderIndex: 0,
  },
  {
    id: 'df-wifi-b',
    drillSetId: 'ds-wifi',
    term: '802.11b',
    value: '2.4 GHz only, up to 11 Mbps',
    hint: 'very old; slowest; most interference-prone band',
    aliases: null,
    orderIndex: 1,
  },
  {
    id: 'df-wifi-g',
    drillSetId: 'ds-wifi',
    term: '802.11g',
    value: '2.4 GHz only, up to 54 Mbps',
    hint: 'backward-compatible with 802.11b devices',
    aliases: null,
    orderIndex: 2,
  },
  {
    id: 'df-wifi-n',
    drillSetId: 'ds-wifi',
    term: '802.11n (Wi-Fi 4)',
    value: '2.4 & 5 GHz dual-band, up to 600 Mbps',
    hint: 'introduced MIMO; very common in homes',
    aliases: '["Wi-Fi 4"]',
    orderIndex: 3,
  },
  {
    id: 'df-wifi-ac',
    drillSetId: 'ds-wifi',
    term: '802.11ac (Wi-Fi 5)',
    value: '5 GHz only, up to ~3.5 Gbps',
    hint: 'MU-MIMO; wide channels up to 160 MHz; 5 GHz band only',
    aliases: '["Wi-Fi 5"]',
    orderIndex: 4,
  },
  {
    id: 'df-wifi-ax',
    drillSetId: 'ds-wifi',
    term: '802.11ax (Wi-Fi 6 / 6E)',
    value: '2.4 & 5 GHz; Wi-Fi 6E also adds 6 GHz — up to ~9.6 Gbps',
    hint: 'OFDMA + MU-MIMO; better dense-environment performance; Wi-Fi 6E adds 6 GHz band',
    aliases: '["Wi-Fi 6","Wi-Fi 6E"]',
    orderIndex: 5,
  },
  {
    id: 'df-wifi-be',
    drillSetId: 'ds-wifi',
    term: '802.11be (Wi-Fi 7)',
    value: '2.4, 5, & 6 GHz tri-band, up to ~46 Gbps',
    hint: 'multi-link operation (MLO); 320 MHz channels; emerging standard',
    aliases: '["Wi-Fi 7"]',
    orderIndex: 6,
  },

  // ─── Cables & Connectors ─────────────────────────────────────────────────────
  {
    id: 'df-conn-rj45',
    drillSetId: 'ds-connectors',
    term: 'RJ45',
    value: 'Ethernet — 8-pin modular connector',
    hint: 'used for Cat5e, Cat6, Cat6a network cables',
    aliases: null,
    orderIndex: 0,
  },
  {
    id: 'df-conn-rj11',
    drillSetId: 'ds-connectors',
    term: 'RJ11',
    value: 'Telephone / DSL — 6-pin (uses 2 or 4) modular connector',
    hint: 'smaller than RJ45; common on landline phones and modems',
    aliases: null,
    orderIndex: 1,
  },
  {
    id: 'df-conn-usb-a',
    drillSetId: 'ds-connectors',
    term: 'USB-A',
    value: 'Standard rectangular USB host connector — USB 1.1 / 2.0 / 3.x',
    hint: 'most common USB port on desktops/laptops; USB 3.0 ports are blue',
    aliases: null,
    orderIndex: 2,
  },
  {
    id: 'df-conn-usb-b',
    drillSetId: 'ds-connectors',
    term: 'USB-B',
    value: 'Square USB device connector — printers, hubs',
    hint: 'the chunky square end on printer cables',
    aliases: null,
    orderIndex: 3,
  },
  {
    id: 'df-conn-usb-micro',
    drillSetId: 'ds-connectors',
    term: 'USB Micro-B',
    value: 'Small mobile connector — Android phones, USB 3.0 external drives',
    hint: 'flat bottom, angled sides; USB 3.0 Micro-B adds extra pins on one side',
    aliases: null,
    orderIndex: 4,
  },
  {
    id: 'df-conn-usb-c',
    drillSetId: 'ds-connectors',
    term: 'USB-C',
    value: 'Reversible oval connector — supports USB 3.1/3.2/4, Thunderbolt 3/4, DisplayPort Alt Mode, Power Delivery',
    hint: 'same physical connector for many protocols; verify spec for actual speed',
    aliases: null,
    orderIndex: 5,
  },
  {
    id: 'df-conn-lightning',
    drillSetId: 'ds-connectors',
    term: 'Lightning',
    value: 'Apple proprietary reversible connector — iPhones/iPads (pre-USB-C models)',
    hint: 'replaced by USB-C on iPhone 15 and later iPad models',
    aliases: null,
    orderIndex: 6,
  },
  {
    id: 'df-conn-thunderbolt3',
    drillSetId: 'ds-connectors',
    term: 'Thunderbolt 3 / 4',
    value: 'USB-C shaped — up to 40 Gbps, carries DisplayPort + PCIe + USB + Power Delivery',
    hint: 'TB symbol (lightning bolt) on port; looks identical to USB-C; TB4 enforces stricter minimums',
    aliases: '["Thunderbolt 3","Thunderbolt 4"]',
    orderIndex: 7,
  },
  {
    id: 'df-conn-sata',
    drillSetId: 'ds-connectors',
    term: 'SATA',
    value: 'L-shaped data (7-pin) + power (15-pin) connectors — HDDs, SSDs, optical drives',
    hint: 'SATA III = 6 Gbps max; eSATA for external; do not confuse data and power connectors',
    aliases: '["eSATA","SATA III"]',
    orderIndex: 8,
  },
  {
    id: 'df-conn-m2',
    drillSetId: 'ds-connectors',
    term: 'M.2',
    value: 'Blade connector on motherboard — M key (NVMe PCIe) or B+M key (SATA); sizes 2242/2260/2280',
    hint: 'NVMe via PCIe lanes is much faster than M.2 SATA; width 22 mm, length = last two digits in mm',
    aliases: null,
    orderIndex: 9,
  },
  {
    id: 'df-conn-hdmi',
    drillSetId: 'ds-connectors',
    term: 'HDMI',
    value: 'Video + audio — Type A (full-size), Type C (mini), Type D (micro)',
    hint: 'HDMI 2.0 = 4K@60Hz; HDMI 2.1 = 8K@60Hz or 4K@120Hz',
    aliases: '["HDMI Type A","Mini HDMI","Micro HDMI"]',
    orderIndex: 10,
  },
  {
    id: 'df-conn-displayport',
    drillSetId: 'ds-connectors',
    term: 'DisplayPort',
    value: 'Video (+ audio) with locking tab — DP 1.4 supports 8K@60Hz; mini-DP variant exists',
    hint: 'preferred for PC monitors; supports MST daisy-chaining; no licensing fee unlike HDMI',
    aliases: '["DP","Mini DisplayPort","Mini-DP"]',
    orderIndex: 11,
  },
  {
    id: 'df-conn-vga',
    drillSetId: 'ds-connectors',
    term: 'VGA',
    value: 'Analog video only — DB-15 (3-row 15-pin D-sub); typically blue',
    hint: 'legacy; no audio; max practical 1920x1200; cannot carry digital signal natively',
    aliases: '["DE-15","D-Sub"]',
    orderIndex: 12,
  },
  {
    id: 'df-conn-dvi',
    drillSetId: 'ds-connectors',
    term: 'DVI',
    value: 'DVI-D = digital only, DVI-A = analog only, DVI-I = both; single/dual link variants',
    hint: 'DVI-D single-link = 1920x1200; dual-link = 2560x1600; no audio signal',
    aliases: '["DVI-D","DVI-A","DVI-I"]',
    orderIndex: 13,
  },
]
