import { randomUUID } from 'crypto'

export const SEED_EXAMS = [
  {
    id: 'exam-core1',
    code: '220-1201',
    name: 'CompTIA A+ Core 1',
    description: 'Covers mobile devices, networking, hardware, virtualization, cloud computing, and hardware/network troubleshooting.',
    totalTimeMinutes: 90,
    passingScore: 675,
    maxQuestions: 90,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exam-core2',
    code: '220-1202',
    name: 'CompTIA A+ Core 2',
    description: 'Covers operating systems, security, software troubleshooting, and operational procedures.',
    totalTimeMinutes: 90,
    passingScore: 700,
    maxQuestions: 90,
    createdAt: new Date().toISOString(),
  },
]

export const SEED_DOMAINS = [
  // Core 1 domains (220-1201)
  {
    id: 'domain-c1-1',
    examId: 'exam-core1',
    number: 1,
    name: 'Mobile Devices',
    slug: 'mobile-devices',
    weightPercent: 13,
    description: 'Covers laptop hardware, mobile device accessories, connectivity, and network configuration.',
    orderIndex: 1,
  },
  {
    id: 'domain-c1-2',
    examId: 'exam-core1',
    number: 2,
    name: 'Networking',
    slug: 'networking',
    weightPercent: 23,
    description: 'Covers TCP/UDP, wireless networking, network hosts, configuration, hardware, SOHO networks, internet connections, and networking tools.',
    orderIndex: 2,
  },
  {
    id: 'domain-c1-3',
    examId: 'exam-core1',
    number: 3,
    name: 'Hardware',
    slug: 'hardware',
    weightPercent: 25,
    description: 'Covers displays, cables, RAM, storage, motherboards, CPUs, power supplies, and printers.',
    orderIndex: 3,
  },
  {
    id: 'domain-c1-4',
    examId: 'exam-core1',
    number: 4,
    name: 'Virtualization and Cloud Computing',
    slug: 'virtualization-cloud',
    weightPercent: 11,
    description: 'Covers virtualization concepts and cloud computing models.',
    orderIndex: 4,
  },
  {
    id: 'domain-c1-5',
    examId: 'exam-core1',
    number: 5,
    name: 'Hardware and Network Troubleshooting',
    slug: 'hw-network-troubleshooting',
    weightPercent: 28,
    description: 'Covers troubleshooting motherboards, storage, displays, mobile devices, networks, and printers.',
    orderIndex: 5,
  },
  // Core 2 domains (220-1202)
  {
    id: 'domain-c2-1',
    examId: 'exam-core2',
    number: 1,
    name: 'Operating Systems',
    slug: 'operating-systems',
    weightPercent: 28,
    description: 'Covers Windows, macOS, Linux, OS types, installations, upgrades, and application management.',
    orderIndex: 1,
  },
  {
    id: 'domain-c2-2',
    examId: 'exam-core2',
    number: 2,
    name: 'Security',
    slug: 'security',
    weightPercent: 28,
    description: 'Covers security measures, Windows security, wireless security, malware, social engineering, hardening, mobile security, data destruction, and browser security.',
    orderIndex: 2,
  },
  {
    id: 'domain-c2-3',
    examId: 'exam-core2',
    number: 3,
    name: 'Software Troubleshooting',
    slug: 'software-troubleshooting',
    weightPercent: 23,
    description: 'Covers troubleshooting Windows OS, mobile OS, application issues, and security problems.',
    orderIndex: 3,
  },
  {
    id: 'domain-c2-4',
    examId: 'exam-core2',
    number: 4,
    name: 'Operational Procedures',
    slug: 'operational-procedures',
    weightPercent: 21,
    description: 'Covers documentation, change management, backup, safety, environmental controls, policies, professionalism, scripting, remote access, and AI concepts.',
    orderIndex: 4,
  },
]

export const SEED_TOPICS = [
  // Core 1 — Domain 1: Mobile Devices
  {
    id: 'topic-c1-1-1',
    domainId: 'domain-c1-1',
    objectiveId: '1.1',
    title: 'Monitor mobile device hardware and apply appropriate replacement methods',
    slug: '1-1-mobile-device-hardware',
    description: 'Battery replacement, keyboard, RAM, storage, wireless cards, and physical privacy/security components.',
    orderIndex: 1,
  },
  {
    id: 'topic-c1-1-2',
    domainId: 'domain-c1-1',
    objectiveId: '1.2',
    title: 'Compare and contrast mobile device accessories and connectivity options',
    slug: '1-2-mobile-accessories-connectivity',
    description: 'USB-C, Thunderbolt, Lightning, docking stations, port replicators, wireless accessories.',
    orderIndex: 2,
  },
  {
    id: 'topic-c1-1-3',
    domainId: 'domain-c1-1',
    objectiveId: '1.3',
    title: 'Configure basic mobile device network connectivity and support applications',
    slug: '1-3-mobile-network-connectivity',
    description: 'WiFi, cellular, Bluetooth, hotspot, location services, email, VPN configuration.',
    orderIndex: 3,
  },
  // Core 1 — Domain 2: Networking
  {
    id: 'topic-c1-2-1',
    domainId: 'domain-c1-2',
    objectiveId: '2.1',
    title: 'Compare and contrast TCP and UDP ports, protocols, and their functions',
    slug: '2-1-tcp-udp-ports-protocols',
    description: 'Common ports (21,22,23,25,53,67,68,80,110,143,443,3389), TCP vs UDP, DNS, DHCP, HTTP/S, FTP, SSH, SMTP.',
    orderIndex: 1,
  },
  {
    id: 'topic-c1-2-2',
    domainId: 'domain-c1-2',
    objectiveId: '2.2',
    title: 'Explain wireless networking technologies',
    slug: '2-2-wireless-networking',
    description: '802.11 standards (a/b/g/n/ac/ax), frequencies (2.4GHz/5GHz/6GHz), channels, SSID, encryption (WPA2/WPA3), Bluetooth.',
    orderIndex: 2,
  },
  {
    id: 'topic-c1-2-3',
    domainId: 'domain-c1-2',
    objectiveId: '2.3',
    title: 'Summarize services provided by networked hosts',
    slug: '2-3-networked-host-services',
    description: 'Server roles: DNS, DHCP, file server, print server, web server, mail server, AAA, proxy, load balancer, IDS/IPS.',
    orderIndex: 3,
  },
  {
    id: 'topic-c1-2-4',
    domainId: 'domain-c1-2',
    objectiveId: '2.4',
    title: 'Explain common network configuration concepts',
    slug: '2-4-network-configuration',
    description: 'IP addressing (IPv4/IPv6), subnetting, CIDR, NAT, DNS, DHCP, VLANs, VPN.',
    orderIndex: 4,
  },
  {
    id: 'topic-c1-2-5',
    domainId: 'domain-c1-2',
    objectiveId: '2.5',
    title: 'Compare and contrast common networking hardware devices',
    slug: '2-5-networking-hardware',
    description: 'Routers, switches, hubs, WAPs, firewalls, modems, patch panels, PoE.',
    orderIndex: 5,
  },
  {
    id: 'topic-c1-2-6',
    domainId: 'domain-c1-2',
    objectiveId: '2.6',
    title: 'Configure basic wired and wireless SOHO networks',
    slug: '2-6-soho-networks',
    description: 'Router setup, SSID, WPA3, DHCP range, NAT/PAT, port forwarding, DMZ, content filtering.',
    orderIndex: 6,
  },
  {
    id: 'topic-c1-2-7',
    domainId: 'domain-c1-2',
    objectiveId: '2.7',
    title: 'Compare and contrast internet connection types and network characteristics',
    slug: '2-7-internet-connection-types',
    description: 'DSL, cable, fiber, satellite, cellular (4G/5G), fixed wireless, bandwidth vs latency.',
    orderIndex: 7,
  },
  {
    id: 'topic-c1-2-8',
    domainId: 'domain-c1-2',
    objectiveId: '2.8',
    title: 'Explain networking tools and their purposes',
    slug: '2-8-networking-tools',
    description: 'Cable tester, punchdown tool, toner probe, loopback plug, network tap, WiFi analyzer, Wireshark, ping, tracert, nslookup, netstat, ipconfig.',
    orderIndex: 8,
  },
  // Core 1 — Domain 3: Hardware
  {
    id: 'topic-c1-3-1',
    domainId: 'domain-c1-3',
    objectiveId: '3.1',
    title: 'Compare and contrast display components and attributes',
    slug: '3-1-display-components',
    description: 'LCD, IPS, TN, VA, OLED, resolution, refresh rate, response time, nit brightness, aspect ratio, connectors (HDMI, DP, DVI, VGA).',
    orderIndex: 1,
  },
  {
    id: 'topic-c1-3-2',
    domainId: 'domain-c1-3',
    objectiveId: '3.2',
    title: 'Summarize basic cable types, connectors, features, and purposes',
    slug: '3-2-cables-connectors',
    description: 'Network cables (Cat5e/Cat6/Cat6a/Cat7, coaxial, fiber), video cables (HDMI/DP/DVI/VGA), storage cables (SATA/SAS/NVMe), power connectors, USB types.',
    orderIndex: 2,
  },
  {
    id: 'topic-c1-3-3',
    domainId: 'domain-c1-3',
    objectiveId: '3.3',
    title: 'Compare and contrast RAM characteristics',
    slug: '3-3-ram-characteristics',
    description: 'DDR4 vs DDR5, SO-DIMM vs DIMM, ECC vs non-ECC, dual-channel, capacity, speed (MHz/MT/s), latency.',
    orderIndex: 3,
  },
  {
    id: 'topic-c1-3-4',
    domainId: 'domain-c1-3',
    objectiveId: '3.4',
    title: 'Compare and contrast storage devices',
    slug: '3-4-storage-devices',
    description: 'HDD vs SSD, SATA SSD vs NVMe M.2, form factors (2.5", 3.5", M.2), RAID levels (0/1/5/10), optical drives, flash storage.',
    orderIndex: 4,
  },
  {
    id: 'topic-c1-3-5',
    domainId: 'domain-c1-3',
    objectiveId: '3.5',
    title: 'Install and configure motherboards, CPUs, and add-on cards',
    slug: '3-5-motherboards-cpus',
    description: 'ATX/mATX/Mini-ITX form factors, CPU sockets (AM5, LGA1700), PCIe slots, chipsets, BIOS/UEFI, CMOS, front panel connectors, add-on cards (GPU, NIC, sound).',
    orderIndex: 5,
  },
  {
    id: 'topic-c1-3-6',
    domainId: 'domain-c1-3',
    objectiveId: '3.6',
    title: 'Install appropriate power supply',
    slug: '3-6-power-supply',
    description: 'Wattage calculations, 80 Plus efficiency ratings (Bronze/Silver/Gold/Platinum), modular vs non-modular, ATX connectors (24-pin, 8-pin EPS, PCIe 6/8-pin), voltage rails.',
    orderIndex: 6,
  },
  {
    id: 'topic-c1-3-7',
    domainId: 'domain-c1-3',
    objectiveId: '3.7',
    title: 'Deploy and configure multifunction devices/printers and settings',
    slug: '3-7-printers-mfds',
    description: 'Laser, inkjet, thermal, impact, 3D printers. Setup: drivers, IP printing, wireless, share via server or direct. Print settings: duplex, quality, media type, tray selection.',
    orderIndex: 7,
  },
  {
    id: 'topic-c1-3-8',
    domainId: 'domain-c1-3',
    objectiveId: '3.8',
    title: 'Perform appropriate printer maintenance',
    slug: '3-8-printer-maintenance',
    description: 'Laser: replace toner/drum/fuser, calibration, cleaning. Inkjet: replace cartridges, printhead cleaning. Thermal: replace paper/heating element. General: firmware updates.',
    orderIndex: 8,
  },
  // Core 1 — Domain 4: Virtualization and Cloud Computing
  {
    id: 'topic-c1-4-1',
    domainId: 'domain-c1-4',
    objectiveId: '4.1',
    title: 'Explain virtualization concepts',
    slug: '4-1-virtualization-concepts',
    description: 'Hypervisors (Type 1/Type 2), VMs vs containers, snapshots, resource allocation, vCPU/vRAM, virtual networking, benefits of virtualization.',
    orderIndex: 1,
  },
  {
    id: 'topic-c1-4-2',
    domainId: 'domain-c1-4',
    objectiveId: '4.2',
    title: 'Summarize cloud computing concepts',
    slug: '4-2-cloud-computing',
    description: 'IaaS, PaaS, SaaS, Public/Private/Hybrid/Community cloud, cloud characteristics (on-demand, scalability, elasticity, metered), shared responsibility model.',
    orderIndex: 2,
  },
  // Core 1 — Domain 1: Mobile Devices (objective 1.4 — display components)
  {
    id: 'topic-c1-1-4',
    domainId: 'domain-c1-1',
    objectiveId: '1.4',
    title: 'Compare and contrast mobile device display components',
    slug: '1-4-mobile-display-components',
    description: 'LCD vs OLED vs AMOLED, digitizer types (capacitive vs resistive), display layers, resolution, PPI, burn-in, common failures.',
    orderIndex: 4,
  },
  // Core 1 — Domain 5: Hardware and Network Troubleshooting
  {
    id: 'topic-c1-5-0',
    domainId: 'domain-c1-5',
    objectiveId: '5.0',
    title: 'Apply the best practice methodology to resolve problems',
    slug: '5-0-troubleshooting-methodology',
    description: "CompTIA's 6-step troubleshooting methodology: identify, theory, test, plan, verify, document. Applied to real scenarios.",
    orderIndex: 0,
  },
  {
    id: 'topic-c1-5-1',
    domainId: 'domain-c1-5',
    objectiveId: '5.1',
    title: 'Troubleshoot motherboards, RAM, CPUs, and power',
    slug: '5-1-troubleshoot-motherboard-ram-cpu-power',
    description: 'POST failures, beep codes, BIOS/UEFI errors, no boot, no video, RAM errors (BSOD, random reboots), CPU overheating, PSU failures.',
    orderIndex: 1,
  },
  {
    id: 'topic-c1-5-2',
    domainId: 'domain-c1-5',
    objectiveId: '5.2',
    title: 'Troubleshoot drive and RAID issues',
    slug: '5-2-troubleshoot-storage-raid',
    description: 'S.M.A.R.T. errors, drive not detected, slow performance, RAID degraded/failed arrays, data recovery basics, boot failures.',
    orderIndex: 2,
  },
  {
    id: 'topic-c1-5-3',
    domainId: 'domain-c1-5',
    objectiveId: '5.3',
    title: 'Troubleshoot video, projector, and display issues',
    slug: '5-3-troubleshoot-display',
    description: 'No image, flickering, artifacts, dead pixels, dim display, incorrect resolution, projector issues (no image, overheating, lamp replacement).',
    orderIndex: 3,
  },
  {
    id: 'topic-c1-5-4',
    domainId: 'domain-c1-5',
    objectiveId: '5.4',
    title: 'Troubleshoot common mobile device issues',
    slug: '5-4-troubleshoot-mobile',
    description: 'Battery drain, overheating, no WiFi/Bluetooth, touchscreen issues, app crashes, no cellular signal, water damage steps.',
    orderIndex: 4,
  },
  {
    id: 'topic-c1-5-5',
    domainId: 'domain-c1-5',
    objectiveId: '5.5',
    title: 'Troubleshoot network issues',
    slug: '5-5-troubleshoot-network',
    description: 'No connectivity, limited connectivity, APIPA (169.254.x.x), DNS failures, DHCP issues, slow throughput, WiFi interference, cable faults.',
    orderIndex: 5,
  },
  {
    id: 'topic-c1-5-6',
    domainId: 'domain-c1-5',
    objectiveId: '5.6',
    title: 'Troubleshoot printer issues',
    slug: '5-6-troubleshoot-printers',
    description: 'Print quality defects (lines, fading, smearing, ghosting), paper jams, offline printer, driver issues, print spooler, wireless printing failures.',
    orderIndex: 6,
  },
  // Core 2 — Domain 1: Operating Systems
  {
    id: 'topic-c2-1-1',
    domainId: 'domain-c2-1',
    objectiveId: '1.1',
    title: 'Explain common OS types and purposes',
    slug: '1-1-os-types',
    description: 'Workstation, server, mobile, IoT, embedded OS types. Windows, macOS, Linux, ChromeOS, Android, iOS use cases.',
    orderIndex: 1,
  },
  {
    id: 'topic-c2-1-2',
    domainId: 'domain-c2-1',
    objectiveId: '1.2',
    title: 'Perform OS installations and upgrades in diverse environments',
    slug: '1-2-os-installations-upgrades',
    description: 'Clean install vs upgrade, boot media (USB/optical/PXE/network), partition types (MBR/GPT), file systems (NTFS/FAT32/exFAT/ext4), post-install steps.',
    orderIndex: 2,
  },
  {
    id: 'topic-c2-1-3',
    domainId: 'domain-c2-1',
    objectiveId: '1.3',
    title: 'Compare and contrast basic features of Microsoft Windows editions',
    slug: '1-3-windows-editions',
    description: 'Windows 10/11 Home vs Pro vs Enterprise vs Education. BitLocker, domain join, Group Policy, Remote Desktop, Hyper-V, sandbox differences.',
    orderIndex: 3,
  },
  {
    id: 'topic-c2-1-4',
    domainId: 'domain-c2-1',
    objectiveId: '1.4',
    title: 'Use Microsoft Windows OS features and tools',
    slug: '1-4-windows-tools',
    description: 'Task Manager, Device Manager, Disk Management, Registry Editor, Event Viewer, System Configuration (msconfig), Services, Performance Monitor.',
    orderIndex: 4,
  },
  {
    id: 'topic-c2-1-5',
    domainId: 'domain-c2-1',
    objectiveId: '1.5',
    title: 'Use appropriate Microsoft command-line tools',
    slug: '1-5-windows-cli',
    description: 'ipconfig, ping, tracert, nslookup, netstat, nbtstat, net, diskpart, sfc, chkdsk, xcopy, robocopy, shutdown, gpupdate, gpresult.',
    orderIndex: 5,
  },
  {
    id: 'topic-c2-1-6',
    domainId: 'domain-c2-1',
    objectiveId: '1.6',
    title: 'Configure Microsoft Windows settings',
    slug: '1-6-windows-settings',
    description: 'Control Panel vs Settings app, System Properties, Display settings, Power plans, User Accounts, Windows Update, Defender settings.',
    orderIndex: 6,
  },
  {
    id: 'topic-c2-1-7',
    domainId: 'domain-c2-1',
    objectiveId: '1.7',
    title: 'Configure Microsoft Windows networking features on a client/desktop',
    slug: '1-7-windows-networking',
    description: 'Network adapter settings, HomeGroup/Workgroup/Domain, sharing permissions (share vs NTFS), VPN client, proxy settings, Windows Firewall.',
    orderIndex: 7,
  },
  {
    id: 'topic-c2-1-8',
    domainId: 'domain-c2-1',
    objectiveId: '1.8',
    title: 'Explain common features and tools of macOS/desktop OS',
    slug: '1-8-macos-features',
    description: 'Finder, Spotlight, Mission Control, Terminal, Disk Utility, FileVault, Gatekeeper, Time Machine, iCloud, System Preferences.',
    orderIndex: 8,
  },
  {
    id: 'topic-c2-1-9',
    domainId: 'domain-c2-1',
    objectiveId: '1.9',
    title: 'Identify common features and tools of Linux client/desktop OS',
    slug: '1-9-linux-features',
    description: 'Common distros (Ubuntu, Fedora), package managers (apt/yum/dnf), terminal commands (ls, cd, pwd, grep, chmod, chown, sudo), file system hierarchy.',
    orderIndex: 9,
  },
  {
    id: 'topic-c2-1-10',
    domainId: 'domain-c2-1',
    objectiveId: '1.10',
    title: 'Install applications according to requirements',
    slug: '1-10-application-installation',
    description: '32-bit vs 64-bit applications, installation methods, distribution methods, system requirements, impact on device (storage, performance).',
    orderIndex: 10,
  },
  {
    id: 'topic-c2-1-11',
    domainId: 'domain-c2-1',
    objectiveId: '1.11',
    title: 'Install and configure cloud-based productivity tools',
    slug: '1-11-cloud-productivity-tools',
    description: 'Microsoft 365, Google Workspace, collaboration tools (Teams, Slack), cloud storage (OneDrive, Google Drive), account setup and sync.',
    orderIndex: 11,
  },
  // Core 2 — Domain 2: Security
  {
    id: 'topic-c2-2-1',
    domainId: 'domain-c2-2',
    objectiveId: '2.1',
    title: 'Summarize various security measures and purposes',
    slug: '2-1-security-measures',
    description: 'Physical security (locks, badges, cameras, biometrics), logical security (MFA, passwords, encryption), principle of least privilege, zero trust.',
    orderIndex: 1,
  },
  {
    id: 'topic-c2-2-2',
    domainId: 'domain-c2-2',
    objectiveId: '2.2',
    title: 'Configure and apply basic Microsoft Windows OS security settings',
    slug: '2-2-windows-security-settings',
    description: 'User Account Control (UAC), Windows Defender, BitLocker, NTFS permissions, Local Security Policy, Windows Firewall rules.',
    orderIndex: 2,
  },
  {
    id: 'topic-c2-2-3',
    domainId: 'domain-c2-2',
    objectiveId: '2.3',
    title: 'Compare and contrast wireless security protocols and authentication methods',
    slug: '2-3-wireless-security',
    description: 'WEP (deprecated), WPA, WPA2 (CCMP/AES), WPA3 (SAE), 802.1X/RADIUS, EAP types, TKIP vs AES, enterprise vs personal mode.',
    orderIndex: 3,
  },
  {
    id: 'topic-c2-2-4',
    domainId: 'domain-c2-2',
    objectiveId: '2.4',
    title: 'Summarize types of malware and tools/methods for detection, removal, prevention',
    slug: '2-4-malware',
    description: 'Virus, worm, Trojan, ransomware, spyware, adware, rootkit, keylogger, botnet. Antivirus, anti-malware, recovery, prevention best practices.',
    orderIndex: 4,
  },
  {
    id: 'topic-c2-2-5',
    domainId: 'domain-c2-2',
    objectiveId: '2.5',
    title: 'Compare and contrast social engineering attacks, threats, and vulnerabilities',
    slug: '2-5-social-engineering',
    description: 'Phishing, spear phishing, whaling, vishing, smishing, tailgating, shoulder surfing, dumpster diving, impersonation. Defense strategies.',
    orderIndex: 5,
  },
  {
    id: 'topic-c2-2-6',
    domainId: 'domain-c2-2',
    objectiveId: '2.6',
    title: 'Implement procedures for basic SOHO malware removal',
    slug: '2-6-malware-removal',
    description: "CompTIA's 8-step malware removal process: identify, quarantine, disable System Restore, remediate, re-enable protection, patch/update, educate user, document.",
    orderIndex: 6,
  },
  {
    id: 'topic-c2-2-7',
    domainId: 'domain-c2-2',
    objectiveId: '2.7',
    title: 'Apply workstation security options and hardening techniques',
    slug: '2-7-workstation-hardening',
    description: 'Password policies, screen locks, OS patching, disabling unused services/ports, host-based firewall, antivirus, MDM, principle of least privilege.',
    orderIndex: 7,
  },
  {
    id: 'topic-c2-2-8',
    domainId: 'domain-c2-2',
    objectiveId: '2.8',
    title: 'Apply common methods for securing mobile devices',
    slug: '2-8-mobile-security',
    description: 'Screen lock types (PIN/pattern/biometric), remote wipe, MDM enrollment, app store policies, OS updates, VPN on mobile, full device encryption.',
    orderIndex: 8,
  },
  {
    id: 'topic-c2-2-9',
    domainId: 'domain-c2-2',
    objectiveId: '2.9',
    title: 'Compare and contrast data destruction and disposal methods',
    slug: '2-9-data-destruction',
    description: 'Overwriting (DoD 5220.22-M), low-level format, degaussing, shredding/incineration, certificate of destruction. When to use each method.',
    orderIndex: 9,
  },
  {
    id: 'topic-c2-2-10',
    domainId: 'domain-c2-2',
    objectiveId: '2.10',
    title: 'Apply security settings on SOHO wireless and wired networks',
    slug: '2-10-soho-network-security',
    description: 'Change default credentials, disable WPS, enable WPA3, SSID broadcast control, MAC filtering, guest networks, firewall rules, firmware updates.',
    orderIndex: 10,
  },
  {
    id: 'topic-c2-2-11',
    domainId: 'domain-c2-2',
    objectiveId: '2.11',
    title: 'Configure relevant security settings in a browser',
    slug: '2-11-browser-security',
    description: 'HTTPS, certificate errors, private browsing, extensions/plugins, pop-up blockers, certificate management, trusted sites, browser hardening.',
    orderIndex: 11,
  },
  // Core 2 — Domain 3: Software Troubleshooting
  {
    id: 'topic-c2-3-1',
    domainId: 'domain-c2-3',
    objectiveId: '3.1',
    title: 'Troubleshoot common Windows OS issues',
    slug: '3-1-troubleshoot-windows',
    description: 'BSOD (stop errors), slow boot, application crashes, Windows Update failures, corrupted profiles, registry errors, missing DLLs.',
    orderIndex: 1,
  },
  {
    id: 'topic-c2-3-2',
    domainId: 'domain-c2-3',
    objectiveId: '3.2',
    title: 'Troubleshoot common mobile OS and application issues',
    slug: '3-2-troubleshoot-mobile-os',
    description: 'App crashes, slow performance, OS update failures, storage full, synchronization issues, touchscreen problems, accessibility settings.',
    orderIndex: 2,
  },
  {
    id: 'topic-c2-3-3',
    domainId: 'domain-c2-3',
    objectiveId: '3.3',
    title: 'Troubleshoot common mobile OS and application security issues',
    slug: '3-3-troubleshoot-mobile-security',
    description: 'Unexpected data usage, fake security warnings, leaked credentials, unauthorized account access, app permissions, certificate errors on mobile.',
    orderIndex: 3,
  },
  {
    id: 'topic-c2-3-4',
    domainId: 'domain-c2-3',
    objectiveId: '3.4',
    title: 'Troubleshoot common personal computer security issues',
    slug: '3-4-troubleshoot-pc-security',
    description: 'Malware symptoms (slow PC, popups, redirects, high CPU), unauthorized access indicators, expired certificates, security alerts.',
    orderIndex: 4,
  },
  // Core 2 — Domain 4: Operational Procedures
  {
    id: 'topic-c2-4-1',
    domainId: 'domain-c2-4',
    objectiveId: '4.1',
    title: 'Implement best practices for documentation and support systems management',
    slug: '4-1-documentation',
    description: 'Network diagrams, asset inventory, knowledge base, change logs, incident documentation, ticketing systems, standard operating procedures (SOPs).',
    orderIndex: 1,
  },
  {
    id: 'topic-c2-4-2',
    domainId: 'domain-c2-4',
    objectiveId: '4.2',
    title: 'Apply change management procedures',
    slug: '4-2-change-management',
    description: 'Change request, approval process, risk assessment, rollback plan, testing, documentation, change window, CAB (Change Advisory Board).',
    orderIndex: 2,
  },
  {
    id: 'topic-c2-4-3',
    domainId: 'domain-c2-4',
    objectiveId: '4.3',
    title: 'Implement workstation backup and recovery methods',
    slug: '4-3-backup-recovery',
    description: 'Full vs incremental vs differential backup, 3-2-1 rule, cloud backup, System Restore, Windows Backup, Recovery Environment (WinRE), imaging.',
    orderIndex: 3,
  },
  {
    id: 'topic-c2-4-4',
    domainId: 'domain-c2-4',
    objectiveId: '4.4',
    title: 'Use common safety procedures',
    slug: '4-4-safety-procedures',
    description: 'ESD prevention (grounding, anti-static), proper lifting techniques, electrical safety (voltage hazards, UPS), fire safety, MSDS/SDS, PPE.',
    orderIndex: 4,
  },
  {
    id: 'topic-c2-4-5',
    domainId: 'domain-c2-4',
    objectiveId: '4.5',
    title: 'Summarize environmental impacts and local environment controls',
    slug: '4-5-environmental-controls',
    description: 'HVAC requirements, proper disposal (WEEE, e-waste, toner), power conditioning (surge protectors, UPS, line conditioners), temperature and humidity.',
    orderIndex: 5,
  },
  {
    id: 'topic-c2-4-6',
    domainId: 'domain-c2-4',
    objectiveId: '4.6',
    title: 'Explain prohibited content/activity, privacy, licensing, and policy concepts',
    slug: '4-6-policies-licensing',
    description: 'AUP, BYOD policy, DLP, PII handling, copyright, open source vs commercial licenses, EULA, illegal activities reporting chain of custody.',
    orderIndex: 6,
  },
  {
    id: 'topic-c2-4-7',
    domainId: 'domain-c2-4',
    objectiveId: '4.7',
    title: 'Use proper communication techniques and professionalism',
    slug: '4-7-professionalism',
    description: 'Active listening, clear communication, set expectations, follow up, avoid jargon with users, cultural sensitivity, proper escalation, avoid personal interruptions.',
    orderIndex: 7,
  },
  {
    id: 'topic-c2-4-8',
    domainId: 'domain-c2-4',
    objectiveId: '4.8',
    title: 'Explain basics of scripting',
    slug: '4-8-scripting',
    description: 'PowerShell, Python, Bash/shell, VBScript, JavaScript. Variables, loops, conditionals. Use cases: automation, user management, system monitoring.',
    orderIndex: 8,
  },
  {
    id: 'topic-c2-4-9',
    domainId: 'domain-c2-4',
    objectiveId: '4.9',
    title: 'Use remote access technologies',
    slug: '4-9-remote-access',
    description: 'RDP (port 3389), VNC, SSH (port 22), remote management tools (TeamViewer, AnyDesk), VPN, remote monitoring and management (RMM).',
    orderIndex: 9,
  },
  {
    id: 'topic-c2-4-10',
    domainId: 'domain-c2-4',
    objectiveId: '4.10',
    title: 'Explain basic concepts related to artificial intelligence',
    slug: '4-10-artificial-intelligence',
    description: 'Machine learning, large language models (LLMs), AI in IT support (chatbots, automation), AI-assisted diagnostics, responsible AI use, data privacy with AI.',
    orderIndex: 10,
  },
]
