// 72 flashcards for CompTIA A+ 220-1202 Core 2
// Covers Domain 2: Security (2.7–2.11) and Domain 3: Software Troubleshooting (3.1–3.4)

const NOW = new Date().toISOString()

export const BATCH6_FLASHCARDS = [

  // ─── 2.7 Workstation Hardening (8 cards) ─────────────────────────────────

  {
    id: 'fc-c2-2-7-01',
    topicId: 'topic-c2-2-7',
    front: 'What are the recommended account lockout policy values for workstation hardening?',
    back: 'Lockout threshold: 3–5 failed login attempts.\nLockout duration: 30 minutes before automatic unlock.\nLockout observation window: 30 minutes — resets the failed-attempt counter.\n\nAn administrator can manually unlock an account before the duration expires. These settings are configured in Local Security Policy (secpol.msc) on standalone machines or via Group Policy (GPO) on domain-joined machines.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-7-02',
    topicId: 'topic-c2-2-7',
    front: 'What is the difference between traditional antivirus and EDR?',
    back: 'Antivirus (AV): signature-based detection. Compares files against a database of known-bad file hashes. Catches known malware; misses novel threats with no existing signature.\n\nEDR (Endpoint Detection and Response): behavioral analysis. Monitors what processes actually do — not just what they are. Detects fileless malware, living-off-the-land attacks, and lateral movement. Records telemetry for forensic investigation. Examples: CrowdStrike Falcon, Microsoft Defender for Endpoint.\n\nEDR is the enterprise replacement for legacy AV.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-7-03',
    topicId: 'topic-c2-2-7',
    front: 'What is WSUS and why do enterprises use it instead of direct Windows Update?',
    back: 'WSUS (Windows Server Update Services) is an enterprise server that centralizes Windows update management. IT administrators approve, schedule, and deploy updates to machines across the organization — machines check WSUS instead of going directly to Microsoft.\n\nBenefits:\n• Bandwidth management — updates download once to WSUS, then distributed internally\n• Controlled rollouts — IT tests updates before deploying organization-wide\n• Compliance reporting — shows which machines are patched\n• Prevents machines from individually reaching out to the internet for updates',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-7-04',
    topicId: 'topic-c2-2-7',
    front: 'Why should SMBv1, Telnet, and FTP be disabled on workstations?',
    back: 'SMBv1: legacy file-sharing protocol exploited by WannaCry and NotPetya ransomware to propagate across networks. No modern scenario requires SMBv1 — disable it.\n\nTelnet: transmits all data, including credentials, in plaintext. Any network observer can read the session. Replaced by SSH (encrypted).\n\nFTP: same problem — plaintext credentials and data transfer. Replaced by SFTP (SSH-based) or HTTPS file transfer.\n\nEvery running service is a potential attack vector. Services not required for the machine\'s function should be stopped and set to Disabled — not just stopped.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-7-05',
    topicId: 'topic-c2-2-7',
    front: 'What is AppLocker and how does it differ from Software Restriction Policies?',
    back: 'AppLocker: Windows Enterprise/Education Group Policy feature that creates allowlists defining which executables, scripts, installers, and DLLs are permitted to run. Rules can be based on publisher (digital signature), file path, or file hash. Even if malware is delivered to the machine, it cannot execute if it is not on the allowlist.\n\nSoftware Restriction Policies (SRP): older Group Policy mechanism compatible with all Windows editions. Less granular — no publisher rules, no DLL control.\n\nKey difference: AppLocker is more granular and reliable; SRP is the legacy alternative for non-Enterprise editions.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-7-06',
    topicId: 'topic-c2-2-7',
    front: 'What are the three Windows Defender Firewall network profiles and when does each apply?',
    back: 'Domain: applies when the machine is joined to and can communicate with its Active Directory domain. Corporate network context.\n\nPrivate: applies when connected to a network the user has designated as trusted (home network, small office).\n\nPublic: applies on untrusted networks — airports, hotels, coffee shops. Most restrictive. Blocks all unsolicited inbound connections.\n\nDefault behavior for all profiles: block all unsolicited inbound, allow all outbound. Windows automatically selects the profile based on network type detection.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-7-07',
    topicId: 'topic-c2-2-7',
    front: 'What is BitLocker, what does it require, and where should the recovery key be stored?',
    back: 'BitLocker is Windows full-disk encryption built into Pro and Enterprise editions. It encrypts the entire drive so that data is unreadable without the correct credentials — protecting data if a device is physically stolen.\n\nRequirements: TPM 1.2+ chip (preferred) OR a USB key to hold the startup key. TPM validates that system hardware has not been tampered with.\n\nRecovery key storage: Active Directory, Azure AD, or a separate secure offline location. Never store the recovery key on the encrypted drive itself — if you lose access to the drive, you lose the key too.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-7-08',
    topicId: 'topic-c2-2-7',
    front: 'What is Secure Boot, what does it prevent, and what firmware type is required?',
    back: 'Secure Boot is a UEFI firmware feature that verifies the digital signature of the bootloader before executing it. If the bootloader\'s signature does not match a trusted key stored in the UEFI firmware, boot is halted.\n\nPrevents: rootkits and bootkits from loading unsigned bootloaders at system start, before the OS or any security software loads.\n\nRequirements: UEFI firmware (not legacy BIOS), and the OS must be signed by a trusted key (Windows, most Linux distributions). Legacy BIOS systems cannot use Secure Boot.\n\nAlways pair Secure Boot with a UEFI supervisor password to prevent an attacker from simply disabling it in firmware settings.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.8 Mobile Security (8 cards) ──────────────────────────────────────

  {
    id: 'fc-c2-2-8-01',
    topicId: 'topic-c2-2-8',
    front: 'Why are pattern locks considered a weak screen lock method?',
    back: 'Pattern locks are vulnerable to smudge attacks. The oils from your fingertip leave a residue trace on the screen that closely follows the unlock pattern. An attacker holding the phone at an angle under light can read the pattern without any technical tools.\n\nThe 3x3 grid also limits the number of meaningful patterns — many users choose simple shapes (L, Z, diagonal) that are guessable.\n\nFor corporate devices, require at minimum a 6-digit PIN (1,000,000 combinations) or an alphanumeric password. A 4-digit PIN has only 10,000 combinations — too easily brute-forced if device protections are bypassed.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-8-02',
    topicId: 'topic-c2-2-8',
    front: 'What is the difference between a full MDM wipe and a selective wipe?',
    back: 'Full wipe: erases the entire device including the OS — returns it to factory state. Removes all personal and corporate data. Used when a device is lost, stolen, or decommissioned.\n\nSelective wipe: removes only the corporate data and MDM management profiles, leaving the user\'s personal data (photos, personal apps, contacts) intact. Critical for BYOD environments — employees are more willing to enroll personal devices if IT cannot erase their personal photos.\n\nSelective wipe is the technical implementation of "containerization" — separating corporate data from personal data so only the corporate portion is wiped.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-8-03',
    topicId: 'topic-c2-2-8',
    front: 'What is the Android Work Profile and what problem does it solve?',
    back: 'Android Work Profile creates a separate, isolated environment on the device visible as a second set of app icons with a briefcase badge. Work apps run inside this profile; personal apps run outside it.\n\nIT management scope: the MDM manages only the work profile — personal apps, messages, and photos are completely invisible to IT.\n\nSelective wipe removes only the work profile (all corporate apps and data) without touching personal data.\n\nThis solves the BYOD privacy challenge: employees allow MDM enrollment because they know IT can only see and wipe the work side of the device.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-8-04',
    topicId: 'topic-c2-2-8',
    front: 'What is sideloading and why is it a security risk on Android?',
    back: 'Sideloading is installing an APK (Android application package) from outside the official Google Play Store, enabled by turning on "Install unknown apps" in Android settings.\n\nRisks:\n• No security review — Google vets Play Store apps for malware; sideloaded apps bypass this entirely\n• No automatic updates — no security patches are delivered\n• Common vector for banking trojans, stalkerware, and spyware disguised as popular apps\n• Users often grant excessive permissions without scrutiny to get the app working\n\nBest practice: keep "Install unknown apps" disabled on all corporate devices. MDM can enforce this and detect if the setting is changed.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-8-05',
    topicId: 'topic-c2-2-8',
    front: 'What is the difference between jailbreaking (iOS) and rooting (Android)?',
    back: 'Jailbreaking (iOS): exploits iOS kernel vulnerabilities to remove Apple\'s code-signing restrictions. Allows installing unsigned apps from outside the App Store, accessing the full filesystem, and potentially removing MDM profiles.\n\nRooting (Android): gains root (superuser) access to the Android OS. Allows modifying system files, bypassing the app sandbox, and defeating security controls.\n\nShared risks of both:\n• Removes OS-level sandboxing — any app can access any data\n• MDM profiles may be removable by the user\n• Security patches may not apply cleanly to modified OS\n• Voids manufacturer warranty\n\nMDM platforms detect jailbreak/root status and can block or quarantine these devices.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-8-06',
    topicId: 'topic-c2-2-8',
    front: 'What is a SIM swap attack and why does it defeat SMS-based MFA?',
    back: 'A SIM swap attack is a social engineering attack where the attacker contacts the victim\'s mobile carrier, impersonates them using personal information (often gathered from data breaches or social media), and convinces the carrier to transfer the victim\'s phone number to a SIM card the attacker controls.\n\nOnce the number is transferred, the attacker receives all SMS messages sent to that number — including MFA one-time codes. This allows account takeover even when MFA is enabled.\n\nDefense: replace SMS-based MFA with an authenticator app (Google Authenticator, Authy, Microsoft Authenticator) or a hardware security key (FIDO2/YubiKey). These are bound to the physical device or key, not the phone number.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-8-07',
    topicId: 'topic-c2-2-8',
    front: 'What is the difference between per-app VPN, always-on VPN, and split tunneling?',
    back: 'Per-app VPN: only traffic from specified corporate apps is tunneled through the VPN. Personal browsing and other apps go directly to the internet. Common in enterprise MDM configurations — reduces VPN load and protects corporate traffic only.\n\nAlways-on VPN: all traffic from the device routes through VPN at all times. Maximum security for corporate data; increases latency and battery consumption.\n\nSplit tunneling: a VPN mode where corporate traffic goes through the VPN tunnel and internet traffic goes directly to the internet. Reduces VPN server load but means internet traffic bypasses corporate security controls.\n\nIKEv2 is the most common VPN protocol for mobile — reconnects quickly when switching between Wi-Fi and cellular.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-8-08',
    topicId: 'topic-c2-2-8',
    front: 'What is bluesnarfing and how does it differ from bluejacking?',
    back: 'Bluejacking: sending unsolicited Bluetooth messages (contacts, messages) to a nearby device. Annoying but not harmful — no data is taken from the victim\'s device. More of a nuisance attack.\n\nBluesnarfing: unauthorized access to data on a victim\'s device via a Bluetooth exploit. The attacker can read contacts, calendar entries, emails, and other data without the user\'s knowledge or consent. A true data theft attack.\n\nKey distinction: Bluejacking pushes data TO a device; Bluesnarfing pulls data FROM a device.\n\nDefense for both: disable Bluetooth when not actively in use. Keep mobile OS patched — bluesnarfing exploits specific Bluetooth protocol vulnerabilities.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.9 Data Destruction (8 cards) ──────────────────────────────────────

  {
    id: 'fc-c2-2-9-01',
    topicId: 'topic-c2-2-9',
    front: 'Why is standard file deletion or OS reinstallation insufficient for data destruction?',
    back: 'When a file is "deleted," the operating system marks the storage sectors as available for reuse but does not erase the underlying data. The data remains intact until those sectors are overwritten by new content.\n\nAn OS reinstallation formats the drive, which may overwrite some data but does not guarantee every sector is cleared — particularly on HDDs where the format creates a new filesystem structure without necessarily writing to all data sectors.\n\nRecovery tools (Recuva, PhotoRec, commercial forensic tools) can reconstruct deleted files from these uncleared sectors. Proper data destruction must actively overwrite or physically destroy the data to prevent recovery.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-9-02',
    topicId: 'topic-c2-2-9',
    front: 'Why does software overwriting fail for SSDs, and what method should be used instead?',
    back: 'SSDs use wear leveling — the SSD controller distributes writes evenly across flash cells to prevent any single cell from wearing out prematurely. When you issue an overwrite command, the controller writes to fresh cells and marks the old ones for future use. The original data remains in those old cells, unreachable by the OS but still physically present.\n\nThis means overwriting commands (including 7-pass DoD wiping) cannot guarantee all data is erased on an SSD.\n\nCorrect methods for SSDs:\n• ATA Secure Erase: built-in drive command that tells the controller to reset ALL cells (including spares) to factory state\n• Cryptographic wipe: if the drive was encrypted, destroy the key — the ciphertext becomes permanently unreadable\n• Physical destruction: shredding, drilling, or incineration',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-9-03',
    topicId: 'topic-c2-2-9',
    front: 'What is degaussing, what media types does it work on, and what is a critical side effect?',
    back: 'Degaussing uses an extremely powerful magnetic field to randomize the magnetic domains on storage media, permanently destroying the data.\n\nEffective on: HDDs, magnetic tape (LTO, DLT), floppy disks — any magnetic storage media.\n\nNOT effective on: SSDs, NVMe drives, USB flash drives, SD cards, optical media (CD/DVD/Blu-ray). These store data electronically, not magnetically — there are no magnetic domains to disrupt.\n\nCritical side effect: degaussing permanently destroys the HDD servo tracks used by the drive controller to position the read/write head. A degaussed HDD cannot be reformatted, repartitioned, or reused in any way — it is physically destroyed as a functional drive. This is a frequently tested exam point.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-9-04',
    topicId: 'topic-c2-2-9',
    front: 'What is a cryptographic wipe (crypto erase) and what is the key requirement for it to work?',
    back: 'Cryptographic wipe destroys data by deleting or destroying the encryption key that protects it. The encrypted data remains physically on the drive, but without the key, it is mathematically unrecoverable — indistinguishable from random noise.\n\nSpeed: nearly instantaneous — no need to overwrite every sector.\n\nKey requirement: the drive MUST have been encrypted BEFORE the data was written. You cannot retroactively encrypt plaintext data and call it erased — the plaintext already exists on the drive sectors and must be physically overwritten.\n\nUse cases: BitLocker (delete key protectors), Self-Encrypting Drives (SED crypto erase command), iOS/Android factory reset (destroys the hardware-bound encryption key), cloud storage (delete the KMS key).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-9-05',
    topicId: 'topic-c2-2-9',
    front: 'What are the three NIST SP 800-88 data sanitization categories?',
    back: 'Clear: overwrites data using standard read/write operations. Protects against casual or non-laboratory recovery. Example: single or multi-pass software overwrite. Appropriate for lower-sensitivity scenarios where data will not be subjected to forensic analysis.\n\nPurge: applies more advanced techniques resistant to laboratory attack. Examples: ATA Secure Erase, degaussing, cryptographic erase. Appropriate for sensitive data.\n\nDestroy: physical destruction so the media cannot be reused. Examples: shredding, incineration, disintegration. Absolute — provides the highest assurance. Required for classified/top-secret data.\n\nMemory tip: Clear → Purge → Destroy increases in both assurance and irreversibility.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-9-06',
    topicId: 'topic-c2-2-9',
    front: 'What is a Certificate of Destruction and why is it required?',
    back: 'A Certificate of Destruction (CoD) is a formal document issued by a destruction vendor confirming that specific devices were destroyed by a specific method on a specific date.\n\nContents: organization name, device make/model/serial numbers, date of destruction, method used, vendor name and certification, signature of the person who performed or witnessed destruction.\n\nWhy it matters:\n• Required evidence for compliance audits — HIPAA, PCI DSS, GDPR, SOX all require documented proof of proper disposal\n• Demonstrates due diligence if a data breach investigation occurs\n• Provides chain-of-custody documentation from pickup to completion\n\nFor the exam: a Certificate of Destruction is required documentation, not optional paperwork.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-9-07',
    topicId: 'topic-c2-2-9',
    front: 'Which data destruction methods work on ALL storage media types, and which are media-specific?',
    back: 'Works on ALL media types:\n• Physical shredding — reduces any media to fragments too small to reconstruct\n• Incineration — destroys any media type at sufficient temperature\n\nMedia-specific limitations:\n• Degaussing: ONLY magnetic media (HDD, tape). NOT SSDs, flash, optical\n• Software overwriting: reliable on HDDs; NOT reliable on SSDs/flash (wear leveling)\n• ATA Secure Erase: works on HDDs and SSDs; N/A for optical or tape\n• Cryptographic wipe: requires prior encryption; works on any encrypted media\n\nWhen in doubt about SSD or mixed media: use ATA Secure Erase, cryptographic wipe, or physical destruction.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-9-08',
    topicId: 'topic-c2-2-9',
    front: 'A regulated healthcare organization is retiring 50 laptops with HDDs. What is the correct destruction process?',
    back: 'Scenario: HIPAA-regulated PHI on magnetic HDDs, organization must document compliance.\n\nCorrect process:\n1. Perform ATA Secure Erase or 7-pass DoD overwrite on each HDD (NIST Purge level) — makes data unrecoverable from laboratory analysis\n2. OR skip software methods and proceed directly to physical destruction (shredding) for highest assurance\n3. Engage a certified destruction vendor who will shred the drives and issue a Certificate of Destruction with serial numbers for each drive\n4. Retain the Certificate of Destruction as compliance evidence for HIPAA audits\n\nHIPAA requires covered entities to "purge" or physically destroy PHI before disposal and document the process. The CoD is the documentation required.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.10 SOHO Network Security (8 cards) ────────────────────────────────

  {
    id: 'fc-c2-2-10-01',
    topicId: 'topic-c2-2-10',
    front: 'Why is changing a router\'s default admin credentials the single most important hardening step?',
    back: 'Default usernames and passwords (admin/admin, admin/password, admin/1234) are publicly documented for every router model and are immediately exploited by automated internet scanners within minutes of a router going online.\n\nAn attacker with router admin access can:\n• Redirect DNS queries to malicious servers (DNS hijacking)\n• Open port forwarding to internal devices\n• Disable the firewall\n• Intercept all network traffic\n\nThe admin password should be strong and unique — different from the Wi-Fi passphrase. Remote administration from the WAN (internet) side should also be disabled; admin access should only be available from the internal network.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-10-02',
    topicId: 'topic-c2-2-10',
    front: 'Compare WEP, WPA2-AES, and WPA3 wireless encryption standards.',
    back: 'WEP (Wired Equivalent Privacy): broken — uses RC4 cipher with fundamental design flaws. Cracked in minutes with freely available tools. Deprecated in 2004. Never use.\n\nWPA2-AES (CCMP): uses AES encryption — still strong. Most widely deployed standard. Vulnerable to offline dictionary attacks if the pre-shared key (PSK) handshake is captured.\n\nWPA3: uses SAE (Simultaneous Authentication of Equals) instead of PSK handshake. Key advantage: even if an attacker captures the SAE handshake, it cannot be cracked offline — each authentication attempt requires online interaction. Also provides forward secrecy. Best option when available.\n\nAlways choose AES (CCMP) over TKIP when configuring WPA2 — TKIP has known vulnerabilities and is deprecated.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-10-03',
    topicId: 'topic-c2-2-10',
    front: 'What is the WPS vulnerability and how is it exploited?',
    back: 'WPS (Wi-Fi Protected Setup) was designed for easy device pairing using an 8-digit PIN. It has a fundamental design flaw: the PIN is validated in two halves (first 4 digits, then last 4 digits) separately — reducing attack combinations from 100,000,000 to just 11,000.\n\nExploit: tools like Reaver brute-force the WPS PIN in under 24 hours. Once the PIN is cracked, the tool retrieves the full WPA2 passphrase automatically — bypassing even a strong 20-character passphrase entirely.\n\nFix: disable WPS completely. There is no patch — the flaw is in the design of the protocol. Verify it is actually disabled; some routers require a reboot and may re-enable WPS after firmware updates.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-10-04',
    topicId: 'topic-c2-2-10',
    front: 'Does hiding the SSID provide meaningful wireless security? Why or why not?',
    back: 'No. SSID hiding is security through obscurity — it provides a minor inconvenience, not real protection.\n\nWhy it fails: even when a network does not broadcast its SSID, it can be discovered using passive Wi-Fi scanning tools that detect probe requests. When a client device that previously connected to the hidden network roams away and searches for it, it broadcasts the SSID in probe requests — revealing the name to any attacker with a Wi-Fi scanner.\n\nAdditionally, hidden SSIDs cause connectivity issues for legitimate users.\n\nBest practice: keep SSID broadcast enabled and rely on WPA3 with a strong passphrase for actual security. Changing the SSID from the default router-brand name (which reveals the device model) is a worthwhile step.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-10-05',
    topicId: 'topic-c2-2-10',
    front: 'What is a guest network and why should IoT devices be placed on it?',
    back: 'A guest network is a separate SSID running on its own VLAN, isolated from the main internal network. Devices on the guest network can reach the internet but cannot communicate with devices on the main network (file servers, printers, NAS, workstations).\n\nWhy IoT devices belong on the guest network:\n• IoT devices (smart TVs, thermostats, cameras, smart bulbs) often run unpatched firmware with hardcoded credentials\n• Many IoT devices are frequent botnet targets (Mirai botnet used IoT devices)\n• Isolating IoT limits the blast radius — a compromised smart thermostat cannot reach business files or internal servers\n• IoT devices rarely need to communicate with other internal computers\n\nBandwidth throttling can also be applied to the guest SSID to prevent guests from saturating the connection.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-10-06',
    topicId: 'topic-c2-2-10',
    front: 'What is port triggering and how does it differ from static port forwarding?',
    back: 'Static port forwarding: a permanent rule that always forwards an external port to a specific internal IP:port combination. The port remains open 24/7 regardless of whether any internal device is actively using it. Lower security — the port is a continuous attack surface.\n\nPort triggering: a dynamic rule that opens an external port temporarily only when outbound trigger traffic is detected from an internal device. The port closes after a timeout when not in use.\n\nKey differences:\n• Port triggering: more secure (port only open when in use); supports multiple devices triggering the same port sequentially\n• Static forwarding: required for servers that must accept connections at any time; limited to one internal IP\n\nUse port triggering for gaming and applications that need temporary inbound access; use static forwarding for permanent services like web servers.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-10-07',
    topicId: 'topic-c2-2-10',
    front: 'What is UPnP, why should it be disabled on SOHO routers, and what is the DMZ?',
    back: 'UPnP (Universal Plug and Play): allows devices on the network to automatically create port forwarding rules on the router without manual configuration. Convenient for gaming consoles and media devices — but malware can also abuse UPnP to open inbound ports, creating a backdoor the attacker controls. Disable UPnP unless a specific application requires it.\n\nDMZ (Demilitarized Zone): places a single device outside the router\'s firewall — all unsolicited inbound ports and protocols are forwarded to it. The device is fully exposed to internet traffic.\n\nDMZ use case: game consoles (to avoid NAT issues), or web/mail servers requiring unrestricted inbound connections. Risk: a compromised DMZ device gives the attacker a foothold inside the network. Prefer specific port forwarding rules over full DMZ exposure when possible.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-10-08',
    topicId: 'topic-c2-2-10',
    front: 'What is MAC address filtering and why is it considered a weak security control?',
    back: 'MAC address filtering creates an allowlist of hardware (MAC) addresses permitted to associate with the wireless network. The router rejects connection attempts from MACs not on the list.\n\nWhy it is weak: MAC addresses can be trivially spoofed on any operating system in seconds. An attacker:\n1. Passively monitors the network with a Wi-Fi adapter in monitor mode\n2. Captures the MAC address of a legitimate connected device from its traffic\n3. Sets their own adapter\'s MAC to match the legitimate device\'s MAC\n4. Connects to the network\n\nMAC filtering adds minor friction (a small additional step for the attacker) but provides no meaningful security against any determined attacker. It does not substitute for strong WPA3 encryption and a strong passphrase.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.11 Browser Security (8 cards) ─────────────────────────────────────

  {
    id: 'fc-c2-2-11-01',
    topicId: 'topic-c2-2-11',
    front: 'What does HTTPS protect, and what does it NOT protect against?',
    back: 'HTTPS (HTTP over TLS) encrypts all data in transit between the browser and the server. It also authenticates the server identity — the TLS certificate proves you are talking to the legitimate domain, not an impersonator.\n\nProtects: login credentials, form data, page content from eavesdropping in transit. Prevents network observers (ISP, Wi-Fi eavesdroppers) from reading the data.\n\nDoes NOT protect against:\n• Server-side breaches — if the server is hacked, your data is exposed regardless of HTTPS\n• Malware on your device — a keylogger captures keystrokes before HTTPS encrypts them\n• Phishing sites — a phishing site can have a valid HTTPS certificate (TLS proves the domain is who it says it is, not that the domain is trustworthy)\n\nHTTPS uses port 443; HTTP uses port 80.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-11-02',
    topicId: 'topic-c2-2-11',
    front: 'What are the five TLS certificate error types and the correct user action for each?',
    back: 'Expired certificate: certificate validity period has passed. Action: do not proceed; site owner must renew.\n\nSelf-signed certificate: not issued by a trusted CA. Action: safe only for known internal servers; never on the public internet.\n\nHostname mismatch: certificate issued for a different domain. Action: possible MITM attack or misconfiguration — do not proceed.\n\nUntrusted CA: issuing CA not in the browser\'s trusted root store. Action: do not proceed unless you know the CA (e.g., internal corporate CA deployed via GPO).\n\nRevoked certificate: CA explicitly revoked the certificate. Action: do not proceed — the site may be compromised.\n\nGeneral rule: never click through certificate errors on sites handling sensitive data. A certificate error means the server\'s identity cannot be verified.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-11-03',
    topicId: 'topic-c2-2-11',
    front: 'What does private/incognito browsing actually do, and what does it NOT do?',
    back: 'What it DOES:\n• Prevents saving browsing history on the local device\n• Deletes cookies and session data when the window is closed\n• Does not save form data or autofill entries\n• Does not record downloads in the browser download history (files still exist on disk)\n\nWhat it does NOT do:\n• Does NOT hide traffic from your ISP — they still see your DNS queries and IP connections\n• Does NOT hide traffic from your employer on a corporate network\n• Does NOT make you anonymous to websites — they see your IP address\n• Does NOT protect against malware or keyloggers on the device\n• Does NOT encrypt your connection — use HTTPS and VPN for that\n\nPrivate browsing is only local storage privacy, not network anonymity. This is the most commonly misunderstood browser security feature.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-11-04',
    topicId: 'topic-c2-2-11',
    front: 'What is the difference between first-party cookies, third-party cookies, and session cookies?',
    back: 'Session cookie: maintains login state for the current visit only. Stored in memory — deleted when the browser closes. Lowest privacy impact.\n\nFirst-party cookie: set by the website you are actually visiting. Used for preferences, login state, shopping cart. Relatively low privacy impact.\n\nThird-party cookie: set by embedded content from other domains (ad networks, tracking pixels) on the site you visit. A single ad network\'s cookie can follow you across hundreds of unrelated websites — a news site, a shopping site, a social media site — building a profile of your browsing behavior. GDPR requires consent for non-essential cookies. Most modern browsers are blocking or phasing out third-party cookies by default.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-11-05',
    topicId: 'topic-c2-2-11',
    front: 'What security risks do browser extensions pose, and what is the danger of legacy plugins (Flash, Java)?',
    back: 'Extensions: run with broad permissions — an extension with "Read and change all your data on all websites" can read every page you visit including banking and email, intercept credentials, and exfiltrate data. Malicious extensions disguised as ad-blockers or utilities are a common attack vector.\n\nBest practice: install only from official extension stores; review permissions carefully; keep the number of extensions minimal; audit periodically.\n\nLegacy plugins — Flash and Java browser plugin: both are end-of-life. Flash was officially killed in December 2020. Java plugin was removed from modern browsers. Both had massive attack surfaces and were responsible for countless zero-day exploits delivered via malicious web pages.\n\nAction: disable or uninstall both from all browsers. If a site requires Flash or Java, it is either outdated or malicious.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-11-06',
    topicId: 'topic-c2-2-11',
    front: 'What are Microsoft SmartScreen and Google Safe Browsing, and why should they remain enabled?',
    back: 'Both are real-time threat protection systems built into their respective browsers that check URLs and downloaded files against maintained databases of known malicious content.\n\nMicrosoft SmartScreen (Edge): checks URLs against Microsoft\'s phishing and malware URL database. Also checks downloaded file hashes against known-malicious file signatures. Shows a warning page before loading dangerous URLs and warns before running suspicious executables.\n\nGoogle Safe Browsing (Chrome, Firefox, Safari): same concept — blocklist of phishing sites, malware download pages, and unwanted software URLs. Updated multiple times per day.\n\nBoth are enabled by default and should not be disabled. Performance overhead is negligible. They block significant real-world threats including phishing links and drive-by malware downloads.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-11-07',
    topicId: 'topic-c2-2-11',
    front: 'What is a browser hijacker, what are the symptoms, and what is the removal procedure?',
    back: 'Browser hijacking occurs when malware or a malicious extension modifies browser settings without user consent.\n\nSymptoms:\n• Homepage changed to an unknown site\n• Default search engine changed (searches redirect to unfamiliar engine)\n• Unknown extensions installed\n• Constant redirects to unrelated sites\n• Excessive pop-up advertisements even on trusted sites\n\nRemoval procedure:\n1. Remove unrecognized extensions from browser extension settings\n2. Run Windows Defender or Malwarebytes full scan to find the underlying adware/PUP\n3. Reset browser settings to defaults (Chrome: Settings → Reset settings → Restore settings to original defaults)\n4. Clear all cookies and cache\n5. Verify homepage and search engine are correct after reset\n6. Check Task Scheduler and msconfig Startup tab for entries that reinstall the hijacker on each boot',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-11-08',
    topicId: 'topic-c2-2-11',
    front: 'How does a password manager\'s domain matching protect against phishing, and what is the autofill hidden field attack?',
    back: 'Domain matching as phishing defense: password managers autofill credentials only on the exact domain they are saved for. If credentials are saved for paypal.com and the user lands on paypa1.com (phishing site), the password manager will not autofill — alerting the user that something is wrong. The human eye may miss the character substitution; the password manager\'s domain matching catches it.\n\nAutofill hidden field attack: malicious web pages include hidden form fields invisible to the user. When autofill populates visible fields (name, email), it may also populate hidden fields (phone number, address, credit card) that are silently submitted without the user seeing them being filled.\n\nMitigation: disable browser autofill for sensitive data (credit cards, addresses) in browser settings. Use a dedicated password manager with domain-matching instead of browser autofill for sensitive data.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.1 Troubleshoot Windows OS (8 cards) ───────────────────────────────

  {
    id: 'fc-c2-3-1-01',
    topicId: 'topic-c2-3-1',
    front: 'What are the common BSOD stop codes and what does each indicate?',
    back: 'IRQL_NOT_LESS_OR_EQUAL: driver tried to access memory at too high an interrupt level — usually a bad or incompatible driver.\n\nMEMORY_MANAGEMENT: RAM problem — bad stick, bad slot, or Windows memory subsystem error. If it happens after a set time, test RAM sticks one at a time.\n\nCRITICAL_PROCESS_DIED: a core Windows process (csrss.exe, winlogon.exe) terminated unexpectedly.\n\nSYSTEM_SERVICE_EXCEPTION: unhandled exception in a system service — often a driver or antivirus.\n\nPAGE_FAULT_IN_NONPAGED_AREA: memory access to an area not paged in — hardware or driver failure.\n\nKERNEL_SECURITY_CHECK_FAILURE: corrupted kernel data — hardware failure or damaged system files.\n\nDiagnosis: disable automatic restart to capture the stop code; read the minidump in C:\\Windows\\Minidump\\ using WinDbg to identify the faulting module.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-1-02',
    topicId: 'topic-c2-3-1',
    front: 'What is the correct order to run DISM and sfc, and why does the order matter?',
    back: 'Correct order: run DISM first, then sfc.\n\nDISM /Online /Cleanup-Image /RestoreHealth: repairs the Windows component store by downloading correct replacement files from Windows Update. The component store is the source sfc uses to replace corrupted files.\n\nsfc /scannow: scans all protected Windows system files and replaces corrupted/missing ones by sourcing replacements from the component store.\n\nWhy order matters: if the component store is corrupted, sfc cannot repair itself — it has nothing to source the replacement files from. Running sfc first on a corrupted component store will report "found errors but could not repair them." Running DISM first fixes the component store, then sfc can successfully repair system files.\n\nResults logged to: C:\\Windows\\Logs\\CBS\\CBS.log',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-1-03',
    topicId: 'topic-c2-3-1',
    front: 'What are the bootrec commands used in boot recovery, and when is each used?',
    back: 'bootrec /fixmbr: writes a new Master Boot Record to the system disk. Use when MBR is corrupted or overwritten.\n\nbootrec /fixboot: writes a new boot sector to the active partition. Use when the partition boot sector is damaged.\n\nbootrec /scanos: scans all disks for Windows installations not listed in the BCD store.\n\nbootrec /rebuildbcd: rebuilds the Boot Configuration Data from scratch after scanning for Windows installations. Use when BCD is missing or corrupt.\n\nTypical MBR/BIOS sequence: fixmbr → fixboot → rebuildbcd → reboot\nTypical UEFI/GPT sequence: rebuildbcd → fixboot → reboot\n\nAll bootrec commands are run from the WinRE Command Prompt. Access WinRE by booting from Windows media and choosing "Repair your computer," or by interrupting boot 3 times.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-1-04',
    topicId: 'topic-c2-3-1',
    front: 'How do you fix a corrupted user profile in Windows?',
    back: 'Symptoms of corrupted profile: settings that don\'t save between logins, blank desktop on login, "You\'ve been signed in with a temporary profile" warning, or application settings reverting constantly.\n\nCause: the profile registry hive (NTUSER.DAT) or profile folder became corrupted — often from improper shutdown, disk error, or permission change.\n\nFix procedure:\n1. Log in as a different admin account (not the affected user)\n2. Create a new user account\n3. Copy data from C:\\Users\\[OldProfile]\\ to the new profile — Documents, Desktop, Pictures, AppData\\Roaming (selectively)\n4. Test the new profile\n5. Delete the old profile via System Properties → Advanced → User Profiles → Settings\n\nDo not attempt to repair NTUSER.DAT directly — creating a new profile is more reliable.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-1-05',
    topicId: 'topic-c2-3-1',
    front: 'What are the steps to resolve Windows Update failures?',
    back: '1. Check disk space: updates need several GB to download and stage. Run Disk Cleanup (cleanmgr) if low.\n\n2. Run Windows Update Troubleshooter: Settings → System → Troubleshoot → Other troubleshooters → Windows Update. Automatically detects and fixes many common issues.\n\n3. Clear the SoftwareDistribution cache: net stop wuauserv → delete contents of C:\\Windows\\SoftwareDistribution\\Download → net start wuauserv → retry update.\n\n4. Manual download from Microsoft Update Catalog: catalog.update.microsoft.com — search by KB number, download and install the standalone .msu package.\n\n5. Run DISM then sfc: DISM /Online /Cleanup-Image /RestoreHealth, then sfc /scannow — damaged system files can block updates.\n\n6. In-place upgrade: last resort — run Windows Setup from ISO, choose Upgrade. Reinstalls Windows keeping files, apps, and settings.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-1-06',
    topicId: 'topic-c2-3-1',
    front: 'What is System Restore and what does it NOT back up?',
    back: 'System Restore saves snapshots (restore points) of Windows system files and the registry. It does NOT back up personal files — documents, photos, and downloads are unaffected by both creating and reverting restore points.\n\nRestore points are created automatically before: Windows Updates, driver installations, and application installations. Can also be created manually.\n\nAccess: Settings → System → About → System Protection (or right-click This PC → Properties → System Protection).\n\nWhen to use: after a driver installation causes instability, after an application install breaks other software, or after a registry change causes problems.\n\nWhen it does NOT help: malware (malware may have created its own restore points that reinfect on restore), personal file loss (System Restore does not touch data files), hardware failures.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-1-07',
    topicId: 'topic-c2-3-1',
    front: 'What tools are available in the Windows Recovery Environment (WinRE)?',
    back: 'WinRE is a lightweight recovery OS that boots separately from Windows. Access it via: Settings → System → Recovery → Advanced startup; interrupting boot 3 times; or booting from Windows installation media.\n\nAvailable tools:\n• Startup Repair: automatically diagnoses and fixes common boot problems\n• System Restore: rolls back to a previous restore point\n• System Image Recovery: restores from a full system image backup\n• Reset this PC: reinstalls Windows, optionally keeping personal files (removes apps and settings)\n• Command Prompt: full command-line access for manual repair (bootrec, sfc, diskpart, bcdedit)\n• Uninstall Updates: removes the most recent quality or feature update\n\nCommand Prompt in WinRE is the entry point for all boot repair commands (bootrec, bootsect, bcdedit).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-1-08',
    topicId: 'topic-c2-3-1',
    front: 'A user has slow boot times. What are the most common causes and how do you address each?',
    back: 'Startup programs (most common): Task Manager → Startup tab. Review every entry and disable non-essential items. The "Startup impact" column prioritizes which to address first.\n\nServices: msconfig → Services tab → check "Hide all Microsoft services" → disable services from unused software.\n\nDisk fragmentation (HDDs only): Disk Defragmenter (defrag and optimize drives). SSDs must NEVER be defragmented — Windows detects SSDs and skips defrag automatically.\n\nLow disk space: keep at least 10–15% of the drive free. Windows needs space for the page file, temporary files, and update staging. Use Disk Cleanup or Storage Sense.\n\nLow RAM: Task Manager → Performance → Memory. If "In use" approaches total RAM, the system is paging heavily to disk. Upgrade RAM or close applications.\n\nMalware: sudden performance degradation warrants a full antivirus scan and Malwarebytes scan.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.2 Troubleshoot Mobile OS (8 cards) ────────────────────────────────

  {
    id: 'fc-c2-3-2-01',
    topicId: 'topic-c2-3-2',
    front: 'What is the correct escalation sequence for a crashing mobile app?',
    back: 'Work from least disruptive to most disruptive:\n\n1. Force stop: terminates the app process cleanly. Android: Settings → Apps → [App] → Force Stop. iOS: swipe up from the bottom, swipe the app card away.\n\n2. Clear app cache: removes corrupted temporary data. Android: Settings → Apps → [App] → Storage → Clear Cache. iOS: no per-app cache clear — proceed to reinstall.\n\n3. Clear app data (Android only): Settings → Apps → [App] → Storage → Clear Data. Resets app to fresh-install state — WARN the user first, all saved data within the app is deleted.\n\n4. Check for updates: the crash may be a known bug fixed in a newer version.\n\n5. Uninstall and reinstall: removes and replaces all app files with a fresh download.\n\nAlso check: available storage space — apps crash when there is insufficient free space for temporary files.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-2-02',
    topicId: 'topic-c2-3-2',
    front: 'What are the prerequisites for a mobile OS update, and what happens when iOS update fails and leaves the device in recovery mode?',
    back: 'Prerequisites for mobile OS update (both iOS and Android):\n• Storage: ~2–4 GB free (iOS varies by update size)\n• Battery: 50% minimum or device plugged in\n• Network: Wi-Fi required (cellular OTA updates are carrier-limited)\n• Backup: recommended before any update\n\nFailing any requirement causes the update to fail.\n\nRecovery from failed iOS update with device in recovery mode:\n1. Connect to a Mac running Finder (macOS Catalina+) or a PC running iTunes\n2. Select "Update" — reinstalls iOS without erasing user data\n3. If "Update" fails, use "Restore" — this erases the device to factory state\n\nAlways try Update before Restore to preserve user data.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-2-03',
    topicId: 'topic-c2-3-2',
    front: 'What is TalkBack / VoiceOver, how is it accidentally enabled, and how do you disable it?',
    back: 'TalkBack (Android) and VoiceOver (iOS) are screen readers designed for visually impaired users. When enabled, normal tap-to-launch becomes a two-step process: tap once to select, double-tap to activate. The device reads everything aloud. Users often describe the device as "broken" or "acting strangely."\n\nHow accidentally enabled:\n• Android: triple-pressing the power button, or using the volume key shortcut if configured\n• iOS: triple-pressing the side/Home button if Accessibility Shortcut is assigned to VoiceOver\n\nHow to disable:\n• Android TalkBack: Settings → Accessibility → TalkBack → Off. With TalkBack active, swipe with two fingers to navigate, double-tap to select.\n• iOS VoiceOver: Settings → Accessibility → VoiceOver → Off. Triple-click the side button to toggle.\n\nExam tip: "phone reads everything aloud" or "everything must be tapped twice" = TalkBack/VoiceOver.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-2-04',
    topicId: 'topic-c2-3-2',
    front: 'A user\'s mobile device sync is broken. What are the four most common causes and how do you resolve each?',
    back: 'Sync disabled: Settings → [Google Account / Apple ID] → verify sync is enabled for Contacts, Calendar, Mail. Toggle off and back on to force a restart if sync appears enabled but stuck.\n\nChanged password: if the account password was changed on the web or another device, the mobile still holds the old password. Sign out of the account on the device and sign back in with the new credentials.\n\nNetwork connectivity: sync requires internet. Verify the device can reach the internet. If all accounts fail simultaneously → network issue; if one account fails → app-specific issue.\n\nIncorrect date and time: certificate validation for HTTPS connections (used by all sync services) requires accurate system time. A clock drifted by more than a few minutes causes sync connections to fail with certificate errors. Set date and time to automatic.\n\nKey insight: if multiple unrelated apps fail simultaneously, check the clock first.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-2-05',
    topicId: 'topic-c2-3-2',
    front: 'What are the most common causes of excessive battery drain on a mobile device?',
    back: 'Background app refresh: iOS: Settings → General → Background App Refresh. Android: per-app background data settings. Apps refreshing content in the background consume CPU and network.\n\nLocation services set to "Always": continuous GPS use is one of the highest battery consumers. Set apps to "While Using" unless Always is genuinely needed.\n\nScreen brightness: the display is the single largest power consumer on most phones. Reduce brightness or enable auto-brightness.\n\nA phone searching for signal: in areas with poor cellular coverage, the radio amplifies power significantly looking for a signal. Enable airplane mode in areas with no coverage.\n\nRogue app in crash-restart loop: an app stuck crashing and restarting appears as very high battery usage in battery stats. Identify via Settings → Battery → per-app usage and uninstall the culprit app.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-2-06',
    topicId: 'topic-c2-3-2',
    front: 'A mobile device\'s touchscreen is unresponsive in certain areas after a drop. What is the most likely cause?',
    back: 'The digitizer is physically separate from the display layer. The digitizer is the capacitive touch sensor that detects finger position; the display is the panel that shows the image. A drop can disconnect, crack, or damage the digitizer without visibly cracking the glass or the display.\n\nWhen a specific area of the screen is unresponsive after a physical drop, the digitizer is likely damaged in that region — even if the screen looks intact from the outside.\n\nThis requires hardware repair — the digitizer assembly must be replaced. Software troubleshooting (restart, clear cache, restore) will not fix a physically damaged digitizer.\n\nNote: if the screen is unresponsive overall without physical damage, check for moisture, a thick/poorly applied screen protector, or Screen Overlay permissions on Android first.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-2-07',
    topicId: 'topic-c2-3-2',
    front: 'What steps should be taken when a mobile device is running out of storage?',
    back: 'Check what is using space first: Settings → Storage (both platforms) shows a breakdown by category.\n\nRecovery steps in order:\n1. Identify largest consumers — photos/videos are almost always the top category\n2. Delete unused apps (games especially)\n3. Enable cloud photo optimization: iCloud Photos (iOS) or Google Photos (Android) with "Optimize Storage" — stores full-resolution in cloud, thumbnails on device\n4. Delete downloaded media — offline music, podcast episodes, video downloads\n5. Clear browser cache: Settings → Safari/Chrome → Clear Website Data\n6. Android only: move appropriate content to SD card if the device supports external storage\n7. Last resort: factory reset — erases everything, returns to out-of-box state; always back up first\n\nTarget: keep at least 10–15% of total storage free for OS operations and virtual memory.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-2-08',
    topicId: 'topic-c2-3-2',
    front: 'A mobile device is overheating persistently even when idle. What does this indicate and how is it addressed?',
    back: 'Brief warmth during intensive tasks (gaming, video recording, navigation) is normal. Persistent heat at idle or heat that causes thermal shutdown is abnormal.\n\nImmediate steps for overheating:\n• Remove the phone case — cases trap heat\n• Move out of direct sunlight\n• Close CPU-intensive apps\n• Stop charging while using if already hot — charging and heavy use together produce significant heat\n\nIdentify software culprits: check Settings → Battery → per-app battery usage. A recently installed app or one stuck in a background loop shows disproportionate battery usage. Uninstall suspect apps.\n\nPersistent overheating with no apps running and device at rest: the battery may be physically failing. Lithium-ion batteries that are swelling or chemically degrading generate heat as a symptom. This is a hardware failure requiring professional service — a swelling battery is also a safety hazard.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.3 Troubleshoot Mobile Security (8 cards) ──────────────────────────

  {
    id: 'fc-c2-3-3-01',
    topicId: 'topic-c2-3-3',
    front: 'What is scareware on mobile and what is the correct response?',
    back: 'Scareware on mobile appears as a browser pop-up claiming "Your iPhone has a virus! Call Apple Support at 1-800-XXX-XXXX immediately!" or similar urgent security warnings. It may prevent navigation, play alarm sounds, or vibrate the device. It is a social engineering attack — there is no actual virus. The goal is toll fraud or getting the user to install a malicious "cleaning" app.\n\nKey fact: a web browser has no ability to scan your device for malware. Legitimate security alerts come from installed security apps as system notifications, never from a web browser pop-up.\n\nCorrect response:\n1. Do NOT call the number — do NOT tap any button inside the pop-up\n2. Close the browser tab via the tab switcher\n3. If the browser cannot be navigated, force-close the browser app\n4. Clear browser history and website data\n5. Report to security team if on a corporate device',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-3-02',
    topicId: 'topic-c2-3-3',
    front: 'Unexpected high background data usage on a mobile device is a symptom of what, and how do you investigate?',
    back: 'Unexpected high background data — especially when the phone is idle or occurring overnight — is one of the clearest behavioral indicators of spyware, malware, or a compromised app sending data to an attacker.\n\nOther causes: background sync stuck in a loop, hotspot enabled with unauthorized connected devices, video autoplay on cellular, or a large OTA update staging.\n\nInvestigation steps:\n1. Settings → Mobile Data (iOS) or Settings → Network → Data Usage (Android) — review per-app data consumption\n2. Reset the data statistics counter; watch for 24–48 hours to identify what is accumulating data\n3. Look for apps you do not recognize or did not install\n4. Check if mobile hotspot is enabled and review which devices are connected\n5. If an unrecognized app is consuming data: uninstall it and run a security scan\n\nDo not dismiss unexpected background data as a network glitch without investigating per-app usage.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-3-03',
    topicId: 'topic-c2-3-3',
    front: 'What are the immediate steps when a user\'s credentials are found in a data breach?',
    back: '1. Change the compromised password immediately — do this from a trusted, secure network (not public Wi-Fi)\n\n2. Change the password on any other account where the same password was reused — password reuse is extremely common and means one breach compromises many accounts\n\n3. Enable MFA on the affected account and related accounts — the attacker may have the password but not the second factor\n\n4. Review account activity and login history for signs of unauthorized access during the breach window\n\n5. Check HaveIBeenPwned.com (hibp) with the email address to understand the full scope of exposure across breaches\n\n6. If corporate credentials are involved: notify IT security immediately — they may need to invalidate sessions, rotate service account passwords, and investigate for data exfiltration\n\nPrevention: use a password manager to generate unique passwords for every account.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-3-04',
    topicId: 'topic-c2-3-3',
    front: 'What are the indicators of unauthorized mobile account access, and what is the response?',
    back: 'Indicators of compromise in account settings:\n• Login history shows unrecognized IP addresses or geolocations\n• Connected/authorized apps include applications the user did not add\n• Account recovery contacts (email, phone) were changed\n• Email forwarding rules forward copies of email to an external address (common persistence technique)\n• User receives 2FA codes they did not request\n\nResponse:\n1. Use account recovery options (secondary email, backup codes) to regain access\n2. Change the password immediately to something new and unique\n3. Enable MFA\n4. Review and revoke all authorized/connected OAuth apps — attackers add these for persistent access even after password change\n5. Check and delete any email forwarding rules\n6. Alert IT security if this is a work account tied to SSO — force reset and session invalidation may be needed across all connected services',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-3-05',
    topicId: 'topic-c2-3-3',
    front: 'What is premium SMS fraud and how do unexpected in-app charges occur on mobile?',
    back: 'Premium SMS fraud: malware (typically from sideloaded apps on Android) silently sends text messages to premium-rate numbers, which generate per-message charges billed directly to the carrier account. The user sees unexplained charges on their phone bill.\n\nInvestigation: review the carrier bill for premium SMS or unusual per-message charges. Contact the carrier to block premium SMS services.\n\nIn-app purchase fraud causes:\n• Children using a parent\'s device with stored payment methods — configure parental controls and require Face ID/password authentication for every purchase\n• Compromised App Store/Google Play account — change password, enable MFA, review purchase history, dispute unauthorized charges through the platform\n\nPrevention: enable purchase authentication (require biometric or password for every app store purchase) and audit app permissions on Android for sideloaded apps.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-3-06',
    topicId: 'topic-c2-3-3',
    front: 'How should app permissions be evaluated — give examples of legitimate vs. red-flag permission requests?',
    back: 'Principle: apps should have only the permissions they genuinely need to function. A permission request with no plausible legitimate use is a red flag.\n\nRed flag examples:\n• Flashlight app requesting contacts, location, or microphone\n• Simple calculator requesting camera or microphone\n• Weather app requesting "Always On" location and contacts\n• Game requesting accessibility permissions\n\nLegitimate examples:\n• Video calling app requesting camera and microphone\n• Navigation app requesting location\n• Contact manager requesting contacts\n• File manager requesting storage\n\nReview and revoke:\n• iOS: Settings → Privacy & Security → select permission type to see all apps with that access\n• Android: Settings → Privacy → Permission Manager → select permission type\n\nThe Accessibility permission is especially powerful — grant it only to screen readers and password managers with autofill.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-3-07',
    topicId: 'topic-c2-3-3',
    front: 'What causes a certificate error on a mobile device, and when is it a red flag vs. expected?',
    back: 'Certificate error causes and appropriate responses:\n\nExpired server certificate: avoid the site; notify the owner.\n\nSelf-signed certificate (internal corporate site): install the organization\'s root CA cert on the device — MDM can push this automatically to enrolled devices.\n\nCaptive portal redirect (hotel/airport Wi-Fi): normal behavior before logging into the portal; open a browser and accept the portal page.\n\nMDM SSL inspection proxy (corporate device): IT intercepts HTTPS for content filtering; MDM pushes a trusted root certificate so the browser accepts it. Expected and intentional.\n\nIncorrect device date/time: fix the clock and retry — incorrect time breaks certificate validation.\n\nMitM attack (public Wi-Fi): certificate warning on a trusted site on an untrusted network is a significant red flag. Disconnect from the network immediately.\n\nKey rule: certificate warnings on public Wi-Fi = disconnect first, investigate second.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-3-08',
    topicId: 'topic-c2-3-3',
    front: 'What MDM non-compliance issues commonly block corporate email access, and how is each resolved?',
    back: 'The fix for any non-compliance issue is always to bring the device into compliance — not to disable MDM controls.\n\nOS version too old: MDM blocks access until the device updates to the minimum required OS version. Update the OS.\n\nScreen lock not set or insufficient: MDM requires a minimum PIN length or biometric. Enable and configure an appropriate screen lock.\n\nEncryption disabled: MDM requires device encryption. Enable device encryption (modern iOS and Android are encrypted by default once a passcode is set).\n\nDevice reported as jailbroken/rooted: factory reset and re-enroll with a clean OS. If it is a false positive, contact IT to investigate.\n\nMDM enrollment expired or missing: device was un-enrolled. Re-enroll: Settings → General → VPN & Device Management (iOS) or Settings → Accounts → MDM Profile (Android).\n\nApps pushed by MDM not installing: free storage and connect to corporate Wi-Fi.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.4 Troubleshoot PC Security (8 cards) ──────────────────────────────

  {
    id: 'fc-c2-3-4-01',
    topicId: 'topic-c2-3-4',
    front: 'What are the most important malware infection symptoms to recognize for the A+ exam?',
    back: 'Symptom → malware type:\n\nHigh CPU/memory from unknown processes → cryptominer, botnet client, trojan\nPop-up ads appearing without a browser open → adware (system-level component)\nBrowser redirects to different search engine or homepage → browser hijacker\nAntivirus disabled or unable to update → rootkit or advanced trojan (malware disables defenses)\nFiles encrypted with a ransom note → ransomware\nSecurity tools won\'t install or run → rootkit (actively blocks security software)\nFrequent crashes or BSODs → rootkit (modifies kernel components)\nMissing or hidden files → rootkit, ransomware in pre-encryption phase\nSpam sent from user\'s email account → credentials harvested by malware or phishing\nUnexpected outbound network traffic → botnet, RAT, data exfiltration malware\n\nMonitor outbound traffic with: Resource Monitor (resmon) → Network tab, or netstat -an in Command Prompt.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-4-02',
    topicId: 'topic-c2-3-4',
    front: 'What are the correct immediate steps when ransomware is detected on a PC?',
    back: '1. Disconnect from the network immediately — before anything else. Ransomware spreads to network shares, mapped drives, and other connected systems. Pulling the network cable or disabling Wi-Fi prevents further spread even if the encryption continues locally.\n\n2. Do NOT pay the ransom — there is no guarantee the attacker provides a working decryption key, and payment encourages further attacks.\n\n3. Restore from a clean backup — this is the correct resolution on the exam. The backup must pre-date the infection.\n\n4. Verify the backup is clean: cloud-synced backups may have synced the encrypted files, overwriting the clean versions. Offline or air-gapped backups are the proper defense.\n\n5. Report to management and potentially law enforcement (FBI Internet Crime Complaint Center — IC3).\n\n6. Determine the infection vector before restoring — fix the entry point so it does not happen again.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-4-03',
    topicId: 'topic-c2-3-4',
    front: 'What Windows tools and locations should be checked for unauthorized access indicators?',
    back: 'Unknown user accounts: lusrmgr.msc (Local Users and Groups) — check for accounts you did not create, especially accounts with admin privileges.\n\nUnfamiliar startup entries: shell:startup (current user startup folder), shell:common startup (all users startup folder). Also check Task Manager → Startup tab and msconfig → Startup.\n\nScheduled tasks: taskschd.msc (Task Scheduler) — look for tasks with suspicious names, unknown executables, or tasks scheduled at unusual times (2 AM daily). Attackers use scheduled tasks for persistence.\n\nEvent Viewer — Security log:\n• Event ID 4625: failed logon\n• Event ID 4624: successful logon\n• Event ID 4720: user account created\n• Event ID 4728: member added to security group\n\nUnauthorized firewall rules: wf.msc (Windows Firewall with Advanced Security) — check inbound/outbound rules for entries you did not create.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-4-04',
    topicId: 'topic-c2-3-4',
    front: 'How do you distinguish a real security alert from a fake scareware alert on a Windows PC?',
    back: 'Real security alert:\n• Comes from installed security software (Windows Defender, Norton, etc.)\n• Appears as a Windows notification or within the AV application\'s own window\n• Does NOT ask you to call a phone number\n• Does NOT ask for payment to remove a threat\n• Provides specific file path and threat name\n• Can be verified by opening the AV application directly\n\nFake alert / scareware:\n• Appears in a web browser as a pop-up or full-screen page\n• Claims to be from Microsoft, Apple, or a well-known AV brand\n• Provides a phone number to call immediately\n• Creates urgency: "Your data is being stolen RIGHT NOW"\n• May lock the browser in full-screen (press F11 or Escape to exit)\n• Has no actual access to your system — it is just a webpage\n\nResponse to fake alert: press Escape/F11 → close the tab → if tab resists closing, use Task Manager to kill the browser process → clear cache and cookies → run a real scan to confirm no infection.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-4-05',
    topicId: 'topic-c2-3-4',
    front: 'What is the complete malware removal procedure for a Windows PC?',
    back: '1. Identify and quarantine: run Windows Defender full scan + Malwarebytes. If ransomware: disconnect from network FIRST before scanning.\n\n2. Safe Mode if needed: restart into Safe Mode (hold Shift + Restart or F8). Loads minimal drivers — may prevent malware from loading and blocking removal tools.\n\n3. Remove detected threats: use the security tool\'s quarantine and removal. For stubborn malware, use a bootable rescue disk (runs outside the infected OS).\n\n4. Check persistence mechanisms: Task Manager Startup tab, Task Scheduler, shell:startup folders, browser extensions, installed programs list. Remove anything suspicious.\n\n5. Repair system files: DISM /Online /Cleanup-Image /RestoreHealth, then sfc /scannow. Malware often corrupts system files.\n\n6. Change all credentials: passwords for all accounts used on the infected machine — the machine may have had a keylogger. Notify IT security if work accounts were used.\n\n7. Verify and monitor: reboot normally; run scan again; monitor for 24–48 hours; check Event Viewer.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-4-06',
    topicId: 'topic-c2-3-4',
    front: 'When should you clean a malware infection vs. when should you wipe and reinstall the OS?',
    back: 'Clean first when:\n• Infection detected early by AV before significant damage\n• Malware type is known with reliable removal tools\n• No evidence of rootkit activity\n• System is a workstation (not a server) with non-critical data\n• Time to clean is reasonable compared to reinstall + reconfiguration time\n\nWipe and reinstall (nuke and pave) when:\n• Rootkit is suspected or confirmed — rootkits modify the OS kernel and bootloader; complete removal is unreliable without reinstalling\n• Malware persists after multiple removal attempts\n• System files are severely corrupted beyond what DISM/sfc can repair\n• Corporate policy requires reinstall for confirmed infections (common in regulated industries)\n• Scope and dwell time of infection are unknown — damage may be beyond what is visible\n\nExam rule: if a question mentions rootkit or malware that keeps returning after removal → the answer is OS reinstall.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-4-07',
    topicId: 'topic-c2-3-4',
    front: 'What causes widespread certificate errors across multiple HTTPS sites on a Windows PC?',
    back: 'If a user reports that multiple HTTPS sites suddenly show certificate errors simultaneously (not just one site), the most common cause is an incorrect system clock.\n\nTLS certificate validation requires the client\'s clock to fall within the certificate\'s validity period. If the system clock drifts significantly — which can happen with a dead CMOS battery — all certificates appear expired or not-yet-valid depending on how far the clock has drifted.\n\nFix: correct the system date and time. All certificate errors will resolve instantly.\n\nOther causes of certificate errors (site-specific, not widespread):\n• Expired server certificate — site owner must renew\n• Self-signed certificate — install organization\'s root CA cert via certmgr.msc or GPO\n• Hostname mismatch — possible MitM or server misconfiguration; do not proceed\n• Revoked certificate — avoid the site',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-3-4-08',
    topicId: 'topic-c2-3-4',
    front: 'A PC shows high CPU usage from an unknown process at idle. Walk through the diagnostic steps.',
    back: 'Scenario: unknown process consuming high CPU while the user is not actively doing anything.\n\n1. Open Task Manager (Ctrl+Shift+Esc) → Details tab. Right-click the process → Open file location to see where the executable lives. Legitimate Windows processes are in C:\\Windows\\System32. Processes in temp folders, AppData, or user profile folders are suspicious.\n\n2. Right-click the process → Search online to research the process name.\n\n3. Check Resource Monitor (resmon) → CPU tab and Network tab. Look for unexpected outbound connections — a process connecting to unusual IPs may be a botnet client, RAT, or cryptominer.\n\n4. Run Windows Defender full scan and Malwarebytes scan.\n\n5. Check startup entries (Task Manager → Startup) and Task Scheduler for scheduled tasks associated with the suspicious process.\n\n6. If malware is confirmed: follow the full malware removal procedure. If a rootkit is suspected based on symptoms (security tools won\'t run, process hides itself), proceed to OS reinstall.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

]
