// CompTIA A+ Flashcards — All Topics (both exams)

import { BATCH1_FLASHCARDS } from './flashcards-batch1'
import { BATCH2_FLASHCARDS } from './flashcards-batch2'
import { BATCH3_FLASHCARDS } from './flashcards-batch3'
import { BATCH4_FLASHCARDS } from './flashcards-batch4'
import { BATCH5_FLASHCARDS } from './flashcards-batch5'
import { BATCH6_FLASHCARDS } from './flashcards-batch6'
import { BATCH7_FLASHCARDS } from './flashcards-batch7'
import { BATCH8_FLASHCARDS } from './flashcards-batch8'

const NOW = new Date().toISOString()

const CORE1_D3_FLASHCARDS = [
  // ─── 3.1 Display Types (13 cards) ───────────────────────────────────────────
  {
    id: 'fc-c1-3-1-01',
    topicId: 'topic-c1-3-1',
    front: 'What does LCD stand for, and how does it produce images?',
    back: 'Liquid Crystal Display. A backlight (CCFL or LED) shines through a layer of liquid crystals that can be twisted to block or pass light. Color filters produce the final image. No self-emitting pixels — needs a backlight at all times.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-02',
    topicId: 'topic-c1-3-1',
    front: 'Compare IPS vs. TN LCD panel technology.',
    back: 'IPS (In-Plane Switching): wide viewing angles (178°), accurate colors, typical response 4–8 ms. Preferred for creative work and general use.\n\nTN (Twisted Nematic): narrow viewing angles (160°/170°), poor color accuracy, very fast response (1–5 ms). Preferred for competitive gaming due to low latency.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-03',
    topicId: 'topic-c1-3-1',
    front: 'What is a VA panel and how does it compare to IPS and TN?',
    back: 'Vertical Alignment (VA): achieves high contrast ratios (3000:1+) and deep blacks, better than both IPS and TN. Color accuracy is between IPS and TN. Response time is slower than TN but comparable to IPS. Best for media consumption.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-04',
    topicId: 'topic-c1-3-1',
    front: 'What is OLED, and what makes it different from LCD?',
    back: 'Organic Light-Emitting Diode. Each pixel emits its own light — no backlight required. Results in true blacks (pixels turn completely off), infinite contrast ratio, and thinner form factor. Can suffer from burn-in with static images. Used in high-end phones, TVs, and premium laptops.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-05',
    topicId: 'topic-c1-3-1',
    front: 'What is display refresh rate, and what unit is it measured in?',
    back: 'Refresh rate = number of times the display redraws the image per second, measured in Hertz (Hz). Standard is 60 Hz. Higher rates (120 Hz, 144 Hz, 240 Hz) produce smoother motion, important for gaming. Must be supported by both the monitor and GPU.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-06',
    topicId: 'topic-c1-3-1',
    front: 'What is display response time?',
    back: 'The time in milliseconds (ms) for a pixel to change from one color to another (gray-to-gray, GtG). Lower = better for fast motion with less blur. TN: 1–5 ms. IPS: 4–8 ms. VA: 4–10 ms. Not the same as input lag.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-07',
    topicId: 'topic-c1-3-1',
    front: 'List common display resolutions and their names.',
    back: '1280×720 — HD (720p)\n1920×1080 — FHD / 1080p\n2560×1440 — QHD / 1440p\n3840×2160 — 4K UHD\n7680×4320 — 8K UHD\nHigher resolution = more pixels = sharper image at the same physical screen size.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-08',
    topicId: 'topic-c1-3-1',
    front: 'What is nit, and what typical brightness levels are used?',
    back: 'Nit = unit of luminance = 1 candela per square meter (cd/m²). Standard monitors: 250–350 nits. HDR-capable displays: 400–1000+ nits. Outdoor/direct-sunlight use: 1000+ nits. Higher nit count = more visible in bright environments.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-09',
    topicId: 'topic-c1-3-1',
    front: 'What is pixel pitch?',
    back: 'Pixel pitch = distance between centers of adjacent pixels, measured in mm. Smaller pitch = higher pixel density = sharper image. Calculated as: screen dimension (mm) ÷ resolution. PPI (pixels per inch) is the inverse relationship — higher PPI = better image quality.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-10',
    topicId: 'topic-c1-3-1',
    front: 'What are the two main types of LCD backlighting?',
    back: 'CCFL (Cold Cathode Fluorescent Lamp): fluorescent tubes behind the panel. Older technology, thicker bezels, less energy efficient, no local dimming.\n\nLED: current standard. Thinner, more energy efficient, longer lifespan, supports local dimming (edge-lit or full-array). Full-array local dimming (FALD) enables better contrast.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-11',
    topicId: 'topic-c1-3-1',
    front: 'What is display aspect ratio? List common ratios.',
    back: 'Ratio of display width to height:\n• 4:3 — older CRT and legacy monitors\n• 16:9 — modern widescreen standard\n• 16:10 — common in some laptops (more vertical space)\n• 21:9 — ultrawide, used for gaming/productivity\n• 32:9 — super ultrawide',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-12',
    topicId: 'topic-c1-3-1',
    front: 'What is a touchscreen digitizer, and what are the two main types?',
    back: 'A transparent layer over the display that detects touch input and converts it to coordinates.\n\nResistive: two flexible layers that make contact when pressed. Works with any stylus or finger, less accurate, used in older devices and industrial settings.\n\nCapacitive: detects electrical charge from bare skin. High accuracy, multi-touch, used in smartphones and tablets. Does NOT work with regular gloves or stylus.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-1-13',
    topicId: 'topic-c1-3-1',
    front: 'What is a curved display, and how is the curve radius specified?',
    back: 'A monitor with a gentle horizontal curve designed to match the natural curvature of human vision, reducing distortion at screen edges and creating an immersive viewing experience.\n\nCurve radius is measured in mm: 1000R = 1-meter radius (tightest curve), 1500R = 1.5-meter radius (gentler curve). Lower number = more aggressive curve. Common in ultrawide and gaming monitors.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.2 Cables and Connectors (14 cards) ────────────────────────────────────
  {
    id: 'fc-c1-3-2-01',
    topicId: 'topic-c1-3-2',
    front: 'What are the USB 3.x speed tiers and how are ports identified?',
    back: 'USB 3.2 Gen 1 (USB 3.0): 5 Gbps — blue Type-A port\nUSB 3.2 Gen 2 (USB 3.1): 10 Gbps\nUSB 3.2 Gen 2×2: 20 Gbps (USB-C only)\nUSB4 Gen 2×2: 20 Gbps\nUSB4 Gen 3×2: 40 Gbps (Thunderbolt 3 protocol)\n\nLook for port color (blue = USB 3.x Gen 1) or the SS (SuperSpeed) logo.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-02',
    topicId: 'topic-c1-3-2',
    front: 'What is USB4 and what connector does it require?',
    back: 'USB4 is the latest USB standard based on Thunderbolt 3 technology. Maximum speed: 40 Gbps. Supports DisplayPort and PCIe tunneling. Requires USB-C connector exclusively. Backward compatible with USB 3.x and Thunderbolt 3 devices.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-03',
    topicId: 'topic-c1-3-2',
    front: 'Compare Thunderbolt 3 and Thunderbolt 4 specifications.',
    back: 'Both: USB-C connector, 40 Gbps data, 100W power delivery, daisy-chain up to 6 devices.\n\nThunderbolt 4 adds mandatory requirements:\n• Minimum 32 Gbps PCIe tunneling (TB3 was 16 Gbps)\n• Minimum 2 × 4K display output support\n• Intel VT-d DMA protection\n• Wake from sleep over TB cable\n\nBoth are backward compatible with USB4 and USB 3.x.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-04',
    topicId: 'topic-c1-3-2',
    front: 'What is DisplayPort and what are its key capabilities?',
    back: 'A digital display interface developed by VESA. Uses rectangular connector with one angled corner (or Mini DisplayPort for smaller devices).\n\nDP 1.4: supports 8K at 60Hz or 4K at 120Hz. Supports daisy-chaining monitors via Multi-Stream Transport (MST). Primarily used on PCs and monitors. Can be adapted to HDMI, DVI, VGA via active adapters.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-05',
    topicId: 'topic-c1-3-2',
    front: 'What is HDMI? Compare HDMI 2.0 vs 2.1.',
    back: 'High-Definition Multimedia Interface. Carries video + audio over a single cable. Common on TVs, monitors, projectors, and AV equipment.\n\nHDMI 2.0: 4K at 60Hz, 18 Gbps bandwidth, supports HDR.\nHDMI 2.1: 8K at 60Hz, 4K at 144Hz, 48 Gbps bandwidth, supports VRR (Variable Refresh Rate), eARC.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-06',
    topicId: 'topic-c1-3-2',
    front: 'What is VGA? Why is it considered legacy?',
    back: 'Video Graphics Array — a 15-pin D-sub analog video connector. Maximum theoretical resolution: 2048×1536, but analog signal degrades with distance and at high resolutions. No audio support. Introduced in 1987. Replaced by digital interfaces (DVI, HDMI, DisplayPort). Still found on older monitors, projectors, and some business laptops for compatibility.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-07',
    topicId: 'topic-c1-3-2',
    front: 'What are the DVI connector variants?',
    back: 'DVI-D: digital signal only. Single-link: up to 1920×1200. Dual-link: up to 2560×1600.\nDVI-A: analog signal only (VGA compatible). Rarely used.\nDVI-I: integrated, supports both digital and analog. Can be adapted to VGA.\n\nNo audio support in any variant.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-08',
    topicId: 'topic-c1-3-2',
    front: 'What is SATA and what speeds does each generation support?',
    back: 'Serial ATA — interface for connecting storage devices (HDDs, SSDs, optical drives).\n\nSATA I (1.5 Gbps) → effective ~150 MB/s\nSATA II (3 Gbps) → effective ~300 MB/s\nSATA III (6 Gbps) → effective ~600 MB/s (real-world SSD max ~550 MB/s)\n\nAll SATA generations are backward compatible. Uses 7-pin data + 15-pin power connectors.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-09',
    topicId: 'topic-c1-3-2',
    front: 'What is eSATA and what are its limitations?',
    back: 'External SATA — extends SATA to external drives using a shielded eSATA cable. Provides native SATA I/II/III speeds (up to 6 Gbps) without USB conversion overhead.\n\nLimitations: does NOT supply power (need separate power adapter), shorter cable length than USB (2m max), less common in modern systems. eSATAp adds power but is non-standard.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-10',
    topicId: 'topic-c1-3-2',
    front: 'Compare single-mode vs. multimode fiber optic cable.',
    back: 'Single-mode (SMF): yellow jacket, small 8–10 μm core. Single light path = no modal dispersion. Long distances (up to 100 km). Used for WAN, ISP backbone, campus core.\n\nMultimode (MMF): orange (OM1/OM2) or aqua (OM3/OM4) jacket, larger 50–62.5 μm core. Multiple light paths. Short distances (up to 2 km). Less expensive. Used for data centers and within buildings.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-11',
    topicId: 'topic-c1-3-2',
    front: 'What fiber optic connector types should you know for the exam?',
    back: 'LC (Lucent Connector): small form factor, snap-in locking. Most common in data centers and patch panels.\nSC (Subscriber Connector): square push-pull design, widely used.\nST (Straight Tip): bayonet-mount (twist-lock), older, used in legacy networks.\nMPO/MTP: multi-fiber connector (12–72 fibers), used in high-density 40G/100G environments.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-12',
    topicId: 'topic-c1-3-2',
    front: 'What is a plenum-rated cable?',
    back: 'A cable with a special fire-resistant jacket (FEP or low-smoke PVC) that emits minimal toxic fumes when burned. Required by fire codes in plenum spaces — areas used for air circulation: above drop ceilings, below raised floors, HVAC ducts. PVC jackets release toxic HCl gas when burned, making them unsuitable for plenum spaces. Plenum cables cost more but are required for safety compliance.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-13',
    topicId: 'topic-c1-3-2',
    front: 'What Ethernet cable categories should you know and their speeds?',
    back: 'Cat5e: up to 1 Gbps at 100m. Most common in older installations.\nCat6: up to 10 Gbps at 55m (or 1 Gbps at 100m). Has internal separator reducing crosstalk.\nCat6a: up to 10 Gbps at 100m. Augmented, thicker, better shielding.\nCat7/Cat8: up to 25–40 Gbps, shielded, data center use.\n\nAll use RJ-45 connectors. Higher category = better shielding and performance.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-2-14',
    topicId: 'topic-c1-3-2',
    front: 'What is the difference between T568A and T568B wiring standards?',
    back: 'Both are TIA/EIA standards for wiring RJ-45 connectors. They differ in the order of orange and green wire pairs.\n\nT568B: most common in the US for new installations.\nT568A: used by some government and residential installations.\n\nStraight-through cable: both ends use same standard (A-A or B-B). Used to connect different devices (PC to switch).\nCrossover cable: T568A on one end, T568B on the other. Used to connect like devices (PC to PC). Modern devices auto-detect (Auto-MDI/MDIX).',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.3 RAM (13 cards) ──────────────────────────────────────────────────────
  {
    id: 'fc-c1-3-3-01',
    topicId: 'topic-c1-3-3',
    front: 'What are the pin counts for DDR4 and DDR5 DIMMs and SO-DIMMs?',
    back: 'DDR4 DIMM: 288 pins\nDDR4 SO-DIMM (laptop): 260 pins\n\nDDR5 DIMM: 288 pins (same count but different notch position — not backward compatible)\nDDR5 SO-DIMM (laptop): 262 pins\n\nThe notch position prevents accidental installation in incompatible slots.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-02',
    topicId: 'topic-c1-3-3',
    front: 'What voltages do DDR3, DDR4, and DDR5 RAM use?',
    back: 'DDR3: 1.5V standard, 1.35V low-voltage (DDR3L)\nDDR4: 1.2V standard, 1.05V low-voltage (DDR4L)\nDDR5: 1.1V standard\n\nLower voltage = less power consumption and heat. Each generation is NOT electrically compatible with previous generations.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-03',
    topicId: 'topic-c1-3-3',
    front: 'What is ECC RAM and when is it used?',
    back: 'Error-Correcting Code RAM detects AND corrects single-bit memory errors in real-time, preventing data corruption. Has an extra 8 bits per 64-bit word (72-bit wide bus vs standard 64-bit).\n\nUsed in: servers, workstations, financial systems, medical equipment, anywhere data integrity is critical.\nNOT compatible with standard consumer motherboards — requires workstation/server platform support.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-04',
    topicId: 'topic-c1-3-3',
    front: 'What is the difference between DIMM and SO-DIMM?',
    back: 'DIMM (Dual Inline Memory Module): full-size, ~133mm long. Used in desktop computers and servers.\n\nSO-DIMM (Small Outline DIMM): compact, ~67mm long. Used in laptops, mini-PCs (NUC), and some all-in-one computers.\n\nBoth have different pin counts per DDR generation and are NOT interchangeable between form factors.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-05',
    topicId: 'topic-c1-3-3',
    front: 'What is dual-channel memory and how do you enable it?',
    back: 'Dual-channel = two identical RAM sticks installed in paired slots, doubling the memory controller bus width from 64-bit to 128-bit. Results in ~20–40% bandwidth increase.\n\nTo enable: install matching sticks in the correct slots per motherboard manual (typically slots A2 and B2, or 2nd and 4th slots). Mismatched sticks may force single-channel.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-06',
    topicId: 'topic-c1-3-3',
    front: 'What is CAS Latency (CL) in RAM?',
    back: 'CAS Latency = Column Access Strobe Latency. The number of clock cycles between the memory controller sending a read command and the first data being available.\n\nLower CL = faster response time. However, actual latency in nanoseconds also depends on clock speed: actual latency (ns) = CL ÷ clock frequency (GHz). A DDR4-3200 CL16 has similar ns latency to DDR4-2133 CL10.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-07',
    topicId: 'topic-c1-3-3',
    front: 'What is XMP / EXPO for RAM?',
    back: "Intel XMP (Extreme Memory Profile) and AMD EXPO (Extended Profiles for Overclocking) allow RAM to run at its advertised rated speed above the JEDEC standard base frequency.\n\nWithout XMP/EXPO enabled in BIOS/UEFI, DDR4-3600 RAM will run at the base JEDEC spec (DDR4-2133 or 2400). Enable XMP/EXPO in UEFI to get the speed you paid for — it's a one-click setting.",
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-08',
    topicId: 'topic-c1-3-3',
    front: 'What is LPDDR RAM and where is it used?',
    back: 'Low Power Double Data Rate RAM. Designed for mobile devices with lower voltage (LPDDR5: 1.05V) and reduced power consumption.\n\nTypically soldered directly to the system board (SoC package or board-level), making it non-upgradeable. Found in: smartphones, tablets, thin laptops/ultrabooks (Surface, MacBook Air), Chromebooks, and ARM-based devices.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-09',
    topicId: 'topic-c1-3-3',
    front: 'What is virtual memory / paging?',
    back: "Virtual memory allows the OS to use disk space as an extension of physical RAM. When physical RAM is full, the OS moves inactive memory pages (blocks) to a paging file (Windows: pagefile.sys) or swap partition (Linux).\n\nSwap/page file access is 100–10,000× slower than RAM. Excessive use of virtual memory causes 'thrashing' — the system spends more time swapping than executing, leading to severe slowdowns.",
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-10',
    topicId: 'topic-c1-3-3',
    front: 'Why can\'t a 32-bit OS use more than 4 GB of RAM?',
    back: '32-bit addressing uses 32 binary digits, allowing memory addresses from 0 to 2³² - 1 = 4,294,967,295 bytes = 4 GB. This is a hard architectural limit.\n\n64-bit OS supports theoretical 16 exabytes (2⁶⁴) of RAM. Practical limits depend on chipset. Windows 11 Pro: 2 TB. Most modern systems require 64-bit OS for more than 4 GB of usable RAM.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-11',
    topicId: 'topic-c1-3-3',
    front: 'What is registered (buffered) RAM (RDIMM)?',
    back: 'Registered DIMMs have a register chip between the memory controller and the RAM modules, buffering the signals. This reduces electrical load on the memory controller, allowing more DIMMs per channel (up to 8).\n\nUsed exclusively in servers. NOT compatible with consumer motherboards (which use unregistered/unbuffered UDIMMs). Often combined with ECC for maximum server reliability.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-12',
    topicId: 'topic-c1-3-3',
    front: 'How do you identify incompatible RAM at a glance?',
    back: 'Check these on the RAM module:\n1. DDR generation (DDR3/4/5) — different notch positions prevent cross-installation\n2. Form factor (DIMM vs SO-DIMM) — size difference is obvious\n3. Pin count — verify with socket spec\n4. Voltage — ECC vs non-ECC modules look identical; check markings\n5. Maximum speed supported by motherboard\n\nAlways check motherboard QVL (Qualified Vendor List) for confirmed compatibility.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-3-13',
    topicId: 'topic-c1-3-3',
    front: 'What is the SPD chip on a RAM module?',
    back: "Serial Presence Detect (SPD) is a small EEPROM chip on every RAM module that stores: manufacturer, part number, serial number, capacity, speed grade, default voltage, and recommended timings.\n\nThe system's BIOS/UEFI reads SPD at boot to auto-configure RAM correctly. XMP/EXPO profiles are stored in the extended SPD data. Without SPD data, the system falls back to the slowest safe JEDEC spec.",
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.4 Storage Devices (13 cards) ──────────────────────────────────────────
  {
    id: 'fc-c1-3-4-01',
    topicId: 'topic-c1-3-4',
    front: 'What are the key differences between HDD and SSD?',
    back: 'HDD (Hard Disk Drive): spinning magnetic platters + read/write heads, mechanical. Fragile to physical shock, slow random access (~0.1–0.5 ms seek), 100–200 MB/s sequential. Inexpensive per GB, no data loss on power cut.\n\nSSD (Solid State Drive): NAND flash, no moving parts. Shock resistant, fast random access (~0.05–0.1 ms), 500–7000 MB/s sequential. More expensive per GB, silent, lighter.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-02',
    topicId: 'topic-c1-3-4',
    front: 'What is NVMe and how does it compare to SATA?',
    back: 'Non-Volatile Memory Express — a storage protocol designed specifically for SSDs over PCIe. Much lower latency and higher parallelism than AHCI (used with SATA).\n\nNVMe PCIe 3.0: ~3500 MB/s read\nNVMe PCIe 4.0: ~7000 MB/s read\nNVMe PCIe 5.0: ~14000 MB/s read\nSATA III SSD: ~550 MB/s max\n\nNVMe requires an M.2 PCIe slot or PCIe add-in card.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-03',
    topicId: 'topic-c1-3-4',
    front: 'What SSD form factors are available?',
    back: '2.5" SATA: same size as laptop HDD, connects via SATA data + power cable. Drop-in HDD replacement.\nM.2: compact card (22mm wide × 42/60/80/110mm long). Can be SATA or NVMe/PCIe — key type determines protocol.\nmSATA: older compact form factor, used in ultrabooks before M.2.\nPCIe Add-in Card (AIC): full PCIe card for desktop high-performance use.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-04',
    topicId: 'topic-c1-3-4',
    front: 'What is an M.2 slot and what key types exist?',
    back: 'M.2 is a compact motherboard connector for storage drives (and other devices like Wi-Fi cards).\n\nKey types (notch position):\n• M-key (single notch, right side): NVMe/PCIe or SATA\n• B-key (single notch, left side): SATA or PCIe ×2 NVMe\n• B+M key (two notches): SATA only\n\nCommon lengths: 2242, 2260, 2280 (22mm wide × 80mm long = most common).\n\nAlways verify whether M.2 slot supports NVMe, SATA, or both.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-05',
    topicId: 'topic-c1-3-4',
    front: 'Describe RAID 0, 1, 5, 6, and 10.',
    back: 'RAID 0 — Striping. Min 2 drives. No redundancy. Max speed/capacity. One drive failure = total data loss.\nRAID 1 — Mirroring. Min 2 drives. Full redundancy. 50% usable capacity.\nRAID 5 — Striping + distributed parity. Min 3 drives. 1 drive failure tolerance. Good balance of speed, capacity, and redundancy.\nRAID 6 — Dual parity. Min 4 drives. 2 drive failure tolerance.\nRAID 10 — Mirrored pairs then striped. Min 4 drives. Best performance + redundancy. 50% usable capacity.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-06',
    topicId: 'topic-c1-3-4',
    front: 'What are common HDD RPM speeds and their use cases?',
    back: '5400 RPM: laptop/2.5" drives. Quieter, lower power, runs cooler. Slower (100–120 MB/s sequential).\n7200 RPM: standard desktop drives. Faster (160–200 MB/s). Most common for general use.\n10,000 RPM: high-performance desktop/workstation (Western Digital Raptor series). Very fast.\n15,000 RPM: enterprise SCSI/SAS drives for servers. Fastest HDDs available, expensive, very hot.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-07',
    topicId: 'topic-c1-3-4',
    front: 'What NAND flash cell types are used in SSDs?',
    back: 'SLC (Single-Level Cell): 1 bit/cell. Fastest, most durable (100,000 P/E cycles), most expensive. Enterprise/caching use.\nMLC (Multi-Level Cell): 2 bits/cell. Good balance, 10,000 P/E cycles.\nTLC (Triple-Level Cell): 3 bits/cell. Most common consumer SSDs, 3,000 P/E cycles.\nQLC (Quad-Level Cell): 4 bits/cell. Highest density/lowest cost, ~1,000 P/E cycles. Best for read-heavy workloads.\n\nMore bits per cell = denser/cheaper but less durable.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-08',
    topicId: 'topic-c1-3-4',
    front: 'What is wear leveling in SSDs?',
    back: 'A firmware algorithm that distributes write and erase cycles evenly across all NAND flash cells. Since each cell can only endure a finite number of Program/Erase cycles, without wear leveling, frequently-written cells would fail first.\n\nStatic wear leveling: moves rarely-changed data to spread wear.\nDynamic wear leveling: only distributes actively written data.\nStatic is more effective but increases write amplification slightly.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-09',
    topicId: 'topic-c1-3-4',
    front: 'What is the TRIM command for SSDs?',
    back: 'An ATA command (ATA_TRIM) that tells the SSD controller which data blocks are no longer in use and can be erased in advance. NAND flash must erase before writing — without TRIM, the SSD must read-modify-write existing blocks, slowing performance over time.\n\nWith TRIM enabled: the OS notifies the SSD when files are deleted, SSD pre-erases those blocks during idle time, maintaining consistent write speeds. Enabled by default in modern OS.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-10',
    topicId: 'topic-c1-3-4',
    front: 'What is S.M.A.R.T.?',
    back: 'Self-Monitoring, Analysis and Reporting Technology. Built-in monitoring system in both HDDs and SSDs that tracks indicators of drive health: reallocated sectors, spin-up time, read/write error rate, temperature, power-on hours, pending sectors.\n\nS.M.A.R.T. data can be read with tools (CrystalDiskInfo, smartctl). Warning indicators can predict failure before it occurs. Does NOT prevent failure — back up data immediately upon S.M.A.R.T. warning.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-11',
    topicId: 'topic-c1-3-4',
    front: 'What is optical storage capacity by disc type?',
    back: 'CD-ROM: 700 MB\nDVD-5: 4.7 GB (single-layer, single-side)\nDVD-9: 8.5 GB (dual-layer, single-side)\nDVD-10: 9.4 GB (single-layer, dual-side)\nBlu-ray BD-25: 25 GB (single-layer)\nBlu-ray BD-50: 50 GB (dual-layer)\nBlu-ray BD-100 (BDXL): 100 GB (triple-layer)\n\nR = write once, RW = rewritable (limited cycles).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-12',
    topicId: 'topic-c1-3-4',
    front: 'What is a hybrid drive (SSHD)?',
    back: 'Solid State Hybrid Drive combines a traditional spinning HDD with a small NAND flash cache (8–32 GB). Firmware automatically moves frequently accessed data to the SSD cache for faster access.\n\nPros: cheaper than full SSD, faster than pure HDD, transparent to the OS (appears as single drive).\nCons: SSD portion too small for all data, performance benefits are inconsistent, cache takes time to warm up after fresh boot.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-4-13',
    topicId: 'topic-c1-3-4',
    front: 'What is SAS storage?',
    back: 'Serial Attached SCSI. Enterprise-grade storage interface designed for servers and workstations. Supports multiple devices per controller, longer cable lengths than SATA, and higher reliability/performance. 12 Gbps current standard (SAS-3).\n\nSAS controllers can connect both SAS and SATA drives. SATA controllers CANNOT connect SAS drives. SAS drives often spin at 10,000–15,000 RPM. Dual-port capability for redundant paths.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.5 Motherboards and CPUs (13 cards) ────────────────────────────────────
  {
    id: 'fc-c1-3-5-01',
    topicId: 'topic-c1-3-5',
    front: 'What are the common motherboard form factors and their dimensions?',
    back: 'ATX: 305 × 244 mm — standard desktop, up to 7 PCIe slots.\nMicro-ATX (mATX): 244 × 244 mm — 4 PCIe slots max, fits ATX cases.\nMini-ITX: 170 × 170 mm — 1 PCIe slot, ultra-compact builds.\nE-ATX: 305 × 330 mm — high-end workstation/server.\n\nForm factor determines case compatibility and expansion slot count.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-02',
    topicId: 'topic-c1-3-5',
    front: 'What is the CPU socket? Compare Intel LGA vs AMD AM4/AM5.',
    back: 'CPU socket: the connector on the motherboard where the processor installs.\n\nIntel LGA (Land Grid Array): pins are in the socket, not the CPU. CPU bottom is flat with pads. Examples: LGA1700 (12th/13th/14th gen Core).\n\nAMD AM4: PGA (Pin Grid Array) — pins on CPU, socket has holes. Used through Ryzen 5000 series.\n\nAMD AM5: LGA design — AMD switched to socketless CPU for Ryzen 7000+. Both sides now use contacts.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-03',
    topicId: 'topic-c1-3-5',
    front: 'What is PCIe? List lane configurations and speeds per generation.',
    back: 'Peripheral Component Interconnect Express — high-speed serial bus for expansion cards.\n\nLane speeds (per direction):\nPCIe 3.0: ~1 GB/s per lane (8 GT/s signaling)\nPCIe 4.0: ~2 GB/s per lane (16 GT/s)\nPCIe 5.0: ~4 GB/s per lane (32 GT/s)\n\nConfigurations: ×1, ×4, ×8, ×16\nGPU typically uses ×16 slot. M.2 NVMe typically ×4.\nPhysical slot size ≠ electrical bandwidth (×4 card fits ×16 slot).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-04',
    topicId: 'topic-c1-3-5',
    front: 'What is UEFI and how does it differ from legacy BIOS?',
    back: 'UEFI (Unified Extensible Firmware Interface) replaced legacy BIOS:\n• Supports drives > 2 TB (uses GPT partition table; BIOS uses MBR, limited to 2 TB)\n• Mouse support in setup menus\n• Faster boot (native NVMe support)\n• Secure Boot (prevents unsigned bootloaders)\n• Network capabilities in pre-boot\n• 32/64-bit mode vs BIOS 16-bit real mode\n\nModern systems use UEFI. "Legacy mode" emulates BIOS for older OS compatibility.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-05',
    topicId: 'topic-c1-3-5',
    front: 'What is the CMOS battery and what happens when it dies?',
    back: 'A coin cell battery (typically CR2032, 3V) on the motherboard that powers the CMOS chip, preserving BIOS/UEFI settings (date/time, hardware configuration, passwords) when the computer is unplugged.\n\nSymptoms of dead CMOS battery:\n• System clock resets to defaults (Jan 1, year 2000 or similar) at every boot\n• BIOS settings lost after shutdown\n• "CMOS checksum error" message\n\nFix: Replace the CR2032 battery. BIOS settings will need to be reconfigured.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-06',
    topicId: 'topic-c1-3-5',
    front: 'What is the difference between CPU cores, threads, and Hyper-Threading?',
    back: 'Core: a physical independent processing unit inside the CPU die. Each core can execute its own instruction stream simultaneously.\n\nThread: a software-level concept; one stream of instructions.\n\nHyper-Threading (Intel) / SMT (AMD Simultaneous Multi-Threading): allows each physical core to run 2 threads by duplicating thread state hardware, keeping execution units busy during stalls. A 6-core CPU with HT = 12 threads visible to the OS.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-07',
    topicId: 'topic-c1-3-5',
    front: 'What is thermal paste and why is it necessary?',
    back: "Thermally conductive compound (usually silicone + metal oxide or liquid metal) applied as a thin layer between the CPU heat spreader and heatsink base.\n\nPurpose: fills microscopic surface imperfections and air gaps. Air has very low thermal conductivity (~0.025 W/m·K); thermal paste: ~4–8 W/m·K; liquid metal: ~70+ W/m·K.\n\nWithout thermal paste: CPU can overheat and throttle or sustain damage within seconds of load.",
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-08',
    topicId: 'topic-c1-3-5',
    front: 'What is CPU TDP?',
    back: "Thermal Design Power — the maximum sustained heat output the CPU's cooling solution must be designed to dissipate, measured in watts.\n\nTDP is a cooling specification, not an exact power draw. Under boost conditions CPUs can temporarily exceed TDP. 'PBP' (Intel) and 'TDP' (AMD) are the base power specifications.\n\nExamples: budget laptop CPU: 15W TDP; desktop i9: 125W TDP; server Xeon: 250W+ TDP.",
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-09',
    topicId: 'topic-c1-3-5',
    front: 'What are CPU cache levels (L1, L2, L3)?',
    back: 'L1: Smallest (32–64 KB per core), fastest (1–4 cycle latency). Split into L1-I (instructions) and L1-D (data). Closest to execution units.\n\nL2: Larger (256 KB – 4 MB per core), slightly slower (10–12 cycles). Unified cache.\n\nL3: Largest (8–64+ MB shared across all cores), slowest cache (30–50 cycles). Shared between cores for inter-core data sharing.\n\nAll caches are on-chip. L1>L2>L3>RAM in speed order.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-10',
    topicId: 'topic-c1-3-5',
    front: 'What is virtualization technology (VT-x / AMD-V)?',
    back: 'Hardware-level CPU feature that enables efficient execution of virtual machines.\n\nIntel VT-x (Virtualization Technology for IA-32/64): allows hypervisors (VMware, Hyper-V, VirtualBox) to run VMs without binary translation overhead.\nAMD-V (AMD Virtualization): equivalent AMD implementation.\n\nMust be enabled in BIOS/UEFI. Required for most modern hypervisors. VT-d (Intel) / AMD-Vi adds support for direct I/O device assignment to VMs (GPU passthrough).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-11',
    topicId: 'topic-c1-3-5',
    front: 'What is POST and what happens if it fails?',
    back: 'Power-On Self-Test — diagnostic routine run by BIOS/UEFI at startup before the OS loads. Tests: CPU, RAM, GPU, storage controllers, keyboard, basic I/O.\n\nPOST success: single beep (on systems with speaker), continues to bootloader.\nPOST failure indicators: beep codes (pattern indicates failed component), LED POST codes (on enthusiast motherboards), no display output.\n\nCommon failures: RAM not seated (beep code), no GPU installed, CPU overtemp.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-12',
    topicId: 'topic-c1-3-5',
    front: 'What is overclocking and what requirements does it have?',
    back: 'Running CPU, RAM, or GPU at speeds above manufacturer-rated specifications for higher performance.\n\nRequirements:\n• Unlocked CPU multiplier (Intel K/KF-series, AMD Ryzen standard)\n• Compatible motherboard (Intel Z-series; AMD X or B series)\n• Adequate cooling (often aftermarket air or AIO liquid cooler)\n• Stable power delivery (quality VRMs on motherboard)\n• May void warranty. Can cause instability or reduced component lifespan.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-5-13',
    topicId: 'topic-c1-3-5',
    front: 'What does the motherboard chipset do?',
    back: "The chipset manages communication between the CPU and peripheral devices. It's a companion chip (or integrated into the SoC) connecting: PCIe lanes (for lower-bandwidth devices), USB ports, SATA ports, M.2 slots, audio, LAN.\n\nModern Intel chipsets: H-series (basic consumer), B-series (mid, limited OC), Z-series (full overclock support).\nAMD chipsets: A-series (budget), B-series (mid), X-series (full features).\n\nCPU direct lanes (for primary GPU and fast NVMe) bypass the chipset.",
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.6 Power Supplies (10 cards) ───────────────────────────────────────────
  {
    id: 'fc-c1-3-6-01',
    topicId: 'topic-c1-3-6',
    front: 'List the 80 Plus efficiency certification tiers.',
    back: '80 Plus: 80% efficiency at 20/50/100% load\n80 Plus Bronze: 82/85/82%\n80 Plus Silver: 85/88/85%\n80 Plus Gold: 87/90/87%\n80 Plus Platinum: 90/92/89%\n80 Plus Titanium: 90/92/94% (highest)\n\nHigher efficiency = less power wasted as heat = lower electricity cost. Gold is the sweet spot for most desktop builds.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-6-02',
    topicId: 'topic-c1-3-6',
    front: 'What power connectors does a PSU provide to the motherboard?',
    back: '24-pin ATX (main power): the primary motherboard connector. Provides +3.3V, +5V, +12V, -12V, +5VSB, and control signals.\n\n4-pin or 8-pin EPS12V (CPU power): dedicated +12V connector for the CPU voltage regulator. High-end motherboards use 8-pin (2×4) or even dual 8-pin.\n\nOlder systems used 20-pin main (ATX) + 4-pin (ATX12V).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-6-03',
    topicId: 'topic-c1-3-6',
    front: 'What are the three PSU modular designs?',
    back: 'Non-modular: ALL cables permanently attached to PSU. Lowest cost. Unused cables clutter the case.\n\nSemi-modular: Main ATX and CPU cables are fixed. All other cables (PCIe, SATA, Molex) are detachable.\n\nFully modular: Every single cable is detachable. Best airflow and cable management. Most expensive.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-6-04',
    topicId: 'topic-c1-3-6',
    front: 'What voltage rails does a PSU supply, and what uses each?',
    back: '+12V: Main rail. Powers CPU (via EPS), GPU (via PCIe connectors), HDD/SSD motors, case fans. Highest current rail.\n+5V: Powers USB ports, older storage devices, some logic circuits. Less critical in modern systems.\n+3.3V: Powers RAM, chipset, and some low-power logic.\n-12V: Legacy, very low current. Used by some serial ports.\n+5VSB: Standby power (always on when PSU is plugged in). Enables USB wake, Wake-on-LAN.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-6-05',
    topicId: 'topic-c1-3-6',
    front: 'What is the SATA power connector?',
    back: 'A 15-pin flat L-shaped power connector providing +3.3V, +5V, and +12V to SATA drives (HDDs, SSDs, optical drives). Replaced the older 4-pin Molex connector for modern drives. The angled L-shape prevents incorrect insertion. One SATA power cable from PSU typically has multiple connectors for daisy-chaining.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-6-06',
    topicId: 'topic-c1-3-6',
    front: 'What is the 6+2 pin PCIe power connector?',
    back: '6+2 pin PCIe connector provides supplemental +12V power to discrete graphics cards. The "2" part can detach, making it usable as 6-pin OR 8-pin to support different GPU requirements.\n\n6-pin: ~75W additional power\n8-pin: ~150W additional power\nSome GPUs require multiple connectors. Very high-end GPUs now use the 16-pin 12VHPWR connector (600W).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-6-07',
    topicId: 'topic-c1-3-6',
    front: 'What is a Molex connector?',
    back: '4-pin large power connector (older AMP/Molex design) providing +5V (yellow) and +12V (red) rails. Originally powered IDE/PATA hard drives and optical drives.\n\nStill used for: some case fans, LED strips, older components. Being phased out — most modern storage uses SATA power.\n\nPin order: +12V (yellow), Ground (black), Ground (black), +5V (red).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-6-08',
    topicId: 'topic-c1-3-6',
    front: 'Why does a PC stay partially powered even when "off"?',
    back: "The PSU provides +5VSB (standby voltage) whenever it's plugged into mains power, even when the PC is 'off' (soft power-off state). The motherboard uses this to:\n• Power the front panel power button circuit\n• Enable Wake-on-LAN (WOL) — wake from network packet\n• Enable USB wake — keyboard/mouse press wakes system\n• Maintain real-time clock\n\nHard power off requires rear PSU switch or unplugging. Important for ESD safety when servicing.",
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-6-09',
    topicId: 'topic-c1-3-6',
    front: 'How do you perform a paperclip test on a PSU?',
    back: 'The paperclip test lets you verify a PSU powers on without a motherboard. On the 24-pin ATX connector, short pin 16 (PS_ON, green wire) to any ground (black wire) with a bent paperclip.\n\nThe PSU will turn on (fan spins). Test voltages on appropriate pins with a multimeter. +12V: ±5% (11.4–12.6V), +5V: ±5%, +3.3V: ±5%.\n\nCAUTION: PSU is energized during test. Do not touch components with bare hands.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-6-10',
    topicId: 'topic-c1-3-6',
    front: 'How do you determine what PSU wattage a system needs?',
    back: 'Add up component TDPs: CPU + GPU + storage + RAM + fans + peripherals.\n\nGeneral guidelines:\n• Basic office PC: 300–400W\n• Mid-range gaming: 550–650W\n• High-end gaming (RTX 4080): 750–850W\n• Add 20–30% headroom for efficiency and future upgrades\n\nPSUs are most efficient at ~50% load. Oversizing wastes money; undersizing causes instability or tripped OCP.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.7 Printers (13 cards) ─────────────────────────────────────────────────
  {
    id: 'fc-c1-3-7-01',
    topicId: 'topic-c1-3-7',
    front: 'What are the 7 steps of the laser printing process in order?',
    back: '1. Processing — RIP converts print job to bitmap in printer memory\n2. Charging — PCR/corona wire applies uniform ~-600V charge to drum\n3. Exposing — Laser selectively neutralizes drum areas (latent image)\n4. Developing — Negatively charged toner adheres to laser-exposed (less negative) areas\n5. Transferring — Transfer roller/corona attracts toner from drum onto paper\n6. Fusing — Heat (150–200°C) + pressure permanently bonds toner to paper\n7. Cleaning — Blade removes residual toner from drum for next cycle\n\nMnemonic: "Please Come Eat Delicious Tasty Fried Chicken"',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-02',
    topicId: 'topic-c1-3-7',
    front: 'What is the primary charge roller (PCR) in a laser printer?',
    back: "The PCR (or corona wire in older printers) applies a uniform negative charge (~-600V) to the photosensitive drum during the Charging step. This 'primes' the drum surface to accept the toner image.\n\nThe PCR is a conductive rubber roller that directly contacts the drum. Corona wires are older technology that uses high voltage through a fine wire but can produce ozone as a byproduct.",
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-03',
    topicId: 'topic-c1-3-7',
    front: 'How does the laser create the image on the drum?',
    back: "During the Exposing step, a laser beam (controlled by mirrors/polygonal mirror spinning at high speed) scans across the drum and selectively discharges specific areas to approximately -100V (from -600V). These discharged areas form the 'latent image' — invisible but present as an electrostatic pattern. The contrast between -600V (no toner) and -100V (toner) areas guides toner deposition.",
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-04',
    topicId: 'topic-c1-3-7',
    front: 'How is toner transferred from drum to paper?',
    back: "During Transferring, the transfer roller (or transfer corona wire) is charged positively (~+400V). As paper passes between the drum and transfer roller, the positively-charged roller attracts the negatively-charged toner particles from the drum onto the paper.\n\nThe toner is now on paper but not yet fixed — it's held only by static electricity and will smear if touched before fusing.",
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-05',
    topicId: 'topic-c1-3-7',
    front: 'What does the fuser assembly do, and why is it HOT?',
    back: "The fuser permanently bonds toner to paper using heat and pressure. The fuser roller (or fuser belt) is heated to 150–200°C — enough to melt the thermoplastic toner particles so they flow into paper fibers. A pressure roller squeezes the paper against the heated element.\n\nWhy it's hot: toner doesn't become liquid until ~180°C. This is why laser printers have a warm-up time and why you should never touch the fuser when servicing.",
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-06',
    topicId: 'topic-c1-3-7',
    front: 'How does an inkjet printer work?',
    back: 'Inkjet printers spray microscopic droplets of liquid ink through tiny nozzles onto paper.\n\nTwo nozzle technologies:\nThermal (piezo-bubble): heating element vaporizes ink, expanding bubble forces droplet out. Used by Canon, HP.\nPiezoelectric: electric charge deforms piezo crystal, physically pushing ink out. Used by Epson. More precise, works with more ink types.\n\nInk types: dye-based (vibrant, less water-resistant) vs pigment-based (durable, water-resistant, preferred for documents).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-07',
    topicId: 'topic-c1-3-7',
    front: 'What is a thermal printer and what two types exist?',
    back: 'Thermal printers use heat to create images without ink or toner.\n\nDirect thermal: prints on special heat-sensitive paper coated with chemicals that darken when heated. No ribbon needed. Used for receipts, labels, tickets. Prints fade over time with heat/light exposure.\n\nThermal transfer: uses a heated ribbon to transfer ink to regular paper or labels. More durable output, used for shipping labels, barcode labels, medical wristbands.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-08',
    topicId: 'topic-c1-3-7',
    front: 'What is an impact/dot matrix printer?',
    back: 'An impact printer creates images by striking pins against an ink-saturated ribbon to imprint dots onto paper. Multiple pins fire in patterns to form characters.\n\nKey characteristics: very noisy, slow, but can print on multi-part forms (carbon copies) — critical for invoices, receipts requiring duplicates. Still used in manufacturing, banking, shipping.\n\nDaisy wheel: older impact printer with letter-shaped spokes — letter quality text but no graphics. Obsolete.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-09',
    topicId: 'topic-c1-3-7',
    front: 'What is a 3D printer and how does FDM work?',
    back: '3D printers create physical objects by depositing material layer by layer.\n\nFDM (Fused Deposition Modeling): most common type. Thermoplastic filament (PLA, ABS, PETG) is fed through a heated extruder nozzle (~200°C), melted, and deposited on a build plate. Each layer fuses to the previous. Slow but inexpensive.\n\nSLA (Stereolithography): UV laser cures liquid photopolymer resin layer by layer. Very high precision, used for prototypes and dental/medical models.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-10',
    topicId: 'topic-c1-3-7',
    front: 'What is automatic duplexing in printers?',
    back: 'Duplexing = printing on both sides of a page. Automatic duplex: the printer mechanically flips the paper to print the second side without manual intervention. Reduces paper consumption by ~50%.\n\nSome lower-cost printers support manual duplexing only — print one side, prompt user to flip the paper stack and reload. Most business laser printers include automatic duplexer as standard or optional accessory.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-11',
    topicId: 'topic-c1-3-7',
    front: 'What is the difference between PCL and PostScript print languages?',
    back: 'PCL (Printer Control Language — HP): printer-dependent rendering. Faster for office text and simple graphics. Widely supported, good for everyday documents. Rendering done by the printer.\n\nPostScript (Adobe): device-independent, mathematical descriptions of output. Same output on any PS printer. Better for complex graphics, accurate font rendering, CMYK color. Standard in professional/graphic design workflows. Generally slower to process.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-12',
    topicId: 'topic-c1-3-7',
    front: 'What is a print server?',
    back: "A print server manages print jobs and connects printers to network clients. Types:\n\nDedicated hardware: small device with USB/parallel port for printer, connects to network. Example: HP Jetdirect box.\n\nBuilt-in: modern network printers have integrated print server with wired/wireless NIC.\n\nSoftware: a PC running print server software (Windows Print and Document Services) shares its local printers over the network.\n\nBenefit: multiple users can access shared printers without each PC needing a direct connection.",
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-7-13',
    topicId: 'topic-c1-3-7',
    front: 'What is printer DPI and how does it affect output?',
    back: 'DPI (Dots Per Inch) = number of dots printed per inch of paper. Higher DPI = sharper detail, smoother gradients, finer text.\n\nTypical DPI values:\nLaser printer text: 600–1200 DPI standard\nPhoto inkjet: 1200–9600 DPI (may use multiple ink passes)\nPlotters/wide format: 300–1200 DPI\n\nDPI is different from PPI (pixels per inch) which describes display and image resolution. Image resolution should match or exceed printer DPI for best results.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.8 Printer Maintenance (11 cards) ──────────────────────────────────────
  {
    id: 'fc-c1-3-8-01',
    topicId: 'topic-c1-3-8',
    front: 'How do you fix a clogged inkjet printhead?',
    back: '1. Run built-in head cleaning utility from printer software — uses ink suction to dislodge clogs.\n2. If still clogged, run 2–3 more cleaning cycles with breaks between.\n3. For severe clogs: remove printhead if removable and soak nozzle plate in warm distilled water for 1–2 hours.\n4. Dry gently with lint-free cloth before reinstalling.\n\nPrevent future clogs: print at least once per week; use high-quality ink; don\'t let ink dry in nozzles from disuse.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-02',
    topicId: 'topic-c1-3-8',
    front: 'What causes ghosting in laser printer output and how do you fix it?',
    back: 'Ghosting = faint repeated image appearing offset from the main print (like a ghost or shadow).\n\nCauses: worn photosensitive drum not fully discharging between cycles, weak primary charge roller, failed cleaning blade leaving residual toner.\n\nFix: replace the imaging drum/drum unit. In all-in-one toner cartridges, replace the whole cartridge. If drum is separate, replace drum only. Can also indicate weak fuser not fully bonding toner (secondary ghosting).',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-03',
    topicId: 'topic-c1-3-8',
    front: 'What causes smearing/smudging in laser printer output?',
    back: 'Smearing = toner rubs off after printing; pages smear when touched.\n\nPrimary cause: failed fuser assembly not reaching proper temperature or losing pressure, so toner doesn\'t bond fully to paper.\n\nOther causes: incorrect paper type (coated/glossy paper may not accept toner), high humidity causing paper moisture problems, fuser wiper pad worn.\n\nFix: replace the fuser assembly. Check paper type compatibility in printer specs.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-04',
    topicId: 'topic-c1-3-8',
    front: 'What causes vertical lines/streaks in laser printer output?',
    back: 'Vertical white lines: scratch or groove on photosensitive drum. Toner won\'t adhere to damaged area. Fix: replace drum/imaging unit.\n\nVertical dark lines: damaged developer roller distributing excess toner in a line pattern. Fix: replace toner cartridge/developer unit.\n\nVertical line from toner cartridge: debris or chip on developer roller. Try cleaning cartridge slot; if persistent, replace toner cartridge.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-05',
    topicId: 'topic-c1-3-8',
    front: 'What causes faded or light print in laser printers?',
    back: '1. Low toner: remove cartridge and gently shake side to side to redistribute toner — may get 50–100 more pages.\n2. Toner save/economy mode enabled in print settings — disable it.\n3. Print density setting too low — increase in printer preferences.\n4. Wrong paper type (too smooth/coated) — check paper compatibility.\n5. Drum worn out — failing drum doesn\'t hold charge properly.\n6. Transfer roller worn — not attracting enough toner to paper.\n\nIf shaking cartridge and adjusting settings don\'t work, replace toner cartridge.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-06',
    topicId: 'topic-c1-3-8',
    front: 'What is a laser printer maintenance kit and when is it used?',
    back: 'A maintenance kit contains the main wear parts replaced at a specified page count interval (typically 200,000 pages for commercial laser printers):\n\n• Fuser assembly\n• Transfer roller\n• Paper pickup rollers (main tray, multi-purpose tray)\n• Separator pads/retard rollers\n\nInstalling the kit at the prescribed interval prevents unexpected failures. After installation, the page counter must be reset in the printer service menu.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-07',
    topicId: 'topic-c1-3-8',
    front: 'What causes paper jams and how are they prevented?',
    back: 'Causes of paper jams:\n• Overfilled paper tray (max fill line exists for a reason)\n• Incorrect paper size/weight for printer specs\n• Worn pickup rollers (won\'t grab paper or grabs multiple sheets)\n• Misaligned paper guides (crooked paper path)\n• Damp, bent, torn, or previously used paper\n• Foreign objects in paper path\n\nPrevention: don\'t overfill, fan paper before loading, clean pickup rollers with isopropyl alcohol, set guides precisely, store paper in dry conditions.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-08',
    topicId: 'topic-c1-3-8',
    front: 'How do you safely handle and replace toner cartridges?',
    back: '1. Power down printer first (avoid toner being heated/scattered).\n2. Remove old cartridge slowly and keep upright to prevent spilling.\n3. Place in sealed bag for disposal — don\'t dump in trash (toner is fine particulate).\n4. New cartridge: remove packaging tape/seals, gently shake to distribute toner.\n5. If toner gets on skin: wash with cold water (hot water sets toner). On clothes: shake off, cold water wash.\n6. Clean any spilled toner with a toner vacuum (special ESD-safe vacuum). Never use regular vacuum — static spark + fine toner = fire/explosion risk.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-09',
    topicId: 'topic-c1-3-8',
    front: 'What safety hazards exist when servicing laser printers?',
    back: 'High voltage: laser printers contain high-voltage power supplies (up to 600V for corona wires). Capacitors may remain charged after power-off. Allow discharge time.\n\nHeat: fuser assembly operates at 150–200°C. Allow printer to cool 10+ minutes before servicing fuser area. Burns occur instantly on contact.\n\nToner particles: fine toner is a respiratory irritant. Wear gloves and face mask when cleaning. Never use compressed air (disperses particles into air/lungs).\n\nLaser beam: Class 3R/3B laser inside. Never defeat safety interlocks or look into laser apertures.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-10',
    topicId: 'topic-c1-3-8',
    front: 'What is calibration in inkjet printing?',
    back: 'Calibration aligns the printhead nozzles so that:\n1. Multiple passes of the printhead align precisely (no banding)\n2. Different color channels (CMYK) register correctly (no color fringing)\n3. Bidirectional printing (left and right passes) aligns perfectly\n\nWhen to calibrate: after replacing ink cartridges, after replacing the printhead, if print quality degrades, or when the printer is first set up. Run through the printer software/utility. Prints a test pattern you confirm or measure.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-3-8-11',
    topicId: 'topic-c1-3-8',
    front: 'What is the drum unit lifespan and when should it be replaced?',
    back: "The photosensitive drum has a finite lifespan rated by page yield (typically 10,000–50,000 pages depending on printer model).\n\nSigns drum needs replacement: ghosting images, light streaks, uneven print density, repeated toner specks.\n\nIn all-in-one cartridges: drum and toner are combined — replace whole cartridge each toner cycle.\n\nIn separate drum units: the drum outlasts multiple toner refills. Replace drum when image quality degrades despite fresh toner, or when the printer's drum life counter triggers a warning.",
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
]

export const SEED_FLASHCARDS = [
  ...CORE1_D3_FLASHCARDS,
  ...BATCH1_FLASHCARDS,
  ...BATCH2_FLASHCARDS,
  ...BATCH3_FLASHCARDS,
  ...BATCH4_FLASHCARDS,
  ...BATCH5_FLASHCARDS,
  ...BATCH6_FLASHCARDS,
  ...BATCH7_FLASHCARDS,
  ...BATCH8_FLASHCARDS,
]
