// 48 flashcards for CompTIA A+ 220-1202 Core 2 Domain 2: Security
// Covers objectives 2.1–2.6

const NOW = new Date().toISOString()

export const BATCH5_FLASHCARDS = [

  // ─── 2.1 Security Measures (8 cards) ──────────────────────────────────────

  {
    id: 'fc-c2-2-1-01',
    topicId: 'topic-c2-2-1',
    front: 'What is a mantrap and what specific physical threat does it prevent?',
    back: 'A mantrap is a two-door airlock entry system where the first door must fully close before the second door opens. Only one person can occupy the space at a time. It prevents tailgating — an unauthorized person following an authorized employee through a secure entrance. Standard in data centers and high-security server rooms.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-1-02',
    topicId: 'topic-c2-2-1',
    front: 'What are the three primary factor categories for multi-factor authentication (MFA)?',
    back: 'Something you KNOW — password, PIN, security question answer.\nSomething you HAVE — hardware token, authenticator app, smart card, FIDO2 key.\nSomething you ARE — fingerprint, retina scan, facial recognition, voice (biometrics).\n\nTrue MFA requires factors from at least two DIFFERENT categories. Two passwords = not MFA.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-1-03',
    topicId: 'topic-c2-2-1',
    front: 'What is the principle of least privilege?',
    back: 'Users and systems should be granted only the minimum permissions required to perform their job function — nothing more. An HR clerk does not need engineering file access. Service accounts should not run as SYSTEM. Excess privilege amplifies the damage of a compromised account. This is one of the most frequently tested security concepts on the A+ exam.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-1-04',
    topicId: 'topic-c2-2-1',
    front: 'What is the Zero Trust security model?',
    back: '"Never trust, always verify." Zero Trust rejects the assumption that internal network traffic is safe.\n\nCore principles:\n• Assume breach — operate as if attackers are already inside\n• Verify every request explicitly (identity, device health, location, risk)\n• Apply least privilege — just-in-time, just-enough access\n• Use micro-segmentation to limit lateral movement\n\nEspecially important for cloud and remote work environments.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-1-05',
    topicId: 'topic-c2-2-1',
    front: 'Compare the three access control models: DAC, MAC, and RBAC.',
    back: 'DAC (Discretionary Access Control): The resource OWNER decides who gets access. Example: NTFS file permissions set by the file\'s creator.\n\nMAC (Mandatory Access Control): POLICY (classification labels) determines access — not owners. Example: government systems using Top Secret / Secret / Unclassified labels.\n\nRBAC (Role-Based Access Control): Access granted based on JOB ROLE. Example: all Sales employees get CRM access.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-1-06',
    topicId: 'topic-c2-2-1',
    front: 'What is the difference between an IDS and an IPS?',
    back: 'IDS (Intrusion Detection System): MONITORS traffic and ALERTS on suspicious patterns. Detects but does NOT block. Passive device — sits out-of-band.\n\nIPS (Intrusion Prevention System): MONITORS and ACTIVELY BLOCKS suspicious traffic inline. Must be placed in the traffic path. Stops attacks in real time but can cause false positive blockages.\n\nMemory tip: Detection = alert only; Prevention = blocks.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-1-07',
    topicId: 'topic-c2-2-1',
    front: 'What physical security control directly counters shoulder surfing?',
    back: 'Privacy screens — polarized overlays applied to laptop or monitor screens that make the display unreadable from side angles. Only the person directly in front can see the screen clearly.\n\nShoulder surfing = someone next to you (on a plane, in a coffee shop) reading your screen. Privacy screens eliminate this threat without changing user behavior.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-1-08',
    topicId: 'topic-c2-2-1',
    front: 'What is a VPN and how does it protect data in transit?',
    back: 'A VPN (Virtual Private Network) creates an encrypted tunnel between a client device and a corporate network (or VPN server) over the public internet. All traffic through the tunnel is encrypted, protecting it from eavesdropping.\n\nCommon protocols: IPsec, SSL/TLS (OpenVPN), WireGuard.\nUse cases: remote work, securing public Wi-Fi connections, connecting branch offices.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.2 Windows Security Settings (8 cards) ──────────────────────────────

  {
    id: 'fc-c2-2-2-01',
    topicId: 'topic-c2-2-2',
    front: 'What is UAC (User Account Control) and what security risk does disabling it create?',
    back: 'UAC prevents unauthorized changes to Windows by prompting for administrator approval before any action requiring elevated privileges (installing software, modifying system settings). Configured in Control Panel > User Accounts or secpol.msc.\n\nDisabling UAC (Never Notify): malware running as a standard user can silently escalate to administrator privileges without triggering any warning — a significant security risk. Never disable in managed environments.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-2-02',
    topicId: 'topic-c2-2-2',
    front: 'What are the requirements for BitLocker, and what editions of Windows support it?',
    back: 'BitLocker is full-disk encryption (AES 128-bit or 256-bit) built into Windows.\n\nEdition requirement: Windows Pro, Enterprise, or Education ONLY — NOT available on Windows Home.\n\nTypical hardware requirement: TPM (Trusted Platform Module) chip on the motherboard. Without TPM, a USB startup key must be used instead.\n\nManaged via: Control Panel > BitLocker Drive Encryption, or command line: manage-bde.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-2-03',
    topicId: 'topic-c2-2-2',
    front: 'What is the BitLocker recovery key and when is it needed?',
    back: 'The BitLocker recovery key is a 48-digit numeric key used to unlock a BitLocker-encrypted drive when the normal unlock method fails.\n\nWhen needed: TPM detects hardware change, PIN is forgotten, drive moved to a different machine, hardware modification detected.\n\nMust be backed up BEFORE needed: Microsoft account, Azure AD, printed copy, USB drive, or saved to a separate file. If the recovery key is lost and normal unlock fails, data is permanently inaccessible.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-2-04',
    topicId: 'topic-c2-2-2',
    front: 'List the standard NTFS permissions from most restrictive to most permissive.',
    back: 'Read — view file contents and attributes only.\nList Folder Contents — view folder contents (folders only).\nRead & Execute — view and run files, traverse folders.\nWrite — create and modify files and folders.\nModify — read, write, modify, and delete.\nFull Control — all of the above, plus change permissions and take ownership.\n\nKey rules: Deny overrides Allow. Effective permissions = cumulative union of all Allow permissions (minus any Deny).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-2-05',
    topicId: 'topic-c2-2-2',
    front: 'When both NTFS permissions and Share permissions apply to a file accessed over the network, which takes precedence?',
    back: 'The MORE RESTRICTIVE of the two wins.\n\nExample: If Share permission = Full Control AND NTFS permission = Read, the effective permission when accessing over the network is Read.\n\nLocal access: only NTFS permissions apply (share permissions are irrelevant for local access).\nNetwork access: NTFS AND share permissions both apply — the more restrictive effective permission wins.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-2-06',
    topicId: 'topic-c2-2-2',
    front: 'What is EFS (Encrypting File System) and how does it differ from BitLocker?',
    back: 'EFS: file-level encryption for individual files/folders on NTFS volumes. Tied to the user\'s certificate — only that user (and designated recovery agents) can decrypt. Encrypted files appear green in Explorer. Transparent to the authenticated owner.\n\nBitLocker: full-volume encryption — the entire drive is encrypted.\n\nThey can be used together: BitLocker protects the drive if physically removed; EFS protects individual files from other OS users on the same machine.\n\nEFS risk: if user certificate is lost (profile deleted), files may be permanently inaccessible.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-2-07',
    topicId: 'topic-c2-2-2',
    front: 'What is secpol.msc (Local Security Policy) and what are its key configuration sections?',
    back: 'secpol.msc = Local Security Policy snap-in. Available on Windows Pro, Enterprise, Education only.\n\nKey sections:\n• Account Policies > Password Policy — minimum length, complexity, age, history\n• Account Policies > Account Lockout Policy — threshold, duration, reset counter\n• Local Policies > User Rights Assignment — who can log on locally, shut down, etc.\n• Local Policies > Audit Policy — what events to log\n• Local Policies > Security Options — UAC settings, network access behavior\n\nNote: On domain-joined machines, Group Policy from the DC overrides Local Security Policy.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-2-08',
    topicId: 'topic-c2-2-2',
    front: 'What is Windows Hello and how does a Hello PIN differ from an account password?',
    back: 'Windows Hello provides biometric and PIN-based authentication.\nMethods: facial recognition (requires IR camera), fingerprint (requires sensor), PIN (no special hardware).\n\nPIN vs. Password:\n• A Windows Hello PIN is DEVICE-SPECIFIC — stored locally, only works on the device it was set up on.\n• A password is account-wide and works on any device.\n• If someone knows your PIN, they cannot use it to log in from another machine — making a PIN more secure than a password in many scenarios.\n\nWindows Hello uses asymmetric cryptography; private key never leaves the device.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.3 Wireless Security (8 cards) ──────────────────────────────────────

  {
    id: 'fc-c2-2-3-01',
    topicId: 'topic-c2-2-3',
    front: 'List the four wireless security protocols in order from oldest to newest, with their encryption methods.',
    back: 'WEP (1999) — RC4, 40-bit or 104-bit keys. Completely broken. Never use.\nWPA (2003) — TKIP (RC4-based). Deprecated. Do not use on new deployments.\nWPA2 (2004) — AES-CCMP (128-bit). Current standard. Still widely used.\nWPA3 (2018) — SAE + AES-GCMP-256. Current preferred standard.\n\nMemory pairing: WPA = TKIP. WPA2 = AES-CCMP. WPA3 = SAE.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-3-02',
    topicId: 'topic-c2-2-3',
    front: 'Why is WEP completely broken and unusable?',
    back: 'WEP (Wired Equivalent Privacy, 1999) uses RC4 with a critically flawed initialization vector (IV) implementation:\n• Static, manually configured keys that never change automatically\n• IVs repeat frequently, enabling statistical cryptanalysis\n• No protection against replay or injection attacks\n\nResult: An attacker with freely available tools can crack a WEP key in under 10 minutes by passively capturing traffic. There is NO scenario where WEP should be used. Replace any device that only supports WEP.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-3-03',
    topicId: 'topic-c2-2-3',
    front: 'Compare WPA2-Personal (PSK) vs. WPA2-Enterprise (802.1X).',
    back: 'WPA2-Personal (PSK):\n• One shared passphrase for ALL users\n• Simple — no infrastructure needed\n• Risk: one compromised device exposes the key to everyone\n• Vulnerable to offline dictionary attacks\n• Suitable for home and small business\n\nWPA2-Enterprise (802.1X):\n• Each user has INDIVIDUAL credentials\n• Requires RADIUS server\n• Revoke one user without changing everyone\'s key\n• Supports certificates (EAP-TLS)\n• Used in corporate and education environments',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-3-04',
    topicId: 'topic-c2-2-3',
    front: 'What is SAE and why does WPA3 use it instead of PSK?',
    back: 'SAE (Simultaneous Authentication of Equals), also called Dragonfly, replaces the PSK handshake in WPA3-Personal.\n\nWPA2-PSK weakness: an attacker captures the 4-way handshake and runs it through an offline password cracker.\n\nSAE fixes this by:\n1. Forward secrecy — past traffic cannot be decrypted even if the passphrase is later stolen\n2. Resistance to offline attacks — each guess requires real-time interaction with the AP, making offline cracking impossible\n\nWPA3-Enterprise additionally uses 192-bit GCMP-256 vs. WPA2\'s 128-bit AES.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-3-05',
    topicId: 'topic-c2-2-3',
    front: 'Describe the three roles in an 802.1X authentication exchange.',
    back: 'Supplicant — the CLIENT device requesting network access.\n\nAuthenticator — the ACCESS POINT (or switch). Blocks all traffic except authentication traffic until the supplicant is verified. Acts as a relay between client and server.\n\nAuthentication Server — the RADIUS server. Verifies credentials and instructs the authenticator to allow or deny access.\n\nWithout a valid RADIUS authentication, the client cannot pass any network traffic — not even to DHCP.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-3-06',
    topicId: 'topic-c2-2-3',
    front: 'Compare EAP-TLS vs. PEAP for wireless enterprise authentication.',
    back: 'EAP-TLS:\n• BOTH client and server present digital certificates (mutual authentication)\n• Most secure EAP method — no shared secret\n• Requires PKI and client certificate on every device\n• Highest security, highest administrative overhead\n\nPEAP (Protected EAP):\n• Only the SERVER presents a certificate\n• Server cert creates an encrypted tunnel, then client authenticates with username/password (MS-CHAPv2)\n• Most common in enterprise — easier to deploy than EAP-TLS\n• Less secure than EAP-TLS because client uses password',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-3-07',
    topicId: 'topic-c2-2-3',
    front: 'What is RADIUS and what ports does it use?',
    back: 'RADIUS (Remote Authentication Dial-In User Service) is the standard AAA (Authentication, Authorization, Accounting) protocol used as the authentication server in 802.1X deployments.\n\nPorts:\n• UDP 1812 — authentication and authorization\n• UDP 1813 — accounting (session start/stop logging)\n\nPrimary use: end-user network access — Wi-Fi, VPN.\nCommon implementations: Windows NPS, FreeRADIUS, Cisco ISE.\n\nNot to be confused with TACACS+ (TCP port 49, used for network device admin).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-3-08',
    topicId: 'topic-c2-2-3',
    front: 'Compare RADIUS vs. TACACS+ — when is each used?',
    back: 'RADIUS:\n• Protocol: UDP (ports 1812/1813)\n• Encrypts: password only\n• Primary use: end-user NETWORK ACCESS (Wi-Fi, VPN)\n• Standard: open standard\n\nTACACS+:\n• Protocol: TCP port 49\n• Encrypts: entire payload\n• Primary use: NETWORK DEVICE ADMINISTRATION (admins SSH-ing into routers and switches)\n• Standard: Cisco proprietary\n• Separates authentication, authorization, and accounting independently\n\nExam tip: Wi-Fi/VPN users = RADIUS. Router/switch admins = TACACS+.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.4 Malware (8 cards) ────────────────────────────────────────────────

  {
    id: 'fc-c2-2-4-01',
    topicId: 'topic-c2-2-4',
    front: 'What is the critical difference between a virus and a worm?',
    back: 'Virus:\n• Attaches to existing files or programs\n• Requires USER to EXECUTE the infected file to spread\n• Spreads when infected files are shared between users\n• Examples: CIH (Chernobyl), macro viruses in Office documents\n\nWorm:\n• Standalone program — does not need a host file\n• Spreads AUTOMATICALLY without any user action\n• Exploits network services and vulnerabilities\n• Can infect thousands of machines in minutes\n• Examples: WannaCry, Code Red, Blaster\n\nExam key: "spread without anyone clicking anything" = WORM.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-4-02',
    topicId: 'topic-c2-2-4',
    front: 'What is a Trojan and how does it differ from a virus and worm?',
    back: 'A Trojan disguises itself as legitimate or useful software to convince the user to install it (game, utility, software crack, fake antivirus).\n\nKey differences:\n• Does NOT self-replicate (unlike a virus or worm)\n• Relies on SOCIAL ENGINEERING — the user must choose to install it\n• The "legitimate" functionality is bait\n• Hidden payload: backdoor, ransomware, keylogger, spyware\n\nOnce installed, Trojans can open backdoors, exfiltrate data, install additional malware, or create a botnet node.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-4-03',
    topicId: 'topic-c2-2-4',
    front: 'What are the hallmark symptoms of ransomware, and what is the recommended recovery method?',
    back: 'Symptoms:\n• Sudden inability to open files\n• File extensions changed (.locked, .encrypted, .crypt)\n• Ransom note on desktop or in folders\n• Excessive disk activity (encryption in progress)\n\nDo NOT pay the ransom — no guarantee of decryption key; funds criminal operations.\n\nRecovery:\n1. Restore from a clean offline/offsite backup (pre-infection)\n2. Check NoMoreRansom.org for free decryptors\n3. Report to FBI IC3 and local law enforcement\n4. If no backup exists, engage a reputable incident response firm',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-4-04',
    topicId: 'topic-c2-2-4',
    front: 'Why are rootkits the most difficult malware type to remove?',
    back: 'Rootkits embed themselves at the KERNEL level of the operating system and intercept OS calls to hide:\n• Their own files, processes, and registry entries\n• Other malware they install\n• Network connections\n\nProblem: standard AV scanning inside the infected OS cannot detect what the OS is hiding. A clean scan result does NOT mean the system is clean.\n\nRemoval: requires a BOOTABLE scanner (Windows Defender Offline, Kaspersky Rescue Disk) that loads a separate, clean OS. In severe cases — wipe and reinstall.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-4-05',
    topicId: 'topic-c2-2-4',
    front: 'What is fileless malware and why does it evade traditional antivirus?',
    back: 'Fileless malware never writes executable code to disk. It executes entirely in memory using legitimate OS tools:\n• PowerShell\n• Windows Management Instrumentation (WMI)\n• Scheduled tasks\n• Office macros\n\nWhy it evades AV: traditional antivirus scans FILES on disk — there are no malicious files to detect.\n\nIndicators: suspicious PowerShell commands, unusual WMI subscriptions, processes spawned from Office applications, unexpected scheduled tasks.\n\nDetection: behavior-based AV, EDR solutions, memory scanning.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-4-06',
    topicId: 'topic-c2-2-4',
    front: 'What is a logic bomb and who typically plants one?',
    back: 'A logic bomb is malicious code hidden inside otherwise legitimate software that activates only when a specific trigger condition is met:\n• A date or time (Friday the 13th, last day of employment)\n• A user action (logging in as a specific user)\n• A database event (a record being deleted)\n\nTypically planted by: disgruntled insiders (developers, sysadmins) with access to the codebase or systems.\n\nKey characteristic: remains dormant and undetected until triggered — making it very hard to find proactively.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-4-07',
    topicId: 'topic-c2-2-4',
    front: 'What is the Autoruns tool and why is it useful for malware analysis?',
    back: 'Autoruns (Sysinternals / Microsoft) is the most comprehensive tool for finding malware persistence mechanisms. It displays every location Windows uses to auto-start programs:\n• Registry Run keys (HKLM and HKCU)\n• Scheduled tasks\n• Browser extensions\n• Drivers and services\n• Boot sector entries\n• Logon scripts\n\nMalware survival = persistence. If Autoruns shows an unknown or suspicious entry, it is a high-priority investigation lead. Includes VirusTotal integration to check entries against known malware hashes.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-4-08',
    topicId: 'topic-c2-2-4',
    front: 'Match each malware symptom to its most likely cause.',
    back: 'Encrypted files + ransom note → Ransomware\nHigh CPU usage at idle + excessive heat → Cryptominer\nAntivirus disabled, security tools won\'t open → Rootkit or advanced Trojan\nUnknown pop-up ads, browser redirects → Adware / browser hijacker\nExcessive outbound network traffic → Botnet C2 communication or spyware exfiltration\nNew browser toolbar, homepage changed → Browser hijacker / PUP\nSuspicious PowerShell activity, no files on disk → Fileless malware\nFiles shared and users executing them spread infection → Virus',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.5 Social Engineering (8 cards) ────────────────────────────────────

  {
    id: 'fc-c2-2-5-01',
    topicId: 'topic-c2-2-5',
    front: 'Distinguish phishing, spear phishing, and whaling.',
    back: 'Phishing: mass fraudulent emails impersonating trusted organizations (bank, Microsoft, IRS). Generic targets, generic content.\n\nSpear phishing: TARGETED phishing using personal details about the specific victim (their name, manager, recent project). Far more convincing than generic phishing.\n\nWhaling: spear phishing aimed specifically at C-SUITE EXECUTIVES (CEO, CFO, board). High-value targets who can authorize large wire transfers or access to sensitive data.\n\nAll three use email as the primary vector.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-5-02',
    topicId: 'topic-c2-2-5',
    front: 'What are vishing and smishing?',
    back: 'Vishing (Voice phishing): uses PHONE CALLS to manipulate victims. Attacker impersonates IT support, bank, IRS, or tech support ("Microsoft has detected a virus on your computer").\n\nSmishing (SMS phishing): uses TEXT MESSAGES with malicious links or requests. Common lures: fake package delivery, bank alerts, government notices.\n\nDefenses:\n• Vishing: never give credentials by phone; hang up and call the company directly on a known number\n• Smishing: never click links in unsolicited SMS; navigate directly to the official site',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-5-03',
    topicId: 'topic-c2-2-5',
    front: 'What is the difference between tailgating and piggybacking?',
    back: 'Tailgating: attacker follows an authorized employee through a secure door WITHOUT the authorized person\'s knowledge or cooperation — slipping through before the door closes.\n\nPiggybacking: the authorized person ACTIVELY holds the door open for the attacker — often because the attacker appears to need assistance (carrying boxes, looks rushed).\n\nBoth bypass physical access controls.\nDefenses: mantraps (physical barrier), challenge policy (employees ask anyone without a badge to stop), badge readers on both sides of doors.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-5-04',
    topicId: 'topic-c2-2-5',
    front: 'What is dumpster diving and how should organizations defend against it?',
    back: 'Dumpster diving: searching discarded documents and hardware for sensitive information useful in an attack — employee directories, account numbers, internal diagrams, printed credentials.\n\nDefenses:\n• Cross-cut shred ALL documents with any sensitive information (not strip-cut — strips can be reassembled)\n• Wipe or physically destroy storage media before disposal\n• Lock dumpsters and bins containing sensitive material\n• Policy: no sensitive data in regular trash',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-5-05',
    topicId: 'topic-c2-2-5',
    front: 'What is Business Email Compromise (BEC) and what technical email standards help prevent it?',
    back: 'BEC: attackers compromise or spoof an executive\'s email account and instruct finance or HR to make fraudulent wire transfers or disclose sensitive payroll data. FBI IC3 lists BEC as the highest-dollar-loss internet crime category.\n\nTechnical defenses:\n• SPF (Sender Policy Framework) — validates which mail servers can send on behalf of a domain\n• DKIM (DomainKeys Identified Mail) — cryptographic signature verifying message integrity\n• DMARC — policy that tells receiving servers what to do when SPF/DKIM fail\n\nProcess defenses: out-of-band verification (phone call) for all wire transfer requests.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-5-06',
    topicId: 'topic-c2-2-5',
    front: 'What are six warning signs of a phishing email?',
    back: '1. Generic greeting — "Dear Customer" or "Dear User" instead of your name\n2. Urgency / threats — "Account suspended," "Immediate action required"\n3. Mismatched URL — link text says paypal.com but hovering shows paypa1.com or paypal.security-check.ru\n4. Spelling and grammar errors — legitimate organizations proofread\n5. Unexpected attachments — invoices or "secure documents" you did not request\n6. Requests for credentials — no legitimate service asks for your password via email\n7. Sender domain mismatch — support@apple-security-alert.com is not Apple',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-5-07',
    topicId: 'topic-c2-2-5',
    front: 'What is pretexting in social engineering?',
    back: 'Pretexting is creating a fabricated scenario (pretext) to justify an unusual or suspicious request. The attacker invents a believable context to lower the victim\'s guard.\n\nExamples:\n• "I\'m from IT and I\'m fixing a server issue — I need your login to check your account"\n• "I\'m a vendor auditor — I need access to your network closet"\n• "This is your bank\'s fraud department — I need to verify your full card number"\n\nDefense: train staff to verify unusual requests through independent channels, regardless of how plausible the pretext sounds.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-5-08',
    topicId: 'topic-c2-2-5',
    front: 'What psychological principles do social engineers exploit to manipulate victims?',
    back: '• Authority — people comply with those in perceived power (IT, management, government)\n• Urgency / Fear — "Your account closes in 24 hours" — pressure prevents careful thinking\n• Trust — we assume people are who they claim to be\n• Reciprocity — if someone does you a favor, you feel obligated to return it\n• Social proof — "Everyone else has already done this"\n• Scarcity — "This is your only chance"\n\nSecurity awareness training teaches employees to recognize these manipulation tactics and pause before complying with unusual requests.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.6 Malware Removal (8 cards) ───────────────────────────────────────

  {
    id: 'fc-c2-2-6-01',
    topicId: 'topic-c2-2-6',
    front: 'List the CompTIA 8-step malware removal process in order.',
    back: '1. Investigate and verify malware symptoms\n2. Quarantine the infected system (disconnect from network)\n3. Disable System Restore in Windows\n4. Remediate the infected system (scan and remove)\n5. Schedule scans and run updates\n6. Re-enable System Restore and create a restore point\n7. Educate the end user\n8. Document findings, actions, and outcomes\n\nThe sequence matters — each step builds on the previous one. Exam questions ask "what should the technician do NEXT?"',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-6-02',
    topicId: 'topic-c2-2-6',
    front: 'Why must System Restore be disabled before cleaning a malware infection, and when is it re-enabled?',
    back: 'System Restore creates point-in-time snapshots of system files. If malware existed BEFORE restore points were created, those restore points contain the malware.\n\nWithout disabling System Restore first: after you clean the infection, a user (or the malware itself) could restore a snapshot and bring the malware back.\n\nStep 3: DISABLE System Restore (right-click This PC > Properties > System Protection > Configure > Disable)\n\nStep 6: Re-ENABLE System Restore and create a NEW, clean restore point to establish a known-good baseline.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-6-03',
    topicId: 'topic-c2-2-6',
    front: 'What are Safe Mode, Safe Mode with Networking, and Safe Mode with Command Prompt — and when is each used?',
    back: 'Safe Mode: starts Windows with minimal drivers and services. Most malware cannot load. Use when: malware blocks normal scanning, tools are available locally.\n\nSafe Mode with Networking: Safe Mode + network drivers. Use when: need to download updated scanners or definitions during remediation.\n\nSafe Mode with Command Prompt: Safe Mode without Explorer shell — only a command prompt. Use when: advanced manual troubleshooting, Explorer is compromised.\n\nAccess in Win 10/11: hold Shift > click Restart > Troubleshoot > Advanced Options > Startup Settings > Restart > press 4/5.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-6-04',
    topicId: 'topic-c2-2-6',
    front: 'When should a technician wipe and reinstall rather than attempt to clean an infected machine?',
    back: 'Wipe and reinstall when:\n• Confirmed rootkit — kernel is compromised; OS cannot be trusted\n• Ransomware with encrypted files — restore from backup instead\n• Persistent reinfection — malware keeps returning after cleaning (hidden persistence mechanism)\n• OS files modified — system integrity compromised; backdoors may remain\n• Critical business system with a clean backup — faster and guaranteed clean\n\nWhen in doubt — wipe and reinstall. A clean OS takes 30–60 minutes. An undetected backdoor can cause damage for months.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-6-05',
    topicId: 'topic-c2-2-6',
    front: 'What is Windows Defender Offline scan and when should it be used?',
    back: 'Windows Defender Offline scan reboots the computer into a minimal, clean environment and scans BEFORE the main Windows OS loads.\n\nWhen to use:\n• Malware is active in memory and blocking normal scans\n• Rootkit is suspected\n• Standard scan completes clean but symptoms persist\n\nAccess: Settings > Windows Security > Virus & Threat Protection > Scan Options > Microsoft Defender Antivirus Offline Scan.\n\nEffective because: malware cannot load and hide itself before the scan runs. Alternative: Kaspersky Rescue Disk, Bitdefender Rescue (bootable USB).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-6-06',
    topicId: 'topic-c2-2-6',
    front: 'What are the specific ransomware handling steps according to CompTIA guidance?',
    back: '1. Do NOT pay the ransom — no guarantee of decryption; funds criminals; marks you as a paying target\n2. Check NoMoreRansom.org — free decryptors exist for many strains\n3. Restore from clean offline backup (pre-infection, not network-connected)\n4. Report to FBI Internet Crime Complaint Center (IC3) and local law enforcement\n5. Preserve evidence — image the encrypted drive before wiping if forensics or law enforcement is likely\n6. Regulated industries (healthcare, finance) may have mandatory breach notification requirements',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-6-07',
    topicId: 'topic-c2-2-6',
    front: 'What does quarantining an infected machine accomplish, and what connections must be severed?',
    back: 'Quarantine (Step 2) = disconnect the machine from ALL networks immediately.\n\nSever:\n• Ethernet cable (unplug physically)\n• Wi-Fi (disable adapter)\n• Bluetooth (disable if active)\n\nWhy it matters:\n1. Prevents malware from spreading laterally to other machines on the network\n2. Cuts off command-and-control (C2) communication — many malware variants cannot function or exfiltrate data without C2 contact\n\nFor high-risk situations (active ransomware spreading): consider physically relocating the machine to prevent accidental reconnection.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-2-6-08',
    topicId: 'topic-c2-2-6',
    front: 'Why is educating the end user an important step in the malware removal process?',
    back: 'Step 7 (Educate the End User) is required because most malware requires some user action to get in. Without addressing user behavior, the same machine is likely to be reinfected.\n\nWhat to cover:\n• How to recognize phishing emails and suspicious links\n• Why not to download software from unofficial sources\n• Why not to run unexpected executable attachments\n• Importance of keeping software updated\n• Who to contact if they suspect a problem\n\nThis step has the highest long-term ROI of all remediation steps — a trained user is significantly harder to re-infect.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

]
