// 48 flashcards for CompTIA A+ 220-1202 Core 2 Domain 1: Operating Systems
// Covers objectives 1.1–1.6

const NOW = new Date().toISOString()

export const BATCH3_FLASHCARDS = [

  // ─── 1.1 Common OS Types (8 cards) ─────────────────────────────────────────

  {
    id: 'fc-c2-1-1-01',
    topicId: 'topic-c2-1-1',
    front: 'What are the four OS categories tested on the A+ Core 2 exam, and a primary example of each?',
    back: '1. Workstation — Windows 10/11, macOS, Ubuntu Desktop (single interactive user, GUI-focused)\n2. Server — Windows Server, RHEL, Ubuntu Server (always-on, multi-user, centralized services)\n3. Mobile — iOS, Android (ARM processors, touch-first, battery-optimized)\n4. Embedded/IoT — RTOS (VxWorks, FreeRTOS), embedded Linux (single-purpose, no general UI)',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-1-02',
    topicId: 'topic-c2-1-1',
    front: 'What is a Real-Time Operating System (RTOS) and when is it used?',
    back: 'An RTOS is designed to process inputs and produce outputs within strict, predictable time constraints. Used in industrial controllers, medical devices (infusion pumps), automotive systems, and avionics where microsecond response times are required. Examples: VxWorks, FreeRTOS, QNX.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-1-03',
    topicId: 'topic-c2-1-1',
    front: 'What are the additional hardware requirements for Windows 11 compared to Windows 10?',
    back: 'Windows 11 requires:\n• TPM 2.0 (required, not just recommended)\n• Secure Boot capability\n• 64-bit dual-core CPU at 1 GHz+ (from a supported CPU list)\n• 4 GB RAM (vs 2 GB for Win 10 64-bit)\n• 64 GB storage (vs 32 GB for Win 10 64-bit)\n• DirectX 12 compatible GPU with WDDM 2.0 driver\nTPM is the most common reason upgrades fail — check UEFI settings (PTT on Intel, fTPM on AMD).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-1-04',
    topicId: 'topic-c2-1-1',
    front: 'What is MDM and which mobile platforms support it?',
    back: 'MDM (Mobile Device Management) lets IT administrators enforce security policies, push configurations, remotely wipe devices, and manage app deployment across a fleet of mobile devices. Both iOS and Android support MDM enrollment. Used for BYOD (Bring Your Own Device) and corporate-liable deployments.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-1-05',
    topicId: 'topic-c2-1-1',
    front: 'What OS is ideal for a K-12 school district wanting cheap, centrally managed laptops?',
    back: 'ChromeOS (Chromebooks). Key advantages:\n• Extremely low-cost hardware\n• Boots in seconds from a read-only OS partition\n• Managed centrally via Google Admin console\n• Automatic updates, resistant to traditional malware\n• Supports web, Android, and Linux apps\n• Ideal when users only need web apps and cloud storage',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-1-06',
    topicId: 'topic-c2-1-1',
    front: 'What is the practical RAM limit of a 32-bit OS, and why?',
    back: 'A 32-bit OS can address a maximum of 4 GB of RAM (2^32 bytes). In practice, only about 3.2 GB is usable because some address space is reserved for hardware and memory-mapped I/O. A 64-bit OS can address a theoretical maximum of 18.4 exabytes.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-1-07',
    topicId: 'topic-c2-1-1',
    front: 'On a 64-bit Windows system, what is stored in System32 vs SysWOW64?',
    back: 'System32 — holds 64-bit DLLs (despite the name)\nSysWOW64 — holds 32-bit DLLs (WOW64 = Windows 32-bit On Windows 64-bit)\nThe naming is counterintuitive but historical. 16-bit applications from the Windows 95/98 era will NOT run on 64-bit Windows at all.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-1-08',
    topicId: 'topic-c2-1-1',
    front: 'Compare iOS vs Android from an enterprise management perspective.',
    back: 'iOS: Apple devices only; curated App Store; no sideloading by default; strong privacy controls; MDM via Apple Business Manager.\nAndroid: Many manufacturers; Google Play + sideloading allowed; highly customizable; MDM via Google Workspace or third-party EMM; open-source base (AOSP).\nBoth support MDM enrollment for remote wipe, policy enforcement, and app management.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.2 OS Installations & Upgrades (8 cards) ─────────────────────────────

  {
    id: 'fc-c2-1-2-01',
    topicId: 'topic-c2-1-2',
    front: 'When should you choose a clean install vs an in-place upgrade?',
    back: 'Clean install: new hardware, severe malware, major OS version jump (e.g., 32-bit → 64-bit), persistent problems, corrupt OS. Wipes everything — stable, predictable result.\nIn-place upgrade: compatible hardware, user wants to preserve apps/settings, single machine. Creates Windows.old for 10-day rollback. Cannot cross architectures.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-2-02',
    topicId: 'topic-c2-1-2',
    front: 'What is PXE boot and what infrastructure does it require?',
    back: 'PXE (Preboot Execution Environment) allows a computer to boot and load an OS image from the network without local media.\nRequires: PXE-capable NIC, DHCP server (provides IP + TFTP server address), TFTP server (serves the bootloader), and WDS or similar deployment server.\nUsed for enterprise imaging — one technician can deploy to hundreds of machines simultaneously.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-2-03',
    topicId: 'topic-c2-1-2',
    front: 'Compare MBR vs GPT partition schemes.',
    back: 'MBR: max disk size 2 TB, max 4 primary partitions, compatible with Legacy BIOS, boot code in first 512 bytes, no redundancy.\nGPT: max disk size 9.4 ZB, up to 128 primary partitions, required for UEFI boot, each partition has a GUID, backup partition table stored at end of disk, CRC32 checksums.\nRule: UEFI + GPT = modern. Legacy BIOS + MBR = older. Disk >2 TB must use GPT.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-2-04',
    topicId: 'topic-c2-1-2',
    front: 'What is the FAT32 file size limit, and what file system should replace it for large removable drives?',
    back: 'FAT32 maximum file size: 4 GB. Attempting to copy a file larger than 4 GB to a FAT32 drive fails even with sufficient free space.\nSolution: reformat as exFAT. exFAT supports files up to 128 PB, has no 4 GB limit, is cross-platform (Windows, macOS, Linux), and is ideal for large USB drives, SD cards, and video files.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-2-05',
    topicId: 'topic-c2-1-2',
    front: 'What are the key features of NTFS that distinguish it from FAT32?',
    back: 'NTFS provides:\n• Journaling — recovers from unexpected shutdowns without data corruption\n• ACL Permissions — read/write/execute per user and group\n• EFS (Encrypting File System) — file-level encryption tied to user account\n• Compression — native file/folder compression\n• Quotas — limit disk space per user\n• Max file size: 16 TB (practical); max volume: 256 TB\nFAT32 has none of these features.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-2-06',
    topicId: 'topic-c2-1-2',
    front: 'What is Sysprep and why must it be run before capturing a Windows image?',
    back: 'Sysprep (System Preparation Tool) generalizes a Windows installation by removing machine-specific information: Security Identifier (SID), hardware identifiers, and activation state. Run with: sysprep /oobe /generalize /shutdown. Without generalization, all deployed machines would share the same SID, causing conflicts in Active Directory. Sysprep is a mandatory step before DISM image capture.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-2-07',
    topicId: 'topic-c2-1-2',
    front: 'What does the Windows.old folder contain, and how long is it kept?',
    back: 'Windows.old is created after an in-place upgrade and contains the previous Windows installation (system files, program files, and user data from before the upgrade). It enables rollback via Settings > Recovery > Go back within 10 days. After 10 days, the rollback option disappears. Windows.old can be deleted manually using Disk Cleanup to reclaim disk space.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-2-08',
    topicId: 'topic-c2-1-2',
    front: 'What file system does each major OS use natively?',
    back: 'Windows — NTFS (system drives); FAT32/exFAT for removable media\nmacOS — APFS (SSD-optimized, snapshots, encryption)\nLinux — ext4 (journaling, large files, Linux-native)\nCross-platform removable media — FAT32 (max 4 GB files) or exFAT (large files)\nmacOS cannot write to NTFS natively without third-party tools.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.3 Windows Editions (8 cards) ─────────────────────────────────────────

  {
    id: 'fc-c2-1-3-01',
    topicId: 'topic-c2-1-3',
    front: 'List the six features that Windows Home CANNOT do.',
    back: '1. No domain join — cannot connect to Active Directory\n2. No BitLocker — no full-disk encryption\n3. No gpedit.msc — no Local Group Policy editor\n4. No Remote Desktop HOST — can connect to others but cannot accept incoming RDP\n5. No Hyper-V — cannot run VMs natively\n6. No Windows Sandbox — cannot create isolated test environments\n(AppLocker is Enterprise-only, not even Pro)',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-3-02',
    topicId: 'topic-c2-1-3',
    front: 'What is BitLocker and what are its minimum requirements?',
    back: 'BitLocker is Windows\'s built-in full-disk encryption. Encrypts the entire volume; data is unreadable without the recovery key if the drive is removed.\nRequirements: Windows Pro, Pro for Workstations, Enterprise, or Education (NOT Home). TPM 1.2 or newer (recommended — allows transparent unlocking). Without TPM, requires a USB key at every boot.\nRecovery key: 48-digit key stored in Microsoft account, Active Directory, Azure AD, USB, or printed copy.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-3-03',
    topicId: 'topic-c2-1-3',
    front: 'What is the Remote Desktop split rule for Windows editions?',
    back: 'CLIENT (connecting to another PC): ALL Windows editions. mstsc.exe is present on Home, Pro, and Enterprise.\nHOST (accepting incoming connections): Pro, Pro for Workstations, Enterprise, and Education ONLY. Home cannot host RDP sessions.\nHome users needing remote access must use third-party tools (TeamViewer, Chrome Remote Desktop).\nRDP uses TCP port 3389.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-3-04',
    topicId: 'topic-c2-1-3',
    front: 'Which features are available in Enterprise but NOT in Pro?',
    back: 'Enterprise-only features:\n• AppLocker — whitelist/blacklist applications by publisher, path, or file hash\n• DirectAccess — automatic corporate VPN for domain-joined machines without client interaction\n• BranchCache — WAN optimization that caches content at branch offices\n• Windows To Go (legacy) — Windows on a bootable USB drive\nPro has BitLocker, domain join, Hyper-V, Group Policy, Remote Desktop hosting, and Windows Sandbox.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-3-05',
    topicId: 'topic-c2-1-3',
    front: 'What is Windows Sandbox and what edition is required?',
    back: 'Windows Sandbox is an isolated, temporary Windows desktop for safely running untrusted software. Every time it opens, it starts fresh from a clean Windows state. When closed, all content inside is permanently deleted — no persistence. Requires Windows Pro or higher (uses Hyper-V). Best use case: testing suspicious installers without risking the host system.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-3-06',
    topicId: 'topic-c2-1-3',
    front: 'What is Group Policy and what are its two scopes?',
    back: 'Group Policy (GPO) allows administrators to configure Windows settings across many machines simultaneously.\n1. Domain Group Policy — applied by domain controller to joined machines; requires domain join (Pro+)\n2. Local Group Policy — applies to local machine only; configured via gpedit.msc; available on Pro+, absent on Home\nCommon uses: screen lock, password complexity, software deployment, desktop restrictions, Windows Defender config.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-3-07',
    topicId: 'topic-c2-1-3',
    front: 'What are the maximum RAM limits for Windows Home, Pro, and Enterprise/Pro for Workstations?',
    back: 'Windows Home: 128 GB\nWindows Pro: 2 TB\nWindows Pro for Workstations: 6 TB\nWindows Enterprise: 6 TB\nWindows Education: 2 TB\nIf a user needs more than 2 TB of RAM (e.g., for high-end engineering or simulation), Pro for Workstations is required.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-3-08',
    topicId: 'topic-c2-1-3',
    front: 'What are the requirements for Hyper-V on Windows Pro?',
    back: 'Hyper-V requirements:\n• Windows Pro, Pro for Workstations, Enterprise, or Education (NOT Home)\n• 64-bit processor with SLAT (Second Level Address Translation) — Intel EPT or AMD RVI\n• CPU virtualization extensions enabled in UEFI (Intel VT-x / AMD-V)\n• Minimum 4 GB RAM (8+ GB recommended)\n• Hyper-V feature enabled via Turn Windows Features On or Off\nHyper-V is Type 1 — when enabled, Windows itself runs as a VM on the hypervisor.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.4 Windows Tools (8 cards) ────────────────────────────────────────────

  {
    id: 'fc-c2-1-4-01',
    topicId: 'topic-c2-1-4',
    front: 'What does each Task Manager tab show in Windows 10/11?',
    back: 'Processes — all running apps and background processes with CPU/Memory/Disk/Network usage\nPerformance — real-time graphs for CPU, Memory, Disk, Network, GPU\nApp history — cumulative resource usage per app\nStartup — programs that launch at login; right-click to Disable (replaces msconfig in Win 10/11)\nUsers — active sessions, resource usage per user\nDetails — granular process list with PID, CPU%, status\nServices — running/stopped services; links to services.msc',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-4-02',
    topicId: 'topic-c2-1-4',
    front: 'What do the Device Manager status icons mean?',
    back: 'Yellow ! (exclamation) — driver problem: missing, corrupt, or conflicting driver. Fix: update/reinstall/roll back driver.\nRed X — device is disabled by user. Fix: right-click > Enable.\nDown arrow — device disabled.\nQuestion mark / "Unknown device" — Windows has no driver and cannot identify the device.\nNo icon — device is working normally.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-4-03',
    topicId: 'topic-c2-1-4',
    front: 'What are the five Windows registry root hives and what does each contain?',
    back: 'HKLM (HKEY_LOCAL_MACHINE) — hardware and software settings for all users\nHKCU (HKEY_CURRENT_USER) — settings for the currently logged-in user\nHKCR (HKEY_CLASSES_ROOT) — file associations and COM object registrations\nHKU (HKEY_USERS) — settings for all user profiles (HKCU is a subkey)\nHKCC (HKEY_CURRENT_CONFIG) — current hardware profile (pointer into HKLM)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-4-04',
    topicId: 'topic-c2-1-4',
    front: 'Which Event Viewer log contains logon/logoff events and what event IDs are critical?',
    back: 'The Security log contains logon/logoff events and audit results.\nKey Event IDs:\n• 4624 — Successful logon\n• 4625 — Failed logon\n• 4648 — Logon using explicit credentials\n• 6005 — Event Log service started (system boot)\n• 6006 — Event Log service stopped (clean shutdown)\n• 41 — Kernel Power (unexpected shutdown/crash)',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-4-05',
    topicId: 'topic-c2-1-4',
    front: 'What are the msconfig Boot tab Safe Boot options?',
    back: 'Minimal — Safe Mode (GUI, minimal drivers, no networking)\nAlternate shell — Safe Mode with Command Prompt (no Explorer)\nActive Directory repair — for domain controller recovery\nNetwork — Safe Mode with Networking\nTip: Use "Hide all Microsoft services" on the Services tab before disabling services to avoid accidentally disabling critical Windows components while isolating third-party conflicts.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-4-06',
    topicId: 'topic-c2-1-4',
    front: 'What are the four service startup types in services.msc?',
    back: 'Automatic — starts when Windows boots, before user login\nAutomatic (Delayed Start) — starts shortly after boot completes; improves boot speed for non-critical services\nManual — starts only when explicitly requested by a program or user\nDisabled — cannot start at all; must be changed to Manual or Automatic first\nPrint Spooler default: Automatic. Remote Desktop Services default: Manual.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-4-07',
    topicId: 'topic-c2-1-4',
    front: 'Which tool provides a read-only snapshot showing BIOS mode (Legacy/UEFI), installed RAM, and OS build number?',
    back: 'System Information (msinfo32). Run via Win+R > msinfo32 or search "System Information."\nSystem Summary shows: OS name, version, build number, BIOS Mode (Legacy or UEFI), Secure Boot State, manufacturer/model, processor, installed RAM.\nFastest way to check BIOS mode without entering UEFI settings.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-4-08',
    topicId: 'topic-c2-1-4',
    front: 'What is the Print Spooler and what should a technician do when a user cannot print?',
    back: 'The Print Spooler service manages print jobs submitted to printers. It must be running for any printing to occur.\nTroubleshooting steps:\n1. Open services.msc\n2. Locate Print Spooler — verify it is Running\n3. If stopped, right-click > Start\n4. If stuck (jobs won\'t clear): Stop the service, delete all files in C:\\Windows\\System32\\spool\\PRINTERS, then Start the service again.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.5 Windows CLI Tools (8 cards) ────────────────────────────────────────

  {
    id: 'fc-c2-1-5-01',
    topicId: 'topic-c2-1-5',
    front: 'What does each ipconfig flag do?',
    back: 'ipconfig — basic IP info for all adapters\nipconfig /all — full details: MAC address, DHCP server, DNS servers, lease info\nipconfig /release — drops the current DHCP lease (IP set to 0.0.0.0)\nipconfig /renew — requests a new IP from the DHCP server\nipconfig /flushdns — clears the local DNS resolver cache\nipconfig /displaydns — shows cached DNS entries\nipconfig /registerdns — re-registers the hostname with the DNS server',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-5-02',
    topicId: 'topic-c2-1-5',
    front: 'What is the standard ping troubleshooting sequence?',
    back: '1. ping 127.0.0.1 — loopback test; verifies TCP/IP stack is functional\n2. ping <own IP> — tests the NIC\n3. ping <default gateway> — tests LAN connectivity\n4. ping 8.8.8.8 — tests internet connectivity (bypasses DNS)\n5. ping google.com — tests DNS resolution\nIf step 4 works but step 5 fails → DNS problem. Run ipconfig /flushdns or check DNS server settings.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-5-03',
    topicId: 'topic-c2-1-5',
    front: 'What does netstat -ano show and how is it used?',
    back: 'netstat -ano combines:\n-a = all connections and listening ports\n-n = numeric addresses (no hostname resolution)\n-o = PID for each connection\nUse case: to find which process is listening on a specific port. Copy the PID from the last column and match it in Task Manager\'s Details tab to identify the application.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-5-04',
    topicId: 'topic-c2-1-5',
    front: 'What is sfc /scannow, what does it do, and what privilege does it require?',
    back: 'SFC (System File Checker) scans all protected Windows system files and replaces corrupted or missing ones with cached copies from the Windows component store (C:\\Windows\\WinSxS).\nRequires: elevated (Administrator) command prompt.\nAfter completion, check %windir%\\Logs\\CBS\\CBS.log for results.\nIf sfc cannot fix files (in-use), run DISM /Online /Cleanup-Image /RestoreHealth first to repair the component store, then run sfc again.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-5-05',
    topicId: 'topic-c2-1-5',
    front: 'What is the difference between chkdsk /f and chkdsk /r?',
    back: 'chkdsk /f — fixes file system errors (logical errors in the file system metadata). Requires a reboot if run on the active system drive (C:).\nchkdsk /r — locates bad sectors and recovers readable data. Implies /f (also fixes logical errors). Much slower because it scans every sector physically.\nBoth require an elevated prompt. On the C: drive, Windows schedules the scan to run before the next OS load.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-5-06',
    topicId: 'topic-c2-1-5',
    front: 'What are the key diskpart commands for setting up a new disk?',
    back: 'diskpart — opens the interactive interpreter\nlist disk — show all physical disks\nselect disk 1 — target disk 1\nclean — DESTROYS all data on selected disk (no undo)\ncreate partition primary — create a primary partition\nformat fs=ntfs quick — quick format as NTFS\nassign letter=D — assign drive letter D\nexit — close diskpart\nWarning: clean and delete partition have no confirmation prompt.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-5-07',
    topicId: 'topic-c2-1-5',
    front: 'Compare robocopy vs xcopy — when should you use each?',
    back: 'robocopy (preferred for production):\n• Retries failed copies automatically (/R:n /W:n)\n• Restartable mode for large transfers (/Z)\n• Mirror mode for one-way sync (/MIR)\n• Multi-threaded (/MT:n)\n• Detailed logs (/LOG:file)\nxcopy (legacy):\n• Available since DOS\n• No retry or restart capability\n• Being phased out\nKey robocopy flags: /E (all subdirectories), /MIR (mirror), /Z (restartable), /LOG (log file)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-5-08',
    topicId: 'topic-c2-1-5',
    front: 'What do gpupdate and gpresult do, and what are their most important flags?',
    back: 'gpupdate — refreshes Group Policy settings\ngpupdate /force — reapplies ALL policies, even unchanged ones\ngpupdate /logoff — logs off after update (for user policies requiring logoff)\ngpupdate /boot — reboots after update (for computer policies requiring restart)\n\ngpresult /r — shows RSoP (Resultant Set of Policy) summary in the console\ngpresult /h gpo.html — generates a full HTML report of all applied policies\nUse gpresult /r to verify a GPO is actually applying when it seems to have no effect.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.6 Windows Settings (8 cards) ─────────────────────────────────────────

  {
    id: 'fc-c2-1-6-01',
    topicId: 'topic-c2-1-6',
    front: 'What is the difference between Control Panel and the Settings app?',
    back: 'Control Panel: legacy interface (since Windows 3.1); more granular and detailed; required for some advanced config not yet in Settings; access via Win+R > control or Start search.\nSettings app: modern interface (Win 8+, redesigned Win 11); touch-friendly, searchable; Win+I shortcut; Microsoft\'s long-term replacement.\nBoth coexist in Windows 10/11. Some Settings links still open Control Panel, and vice versa.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-6-02',
    topicId: 'topic-c2-1-6',
    front: 'What are the three built-in Windows power plans and when is each used?',
    back: 'Balanced — scales CPU speed with demand; default for most systems; good for general desktop and laptop use.\nPower saver — reduces performance to minimum to save maximum battery/energy; best for extended battery life on laptops.\nHigh performance — prevents CPU throttling; keeps hardware fully powered; best for performance-critical workstations.\n(Ultimate Performance is a fourth option not shown by default; disables sleep entirely for high-end workstations.)',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-6-03',
    topicId: 'topic-c2-1-6',
    front: 'What are the four Windows sleep/power states?',
    back: 'Sleep (S3) — RAM stays powered; disk/components off; resumes in 1-2 seconds; consumes some power.\nHibernate (S4) — RAM contents written to hiberfil.sys on disk; all power off; resumes in 10-30 seconds; uses no power.\nHybrid Sleep — saves to RAM AND disk; powers down; fast resume if powered, disk fallback if power lost.\nFast Startup — saves kernel session to hiberfil.sys on shutdown; resumes fast on next boot. Can cause dual-boot issues; disable in Power Options > Choose what power buttons do.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-6-04',
    topicId: 'topic-c2-1-6',
    front: 'What is the difference between Windows quality updates and feature updates?',
    back: 'Quality updates — security patches, bug fixes, reliability improvements. Released on Patch Tuesday (second Tuesday of every month). Applied via Windows Update automatically.\nFeature updates — major OS version changes (e.g., 22H2 → 23H2). Released approximately once or twice per year. Can be paused. Larger download; takes longer to install.\nDefinition updates — antivirus/Defender signature updates; released frequently, often silently.\nDriver updates — optional hardware driver updates through Windows Update.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-6-05',
    topicId: 'topic-c2-1-6',
    front: 'What are the three Windows Defender Firewall network profiles and when does each apply?',
    back: 'Domain — applied when the computer is domain-joined and connected to the corporate network. Least restrictive of the three.\nPrivate — applied when connected to a trusted home or small office network. Moderate restrictions.\nPublic — applied on untrusted public networks (coffee shop, airport, hotel). Most restrictive — blocks incoming connections by default.\nEach profile can have separate inbound and outbound rules.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-6-06',
    topicId: 'topic-c2-1-6',
    front: 'What is UAC and what are the four UAC notification levels?',
    back: 'UAC (User Account Control) prevents unauthorized changes by requiring confirmation or credentials for elevated actions.\nFour levels (Control Panel > User Accounts > Change UAC settings):\n1. Always notify — prompt for every change to Windows settings or software installs\n2. Notify only for app changes (default) — prompt when apps try to make changes; no prompt for Windows settings\n3. Notify only for app changes (no dimming) — same but desktop does not dim; less secure\n4. Never notify — UAC disabled; not recommended',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-6-07',
    topicId: 'topic-c2-1-6',
    front: 'What Windows features are enabled/disabled via "Turn Windows features on or off" in Programs and Features?',
    back: 'Key features toggled here:\n• Hyper-V — native hypervisor (Pro+)\n• Windows Subsystem for Linux (WSL) — run Linux natively on Windows\n• Windows Sandbox — isolated temporary desktop (Pro+)\n• Telnet Client — disabled by default; enable for port-testing with telnet hostname port\n• TFTP Client\n• Internet Information Services (IIS) — built-in web server\n• .NET Framework — required by many apps\nAccess: Control Panel > Programs > Turn Windows features on or off',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-6-08',
    topicId: 'topic-c2-1-6',
    front: 'What are the five System Properties (sysdm.cpl) tabs and what does each control?',
    back: 'Computer Name — hostname, domain or workgroup join (requires reboot)\nHardware — links to Device Manager; driver signing settings\nAdvanced — Performance (visual effects, paging file/virtual memory, DEP); User Profiles (local vs roaming); Startup and Recovery (BSOD settings, memory dump type)\nSystem Protection — enable/disable System Restore per drive; create restore points manually\nRemote — Remote Assistance and Remote Desktop enable/disable; NLA (Network Level Authentication) option',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

]
