// CompTIA A+ 220-1201 flashcards — Core 1 Domain 1 + Domain 2
// 88 flashcards across 11 topics (8 per topic)

const NOW = new Date().toISOString()

export const BATCH1_FLASHCARDS = [

  // ─── 1.1 Mobile Device Hardware (8 cards) ───────────────────────────────

  {
    id: 'fc-c1-1-1-01',
    topicId: 'topic-c1-1-1',
    front: 'What is the purpose of an inverter board in a laptop, and which display type requires it?',
    back: 'The inverter board converts DC power from the laptop battery/adapter into the high-voltage AC current required to power a CCFL (Cold Cathode Fluorescent Lamp) backlight.\n\nOnly CCFL-backlit laptops need an inverter — LED-backlit displays run directly on DC and have no inverter. Failed inverter symptoms: screen goes dark but faint image visible under flashlight, flickering before failure.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-1-02',
    topicId: 'topic-c1-1-1',
    front: 'Compare eDP and LVDS — what are they, and which is used in modern laptops?',
    back: 'LVDS (Low-Voltage Differential Signaling): analog-based internal display interface used ~2000–2012. Uses a wide 30/40-pin ribbon cable. Susceptible to interference.\n\neDP (Embedded DisplayPort): digital protocol based on DisplayPort, replaced LVDS around 2012. Thinner cable, fewer pins, supports higher resolutions and refresh rates. All modern laptops use eDP. Damaged eDP cable causes flickering, color artifacts, or no image.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-1-03',
    topicId: 'topic-c1-1-1',
    front: 'What is a digitizer, and what symptom indicates it has failed?',
    back: 'A digitizer is the layer that converts touch or stylus input into digital coordinates. It sits in front of or bonded to the LCD panel.\n\nTypes:\n• Capacitive: responds to finger electrical charge or active stylus\n• Active digitizer: pressure-sensitive stylus (Microsoft Surface, Wacom)\n\nFailed digitizer symptom: touch/stylus input completely unresponsive, but the display image is perfectly fine. Replace the digitizer, not the LCD.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-1-04',
    topicId: 'topic-c1-1-1',
    front: 'What are the SO-DIMM pin counts for DDR3, DDR4, and DDR5 laptop RAM?',
    back: 'SO-DIMM (Small Outline DIMM) pin counts by generation:\n• DDR3 SO-DIMM: 204 pins\n• DDR4 SO-DIMM: 260 pins\n• DDR5 SO-DIMM: 262 pins\n\nAll three have different notch positions — they are physically incompatible and cannot be swapped. Always verify the laptop\'s supported RAM generation before purchasing. Some ultrabooks have RAM soldered to the motherboard and cannot be upgraded at all.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-1-05',
    topicId: 'topic-c1-1-1',
    front: 'What do M.2 SSD size codes mean, and what is the most common laptop size?',
    back: 'M.2 size codes = width × length in mm:\n• 2230 = 22 mm wide × 30 mm long\n• 2242 = 22 mm × 42 mm\n• 2260 = 22 mm × 60 mm\n• 2280 = 22 mm × 80 mm (most common in laptops)\n\nAll standard M.2 drives are 22 mm wide. The motherboard specifies which lengths it supports. M.2 drives also differ by protocol: SATA (B+M key, ~550 MB/s) or NVMe/PCIe (M key, up to 7,000 MB/s). These are not interchangeable in all slots.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-1-06',
    topicId: 'topic-c1-1-1',
    front: 'What is the difference between a capacitive and resistive touchscreen?',
    back: 'Capacitive touchscreen:\n• Detects electrical conductivity of finger or active stylus\n• Multi-touch capable\n• Will NOT respond to regular stylus or gloved finger\n• Used in all modern smartphones and tablets\n\nResistive touchscreen:\n• Detects physical pressure — any object works (finger, fingernail, stylus)\n• Single-touch typically\n• Used in industrial, medical, and outdoor environments\n• Lower cost, more durable in harsh conditions',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-1-07',
    topicId: 'topic-c1-1-1',
    front: 'List the key internal sensors found in smartphones and their functions.',
    back: '• Accelerometer: detects linear acceleration and gravity — screen rotation, step counting\n• Gyroscope: detects rotational rate — AR apps, gaming, precise orientation\n• Magnetometer (compass): detects magnetic field direction — maps, navigation\n• GPS: determines geographic location — navigation, location services\n• Proximity sensor: detects objects near screen — turns off screen during calls\n• Ambient light sensor: measures surrounding light — auto-brightness\n• Barometer: measures air pressure — altitude, weather\n\nAccelerometer + gyroscope together = full 6-axis motion tracking.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-1-08',
    topicId: 'topic-c1-1-1',
    front: 'What are the ESD best practices when disassembling a laptop?',
    back: '1. Power down completely (not sleep) and disconnect AC adapter\n2. Remove battery if possible before touching internals\n3. Wear an ESD wrist strap connected to a ground point\n4. Work on an ESD-safe mat — avoid carpeted areas\n5. Handle PCBs by edges only — never touch component surfaces or traces\n6. ZIF ribbon cable connectors: always flip the locking tab FIRST before pulling cable\n7. Document screw locations — laptop screws are often different lengths\n8. Test before full reassembly to confirm repair worked\n\nESD can permanently destroy RAM, GPU, or motherboard from a single event.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.2 Mobile Accessories & Connectivity (8 cards) ────────────────────

  {
    id: 'fc-c1-1-2-01',
    topicId: 'topic-c1-1-2',
    front: 'What is the difference between a docking station and a port replicator?',
    back: 'Port replicator: mirrors the laptop\'s existing ports in a convenient tabletop form. Does not add new functionality. May or may not charge the laptop.\n\nDocking station: actively extends capability by adding ports/functions the laptop does not have (additional display outputs, Ethernet, PCIe, charging via single connection). Uses proprietary or Thunderbolt/USB-C interface.\n\nKey exam distinction: port replicator = same ports, convenient. Docking station = new capabilities.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-2-02',
    topicId: 'topic-c1-1-2',
    front: 'What are the Thunderbolt versions, their connectors, and speeds?',
    back: '• TB1: Mini DisplayPort connector — 10 Gbps\n• TB2: Mini DisplayPort connector — 20 Gbps\n• TB3: USB-C connector — 40 Gbps, 2× 4K displays, also provides USB 3.1 + DisplayPort\n• TB4: USB-C connector — 40 Gbps, stricter requirements (min 32 Gbps PCIe, 2× 4K)\n\nTB3/TB4 ports look identical to USB-C — identified by lightning bolt icon. TB cables are backward compatible with USB-C devices but USB-C cables do NOT support Thunderbolt speeds.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-2-03',
    topicId: 'topic-c1-1-2',
    front: 'What are the USB speed standards and their speeds? (Common exam names)',
    back: '• USB 1.1 (Full Speed): 12 Mbps\n• USB 2.0 (Hi-Speed): 480 Mbps — most commonly tested\n• USB 3.0 = USB 3.1 Gen 1 = USB 3.2 Gen 1 (SuperSpeed): 5 Gbps\n• USB 3.1 Gen 2 = USB 3.2 Gen 2 (SuperSpeed 10G): 10 Gbps\n• USB 3.2 Gen 2×2: 20 Gbps — USB-C required\n• USB4 Gen 2×2: 20 Gbps — USB-C only\n• USB4 Gen 3×2: 40 Gbps — USB-C only\n\nCritical: USB-C is a connector SHAPE, not a speed. A USB-C port could be any speed from 2.0 to 40 Gbps.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-2-04',
    topicId: 'topic-c1-1-2',
    front: 'What are the DVI connector types and which one supports a passive VGA adapter?',
    back: 'DVI types:\n• DVI-A: Analog only (rare)\n• DVI-D Single Link: Digital only, 18+1 pins, up to 1920×1200@60Hz\n• DVI-D Dual Link: Digital only, 24+1 pins, up to 2560×1600@60Hz\n• DVI-I Single Link: Digital + Analog, 18+5 pins\n• DVI-I Dual Link: Digital + Analog, 24+5 pins (most flexible)\n\nOnly DVI-I supports a passive VGA adapter because it includes the 4 analog pins in the cross pattern. DVI-D is digital-only and physically lacks those pins — no passive VGA adapter possible.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-2-05',
    topicId: 'topic-c1-1-2',
    front: 'What is the Bluetooth pairing process (Secure Simple Pairing methods)?',
    back: 'Pairing steps:\n1. Enable Bluetooth on host device\n2. Put accessory into discoverable mode (hold pair button until LED flashes)\n3. Host scans and displays discoverable devices\n4. Select the device\n5. Authenticate via one of four SSP methods:\n   • Numeric Comparison: both show same number, confirm on both\n   • Just Works: no input needed (low security, simple accessories)\n   • Passkey Entry: one device shows number, user enters on other\n   • Out of Band (OOB): NFC transfers pairing data\n6. Bonding — devices exchange link keys for automatic future reconnection',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-2-06',
    topicId: 'topic-c1-1-2',
    front: 'What are the three methods of mobile hotspot/tethering and their trade-offs?',
    back: '• Wi-Fi Hotspot: phone broadcasts a Wi-Fi network. Most common. Supports 2.4 GHz or 5 GHz. Battery drain. Multiple devices can connect simultaneously.\n\n• USB Tethering: phone shares internet via USB to one device. Fastest and most reliable. Also charges the phone while tethering.\n\n• Bluetooth Tethering: phone shares internet via Bluetooth. Slowest option (~3–50 Mbps Bluetooth limit). Useful when USB cable unavailable.\n\nAll methods use cellular data from your plan. Carrier data caps apply.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-2-07',
    topicId: 'topic-c1-1-2',
    front: 'What is the difference between MTP and PTP when connecting an Android phone via USB?',
    back: 'MTP (Media Transfer Protocol):\n• Provides full file system access to phone storage\n• Use for transferring music, documents, photos, any files\n• The PC sees the phone as a portable device in File Explorer\n\nPTP (Picture Transfer Protocol):\n• Photo access only — used by photo management software (like Camera Roll import)\n• Only the DCIM folder is accessible\n• Older protocol designed for digital cameras\n\nTo enable either: swipe down notification shade → tap USB notification → select File Transfer (MTP) or Photo Transfer (PTP).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-2-08',
    topicId: 'topic-c1-1-2',
    front: 'What are common causes of mobile device sync failure?',
    back: 'Common causes to check when a device "won\'t sync":\n1. Cloud storage quota full (iCloud only 5 GB free — fills quickly)\n2. Sync disabled in settings (iCloud/Google account sync toggle)\n3. Not signed into the correct account\n4. No Wi-Fi connection (if cellular sync is disabled)\n5. Airplane mode enabled\n6. App-level sync disabled (e.g., Contacts sync off for iCloud)\n7. VPN blocking sync server access\n8. Incorrect date/time on device\n\nFor iOS: check Settings → [Name] → iCloud → each sync toggle.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.3 Mobile Network Connectivity (8 cards) ──────────────────────────

  {
    id: 'fc-c1-1-3-01',
    topicId: 'topic-c1-1-3',
    front: 'What are the SIM card form factors from largest to smallest?',
    back: 'SIM form factors (largest to smallest physical size):\n1. Standard SIM (1FF/2FF): 25mm × 15mm — older phones, feature phones\n2. Micro-SIM (3FF): 15mm × 12mm — iPhone 4 era, mid-2010s phones\n3. Nano-SIM (4FF): 12.3mm × 8.8mm — current smartphones (iPhone 5+, modern Android)\n4. eSIM (5FF): no physical card — embedded chip, provisioned over the air\n\nSIMs can be cut smaller (Nano-SIM cutter) but not made larger without an adapter tray. eSIM supports multiple carrier profiles simultaneously.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-3-02',
    topicId: 'topic-c1-1-3',
    front: 'What are the advantages of eSIM over a physical SIM card?',
    back: 'eSIM (Embedded SIM) advantages:\n• No physical SIM tray needed → thinner devices, better water resistance\n• Multiple carrier profiles stored simultaneously (e.g., personal + work lines)\n• Switch carriers over-the-air without physically swapping a card\n• Cannot be removed by thief → better for device recovery\n• Supports Dual SIM: one eSIM + one nano-SIM for two active numbers\n\nProvisioning: get QR code or activation code from carrier → Settings → Cellular → Add Plan → scan QR.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-3-03',
    topicId: 'topic-c1-1-3',
    front: 'What is 5G NSA vs. 5G SA, and why does the distinction matter?',
    back: '5G NSA (Non-Standalone):\n• 5G NR radio anchored to existing 4G LTE core network\n• Faster deployment, reuses existing infrastructure\n• Most current 5G deployments are NSA\n• Cannot support true 5G features like network slicing\n\n5G SA (Standalone):\n• Both 5G radio AND 5G core network\n• Enables network slicing, ultra-low latency (<1ms), edge computing\n• The long-term goal; still being deployed\n\n5G mmWave (FR2): 24–100 GHz, 1–4 Gbps, <100m range, poor penetration\n5G Sub-6 (FR1): 600 MHz–6 GHz, 100–900 Mbps, broad coverage like LTE',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-3-04',
    topicId: 'topic-c1-1-3',
    front: 'What is VoLTE and how does it differ from regular voice calls on LTE?',
    back: 'VoLTE (Voice over LTE):\n• Carries voice calls as data packets over the LTE network\n• Enables HD voice quality (wideband audio)\n• Allows simultaneous voice + data use on LTE without dropping to 3G\n• Faster call setup time than legacy circuit-switched calls\n\nWithout VoLTE: phone falls back to 2G/3G for voice calls (CSFB — Circuit Switched Fallback). This drops data speeds during a call on networks without VoLTE.\n\nVoLTE requires: carrier support, compatible device, LTE signal.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-3-05',
    topicId: 'topic-c1-1-3',
    front: 'What is MDM and what capabilities does it give IT administrators?',
    back: 'MDM (Mobile Device Management): software platform for managing, monitoring, and securing employee mobile devices.\n\nCapabilities:\n• Remote Wipe: erase entire device to factory defaults\n• Selective Wipe: remove only corporate data/profile (BYOD standard)\n• Remote Lock: lock device remotely\n• Enforce Passcode: require PIN with minimum complexity\n• Enforce Encryption: require device storage encryption\n• Push Certificates: deploy Wi-Fi/VPN certificates automatically\n• App Management: push/remove apps silently\n• Geofencing: location-based policy enforcement\n• Compliance Check: block jailbroken/rooted devices\n• Always-On VPN: force all traffic through VPN',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-3-06',
    topicId: 'topic-c1-1-3',
    front: 'What is the difference between remote wipe and selective wipe in MDM?',
    back: 'Remote Wipe (Full Wipe):\n• Erases ALL data on the device to factory defaults\n• Personal photos, apps, messages — everything is gone\n• Used for: lost or stolen corporate-owned devices\n\nSelective Wipe (Corporate Wipe / Unenrollment):\n• Removes ONLY the MDM profile, corporate apps, and corporate data\n• Personal photos, personal apps, personal messages remain intact\n• Used for: BYOD devices when an employee leaves the company\n\nBest practice for BYOD: always use selective wipe. Full wipe on a personal device would destroy personal data and create legal/HR issues.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-3-07',
    topicId: 'topic-c1-1-3',
    front: 'What is Exchange ActiveSync (EAS) and what security implications arise from enrolling a personal device?',
    back: 'Exchange ActiveSync (EAS): Microsoft protocol for syncing email, calendar, contacts, and tasks between Exchange Server (or Microsoft 365) and mobile devices.\n\nSecurity implications on personal device enrollment:\n• Accepting EAS grants Device Administrator rights to IT\n• IT can enforce PIN requirements and screen lock timeout\n• IT can enforce device encryption\n• IT can perform a REMOTE WIPE of the ENTIRE device\n\nConfiguration fields needed: email address, server (mail.company.com), domain, username, password.\n\nRead the corporate policy carefully before accepting — remote wipe covers ALL data, not just corporate data, on basic EAS enrollment.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-1-3-08',
    topicId: 'topic-c1-1-3',
    front: 'What incoming and outgoing email port numbers should a technician know for mobile email setup?',
    back: 'Incoming mail ports:\n• IMAP: port 143 (plaintext) | port 993 with SSL/TLS (IMAPS)\n• POP3: port 110 (plaintext) | port 995 with SSL/TLS (POP3S)\n\nOutgoing mail port:\n• SMTP: port 25 (server-to-server) | port 587 with STARTTLS (client submission, auth required) | port 465 with SSL (SMTPS, legacy)\n\nRule: use IMAP (not POP3) for multi-device access. Use SSL/TLS variants (993, 995, 587/465) to avoid sending credentials in plaintext. Always use 587 (STARTTLS) for authenticated client submission.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.1 TCP/UDP Ports & Protocols (8 cards) ────────────────────────────

  {
    id: 'fc-c1-2-1-01',
    topicId: 'topic-c1-2-1',
    front: 'What are the must-memorize port numbers for the CompTIA A+ exam?',
    back: 'Critical port table:\n• 20 — FTP Data (TCP)\n• 21 — FTP Control (TCP)\n• 22 — SSH / SFTP (TCP)\n• 23 — Telnet (TCP) — INSECURE\n• 25 — SMTP (TCP)\n• 53 — DNS (UDP typical / TCP for zone transfers)\n• 67 — DHCP Server (UDP)\n• 68 — DHCP Client (UDP)\n• 80 — HTTP (TCP)\n• 110 — POP3 (TCP)\n• 143 — IMAP (TCP)\n• 161 — SNMP query (UDP)\n• 162 — SNMP Trap (UDP)\n• 389 — LDAP (TCP/UDP)\n• 443 — HTTPS (TCP)\n• 445 — SMB (TCP)\n• 3389 — RDP (TCP)',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-1-02',
    topicId: 'topic-c1-2-1',
    front: 'Compare TCP and UDP — when is each used?',
    back: 'TCP (Transmission Control Protocol):\n• Connection-oriented — three-way handshake (SYN → SYN-ACK → ACK)\n• Reliable — every packet acknowledged; lost packets retransmitted\n• Ordered — data arrives in correct sequence\n• Higher overhead\n• Used by: HTTP, HTTPS, SSH, FTP, SMTP, RDP, SMB\n\nUDP (User Datagram Protocol):\n• Connectionless — fire-and-forget, no setup\n• Unreliable — no guaranteed delivery, no ordering\n• Lower overhead, faster\n• Used by: DNS queries, VoIP, video streaming, gaming, DHCP\n\nMemory: TCP = phone call (reliable). UDP = postcard (no guarantee).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-1-03',
    topicId: 'topic-c1-2-1',
    front: 'What is the DHCP DORA process?',
    back: 'DORA = four-step DHCP lease process:\n\nD — Discover: client broadcasts to 255.255.255.255 seeking a DHCP server (UDP source port 68, destination port 67)\n\nO — Offer: DHCP server unicasts/broadcasts an IP address offer + subnet mask, gateway, lease duration\n\nR — Request: client broadcasts acceptance of the offer (lets other DHCP servers know offer was accepted)\n\nA — Acknowledge: server confirms the lease; client now has valid IP config\n\nAPIPE (169.254.x.x) = DHCP failure — client self-assigned because no server responded.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-1-04',
    topicId: 'topic-c1-2-1',
    front: 'What is the difference between SFTP and FTPS?',
    back: 'SFTP (SSH File Transfer Protocol):\n• Runs entirely over SSH on port 22\n• Completely separate protocol from FTP — NOT "FTP with security"\n• All traffic encrypted by SSH\n• Firewall-friendly (single port)\n\nFTPS (FTP Secure):\n• Standard FTP with TLS/SSL encryption added\n• Still uses ports 20 (data) and 21 (control)\n• Two modes: Explicit FTPS (STARTTLS on port 21) and Implicit FTPS (port 990)\n• Related to FTP; uses its dual-port design\n\nKey exam point: SFTP ≠ FTP + SSL. SFTP is a completely different protocol that rides SSH.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-1-05',
    topicId: 'topic-c1-2-1',
    front: 'What DNS record types must you know and what does each do?',
    back: 'DNS record types:\n• A: hostname → IPv4 address (e.g., example.com → 93.184.216.34)\n• AAAA: hostname → IPv6 address (quad-A)\n• MX: identifies mail server(s) for a domain\n• CNAME: alias — points one hostname to another (www → example.com)\n• PTR: reverse lookup — IP address → hostname\n• SOA: Start of Authority — zone metadata, serial number, TTL defaults\n• NS: identifies authoritative name servers for a domain\n\nDNS uses UDP port 53 for queries. TCP port 53 for zone transfers and large responses (>512 bytes).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-1-06',
    topicId: 'topic-c1-2-1',
    front: 'Why is Telnet considered insecure, and what replaced it?',
    back: 'Telnet (port 23) is insecure because:\n• Transmits all data including usernames and passwords in PLAINTEXT\n• Anyone on the network can capture credentials with a packet sniffer\n• No encryption of any kind\n\nSSH (port 22) replaced Telnet because:\n• Encrypts the entire session\n• Supports key-based authentication (more secure than passwords)\n• Also enables tunneling, SCP/SFTP file transfers\n• Functionally equivalent but fully encrypted\n\nExam rule: if asked which is insecure — Telnet. If asked for secure remote terminal — SSH.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-1-07',
    topicId: 'topic-c1-2-1',
    front: 'What are the FTP active and passive modes, and which works better through firewalls?',
    back: 'FTP Active Mode:\n• Client opens random high port, tells server its IP + port\n• Server initiates data connection back to client on port 20\n• Problem: NAT/firewalls block inbound server-initiated connections\n\nFTP Passive Mode (PASV):\n• Server opens random high port, tells client to connect to it\n• Client initiates both control and data connections (outbound only)\n• Firewall-friendly — all connections initiated from inside\n\nFor clients behind NAT (most home/corporate users): passive mode is required. FTP control = port 21, data = port 20 in active mode.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-1-08',
    topicId: 'topic-c1-2-1',
    front: 'What is SNMP and what ports does it use for queries vs. traps?',
    back: 'SNMP (Simple Network Management Protocol): monitors and manages network devices (switches, routers, UPS, servers).\n\nPorts:\n• UDP 161: SNMP queries — manager polls agent for metrics (CPU, memory, interface status)\n• UDP 162: SNMP Traps — agent sends unsolicited alerts to manager (link down, threshold exceeded)\n\nKey concepts:\n• MIB (Management Information Base): database of variables a device can report\n• Community strings: simple shared passwords in SNMPv1/v2c (weak security)\n• SNMPv3: adds proper encryption and user authentication\n\nSNMP is UDP because polling generates high volume — reliability traded for speed.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.2 Wireless Networking (8 cards) ──────────────────────────────────

  {
    id: 'fc-c1-2-2-01',
    topicId: 'topic-c1-2-2',
    front: 'What are the 802.11 Wi-Fi standards, their frequencies, and max speeds?',
    back: '802.11 standard cheat sheet:\n• 802.11a (Wi-Fi 1): 5 GHz — 54 Mbps\n• 802.11b (Wi-Fi 2): 2.4 GHz — 11 Mbps\n• 802.11g (Wi-Fi 3): 2.4 GHz — 54 Mbps\n• 802.11n (Wi-Fi 4): 2.4 GHz AND 5 GHz — 600 Mbps (first dual-band, introduced MIMO)\n• 802.11ac (Wi-Fi 5): 5 GHz only — 3.5+ Gbps (MU-MIMO, up to 160 MHz channel)\n• 802.11ax (Wi-Fi 6/6E): 2.4 + 5 + 6 GHz — 9.6 Gbps (OFDMA, uplink MU-MIMO)\n\nMemory: b/g/n = 2.4 GHz. a/ac = 5 GHz only. n can also do 5 GHz. ax = all three bands.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-2-02',
    topicId: 'topic-c1-2-2',
    front: 'Compare 2.4 GHz, 5 GHz, and 6 GHz Wi-Fi bands.',
    back: '2.4 GHz:\n• Longer range — better wall penetration\n• Lower max speed\n• High interference (microwaves, Bluetooth, baby monitors)\n• Only 3 non-overlapping channels (1, 6, 11)\n\n5 GHz:\n• Shorter range — worse wall penetration\n• Higher speed\n• Low interference, 24+ non-overlapping channels\n• Best for performance-sensitive use\n\n6 GHz (Wi-Fi 6E only):\n• Shortest range\n• Highest speed\n• Very low interference (new, unoccupied spectrum)\n• 59 non-overlapping channels\n\nRule: 2.4 GHz for range; 5 GHz for performance; 6 GHz for latest devices.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-2-03',
    topicId: 'topic-c1-2-2',
    front: 'What are the wireless encryption protocols (WEP, WPA, WPA2, WPA3) and their security levels?',
    back: 'Wireless encryption evolution:\n\n• WEP: BROKEN — RC4 cipher with flawed key scheduling, crackable in minutes. NEVER use.\n• WPA: Weak — TKIP cipher, better than WEP but still vulnerable. Deprecated.\n• WPA2: Strong (current minimum) — AES-CCMP encryption. Two modes:\n  - Personal (PSK): shared password for home/SOHO\n  - Enterprise (802.1X): per-user auth via RADIUS server\n• WPA3: Strongest — SAE replaces 4-way handshake, prevents offline dictionary attacks. Forward secrecy. WPA3-Enterprise uses 192-bit encryption.\n\nExam rule: WEP = completely broken. WPA2 = current minimum. WPA3 = best.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-2-04',
    topicId: 'topic-c1-2-2',
    front: 'What is MIMO and how does MU-MIMO improve on it?',
    back: 'MIMO (Multiple Input Multiple Output):\n• Uses multiple antennas on both transmitter and receiver simultaneously\n• Increases throughput by sending multiple data streams\n• Introduced in 802.11n\n• SU-MIMO: communicates with only one client at a time\n\nMU-MIMO (Multi-User MIMO):\n• AP communicates with multiple clients simultaneously (not sequentially)\n• 802.11ac introduced downlink MU-MIMO (AP → multiple clients)\n• 802.11ax added uplink MU-MIMO (multiple clients → AP simultaneously)\n\nOFDMA (802.11ax): divides a channel into sub-channels assigned to different clients — further improves efficiency in dense environments.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-2-05',
    topicId: 'topic-c1-2-2',
    front: 'What is the 2.4 GHz channel plan and why do only channels 1, 6, and 11 matter?',
    back: 'The 2.4 GHz band in the US has 11 channels, each 22 MHz wide, spaced 5 MHz apart.\n\nBecause channels are 22 MHz wide but only 5 MHz apart, adjacent channels heavily overlap and cause interference.\n\nOnly channels 1, 6, and 11 are separated enough (5 apart) to be fully non-overlapping with each other.\n\nBest practice:\n• Configure neighboring APs on different non-overlapping channels\n• Use a Wi-Fi analyzer to find which channel has least existing traffic\n• Never use channels 2–5, 7–10 for APs — they overlap with others and cause interference\n\n5 GHz has 24+ non-overlapping channels — this restriction does not apply.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-2-06',
    topicId: 'topic-c1-2-2',
    front: 'What is the difference between Infrastructure mode, Ad Hoc mode, and Wi-Fi Direct?',
    back: 'Infrastructure mode (BSS/ESS):\n• Standard mode — clients connect to an Access Point\n• AP bridges wireless clients to wired network\n• BSS = single AP + its clients\n• ESS = multiple APs sharing same SSID for roaming\n\nAd Hoc mode (IBSS):\n• Devices connect directly to each other without an AP\n• No central device, limited range, rarely deployed\n\nWi-Fi Direct:\n• Modern peer-to-peer Wi-Fi without an AP\n• One device acts as a "soft AP"\n• Used for: Miracast screen mirroring, wireless printing, file sharing\n• Better range and speed than Bluetooth for direct device-to-device communication',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-2-07',
    topicId: 'topic-c1-2-2',
    front: 'What is NFC and what are its key characteristics?',
    back: 'NFC (Near Field Communication):\n• Frequency: 13.56 MHz\n• Range: approximately 4 cm (intentionally very short)\n• Short range is a security feature — prevents accidental or eavesdropped transactions\n\nUse cases:\n• Mobile payments: Apple Pay, Google Pay\n• Access control: NFC ID badges, transit cards\n• Quick Bluetooth pairing (tap to pair)\n• Asset tracking tags\n• Data transfer between nearby devices\n\nNFC is NOT a full network technology — it is short-range point-to-point data exchange only. Not for general internet access or streaming.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-2-08',
    topicId: 'topic-c1-2-2',
    front: 'What are Bluetooth power classes and what range does each support?',
    back: 'Bluetooth power classes:\n• Class 1: 100 mW — up to ~100 meters (long-range devices, industrial)\n• Class 2: 2.5 mW — up to ~10 meters (most consumer devices: phones, headphones, mice)\n• Class 3: 1 mW — up to ~1 meter (very short range, limited use)\n\nBluetooth operates at 2.4 GHz ISM band — same as 802.11b/g. Uses FHSS (Frequency Hopping Spread Spectrum) to reduce interference by rapidly changing frequencies.\n\nBluetooth 5.0: up to 240m range, 50 Mbps. Bluetooth 4.0/BLE: very low power for IoT/fitness trackers.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.3 Networked Host Services (8 cards) ──────────────────────────────

  {
    id: 'fc-c1-2-3-01',
    topicId: 'topic-c1-2-3',
    front: 'What is the DNS recursive resolution process?',
    back: 'DNS recursive resolution steps:\n1. Client queries its configured DNS resolver (usually router or ISP DNS)\n2. Resolver checks its cache — if found, returns immediately (TTL determines cache lifetime)\n3. If not cached, resolver queries a Root Name Server for the TLD (.com, .org)\n4. Root refers to the TLD Name Server (e.g., Verisign for .com)\n5. TLD refers to the Authoritative Name Server for the specific domain\n6. Authoritative server returns the record (A, AAAA, MX, etc.)\n7. Resolver caches the result and returns it to the client\n\nInternal DNS: organizations run private DNS servers for internal hostnames (fileserver.corp.local) not visible on the public internet.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-3-02',
    topicId: 'topic-c1-2-3',
    front: 'What does AAA stand for and which protocol implements it for Wi-Fi and VPN?',
    back: 'AAA = Authentication, Authorization, Accounting\n\n• Authentication: Who are you? (verify identity — username/password, certificate, MFA)\n• Authorization: What can you do? (access control — which resources, which permissions)\n• Accounting: What did you do? (logging activity for auditing and billing)\n\nRADIUS (Remote Authentication Dial-In User Service):\n• Port 1812 — authentication\n• Port 1813 — accounting\n• Used for: WPA2-Enterprise Wi-Fi, VPN, wired 802.1X\n• Client (AP or switch) sends credentials to RADIUS; RADIUS approves or denies\n\nKerberos (port 88): used by Active Directory for domain login authentication.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-3-03',
    topicId: 'topic-c1-2-3',
    front: 'What is NTP, why is it critical for enterprise networks, and what is the stratum hierarchy?',
    back: 'NTP (Network Time Protocol): UDP port 123. Synchronizes clocks across all network devices.\n\nWhy time matters:\n• Log correlation: events across devices require matching timestamps\n• Kerberos fails if clock drift exceeds 5 minutes (replay attack prevention)\n• SSL certificate validation requires accurate time\n• Audit trails depend on synchronized time\n\nStratum hierarchy:\n• Stratum 0: atomic clock, GPS receiver (reference clock)\n• Stratum 1: directly synced to Stratum 0 (primary time servers)\n• Stratum 2: synced to Stratum 1 (enterprise NTP servers)\n• Stratum 3+: synced to Stratum 2 (most client devices)\n\nLower stratum = more accurate time source.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-3-04',
    topicId: 'topic-c1-2-3',
    front: 'What is the difference between a forward proxy and a reverse proxy?',
    back: 'Forward Proxy:\n• Sits between clients and the internet\n• Clients send requests to the proxy; it forwards to the internet on their behalf\n• Benefits: content filtering (block bad sites), caching (faster repeated access), anonymization, logging\n• Configured in browser or OS network settings\n• Transparent proxy: intercepts without client configuration\n\nReverse Proxy:\n• Sits in front of web servers; clients connect thinking they are reaching the server\n• Forwards requests to backend servers\n• Benefits: load balancing, SSL termination, hiding internal topology\n• Used by CDNs, enterprise web infrastructure, nginx\n\nKey: Forward proxy serves the client. Reverse proxy serves the server.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-3-05',
    topicId: 'topic-c1-2-3',
    front: 'What is a load balancer and what load balancing algorithms are commonly used?',
    back: 'Load balancer: distributes incoming traffic across multiple servers to prevent overload, enable fault tolerance, and allow scaling.\n\nLoad balancing algorithms:\n• Round-robin: requests go to each server in rotation (1, 2, 3, 1, 2, 3...)\n• Least connections: new request goes to server with fewest active connections\n• IP hash: client IP determines server — ensures same client always hits same server (session persistence)\n• Weighted: servers with more capacity get proportionally more traffic\n\nBenefits:\n• No single point of failure — if one server fails, traffic reroutes\n• Horizontal scaling — add servers to handle more load\n• SSL termination — handles HTTPS decryption centrally',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-3-06',
    topicId: 'topic-c1-2-3',
    front: 'What is Syslog and what do the severity levels mean?',
    back: 'Syslog: centralized log collection protocol (UDP port 514). Devices send log messages to a central Syslog server.\n\nWhy centralize: devices have limited local storage; central logs are harder to tamper with; enables correlation across multiple devices.\n\nSyslog severity levels (0 = most critical, 7 = least critical):\n• 0 — Emergency (system unusable)\n• 1 — Alert (immediate action needed)\n• 2 — Critical\n• 3 — Error\n• 4 — Warning\n• 5 — Notice\n• 6 — Informational\n• 7 — Debug\n\nLower number = higher severity. Admins set a minimum threshold (e.g., "log level 3 and above").',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-3-07',
    topicId: 'topic-c1-2-3',
    front: 'What is LDAP and what port does it use? What is its relationship to Active Directory?',
    back: 'LDAP (Lightweight Directory Access Protocol):\n• Queries and modifies directory service databases\n• Contains: user accounts, groups, computers, organizational units, policies\n• Port 389 (plaintext)\n• Port 636 — LDAPS (LDAP over TLS, encrypted)\n\nRelationship to Active Directory:\n• Active Directory IS a directory service\n• LDAP is the protocol used to query Active Directory\n• When a user searches for a user account or app authenticates against AD, it uses LDAP queries\n\nKerberos (port 88) handles the actual authentication (proving identity). LDAP handles directory lookups (finding users, groups, policies).',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-3-08',
    topicId: 'topic-c1-2-3',
    front: 'What are the common print server implementations and their protocols?',
    back: 'Print server implementations:\n\n1. Dedicated hardware print server:\n   • Small device with USB/parallel port connecting printer to network\n   • Plugs into switch, runs embedded print software\n\n2. Software (Windows Print Spooler):\n   • A PC shares its locally-connected printer to the network\n   • Other machines add it as a network printer\n\n3. Printer with integrated NIC:\n   • Modern printers connect directly to the switch\n   • Built-in print server handles all spooling\n\nProtocols:\n• SMB/Windows: port 445 — most common in Windows environments\n• IPP (Internet Printing Protocol): port 631 (HTTP-based, cross-platform)\n• LPD/LPR (Line Printer Daemon): legacy Unix printing',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.4 Network Configuration (8 cards) ────────────────────────────────

  {
    id: 'fc-c1-2-4-01',
    topicId: 'topic-c1-2-4',
    front: 'What are the RFC 1918 private IP address ranges?',
    back: 'RFC 1918 private address ranges (not routable on public internet):\n\n• 10.0.0.0 – 10.255.255.255 (/8, Class A): large enterprises, 16+ million addresses\n• 172.16.0.0 – 172.31.255.255 (/12, Class B): medium networks\n• 192.168.0.0 – 192.168.255.255 (/16, Class C): home/SOHO — most commonly seen\n\nSpecial ranges:\n• 127.0.0.0/8: loopback (127.0.0.1 = localhost)\n• 169.254.0.0/16: APIPA — self-assigned when DHCP fails\n• 224.0.0.0/4: multicast\n• 0.0.0.0/0: default route (catch-all)\n\nNAT/PAT translates private IPs to public IPs for internet access.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-4-02',
    topicId: 'topic-c1-2-4',
    front: 'How many usable hosts do common subnet masks provide?',
    back: 'Usable hosts = 2^(host bits) − 2\n\nCommon subnet masks:\n• /8  (255.0.0.0):       16,777,214 hosts\n• /16 (255.255.0.0):     65,534 hosts\n• /24 (255.255.255.0):   254 hosts (standard office subnet)\n• /25 (255.255.255.128): 126 hosts\n• /26 (255.255.255.192): 62 hosts\n• /27 (255.255.255.224): 30 hosts\n• /28 (255.255.255.240): 14 hosts\n• /30 (255.255.255.252): 2 hosts (point-to-point links)\n\nSubtract 2 from the total (network address + broadcast address are unusable).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-4-03',
    topicId: 'topic-c1-2-4',
    front: 'What are IPv6 address types and their prefixes?',
    back: 'IPv6 address types:\n• Global Unicast (2000::/3): internet-routable, like public IPv4\n• Link-local (fe80::/10): auto-configured, valid only on local link, not routable\n• Loopback (::1/128): equivalent to IPv4 127.0.0.1\n• Unique Local (fc00::/7): private addresses, like RFC 1918\n• Multicast (ff00::/8): one-to-many delivery, replaces IPv4 broadcast\n\nIPv6 key differences from IPv4:\n• No broadcast — multicast replaces broadcast functions\n• No NAT needed — every device can have globally unique address\n• :: shorthand replaces consecutive zero groups\n• fe80:: addresses are always link-local (auto-configured)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-4-04',
    topicId: 'topic-c1-2-4',
    front: 'What is a VLAN and what switch port types are used with VLANs?',
    back: 'VLAN (Virtual Local Area Network): logically segments a physical switch into multiple isolated broadcast domains.\n\nWhy VLANs:\n• Security: guest traffic isolated from corporate network\n• Performance: reduces broadcast domain size\n• Organization: group devices by department regardless of physical location\n\nSwitch port types:\n• Access port: carries traffic for ONE VLAN; connects end devices (PCs, printers, phones)\n• Trunk port: carries traffic for MULTIPLE VLANs tagged with 802.1Q; used between switches and router\n\n802.1Q tagging: 4-byte tag added to Ethernet frames identifying the VLAN.\n\nInter-VLAN routing: VLANs cannot communicate without a router or Layer 3 switch.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-4-05',
    topicId: 'topic-c1-2-4',
    front: 'What is the difference between NAT and PAT?',
    back: 'NAT (Network Address Translation):\n• One-to-one mapping: one private IP ↔ one public IP\n• Requires a pool of public IPs\n• Each internal device needs its own public IP\n\nPAT (Port Address Translation) / NAT Overload:\n• Many-to-one: many private IPs share ONE public IP\n• Tracks connections using unique source port numbers\n• Example: 192.168.1.10:52341 → 203.0.113.5:10001\n                192.168.1.11:52341 → 203.0.113.5:10002\n• How home routers work — 10+ devices sharing one public IP\n\nIn common usage, "NAT" usually means PAT/NAT Overload. The exam may test the distinction.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-4-06',
    topicId: 'topic-c1-2-4',
    front: 'What are the IP address assignment methods and when is each used?',
    back: 'IP assignment methods:\n\n• DHCP (Dynamic): server automatically assigns IP, subnet, gateway, DNS. Used for most client devices — PCs, laptops, phones.\n\n• Static (Manual): IP configured directly on the device. Used for: servers, printers, network equipment (need consistent, known IPs).\n\n• DHCP Reservation: fixed IP assigned by DHCP server based on MAC address. Device gets same IP every time while remaining centrally managed. Best of both approaches.\n\n• APIPA (169.254.x.x): self-assigned fallback when DHCP fails. Not internet-routable. Seeing this = DHCP failure.\n\nTroubleshooting: ipconfig (Windows) or ip addr (Linux) to check assigned IP.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-4-07',
    topicId: 'topic-c1-2-4',
    front: 'What are the IPv4 address classes and their default subnet masks?',
    back: 'IPv4 address classes:\n\n• Class A: first octet 1–126, default mask /8 (255.0.0.0) — millions of hosts, large enterprises. 127.x.x.x reserved for loopback.\n\n• Class B: first octet 128–191, default mask /16 (255.255.0.0) — 65,534 hosts, campus/large office\n\n• Class C: first octet 192–223, default mask /24 (255.255.255.0) — 254 hosts, small office/home\n\n• Class D: 224–239 — multicast, no subnet mask\n\n• Class E: 240–255 — experimental, reserved\n\nPrivate ranges:\n• Class A private: 10.0.0.0/8\n• Class B private: 172.16.0.0–172.31.255.255\n• Class C private: 192.168.0.0/16',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-4-08',
    topicId: 'topic-c1-2-4',
    front: 'What are the VPN types and when is each used?',
    back: 'VPN types:\n\n• Remote Access VPN: individual user → corporate network. Client software on the device. Common for work-from-home.\n\n• Site-to-Site VPN: office ↔ office. Connects two entire networks permanently. Routers at each site handle the tunnel transparently.\n\n• Split Tunnel: only corporate-bound traffic goes through VPN; internet traffic bypasses it. Reduces VPN load, less secure.\n\n• Full Tunnel: all traffic through VPN including internet. More secure (corporate filtering applies), higher latency.\n\nCommon protocols:\n• IPSec: industry standard for site-to-site and remote access\n• SSL/TLS VPN: uses port 443, firewall-friendly\n• WireGuard: modern, fast, simple\n• IKEv2/IPsec: best for mobile (fast reconnection)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.5 Networking Hardware (8 cards) ──────────────────────────────────

  {
    id: 'fc-c1-2-5-01',
    topicId: 'topic-c1-2-5',
    front: 'Compare hub vs. switch — OSI layer, forwarding method, and collision domains.',
    back: 'Hub:\n• OSI Layer 1 (Physical)\n• Repeats incoming signal out ALL other ports — no intelligence\n• All ports in one collision domain — only one device can transmit at a time\n• Half-duplex only\n• Obsolete\n\nSwitch:\n• OSI Layer 2 (Data Link)\n• Forwards frames based on MAC address table (CAM table)\n• Each port = separate collision domain — full-duplex possible\n• Dedicated bandwidth per port\n• Floods only unknown unicasts and broadcasts\n\nKey: Both hub and switch = one broadcast domain (without VLANs). Switch = separate collision domains per port. Hub = one shared collision domain.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-5-02',
    topicId: 'topic-c1-2-5',
    front: 'What are the PoE standards and how much power does each deliver?',
    back: 'PoE (Power over Ethernet) standards:\n\n• PoE (802.3af): up to 15.4W to device — IP phones, basic APs, basic cameras\n• PoE+ (802.3at): up to 30W — APs, IP cameras, video phones\n• PoE++ (802.3bt Type 3): up to 60W — PTZ cameras, higher-power APs\n• PoE++ (802.3bt Type 4): up to 90W — laptops, advanced displays\n\nPoE injector: adds PoE to a single port on a non-PoE switch. Sits between switch and powered device.\n\nPoE switch: has PoE built into multiple/all ports.\n\nPoE uses Cat 5e or better cable; power and data travel on the same cable pairs.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-5-03',
    topicId: 'topic-c1-2-5',
    front: 'What are the common Ethernet cable categories and their specifications?',
    back: 'Ethernet cable specs:\n\n• Cat 5e: 1 Gbps, 100m — minimum for modern installs\n• Cat 6: 1 Gbps at 100m / 10 Gbps at 55m — common for new installations\n• Cat 6a (Augmented): 10 Gbps at 100m — better shielding for 10GbE full distance\n• Cat 7: 10 Gbps, 100m — shielded, uses GG45 or TERA connectors\n• Fiber Multimode: 10+ Gbps, up to 550m — shorter runs, less expensive lasers\n• Fiber Singlemode: 10+ Gbps, many km — long distance, expensive\n\nUTP: unshielded, standard office use\nSTP: shielded, high-EMI industrial environments\n\nAll copper Ethernet = 100m maximum except where noted.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-5-04',
    topicId: 'topic-c1-2-5',
    front: 'What are the cable connector types for Ethernet, telephone, and fiber?',
    back: 'Connector types:\n\n• RJ-45: 8-pin — Ethernet (Cat 5e/6/6a/7). Standard networking connector.\n• RJ-11: 6-pin (4 used) — Telephone lines, DSL modems. Smaller than RJ-45.\n• LC: small fiber connector with a latch — high-density fiber (common in data centers)\n• SC: square fiber connector with push-pull — common in enterprise fiber\n• ST: round bayonet fiber connector — older, twist-lock (legacy)\n• BNC: bayonet connector — legacy coaxial (Token Ring, CCTV)\n• F-type: threaded coaxial — cable TV, DOCSIS modems\n\nEasy distinction: RJ-45 = looks like a wide phone jack (8 pins). RJ-11 = standard phone jack (4-6 pins).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-5-05',
    topicId: 'topic-c1-2-5',
    front: 'What is the difference between a managed and unmanaged switch?',
    back: 'Unmanaged switch:\n• Plug and play — no configuration required or possible\n• Fixed forwarding behavior, no VLAN support\n• No monitoring, no port security\n• For home and small office environments\n• Less expensive\n\nManaged switch:\n• Fully configurable via CLI, web GUI, or SNMP\n• VLAN support (802.1Q tagging, trunk/access ports)\n• Port security (limit MACs per port, sticky MAC)\n• STP (Spanning Tree Protocol) — prevents loops\n• SNMP monitoring\n• PoE management (per-port power control)\n• For enterprise environments\n\nLayer 3 switch: managed switch with routing capabilities — routes between VLANs without a separate router.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-5-06',
    topicId: 'topic-c1-2-5',
    front: 'What types of firewalls exist and what does each inspect?',
    back: 'Firewall types:\n\n• Packet filter (stateless): examines individual packets against ACL rules (src/dst IP, port, protocol). No session awareness — reply traffic must be explicitly allowed.\n\n• Stateful firewall: tracks connection state — automatically allows reply traffic for established sessions. More intelligent, default for modern firewalls.\n\n• Application-layer / NGFW (Next-Gen Firewall): inspects application content (HTTP, DNS, TLS). Blocks by app, user, URL category, or threat signature. Layer 7 awareness.\n\n• Host-based firewall: software on a single device (Windows Firewall, iptables)\n\n• Network firewall: hardware/VM appliance protecting network segments\n\nDMZ: places public servers between internet and internal network for isolation.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-5-07',
    topicId: 'topic-c1-2-5',
    front: 'What is a modem and what type connects each internet medium?',
    back: 'Modem (modulator/demodulator): converts digital data to/from the analog or carrier signal of the WAN medium.\n\nModem types by medium:\n• Cable modem: coaxial cable (DOCSIS protocol) → Ethernet — for ISP cable internet\n• DSL modem: telephone copper wire (DSL) → Ethernet — requires phone line\n• Fiber ONT (Optical Network Terminal): fiber optic → Ethernet — converts light pulses to electrical signal\n• Cellular modem: LTE/5G cellular → Ethernet or USB — mobile broadband, failover\n\nHome "router" is often: modem + router + wireless AP + switch in one box. An ISP combo device handles all these functions.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-5-08',
    topicId: 'topic-c1-2-5',
    front: 'What is the 568A vs. 568B wiring standard and when is each used?',
    back: '568A and 568B are ANSI/TIA wiring standards for terminating RJ-45 connectors and patch panel punchdowns. They differ only in the order of the orange and green wire pairs.\n\nStraight-through cable: SAME standard on both ends (568B/568B most common in the US). Used for connecting devices to switches/routers.\n\nCrossover cable: DIFFERENT standards on each end (568A on one end, 568B on the other). Used to directly connect two similar devices (PC-to-PC, switch-to-switch — though modern devices support Auto-MDI/X so crossover cables are rarely needed now).\n\n568B is the more common US standard for new installations.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.6 SOHO Networks (8 cards) ────────────────────────────────────────

  {
    id: 'fc-c1-2-6-01',
    topicId: 'topic-c1-2-6',
    front: 'What are the first steps when setting up a new SOHO router?',
    back: 'SOHO router initial setup checklist:\n\n1. Change the default admin password (default credentials are public knowledge)\n2. Update firmware (fixes vulnerabilities and bugs)\n3. Configure WAN interface (DHCP from ISP, or static IP if required)\n4. Set DHCP pool range for local devices\n5. Configure wireless:\n   • SSID (don\'t reveal model or ISP)\n   • Security: WPA2/WPA3 minimum\n   • Strong passphrase (12+ characters)\n   • Disable WPS\n6. Disable remote management (admin only via wired LAN)\n7. Set up static DHCP reservations for printers and servers\n8. Enable guest network with client isolation if needed\n\nAccess router admin: navigate to 192.168.0.1 or 192.168.1.1 in a browser.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-6-02',
    topicId: 'topic-c1-2-6',
    front: 'What is port forwarding, and what information must be configured?',
    back: 'Port forwarding (Destination NAT): directs inbound internet traffic arriving on a specific port to a specific internal device.\n\nRequired: because NAT blocks all unsolicited inbound connections by default.\n\nConfiguration fields:\n• External port: the port internet traffic arrives on\n• Internal IP: which internal device receives the traffic\n• Internal port: what port the internal service listens on\n• Protocol: TCP, UDP, or both\n\nExample — Minecraft server:\n• External port: 25565\n• Internal IP: 192.168.1.50\n• Internal port: 25565\n• Protocol: TCP\n\nSecurity warning: port forwarding opens your internal network. Only forward necessary ports.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-6-03',
    topicId: 'topic-c1-2-6',
    front: 'What is UPnP and why is it a security concern?',
    back: 'UPnP (Universal Plug and Play): allows devices and applications to automatically request port forwarding from the router without manual configuration.\n\nUse cases: gaming consoles (Xbox, PlayStation), BitTorrent, video conferencing apps, media servers (Plex)\n\nSecurity concern:\n• Malware can use UPnP to open firewall rules without user knowledge\n• Creates unintended inbound access to internal devices\n• No authentication — any LAN device can make UPnP requests\n• Has been exploited in large-scale attacks\n\nRecommendation: disable UPnP in security-conscious environments. Configure port forwarding manually only for what is needed. Enable UPnP only if specific devices require it and you accept the risk.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-6-04',
    topicId: 'topic-c1-2-6',
    front: 'What is QoS on a SOHO router and what is the typical priority order?',
    back: 'QoS (Quality of Service): prioritizes certain types of traffic to ensure performance for latency-sensitive applications when bandwidth is limited.\n\nWhy needed: when bandwidth is saturated, all traffic competes equally. QoS puts critical traffic at the front of the queue.\n\nTypical priority order (highest → lowest):\n1. VoIP/voice calls — most sensitive to latency and jitter\n2. Video conferencing (Zoom, Teams)\n3. Online gaming\n4. Video streaming (Netflix, YouTube)\n5. General web browsing\n6. Background downloads and updates (lowest)\n\nQoS does not add bandwidth — it only controls which traffic gets priority when the link is congested. Application-based QoS can identify specific apps automatically.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-6-05',
    topicId: 'topic-c1-2-6',
    front: 'What is a SOHO DMZ host and how does it differ from an enterprise DMZ?',
    back: 'SOHO DMZ host:\n• Exposes ONE specific internal device to ALL inbound internet traffic on ALL ports\n• No firewall protection for that device from inbound connections\n• Use for: game consoles, DVRs, devices needing many inbound ports where individual port forwarding is impractical\n• Risk: any vulnerable service on the DMZ device is directly exposed to the internet\n\nEnterprise DMZ:\n• A dedicated network SEGMENT with its own firewall rules\n• Public-facing servers (web, email, DNS) live here\n• Dual firewall: outer firewall between internet and DMZ; inner firewall between DMZ and internal network\n• Compromise of a DMZ server does not give attacker direct access to internal network\n\nSOHO DMZ = risky, no true isolation. Enterprise DMZ = proper network architecture.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-6-06',
    topicId: 'topic-c1-2-6',
    front: 'What SOHO router security settings should always be hardened?',
    back: 'SOHO router security hardening checklist:\n\n• Admin password: change from default immediately\n• Firmware: update to latest (patches vulnerabilities)\n• WPS: DISABLE — PIN mode has known brute-force vulnerability\n• Remote management: disable unless required (prevents internet-based admin access)\n• Admin via wireless: disable (force wired-only admin access)\n• Encryption: WPA2 or WPA3 minimum — never WEP or Open\n• SSID: change from default (don\'t reveal router model or ISP)\n• Unused services: disable Telnet, FTP if present on the router\n• Default IP range: optionally change 192.168.1.x (minor benefit)\n• Guest network: enable with client isolation for visitors',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-6-07',
    topicId: 'topic-c1-2-6',
    front: 'What is band steering and when would you configure separate SSIDs per band instead?',
    back: 'Band steering:\n• Dual-band router broadcasts SAME SSID on both 2.4 GHz and 5 GHz\n• Router automatically guides capable clients to 5 GHz for better performance\n• Simpler for users — one network name to connect to\n\nSeparate SSIDs per band:\n• Name the bands differently (e.g., "HomeNet" and "HomeNet_5G")\n• Users manually choose which band to connect to\n• Useful when: older IoT devices only support 2.4 GHz and must be segregated, or when band steering causes connectivity issues\n\nRecommendation: band steering with one SSID is easier to manage. Separate SSIDs for troubleshooting or specific device requirements.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-6-08',
    topicId: 'topic-c1-2-6',
    front: 'What content filtering options are available on a SOHO router?',
    back: 'SOHO router content filtering options:\n\n• Website category blocking: block predefined categories (adult content, gambling, malware, social media) using router\'s built-in database\n\n• DNS-based filtering: configure upstream DNS to a filtering service (OpenDNS, Cisco Umbrella, CleanBrowsing) — blocks domains at DNS level before connection\n\n• Schedule-based access: restrict internet access by device (MAC address) and time of day — e.g., no internet for kids\' devices after 10 PM\n\n• MAC address filtering: allow or block specific devices by MAC address\n\nLimitation of MAC filtering: MAC addresses can be spoofed — provides minimal actual security. Useful for managing known devices, not as a security barrier against determined users.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.7 Internet Connection Types (8 cards) ────────────────────────────

  {
    id: 'fc-c1-2-7-01',
    topicId: 'topic-c1-2-7',
    front: 'Compare DSL, Cable, and Fiber internet connections.',
    back: 'DSL:\n• Medium: existing telephone copper wire\n• Speed: 8–100+ Mbps depending on type (ADSL/VDSL)\n• Asymmetric (ADSL) — faster download than upload\n• Dedicated pair to your home — neighbors don\'t affect speed\n• Speed degrades with distance from DSLAM exchange\n• Requires DSL modem\n\nCable (DOCSIS):\n• Medium: coaxial cable TV infrastructure\n• Speed: up to 1–10 Gbps (DOCSIS 3.0/3.1)\n• Shared neighborhood node — speeds drop during peak hours\n• Requires cable modem\n\nFiber (FTTH):\n• Medium: glass/plastic fiber optic\n• Speed: 100 Mbps – 100 Gbps\n• Symmetric speeds (equal upload/download)\n• Immune to EMI, no distance degradation\n• Requires ONT at premises\n• Best overall; not universally available',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-7-02',
    topicId: 'topic-c1-2-7',
    front: 'Compare GEO satellite vs. LEO satellite internet.',
    back: 'GEO (Geostationary) Satellite:\n• Orbit: ~35,786 km altitude\n• Latency: 500–600 ms (signal travels 72,000+ km round trip)\n• Speed: 25–100 Mbps\n• Coverage: global (one satellite covers large area)\n• Examples: HughesNet, Viasat\n• Problem: high latency makes VoIP, gaming, video calls difficult\n\nLEO (Low Earth Orbit) Satellite:\n• Orbit: ~550 km altitude\n• Latency: 20–60 ms (dramatically lower)\n• Speed: 50–300+ Mbps\n• Requires constellation of thousands of satellites for global coverage\n• Example: Starlink\n• Viable for most applications including VoIP\n\nBoth: available anywhere with clear sky view. Weather can degrade signal.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-7-03',
    topicId: 'topic-c1-2-7',
    front: 'What is bandwidth vs. latency vs. throughput?',
    back: 'Bandwidth:\n• Maximum theoretical capacity of a link\n• Measured in Mbps or Gbps\n• Analogy: width of a highway (more lanes = more cars possible)\n\nLatency:\n• Time for a packet to travel from source to destination\n• Measured in milliseconds (ms)\n• Analogy: speed limit — how fast cars travel\n• Sources: propagation delay, queuing delay, processing delay\n\nThroughput:\n• Actual data rate achieved in practice\n• Always less than bandwidth due to overhead, retransmissions, congestion\n• Analogy: actual cars getting through per hour\n\nFor real-time apps (VoIP, gaming): low latency > high bandwidth. A 50 Mbps link at 5ms beats 1 Gbps satellite at 500ms for voice calls.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-7-04',
    topicId: 'topic-c1-2-7',
    front: 'What is DOCSIS and what versions of the standard are important to know?',
    back: 'DOCSIS (Data Over Cable Service Interface Specification):\n• Standard for delivering internet over coaxial cable TV infrastructure\n• Requires a DOCSIS-certified cable modem\n\nVersions:\n• DOCSIS 3.0: max 1 Gbps download, 200 Mbps upload — current standard for most cable internet\n• DOCSIS 3.1: max 10 Gbps download, 1–2 Gbps upload — multi-gigabit cable service\n\nCharacteristic: shared medium — bandwidth is shared among users in a neighborhood node. During peak hours (evenings), speeds can drop for all users on that node.\n\nContrast with DSL: each DSL customer has a dedicated copper pair — neighbor usage doesn\'t affect speed, but distance from the DSLAM does.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-7-05',
    topicId: 'topic-c1-2-7',
    front: 'What is Fixed Wireless Access (FWA) and where is it used?',
    back: 'Fixed Wireless Access (FWA):\n• Delivers internet to a stationary location (home or business) without physical cable\n• Uses a directional antenna mounted on the building, pointed at a nearby tower or base station\n• Uses cellular (LTE, 5G) or licensed wireless spectrum\n\nUse cases:\n• Rural areas without fiber or cable infrastructure\n• 5G home internet (some ISPs offer as cable alternative)\n• Business locations where cabling is impractical\n\nAdvantages: faster deployment than laying cable, no trenching\nLimitations: line-of-sight issues, weather sensitivity, shared spectrum contention\n\nDistinguish from mobile hotspot: FWA is for a fixed location with a permanently-mounted antenna, not a portable device.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-7-06',
    topicId: 'topic-c1-2-7',
    front: 'What is a T1 line and what makes it suitable for business use?',
    back: 'T1 leased line:\n• Speed: exactly 1.544 Mbps symmetric (24 DS0 channels × 64 kbps each)\n• Symmetric: equal upload and download\n• Dedicated: not shared with other customers\n• Guaranteed bandwidth with SLA (Service Level Agreement)\n• Point-to-point: connects a business directly to the carrier\n\nWhy businesses used it:\n• Guaranteed bandwidth — unlike best-effort broadband\n• SLA with financial penalties for outages\n• Symmetric — important for hosting, video, VoIP\n\nStatus: largely legacy. Being replaced by fiber internet with VPN, which provides much higher speeds at lower cost. T3 = 28 T1s = 44.736 Mbps.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-7-07',
    topicId: 'topic-c1-2-7',
    front: 'What are the DSL variants and their speed characteristics?',
    back: 'DSL (Digital Subscriber Line) variants:\n\n• ADSL (Asymmetric DSL):\n  - Download: 8–24 Mbps | Upload: 1–3 Mbps\n  - Asymmetric — faster download reflects typical residential use\n  - Most common residential DSL type\n\n• ADSL2+:\n  - Download: up to 24 Mbps | Upload: up to 3.3 Mbps\n  - Extended range version\n\n• VDSL/VDSL2 (Very-high-speed DSL):\n  - Download: 52–100+ Mbps | Upload: 16–100 Mbps\n  - Very fast but very short distance from DSLAM (< 1.5 km)\n  - Used in FTTN (Fiber to the Node) hybrid deployments\n\nAll DSL: uses existing telephone copper wire, coexists with voice, speed decreases with distance from exchange.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-7-08',
    topicId: 'topic-c1-2-7',
    front: 'Which internet connection types are best for VoIP and why?',
    back: 'Best for VoIP (in order):\n1. Fiber — lowest latency (1–5ms), symmetric, most reliable\n2. Cable — low latency (~5–10ms), fast — good when not congested\n3. Fixed Wireless / 5G — moderate latency, improving\n4. 4G LTE — 20–60ms, adequate for VoIP\n5. LEO Satellite (Starlink) — 20–60ms, marginal for VoIP\n6. DSL — adequate if speed is sufficient\n7. GEO Satellite — 500–600ms, UNSUITABLE for VoIP\n\nVoIP requirements:\n• One-way latency < 150ms (ITU G.114 standard)\n• Packet loss < 1%\n• Low jitter (variation in latency)\n• Bandwidth: only 80–100 kbps per call — bandwidth is rarely the bottleneck',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.8 Networking Tools (8 cards) ─────────────────────────────────────

  {
    id: 'fc-c1-2-8-01',
    topicId: 'topic-c1-2-8',
    front: 'What is the ipconfig command and its most useful switches?',
    back: 'ipconfig (Windows): displays and manages IP configuration for all network adapters.\n\nKey switches:\n• ipconfig — shows IP address, subnet mask, default gateway for all adapters\n• ipconfig /all — full details: MAC address, DHCP server, lease times, DNS servers\n• ipconfig /release — releases current DHCP lease (sends DHCPRELEASE)\n• ipconfig /renew — requests new DHCP lease (sends DHCPDISCOVER)\n• ipconfig /flushdns — clears the local DNS resolver cache (fixes stale/wrong DNS)\n\nTroubleshooting use:\n• 169.254.x.x → DHCP failure, check DHCP server and network\n• Wrong subnet → wrong VLAN or DHCP scope\n• Correct IP but no internet → check default gateway and DNS entries',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-8-02',
    topicId: 'topic-c1-2-8',
    front: 'When should you use ping vs. tracert/traceroute?',
    back: 'ping:\n• Tests basic IP connectivity to a host\n• Sends ICMP Echo Request, waits for Echo Reply\n• Tells you IF a destination is reachable and the round-trip time\n• Does NOT show intermediate hops\n• "Request timed out" = host not responding OR firewall blocking ICMP\n• "Destination host unreachable" = routing failure\n\ntracert (Windows) / traceroute (Linux/macOS):\n• Shows EACH router hop between source and destination\n• Reveals WHERE in the path latency increases or connectivity fails\n• Uses incrementing TTL — each router returns TTL Exceeded\n• *** at a hop = router doesn\'t respond (not necessarily a problem)\n\nRule: ping to confirm IF reachable. tracert to find WHERE it fails.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-8-03',
    topicId: 'topic-c1-2-8',
    front: 'What is nslookup and how is it used for DNS troubleshooting?',
    back: 'nslookup: tests DNS name resolution from the command line.\n\nCommon uses:\n• nslookup google.com — resolve hostname to IP using default DNS server\n• nslookup 8.8.8.8 — reverse lookup: IP to hostname (PTR record)\n• nslookup google.com 1.1.1.1 — query a SPECIFIC DNS server (useful for comparison)\n\nTroubleshooting scenarios:\n• Website won\'t load but IP works → DNS failure → test with nslookup\n• nslookup works but browser doesn\'t → check browser proxy, DNS cache\n• nslookup returns wrong IP → stale cache → ipconfig /flushdns\n• Compare results from two DNS servers → isolate if issue is DNS-server-specific\n\nIf nslookup google.com works but pinging google.com fails → routing issue, not DNS.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-8-04',
    topicId: 'topic-c1-2-8',
    front: 'What does netstat show and what are its most useful switches?',
    back: 'netstat: displays active network connections, listening ports, and protocol statistics.\n\nKey switches:\n• netstat -a — all connections AND all listening ports\n• netstat -n — show numerical IPs (skip DNS resolution — much faster)\n• netstat -b — show which executable owns each connection (Windows, requires admin)\n• netstat -r — display routing table (same as route print)\n• Combine: netstat -an — all connections/ports in numerical format\n\nTroubleshooting uses:\n• Identify which ports a suspicious process has open\n• Confirm a service is listening on its expected port\n• Check for unexpected outbound connections (malware detection)\n• Verify no port conflict before starting a new service\n\nNote: netstat -b requires Administrator rights on Windows.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-8-05',
    topicId: 'topic-c1-2-8',
    front: 'What is a toner probe (fox and hound) and how is it used?',
    back: 'Toner probe kit (tone generator + inductive amplifier):\n\nPurpose: trace and identify cables in bundles, walls, and ceilings.\n\nComponents:\n• Tone generator: connects to one end of the cable, sends a distinctive audible tone\n• Inductive amplifier (probe): detects the tone through insulation and walls WITHOUT direct contact\n\nHow to use:\n1. Connect tone generator to cable at one end (e.g., wall jack)\n2. Move the probe near cables, patch panel ports, or punchdown blocks\n3. The probe emits audio when it detects the tone — louder = correct cable\n\nUse cases:\n• Identify which cable in a bundle goes to a specific jack\n• Find where an unlabeled cable terminates in the patch panel\n• Trace cables through walls and ceilings without damage\n\nDoes NOT test cable wiring — use a cable tester for that.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-8-06',
    topicId: 'topic-c1-2-8',
    front: 'What is Wireshark and what is the difference between a capture filter and a display filter?',
    back: 'Wireshark: packet analyzer (protocol analyzer) that captures and displays complete packet contents by protocol layer.\n\nShows: Ethernet frame → IP header → TCP/UDP header → full application payload.\n\nCapture filter:\n• Applied BEFORE capture begins\n• Limits which packets are captured and saved to disk\n• Reduces file size and performance impact\n• Syntax: host 192.168.1.1, port 80, tcp\n• Cannot be changed after capture starts\n\nDisplay filter:\n• Applied AFTER capture, to narrow what is displayed\n• Does not delete captured packets — just hides non-matching ones\n• Can be changed at any time\n• Example: tcp.port == 80 (show only HTTP)\n• Example: ip.addr == 10.0.0.5 (show traffic to/from host)\n\nUses: malware analysis, protocol debugging, DHCP/DNS troubleshooting, security investigation.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-8-07',
    topicId: 'topic-c1-2-8',
    front: 'What is a loopback plug and when is it used?',
    back: 'Loopback plug: connects a port\'s transmit (TX) pins directly to its receive (RX) pins.\n\nHow it works: when a test signal is sent out through TX, it loops back in through RX. If the port hardware successfully receives its own transmission, the port is functional.\n\nTypes:\n• RJ-45 loopback: tests Ethernet NIC or switch port hardware\n• RJ-11 loopback: tests telephone line ports\n• Fiber loopback: connects TX fiber to RX fiber on a fiber port\n\nUse cases:\n• Test NIC hardware: is the NIC physically functional or dead?\n• Test switch port hardware: is the port burned out?\n• Isolate: is the problem in the cable/remote device vs. the local port?\n\nDistinguish from cable tester (tests the cable between two ends) — loopback tests the LOCAL port hardware only.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-2-8-08',
    topicId: 'topic-c1-2-8',
    front: 'What tool should a technician use for each of these network problems?',
    back: 'Tool selection guide:\n\n• No network connectivity → ipconfig (check IP) → ping gateway → ping DNS → tracert\n• DNS resolution failing → nslookup → ipconfig /flushdns\n• Can\'t reach specific website → ping (IP) → tracert → nslookup\n• Slow or dropping Wi-Fi → Wi-Fi analyzer (channel congestion, signal strength, interference)\n• New cable won\'t link → cable tester (check all 8 conductors)\n• Can\'t find which cable goes where → toner probe (fox and hound)\n• NIC seems dead → loopback plug (test port hardware)\n• Capturing traffic for analysis → network tap or switch SPAN port + Wireshark\n• Suspicious process with open port → netstat -an -b\n• Terminating cable into patch panel/keystone → punchdown tool',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

]
