// flashcards-batch8.ts
// Core 2 Domain 4 — Operational Procedures (additional cards 09–16 per topic)
// Covers new concepts introduced in questions-batch16.ts
// 80 flashcards across 10 topics (8 per topic)

const NOW = new Date().toISOString()

export const BATCH8_FLASHCARDS = [

  // ─── 4.1 Documentation (cards 09–16) ─────────────────────────────────────────

  {
    id: 'fc-c2-4-1-09',
    topicId: 'topic-c2-4-1',
    front: 'Compare Microsoft Visio, draw.io, and NetBox as network documentation tools. When is each appropriate?',
    back: 'Microsoft Visio: industry-standard diagramming tool. Best for enterprise logical/physical network diagrams, rack diagrams, floor plans. Requires a license; integrates with Microsoft 365.\n\ndraw.io (diagrams.net): free, browser-based diagramming. Suitable for teams without Visio licenses; stores diagrams in Google Drive or locally. Good for quick network diagrams.\n\nNetBox: open-source IPAM and DCIM (Data Center Infrastructure Management) platform. Tracks IP address allocations, racks, devices, cables, and connections in a database — not just a drawing. Best for organizations needing authoritative IP and rack inventory, not just visual diagrams.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-10',
    topicId: 'topic-c2-4-1',
    front: 'What should a rack diagram document, and why is it important for data center operations?',
    back: 'A rack diagram is a scaled drawing of a server rack showing every unit installed in it.\n\nShould include:\n- Device model and name in each rack unit (U) position\n- Rack unit height of each device (1U, 2U, etc.)\n- Blank panels in empty slots\n- PDU (power distribution unit) position\n- Cable management panels\n- Total rack U capacity vs. used\n\nWhy important:\n- Enables capacity planning before ordering new hardware\n- Guides technicians to the correct location without physically being there\n- Identifies power and cooling density for each rack\n- Required for audits and data center migrations',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-11',
    topicId: 'topic-c2-4-1',
    front: 'What is IPAM and what does it track?',
    back: 'IPAM (IP Address Management): a system for planning, tracking, and managing IP address space across a network.\n\nTracks:\n- Which IP addresses and subnets are allocated vs. available\n- What device each IP is assigned to (hostname, MAC address, location)\n- DHCP scopes and reservations\n- DNS records and their corresponding IPs\n- VLANs and their associated subnets\n\nWhy important:\n- Prevents IP conflicts from manual tracking errors\n- Required when managing hundreds or thousands of addresses\n- Enables audits of network address usage\n- Integrated tools: NetBox, SolarWinds IPAM, ManageEngine OpUtils',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-12',
    topicId: 'topic-c2-4-1',
    front: 'What is a wiring diagram (cable diagram) and how does it differ from a physical network diagram?',
    back: 'Wiring/cable diagram: documents the physical cabling infrastructure — cable runs, conduit paths, patch panel ports, and how physical connections terminate.\n\nShows:\n- Cable run lengths and pathways (overhead tray, conduit, under-floor)\n- Patch panel port assignments (Port 1A → Office 101 wall jack)\n- Color coding and labeling conventions\n- Cable type (Cat6A, fiber, coax)\n\nPhysical network diagram: shows devices (switches, routers, servers) and how they connect — but at a higher level, not cable-by-cable.\n\nDifference: wiring diagrams are for the physical cabling plant; physical network diagrams are for device-level topology. Both are needed in a complete documentation set.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-13',
    topicId: 'topic-c2-4-1',
    front: 'What is a knowledge base (KB) article and when should a new one be created?',
    back: 'KB article: a document that captures the solution to a known problem in a reusable, searchable format so future technicians or users can self-serve.\n\nWhen to create:\n- After resolving a non-trivial ticket with a solution that isn\'t obvious\n- When the same issue recurs more than twice\n- After finding a workaround for a known vendor bug\n- After completing a new installation or configuration procedure\n\nGood KB articles include:\n- Symptoms (what the user experiences)\n- Root cause (what caused it)\n- Step-by-step resolution\n- Verification steps\n- Related issues or known caveats\n\nKB articles reduce repeat escalations and enable faster Tier-1 resolution.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-14',
    topicId: 'topic-c2-4-1',
    front: 'Why must documentation be updated immediately after implementing a change?',
    back: 'Documentation that doesn\'t reflect current state causes:\n- Configuration errors: a technician follows outdated documentation and misconfigures a system\n- Security gaps: undocumented firewall rules or accounts are missed during audits\n- Troubleshooting delays: the next technician wastes time investigating based on wrong assumptions\n- Compliance failures: auditors compare actual state to documented state — discrepancies indicate control failures\n\nBest practice: updating documentation is part of the change implementation checklist, not a follow-up task. This includes: network diagrams, CMDB, IP address records, asset inventory, SOPs, and baseline configs.\n\nRule: if a diagram doesn\'t match the network, both are wrong — fix the diagram.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-15',
    topicId: 'topic-c2-4-1',
    front: 'What is a network labeling standard and why does it matter?',
    back: 'Network labeling standard: a consistent naming and physical labeling convention applied to all devices, ports, cables, and patch panels.\n\nCommon elements:\n- Device naming: switch-floor2-01, fw-dc-edge-01 (location, role, number)\n- Port labels: both ends of a cable labeled identically\n- Patch panel labels: correspond to floor plan jack numbers\n- VLAN naming: VLAN10-Finance, VLAN20-Guest\n\nWhy it matters:\n- Removes ambiguity during high-pressure troubleshooting\n- Enables technicians unfamiliar with the environment to work effectively\n- Required for accurate physical network diagrams\n\nBest practice: document the standard itself so new technicians follow it consistently.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-16',
    topicId: 'topic-c2-4-1',
    front: 'What is the difference between documenting symptoms vs. root cause in a support ticket?',
    back: 'Symptoms: what the user observes — what is broken, when it started, what error messages appear, what actions preceded the issue.\n\nRoot cause: the underlying technical reason the symptom occurred — the actual failure, misconfiguration, or bug.\n\nWhy both must be documented:\n- Symptoms help future technicians recognize the same issue when it recurs\n- Root cause enables permanent fixes rather than workarounds\n- Root cause analysis feeds into problem management (identifying repeat patterns)\n- Compliance: many regulated environments require root cause documentation\n\nPoor ticket: "Fixed the email issue."\nGood ticket: "Symptom: Outlook failed to connect to Exchange. Root cause: service account password expired. Resolution: reset password, updated in Exchange service configuration."',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.2 Change Management (cards 09–16) ─────────────────────────────────────

  {
    id: 'fc-c2-4-2-09',
    topicId: 'topic-c2-4-2',
    front: 'What is scope creep in a change, and how does formal change management prevent it?',
    back: 'Scope creep: a change gradually expands beyond its original documented scope during implementation — e.g., a firewall rule change becomes an opportunity to "also clean up these old rules while we\'re in there."\n\nWhy it\'s dangerous:\n- The expanded work was not reviewed or approved\n- No rollback plan exists for the undocumented additions\n- Expanded changes increase the risk of unintended consequences\n\nHow change management prevents it:\n- The RFC documents the exact scope; anything beyond scope requires a separate RFC\n- Change window is time-bounded — forces scope discipline\n- Post-implementation review checks actual work against approved scope\n\nRule: if it wasn\'t in the RFC, it doesn\'t happen during this change.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-10',
    topicId: 'topic-c2-4-2',
    front: 'What is configuration drift and how does it relate to change management?',
    back: 'Configuration drift: the gradual divergence of a system\'s actual configuration from its documented baseline — caused by untracked changes, manual fixes, software updates, or ad-hoc adjustments.\n\nWhy it\'s a problem:\n- Systems behave differently than expected based on documentation\n- Security vulnerabilities introduced by undocumented changes go undetected\n- Troubleshooting is harder because assumptions about configuration are wrong\n- Compliance audits fail when actual state differs from documented state\n\nPrevention:\n- Enforce change management — all changes require an RFC\n- Use configuration management tools (Ansible, Puppet, Chef) that enforce desired state\n- Regular configuration audits compare current state to baseline\n- Immutable infrastructure (rebuild from code rather than patch in place)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-11',
    topicId: 'topic-c2-4-2',
    front: 'Why must changes be tested in a staging environment before production, and what makes a good staging environment?',
    back: 'Why test in staging:\n- Identifies bugs, conflicts, and unexpected behaviors before users are affected\n- Validates the implementation procedure so the production change runs smoothly\n- Tests the rollback procedure — confirms it works before it\'s needed under pressure\n\nWhat makes a good staging environment:\n- Representative: mirrors production hardware, OS, software versions, and configuration as closely as possible\n- Isolated: changes in staging cannot affect production\n- Current: regularly synchronized with production so tests are relevant\n- Repeatable: can be reset to a known state after each test\n\nCommon failure: staging is maintained poorly and diverges from production — tests pass in staging but fail in production.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-12',
    topicId: 'topic-c2-4-2',
    front: 'Who must be notified before a planned maintenance change, and what must the notification include?',
    back: 'Who to notify:\n- Users directly affected by the outage or service degradation\n- Business unit managers if the change affects critical business processes\n- On-call staff who need to be available during or after the change\n- Security team if the change has security implications\n- Management / stakeholders for high-impact changes\n\nNotification must include:\n- What is changing\n- When (date, start time, end time in local time zones)\n- Expected impact (service unavailable, degraded, no impact)\n- Contact for questions or emergencies\n- Where to find status updates if the window is extended\n\nTiming: send at least 48–72 hours in advance for significant changes; more for critical business systems.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-13',
    topicId: 'topic-c2-4-2',
    front: 'What is a performance baseline and how is it used in change management?',
    back: 'Performance baseline: a documented snapshot of a system\'s performance metrics under normal operating conditions — CPU utilization, memory usage, disk I/O, network throughput, response times.\n\nHow it\'s used:\n- Pre-change: establish the baseline so there is something to compare against\n- Post-change: compare performance against the baseline to confirm the change didn\'t degrade performance\n- Troubleshooting: deviations from baseline indicate where to investigate\n- Capacity planning: track trends over time to predict when upgrades are needed\n\nBaseline should be captured over multiple time periods (peak, off-peak, end-of-month) to account for normal variation. Store baselines in documentation alongside the system\'s configuration baseline.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-14',
    topicId: 'topic-c2-4-2',
    front: 'What is an unauthorized change, and what are the consequences?',
    back: 'Unauthorized change: any modification to a production system made outside the formal change management process — without an approved RFC, outside a change window, or by someone without authorization.\n\nConsequences:\n- Operational: can cause outages with no rollback plan and no documentation to guide recovery\n- Security: bypassed change management may introduce vulnerabilities undetected by the security review\n- Compliance: violates SOX, PCI-DSS, ISO 27001, and other frameworks that require documented change control\n- HR: grounds for disciplinary action or termination, depending on severity\n\nChange management exists precisely to prevent unauthorized changes from causing incidents. Emergency changes are authorized through an expedited process — they are not the same as unauthorized changes.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-15',
    topicId: 'topic-c2-4-2',
    front: 'What is the difference between an incident and a problem in ITIL?',
    back: 'Incident: an unplanned interruption or degradation of an IT service requiring immediate restoration. Focus is on restoring service quickly — root cause analysis is secondary.\n\nExample: server is down, restore service → that\'s incident management.\n\nProblem: the underlying cause of one or more incidents. Focus is on identifying and permanently eliminating root cause to prevent recurrence.\n\nExample: "Why does this server keep going down?" → that\'s problem management.\n\nRelationship:\n- Multiple incidents may be linked to one problem\n- A problem record is opened when patterns emerge\n- Solving the problem prevents future incidents\n\nKey distinction: an incident = restore now. A problem = fix permanently.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-16',
    topicId: 'topic-c2-4-2',
    front: 'How does change management support compliance with regulations like PCI-DSS and SOX?',
    back: 'Regulated frameworks require evidence that changes to systems handling sensitive data are controlled, reviewed, and documented.\n\nPCI-DSS Requirement 6: all system components must have a formal change management process — requirement 6.5 mandates documented change control for production environments.\n\nSOX: IT controls for financial systems must include evidence that changes cannot be made without authorization and review (segregation of duties).\n\nChange management satisfies this by:\n- Creating an audit trail (RFC, approval records, implementation notes)\n- Enforcing segregation of duties: the requester cannot also approve\n- Requiring testing and documented rollback plans\n- Demonstrating that changes to in-scope systems were controlled\n\nAuditors ask for change tickets to verify that production changes were authorized.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.3 Backup & Recovery (cards 09–16) ─────────────────────────────────────

  {
    id: 'fc-c2-4-3-09',
    topicId: 'topic-c2-4-3',
    front: 'Compare hot site, warm site, and cold site disaster recovery facilities.',
    back: 'Hot site: fully equipped and operational duplicate of the primary data center. Systems are running, data is synchronized in near-real-time. Failover can occur in minutes.\n- Cost: highest (paying for duplicate running infrastructure)\n- RTO: very low (minutes to hours)\n\nWarm site: facility with hardware installed and configured but not running. Data must be restored from backups. Requires hours to days to bring online.\n- Cost: medium (hardware cost but no ongoing compute cost)\n- RTO: hours to days\n\nCold site: a physical space with power, cooling, and connectivity but no hardware. Equipment must be sourced and installed before recovery can begin.\n- Cost: lowest\n- RTO: days to weeks\n\nChoice is driven by RTO requirements and budget.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-10',
    topicId: 'topic-c2-4-3',
    front: 'What is a Disaster Recovery Plan (DRP) and how does it differ from a Business Continuity Plan (BCP)?',
    back: 'DRP (Disaster Recovery Plan): the IT-focused plan for restoring systems and data after a disruptive event. Covers: backup procedures, recovery procedures, RTO/RPO targets, roles and responsibilities, vendor contacts, testing schedule.\n\nBCP (Business Continuity Plan): the broader organizational plan for maintaining business operations during and after a disruption — not just IT. Covers: manual workarounds, alternative office locations, communication trees, supplier alternates.\n\nRelationship: the DRP is a component of the BCP. IT restoration is necessary but not sufficient — the business must also know how to operate while IT is being restored.\n\nBoth must be tested regularly with tabletop exercises and actual recovery drills.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-11',
    topicId: 'topic-c2-4-3',
    front: 'What is a bare-metal restore and when is it needed?',
    back: 'Bare-metal restore (BMR): recovering a complete system from a system image to new or replacement hardware — restoring the OS, applications, settings, and data in one operation, starting from a blank (bare metal) machine.\n\nWhen needed:\n- Catastrophic hardware failure requiring complete replacement\n- Ransomware attack requiring a clean rebuild\n- Migration to new hardware\n- After complete system image backup\n\nTools:\n- Windows: System Image + WinRE\n- Third-party: Acronis True Image, Veeam, Macrium Reflect\n\nKey requirement: system image must include all partitions (OS, recovery, data). The target hardware must be compatible or use a tool that handles hardware abstraction (especially for drivers).\n\nDistinct from file restore: BMR recovers the entire machine; file restore recovers specific files.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-12',
    topicId: 'topic-c2-4-3',
    front: 'How should backups be protected against ransomware?',
    back: 'Ransomware specifically targets backup systems to prevent recovery. Protections:\n\n1. Immutable backups: "write-once" storage that cannot be modified or deleted for a defined retention period (object lock in S3; WORM drives).\n\n2. Offline / air-gapped backups: tape or removable media taken off-network — ransomware cannot reach what is not connected.\n\n3. 3-2-1+ rule extended: add at least one copy to immutable cloud storage.\n\n4. Backup application isolation: backup servers should not be domain-joined — ransomware spreading via domain credentials cannot reach them.\n\n5. Test restores: confirm backups can actually recover before an incident.\n\n6. Separate credentials: backup admin account distinct from domain admin credentials.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-13',
    topicId: 'topic-c2-4-3',
    front: 'What is a backup retention policy and what factors determine retention periods?',
    back: 'Backup retention policy: defines how long backup copies are kept before being deleted or overwritten.\n\nFactors that determine retention:\n\nRegulatory requirements:\n- HIPAA: medical records must be retained for 6 years\n- SOX: financial records 7 years\n- GDPR: personal data retained only as long as necessary\n\nBusiness recovery needs:\n- "How far back might we need to restore?" — quarterly retention covers accidental deletions noticed months later\n\nStorage cost: longer retention = more storage; cloud storage costs scale with retention\n\nOperational window: ransomware may be dormant for weeks before activating — retention must extend beyond typical dwell time\n\nTypical practice: daily backups for 30 days, weekly for 6 months, monthly for 1–7 years.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-14',
    topicId: 'topic-c2-4-3',
    front: 'What are the trade-offs between local backup and cloud backup?',
    back: 'Local backup (NAS, tape, external drive):\n- Pros: fast restore, no internet dependency, no recurring cloud cost, no data leaving the premises\n- Cons: vulnerable to same site disaster as primary data (fire, flood), can be encrypted by ransomware, requires physical media management\n\nCloud backup:\n- Pros: offsite by definition (satisfies 3-2-1 offsite requirement), scales without hardware investment, geographic redundancy\n- Cons: restore speed limited by internet bandwidth, ongoing subscription cost, data sovereignty/compliance concerns for regulated data, initial seeding can take weeks for large datasets\n\nBest practice: use both — local for fast restore of recent data, cloud for offsite protection and long-term retention. The 3-2-1 rule intentionally requires both media types.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-15',
    topicId: 'topic-c2-4-3',
    front: 'Is RAID a backup? Explain why or why not.',
    back: 'No. RAID is NOT a backup.\n\nWhat RAID provides:\n- High availability: the system keeps running if a drive fails\n- Fault tolerance for hardware failure (RAID 1, 5, 6, 10)\n\nWhat RAID does NOT protect against:\n- Accidental deletion (deleted file is mirrored immediately across all drives)\n- Ransomware (encryption propagates to all RAID members in real time)\n- Controller failure (corrupts data on all drives simultaneously)\n- Theft or site disaster\n- Logical corruption (bit rot, file system errors propagate)\n\nRAID and backup serve different purposes:\n- RAID: hardware redundancy for uptime\n- Backup: point-in-time copy of data for recovery\n\nA system can have RAID and still lose all data without a proper backup.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-16',
    topicId: 'topic-c2-4-3',
    front: 'What backup testing schedule is recommended and what does a proper test involve?',
    back: 'Recommended schedule:\n- Weekly: review backup job logs for errors, warnings, and skipped files\n- Monthly: restore a representative sample of files to a test location and verify content integrity\n- Quarterly: full system image restore to a test VM — full end-to-end recovery verification\n- Annually: tabletop exercise simulating a full disaster recovery scenario\n\nProper test involves:\n- Restoring to isolated/test environment (not overwriting production)\n- Verifying the restored data is correct and usable — not just that files exist\n- Measuring actual restore time against RTO target\n- Documenting the test: date, scope, result, and any issues found\n\nFailed backup tests must be treated as incidents — the backup system needs immediate remediation.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.4 Safety Procedures (cards 09–16) ─────────────────────────────────────

  {
    id: 'fc-c2-4-4-09',
    topicId: 'topic-c2-4-4',
    front: 'Why are CRT monitors dangerous even when unplugged, and what is the safe approach?',
    back: 'CRT monitors contain a flyback transformer and capacitors that can hold 25,000 volts or more for hours or days after being powered off and disconnected from mains power.\n\nSpecifically:\n- The flyback transformer drives the electron gun at extremely high voltage\n- High-value capacitors in the CRT circuit retain charge long after power removal\n- Touching the wrong internal component can cause lethal shock\n\nSafe approach for IT technicians:\n- Do NOT open a CRT monitor unless you are specifically trained and equipped for CRT servicing\n- Treat a CRT as potentially energized at all times, even unplugged\n- CRTs requiring repair should go to specialized TV/monitor repair shops\n- For disposal: use certified e-waste recycler (CRTs contain lead in the glass funnel)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-10',
    topicId: 'topic-c2-4-4',
    front: 'Why does an ESD wrist strap contain a 1 MΩ resistor, and why must it make skin contact?',
    back: '1 MΩ (one megaohm) safety resistor:\n- Limits the current path to ground if the wearer accidentally touches a live voltage source\n- Without the resistor, the strap would create a direct short to ground — lethal if contacted with line voltage\n- The high resistance dissipates static slowly (safe for components) while preventing dangerous current flow\n\nSkin contact requirement:\n- The strap works by continuously equalizing the charge between your body and the grounded work surface\n- If the strap is worn over clothing, it cannot drain static from your body — there is no electrical contact\n- The metal band must touch skin directly, typically the wrist\n\nVerification: test the strap periodically with a wrist strap tester to confirm the resistor and ground connection are intact.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-11',
    topicId: 'topic-c2-4-4',
    front: 'What are the safety and disposal requirements for laser printer toner?',
    back: 'Safety hazards:\n- Toner is a fine powder of plastic particles and pigment — respiratory irritant if inhaled\n- Airborne toner exposure risk: occurs during cartridge replacement, drum cleaning, or a toner spill\n- Skin/eye contact: mild irritant; wash with cool water (not hot — heat sets toner)\n\nPPE for toner work:\n- N95 respirator or higher (prevents inhalation of fine particles)\n- Nitrile gloves (prevent skin contact)\n- Safety glasses if working near toner dust\n\nDisposal:\n- Empty cartridges: many manufacturers have take-back recycling programs (HP, Canon, Brother)\n- Never vacuum with a standard vacuum — toner passes through regular filters and is expelled back into the air; use a HEPA vacuum\n- Do not dispose of full or partial cartridges in regular trash in most jurisdictions',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-12',
    topicId: 'topic-c2-4-4',
    front: 'How should inkjet printer ink cartridges and toner cartridges be handled during replacement?',
    back: 'Inkjet cartridges:\n- Ink can stain skin and clothing — nitrile gloves recommended\n- Ink contains dyes and solvents that are mild irritants on prolonged contact\n- Do not puncture or attempt to refill without a proper refill kit\n- Dispose via manufacturer recycling programs (HP Instant Ink, Canon CartridgeRecycle)\n\nLaser toner cartridges:\n- Avoid shaking horizontally — toner can leak from the exit slot\n- Handle over a tray or paper in case of spills\n- If toner spills: clean up with cold water (never hot), use a toner cloth or HEPA vacuum\n- Photosensitive drums (OPCs): protect from light — cover immediately after removal\n\nBoth types: store unused cartridges in original packaging in a cool, dry location away from direct sunlight.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-13',
    topicId: 'topic-c2-4-4',
    front: 'What is lockout/tagout (LOTO) and when does it apply to IT work?',
    back: 'Lockout/tagout (LOTO): an OSHA safety procedure that ensures dangerous machinery or energy sources are properly de-energized and secured before maintenance work begins.\n\nHow it works:\n- Lockout: a physical lock is placed on the energy isolation device (breaker, valve) so it cannot be re-energized\n- Tagout: a warning tag states who placed the lock and why — do not re-energize\n- Each technician working on the equipment places their own lock — the energy source stays locked until ALL workers have removed their individual locks\n\nWhen relevant to IT:\n- Working on UPS systems or power distribution panels\n- Servicing high-voltage equipment (PDUs, electrical panels supplying server rooms)\n- Working inside high-voltage cabinets\n\nNOT typically needed for: standard component replacement in powered-off consumer hardware.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-14',
    topicId: 'topic-c2-4-4',
    front: 'What are the correct disposal methods for IT batteries (lead-acid, lithium-ion, NiCd)?',
    back: 'All battery types: do NOT dispose in regular municipal trash. Batteries contain toxic or reactive materials.\n\nLead-acid (UPS batteries):\n- Highly recyclable; most retailers and battery shops accept them\n- Lead and sulfuric acid — both hazardous to environment\n\nLithium-ion (laptops, phones, tablets):\n- Most major retailers accept drop-off (Best Buy, Staples, Apple)\n- Never incinerate — risk of violent reaction; can reignite during transport if damaged\n- Tape over terminals before shipping or storage\n\nNickel-cadmium (NiCd — older power tools, legacy IT equipment):\n- Cadmium is highly toxic; certified recycler required\n- Call2Recycle program accepts NiCd in North America\n\nStorage before disposal: keep in a cool location, away from combustibles; tape terminals; do not stack.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-15',
    topicId: 'topic-c2-4-4',
    front: 'What are the electrical hazards of uninterruptible power supplies (UPS) and how are they mitigated?',
    back: 'UPS hazards:\n1. High-current battery bank: even a 12V lead-acid battery can deliver thousands of amps into a short circuit — capable of welding rings to fingers and starting fires\n2. Line voltage input: the AC input to the UPS carries full line voltage (120V/240V) even when the UPS appears off\n3. Capacitors: internal capacitors retain charge after unplugging — wait 30 seconds before servicing\n4. Battery acid: lead-acid batteries contain sulfuric acid — contact with skin requires immediate washing\n\nMitigations:\n- Remove jewelry before working near UPS battery banks\n- Use insulated tools\n- LOTO the upstream breaker if servicing UPS internals\n- Wear gloves and eye protection when handling lead-acid batteries\n- Only replace batteries with specified type and capacity',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-16',
    topicId: 'topic-c2-4-4',
    front: 'What cable management practices reduce safety hazards in IT environments?',
    back: 'Cable management hazards:\n- Trip hazards: cables on the floor create trip and fall risks — especially dangerous with heavy server equipment nearby\n- Fire hazards: excessive cable bundles can restrict airflow and trap heat; non-plenum-rated cable in air-handling spaces\n- Electrical hazards: damaged cables, pinched runs, and cables near heat sources risk shorts and shock\n\nBest practices:\n- Use cable trays, conduit, and raceways — cables off the floor\n- Label both ends of every cable\n- Use velcro ties (not zip ties in data runs — they can crimp and damage cables)\n- Maintain minimum bend radius for fiber optic and Cat6A cables\n- Use plenum-rated cable in ceiling or raised-floor air-handling spaces (lower flame/smoke rating)\n- Leave slack for future service — avoid tension on connectors',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.5 Environmental Controls (cards 09–16) ────────────────────────────────

  {
    id: 'fc-c2-4-5-09',
    topicId: 'topic-c2-4-5',
    front: 'What is N+1 redundancy and how do you calculate it for HVAC systems?',
    back: 'N+1 redundancy: having one additional unit beyond the minimum required to handle the load.\n\nFormula: determine N (minimum units needed), then deploy N+1.\n\nExample:\n- A data center requires 3 CRAC units running at full capacity to maintain temperature → N=3\n- With N+1: deploy 4 CRAC units → 3 carry the load, 1 is available for failover\n- If one unit fails, the remaining 3 maintain cooling — no service disruption\n- One unit can also be taken offline for maintenance without impacting cooling\n\nVariants:\n- N+1: one spare\n- 2N: full duplicate of everything (100% redundancy)\n- 2N+1: two full sets plus one extra — used for Tier IV data centers\n\nN+1 is the minimum acceptable redundancy for enterprise data centers.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-10',
    topicId: 'topic-c2-4-5',
    front: 'What is PUE (Power Usage Effectiveness) and how is it calculated?',
    back: 'PUE (Power Usage Effectiveness): the primary metric for data center energy efficiency.\n\nFormula: PUE = Total Facility Power ÷ IT Equipment Power\n\nInterpretation:\n- PUE of 1.0: theoretically perfect — 100% of power goes to IT equipment (impossible in practice)\n- PUE of 2.0: for every 1W consumed by IT, 1W is wasted on overhead (cooling, lighting, power conversion) — 50% efficiency\n- PUE of 1.5: for every 1W of IT, 0.5W overhead — industry average\n- PUE of 1.1: near world-class efficiency (Google hyperscale DCs achieve this)\n\nLower PUE = more efficient. Hot/cold aisle containment, efficient UPS, and economizer cooling all reduce PUE.\n\nDCiE (Data Center Infrastructure Efficiency) = 1/PUE × 100% — the inverse, expressed as a percentage.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-11',
    topicId: 'topic-c2-4-5',
    front: 'What are ASHRAE thermal classes A1–A4 for IT equipment?',
    back: 'ASHRAE (American Society of Heating, Refrigerating and Air-Conditioning Engineers) defines thermal environment classes for IT equipment:\n\nA1 — most restrictive:\n- Inlet temperature: 59–89.6°F (15–32°C)\n- For equipment designed exclusively for controlled data centers\n- Requires precision cooling, tight humidity control\n\nA2:\n- Inlet temperature: 50–95°F (10–35°C)\n- Standard enterprise equipment (most rack servers)\n\nA3:\n- Inlet temperature: 41–104°F (5–40°C)\n- Rugged enterprise equipment\n\nA4 — most permissive:\n- Inlet temperature: 41–113°F (5–45°C)\n- Equipment tolerating harsh environments (industrial, outdoor-rated)\n\nPractical implication: data centers with older A1-class equipment must maintain tighter temperature control than modern A2/A3 equipment.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-12',
    topicId: 'topic-c2-4-5',
    front: 'What is free-air cooling (economizer mode) and when is it feasible?',
    back: 'Free-air cooling (economizer): using outside air or cooling tower water to reject heat without running mechanical refrigeration compressors.\n\nHow it works:\n- Direct air economizer: outside air is filtered and circulated through the data center when outdoor temperature and humidity are suitable\n- Indirect air economizer: a heat exchanger transfers heat from return air to outside air without mixing — data center air stays separate\n- Waterside economizer: cooling towers provide chilled water to CRAC units, bypassing the refrigerant compressor\n\nWhen feasible:\n- Cold climates: northern US, Canada, UK, Nordic countries can run economizer mode 70–90% of the year\n- Tropical climates: economizer provides minimal benefit\n- Suitable humidity and air quality required for direct air economizer\n\nBenefit: dramatically reduces energy cost (no compressor power) during economizer hours.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-13',
    topicId: 'topic-c2-4-5',
    front: 'What is power factor and why do data centers prefer high power factor (80 PLUS) equipment?',
    back: 'Power factor: the ratio of real power (watts, doing useful work) to apparent power (volt-amperes, drawn from the supply).\n\nPF = Real Power (W) ÷ Apparent Power (VA)\n\nA PF of 0.6 means: for every 600W of useful work, the circuit must supply 1,000 VA — 400 VA is reactive current that flows but does no work, heating wires and wasting capacity.\n\nWhy high PF matters in data centers:\n- Low PF wastes circuit capacity — you need larger conductors and breakers for the same useful power\n- Utility companies may charge demand penalties for low power factor\n- UPS units are sized in VA — a low-PF load requires a larger UPS\n\n80 PLUS certification: certifies power supplies achieve 80%+ efficiency at 20/50/100% load, reducing waste and lowering heat output. Platinum/Titanium ratings achieve 90–96% efficiency.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-14',
    topicId: 'topic-c2-4-5',
    front: 'What do R2 and e-Stewards certifications mean for e-waste recyclers?',
    back: 'R2 (Responsible Recycling) certification:\n- Managed by SERI (Sustainable Electronics Recycling International)\n- Audits recyclers for downstream chain of custody, worker safety, environmental compliance, and data destruction\n- Requires verified data destruction procedures for storage media\n\ne-Stewards certification:\n- Managed by the Basel Action Network\n- Stricter standard prohibiting export of hazardous e-waste to developing countries\n- Emphasis on preventing toxic dumping\n\nFor IT departments:\n- Using a certified recycler (R2 or e-Stewards) provides documentation that assets were handled responsibly\n- Required by some compliance frameworks and government contracts\n- Certificates of destruction for hard drives provided by certified ITADs\n\nNever use an uncertified recycler — no way to verify proper handling or data destruction.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-15',
    topicId: 'topic-c2-4-5',
    front: 'How do you correctly size a UPS for a server deployment?',
    back: 'Step-by-step UPS sizing:\n\n1. Total real power (watts):\nAdd the wattage of all devices to be protected (from specs or measured with a clamp meter).\nExample: 3 servers × 400W each + 1 network switch × 150W = 1,350W total.\n\n2. Apply power factor:\nUPS is rated in VA (volt-amperes), not just watts.\nVA = Watts ÷ Power Factor\nIf equipment PF = 0.9: VA = 1,350 ÷ 0.9 = 1,500 VA\n\n3. Add headroom (20–25%):\n1,500 VA × 1.2 = 1,800 VA minimum UPS rating\n\n4. Calculate runtime:\nRuntime depends on battery capacity (Ah × V). Vendors provide runtime curves for different loads.\nCommon target: enough runtime to allow graceful shutdown + generator startup (10–30 minutes).\n\n5. Consider form factor: rack-mount vs. tower, output receptacles, and remote management card.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-16',
    topicId: 'topic-c2-4-5',
    front: 'What is direct liquid cooling (DLC) and when is it used instead of air cooling?',
    back: 'Direct liquid cooling (DLC): routes chilled water or refrigerant through cold plates mounted directly on CPUs, GPUs, and memory — removing heat at the source rather than cooling the room air.\n\nVariants:\n- Cold plate DLC: tubing brings coolant to a plate on the chip\n- Rear-door heat exchangers: a water-cooled door on the rack removes heat from server exhaust\n- Immersion cooling: entire servers submerged in dielectric fluid (most extreme, highest density)\n\nWhen DLC is used:\n- High-density computing: GPU clusters, HPC (> 10–30 kW per rack) — air cooling cannot remove enough heat\n- Blade server enclosures\n- Edge deployments where room cooling is impractical\n\nBenefits:\n- Water is ~3,500× more heat-conductive than air — far more efficient\n- Enables higher CPU frequencies by removing heat faster\n- Reduces data center cooling energy significantly',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.6 Policies & Licensing (cards 09–16) ──────────────────────────────────

  {
    id: 'fc-c2-4-6-09',
    topicId: 'topic-c2-4-6',
    front: 'What is the GDPR "right to be forgotten" (right to erasure) and when can it be refused?',
    back: 'Right to erasure (Article 17): EU residents can request that an organization delete their personal data.\n\nWhen it applies:\n- Data is no longer needed for the original purpose\n- Person withdraws consent and no other legal basis exists\n- Person objects to processing and there is no overriding legitimate interest\n\nWhen it can be refused (Article 17(3)):\n- Legal obligation: organization must retain data to comply with law (e.g., financial records, medical records)\n- Public interest: data needed for public health tasks\n- Legal claims: data needed to establish, exercise, or defend legal claims\n- Freedom of expression: data is part of journalistic or academic public interest work\n\nKey point: consent to collect data is not a permanent license — it can be withdrawn, triggering erasure unless another legal basis applies.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-10',
    topicId: 'topic-c2-4-6',
    front: 'What rights does CCPA grant California residents regarding their personal data?',
    back: 'CCPA (California Consumer Privacy Act) grants California residents:\n\n1. Right to know: what personal data is collected, how it is used, and with whom it is shared\n2. Right to delete: request deletion of personal data (with exemptions)\n3. Right to opt out of sale: prohibit the organization from selling their data to third parties\n4. Right to non-discrimination: cannot be denied service or charged more for exercising CCPA rights\n5. Right to correct (added by CPRA amendment): correct inaccurate personal information\n\nWho it applies to:\nBusinesses meeting any of: $25M+ annual revenue, buying/selling data of 100,000+ CA residents/year, or deriving 50%+ of revenue from selling personal data.\n\nCCPA vs GDPR: CCPA focuses on opt-out of sale; GDPR requires opt-in consent as the legal basis for processing.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-11',
    topicId: 'topic-c2-4-6',
    front: 'What is a CASB (Cloud Access Security Broker) and what role does it play in DLP?',
    back: 'CASB: security software positioned between users and cloud services that enforces security policies for cloud application usage.\n\nFour core functions (Gartner pillars):\n1. Visibility: discovers which cloud services are being used — including unauthorized "shadow IT" apps\n2. Compliance: ensures cloud usage meets regulatory requirements (HIPAA data not stored in non-compliant cloud)\n3. Data security: applies DLP policies to cloud content — blocks sensitive data uploads to personal cloud storage\n4. Threat protection: detects compromised accounts, malware distribution, and insider threats via cloud services\n\nDeployment modes:\n- API mode: connects to sanctioned cloud apps (O365, Salesforce) for visibility and control\n- Proxy mode: inline between users and all cloud traffic for real-time inspection\n\nCASB extends DLP beyond the corporate perimeter to cloud-delivered services.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-12',
    topicId: 'topic-c2-4-6',
    front: 'What is Software Asset Management (SAM) and why does it matter?',
    back: 'SAM (Software Asset Management): the practice of managing and optimizing software licenses across an organization — tracking what is installed, what is licensed, and ensuring compliance.\n\nWhy it matters:\n- License compliance: avoid under-licensing fines (vendor audits can result in substantial penalties)\n- Cost optimization: identify over-licensed software and reduce spend\n- Security: unmanaged software may be unpatched or contain vulnerabilities\n- Compliance: required by ISO/IEC 19770, PCI-DSS, and enterprise governance frameworks\n\nSAM process:\n1. Inventory: discover all installed software (endpoint agents, Active Directory)\n2. Entitlements: record licenses purchased, versions covered, deployment rights\n3. Reconcile: compare installations to entitlements — find gaps\n4. Optimize: reassign licenses from uninstalled software to reduce new purchases\n\nTools: Microsoft SCCM, Flexera, Snow Software, ServiceNow SAM',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-13',
    topicId: 'topic-c2-4-6',
    front: 'What is a data classification scheme and why is it the foundation of DLP?',
    back: 'Data classification: the process of categorizing data by its sensitivity level so appropriate security controls can be applied.\n\nTypical classification levels (most to least sensitive):\n- Top Secret / Confidential: financial forecasts, trade secrets, PII, PHI — most restrictive access\n- Internal / Private: internal business documents, employee records — restricted to employees\n- Public: marketing materials, press releases — can be disclosed externally\n\nWhy it underpins DLP:\n- DLP cannot protect data it cannot identify\n- Classification defines what "sensitive" means so DLP rules can target the right data\n- Labels or metadata tags applied at classification time are what DLP engines inspect\n\nClassification methods:\n- Manual: users or document owners apply labels\n- Automated: ML classifiers and pattern matching detect sensitive content automatically\n- Combined: auto-classify suggestions reviewed by users',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-14',
    topicId: 'topic-c2-4-6',
    front: 'What are the requirements for maintaining chain of custody of digital evidence?',
    back: 'Chain of custody requirements for digital evidence:\n\n1. Documentation at acquisition:\n- Device description (make, model, serial number)\n- Date, time, and location of seizure\n- Name and title of person who seized it\n- Hash of storage media (MD5 or SHA-256) before imaging\n\n2. Imaging:\n- Create a forensic image (sector-by-sector copy) using write-blocking hardware\n- Hash the image and verify it matches the original hash\n- Work only from the image — never from the original\n\n3. Access log:\n- Every person who accesses the evidence must sign in/out with date, time, and reason\n\n4. Physical security:\n- Evidence stored in locked, access-controlled location\n- Tamper-evident seals on physical media containers\n\nAny gap in the chain can render evidence inadmissible in court.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-15',
    topicId: 'topic-c2-4-6',
    front: 'How do GPL, LGPL, MIT, and Apache 2.0 differ in terms of using open-source code in commercial products?',
    back: 'MIT:\n- Can use in any product (commercial or proprietary) with no restrictions beyond attribution\n- Most permissive; widely used for libraries\n\nApache 2.0:\n- Same as MIT plus an explicit patent grant protecting users from patent claims by contributors\n- Can use in commercial/proprietary products\n\nLGPL (Lesser GPL):\n- Can link to an LGPL library from proprietary code without requiring your code to be open-sourced\n- Modifications to the LGPL library itself must be released under LGPL\n- Used for widely-adopted libraries (Qt, GNU C Library)\n\nGPL:\n- Copyleft — any product that incorporates GPL code must release its entire source code under GPL\n- Cannot be incorporated into closed-source commercial products\n- "Viral" — the license propagates to the whole program\n\nGPL v3 adds: restrictions on tivoization (hardware-locked GPL software)',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-16',
    topicId: 'topic-c2-4-6',
    front: 'What are escalation procedures in IT support, and what triggers an escalation?',
    back: 'Escalation: passing a support issue to a higher tier or different team when the current technician cannot resolve it within their capability or authority.\n\nTriggers for escalation:\n- Technical: problem is beyond current technician\'s knowledge or toolset\n- Authorization: fix requires admin access, vendor engagement, or budget approval the technician lacks\n- Policy: incident involves security breach, HR matter, or legal concern requiring specialist handling\n- SLA: resolution is taking too long — escalation prevents SLA breach\n\nProper escalation procedure:\n1. Document everything attempted and findings so far\n2. Identify the correct escalation target (tier 2, security team, vendor)\n3. Brief the receiving team before handing off\n4. Update the user: who will handle it and expected next contact\n5. Keep the ticket open and monitor for completion\n\nEscalation is a professional responsibility — not a sign of failure.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.7 Professionalism (cards 09–16) ───────────────────────────────────────

  {
    id: 'fc-c2-4-7-09',
    topicId: 'topic-c2-4-7',
    front: 'What is paraphrasing in technical support, and why is it used?',
    back: 'Paraphrasing: restating what the user said in your own words to confirm mutual understanding before proceeding.\n\nExample:\n"So what you\'re saying is the printer prints from every other computer in the office, but not from your laptop — even after restarting. Is that right?"\n\nWhy it\'s used:\n1. Confirms understanding: catches misinterpretations before wasted troubleshooting effort\n2. Shows the user they were heard and their concern was understood\n3. Reduces follow-up questions by establishing a shared, specific problem statement\n4. Focuses the interaction: the user often confirms or adds critical details when they hear their own problem summarized\n\nCommon format: "So if I understand correctly..." or "Let me make sure I have this right..."\nThen: "Is that correct?" — always invite confirmation.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-10',
    topicId: 'topic-c2-4-7',
    front: 'What is the verify–explain–educate–document sequence for closing a support ticket?',
    back: 'The four-step professional close-out sequence:\n\n1. Verify:\nConfirm the fix resolves the original problem with the user present.\n"Is everything working the way it should now?"\nDo NOT close the ticket based on the technician\'s assumption alone.\n\n2. Explain:\nBriefly tell the user what caused the problem in plain language.\n"Your email stopped working because the server certificate expired overnight."\nBuilds trust and helps the user understand what happened.\n\n3. Educate:\nOffer one or two tips to prevent the issue from recurring.\n"When you see this error message in the future, it usually means..."\nEmpowers the user; reduces repeat tickets.\n\n4. Document:\nRecord the root cause and specific resolution steps in the ticket — in enough detail that a different technician could reproduce the fix.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-11',
    topicId: 'topic-c2-4-7',
    front: 'What professional boundaries apply when handling sensitive or personal data during a repair?',
    back: 'Key professional boundaries:\n\nAccess scope:\n- Only access files, folders, and systems directly necessary for the repair\n- Do not browse the user\'s file system out of curiosity or for any reason unrelated to the task\n\nData seen incidentally:\n- If sensitive data appears on screen (financial records, personal photos, confidential documents): look away and do not read it\n- Never mention or discuss it afterward — not to colleagues, not in the ticket\n\nNo copying or recording:\n- Do not screenshot, photograph, or copy personal or confidential data — even for legitimate IT purposes — without explicit authorization\n\nTransparency:\n- If access to sensitive areas is required for the repair, explain to the user why before accessing\n\nLegal note: unauthorized access to computer data is a criminal offense in most jurisdictions (CFAA in the US). Good professional practice and the law align here.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-12',
    topicId: 'topic-c2-4-7',
    front: 'What should a technician do when asked by a senior executive to bypass a security control?',
    back: 'The correct response — regardless of who is asking:\n\n1. Acknowledge the urgency: "I understand this is time-sensitive."\n\n2. Explain the policy clearly and briefly:\n"This policy applies to all accounts including executives — it\'s there to protect the organization from specific known risks."\n\n3. Offer compliant alternatives:\n"Here\'s what we can do within policy..."\n\n4. Escalate if an exception is genuinely warranted:\n"If this situation requires a policy exception, that decision should go through IT management and security — I can help facilitate that quickly."\n\n5. Do NOT comply with the bypass — and document the request.\n\nWhy: security policies are organizational controls, not technician preferences. Bypassing them at anyone\'s verbal request — executive or otherwise — exposes the technician, the organization, and the executive to liability. Proper exceptions go through the change/approval process.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-13',
    topicId: 'topic-c2-4-7',
    front: 'What does cultural sensitivity mean in day-to-day IT support, and what are common pitfalls?',
    back: 'Cultural sensitivity: adjusting communication style and behavior to be respectful and effective with users from diverse backgrounds.\n\nWhat it means in practice:\n- Do not assume technical literacy based on age, gender, job title, or cultural background\n- Avoid idioms and colloquialisms that may not translate across cultures\n- Adjust language complexity to the individual user — gauge during the conversation\n- Respect different communication styles (some cultures are more indirect; some are more direct)\n\nCommon pitfalls:\n- Condescension: speaking louder, slower, or more simply to someone with a non-English name or accent — unless there\'s an actual communication barrier\n- Assumptions: assuming an older user is less technical, or a young user is more technical\n- Jargon: using acronyms and technical terms without checking understanding\n\nGoal: every user receives the same quality of professional, respectful service.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-14',
    topicId: 'topic-c2-4-7',
    front: 'How should a technician handle a user who provides personal or emotional disclosures during a support call?',
    back: 'Situation: a user mentions personal stress, health issues, or emotional distress during a support interaction — unrelated to the IT problem.\n\nProfessional response:\n1. Briefly acknowledge: a short, compassionate response is appropriate\n"I\'m sorry to hear you\'re dealing with that."\n\n2. Redirect to the task: return to the technical issue professionally\n"Let\'s see if we can at least get this sorted for you."\n\n3. Do not:\n- Engage in extended counseling or life advice — this goes beyond IT\'s professional scope\n- Record personal disclosures in the ticket\n- Share what was said with colleagues\n- Dismiss the user\'s feelings abruptly\n\n4. If the user appears to be in distress that requires professional help: IT can note that the organization has an Employee Assistance Program (EAP) and gently suggest it — but this is the limit of IT\'s appropriate role.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-15',
    topicId: 'topic-c2-4-7',
    front: 'What are the key principles of professional written communication in IT support (email, tickets, documentation)?',
    back: 'Professional written communication principles:\n\nClarity:\n- Use specific, concrete language — not "fixed the issue" but "replaced the failed network adapter"\n- Avoid ambiguous pronouns — name the specific system or user each time\n\nTone:\n- Professional and neutral — not sarcastic, defensive, or dismissive\n- Assume the message may be read by lawyers, auditors, or executives\n\nCompleteness:\n- Include: what the symptom was, what was tried, what was found, what was done, how it was verified\n- Future technicians must be able to reconstruct exactly what happened from the ticket alone\n\nPromptness:\n- Acknowledge receipt of issues within the SLA response time\n- Update users proactively — do not make them ask for status\n\nAvoid:\n- Technical jargon in user-facing emails\n- Blame language ("user error")\n- Passive voice that obscures responsibility',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-16',
    topicId: 'topic-c2-4-7',
    front: 'What is the professional responsibility regarding knowledge transfer before planned absence?',
    back: 'The problem: a technician who holds exclusive knowledge of a critical system creates a Single Point of Failure (SPOF) in IT staffing.\n\nProfessional responsibilities before extended absence:\n\n1. Document: write up operating procedures for systems only you maintain — enough for a qualified colleague to troubleshoot and make routine changes\n\n2. Cross-train: walk at least one colleague through the key systems so they can provide coverage\n\n3. Hand off open work: brief your team on outstanding tickets, pending changes, and anything that may need attention\n\n4. Update the team: ensure escalation contacts, vendor support numbers, and access credentials are documented and accessible to appropriate team members\n\n5. Do NOT promise to be available during vacation — this is an organizational failure to address, not a personal obligation\n\nOrganizations have a parallel responsibility to build knowledge redundancy so no individual is irreplaceable.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.8 Scripting (cards 09–16) ─────────────────────────────────────────────

  {
    id: 'fc-c2-4-8-09',
    topicId: 'topic-c2-4-8',
    front: 'What do the Bash operators &&, ||, and ; do when chaining commands?',
    back: '"&&" (AND): run second command ONLY IF the first succeeds (exits with code 0).\nExample: mkdir /backup && cp data.txt /backup\n→ only copies if mkdir succeeded\n\n"||" (OR): run second command ONLY IF the first FAILS (non-zero exit code).\nExample: ping -c1 server || echo "Server unreachable"\n→ echoes only if ping fails\n\n";" (sequential): run commands one after the other regardless of success or failure.\nExample: echo "start"; rsync ...; echo "done"\n→ "done" prints even if rsync failed\n\nExit codes:\n- $? contains the exit code of the last command\n- 0 = success; any non-zero = failure\n\nPractical use: && chains dependent steps safely — if step 1 fails, step 2 does not run with incorrect state.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-10',
    topicId: 'topic-c2-4-8',
    front: 'What does "2>&1" mean in Bash, and when is it useful?',
    back: '"2>&1" redirects stderr (file descriptor 2) to the same destination as stdout (file descriptor 1).\n\nFile descriptors:\n- 0 = stdin\n- 1 = stdout (normal output)\n- 2 = stderr (error messages)\n\nBy default, commands send stdout to the terminal and stderr to the terminal separately. Redirection normally only affects stdout.\n\nUseful scenarios:\n\nCapture all output to a log file:\ncommand > /var/log/job.log 2>&1\n→ both stdout and stderr go to the file\n\nDiscard all output (including errors):\ncommand > /dev/null 2>&1\n\nPipe errors through grep:\ncommand 2>&1 | grep ERROR\n\nOrder matters: > logfile 2>&1 is correct; 2>&1 > logfile is NOT (redirects stderr to old stdout before redirect).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-11',
    topicId: 'topic-c2-4-8',
    front: 'How does Python try/except work, and what is the correct pattern for handling specific exceptions?',
    back: 'Structure:\ntry:\n    # code that might fail\nexcept SpecificException as e:\n    # handle this specific error\nexcept AnotherException as e:\n    # handle a different error\nfinally:\n    # always runs — cleanup code\n\nBest practices:\n- Catch specific exceptions, not bare "except:" — catching everything hides bugs\n- Log the exception with traceback for debugging\n- Use "finally" for cleanup (closing files, database connections)\n\nCommon IT scripting exceptions:\n- FileNotFoundError: file path doesn\'t exist\n- PermissionError: insufficient access\n- requests.exceptions.ConnectionError: network call failed\n- KeyError: dictionary key missing\n- json.JSONDecodeError: API returned invalid JSON\n\nExample:\ntry:\n    response = requests.get(url, timeout=5)\n    response.raise_for_status()\nexcept requests.exceptions.Timeout:\n    logging.error("Request timed out")',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-12',
    topicId: 'topic-c2-4-8',
    front: 'How do you read a cron schedule, and write a common example?',
    back: 'Cron format: 5 time fields + command\n┌─── minute (0–59)\n│ ┌─── hour (0–23)\n│ │ ┌─── day of month (1–31)\n│ │ │ ┌─── month (1–12)\n│ │ │ │ ┌─── day of week (0–7, 0=Sunday)\n│ │ │ │ │\n* * * * * /path/to/command\n\nSpecial values:\n* = every\n*/5 = every 5 (e.g., */5 in minutes = every 5 minutes)\n1-5 = range\n1,3,5 = specific values\n\nCommon examples:\n0 2 * * * /scripts/backup.sh\n→ 2:00 AM every day\n\n0 2 * * 0 /scripts/weekly.sh\n→ 2:00 AM every Sunday\n\n*/15 * * * * /scripts/check.sh\n→ Every 15 minutes\n\n0 0 1 * * /scripts/monthly.sh\n→ Midnight on 1st of every month\n\nEdit crontab: crontab -e (per-user) or /etc/crontab (system-wide)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-13',
    topicId: 'topic-c2-4-8',
    front: 'What are the security best practices for scripts that require credentials?',
    back: 'NEVER:\n- Hardcode passwords, API keys, or connection strings in the script\n- Commit credentials to version control (Git)\n- Print credentials to logs or stdout\n- Pass credentials as command-line arguments (visible in process list)\n\nDO:\n\n1. Environment variables:\n$apiKey = $Env:API_KEY (PowerShell)\napiKey = os.environ[\'API_KEY\'] (Python)\n\n2. Credential stores:\n- Windows: Windows Credential Manager (Get-StoredCredential)\n- Linux: secret-tool, HashiCorp Vault, AWS Secrets Manager\n\n3. Prompt at runtime:\n$cred = Get-Credential (PowerShell)\ngetpass.getpass() (Python)\n\n4. Service accounts with minimal permissions:\n- Script should only have the rights it needs for its task\n\n5. Audit logging:\n- Log all actions performed; do not log credential values\n\nExposed credentials must be rotated immediately — not "next maintenance window."',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-14',
    topicId: 'topic-c2-4-8',
    front: 'What is PowerShell\'s -WhatIf parameter and when should it be used?',
    back: '-WhatIf: a PowerShell common parameter that shows what a cmdlet WOULD do without actually doing it.\n\nExample:\nRemove-Item -Path C:\\Temp\\* -Recurse -WhatIf\n→ Outputs: "What if: Performing the operation \'Remove Item\' on target \'C:\\Temp\\file.txt\'"\n→ Nothing is actually deleted\n\nWhen to use:\n- Before running any destructive cmdlet (Remove-Item, Stop-Process, Format-*)\n- When testing a script against production data for the first time\n- During code review to verify the scope of a change\n- In script documentation: run with -WhatIf first as a dry-run step\n\nNot all cmdlets support -WhatIf. Check with:\nGet-Command Remove-Item | Select -ExpandProperty Parameters | Select whatif\n\nPython/Bash equivalents: a --dry-run flag or a $DRY_RUN variable that substitutes print statements for actual actions.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-15',
    topicId: 'topic-c2-4-8',
    front: 'What should a script file header comment include?',
    back: 'A script header comment documents the essential context for anyone who inherits or maintains the script.\n\nRequired fields:\n- Name / purpose: one-sentence description of what the script does\n- Author: who wrote it and contact info\n- Date created: original creation date\n- Version: current version (increment with each significant change)\n- Change log: brief history of modifications with date and description\n- Prerequisites: required modules, permissions, environment variables, or accounts\n- Usage example: sample invocation with parameters\n\nPowerShell example:\n# Name: New-UserBulk.ps1\n# Purpose: Create AD accounts from a CSV file\n# Author: Jane Smith <jane@company.com>\n# Created: 2024-01-15\n# Version: 1.2\n# Changelog:\n#   1.1 - Added email notification on error\n#   1.2 - Added -WhatIf support\n# Requires: ActiveDirectory module, Domain Admin or Account Operator role\n# Usage: .\\New-UserBulk.ps1 -CsvPath .\\users.csv [-WhatIf]',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-16',
    topicId: 'topic-c2-4-8',
    front: 'What are the "set -e", "set -u", and "set -x" Bash options and when should they be used?',
    back: 'These options make Bash scripts safer and easier to debug:\n\nset -e (errexit):\nExit the script immediately if any command exits with a non-zero status.\nPrevents subsequent commands from running on a broken prior state.\nBest practice: include in all production scripts.\n\nset -u (nounset):\nTreat unset variables as an error and exit.\nPrevents bugs where a typo in a variable name silently uses an empty string.\nExample: rm -rf "$TMPDIR/" expands to rm -rf "/" if TMPDIR is unset — catastrophic. set -u catches this.\n\nset -x (xtrace):\nPrint each command before executing it (with a + prefix).\nUseful for debugging — see exactly what the script is doing.\nRemove from production scripts or gate behind a DEBUG flag.\n\nCombine: set -euo pipefail\n-o pipefail: causes a pipeline to fail if ANY command in it fails (not just the last).\n\nUsage: add to the top of the script after the shebang line.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.9 Remote Access (cards 09–16) ─────────────────────────────────────────

  {
    id: 'fc-c2-4-9-09',
    topicId: 'topic-c2-4-9',
    front: 'Compare IKEv2, OpenVPN, WireGuard, and SSTP VPN protocols.',
    back: 'IKEv2/IPSec:\n- UDP 500 / 4500\n- Fast reconnection via MOBIKE (handles Wi-Fi↔cellular switches seamlessly)\n- Native on Windows, macOS, iOS, Android\n- Strong security; widely enterprise-supported\n\nOpenVPN:\n- TCP 443 or UDP 1194\n- Open-source, highly configurable, TLS-based\n- Penetrates restrictive firewalls on port 443\n- Requires client software; slower than IKEv2 on mobile\n\nWireGuard:\n- UDP 51820 (configurable)\n- Modern cryptography (ChaCha20, Curve25519), very small codebase\n- Fastest of the three; in Linux kernel since 5.6\n- Newer — less enterprise support than IKEv2\n\nSSTP:\n- TCP 443, Microsoft proprietary\n- Built into Windows; penetrates firewalls well\n- Not available on non-Windows natively\n\nPPTP / L2TP: legacy, avoid — PPTP is cryptographically broken.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-10',
    topicId: 'topic-c2-4-9',
    front: 'What is always-on VPN and how does it differ from user-initiated VPN?',
    back: 'Always-on VPN (AOVPN):\n- The VPN tunnel is automatically established at device boot — before user logon\n- Users cannot disconnect it (it is enforced by policy)\n- Provides uninterrupted coverage whenever the device is outside the corporate network\n\nTwo tunnel types in AOVPN:\n- Device tunnel: connects at boot (before user logon); enables domain authentication, Group Policy, remote management\n- User tunnel: connects at user logon; provides user-specific resource access\n\nUser-initiated VPN:\n- User manually connects and can disconnect at will\n- No enforcement — users who forget to connect or choose not to are unprotected\n\nAlways-on VPN use cases:\n- Corporate devices on unmanaged networks (home Wi-Fi, coffee shops)\n- Ensuring endpoint security controls are always enforced\n- Replacement for DirectAccess (Windows-native always-on predecessor)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-11',
    topicId: 'topic-c2-4-9',
    front: 'What does SSH host key verification protect against, and what does the WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED message indicate?',
    back: 'Host key verification purpose:\nWhen connecting to an SSH server for the first time, the server presents its public host key. The client stores this fingerprint in ~/.ssh/known_hosts.\nOn subsequent connections, the client verifies the fingerprint matches the stored value.\n\nProtects against:\nMan-in-the-middle (MITM) attacks — if an attacker intercepts the connection and presents their own key, the fingerprint mismatch triggers a warning.\n\nWARNING: REMOTE HOST IDENTIFICATION HAS CHANGED:\nThe server\'s fingerprint no longer matches the stored known_hosts entry.\n\nLegitimate causes:\n- Server was rebuilt or re-imaged (new host keys generated)\n- Server\'s OS was reinstalled\n- SSH keys were explicitly rotated for security\n\nMalicious cause:\n- Possible MITM attack\n\nResponse:\n- Verify the change through an out-of-band channel (phone, ticket, admin confirmation) before accepting\n- If legitimate: remove the old entry with ssh-keygen -R hostname and reconnect',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-12',
    topicId: 'topic-c2-4-9',
    front: 'Compare SFTP, SCP, and FTP for secure file transfer.',
    back: 'FTP (File Transfer Protocol):\n- Port 21 (control), 20 (data)\n- Transmits credentials and data in PLAINTEXT — do not use over untrusted networks\n- Still used on isolated internal networks or legacy systems\n- FTPS: FTP over TLS — adds encryption but more complex than SFTP\n\nSFTP (SSH File Transfer Protocol):\n- Port 22 (runs over SSH)\n- Full-featured file transfer: upload, download, directory listing, delete, rename\n- Encrypted and authenticated via SSH\n- NOT the same as FTPS — completely different protocol\n- Supported natively in most Linux/macOS/Windows clients\n\nSCP (Secure Copy):\n- Port 22 (runs over SSH)\n- Simple one-way file copy command: scp source user@host:destination\n- No interactive file browsing — command-line only\n- Faster than SFTP for simple copy operations\n- Being phased out in favor of rsync over SSH for large transfers\n\nChoice: SFTP for interactive file management; SCP for simple scripted copies.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-13',
    topicId: 'topic-c2-4-9',
    front: 'What is a jump server (bastion host) and why is it used?',
    back: 'Jump server (bastion host): a single, hardened server that acts as the only entry point into a secure network segment.\n\nHow it works:\n- Administrators connect to the jump server first (via SSH or RDP)\n- From the jump server, they connect to internal systems\n- Internal systems accept connections only from the jump server\'s IP — not from the internet\n\nSecurity benefits:\n- Single point of access: every session to the secure zone goes through the jump server — fully logged\n- Reduced attack surface: sensitive internal systems have no direct internet exposure\n- Centralized MFA: enforce multi-factor authentication at the jump server entry point\n- Privileged Access Workstation (PAW): hardened jump servers used for admin access to critical systems\n\nModern equivalent: Privileged Access Management (PAM) solutions (CyberArk, BeyondTrust) provide web-based session management with session recording, replacing dedicated jump servers.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-14',
    topicId: 'topic-c2-4-9',
    front: 'What session security and consent requirements apply to remote support sessions?',
    back: 'Consent requirements:\n- Obtain explicit permission before connecting to a user\'s machine — verbal or written\n- Inform the user what you will be doing and why\n- Ideally have the user present during the session\n\nSession security:\n- Use encrypted protocols (RDP with NLA, SSH, TLS-encrypted remote support tools)\n- Require MFA for all remote access, especially unattended access\n- Time-limit sessions: configure automatic disconnection after inactivity\n\nSession recording and logging:\n- Enterprise tools should log who connected to what system and when\n- Session recording for privileged access sessions is best practice and often required by compliance frameworks\n- Logs must be tamper-resistant\n\nData during sessions:\n- Do not screenshot or record sensitive user data encountered during the session\n- Scope access to the task — avoid browsing files unrelated to the support request\n\nUnattended access:\n- Must be explicitly provisioned and documented — not established ad-hoc without user knowledge',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-15',
    topicId: 'topic-c2-4-9',
    front: 'What is an SSL VPN and how does it differ from IPSec VPN?',
    back: 'SSL/TLS VPN:\n- Uses HTTPS (TCP 443) — traverses almost any firewall\n- Clientless option: access through a browser (for specific web applications)\n- Full-client option: thin client establishes full tunnel over HTTPS\n- Examples: Cisco AnyConnect SSL, Palo Alto GlobalProtect, Fortinet SSL VPN\n\nIPSec VPN:\n- Uses UDP 500 and 4500 (IKE for key exchange)\n- Network-layer protocol — stronger for full-network access\n- May be blocked by strict firewalls; requires firewall rules for UDP traffic\n- Higher performance for bulk data transfer\n\nKey differences:\n- Firewall traversal: SSL VPN wins (port 443 rarely blocked); IPSec may be blocked\n- Performance: IPSec generally higher throughput\n- Application compatibility: IPSec supports all IP traffic; SSL VPN may work at application layer\n- Clientless support: only SSL VPN can provide browser-based access without a client\n\nModern enterprise: many organizations use SSL VPN (AnyConnect, GlobalProtect) for user VPN and IPSec for site-to-site VPN.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-16',
    topicId: 'topic-c2-4-9',
    front: 'What governance controls are needed for RMM platforms with script execution capabilities?',
    back: 'RMM platforms can run scripts on hundreds of endpoints simultaneously — powerful and dangerous. Required controls:\n\n1. Role-Based Access Control (RBAC):\n- Separate roles: read-only monitoring vs. script deployment vs. full remote access\n- Principle of least privilege — helpdesk staff should not have script deployment rights\n\n2. Script approval workflow:\n- New scripts require review and approval before they can be run in production\n- Approved script library — only pre-approved scripts can be scheduled\n\n3. Audit logging:\n- Every script execution logged: who ran it, on which endpoints, at what time, with what output\n- Logs must be immutable and retained per policy\n\n4. MFA for platform access:\n- RMM credentials are high-value targets — compromise of RMM gives attacker access to all managed endpoints\n\n5. Scope limiting:\n- Scripts should run under least-privilege service accounts — not domain admin\n- Test on a subset of machines before fleet-wide deployment',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.10 Artificial Intelligence (cards 09–16) ──────────────────────────────

  {
    id: 'fc-c2-4-10-09',
    topicId: 'topic-c2-4-10',
    front: 'What is an LLM knowledge cutoff and how does it affect reliability for IT use?',
    back: 'Knowledge cutoff: the date after which an LLM has no training data. The model has no knowledge of events, software releases, vulnerabilities, or changes that occurred after this date.\n\nIT implications:\n- CVE and vulnerability research: an LLM may not know about recently disclosed vulnerabilities — always check NIST NVD or vendor advisories for current security information\n- Software documentation: commands, APIs, and features that changed after the cutoff may be described incorrectly\n- New product information: models released, features shipped, or products discontinued after the cutoff are unknown to the model\n- Legal and regulatory: regulatory changes after the cutoff are not reflected\n\nMitigation:\n- Use AI for concepts and general approaches — verify version-specific details against official documentation\n- Use tools with real-time retrieval (RAG or search augmentation) for current information\n- Check the model\'s stated knowledge cutoff before relying on time-sensitive information',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-10',
    topicId: 'topic-c2-4-10',
    front: 'What is RAG (Retrieval-Augmented Generation) and how does it improve LLM accuracy for IT use cases?',
    back: 'RAG: a technique that combines an LLM with a retrieval system — before generating a response, the system retrieves relevant documents from a knowledge base and includes them in the LLM\'s context.\n\nHow it works:\n1. User submits a query\n2. Retrieval system searches an internal knowledge base (documentation, KB articles, policies) for relevant content\n3. Retrieved content is included in the LLM prompt as context\n4. LLM generates a response grounded in the retrieved documents\n\nWhy it improves accuracy:\n- Reduces hallucination: the model answers from provided source material, not just training data\n- Overcomes knowledge cutoff: the knowledge base can contain current documentation\n- Organization-specific: responses reflect the actual products, policies, and procedures in use\n\nIT support use case: AI assistant that answers "How do I reset my password?" based on the current IT portal documentation — not generic LLM knowledge.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-11',
    topicId: 'topic-c2-4-10',
    front: 'What is prompt injection and why is it a security concern for AI systems?',
    back: 'Prompt injection: an attack where malicious instructions are embedded in data that an AI system processes — causing the AI to override its intended behavior.\n\nTypes:\n- Direct: the user directly enters instructions designed to override system prompts ("Ignore previous instructions and...")\n- Indirect: malicious instructions are hidden in external content that the AI reads (a web page, document, or email processed by an AI agent)\n\nWhy it\'s dangerous:\n- AI agents that take actions (send emails, run commands, access files) can be hijacked to take malicious actions\n- Hidden text in a document might instruct the AI to exfiltrate information to an attacker\n- The AI has no inherent way to distinguish its system instructions from injected instructions\n\nMitigations:\n- Limit AI agents to least-privilege — only the capabilities needed for the task\n- Never automatically execute AI-suggested commands without human review\n- Treat AI-processed external content as untrusted input\n- Use input sanitization and output validation for production AI systems',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-12',
    topicId: 'topic-c2-4-10',
    front: 'What is model drift (data drift / concept drift) and how is it addressed?',
    back: 'Model drift: the degradation of an ML model\'s accuracy over time as real-world data patterns diverge from the training data.\n\nTwo types:\n\nData drift: the statistical distribution of input data changes — e.g., new applications generate network traffic patterns unlike anything in the training set.\n\nConcept drift: the relationship between inputs and the target outcome changes — e.g., attack techniques evolve so malicious traffic no longer resembles the examples the model was trained on.\n\nSigns of drift:\n- Increasing false positive or false negative rates\n- Declining accuracy on recent data compared to historical performance\n- Model outputs no longer matching domain expert expectations\n\nAddressing drift:\n- Monitor model performance continuously with real data and track metrics over time\n- Set accuracy thresholds that trigger investigation when crossed\n- Retrain on current data periodically\n- Consider continual learning architectures that update incrementally\n\nExpect IT security ML models to need retraining as the threat landscape evolves.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-13',
    topicId: 'topic-c2-4-10',
    front: 'What is an LLM context window and why does it matter for IT practitioners?',
    back: 'Context window: the maximum amount of text (measured in tokens) that an LLM can process in a single interaction — including conversation history, the system prompt, the user\'s input, and the model\'s output.\n\nApproximate token ratios: 1 token ≈ 0.75 words (English). GPT-4: 128K tokens (~96,000 words); Claude 3.5: up to 200K tokens.\n\nWhy it matters for IT use:\n\n1. Long documents: analyzing a 10,000-line log file may approach context limits — the AI may not "see" earlier content when responding about later content\n\n2. Long conversations: in extended troubleshooting sessions, early context gets dropped — the AI may "forget" constraints or information from the beginning\n\n3. Codebases: large scripts or configuration files may need to be chunked and processed in sections\n\nPractical tip:\n- For large inputs, provide the most relevant sections, not the whole file\n- Restate key constraints at the end of long prompts\n- Use RAG to retrieve relevant document sections rather than sending entire documents',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-14',
    topicId: 'topic-c2-4-10',
    front: 'What is Explainable AI (XAI) and why is it important for IT governance?',
    back: 'Explainable AI (XAI): a design principle and set of techniques that enable AI systems to provide human-understandable explanations for their decisions and predictions.\n\nWhy it matters for IT governance:\n\n1. Accountability: when AI denies a user access, flags an account, or recommends a termination, there must be a way to explain and justify the decision to the affected party and to auditors\n\n2. Compliance: GDPR Article 22 grants EU individuals the right not to be subject to automated decisions without human review or explanation; some regulations require explainability for consequential decisions\n\n3. Audit trails: security incidents involving AI actions must be explainable for forensic investigation\n\n4. Bias detection: XAI makes it possible to identify which input features drive decisions — enabling detection of biased or problematic decision criteria\n\nBlack-box vs. white-box models:\n- Black-box (neural networks): high accuracy, low explainability\n- White-box (decision trees, logistic regression): lower accuracy, high explainability\n- XAI tools (LIME, SHAP): apply post-hoc explanations to black-box models',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-15',
    topicId: 'topic-c2-4-10',
    front: 'How does AI/ML-powered SIEM differ from rule-based SIEM?',
    back: 'Rule-based SIEM:\n- Security analysts write explicit detection rules: "alert if >5 failed logins in 60 seconds"\n- Detects known patterns exactly\n- Cannot detect attacks not covered by an existing rule\n- High false positive rate if rules are too broad; high false negative rate if too narrow\n- Each new threat requires a new rule\n\nML-powered SIEM (UEBA — User and Entity Behavior Analytics):\n- Learns baseline behavior for each user and system\n- Flags statistical anomalies regardless of whether a rule was written\n- Detects zero-day attacks and novel techniques not in any signature database\n- Correlates weak signals across many data sources (login location + access time + data volume + destination)\n- Lower false positive rate over time as the model learns what\'s normal for each entity\n\nPractical combination:\n- Both are used together: rules catch known threats immediately; ML catches unknown threats over time\n- Examples: Microsoft Sentinel (ML + KQL rules), Splunk UEBA, Exabeam',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-16',
    topicId: 'topic-c2-4-10',
    front: 'What are the key principles of responsible AI deployment in an IT environment?',
    back: 'Privacy:\n- Do not input PII, PHI, or confidential data into public AI services without data processing agreements\n- Review vendor data handling: is input used for training? Where is it stored?\n\nAccuracy and verification:\n- Treat AI output as a starting point, not an authoritative answer\n- Verify commands, configurations, and facts against official documentation\n- Test AI-generated code before production deployment\n\nTransparency:\n- Users should know when AI is involved in decisions affecting them\n- Document how AI is used in IT processes for audit purposes\n\nBias awareness:\n- Monitor AI tools for systematically skewed outputs across groups\n- Human review required for AI-driven decisions about people\n\nHuman oversight:\n- AI should augment human judgment, not replace it for consequential decisions\n- Always provide a human escalation path when AI handles support interactions\n\nScope discipline:\n- AI agents with action capabilities must operate under least privilege\n- Autonomous AI actions must be fully logged and auditable',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

]
