// CompTIA A+ 220-1201 Flashcards — Batch 2
// Core 1 Domain 4: Virtualization and Cloud Computing (topics 4.1–4.2)
// Core 1 Domain 5: Hardware and Network Troubleshooting (topics 5.1–5.6)
// 8 flashcards per topic × 8 topics = 64 flashcards total

const NOW = new Date().toISOString()

export const BATCH2_FLASHCARDS = [

  // ─── 4.1 Virtualization Concepts (8 cards) ────────────────────────────────

  {
    id: 'fc-c1-4-1-01',
    topicId: 'topic-c1-4-1',
    front: 'What is the difference between a Type 1 and a Type 2 hypervisor?',
    back: 'Type 1 (bare-metal): runs directly on physical hardware with no host OS. Examples: VMware ESXi, Microsoft Hyper-V, KVM, Xen. High performance; used in enterprise data centers.\n\nType 2 (hosted): runs as an application on top of an existing host OS (Windows, macOS, Linux). Examples: VMware Workstation, VMware Fusion, Oracle VirtualBox, Parallels Desktop. Easier setup; used for development, testing, and learning.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-1-02',
    topicId: 'topic-c1-4-1',
    front: 'What are the four VM networking modes and what does each provide?',
    back: 'NAT: VM shares host\'s IP; can reach the internet, but external devices cannot initiate connections to VM.\n\nBridged: VM gets its own IP from the physical network; appears as a separate host on the LAN; other devices can reach it.\n\nHost-Only: VM communicates only with the host and other VMs on the same host; no internet access.\n\nInternal: VM communicates only with other VMs on the same internal network; not even the host can communicate with it.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-1-03',
    topicId: 'topic-c1-4-1',
    front: 'What is a VM snapshot, and what important limitation should you know?',
    back: 'A snapshot captures the complete state of a VM at a point in time: RAM contents, virtual disk state, and configuration. Use before updates or risky changes for instant rollback capability.\n\nKey limitation: Snapshots are NOT backups. They are stored on the same storage as the VM — if that storage fails, both the VM and all its snapshots are lost. Long snapshot chains also degrade performance and consume significant additional storage.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-1-04',
    topicId: 'topic-c1-4-1',
    front: 'What CPU hardware requirements must be met before running virtual machines?',
    back: 'The CPU must support hardware virtualization extensions:\n- Intel: VT-x (Intel Virtualization Technology)\n- AMD: AMD-V / SVM (Secure Virtual Machine)\n\nThese must be enabled in BIOS/UEFI — many systems ship with them disabled. Error "VT-x is not available" or "AMD-V is disabled" = enable the setting in BIOS setup.\n\nAdditional extensions:\n- Intel VT-d / AMD IOMMU: required for PCI passthrough\n- Intel EPT / AMD NPT: hardware-accelerated memory virtualization',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-1-05',
    topicId: 'topic-c1-4-1',
    front: 'Compare virtual machines (VMs) to containers. What is the key architectural difference?',
    back: 'Virtual Machines: include a full guest OS (kernel + userspace); isolated at the hardware level via hypervisor; size = GBs; startup = seconds to minutes; strong isolation.\n\nContainers (e.g., Docker): share the host OS kernel; isolated at the OS namespace/cgroup level; size = MBs; startup = milliseconds; lighter but less isolated.\n\nKey: containers are lighter because they do not include their own OS — they rely on the host kernel.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-1-06',
    topicId: 'topic-c1-4-1',
    front: 'What is thick provisioning vs. thin provisioning for virtual disks?',
    back: 'Thick provisioning: all storage space is allocated upfront. A 100 GB thick disk consumes 100 GB on the host immediately, regardless of how much data is stored. Better for predictable performance.\n\nThin provisioning: storage is allocated on demand as data is written. A 100 GB thin disk might consume only 5 GB initially. Better for storage efficiency, but can cause problems if the storage pool fills unexpectedly.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-1-07',
    topicId: 'topic-c1-4-1',
    front: 'Name four common virtual disk formats and which platform each is associated with.',
    back: 'VMDK (.vmdk) — VMware (Workstation, Fusion, ESXi); widely supported across platforms.\n\nVHD (.vhd) — Microsoft Hyper-V (older format); also used by Azure.\n\nVHDX (.vhdx) — Microsoft Hyper-V (modern format); supports up to 64 TB, better performance than VHD.\n\nQCOW2 (.qcow2) — QEMU/KVM; supports snapshots and compression natively.\n\nOVA/OVF (.ova/.ovf) — Open Virtualization Format; cross-platform portable VM packaging standard.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-1-08',
    topicId: 'topic-c1-4-1',
    front: 'What is VDI (Virtual Desktop Infrastructure) and how does it work?',
    back: 'VDI is a deployment model where user desktops run as VMs on centralized servers in a data center. Users connect remotely using thin clients, laptops, or other devices.\n\nComponents: VDI server (runs desktop VMs via Type 1 hypervisor) → Connection broker (routes users to their VM) → Thin client (user\'s access device) → Display protocol (RDP, PCoIP, ICA/HDX).\n\nBenefits: centralized management, data stays in data center, access from anywhere.\nDrawbacks: requires reliable low-latency network; graphics-intensive apps may perform poorly.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.2 Cloud Computing (8 cards) ────────────────────────────────────────

  {
    id: 'fc-c1-4-2-01',
    topicId: 'topic-c1-4-2',
    front: 'What are the three main cloud service models and who manages what in each?',
    back: 'IaaS (Infrastructure as a Service): customer manages OS, middleware, apps, data. Provider manages hardware, virtualization, network. Examples: AWS EC2, Azure VMs, Google Compute Engine.\n\nPaaS (Platform as a Service): customer manages apps and data only. Provider manages OS, runtime, middleware, and everything below. Examples: Heroku, AWS Elastic Beanstalk, Google App Engine.\n\nSaaS (Software as a Service): customer manages only their data and user settings. Provider manages everything. Examples: Microsoft 365, Google Workspace, Salesforce.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-2-02',
    topicId: 'topic-c1-4-2',
    front: 'What are the four cloud deployment models?',
    back: 'Public cloud: owned by a provider, shared among multiple tenants; accessed over the internet. Examples: AWS, Azure, GCP. Low cost, infinite scale, less control.\n\nPrivate cloud: provisioned for exclusive use by one organization; on-premise or hosted. Full control, high cost, strict compliance capability.\n\nHybrid cloud: combination of public and private; sensitive workloads on private, burst to public. Balance of control and scale.\n\nCommunity cloud: shared by several organizations with common concerns (e.g., healthcare compliance). Cost sharing among members.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-2-03',
    topicId: 'topic-c1-4-2',
    front: 'What are the five NIST essential characteristics of cloud computing?',
    back: '1. On-demand self-service: users provision resources without human interaction with the provider.\n\n2. Broad network access: accessible over the network from phones, tablets, laptops.\n\n3. Resource pooling: provider\'s resources pooled to serve multiple consumers (multi-tenant).\n\n4. Rapid elasticity: resources can scale up and down automatically with demand.\n\n5. Measured service: usage is monitored, controlled, and reported — pay for what you use.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-2-04',
    topicId: 'topic-c1-4-2',
    front: 'Explain the cloud shared responsibility model. What is ALWAYS the customer\'s responsibility?',
    back: 'In the shared responsibility model, security tasks are divided between cloud provider and customer based on the service model.\n\nAlways the PROVIDER\'s responsibility: physical data center, network infrastructure, hypervisor/virtualization layer.\n\nAlways the CUSTOMER\'s responsibility regardless of IaaS/PaaS/SaaS:\n- Data classification and protection\n- Identity and access management (IAM)\n- User account security and MFA\n\nVaries by model: OS patching (customer in IaaS; provider in PaaS/SaaS), application security (customer in IaaS/PaaS; provider in SaaS).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-2-05',
    topicId: 'topic-c1-4-2',
    front: 'What is a CDN (Content Delivery Network) and how does it improve performance?',
    back: 'A CDN is a geographically distributed network of servers that caches and delivers content from locations close to end users.\n\nHow it works: origin content is replicated to edge servers (Points of Presence — PoPs) worldwide. User requests are routed to the nearest edge server, reducing latency.\n\nBenefits: lower latency, reduced load on origin server, DDoS mitigation, high availability.\n\nExam scenario: if a user reports seeing stale website content, the CDN cache may need to be purged after a content update. Examples: Cloudflare, AWS CloudFront, Azure CDN, Akamai.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-2-06',
    topicId: 'topic-c1-4-2',
    front: 'What is the difference between AWS Direct Connect (or Azure ExpressRoute) and a VPN connection to the cloud?',
    back: 'VPN to cloud: encrypted IPsec tunnel over the public internet. Subject to internet latency variability and shared bandwidth. Lower cost, easier to set up.\n\nDirect Connect / ExpressRoute: dedicated private physical connection from the organization\'s data center directly to the cloud provider, bypassing the public internet. Benefits: more consistent latency (2–10 ms vs 5–50 ms), higher bandwidth (up to 10 Gbps), no shared internet path. Better for large data transfers and latency-sensitive applications. Higher cost.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-2-07',
    topicId: 'topic-c1-4-2',
    front: 'Compare on-premise vs. cloud in terms of CapEx, OpEx, and scalability.',
    back: 'On-premise:\n- High upfront CapEx (buy servers, networking, data center space)\n- Ongoing OpEx: power, cooling, IT staff, maintenance\n- Scaling up: purchase new hardware (weeks/months)\n- Scaling down: hardware sits idle\n- Predictable fixed cost after initial purchase\n\nCloud:\n- Low/no CapEx — pay-as-you-go OpEx\n- Scaling up: provision in minutes\n- Scaling down: stop paying for unused resources\n- Variable cost — can be unpredictable\n- No hardware depreciation\n\nTCO analysis is needed to determine which is cheaper for a given workload.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-4-2-08',
    topicId: 'topic-c1-4-2',
    front: 'What are the common cloud file storage/sync services and their default free storage amounts?',
    back: 'iCloud Drive (Apple) — 5 GB free; optimized for iOS/macOS.\nOneDrive (Microsoft) — 5 GB free (15 GB with Microsoft 365 subscription); integrated with Windows and Office.\nGoogle Drive (Google) — 15 GB free; shared with Gmail and Google Photos.\nDropbox — 2 GB free; cross-platform.\nBox — 10 GB free; enterprise-focused.\n\nAll services offer local sync and online-only (on-demand) file access modes. Online-only shows placeholders and downloads files only when opened, saving local disk space.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.1 Troubleshoot Motherboards, RAM, CPUs, Power (8 cards) ───────────

  {
    id: 'fc-c1-5-1-01',
    topicId: 'topic-c1-5-1',
    front: 'What is POST, and what happens during the POST sequence?',
    back: 'POST (Power-On Self Test): firmware diagnostic run at every power-on to verify hardware before OS loading.\n\nSequence:\n1. CPU initializes, executes firmware from ROM\n2. BIOS/UEFI checks its own integrity\n3. Chipset and memory controller initialized\n4. RAM tested\n5. Expansion cards and storage controllers discovered\n6. Control passed to bootloader\n\nIf POST fails: system produces beep codes (audio) or lights up POST LED indicators (Q-LED on modern UEFI motherboards). The last LED that stays lit indicates the failing component (CPU, DRAM, VGA, BOOT).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-1-02',
    topicId: 'topic-c1-5-1',
    front: 'What are the symptoms of a dead CMOS battery, and how do you fix it?',
    back: 'Symptoms of dead CMOS battery (CR2032 coin cell):\n- Date and time reset to default (e.g., Jan 1, 2000) every cold boot\n- BIOS settings revert to factory defaults after each power cycle\n- "CMOS checksum error" or "CMOS battery low" message at POST\n- Prompted to configure date/time on every boot\n\nFix:\n1. Power off, unplug, discharge (hold power button 5 sec)\n2. Locate the flat CR2032 on the motherboard\n3. Press retention clip, remove old battery\n4. Insert new CR2032 with + side up\n5. Power on, reset BIOS date/time and custom settings',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-1-03',
    topicId: 'topic-c1-5-1',
    front: 'What are the key symptoms of RAM failure, and how do you troubleshoot it?',
    back: 'RAM failure symptoms:\n- System won\'t POST (beep codes indicating RAM)\n- Random BSODs: MEMORY_MANAGEMENT (0x1A), PAGE_FAULT_IN_NONPAGED_AREA (0x50)\n- Crashes during memory-intensive tasks\n- Corrupted files or application errors\n- Random reboots\n\nTroubleshooting steps:\n1. Reseat RAM (remove, clean contacts, reinstall until clips click)\n2. Test one stick at a time in the primary slot (A2/DIMM1 per manual)\n3. Run MemTest86 from bootable USB — any errors = faulty RAM\n4. Check XMP/EXPO is enabled for DDR4/DDR5 kits running below rated speed\n5. Verify dual-channel slot configuration',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-1-04',
    topicId: 'topic-c1-5-1',
    front: 'What is XMP/EXPO, and why does it matter for RAM configuration?',
    back: 'XMP (Extreme Memory Profile) — Intel standard\nEXPO (Extended Profiles for Overclocking) — AMD standard\n\nPurpose: DDR4/DDR5 kits advertised at speeds like 3200 MHz or 6000 MHz default to JEDEC baseline speeds (2133 MHz or 4800 MHz) when installed. XMP/EXPO profiles stored on the RAM module tell the BIOS the correct frequency, voltage, and timings.\n\nMust be enabled in BIOS/UEFI to run RAM at advertised speed. Without it, the RAM runs slower than purchased. Running out-of-spec settings causes instability.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-1-05',
    topicId: 'topic-c1-5-1',
    front: 'What are the symptoms of CPU overheating, and how do you fix it?',
    back: 'CPU overheating symptoms:\n- Thermal throttling (performance becomes sluggish under load)\n- Sudden shutdown (thermal protection)\n- System restarts spontaneously\n- Fans running at maximum speed constantly\n- BSOD THERMAL_RUNAWAY\n\nNormal temps: 30–50°C idle; 70–85°C under load. Action needed: 85–95°C (high). Immediate: >95°C.\n\nFixes:\n1. Reseat heatsink — all mounting points must engage\n2. Reapply thermal paste — clean with IPA 90%+; pea-sized dot on CPU center\n3. Clean dust from heatsink fins and fan\n4. Verify CPU fan is spinning and connected\n5. Improve case airflow',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-1-06',
    topicId: 'topic-c1-5-1',
    front: 'How do you perform the paperclip test on a PSU, and what does it tell you?',
    back: 'The paperclip test checks whether a PSU can power on independently of the motherboard.\n\nProcedure:\n1. Disconnect PSU from all components\n2. Find the 24-pin ATX connector\n3. Insert a bent paperclip between the green wire (PS_ON, pin 16) and any black wire (ground/COM)\n4. Plug PSU into wall outlet\n5. Result: PSU fan should spin — confirms the PSU can power on\n\nLimitation: only confirms power-on at no load. A PSU can pass this test but fail under the actual system load. Use a multimeter to check voltage rails (+12V, +5V, +3.3V) for more complete testing.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-1-07',
    topicId: 'topic-c1-5-1',
    front: 'What are common Windows BSOD stop codes and their likely hardware causes?',
    back: 'IRQL_NOT_LESS_OR_EQUAL (0x0000000A) — Driver bug, bad RAM\nMEMORY_MANAGEMENT (0x0000001A) — Faulty RAM\nPAGE_FAULT_IN_NONPAGED_AREA (0x00000050) — Faulty RAM or driver\nSYSTEM_THREAD_EXCEPTION_NOT_HANDLED — Driver crash\nCRITICAL_PROCESS_DIED — Corrupted system file or driver\nKERNEL_SECURITY_CHECK_FAILURE — Driver or hardware malfunction\nNTFS_FILE_SYSTEM — Failing hard drive or file system corruption\n\nAnalysis tools: Event Viewer → Windows Logs → System; BlueScreenView or WinDbg to read minidump files from C:\\Windows\\Minidump\\',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-1-08',
    topicId: 'topic-c1-5-1',
    front: 'What is MemTest86 and how is it used?',
    back: 'MemTest86 is the gold-standard RAM testing tool. It runs independently from a bootable USB drive — no OS required — allowing it to test RAM without OS interference.\n\nHow to use:\n1. Download from memtest86.com, write ISO to USB\n2. Boot from the USB drive\n3. Allow all tests to run (at least one full pass; 30–60 minutes)\n4. Any errors reported = faulty RAM — identify and replace the failing module\n\nTests address lines, data lines, and read/write patterns. Catches both hard failures and intermittent (thermal-sensitive) failures. Run multiple passes for maximum confidence.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.2 Troubleshoot Storage & RAID (8 cards) ────────────────────────────

  {
    id: 'fc-c1-5-2-01',
    topicId: 'topic-c1-5-2',
    front: 'What are the key audible symptoms of a failing HDD and what do they indicate?',
    back: 'Clicking or ticking ("click of death"): read/write head failing to find tracks — severe failure imminent. Power off immediately.\n\nGrinding: head is physically contacting the platter — immediate data loss. Power off immediately.\n\nRepetitive chirping: calibration failure, seek errors.\n\nDrive spinning up and down repeatedly: power issue or drive unresponsive to commands.\n\nSilence (no spin): seized spindle motor or PCB failure.\n\nAction for clicking/grinding: power off, do not run any writes, image the drive with ddrescue or Clonezilla, recover files from the image.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-2-02',
    topicId: 'topic-c1-5-2',
    front: 'What is S.M.A.R.T. and which attributes are most critical to monitor?',
    back: 'S.M.A.R.T. (Self-Monitoring, Analysis and Reporting Technology): built-in drive monitoring system that tracks health indicators and can predict failure.\n\nMost critical attributes:\n- Reallocated Sectors Count (0x05): any count above 0 is concerning\n- Current Pending Sectors (0xC5): sectors with active read errors waiting to be remapped — non-zero = serious\n- Uncorrectable Sector Count (0xC6): sectors that could not be corrected — any non-zero = critical\n- SSD Wear Leveling Count (0xB3): remaining write endurance; 0 = end of life\n\nTool: CrystalDiskInfo (Windows). Status: Good / Caution / Bad.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-2-03',
    topicId: 'topic-c1-5-2',
    front: 'Compare RAID 0, 1, 5, 6, and 10 in terms of fault tolerance and minimum drives.',
    back: 'RAID 0 (Striping): 2 drives min. Zero fault tolerance — any drive fails = total data loss. Performance only.\n\nRAID 1 (Mirroring): 2 drives min. Tolerates 1 drive failure. 50% capacity utilization.\n\nRAID 5 (Stripe + parity): 3 drives min. Tolerates 1 drive failure. Capacity = n-1 drives. Rebuild risk during recovery.\n\nRAID 6 (Stripe + dual parity): 4 drives min. Tolerates 2 simultaneous drive failures. Capacity = n-2 drives.\n\nRAID 10 (Stripe of mirrors): 4 drives min. Tolerates 1 failure per mirrored pair. Fails if both drives in the SAME pair fail. 50% capacity.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-2-04',
    topicId: 'topic-c1-5-2',
    front: 'What is the cardinal rule of data recovery from a failing drive?',
    back: 'Do NOT write to a failing drive. Every write operation risks overwriting recoverable data.\n\nThis means:\n- Do not save files to the failing drive\n- Do not defragment the drive\n- Do not run chkdsk /r (it writes to sectors)\n- Do not attempt OS installation on it\n\nCorrect approach:\n1. Power off if clicking or grinding\n2. Image the drive first using ddrescue or Clonezilla (sector-by-sector copy; skips unreadable sectors gracefully)\n3. Recover files from the IMAGE, not the original drive\n4. For physical damage: professional cleanroom recovery (DriveSavers, Ontrack)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-2-05',
    topicId: 'topic-c1-5-2',
    front: 'How does RAID 5 rebuild work, and why is it the most dangerous time for data loss?',
    back: 'When a RAID 5 drive fails:\n1. Array enters degraded mode — still operational; data reconstructed from parity on reads\n2. Replacement drive is installed\n3. Controller reads ALL surviving drives in their entirety to recalculate and write the missing data to the new drive\n4. Rebuild time: 4–24+ hours depending on array size\n\nWhy it\'s dangerous: during rebuild, ALL surviving drives are under continuous heavy read load. If ANY one of them fails during the rebuild, the RAID 5 array fails completely and all data is lost — RAID 5 can only tolerate one failure at a time. Always maintain a spare drive and back up RAID 5 arrays.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-2-06',
    topicId: 'topic-c1-5-2',
    front: 'What are common boot error messages and their causes?',
    back: 'NTLDR is missing — Windows XP boot file missing; boot from XP CD, use recovery console.\n\nBOOTMGR is missing — Windows Vista/7/8/10/11 boot manager missing; boot from Windows media, run Startup Repair or bootrec /fixmbr.\n\nOperating System not found — boot device not in BIOS boot order, or drive failure; check BIOS boot order and drive health.\n\nGrub rescue prompt — GRUB (Linux) bootloader corrupted; boot from Linux live USB, run grub-install.\n\nInvalid partition table — MBR corruption; repair with bootrec /fixmbr (Windows) or testdisk (Linux).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-2-07',
    topicId: 'topic-c1-5-2',
    front: 'How do SSDs fail differently from HDDs?',
    back: 'HDDs (mechanical): fail with audible symptoms (clicking, grinding), gradual S.M.A.R.T. degradation, bad sectors. Sudden catastrophic failure less common.\n\nSSDs (solid state, no moving parts): NO audible symptoms.\nSSD-specific failure modes:\n- Sudden disappearance: controller failure — drive vanishes from BIOS and OS completely\n- Read-only mode: SSD detected TBW (Terabytes Written) limit approaching — locks drive to preserve data\n- Worn NAND: corrupted data from worn cells\n- Extremely slow performance: cache exhausted or heavy wear leveling\n\nAdvantage: SSDs often degrade gracefully (read-only mode), preserving data. Monitor S.M.A.R.T. wear indicators.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-2-08',
    topicId: 'topic-c1-5-2',
    front: 'What steps should be taken when a drive is not detected in BIOS/UEFI?',
    back: '1. Check physical connections: SATA data cable and SATA power connector (or M.2 seating for NVMe).\n\n2. Try a different SATA port: some ports share bandwidth or can malfunction.\n\n3. Try a different SATA data cable: SATA data cables fail more often than expected.\n\n4. Verify drive power: confirm PSU SATA power connector is supplying power.\n\n5. Check BIOS storage mode: AHCI vs. IDE — changing after OS installation breaks Windows.\n\n6. If an M.2 drive: verify it is fully seated and the retaining screw is tightened.\n\n7. Test the drive in another system to rule out drive failure.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.3 Troubleshoot Display Issues (8 cards) ────────────────────────────

  {
    id: 'fc-c1-5-3-01',
    topicId: 'topic-c1-5-3',
    front: 'A laptop screen is completely dark. How do you determine whether the backlight or display panel has failed?',
    back: 'Flashlight test: shine a flashlight at an angle close to the display surface in a darkened room.\n\n- If you can see a faint image: the display panel and GPU are working correctly — only the backlight has failed. Replace the inverter (CCFL) or display assembly (LED).\n\n- If you see nothing at all: the panel itself may have failed, or the GPU is not sending a signal to the display.\n\nSecondary check: connect an external monitor. If external works but internal doesn\'t, the issue is between the GPU and the built-in display (flex cable, panel, or backlight).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-3-02',
    topicId: 'topic-c1-5-3',
    front: 'What is the difference between a dead pixel and a stuck pixel?',
    back: 'Dead pixel: always black. The transistor is not receiving power. Cannot be fixed with software. Hardware defect.\n\nStuck pixel: always one color (red, green, or blue). A sub-pixel element is stuck in the ON state. Sometimes fixable with pixel-refresher software (JScreenFix, UDPixel) that rapidly cycles colors.\n\nHot pixel: always bright white. All three color sub-pixels (red, green, blue) are stuck fully ON.\n\nDead pixels appear as black dots on any background. Stuck pixels are visible on certain background colors. Use a solid-color test tool cycling red, green, blue, white, and black to identify them.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-3-03',
    topicId: 'topic-c1-5-3',
    front: 'What causes display flickering, and how do you diagnose it?',
    back: 'Common causes of display flickering:\n- Loose or damaged video cable: flicker when cable or lid is moved → reseat or replace cable\n- Refresh rate mismatch: consistent regular flicker → set correct refresh rate in Display Settings\n- Failing GPU: erratic flicker under load → update or roll back drivers; may be GPU failure\n- Internal eDP/LVDS cable (laptop): flicker when lid angle changes → cable through hinge is damaged\n- Driver issue: started after driver update → roll back display driver\n- Monitor hardware failure: constant unpredictable flicker → replace monitor\n\nDiagnose: check Right-click Desktop → Display Settings → Advanced Display Settings → refresh rate.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-3-04',
    topicId: 'topic-c1-5-3',
    front: 'What visual artifacts indicate GPU or VRAM failure?',
    back: 'GPU/VRAM failure artifacts:\n- Texture corruption: wrong colors or patterns on 3D surfaces → failing VRAM\n- Random colored pixels or blocks: scattered wrong-color dots → overheating VRAM or failing GPU\n- Geometry distortion: 3D objects have wrong shapes → GPU shader unit failure\n- Driver crash + black screen: "Display driver stopped responding" recovery → GPU overheating or driver bug\n- Screen tearing: horizontal displacement/split in image → V-sync disabled (not usually hardware failure)\n\nDiagnose: run FurMark stress test; monitor GPU temperature with GPU-Z or HWiNFO. Normal gaming: 70–85°C. Throttle threshold: 90–95°C.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-3-05',
    topicId: 'topic-c1-5-3',
    front: 'What is the systematic approach to troubleshooting "no image" on a display?',
    back: '1. Verify monitor is powered on — check power LED (amber/orange = standby, green = active with signal).\n2. Check input source — cycle monitor inputs (HDMI, DisplayPort, VGA) to match the connected cable.\n3. Check cable — reseat at both ends; try a different cable.\n4. Test with a different monitor — rule out monitor failure.\n5. Try a different GPU output port — try each port on the GPU.\n6. Check GPU seating — reseat GPU in PCIe slot until retention clip clicks.\n7. Check BIOS output setting — is video going to discrete or integrated GPU?\n8. Remove discrete GPU, test with integrated GPU — determines if discrete GPU has failed.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-3-06',
    topicId: 'topic-c1-5-3',
    front: 'What causes color display problems on monitors, and what is each symptom\'s likely cause?',
    back: 'Overall pink or red tint: failing CCFL backlight nearing end of life.\n\nSingle color cast (blue, green, or red dominant): damaged video cable — one signal pair broken.\n\nWashed out / faded colors: incorrect contrast/brightness settings or display calibration.\n\nInverted colors: accessibility setting enabled (High Contrast / Color Inversion) or GPU color inversion.\n\nGreen or magenta horizontal lines: failing GPU or display controller.\n\nIncorrect colors only on external display: wrong ICC profile assigned or cable issue to external display.\n\nFix: check settings first; replace cable; update/rollback display driver; calibrate display (Windows: search "Calibrate display color").',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-3-07',
    topicId: 'topic-c1-5-3',
    front: 'What causes a blurry or incorrectly scaled display, and how is it fixed?',
    back: 'Wrong resolution: non-native resolution on an LCD looks blurry due to scaling. Fix: set the resolution labeled "(Recommended)" in Display Settings — this is the panel\'s native resolution.\n\nDriver not installed: without the GPU driver, Windows uses Microsoft Basic Display Adapter, limiting resolution options and disabling hardware acceleration. Fix: install correct GPU driver from Intel/AMD/Nvidia.\n\nHigh DPI / scaling: on 4K displays, 100% scaling may make text tiny. Fix: Settings → Display → Scale → set to 125–200%.\n\nApp blurry on high-DPI: older apps not DPI-aware appear blurry. Fix: app Properties → Compatibility → Change high DPI settings → Override DPI scaling.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-3-08',
    topicId: 'topic-c1-5-3',
    front: 'What are common projector-specific issues and their fixes?',
    back: 'No image from laptop: laptop not outputting to external display → press Fn+F5 or Win+P to toggle display mode.\n\nNo image (projector): wrong input source selected → press Input/Source button on projector.\n\nDim image: aging lamp → replace projector lamp (rated 2,000–5,000 hours).\n\nOverheating/shutdown: clogged air filter → clean or replace filter.\n\nOut of focus: focus ring not adjusted → manually adjust focus ring on lens.\n\nKeystone distortion: projector not perpendicular to screen → adjust keystone correction in projector menu.\n\nImportant: allow projector to cool completely before moving — hot lamp can crack or break if moved.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.4 Troubleshoot Mobile Devices (8 cards) ────────────────────────────

  {
    id: 'fc-c1-5-4-01',
    topicId: 'topic-c1-5-4',
    front: 'What are the main causes of rapid battery drain on a mobile device?',
    back: 'Primary causes:\n- Screen brightness (single largest consumer) → reduce brightness, enable auto-brightness\n- Background app activity → disable background refresh for non-essential apps\n- Weak cellular signal (phone increases transmit power) → enable Wi-Fi when available\n- Location services / constant GPS polling → limit to "While Using" for apps\n- Push email / notifications → reduce push frequency\n- Aging battery (Li-ion loses capacity with age and charge cycles) → check battery health; replace if below 80%\n- Rogue app (crash loop or CPU runaway) → check battery usage in Settings; uninstall suspect app\n\nCheck: iOS: Settings → Battery → Battery Health & Charging. Android: Settings → Battery → Battery Usage.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-4-02',
    topicId: 'topic-c1-5-4',
    front: 'What is a swollen Li-ion battery and how should it be handled?',
    back: 'A swollen (puffed up) Li-ion battery has accumulated gas from electrolyte decomposition, causing the battery pouch to expand. Causes: overcharging, heat damage, manufacturing defects, or age.\n\nSigns: back cover bulging outward, device components separating, increased device thickness.\n\nHazard: swollen Li-ion batteries are a fire and explosion risk.\n\nDo NOT: puncture, compress, bend, or heat the battery. Do NOT charge the device.\n\nDo: store in a fireproof container or bag. Remove and safely dispose of the battery as soon as possible (professional repair recommended). Keep away from flammable materials.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-4-03',
    topicId: 'topic-c1-5-4',
    front: 'What is the correct immediate response to a smartphone dropped in water?',
    back: '1. Power off immediately — do NOT attempt to use or test it (shorting causes permanent damage).\n2. Remove SIM card and tray.\n3. Gently shake water from ports.\n4. Pat dry with absorbent cloth — do NOT rub.\n5. Place in container with silica gel desiccant packets — NOT rice (ineffective myth).\n6. Wait 24–48 hours before attempting to power on.\n\nDo NOT:\n- Put in rice (poor desiccant; dust enters ports)\n- Use hair dryer or oven (heat damages battery and plastic)\n- Shake vigorously (spreads water)\n- Charge immediately (moisture + electricity = shorts)\n\nIP67/IP68 ratings help but are not guarantees, especially with aging seals.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-4-04',
    topicId: 'topic-c1-5-4',
    front: 'What causes ghost touches on a touchscreen and how are they resolved?',
    back: 'Ghost touches: the screen responds to touches that are not occurring.\n\nCauses:\n- Moisture under screen (liquid shorting digitizer traces)\n- Cracked digitizer glass creating false electrical contacts\n- Defective or poor-quality screen protector\n- Loose digitizer ribbon cable connector (especially after battery swelling or flexion)\n- EMI interference (rare)\n\nTroubleshooting steps:\n1. Remove screen protector and test\n2. Check for water damage — dry device thoroughly\n3. Inspect for cracked glass\n4. If accessible: reseat digitizer connector\n5. Replace digitizer/display assembly\n\nGhost touches with no drop/crack often indicate a loose digitizer connector.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-4-05',
    topicId: 'topic-c1-5-4',
    front: 'What is the force restart sequence for iPhone 8 and later models?',
    back: 'iPhone 8, 9 (SE 2nd gen), 10 (X), 11, 12, 13, 14, 15, 16 series:\n1. Press and quickly release the Volume Up button\n2. Press and quickly release the Volume Down button\n3. Press and hold the Side (Power) button until the Apple logo appears\n\nThis is a hardware-level restart that clears the device\'s memory state without erasing data. Use when the touchscreen is completely unresponsive or the device is frozen.\n\niPhone 7: Hold Volume Down + Side button simultaneously.\niPhone 6s and earlier: Hold Home + Power simultaneously.\nMost Android: Hold Power + Volume Down for 10–15 seconds.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-4-06',
    topicId: 'topic-c1-5-4',
    front: 'What are APN settings and when should they be reconfigured?',
    back: 'APN (Access Point Name): configuration settings that tell a mobile device how to connect to the carrier\'s mobile data network. Required for mobile data, MMS messaging, and tethering.\n\nAPNs are normally provisioned automatically when a SIM card is inserted. Manual reconfiguration is needed when:\n- Using a carrier or MVNO that does not auto-provision APNs\n- APN settings were accidentally changed or corrupted\n- Upgrading to a new device without profile transfer\n- No data connectivity despite strong signal and active data plan\n\nLocation:\n- iOS: Settings → Cellular → Cellular Data Network → APN\n- Android: Settings → Network & Internet → Mobile Network → Advanced → APNs',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-4-07',
    topicId: 'topic-c1-5-4',
    front: 'What are IP67 and IP68 ratings on mobile devices?',
    back: 'IP (Ingress Protection) ratings describe a device\'s resistance to dust and water ingress.\n\nFormat: IP[solid particle rating][liquid rating]\n\nFirst digit (6): dust tight — no ingress of dust.\n\nSecond digit:\n- 7: water resistant to 1 meter depth for 30 minutes\n- 8: water resistant to 1.5–6 meters for 30 minutes (exact depth varies by manufacturer)\n\nImportant limitations:\n- Ratings are from laboratory testing under controlled conditions\n- Real-world protection is lower — aging seals, drops, and pressure variance reduce protection\n- IP ratings do not mean the device is waterproof — water damage voids most warranties\n- Saltwater and chlorinated water are more corrosive than fresh water',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-4-08',
    topicId: 'topic-c1-5-4',
    front: 'What is A-GPS (Assisted GPS) and how does it improve GPS performance?',
    back: 'A-GPS (Assisted GPS): a system that uses cellular network data and Wi-Fi to speed up GPS satellite acquisition.\n\nHow standard GPS works: the receiver must download satellite ephemeris (orbit) data directly from satellites — cold start can take 1–5 minutes in open sky.\n\nHow A-GPS improves this: downloads current satellite position data (ephemeris) from internet servers via cellular/Wi-Fi, dramatically reducing time-to-first-fix to seconds.\n\nPractical impact: Android\'s High Accuracy mode enables A-GPS. If GPS is slow, ensure: Location is on, High Accuracy mode is selected, cellular/Wi-Fi is available for data download, and that A-GPS data is current (some Android apps offer "A-GPS reset" to force a fresh download).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.5 Troubleshoot Network Issues (8 cards) ────────────────────────────

  {
    id: 'fc-c1-5-5-01',
    topicId: 'topic-c1-5-5',
    front: 'What does an APIPA address (169.254.x.x) mean, and what causes it?',
    back: 'APIPA (Automatic Private IP Addressing): Windows assigns itself a 169.254.x.x address when it FAILS to receive an IP from a DHCP server.\n\nAPIPА range: 169.254.0.0/16 (169.254.0.1 – 169.254.255.254)\n\nAn APIPA address means: no default gateway, no DNS server, no internet access. Can only communicate with other APIPA devices on the same physical segment.\n\nCommon causes:\n- No cable connection (Physical Layer)\n- DHCP server is down\n- DHCP scope exhausted (all IPs leased out)\n- Switch port in wrong VLAN (DHCP requests never reach server)\n\nFix: ipconfig /release then ipconfig /renew after resolving the underlying cause.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-5-02',
    topicId: 'topic-c1-5-5',
    front: 'What is the OSI bottom-up troubleshooting approach for network problems?',
    back: 'Always start at Layer 1 (Physical) and work upward — problems at lower layers affect all layers above.\n\nLayer 1 (Physical): cable connected? Link LED lit on NIC and switch? Wi-Fi enabled?\nLayer 2 (Data Link): correct VLAN? MAC address visible? (arp -a)\nLayer 3 (Network): valid IP? (ipconfig) — APIPA or correct address?\nLayer 3: can ping loopback (127.0.0.1)? Own IP? Default gateway?\nLayer 3: can ping 8.8.8.8? (tests internet routing without DNS)\nLayer 5–7 (Application): can ping google.com? (tests DNS) Use nslookup to isolate DNS.\n\nTool summary: ipconfig, ping, tracert, nslookup, netstat, arp -a',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-5-03',
    topicId: 'topic-c1-5-5',
    front: 'What is a duplex mismatch and how does it degrade network performance?',
    back: 'Duplex mismatch: one side of a network link is full duplex, the other is half duplex.\n\nHow it causes problems:\n- Full duplex side sends and receives simultaneously\n- Half duplex side uses CSMA/CD and detects simultaneous traffic as collisions\n- High collision rate → frequent retransmissions → extremely slow throughput\n- Symptom: link established and valid IP assigned, but very slow transfer speeds; late collisions visible in switch port statistics\n\nDiagnosis: check switch port statistics for late collisions (collisions after 512 bit-times).\n\nFix: either hardcode BOTH sides to the same speed/duplex, OR leave BOTH on auto-negotiate. Never mix hardcoded on one side with auto-negotiate on the other.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-5-04',
    topicId: 'topic-c1-5-5',
    front: 'What are the key Windows network troubleshooting commands and what does each do?',
    back: 'ipconfig — show IP address, subnet mask, default gateway\nipconfig /all — all adapter details including MAC address and DHCP server\nipconfig /release — release current DHCP lease\nipconfig /renew — request new DHCP lease\nipconfig /flushdns — clear local DNS resolver cache\n\nping [IP/hostname] — test Layer 3 connectivity and name resolution\nping 127.0.0.1 — test local TCP/IP stack\nping -t [IP] — continuous ping (Ctrl+C to stop)\n\ntracert [IP/hostname] — trace route, show each hop\nnslookup [hostname] — DNS query; diagnose DNS failures\nnetstat -an — show active connections and listening ports\narp -a — show ARP cache (IP-to-MAC mappings)\nnetsh winsock reset — reset TCP/IP stack\nTest-NetConnection (PowerShell) — test TCP connectivity to a specific port',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-5-05',
    topicId: 'topic-c1-5-5',
    front: 'How do you troubleshoot a DNS failure where IP-based access works but domain names fail?',
    back: 'Confirm DNS is the issue: ping 8.8.8.8 succeeds (internet works) but ping google.com fails (name resolution broken).\n\nDiagnose:\nnslookup google.com — directly queries DNS server; shows if server responds and what it returns.\nnslookup google.com 8.8.8.8 — query Google DNS directly, bypassing configured DNS. If this works but configured DNS doesn\'t, the configured DNS server is the problem.\n\nFix options:\n- ipconfig /flushdns — clear stale cache (if old IP was cached)\n- Change DNS to 8.8.8.8 (Google) or 1.1.1.1 (Cloudflare) temporarily\n- Restart DNS client service if DNS resolver is crashed\n- Check router\'s WAN DNS settings if all devices affected',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-5-06',
    topicId: 'topic-c1-5-5',
    front: 'What is a VLAN mismatch and what are its symptoms?',
    back: 'VLAN mismatch: a switch port is configured for the wrong VLAN, placing the device on the wrong logical network segment.\n\nSymptoms:\n- Device gets an IP from the wrong subnet (e.g., 192.168.20.x instead of expected 192.168.10.x)\n- Device cannot reach expected resources even with a valid IP\n- Device gets an APIPA address if the wrong VLAN has no DHCP server\n\nCommon scenario: device moved to a different switch port that is in a different VLAN; or switch port accidentally reconfigured during network maintenance.\n\nDiagnosis: check the IP subnet received vs. expected. Check switch port VLAN configuration.\nFix: on the switch, set the correct access VLAN on the affected port.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-5-07',
    topicId: 'topic-c1-5-5',
    front: 'What is port flapping and what are its common causes?',
    back: 'Port flapping: a switch port repeatedly transitions between up and down states.\n\nSymptoms:\n- Intermittent connectivity that comes and goes\n- Switch logs show repeated "link up" / "link down" on same port\n- In-progress connections drop (file transfers, video calls)\n\nCommon causes:\n- Damaged network cable (most common)\n- Loose or poorly crimped RJ-45 connector\n- Failing NIC\n- Failing switch port\n- Duplex/speed auto-negotiation conflict\n- PoE power budget exceeded (too many PoE devices)\n\nDiagnosis: flex and move the cable while watching connectivity — if it changes with cable movement, cable is the cause. Replace cable first.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-5-08',
    topicId: 'topic-c1-5-5',
    front: 'What non-overlapping Wi-Fi channels exist for 2.4 GHz, and why does channel selection matter?',
    back: '2.4 GHz non-overlapping channels: 1, 6, and 11 (only these three are truly non-overlapping in the standard 20 MHz channel width).\n\n5 GHz: many non-overlapping channels (36, 40, 44, 48, 52, 56, etc.) — much less congestion.\n\nWhy it matters: overlapping channels cause interference between nearby access points, reducing throughput and increasing latency. In dense Wi-Fi environments (apartments, offices), all APs should use channels 1, 6, or 11 to minimize interference.\n\nDiagnosis tool: Wi-Fi Analyzer (Android), Wireless Diagnostics (macOS) — shows which channels nearby APs are using. Select the least-used channel on your AP.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.6 Troubleshoot Printers (8 cards) ──────────────────────────────────

  {
    id: 'fc-c1-5-6-01',
    topicId: 'topic-c1-5-6',
    front: 'What are the seven steps of the laser printing process in order?',
    back: '1. Processing — RIP (Raster Image Processing) converts the print job to a raster image\n2. Charging — Primary Charge Roller (PCR) or corona wire applies a uniform negative charge (~-600V) to the drum\n3. Exposing — laser writes the image onto the drum, discharging areas to ~-100V where toner should adhere\n4. Developing — negatively charged toner is attracted to the less-negative (exposed) areas on the drum\n5. Transferring — transfer roller/corona wire transfers toner from drum to paper\n6. Fusing — fuser assembly melts toner into paper using heat (~200°C) and pressure rollers\n7. Cleaning — cleaning blade removes residual toner from drum for next cycle',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-6-02',
    topicId: 'topic-c1-5-6',
    front: 'Match each laser printer print quality symptom to its most likely failing component.',
    back: 'Smearing / toner rubs off → Fuser assembly (not reaching correct temperature; rollers worn)\n\nGhosting (faint duplicate image lower on page) → Drum or cleaning blade (residual toner not cleaned)\n\nVertical lines down page → Drum surface scratched, or dirty developer roller on toner cartridge\n\nCompletely blank page → No toner, PCR failure, or laser unit failure\n\nAll-black page → PCR or corona wire not charging drum (all toner sticks everywhere)\n\nFaded/light print → Low toner, density set too low, or worn drum\n\nBackground speckling → High humidity, worn drum, or poor paper quality\n\nPaper jams at pickup → Worn pickup roller',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-6-03',
    topicId: 'topic-c1-5-6',
    front: 'How do you restart the Windows Print Spooler and clear a stuck print queue?',
    back: 'Restart Print Spooler (Method 1 — Services):\nWin+R → services.msc → Print Spooler → Right-click → Restart\n\nRestart via Command Line (Admin):\nnet stop spooler\nnet start spooler\n\nClear a stuck print queue (when restart alone doesn\'t work):\n1. net stop spooler\n2. Navigate to C:\\Windows\\System32\\spool\\PRINTERS\\\n3. Delete all .SHD and .SPL files (do NOT delete the PRINTERS folder itself)\n4. net start spooler\n\nThe Print Spooler must be stopped before deleting spool files — files in use by the running service cannot be deleted.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-6-04',
    topicId: 'topic-c1-5-6',
    front: 'Why does a network printer\'s IP address change cause printing to fail, and what are the solutions?',
    back: 'Problem: network printers receive IP via DHCP. When the DHCP lease renews, the printer may get a different IP. All computers configured to print to the old IP fail — Windows cannot reach the printer at the old address.\n\nSolutions:\n1. DHCP reservation (recommended): bind the printer\'s MAC address to a fixed IP on the router/DHCP server. The printer always receives the same IP from DHCP without needing manual configuration on the printer.\n\n2. Static IP on printer: configure a fixed IP directly on the printer\'s network settings (must be outside the DHCP pool range). No server-side configuration needed, but must manually configure gateway/subnet.\n\n3. Update printer port: Devices and Printers → Printer Properties → Ports → Configure Port → update IP. Must be done on every affected computer.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-6-05',
    topicId: 'topic-c1-5-6',
    front: 'What are the common inkjet printer problems and their causes?',
    back: 'Banding (horizontal white streaks at regular intervals): clogged printhead nozzles → run printhead cleaning utility 1–3 times.\n\nFaded or wrong colors: low or empty ink cartridge → replace cartridge.\n\nColors bleed or blotch: wrong paper type or too much ink density → use correct inkjet paper.\n\nLines are jagged or misaligned: printhead alignment off → run printhead alignment utility.\n\nMissing color entirely: one cartridge empty or completely clogged nozzle → replace cartridge or deep clean cycle.\n\nSmearing: paper not absorbing ink (wrong paper type) or humidity → use correct inkjet paper.\n\nExcessive cleaning (more than 3 cycles) wastes ink without helping. Allow overnight rest for severe clogs.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-6-06',
    topicId: 'topic-c1-5-6',
    front: 'How do thermal printers work, and how do you troubleshoot faded or blank output?',
    back: 'Thermal printers use heat-sensitive paper — no ink or toner. A thermal printhead selectively heats the paper to create the image. Common uses: receipts, labels, fax machines.\n\nFaded output causes:\n- Dirty printhead (most common): clean with isopropyl alcohol swab\n- Paper loaded backward (non-thermal side facing printhead)\n\nBlank output causes:\n- Printhead failure\n- Paper loaded backward\n\nDiagnostic test: scratch the paper with a fingernail — the side that produces a dark mark is the thermal (heat-sensitive) side. This side must face the printhead.\n\nBlack streak down output: a stuck/burned heating element → replace printhead.\n\nNote: thermal printouts fade over time — use archival paper or laser/inkjet for permanent records.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-6-07',
    topicId: 'topic-c1-5-6',
    front: 'What is Apple AirPrint and what are common AirPrint troubleshooting steps?',
    back: 'AirPrint: Apple\'s wireless printing technology that allows iOS and macOS devices to print to compatible printers on the same Wi-Fi network without installing any drivers.\n\nRequirements: AirPrint-compatible printer, iOS/macOS device, both on the same Wi-Fi network (not a guest VLAN — guest networks typically block device-to-device communication).\n\nTroubleshooting:\n- Printer not found: verify printer and iOS device are on the SAME Wi-Fi network (not guest vs. main network split); verify printer supports AirPrint.\n- Print job queued but never prints: restart printer; check paper/ink.\n- Connection failed: disable/re-enable Wi-Fi on iOS device; restart printer.\n- Check manufacturer\'s AirPrint compatibility list if unsure.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c1-5-6-08',
    topicId: 'topic-c1-5-6',
    front: 'What are the correct steps to safely clear a paper jam in a laser printer?',
    back: '1. Turn off the printer before reaching inside (laser printers: allow the fuser to cool — it operates at ~200°C).\n2. Remove paper from the input tray.\n3. Open all relevant access panels (most printers have rear and top/front jam-clearing access panels).\n4. Pull jammed paper slowly and steadily in the DIRECTION OF PAPER TRAVEL — never pull against it.\n5. Inspect for torn paper fragments — use a flashlight to check the entire paper path. Any fragment left inside will cause repeated jams.\n6. Close all panels; reload paper.\n7. Run a test page to confirm the jam is fully cleared.\n\nCritical: never pull paper backward in a laser printer — the fuser rollers grip with significant force; pulling backward tears paper and leaves fragments near the fuser (fire risk).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

]
