// 80 flashcards for CompTIA A+ 220-1202 Core 2 Domain 4: Operational Procedures
// Covers objectives 4.1–4.10

const NOW = new Date().toISOString()

export const BATCH7_FLASHCARDS = [

  // ─── 4.1 Documentation (8 cards) ─────────────────────────────────────────────

  {
    id: 'fc-c2-4-1-01',
    topicId: 'topic-c2-4-1',
    front: 'What is the difference between a logical and a physical network diagram?',
    back: 'Logical diagram: shows how data flows — IP addresses, VLANs, routing paths, firewall zones, device hostnames. Use for troubleshooting routing, planning firewall rules, or understanding traffic flow.\n\nPhysical diagram: shows where things physically are — cable runs, rack numbers, room numbers, patch panel port assignments. Use for physical cabling work or locating equipment in a data center.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-02',
    topicId: 'topic-c2-4-1',
    front: 'What is a CMDB and how does it extend a basic asset inventory?',
    back: 'CMDB (Configuration Management Database): an ITIL concept that extends the asset inventory to also track relationships between configuration items — which servers run which services, which apps depend on which databases, which switches connect to which.\n\nBasic asset inventory: tracks individual assets (serial number, model, location, warranty, assigned user).\n\nCMDB adds the dependency map — critical for impact analysis when planning changes.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-03',
    topicId: 'topic-c2-4-1',
    front: 'What is a baseline configuration and why is it important?',
    back: 'A baseline is the documented, approved configuration of a system at a specific point in time — the "known good" state.\n\nTwo purposes:\n1. Consistency: new systems are deployed to match the baseline (using imaging or config management tools)\n2. Change detection: comparing current state to baseline reveals unauthorized changes, configuration drift, or indicators of compromise\n\nBaselines are updated after every approved change.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-04',
    topicId: 'topic-c2-4-1',
    front: 'What is an SOP and what types of tasks should have one?',
    back: 'SOP (Standard Operating Procedure): a documented, step-by-step procedure for a repeatable task. Ensures the same task is performed the same way regardless of which technician does it.\n\nCommon IT SOPs:\n- New employee workstation setup\n- Employee offboarding (disable account, backup data, return equipment)\n- Monthly patch management cycle\n- Backup verification\n- Data recovery procedures\n\nSOPs enable consistent onboarding and help meet compliance requirements.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-05',
    topicId: 'topic-c2-4-1',
    front: 'What is a chain of custody record and when is it required?',
    back: 'Chain of custody: documentation of every person who handles evidence from the moment of discovery through legal proceedings.\n\nRequired when: handling digital evidence for legal proceedings or internal investigations.\n\nMust record: description of evidence (device serial number), date/time collected, name and signature of each person who handled it, purpose of each transfer, storage conditions.\n\nAny break in the chain of custody can make evidence inadmissible in court.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-06',
    topicId: 'topic-c2-4-1',
    front: 'What is the standard lifecycle of a support ticket in a ticketing system?',
    back: '1. Open — user reports issue; ticket created with symptoms, contact info, priority; SLA clock starts\n2. Assigned — routed to appropriate team or technician\n3. In Progress — technician investigates; all steps documented; user updated\n4. Resolved — issue fixed; resolution documented in detail (not just "fixed")\n5. Closed — user confirms resolution or auto-closes after waiting period; ticket available for reporting\n\nEvery ticket must document: exact symptoms, all steps tried, root cause, and specific resolution.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-07',
    topicId: 'topic-c2-4-1',
    front: 'What is an SLA and what does it define in an IT context?',
    back: 'SLA (Service Level Agreement): a formal agreement defining the required response and resolution times by priority level.\n\nExample:\n- P1 (system down, critical): 15-minute response, 4-hour resolution\n- P3 (minor issue): 4-hour response, next-business-day resolution\n\nSLAs create accountability, are contractually enforceable in MSP agreements, and drive prioritization in ticketing systems. The SLA clock starts when the ticket is opened.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-1-08',
    topicId: 'topic-c2-4-1',
    front: 'What regulations require organizations to retain audit trails, and what do audit trails demonstrate?',
    back: 'Regulations requiring audit trail retention: HIPAA (healthcare), PCI-DSS (payment cards), SOX (financial), GDPR (EU personal data), ISO 27001, SOC 2.\n\nRetention periods: typically 1–7 years depending on regulation.\n\nAudit trails demonstrate: who accessed what data and when, what changes were made to systems, evidence of compliance with documented procedures.\n\nSystem logs, access logs, and change logs all contribute to the audit trail.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.2 Change Management (8 cards) ─────────────────────────────────────────

  {
    id: 'fc-c2-4-2-01',
    topicId: 'topic-c2-4-2',
    front: 'What are the three types of changes in formal change management and when is each used?',
    back: 'Standard: pre-approved, routine, low-risk, well-documented. No individual CAB review. Example: monthly OS patching, password resets.\n\nNormal: requires full CAB review, risk assessment, and explicit approval. Example: server configuration changes, major software upgrades, network topology changes.\n\nEmergency: urgent, cannot wait for standard CAB cycle — active outage or critical zero-day patch. Expedited approval by available CAB members or IT management, followed by mandatory post-implementation review.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-02',
    topicId: 'topic-c2-4-2',
    front: 'What is the CAB (Change Advisory Board) and who typically comprises it?',
    back: 'CAB (Change Advisory Board): the group that reviews and approves significant changes before implementation.\n\nTypical members:\n- IT management\n- Representatives from affected business units\n- Security team\n- Operations / infrastructure leads\n- Application owners for systems being changed\n\nThe CAB challenges assumptions, identifies risks, and ensures alignment with business priorities. Meets regularly (often weekly). The eCAB (Emergency CAB) handles urgent changes that cannot wait.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-03',
    topicId: 'topic-c2-4-2',
    front: 'What must a rollback plan include and why must it be written BEFORE the change?',
    back: 'A rollback plan is the documented procedure for reversing a change if it fails.\n\nMust be:\n- Written before the change (no time to plan during an outage)\n- Specific and actionable — not "revert the change" but exact steps\n- Tested where possible in a non-production environment\n- Assigned to a specific responsible person\n- Time-boxed — define the trigger: "if service not restored by 02:00, initiate rollback"\n\nA change without a rollback plan should not be approved.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-04',
    topicId: 'topic-c2-4-2',
    front: 'What is an RFC (Request for Change) and what key fields must it contain?',
    back: 'RFC (Request for Change): the formal document that initiates the change management process.\n\nKey fields:\n- Change description (what will be changed)\n- Reason / justification (why)\n- Scope and impact (which systems and users)\n- Implementation plan (step-by-step)\n- Rollback plan (how to revert if it fails)\n- Risk assessment (what could go wrong, likelihood, impact)\n- Test plan (how it will be tested)\n- Requested change window (date, time, duration)\n- Requestor and approver',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-05',
    topicId: 'topic-c2-4-2',
    front: 'What is a change window, and what is a freeze period?',
    back: 'Change window: the pre-scheduled, approved time period during which changes can be made to production systems. Typically scheduled during lowest-activity periods — nights (10 PM–4 AM), Saturday nights for major changes. Minimizes user impact if something goes wrong.\n\nFreeze period: a declared moratorium on changes around critical business periods — fiscal year end, holiday shopping season, major product launches. Only emergency changes permitted during freeze periods.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-06',
    topicId: 'topic-c2-4-2',
    front: 'What is the correct sequence of steps in the change management workflow?',
    back: '1. RFC submission (document what, why, how, rollback plan, risk, test plan)\n2. Initial review (change manager screens for completeness)\n3. CAB review and approval\n4. Test in pre-production / staging environment\n5. Communicate to affected users and stakeholders\n6. Implementation during approved change window\n7. Post-implementation verification\n8. Documentation update (CMDB, diagrams, baselines)\n9. Post-implementation review (for significant changes)',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-07',
    topicId: 'topic-c2-4-2',
    front: 'What is ITIL and which change management concepts come from it?',
    back: 'ITIL (Information Technology Infrastructure Library): the most widely adopted framework for IT Service Management (ITSM). Provides structured practices covering service strategy, design, transition, operation, and continual improvement.\n\nITIL change management concepts on the A+ exam:\n- RFC (Request for Change)\n- CAB (Change Advisory Board)\n- Change types: standard, normal, emergency\n- CMDB (Configuration Management Database)\n- Post-implementation review\n- Incident management (ticketing)\n- SLA (Service Level Agreement)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-2-08',
    topicId: 'topic-c2-4-2',
    front: 'What is the purpose of a post-implementation review after a significant change?',
    back: 'Post-implementation review (PIR): a structured review held after a significant change to evaluate what happened and capture lessons learned.\n\nKey questions:\n- Did the change achieve its goal?\n- Were there unexpected effects?\n- Was the rollback plan used? If so, why?\n- Were time estimates accurate?\n- What would be done differently next time?\n\nLessons learned feed back into the knowledge base and improve future RFC templates and risk assessments.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.3 Backup & Recovery (8 cards) ─────────────────────────────────────────

  {
    id: 'fc-c2-4-3-01',
    topicId: 'topic-c2-4-3',
    front: 'Compare all four backup types: Full, Incremental, Differential, and Synthetic Full.',
    back: 'Full: backs up all data. Clears archive bit. Slowest backup, simplest restore (one set).\n\nIncremental: backs up changes since LAST backup (any type). Clears archive bit. Fastest backup, most complex restore (full + every incremental in order).\n\nDifferential: backs up all changes since LAST FULL. Does NOT clear archive bit (grows over week). Medium speed, medium restore (full + most recent differential only).\n\nSynthetic Full: constructs a full backup from previous full + incrementals without re-reading source. Simple restore like a full backup.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-02',
    topicId: 'topic-c2-4-3',
    front: 'What is the 3-2-1 backup rule? Give a practical example.',
    back: '3-2-1 rule: keep 3 copies of data, on 2 different media types, with 1 copy offsite.\n\nPractical example:\n- Copy 1: original data on the workstation (primary storage)\n- Copy 2: local NAS backup (different media type — network storage)\n- Copy 3: cloud backup via Backblaze or Azure Blob (offsite)\n\nProtects against: local drive failure, local media-specific failure (e.g., NAS RAID failure), and site-level disasters (fire, flood, ransomware affecting local systems).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-03',
    topicId: 'topic-c2-4-3',
    front: 'What is the difference between RPO and RTO?',
    back: 'RPO (Recovery Point Objective): maximum acceptable data loss, measured in time. "We can lose up to 4 hours of data" → backups must run at least every 4 hours. Shorter RPO = more frequent backups, more storage.\n\nRTO (Recovery Time Objective): maximum acceptable time to restore service after an incident. "We must be back online within 2 hours" → the entire restore process must complete in 2 hours. Shorter RTO = faster restore technology needed (local disk > cloud; disk > tape).\n\nRPO drives backup frequency. RTO drives restore speed requirements.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-04',
    topicId: 'topic-c2-4-3',
    front: 'What does System Restore do, and what does it NOT do?',
    back: 'System Restore DOES:\n- Roll back Windows system files, installed drivers, and registry settings\n- Restore to a saved restore point (created before Windows Updates, driver installs, or manually)\n- Available via System Properties → System Protection, or via WinRE\n\nSystem Restore does NOT:\n- Back up or restore personal files (documents, photos, email)\n- Replace full backup\n- Help if the drive physically fails\n\nUse case: driver or application install causes instability. Fast fix, preserves user data.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-05',
    topicId: 'topic-c2-4-3',
    front: 'What Windows tools are available for backup and recovery, and what does each do?',
    back: 'File History: continuously backs up user folders (Documents, Desktop, Pictures) to external drive or network share. Keeps version history. User files only — no OS.\n\nWindows Backup (Win 11): integrates with OneDrive to back up folders, settings, credentials, and apps.\n\nBackup and Restore (Windows 7): still in Windows 10/11 via Control Panel. Schedules file backups and creates system images.\n\nSystem Image: sector-by-sector snapshot of entire drive (OS + apps + data). Enables bare-metal restore.\n\nSystem Restore: restore points for OS/drivers/registry only. Not a full backup.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-06',
    topicId: 'topic-c2-4-3',
    front: 'What is WinRE (Windows Recovery Environment) and how is it accessed?',
    back: 'WinRE provides recovery tools when Windows cannot boot normally.\n\nTools available:\n- Startup Repair: auto-fixes common boot problems\n- System Restore: roll back to a restore point\n- System Image Recovery: restore from a system image\n- Reset this PC: reinstall Windows (keep files or remove everything)\n- Command Prompt: manual repair (bootrec, diskpart, sfc)\n- Uninstall Updates: remove recent quality or feature updates\n\nAccess methods:\n- Settings → System → Recovery → Advanced startup\n- Interrupt boot 3 times (auto-triggers WinRE)\n- Boot from Windows installation media → Repair your computer',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-07',
    topicId: 'topic-c2-4-3',
    front: 'Explain the GFS (Grandfather-Father-Son) backup rotation scheme.',
    back: 'GFS rotation balances storage cost with recovery flexibility:\n\nSon (daily): backup every day — typically incremental or differential. Retained through the current week.\n\nFather (weekly): full backup once per week. Retained through the current month.\n\nGrandfather (monthly): one full backup per month. Retained for a year or longer.\n\nResult: can restore to any day this week, any week this month, any month in the past year — without storing a full backup for every single day.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-3-08',
    topicId: 'topic-c2-4-3',
    front: 'Why must backup restores be tested regularly, and what does a backup verification procedure involve?',
    back: 'A backup that has never been tested is not a backup — it is an assumption. Backup media fails, software corrupts archives, and configuration errors silently exclude critical files.\n\nVerification procedure:\n1. Review backup job logs for errors or skipped files\n2. Browse the backup catalog to confirm expected files are present\n3. Restore a sample of files to a test location and verify content\n4. Periodically do a full system restore to a test VM (at least quarterly)\n5. Document results: date, what was tested, who performed it, outcome\n6. Remediate any failures immediately — a failed verification is urgent',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.4 Safety Procedures (8 cards) ─────────────────────────────────────────

  {
    id: 'fc-c2-4-4-01',
    topicId: 'topic-c2-4-4',
    front: 'What is ESD and why is it dangerous even when you cannot feel it?',
    back: 'ESD (Electrostatic Discharge): occurs when two objects at different electrical potentials touch and charge equalizes between them.\n\nHumans feel static discharge at ~3,000 volts. Electronic components can be damaged at as little as 30 volts — well below human perception.\n\nLatent damage: ESD may not cause immediate failure. It degrades components over time, causing intermittent errors that are extremely difficult to diagnose.\n\nThis means you can destroy a CPU or RAM stick without any sensation whatsoever.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-02',
    topicId: 'topic-c2-4-4',
    front: 'What ESD prevention tools are used and how does each work?',
    back: 'Antistatic wrist strap: worn on wrist, clipped to unpainted metal chassis (or mat ground point). Continuously equalizes charge. Contains a 1 MΩ safety resistor. Must make metal-to-skin contact.\n\nAntistatic (ESD) mat: placed on workbench under the PC. Connected to ground. Dissipates static from components placed on it. Wrist strap clips to mat\'s ground point.\n\nAntistatic bags: metallic shielding creates a Faraday cage. Store/transport components in these until installation. Do NOT use regular plastic bags — they generate charge.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-03',
    topicId: 'topic-c2-4-4',
    front: 'What are the fire extinguisher classes and which is correct for IT equipment?',
    back: 'Class A: ordinary combustibles (wood, paper, fabric) — water, dry chemical\nClass B: flammable liquids (gasoline, oil, solvents) — CO2, dry chemical, foam\nClass C: electrical fires (energized equipment) — CO2, dry chemical (NON-CONDUCTIVE)\nClass D: combustible metals (magnesium, lithium) — dry powder (specialized)\nClass K: cooking oils and fats — wet chemical\n\nFor IT: Class C. Never use water on electrical fires — water conducts electricity.\nCO2 preferred in IT: leaves no residue that damages electronics.\nABC dry chemical: versatile but leaves corrosive powder.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-04',
    topicId: 'topic-c2-4-4',
    front: 'What electrical safety hazards exist in IT equipment, and why are CRT monitors especially dangerous?',
    back: 'CRT monitors: flyback transformer and capacitors hold 25,000 volts or more for hours or days after being powered off and unplugged. NEVER open a CRT without specialized training.\n\nOther hazards:\n- PSU line voltage input: 120V AC (US) / 240V AC — dangerous\n- PSU capacitors: hold charge after unplugging — wait 30+ seconds before servicing\n- Laser printer corona wire assembly: high voltage\n- UPS units: contain large batteries with significant current\n- GFCI outlets required near water — cuts power in milliseconds if leakage detected',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-05',
    topicId: 'topic-c2-4-4',
    front: 'What are the correct manual lifting techniques for heavy IT equipment?',
    back: 'Correct technique:\n- Assess the load first — test weight before committing\n- Get close to the load — distance increases spinal strain\n- Bend knees, not back — squat using leg muscles\n- Keep back straight — maintain natural spinal curve\n- Lift with legs — straighten knees while back stays straight\n- No twisting — turn whole body to change direction\n- 50 lbs limit — anything above requires a second person\n- Use equipment — wheeled carts and server sliding rails minimize manual lifting',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-06',
    topicId: 'topic-c2-4-4',
    front: 'What is an SDS (Safety Data Sheet) and what information does it contain?',
    back: 'SDS (Safety Data Sheet): formerly called MSDS. Standardized documentation required for every chemical substance. Must be accessible to all employees who may work with or near those chemicals.\n\nContains 16 standardized sections including:\n- Chemical identification and composition\n- Hazard identification\n- First-aid measures\n- Firefighting measures\n- Handling and storage guidelines\n- Exposure controls and required PPE\n- Disposal information\n\nCommon IT chemicals: toner (respiratory hazard), isopropyl alcohol (flammable), batteries (toxic).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-07',
    topicId: 'topic-c2-4-4',
    front: 'Match each IT task to the correct PPE: toner handling, cutting cables, server room work, electronic component handling.',
    back: 'Toner handling: N95 respirator mask + nitrile gloves (respiratory hazard + skin irritant)\n\nCutting cables: safety glasses / goggles (flying cable fragments)\n\nServer room (loud): ear protection (sustained noise above 85 dB causes hearing damage; server rooms often exceed this)\n\nElectronic component handling: ESD wrist strap (prevents electrostatic discharge damage)\n\nBattery handling (Li-ion, lead-acid): nitrile gloves (toxic materials, corrosive electrolyte)\n\nMultiple PPE items may apply simultaneously in a single task.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-4-08',
    topicId: 'topic-c2-4-4',
    front: 'What is thermal runaway in lithium batteries and why is it a fire safety concern?',
    back: 'Thermal runaway: a self-sustaining exothermic reaction in a lithium battery once it begins — heat causes the reaction, which produces more heat, accelerating uncontrollably.\n\nHazards:\n- The fire is very difficult to extinguish\n- Produces toxic fumes (hydrogen fluoride)\n- Can reignite hours after appearing extinguished\n- Triggered by: physical puncture, overcharging, manufacturing defects, or physical damage\n\nA swollen or punctured lithium battery should be treated as a fire hazard and handled with nitrile gloves. Dispose via retail drop-off or manufacturer take-back — never in regular trash.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.5 Environmental Controls (8 cards) ────────────────────────────────────

  {
    id: 'fc-c2-4-5-01',
    topicId: 'topic-c2-4-5',
    front: 'What are the recommended temperature and humidity ranges for a server room and why?',
    back: 'Temperature: 64–80°F (18–27°C) — ASHRAE A1 class for servers.\n\nRelative Humidity: 40–60% RH (ASHRAE recommends 45–55%).\n\nToo hot: CPU throttling, capacitor degradation, solder joint fatigue, HDD platter expansion.\nToo cold: condensation on circuit boards (water = shorts); increased ESD risk.\nToo humid (>60%): condensation, corrosion on metal contacts.\nToo dry (<40%): dramatic increase in electrostatic buildup — ESD risk spikes.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-02',
    topicId: 'topic-c2-4-5',
    front: 'Explain hot aisle / cold aisle configuration in a data center.',
    back: 'Hot aisle / cold aisle: standard rack layout that prevents hot exhaust air from mixing with cold supply air.\n\nHow it works:\n- Server rack fronts face each other → this is the COLD AISLE (cold air supplied here from floor vents or overhead; servers draw intake air from cold aisle)\n- Server rack rears face each other → this is the HOT AISLE (servers exhaust hot air here; returned to HVAC for cooling)\n\nHot aisle containment (curtains or doors) isolates exhaust air and forces it back to the HVAC return, preventing hot/cold air mixing.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-03',
    topicId: 'topic-c2-4-5',
    front: 'Compare a surge protector, UPS, and line conditioner. What does each protect against?',
    back: 'Surge protector: protects against brief voltage spikes via MOVs (Metal Oxide Varistors). No battery, no conditioning. Joule rating = absorption capacity. Replace after major surge.\n\nUPS (Uninterruptible Power Supply): battery backup during outage (minutes, not hours). Also suppresses surges. Sized by watts. Enables graceful shutdown or bridges gap until generator starts.\n\nLine conditioner: filters electrical noise and voltage fluctuations (brownouts, dirty power). Does NOT provide battery backup.\n\nPower strip: extends outlet count only. No surge protection, no battery, no conditioning. Never use for servers.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-04',
    topicId: 'topic-c2-4-5',
    front: 'Compare the three UPS types: Standby, Line-Interactive, and Online/Double-Conversion.',
    back: 'Standby (Offline): battery is idle; switches to battery on failure. 4–8ms transfer time. Inexpensive. May produce stepped approximation (modified sine wave) — issues with active PFC power supplies.\n\nLine-Interactive: autotransformer regulates voltage; battery activates on full failure. Better than standby for brownouts. Still has brief switchover. Common for workstations.\n\nOnline/Double-Conversion: power always flows through battery/inverter. Zero transfer time. True sine wave. Best power quality. Protects against all power issues. Most expensive, generates more heat. Best for servers and sensitive equipment.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-05',
    topicId: 'topic-c2-4-5',
    front: 'What toxic materials are found in common electronic components and why does this make disposal regulated?',
    back: 'Common toxic materials in e-waste:\n- Lead: CRT displays (several pounds per unit), solder joints, batteries\n- Mercury: fluorescent backlights in older LCDs, switches\n- Cadmium: nickel-cadmium (NiCd) batteries\n- Beryllium: some chips and connectors\n- Hexavalent chromium: some hardware coatings\n\nRegulation: WEEE (EU) requires manufacturer take-back. EPA (US) regulates under RCRA. Most US states have mandatory e-waste recycling laws. Throwing regulated e-waste in regular trash is illegal and environmentally harmful.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-06',
    topicId: 'topic-c2-4-5',
    front: 'What is the WEEE Directive and what does it require?',
    back: 'WEEE (Waste Electrical and Electronic Equipment) Directive: EU regulation governing end-of-life disposal of electronic equipment.\n\nRequirements:\n- Manufacturers must take back and recycle their products at end of life\n- Retailers must accept old equipment when selling new equivalents (e.g., take back old TV when selling new one)\n\nUS equivalent: EPA regulations under RCRA (Resource Conservation and Recovery Act) for certain items (lead-acid batteries, CRTs). Many US states also have mandatory e-waste recycling laws with significant penalties for businesses.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-07',
    topicId: 'topic-c2-4-5',
    front: 'What is the purpose of blanking panels in server racks?',
    back: 'Blanking panels fill unused rack unit (1U, 2U) slots in server racks.\n\nPurpose: prevent hot exhaust air from the rear of the rack from recirculating to the front intake through the empty gaps.\n\nWithout blanking panels: hot air short-circuits from the hot aisle back to the cold aisle through empty slots, warming the intake air and reducing cooling efficiency. This creates localized hot spots even in otherwise well-cooled rooms.\n\nBest practice: fill ALL unused rack slots with blanking panels. Simple, inexpensive, significant impact.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-5-08',
    topicId: 'topic-c2-4-5',
    front: 'How does a generator work with a UPS for data center power backup?',
    back: 'Generator: provides long-term backup power (hours to days) when utility power fails. Diesel or propane. Takes 10–30 seconds to start and reach stable output.\n\nUPS bridges the gap: the UPS battery provides instant power during the 10–30 seconds it takes the generator to start and stabilize. Together they provide seamless coverage.\n\nTransfer switch: required to safely disconnect the facility from utility power before the generator comes online. ATS (Auto-Transfer Switch) does this automatically in seconds.\n\nRequirement: UPS must be sized to support the full load for the generator startup time.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.6 Policies & Licensing (8 cards) ──────────────────────────────────────

  {
    id: 'fc-c2-4-6-01',
    topicId: 'topic-c2-4-6',
    front: 'What is an AUP (Acceptable Use Policy) and what does it typically cover?',
    back: 'AUP (Acceptable Use Policy): defines what employees may and may not do with organizational technology, networks, and internet access.\n\nKey points:\n- Users sign AUP before receiving network access (part of onboarding)\n- Violations grounds for discipline up to termination\n- Gives organization legal basis to monitor network activity\n\nTypically covers:\n- Personal use of work equipment\n- Prohibited websites and social media\n- Email use\n- Removable media policies\n- Software installation restrictions\n- Prohibition on sharing login credentials',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-02',
    topicId: 'topic-c2-4-6',
    front: 'What is BYOD and what are the key security implications of enrolling a personal device in MDM?',
    back: 'BYOD (Bring Your Own Device): policy governing use of personally-owned devices to access corporate resources.\n\nKey security implications of MDM enrollment:\n- MDM can enforce encryption, passcode requirements, and remote wipe on the personal device\n- Remote wipe may erase personal photos, apps, and data alongside corporate data — employees must understand this risk before enrolling\n- Data containerization (e.g., Intune) keeps corporate data isolated in a "work container"\n- IT supports corporate apps only, not the personal OS or hardware\n- Organization specifies minimum OS versions for security patch coverage',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-03',
    topicId: 'topic-c2-4-6',
    front: 'What is DLP (Data Loss Prevention) and what types of controls does it use?',
    back: 'DLP (Data Loss Prevention): policies and technical tools that prevent sensitive data from leaving the organization without authorization.\n\nDLP control types:\n- Email scanning: block outbound emails containing SSNs, credit card numbers, proprietary keywords\n- Endpoint DLP / USB blocking: prevent copying sensitive files to USB drives via Group Policy or endpoint agents\n- Print controls: log or restrict printing of sensitive documents\n- Cloud upload monitoring: block uploads to personal cloud storage from managed devices\n- Network DLP: deep packet inspection at the perimeter to detect data exfiltration\n\nRequires data classification rules to identify what "sensitive" looks like.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-04',
    topicId: 'topic-c2-4-6',
    front: 'What is PII and what are examples of it?',
    back: 'PII (Personally Identifiable Information): any data that can identify a specific individual, alone or in combination with other data.\n\nExamples:\n- Full name, address, phone number, email address\n- Social Security Number (SSN), passport number, driver\'s license number\n- Date of birth, place of birth\n- Biometric data (fingerprints, facial recognition data, retinal scans)\n- IP addresses and device identifiers (context-dependent)\n- Financial account numbers, medical record numbers\n\nPII is protected by HIPAA (health), FERPA (education), GDPR (EU), CCPA (California), and other regulations.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-05',
    topicId: 'topic-c2-4-6',
    front: 'Compare the software license types: OEM, Retail (FPP), Volume, Subscription, Open Source, Freeware, Shareware.',
    back: 'OEM: bundled with hardware, tied to that specific machine, NOT transferable.\nRetail/FPP: purchased standalone, CAN be transferred to new hardware.\nVolume/Enterprise: single key or server activates multiple machines; per-seat or site license.\nSubscription: access for duration of payment (monthly/annual), tied to account.\nOpen Source: source code available; governed by open source license terms; usually free.\nFreeware: free to use, source code not available.\nShareware: limited trial version (features or time); paid for full version.\n\nKey exam fact: OEM licenses are hardware-bound and cannot be transferred.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-06',
    topicId: 'topic-c2-4-6',
    front: 'What is the difference between KMS and MAK for Windows volume license activation?',
    back: 'KMS (Key Management Service): on-premises activation server within the organization. Managed devices check in with KMS every 180 days to renew activation. Works without internet access to Microsoft. Ideal for large enterprise environments with many machines.\n\nMAK (Multiple Activation Key): a single product key that activates a specific number of machines against Microsoft\'s servers. Once the activation count is exhausted, no more activations without purchasing additional licenses. Suitable for smaller deployments or internet-connected environments.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-07',
    topicId: 'topic-c2-4-6',
    front: 'What are the key open source license types and how do they differ?',
    back: 'MIT: very permissive. Can use, modify, redistribute, include in proprietary software. Must retain copyright notice.\n\nApache 2.0: permissive, similar to MIT. Also includes a patent grant protecting users from patent claims by contributors.\n\nGNU GPL (v2/v3): copyleft. Derivatives must also be GPL — CANNOT be included in proprietary software. "Viral" license.\n\nGNU LGPL: weak copyleft. Can link from proprietary software without triggering full GPL obligation. Designed for libraries.\n\nKey distinction: MIT/Apache = can use in proprietary software. GPL = derivatives must remain open source.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-6-08',
    topicId: 'topic-c2-4-6',
    front: 'What privacy regulations apply to these data types: health records, student records, payment cards, EU personal data?',
    back: 'Health records (PHI): HIPAA — applies to US healthcare providers, insurers, and their business associates.\n\nStudent education records: FERPA — applies to educational institutions receiving federal funding (US).\n\nPayment card data: PCI DSS — applies globally to any entity that handles credit/debit card data.\n\nEU personal data broadly: GDPR (General Data Protection Regulation) — applies to any organization handling data of EU residents, regardless of where the organization is based.\n\nCalifornia residents (broad): CCPA — applies to businesses meeting certain revenue or data thresholds.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.7 Professionalism (8 cards) ───────────────────────────────────────────

  {
    id: 'fc-c2-4-7-01',
    topicId: 'topic-c2-4-7',
    front: 'What is active listening and how does it differ from passive listening?',
    back: 'Active listening: fully concentrating on what the user is saying, not formulating your response while they talk.\n\nActive listening behaviors:\n- Give full attention; let them finish without interrupting\n- Maintain appropriate eye contact\n- Take notes during the conversation\n- Paraphrase to confirm understanding: "So if I understand correctly..."\n- Ask clarifying questions\n\nPassive listening (avoid): hearing without processing, forming answers while they talk, interrupting to show you already know, assuming you understand before they finish.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-02',
    topicId: 'topic-c2-4-7',
    front: 'What are the best practices for setting and managing user expectations during a support interaction?',
    back: 'Key practices:\n- Provide a timeline: "I\'ll have a diagnosis within the hour"\n- Update proactively if the timeline changes — do NOT wait for the user to follow up\n- Know your limits: if beyond your scope, say so and explain who will handle it and when\n- Follow up after resolution: brief email or callback confirms satisfaction and catches lingering issues\n- When uncertain: "I don\'t know yet, but I\'ll update you by end of day" is better than silence\n\nUncertainty causes the most user frustration — not the problem itself.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-03',
    topicId: 'topic-c2-4-7',
    front: 'What is the correct process for handling a difficult or angry customer?',
    back: '1. Allow them to vent — do not interrupt; let them feel heard\n2. Acknowledge and empathize — "I understand this has been really disruptive" — without admitting fault or arguing\n3. Clarify the problem — once emotional intensity drops, transition to problem-solving\n4. Focus on solutions — keep conversation forward-looking; do not relitigate the past\n5. Set a clear expectation — specific next step and timeline\n6. Follow up — after resolution, confirm satisfaction\n\nDo NOT: match their anger, take it personally, make promises you cannot keep, involve other users.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-04',
    topicId: 'topic-c2-4-7',
    front: 'What professional behavior is expected regarding personal interruptions during a support interaction?',
    back: 'Personal calls, texts, and interruptions must not occur during a support interaction with a user.\n\nRequired:\n- Silence your phone before beginning any user-facing work\n- Let personal calls go to voicemail\n- Do not respond to text messages\n- If an urgent call must be taken: apologize to the user, step away briefly, return promptly\n\nRationale: the user in front of you deserves your full attention. Personal interruptions signal that their issue is not a priority and are unprofessional.\n\nThis is a direct CompTIA A+ exam topic.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-05',
    topicId: 'topic-c2-4-7',
    front: 'What are the technician\'s confidentiality obligations during a support interaction?',
    back: 'Technicians routinely access sensitive information. Confidentiality obligations:\n\n- Do not discuss one user\'s issues with other users or in common areas\n- Do not read personal files, emails, or documents beyond what is needed to solve the problem\n- If sensitive information is inadvertently seen: do not mention it, share it, or use it\n- Do not take screenshots or photos of user content without explicit authorization\n- Follow organizational privacy policies regarding what may be accessed\n\nConfidentiality is both an ethical obligation and often a legal one (HIPAA, GDPR, etc.).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-06',
    topicId: 'topic-c2-4-7',
    front: 'When should a technician escalate an issue, and how should escalation be handled?',
    back: 'Escalate when:\n- Problem is beyond your technical skill level\n- Fix requires permissions or access you don\'t have\n- Company policy requires a different team (security incidents, HR matters)\n- Legal or compliance issue is involved\n- Time constraints require faster resolution\n\nHow to escalate properly:\n1. Document everything already tried (steps, results)\n2. Contact the next-tier technician BEFORE handing off\n3. Brief them: user, issue, steps tried, findings\n4. Inform the user who will handle it and when\n5. Never leave the user without knowing what happens next\n\nEscalation is a professional skill, not a failure.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-07',
    topicId: 'topic-c2-4-7',
    front: 'What are the best practices for ending a support interaction?',
    back: '1. Verify resolution — ask the user: "Is everything working the way it should now?" Do NOT assume it is fixed.\n2. Explain what was done — in plain language: what was wrong and what was done to fix it. Builds trust.\n3. Provide preventive education — if caused by user behavior (phishing link, unknown USB), explain gently what to do differently.\n4. Close the ticket completely — document resolution, root cause, and steps taken for future reference.\n5. Follow up — brief email or callback the next day builds goodwill and catches any recurrence before it becomes a new incident.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-7-08',
    topicId: 'topic-c2-4-7',
    front: 'What plain-language translations should technicians use for common technical terms when speaking with end users?',
    back: '"Your DIMM is failing" → "Your computer\'s memory is going bad and needs to be replaced"\n\n"DNS resolution failure" → "Your computer can\'t find the websites you\'re trying to visit — it\'s a network setting issue"\n\n"BIOS needs updating" → "There\'s a low-level software update for your computer\'s firmware"\n\n"HDD has bad sectors" → "Part of your hard drive is damaged and could fail soon — we need to back up your data"\n\nGeneral rule: when speaking with non-technical users, translate jargon into plain language that describes the user impact.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.8 Scripting (8 cards) ─────────────────────────────────────────────────

  {
    id: 'fc-c2-4-8-01',
    topicId: 'topic-c2-4-8',
    front: 'Compare the major scripting languages used in IT: PowerShell, Python, Bash, VBScript, JavaScript.',
    back: 'PowerShell (.ps1): Windows-native (also cross-platform via PS 7). Active Directory, Windows admin, Microsoft 365. Verb-Noun cmdlets, object pipeline.\n\nPython (.py): cross-platform. Network automation, log parsing, REST API interaction, data processing. Most versatile.\n\nBash (.sh): Linux/macOS native. Linux system admin, cron jobs, server automation. Strings CLI tools together.\n\nVBScript (.vbs): Windows legacy. Old login scripts. Replaced by PowerShell. Not used for new work.\n\nJavaScript (.js): web + Node.js for server-side automation. Increasingly common in DevOps.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-02',
    topicId: 'topic-c2-4-8',
    front: 'What is the PowerShell execution policy and what are its settings?',
    back: 'Execution policy: controls whether PowerShell scripts can run on a system.\n\nSettings:\n- Restricted: no scripts can run (default on new installations)\n- AllSigned: only scripts signed by a trusted publisher can run\n- RemoteSigned: local scripts run unsigned; downloaded scripts must be signed\n- Unrestricted: all scripts run; warns about downloaded scripts\n\nCheck current policy: Get-ExecutionPolicy\nChange policy: Set-ExecutionPolicy RemoteSigned (requires admin)\n\nThis is a safety mechanism — not a security boundary (can be bypassed by a local admin).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-03',
    topicId: 'topic-c2-4-8',
    front: 'What are the universal scripting concepts that apply across all scripting languages?',
    back: 'Variables: store a value and refer to it by name. ($username = "jsmith" in PS; username = "jsmith" in Python; USERNAME="jsmith" in Bash)\n\nConditionals (if/else/elif): execute different code paths based on a condition.\n\nLoops (for/while/foreach): repeat an action for each item in a collection or while a condition is true.\n\nFunctions: reusable named blocks of code — define once, call multiple times.\n\nComments: notes in code that are not executed. Explain the "why." Critical for maintainability.\n\nError handling (try/catch): prevent scripts from failing silently.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-04',
    topicId: 'topic-c2-4-8',
    front: 'What are the best IT scripting use cases for PowerShell vs Python vs Bash?',
    back: 'PowerShell best for:\n- Creating AD user accounts from a CSV\n- Automating patch deployment across Windows fleet\n- Managing Group Policy settings remotely\n- Windows service and event log management\n\nPython best for:\n- Pulling device inventory from network gear via REST API\n- Parsing large log files for error patterns\n- Automating SSH connections to multiple network switches (Paramiko/Netmiko)\n- Cross-platform data processing and reporting\n\nBash best for:\n- Nightly backup of config files on Linux servers\n- Scheduling jobs with cron\n- Linux system administration and file operations',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-05',
    topicId: 'topic-c2-4-8',
    front: 'What is a shebang line and why is it used in Bash scripts?',
    back: 'Shebang line: the first line of a script beginning with #! that tells the OS which interpreter to use.\n\nExample: #!/bin/bash\nThis tells the system to run the script with the Bash interpreter at /bin/bash, even if the user\'s default shell is different (zsh, sh, etc.).\n\nWithout the shebang: the OS may use the wrong interpreter, causing the script to fail or behave unpredictably.\n\nOther examples:\n#!/usr/bin/env python3 (for Python scripts)\n#!/bin/sh (for POSIX-compatible sh scripts)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-06',
    topicId: 'topic-c2-4-8',
    front: 'What are the key benefits of scripting over manual processes in IT?',
    back: 'Consistency: every execution follows the same steps — no missed steps, no typos in usernames.\n\nSpeed: a script creating 200 user accounts takes seconds; manually takes hours.\n\nScheduling: scripts run unattended at 2AM when users are not impacted.\n\nDocumentation: a well-written script is self-documenting — shows exactly what was done and in what order.\n\nRepeatability: run the same deployment script on 500 machines with identical results.\n\nError reduction: removes human error from repetitive tasks.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-07',
    topicId: 'topic-c2-4-8',
    front: 'What is pip in Python and what is a virtual environment?',
    back: 'pip: Python\'s package manager. Installs third-party libraries from PyPI (Python Package Index).\n- pip install requests → installs the requests HTTP library\n- pip list → shows all installed packages\n- pip install paramiko netmiko → installs SSH automation libraries\n\nVirtual environment: isolates project dependencies in a separate environment.\n- python -m venv myenv → creates a virtual environment\n- Prevents version conflicts between projects (Project A needs requests 2.x, Project B needs 3.x)\n- Best practice for any Python project',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-8-08',
    topicId: 'topic-c2-4-8',
    front: 'What PowerShell cmdlets are most important for IT administration tasks?',
    back: 'Get-Help: display help for any cmdlet\nGet-Process: list running processes\nGet-Service: list Windows services and status\nStart-Service / Stop-Service: start or stop a service\nGet-EventLog: read Windows event log entries\nGet-ADUser: query Active Directory user accounts\nNew-ADUser: create an AD user\nNew-LocalUser: create a local user account\nInvoke-Command: run commands on remote computers\nWhere-Object: filter objects by property\nForEach-Object: iterate through a collection\nGet-PSDrive: check disk space\n\nCmdlets follow Verb-Noun format: Get-X, Set-X, New-X, Remove-X, Start-X, Stop-X',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.9 Remote Access (8 cards) ─────────────────────────────────────────────

  {
    id: 'fc-c2-4-9-01',
    topicId: 'topic-c2-4-9',
    front: 'Compare RDP and VNC remote desktop protocols.',
    back: 'RDP (Remote Desktop Protocol):\n- Port: TCP 3389\n- Developed by Microsoft, proprietary\n- Full GUI desktop access to remote Windows machine\n- Requires Windows Pro/Enterprise/Server on host (not Home)\n- Built-in TLS encryption\n- Client: mstsc.exe (Remote Desktop Connection)\n- Best: Windows-to-Windows, highest performance\n\nVNC (Virtual Network Computing):\n- Port: TCP 5900\n- Cross-platform (Windows, macOS, Linux)\n- Uses RFB protocol, transfers raw pixels (less efficient)\n- No built-in encryption — must tunnel over SSH for security\n- Best: cross-platform access when platform-agnostic needed',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-02',
    topicId: 'topic-c2-4-9',
    front: 'What are the key properties of SSH and when is it used?',
    back: 'SSH (Secure Shell):\n- Port: TCP 22\n- Provides encrypted terminal (command-line) access\n- Standard for Linux/Unix server management and network device configuration\n- Authentication: password or public/private key pair (keys preferred)\n- Key-based auth: ssh-keygen → private key on client, public key on server\n- File transfer: SFTP and SCP both run over SSH on port 22\n- Port forwarding: can tunnel other protocols securely over SSH\n\nTools:\n- Linux/macOS: built-in terminal\n- Windows: built-in OpenSSH (Win 10+) or PuTTY (.ppk key format)',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-03',
    topicId: 'topic-c2-4-9',
    front: 'What remote access protocols and their ports should be memorized for the A+ exam?',
    back: 'RDP — TCP 3389 (Remote Desktop Protocol, Windows GUI)\nVNC — TCP 5900 (Virtual Network Computing, cross-platform GUI)\nSSH — TCP 22 (Secure Shell, encrypted terminal)\nRD Gateway — TCP 443 (HTTPS) — proxies RDP over HTTPS\nSSL VPN — TCP 443\nIPSec / IKE — UDP 500 and 4500\nWireGuard VPN — UDP 51820\nSFTP / SCP — TCP 22 (runs over SSH)\n\nMemory tip: RDP=3389, VNC=5900, SSH=22. RDP and SSL VPN both use 443 when going through a gateway.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-04',
    topicId: 'topic-c2-4-9',
    front: 'What security measures should be applied to RDP to prevent unauthorized access?',
    back: '1. Never expose port 3389 directly to the internet — primary ransomware attack vector\n\n2. Require VPN first: users connect via VPN, then RDP to internal IP. Internet only sees VPN traffic.\n\n3. RD Gateway: Microsoft server role that proxies RDP over HTTPS (port 443). Internal RDP port never exposed publicly.\n\n4. Network Level Authentication (NLA): requires authentication before a full RDP session is established. Reduces attack surface by rejecting unauthorized connections before resources are allocated.\n\n5. Add users to Remote Desktop Users group — do not allow everyone.\n\n6. Use strong passwords and account lockout policies.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-05',
    topicId: 'topic-c2-4-9',
    front: 'What is the difference between split tunnel and full tunnel VPN?',
    back: 'Split tunnel: only traffic destined for corporate networks goes through the VPN tunnel. Internet traffic goes directly to the internet.\n- Pros: better performance, less corporate bandwidth consumed\n- Cons: internet traffic bypasses corporate security tools (web filter, IDS/IPS)\n\nFull tunnel: ALL traffic — corporate AND internet — routes through the VPN.\n- Pros: corporate security tools inspect all traffic; more secure\n- Cons: higher bandwidth on corporate infrastructure; slower internet for users\n\nAlways-on VPN (enterprise): enforces VPN connection whenever the device is not on the corporate physical network.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-06',
    topicId: 'topic-c2-4-9',
    front: 'What is an RMM platform and what capabilities does it provide for MSPs?',
    back: 'RMM (Remote Monitoring and Management): enterprise platform for managing large fleets of endpoints.\n\nKey capabilities:\n- Real-time monitoring: CPU, memory, disk, service health with automated alerting\n- Patch management: deploy Windows updates and third-party patches across all managed devices\n- Remote script execution: run PowerShell or Bash scripts on hundreds of machines simultaneously\n- Remote access: integrated remote control for support\n- Asset inventory: hardware and software inventory across all managed endpoints\n- Backup management integration\n\nCommon platforms: ConnectWise Automate, NinjaRMM, Datto RMM, Kaseya VSA, SolarWinds N-central',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-07',
    topicId: 'topic-c2-4-9',
    front: 'What is Windows Quick Assist and how does it differ from TeamViewer?',
    back: 'Windows Quick Assist (built-in):\n- Built into Windows 10 and 11 (Start → Quick Assist)\n- Helper generates a 6-digit code; user enters the code\n- Works over HTTPS — no port configuration required\n- Remote view or full remote control\n- Session ends automatically when helper disconnects\n- Requires Microsoft account sign-in for the helper\n\nTeamViewer (third-party):\n- Cross-platform (Windows, macOS, Linux, iOS, Android)\n- Works through NAT/firewalls via outbound cloud relay\n- Session recording, file transfer, unattended access\n- Free for personal use; requires commercial license for business use',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-9-08',
    topicId: 'topic-c2-4-9',
    front: 'What is VDI and DaaS and what are the benefits of virtual desktops?',
    back: 'VDI (Virtual Desktop Infrastructure): virtual desktops run on servers in the data center or cloud. Endpoint devices (thin clients, laptops) just display the session — all processing on the server.\n\nDaaS (Desktop as a Service): cloud-hosted VDI. Pay per-user per-month. No on-premises VDI infrastructure needed.\n\nBenefits:\n- Centralized management — one place to patch and update\n- Data stays in data center, not on endpoints\n- Easy provisioning — new desktop in minutes\n- Consistent environment for all users\n- Supports thin clients (lower cost endpoints)\n\nExamples: Citrix, VMware Horizon, Azure Virtual Desktop, Amazon WorkSpaces',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.10 Artificial Intelligence (8 cards) ──────────────────────────────────

  {
    id: 'fc-c2-4-10-01',
    topicId: 'topic-c2-4-10',
    front: 'What is AI hallucination and why is it a critical concern in IT support?',
    back: 'AI hallucination: an LLM generates text that sounds correct and authoritative but is factually inaccurate or entirely fabricated. The model does not "know" it is wrong — it is optimized to produce plausible text, not verified facts.\n\nIT-specific risks:\n- Fabricated PowerShell commands that don\'t exist or do something different\n- AI-generated code with security vulnerabilities\n- Cited documentation or CVEs that do not exist\n- Incorrect remediation steps for your specific OS version\n\nMitigation: treat AI output as a starting point. Verify commands against official documentation. Test in non-production first.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-02',
    topicId: 'topic-c2-4-10',
    front: 'What are the three types of machine learning training and examples of each?',
    back: 'Supervised learning: model trained on labeled data (input + correct answer). Example: spam filter trained on emails labeled "spam" or "not spam." Output: a model that classifies new emails.\n\nUnsupervised learning: model finds patterns without labeled answers. Example: clustering similar support tickets without pre-defined categories.\n\nReinforcement learning: model learns by receiving rewards for correct actions, penalties for wrong ones. Example: AI learns to play chess by winning or losing games.\n\nOutput of all training: a model — a mathematical representation of the patterns found in training data.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-03',
    topicId: 'topic-c2-4-10',
    front: 'What are LLMs (Large Language Models) and what are examples relevant to IT?',
    back: 'LLMs (Large Language Models): a type of ML model trained on massive amounts of text data (hundreds of billions to trillions of words). Learn statistical patterns of language to understand prompts and generate responses.\n\nKey characteristics:\n- Defined by number of parameters (billions to trillions of learned weights)\n- Input: text prompt → Output: generated text\n- Can perform diverse tasks with no task-specific training: Q&A, writing, coding, summarizing\n\nExamples:\n- GPT-4 (ChatGPT) — OpenAI\n- Claude — Anthropic\n- Gemini — Google\n- Llama — Meta (open source)\n- Microsoft Copilot (built on GPT)',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-04',
    topicId: 'topic-c2-4-10',
    front: 'What are the responsible AI use guidelines for IT technicians?',
    back: 'Privacy:\n- Do NOT input PII, PHI, proprietary code, confidential data, or trade secrets into public AI tools\n- Review vendor data retention and training policies before use\n- Use enterprise tiers with contractual data protection (e.g., Microsoft Copilot for M365)\n- Sanitize/anonymize data before input\n\nAccuracy and verification:\n- Verify AI-generated commands against official documentation\n- Test AI scripts in non-production first\n- Do not implement security recommendations without qualified review\n\nBias: AI reflects training data biases. Human review required for decision-making tools.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-05',
    topicId: 'topic-c2-4-10',
    front: 'How is AI used in IT support workflows? List at least five applications.',
    back: '1. Tier-0 chatbots: handle password resets, account unlocks, FAQ answers, ticket creation — 24/7, no staffing cost\n\n2. Automated ticket management: ML classifies tickets by category, priority, and routes to the correct team\n\n3. Log analysis: scans millions of log entries, identifies anomalous patterns, surfaces root causes in seconds\n\n4. Predictive failure analysis: monitors SMART data and performance metrics to predict hardware failure before it occurs\n\n5. Security anomaly detection: baselines "normal" behavior and flags unusual logins, data transfers, or new outbound connections\n\n6. Code/script assistance: GitHub Copilot, Tabnine — generates PowerShell, Python, explains existing scripts',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-06',
    topicId: 'topic-c2-4-10',
    front: 'What is machine learning and how does it differ from traditional programming?',
    back: 'Machine learning (ML): a subset of AI where systems learn patterns from data without being explicitly programmed with rules.\n\nTraditional programming:\n- Human writes explicit rules: "if X then Y"\n- Predictable and deterministic\n- Fails on inputs not covered by the rules\n- Must be manually updated when conditions change\n\nMachine learning:\n- Trained on examples; develops internal pattern representation\n- Handles ambiguous or novel inputs\n- Improves with more training data\n- Less predictable — may behave unexpectedly\n- Better for: classification, prediction, natural language processing',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-07',
    topicId: 'topic-c2-4-10',
    front: 'How does AI-powered security anomaly detection work in an IT environment?',
    back: 'AI anomaly detection for security:\n\n1. Establish baseline: AI learns "normal" behavior — typical login times, normal data transfer volumes, known outbound IP connections, standard process behavior on endpoints\n\n2. Continuous monitoring: AI compares current activity against the baseline in real time\n\n3. Flagging deviations: unusual login time, unexpected large data transfer, new outbound connection to unknown IP, process spawning unusual child processes\n\n4. Automated response: can automatically quarantine a device, block a process, or isolate a network segment — faster than any human can respond\n\nAdvantage over signatures: catches zero-day and fileless malware that has no known signature.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-4-10-08',
    topicId: 'topic-c2-4-10',
    front: 'What is AI bias and what is its practical implication for IT decision-making tools?',
    back: 'AI bias: AI models reflect the data they were trained on. If training data contains historical, demographic, or geographic biases, the model will reproduce and potentially amplify those biases.\n\nPractical implications for IT:\n- Ticket prioritization: AI may systematically deprioritize tickets from certain departments or user groups based on biased historical patterns\n- Security risk scoring: may unfairly flag certain user behaviors based on biased training data\n- Hiring tool recommendations: well-documented cases of AI favoring or disfavoring candidates based on biased historical data\n\nMitigation: human review for AI-powered decision tools, regular auditing of AI outputs for disparate impact.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

]
