// CompTIA A+ 220-1202 Core 2 — Domain 1: Operating Systems
// Topics 1.7–1.11 | 40 flashcards (8 per topic)

const NOW = new Date().toISOString()

export const BATCH4_FLASHCARDS = [

  // ─── 1.7 Windows Networking (8 cards) ────────────────────────────────────

  {
    id: 'fc-c2-1-7-01',
    topicId: 'topic-c2-1-7',
    front: 'What does an APIPA address (169.254.x.x) indicate on a Windows PC?',
    back: 'APIPA (Automatic Private IP Addressing) means Windows could not reach a DHCP server and assigned itself a link-local address. The device cannot communicate beyond the local subnet. Causes: disconnected cable, switch port down, DHCP service stopped, or DHCP scope exhausted. Verify with ipconfig — if 169.254.x.x appears, fix the connectivity to the DHCP server.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-7-02',
    topicId: 'topic-c2-1-7',
    front: 'How do share permissions and NTFS permissions interact when accessing a shared folder over the network?',
    back: 'Both permission sets are evaluated independently. Windows enforces the MORE RESTRICTIVE of the two as the effective permission.\n\nExample: Share = Full Control, NTFS = Read → Effective = Read.\n\nNTFS permissions also apply to local access; share permissions only apply to network access. Always check both before troubleshooting access issues.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-7-03',
    topicId: 'topic-c2-1-7',
    front: 'Compare Workgroup vs Domain network models.',
    back: 'Workgroup:\n- Peer-to-peer, no central server required\n- Each PC manages its own accounts\n- Practical limit ~20 computers\n- No Group Policy, no SSO\n- Users need accounts on each PC they access\n\nDomain:\n- Centralized via Active Directory and Domain Controller\n- Single Sign-On across all domain resources\n- Scales to thousands of computers\n- Group Policy Objects (GPO) enforce settings centrally\n- Users log in with domain credentials anywhere on the network',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-7-04',
    topicId: 'topic-c2-1-7',
    front: 'What are Windows administrative shares and how are they accessed?',
    back: 'Windows automatically creates hidden administrative shares accessible only to Administrators:\n\n• C$ → root of C: drive\n• D$ → root of D: drive\n• ADMIN$ → Windows installation directory (C:\\Windows)\n• IPC$ → inter-process communication (not a file share)\n• PRINT$ → printer drivers\n\nAccess via \\\\computername\\C$ — the dollar sign hides them from normal browsing. Only Administrators group members can connect.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-7-05',
    topicId: 'topic-c2-1-7',
    front: 'Compare the four built-in Windows VPN protocols.',
    back: 'PPTP — Weak security, deprecated. Avoid on modern networks.\n\nL2TP/IPsec — Strong security; requires shared key or certificate; may be blocked by NAT firewalls.\n\nSSTP — Strong (SSL/TLS over port 443); most firewall-friendly because port 443 is rarely blocked.\n\nIKEv2 — Strong security; fast reconnection after network drops; ideal for mobile users. Requires Windows 10/11 Enterprise for Always-On VPN.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-7-06',
    topicId: 'topic-c2-1-7',
    front: 'What are the three Windows network profiles, and how do they differ?',
    back: 'Public — Network discovery and file sharing OFF. Most restrictive. Used for untrusted networks (coffee shops, airports). Windows Firewall is most restrictive.\n\nPrivate — Network discovery and file sharing ON. Used for home or trusted networks. Devices are visible to each other.\n\nDomain — Settings managed by Group Policy. Active when the domain-joined PC is on the corporate network. Firewall rules pushed by GPO.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-7-07',
    topicId: 'topic-c2-1-7',
    front: 'What is split tunneling in a VPN, and what is the trade-off?',
    back: 'Split tunneling ON: Only traffic destined for the corporate network goes through the VPN tunnel. Internet browsing uses the local ISP connection directly. Result: faster internet, less VPN load.\n\nSplit tunneling OFF (full tunnel): ALL traffic routes through the corporate VPN. Result: internet browsing is slower but IT can monitor/filter all traffic.\n\nEnterprise environments often disable split tunneling for security/compliance reasons.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-7-08',
    topicId: 'topic-c2-1-7',
    front: 'What is wf.msc, and how do you create an inbound firewall rule to allow a specific port?',
    back: 'wf.msc opens Windows Defender Firewall with Advanced Security (WFAS) — the full-featured firewall MMC snap-in.\n\nTo create an inbound rule for a port:\n1. Open wf.msc\n2. Inbound Rules > New Rule\n3. Select "Port" as rule type\n4. Choose TCP or UDP and enter the port number\n5. Select "Allow the connection"\n6. Choose applicable profiles (Domain / Private / Public)\n7. Name the rule and click Finish',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.8 macOS Features (8 cards) ────────────────────────────────────────

  {
    id: 'fc-c2-1-8-01',
    topicId: 'topic-c2-1-8',
    front: 'What is Spotlight, and what keyboard shortcut opens it?',
    back: 'Spotlight is macOS\'s system-wide search and quick-launch tool. Shortcut: Cmd+Space.\n\nCapabilities: launch apps, find files, search email/calendar, perform math calculations, convert units, show word definitions, search the web, find contacts.\n\nEquivalent to Windows Search (Win+S). On the exam: if asked how to quickly launch an app on macOS without the Dock, the answer is Spotlight (Cmd+Space).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-8-02',
    topicId: 'topic-c2-1-8',
    front: 'What is FileVault, and what is the Windows equivalent?',
    back: 'FileVault is macOS\'s full-disk encryption system — the equivalent of BitLocker on Windows.\n\n• Encrypts the entire startup disk using XTS-AES-128 encryption\n• Transparent to the user after unlocking with their login password\n• Enable: System Settings > Privacy & Security > FileVault\n\nRecovery options: 24-character recovery key (shown at setup) OR Apple ID (personal) OR MDM-escrowed key (enterprise). Without the password AND recovery key, data is permanently unrecoverable.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-8-03',
    topicId: 'topic-c2-1-8',
    front: 'What is Gatekeeper, and how can a user run an unsigned app on macOS?',
    back: 'Gatekeeper controls which applications can run based on source and code-signing status.\n\nSecurity levels (System Settings > Privacy & Security):\n• App Store only — most restrictive\n• App Store + identified developers — default; requires Apple Developer ID certificate\n• Anywhere — disabled by default in modern macOS\n\nTo run an unsigned app: right-click > Open, then confirm in the dialog. This bypasses Gatekeeper for that specific instance only.\n\nEquivalent to Windows SmartScreen.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-8-04',
    topicId: 'topic-c2-1-8',
    front: 'What is Time Machine and how does its backup schedule work?',
    back: 'Time Machine is macOS\'s built-in automatic backup system.\n\nBackup schedule:\n• Hourly backups for the past 24 hours\n• Daily backups for the past month\n• Weekly backups until the backup drive fills\n• Oldest backups are automatically deleted when space is needed\n\nBackup destinations: external USB/Thunderbolt drive, NAS with Time Machine support.\n\nRestore: Browse via the Time Machine menu bar icon to restore individual files. Full system restore requires macOS Recovery.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-8-05',
    topicId: 'topic-c2-1-8',
    front: 'What macOS file system formats does Disk Utility support, and which should be used for a cross-platform external drive?',
    back: 'APFS — Default for macOS 10.13+ (High Sierra). SSD-optimized, snapshots, native encryption. macOS-only.\n\nHFS+ (Mac OS Extended) — Legacy macOS format. Older Macs and drives.\n\nexFAT — Best choice for cross-platform (macOS + Windows) external drives. No file size limit. Read/write on both OS.\n\nFAT32 — Compatible with everything but limited to 4 GB max file size.\n\nNTFS — Windows native. macOS can READ but NOT WRITE without third-party drivers (e.g., Paragon NTFS).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-8-06',
    topicId: 'topic-c2-1-8',
    front: 'What is Mission Control, and how is it activated?',
    back: 'Mission Control gives a bird\'s-eye view of all open windows, Spaces (virtual desktops), and full-screen apps simultaneously.\n\nActivation: F3 key OR swipe up with three fingers on trackpad.\n\nKey features:\n• Spaces: virtual desktops — switch with Ctrl+Arrow keys\n• Create new Spaces from the Mission Control view\n• Full-screen apps appear as separate Spaces\n• App Exposé (swipe down three fingers): shows all windows of the current app only\n\nEquivalent to Windows virtual desktops (Win+Tab).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-8-07',
    topicId: 'topic-c2-1-8',
    front: 'What macOS utility is equivalent to Windows Task Manager?',
    back: 'Activity Monitor (located in /Applications/Utilities/) is the macOS equivalent of Windows Task Manager.\n\nCapabilities:\n• CPU tab: see per-process CPU usage, stop runaway processes\n• Memory tab: see RAM usage and memory pressure\n• Energy tab: see battery impact per app (laptops)\n• Disk tab: see read/write activity per process\n• Network tab: see per-process network usage\n\nForce quit shortcut: Cmd+Option+Esc (equivalent to Ctrl+Alt+Del > Task Manager).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-8-08',
    topicId: 'topic-c2-1-8',
    front: 'What is the difference between System Preferences and System Settings in macOS?',
    back: 'They are the same tool with different names depending on the macOS version:\n\n• System Preferences — name used in macOS Monterey (12) and earlier\n• System Settings — renamed in macOS Ventura (13) and later; redesigned with a sidebar layout similar to iOS Settings\n\nBoth are the macOS equivalent of Windows Control Panel / Settings app. Exam questions may use either term — treat them as identical. Key sections: Network, Users & Groups, Privacy & Security, Software Update, Displays, Printers & Scanners.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.9 Linux Features (8 cards) ────────────────────────────────────────

  {
    id: 'fc-c2-1-9-01',
    topicId: 'topic-c2-1-9',
    front: 'Compare APT and DNF/YUM package managers — which distros use each?',
    back: 'APT (Advanced Package Tool) — Debian-based distros:\n• Ubuntu, Debian, Linux Mint, Kali Linux, Raspberry Pi OS\n• Commands: apt install, apt update, apt upgrade, apt remove\n• Package format: .deb\n\nDNF / YUM — Red Hat-based distros:\n• Fedora, RHEL, CentOS, AlmaLinux, Rocky Linux\n• Commands: dnf install, dnf check-update, dnf upgrade, dnf remove\n• Package format: .rpm\n• YUM is older; DNF replaced it but YUM still appears on older systems and exams',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-9-02',
    topicId: 'topic-c2-1-9',
    front: 'Explain Linux octal file permissions. What does chmod 755 mean?',
    back: 'Linux permissions use three sets (owner, group, others), each as a sum of:\n• Read (r) = 4\n• Write (w) = 2\n• Execute (x) = 1\n\nchmod 755:\n• 7 = rwx (owner: full access)\n• 5 = r-x (group: read + execute)\n• 5 = r-x (others: read + execute)\n\nCommon patterns:\n• 755 — executables/directories (public read/execute)\n• 644 — regular files (owner write, world read)\n• 700 — private scripts (owner only)\n• 600 — SSH keys / private configs\n• 777 — world-writable (dangerous, avoid)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-9-03',
    topicId: 'topic-c2-1-9',
    front: 'What are the key directories in the Linux Filesystem Hierarchy Standard (FHS)?',
    back: '/ — root of the entire filesystem\n/etc — system configuration files (passwd, hosts, fstab, ssh/)\n/home — user home directories (/home/alice)\n/root — home directory for the root user\n/var — variable data (logs in /var/log, spool files)\n/tmp — temporary files; cleared on reboot\n/bin — essential user binaries (ls, cp, mv)\n/sbin — system binaries for root (fdisk, ifconfig)\n/usr — user programs (/usr/bin, /usr/lib)\n/usr/local — locally installed third-party software\n/dev — device files\n/proc — virtual filesystem: live kernel/process info\n/mnt — temporary manual mount point\n/media — auto-mounted removable media',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-9-04',
    topicId: 'topic-c2-1-9',
    front: 'What is sudo, and how does it differ from su?',
    back: 'sudo (substitute user do) — runs a single command as root without switching to the root account:\n• sudo apt install vim\n• User must be in the sudoers file (/etc/sudoers)\n• Password required is the user\'s own password\n• Provides an audit trail of privileged commands\n\nsu (substitute user) — switches to another user account for the entire session:\n• su - (switch to root, load root\'s environment)\n• su username (switch to another user)\n• Requires the TARGET user\'s password (root\'s password for su -)\n\nBest practice: use sudo for individual elevated commands; avoid logging in directly as root.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-9-05',
    topicId: 'topic-c2-1-9',
    front: 'What is the difference between kill -15 and kill -9 in Linux?',
    back: 'kill -15 (SIGTERM, signal 15) — graceful termination request:\n• Asks the process to save data and exit cleanly\n• The process CAN ignore this signal\n• Default behavior of "kill PID" with no signal specified\n\nkill -9 (SIGKILL, signal 9) — immediate forced termination:\n• The OS kills the process immediately, no cleanup possible\n• The process CANNOT ignore or catch this signal\n• May leave temporary files, sockets, or locks behind\n• Use only when SIGTERM fails\n\nExam tip: "which signal number forces immediate termination?" → 9 (SIGKILL)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-9-06',
    topicId: 'topic-c2-1-9',
    front: 'What does systemctl enable do, and how is it different from systemctl start?',
    back: 'systemctl start servicename — starts the service RIGHT NOW in the current session. Does not affect future boots.\n\nsystemctl enable servicename — configures the service to start automatically at BOOT. Does not start it now.\n\nsystemctl enable --now servicename — combines both: enables at boot AND starts immediately.\n\nsystemctl disable servicename — prevents service from starting at boot (does not stop it now).\n\nsystemctl status servicename — shows current status, whether it is running, enabled, and recent log output.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-9-07',
    topicId: 'topic-c2-1-9',
    front: 'What are the basic vi/vim commands needed to edit and save a file?',
    back: 'vi/vim is a modal terminal text editor available on virtually every Unix/Linux system.\n\nModes:\n• Normal mode — default when vi opens; used for navigation and commands\n• Insert mode — for typing text\n\nEssential commands:\n• i — enter Insert mode (start typing)\n• Esc — return to Normal mode\n• :w — write (save) the file\n• :q — quit (only works if no unsaved changes)\n• :wq — write and quit (save and exit)\n• :q! — quit without saving (force quit)\n• dd — delete current line (Normal mode)\n• /pattern — search forward for pattern',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-9-08',
    topicId: 'topic-c2-1-9',
    front: 'What is the grep command, and what flags are commonly tested on the exam?',
    back: 'grep searches for text patterns within files.\n\nBasic: grep "pattern" filename\n\nCommon flags:\n• -r — recursive (search all files in directory tree)\n• -i — case-insensitive match\n• -n — show line numbers in output\n• -v — invert match (show lines that do NOT match)\n• -l — show only filenames with matches (not the lines)\n• -c — count matching lines\n\nExam scenarios:\n• Search logs recursively: grep -r "error" /var/log/\n• Case-insensitive search: grep -i "Error" auth.log\n• Search with line numbers: grep -n "failed" syslog',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.10 Application Installation (8 cards) ─────────────────────────────

  {
    id: 'fc-c2-1-10-01',
    topicId: 'topic-c2-1-10',
    front: '32-bit vs 64-bit application compatibility rules — what can run on what?',
    back: '64-bit OS:\n• CAN run 64-bit applications (native)\n• CAN run 32-bit applications (via WOW64 compatibility layer)\n• CANNOT run 16-bit applications\n\n32-bit OS:\n• CAN run 32-bit applications\n• CANNOT run 64-bit applications\n• CAN run 16-bit applications (via NT Virtual DOS Machine on 32-bit Windows)\n\nWOW64 = Windows 32-bit on Windows 64-bit — a subsystem that translates 32-bit API calls so they work on a 64-bit OS. Transparent to the user.\n\nInstall locations on 64-bit Windows:\n• 64-bit apps → C:\\Program Files\\\n• 32-bit apps → C:\\Program Files (x86)\\',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-10-02',
    topicId: 'topic-c2-1-10',
    front: 'What are the silent install switches for MSI packages?',
    back: 'msiexec is the Windows Installer command for MSI packages.\n\nKey switches:\n• /i package.msi — install\n• /x package.msi — uninstall\n• /quiet — completely silent; no UI, no prompts\n• /passive — minimal UI with progress bar; no prompts\n• /norestart — suppress automatic reboot\n• /log logfile.txt — write installation log\n\nSilent install example:\nmsiexec /i package.msi /quiet /norestart\n\nTransform files (.mst) customize MSI installations for enterprise deployment — applied with /t transform.mst.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-10-03',
    topicId: 'topic-c2-1-10',
    front: 'What is WOW64 and when does it apply?',
    back: 'WOW64 (Windows 32-bit on Windows 64-bit) is a compatibility subsystem built into 64-bit Windows that allows 32-bit applications to run without modification.\n\nHow it works: WOW64 intercepts 32-bit API calls and translates them to their 64-bit equivalents, then translates responses back. This is transparent to the user and the application.\n\nLimitations:\n• 32-bit kernel-mode drivers will NOT run on 64-bit Windows (must use 64-bit drivers)\n• 16-bit applications are NOT supported on 64-bit Windows via WOW64\n• Anti-cheat and low-level security software may require 64-bit versions',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-10-04',
    topicId: 'topic-c2-1-10',
    front: 'What are common Windows application prerequisites and what errors do they cause when missing?',
    back: 'Microsoft .NET Framework / .NET:\n• Required by many Windows apps\n• Windows 10/11 includes .NET Framework 4.x built-in\n• .NET 5/6/7/8 must be installed separately\n• Missing: app fails to launch with .NET error\n\nVisual C++ Redistributables (VC++ Runtime):\n• Libraries for apps compiled with Microsoft Visual C++\n• Multiple versions coexist (2010, 2015, 2019, 2022)\n• Missing: "The program can\'t start because [MSVCP140.dll / VCRUNTIME140.dll] is missing"\n• Fix: install the correct VC++ Redistributable from Microsoft\n\nJava Runtime Environment (JRE):\n• Required for Java-based applications\n• Missing: app fails to launch with Java error',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-10-05',
    topicId: 'topic-c2-1-10',
    front: 'How do you manage application startup entries in Windows 10/11?',
    back: 'Task Manager > Startup tab — the primary location in Windows 10/11.\n• Shows all startup applications with their startup impact rating (Low, Medium, High)\n• Right-click any entry > Disable to prevent auto-launch at boot\n• Disabling does not uninstall the application\n\nAlternative locations:\n• msconfig > Startup tab (Windows 7/8 / legacy reference on exams)\n• Shell:startup folder (C:\\Users\\username\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup)\n• Registry: HKLM and HKCU ...\\CurrentVersion\\Run keys\n\nExam tip: if an app slows boot time → Task Manager > Startup tab.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-10-06',
    topicId: 'topic-c2-1-10',
    front: 'What is Windows Compatibility Mode and when should it be used?',
    back: 'Compatibility Mode applies OS-level shims to mimic older Windows behaviors for legacy applications that fail on modern Windows.\n\nHow to enable:\nRight-click EXE > Properties > Compatibility tab > "Run this program in compatibility mode for:" > select Windows version (XP SP2/SP3, Vista, 7, 8)\n\nHow it works: The OS intercepts specific API calls from the legacy app and redirects them to modern equivalents. It does NOT actually run the old OS.\n\nWhen to use: first troubleshooting step for a legacy app that errors on modern Windows.\n\nLimitation: not all compatibility issues can be fixed this way — a VM may be needed.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-10-07',
    topicId: 'topic-c2-1-10',
    front: 'What are the software distribution methods tested on the CompTIA A+ exam?',
    back: 'Physical media (CD/DVD) — legacy; declining use.\n\nUSB drive — portable installer media; used for OS installations and field deployments.\n\nNetwork share — installer stored on a file server (\\\\server\\software\\); common in corporate environments.\n\nWeb/cloud download — vendor website download; most common for consumer software. Verify integrity with SHA-256 hash (certutil -hashfile file.exe SHA256).\n\nEnterprise MDM/deployment tools — SCCM, Microsoft Intune, Jamf, PDQ Deploy; used for large-scale silent deployments to managed devices.\n\nEmail attachment — HIGH RISK; primary malware vector. Avoid running installers received via email.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-10-08',
    topicId: 'topic-c2-1-10',
    front: 'What impacts does installing a new application have on a Windows system?',
    back: 'Disk space — installation files plus ongoing data growth (logs, cache, databases).\n\nRAM — active when app runs; background services use RAM even when app is closed.\n\nStartup time — many apps add startup entries (Task Manager > Startup to manage).\n\nBackground services — some apps install Windows Services that run at all times (services.msc to view/manage).\n\nSystem tray — background processes often add tray icons.\n\nBrowser extensions — apps may install toolbars or extensions without clear disclosure.\n\nNetwork — cloud apps and updaters consume bandwidth.\n\nSecurity — every app is a potential attack surface; verify source and digital signature before installing.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.11 Cloud Productivity Tools (8 cards) ─────────────────────────────

  {
    id: 'fc-c2-1-11-01',
    topicId: 'topic-c2-1-11',
    front: 'Compare Microsoft 365 and Google Workspace at a high level.',
    back: 'Microsoft 365:\n• Desktop apps (Word, Excel, PowerPoint, Outlook, Teams) + cloud services\n• Deep Windows integration; OneDrive built into Windows 10/11\n• Files stored in OneDrive (personal) and SharePoint (teams)\n• Enterprise MDM via Intune; SSO via Microsoft Entra ID\n• Per-user subscription; install on up to 5 devices\n\nGoogle Workspace:\n• Primarily browser-based (Docs, Sheets, Slides, Gmail, Meet, Chat)\n• No installation required for core apps\n• Files stored in Google Drive (My Drive or Shared Drives)\n• Offline access via Google Docs Offline Chrome extension\n• 15 GB free storage shared across Drive/Gmail/Photos',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-11-02',
    topicId: 'topic-c2-1-11',
    front: 'What are the OneDrive Files On-Demand sync status icons?',
    back: 'OneDrive Files On-Demand shows sync status icons in File Explorer:\n\n• Cloud outline (white cloud) — Online-only. File is in OneDrive but NOT downloaded locally. Clicking downloads it on demand.\n\n• Green checkmark (circle) — Synced. File is available offline on this device.\n\n• Blue arrows (circle) — Syncing. File is currently uploading or downloading.\n\n• Red X (circle) — Sync error. File failed to sync and needs attention.\n\nTo manage: right-click OneDrive tray icon > Settings > Account > Choose folders (Selective Sync).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-11-03',
    topicId: 'topic-c2-1-11',
    front: 'What email protocols and port numbers are tested on CompTIA A+?',
    back: 'Receiving email:\n• IMAP — port 143 (plain) / 993 (SSL). Keeps mail on server; syncs across devices. Preferred for multi-device use.\n• POP3 — port 110 (plain) / 995 (SSL). Downloads mail to local device; deletes from server by default. Single device.\n\nSending email:\n• SMTP submission — port 587 (STARTTLS). Used by email clients to send outbound mail with authentication.\n• SMTP relay — port 25. Server-to-server relay; blocked by ISPs to prevent spam. Not for end-user clients.\n• SMTPS — port 465 (SSL/TLS). Legacy encrypted SMTP.\n\nExchange/ActiveSync — port 443 (HTTPS).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-11-04',
    topicId: 'topic-c2-1-11',
    front: 'What is the difference between POP3 and IMAP for email access?',
    back: 'POP3 (Post Office Protocol 3):\n• Downloads messages to the local device\n• Typically deletes messages from the server after download\n• No folder sync between devices\n• Works on one device at a time\n• Ports: 110 (plain) / 995 (SSL)\n• Use when: single device, offline access priority\n\nIMAP (Internet Message Access Protocol):\n• Keeps messages on the server\n• Syncs folder structure, read/unread status, and flags across all devices\n• Changes on one device are reflected on all others\n• Ports: 143 (plain) / 993 (SSL)\n• Use when: multiple devices, always need current state',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-11-05',
    topicId: 'topic-c2-1-11',
    front: 'What is Autodiscover in Microsoft 365, and why is it important?',
    back: 'Autodiscover is a service that allows Outlook and other email clients to automatically configure themselves by entering only the user\'s email address and password.\n\nHow it works: Outlook queries DNS for an autodiscover record (autodiscover.domain.com) that points to the Exchange server configuration. The server returns all settings automatically — incoming server, outgoing server, ports, and encryption type.\n\nWhy it matters: eliminates manual server configuration for users. If Autodiscover fails, manual settings for Microsoft 365 are:\n• Incoming: outlook.office365.com, port 993 (IMAP) or 443 (Exchange)\n• Outgoing: smtp.office365.com, port 587 (STARTTLS)',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-11-06',
    topicId: 'topic-c2-1-11',
    front: 'What is the free storage tier for the major cloud storage services?',
    back: 'Memorize for the exam:\n\n• OneDrive (Microsoft) — 5 GB free\n• Google Drive — 15 GB free (shared with Gmail and Google Photos)\n• iCloud Drive (Apple) — 5 GB free\n• Dropbox — 2 GB free\n• Box — 10 GB free\n\nMicrosoft 365 Personal/Family plans include 1 TB of OneDrive storage per user.\nGoogle Workspace business plans provide more or unlimited Drive storage.\n\nExam tip: Google Drive gives the most free storage at 15 GB. Dropbox gives the least at 2 GB.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-11-07',
    topicId: 'topic-c2-1-11',
    front: 'What steps should IT take when an employee leaves the organization? (Cloud account offboarding)',
    back: 'Correct offboarding sequence for Microsoft 365 / Google Workspace:\n\n1. DISABLE the account immediately — stops all cloud access (email, Teams, SharePoint, Drive)\n2. DO NOT delete yet — preserve the mailbox and file data per retention policy (typically 30 days)\n3. Revoke active sessions and app passwords\n4. Transfer ownership of files/data to a manager or successor\n5. Reassign email alias / set up auto-reply or mail forwarding as needed\n6. Remove the user\'s device from MDM enrollment\n7. After retention period expires — delete the account and release the license\n\nKey: disable FIRST, delete LAST.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'fc-c2-1-11-08',
    topicId: 'topic-c2-1-11',
    front: 'What is Conditional Access in Microsoft Entra ID (Azure AD) and what conditions can it evaluate?',
    back: 'Conditional Access is a policy engine in Microsoft Entra ID that controls access to cloud apps based on specified conditions.\n\nConditions evaluated:\n• User identity and group membership\n• Device compliance status (enrolled in Intune? encrypted? OS up to date?)\n• Location (IP address range, country)\n• Application being accessed (Teams vs. SharePoint vs. Admin Center)\n• Sign-in risk level (from Microsoft Entra ID Protection)\n\nActions: Allow access, Block access, or Require MFA.\n\nExample: Block access to SharePoint from devices not enrolled in Intune, or require MFA when signing in from outside the corporate network.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

]
