// 80 verified practice questions for CompTIA A+ 220-1202 Core 2 Domain 4: Operational Procedures
// Covers objectives 4.1–4.10 with accurate, exam-representative content

const NOW = new Date().toISOString()

type Choice = { id: string; text: string; isCorrect: boolean }

function ch(a: string, b: string, c: string, d: string, correct: 'a' | 'b' | 'c' | 'd'): string {
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: correct === 'a' },
    { id: 'b', text: b, isCorrect: correct === 'b' },
    { id: 'c', text: c, isCorrect: correct === 'c' },
    { id: 'd', text: d, isCorrect: correct === 'd' },
  ] as Choice[])
}

const ca = (id: 'a' | 'b' | 'c' | 'd') => JSON.stringify(id)

export const BATCH7_QUESTIONS = [

  // ─── 4.1 Documentation (8 questions) ────────────────────────────────────────

  {
    id: 'q-c2-4-1-01',
    topicId: 'topic-c2-4-1',
    type: 'single_choice',
    stem: 'A network technician needs to verify which VLAN a particular server is assigned to and confirm the routing path between two network segments. Which type of documentation should the technician consult?',
    choices: ch(
      'Physical network diagram',
      'Logical network diagram',
      'Asset inventory',
      'Change log',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A logical network diagram shows IP address schemes, VLAN assignments, routing paths, firewall zones, and device hostnames — it represents how data flows through the network regardless of physical location. A physical diagram shows cable runs, rack locations, and room numbers. For VLAN and routing information, the logical diagram is the correct tool.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-1-02',
    topicId: 'topic-c2-4-1',
    type: 'single_choice',
    stem: 'A data center technician is tasked with replacing a failed switch. They need to know which rack it is in and which patch panel ports connect to it. Which document should they reference?',
    choices: ch(
      'Logical network diagram',
      'Knowledge base article',
      'Physical network diagram',
      'SLA document',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A physical network diagram documents cable runs, rack numbers, room numbers, building names, and patch panel port assignments. This is the correct reference for physically locating and identifying equipment in the data center. Logical diagrams show IP and VLAN information, not physical location.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-1-03',
    topicId: 'topic-c2-4-1',
    type: 'single_choice',
    stem: 'A helpdesk manager wants to ensure that all technicians resolve a common printer connectivity issue the same way every time, and that users can resolve it themselves. Which two documentation artifacts best serve these goals?',
    choices: ch(
      'Change log and SLA',
      'SOP (for technicians) and knowledge base article (for users)',
      'Asset inventory and CMDB',
      'Incident record and chain of custody',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'An SOP (Standard Operating Procedure) documents a step-by-step procedure for technicians to ensure the task is performed consistently regardless of who handles it. A knowledge base article provides the same information in a self-service format for end users. Together these serve both the consistency and self-service goals. Change logs document changes, not recurring procedures.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-1-04',
    topicId: 'topic-c2-4-1',
    type: 'single_choice',
    stem: 'After investigating a system compromise, the security team discovers that a configuration file was modified two weeks ago outside a maintenance window. Which document would provide accountability for that change?',
    choices: ch(
      'Incident record',
      'Knowledge base article',
      'Baseline configuration',
      'Change log',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'A change log records what was changed, when, who made the change, why it was necessary, and how to reverse it. It provides accountability and is the primary reference when troubleshooting issues that started "right after maintenance." A baseline configuration documents the approved state of a system and helps detect unauthorized changes by comparison.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-1-05',
    topicId: 'topic-c2-4-1',
    type: 'single_choice',
    stem: 'Which document tracks hardware serial numbers, purchase dates, warranty expiration, physical location, and assigned user for every device in an organization?',
    choices: ch(
      'CMDB',
      'Asset inventory',
      'Network diagram',
      'SLA',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'An asset inventory tracks every hardware asset and at minimum includes manufacturer, model, serial number, purchase date, warranty expiration, physical location, and assigned user or department. A CMDB (Configuration Management Database) extends this by also tracking relationships between assets — which servers run which services, which applications depend on which databases.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-1-06',
    topicId: 'topic-c2-4-1',
    type: 'single_choice',
    stem: 'A ticketing system shows a closed ticket with the resolution note "fixed it." Why is this problematic from a documentation standpoint?',
    choices: ch(
      'The ticket should have been escalated before closing',
      'The resolution provides zero value for pattern analysis or future troubleshooting because it lacks exact symptoms, troubleshooting steps, root cause, and resolution details',
      'Tickets can only be closed by the original reporter',
      'The SLA clock should be stopped before closing',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A ticket that says "fixed it" with no details of what was done provides zero value for pattern analysis or future troubleshooting. Every ticket must document: exact symptoms, all troubleshooting steps taken (including steps that did not work), root cause, and the specific resolution. Documentation quality is a measurable indicator of technician professionalism and is critical for identifying recurring failure patterns.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-1-07',
    topicId: 'topic-c2-4-1',
    type: 'single_choice',
    stem: 'During a digital forensics investigation, the security team transfers a confiscated hard drive to a third-party forensic lab. Which document must accompany this transfer to preserve the admissibility of evidence?',
    choices: ch(
      'SLA',
      'Knowledge base article',
      'Chain of custody record',
      'Incident ticket',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A chain of custody record documents every person who handles evidence — who had it, when, what they did with it, and who received it on transfer. Any break in the chain of custody can make evidence inadmissible in court. This is a forensics requirement that the A+ exam directly tests.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-1-08',
    topicId: 'topic-c2-4-1',
    type: 'single_choice',
    stem: 'A company adopts the ITIL framework and implements a system that tracks not just individual assets, but the relationships between assets — which servers run which applications, and which applications depend on which databases. What is this system called?',
    choices: ch(
      'Asset inventory',
      'CMDB (Configuration Management Database)',
      'Knowledge base',
      'SLA management system',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A CMDB (Configuration Management Database) is an ITIL concept that extends asset inventory to also track relationships between configuration items — which servers run which services, which switches connect to which, which applications depend on which databases. CMDBs are a core component of ITIL Service Management and are commonly managed in platforms like ServiceNow.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.2 Change Management (8 questions) ─────────────────────────────────────

  {
    id: 'q-c2-4-2-01',
    topicId: 'topic-c2-4-2',
    type: 'single_choice',
    stem: 'A technician wants to apply a configuration change to a production server. According to change management best practices, what must be documented BEFORE the change is made?',
    choices: ch(
      'Post-implementation review notes',
      'User acceptance test results',
      'Rollback plan',
      'Updated knowledge base article',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A rollback plan — the documented procedure for reversing the change if it fails — must be written before the change is made, not during an outage when there is no time to think it through. A change without a rollback plan should not be approved. The rollback plan must be specific, actionable, time-boxed, and assigned to a responsible person.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-2-02',
    topicId: 'topic-c2-4-2',
    type: 'single_choice',
    stem: 'Which body is responsible for reviewing, approving, or rejecting change requests (RFCs) in a formal change management process?',
    choices: ch(
      'SLA committee',
      'CAB (Change Advisory Board)',
      'Help desk manager',
      'eCAB',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'The CAB (Change Advisory Board) reviews and approves significant changes before they are implemented. Typical composition includes IT management, affected business unit representatives, the security team, operations leads, and application owners. The CAB meets regularly to challenge assumptions, identify risks, and ensure alignment with business priorities. The eCAB (Emergency CAB) handles urgent changes that cannot wait for the regular cycle.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-2-03',
    topicId: 'topic-c2-4-2',
    type: 'single_choice',
    stem: 'An organization applies monthly OS security patches to all workstations on the same schedule every month. This process has been tested and approved as a repeating procedure. What type of change is this classified as?',
    choices: ch(
      'Emergency change',
      'Normal change',
      'Standard change',
      'Unauthorized change',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A standard change is a pre-approved, routine, low-risk change with a well-documented procedure. Monthly Patch Tuesday patching is a classic example of a standard change — the category is approved once, and individual monthly patches are documented but do not require new CAB approval each month. Normal changes require full CAB review. Emergency changes are for urgent situations like active outages.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-2-04',
    topicId: 'topic-c2-4-2',
    type: 'single_choice',
    stem: 'A critical zero-day vulnerability is being actively exploited in the wild. The vendor has released an emergency patch. The organization needs to apply it immediately but the next regular CAB meeting is three days away. What is the correct change management approach?',
    choices: ch(
      'Skip change management entirely since it is an emergency',
      'Wait for the regular CAB meeting to maintain process integrity',
      'Use the emergency CAB (eCAB) process for expedited approval followed by post-implementation review',
      'Apply the patch and document it in the change log after the fact only',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'An emergency change is used when an urgent situation — such as an active exploit or critical security patch — cannot wait for the standard CAB cycle. The correct approach is to use the emergency CAB (eCAB) process for expedited approval with available CAB members and IT management, apply the change, and then complete a full post-implementation review. Change management is never skipped entirely — even emergency changes require documentation.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-2-05',
    topicId: 'topic-c2-4-2',
    type: 'single_choice',
    stem: 'A change is applied to a production server during a maintenance window. After the change, verification testing reveals the primary application is no longer responding. What should happen next?',
    choices: ch(
      'Wait until morning to assess the situation',
      'Open a new incident ticket and begin troubleshooting from scratch',
      'Execute the rollback plan immediately',
      'Escalate to the CAB for guidance',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'When post-implementation verification fails during a change window, the rollback plan should be executed immediately. The rollback plan was documented before the change precisely for this scenario. It defines the specific steps to revert the change and a time-box trigger — for example, "if service is not restored by 02:00, initiate rollback." Waiting or trying to troubleshoot from scratch wastes the maintenance window.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-2-06',
    topicId: 'topic-c2-4-2',
    type: 'single_choice',
    stem: 'Before submitting an RFC, a technician tests the configuration change in the staging environment. The change works correctly. What is the primary purpose of this step?',
    choices: ch(
      'To satisfy the CAB so the meeting can be skipped',
      'To validate that the change works as intended and does not break existing functionality before it reaches production',
      'To generate post-implementation review documentation',
      'To update the CMDB with the new configuration',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Testing in a staging or pre-production environment — which mirrors production as closely as possible — validates that the change achieves its goal and does not introduce regressions. Testing in staging does not eliminate the requirement for CAB approval; it is one step in the process. Post-implementation testing in production still occurs after the change is deployed.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-2-07',
    topicId: 'topic-c2-4-2',
    type: 'single_choice',
    stem: 'After a significant change is successfully deployed and verified, which final step completes the change management cycle?',
    choices: ch(
      'Submitting a new RFC for the next change',
      'Updating the CMDB, network diagrams, configuration baselines, and closing the RFC with implementation notes',
      'Archiving the rollback plan for future reference',
      'Notifying the eCAB of the outcome',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'After a successful change, documentation must be updated to reflect the new state of the environment: CMDB, network diagrams, configuration baselines, and runbooks. The RFC is closed with implementation notes and the outcome. This ensures the organization\'s documentation remains accurate and the next change can reference the current state.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-2-08',
    topicId: 'topic-c2-4-2',
    type: 'single_choice',
    stem: 'A technician makes what they believe is a trivial configuration tweak to a production firewall without submitting an RFC, believing the change is too small to need approval. Why is this a problem?',
    choices: ch(
      'The tweak will be overwritten by the next scheduled backup',
      'Undocumented changes to production systems have no rollback reference and no accountability — even small changes can interact with other configurations unexpectedly',
      'Only senior engineers are allowed to make configuration tweaks',
      'The firewall vendor\'s EULA requires RFC submission for all changes',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Making undocumented changes to production systems — even small ones — violates change management principles. A seemingly trivial tweak can interact with other configurations in unexpected ways. Without a change record, there is no rollback reference if something goes wrong, and no accountability for what was changed. Change management applies to all significant changes regardless of perceived impact.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.3 Backup & Recovery (8 questions) ─────────────────────────────────────

  {
    id: 'q-c2-4-3-01',
    topicId: 'topic-c2-4-3',
    type: 'single_choice',
    stem: 'An organization runs a full backup every Sunday and incremental backups Monday through Saturday. A failure occurs on Friday. What is needed to restore the data to Thursday night\'s state?',
    choices: ch(
      'Sunday\'s full backup only',
      'Sunday\'s full backup plus Monday\'s incremental only',
      'Sunday\'s full backup plus every incremental from Monday through Thursday',
      'Thursday\'s incremental backup only',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Incremental backups capture only changes since the LAST backup of any type. To restore to Thursday night, you need the Sunday full backup plus every incremental in sequence (Monday, Tuesday, Wednesday, Thursday) — because each incremental only contains the changes since the previous backup. This is why incremental has the most complex restore process. Differential requires only the full plus the most recent differential.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-3-02',
    topicId: 'topic-c2-4-3',
    type: 'single_choice',
    stem: 'A company runs a full backup every Monday and differential backups Tuesday through Sunday. A failure occurs on Saturday. What backup sets are needed for a complete restore?',
    choices: ch(
      'Monday\'s full backup plus every differential from Tuesday through Friday',
      'Monday\'s full backup plus Friday\'s differential only',
      'Friday\'s differential backup only',
      'Saturday\'s differential plus Sunday\'s full',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Differential backups capture all changes since the LAST FULL backup. Friday\'s differential contains all changes since Monday\'s full. To restore to Friday night\'s state, you only need Monday\'s full backup plus Friday\'s differential — just two sets. This is faster to restore than incremental, which would require Monday\'s full plus every individual daily incremental.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-3-03',
    topicId: 'topic-c2-4-3',
    type: 'single_choice',
    stem: 'Which backup type clears the archive bit after completion, backs up all selected data on every run, and provides the simplest restore process?',
    choices: ch(
      'Incremental',
      'Differential',
      'Full',
      'Synthetic full',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A full backup backs up all selected data every time regardless of the archive bit, and clears the archive bit after completion. It is the slowest backup type but provides the simplest restore — only one backup set is needed. Incremental clears the archive bit but only backs up changes since the last backup. Differential does NOT clear the archive bit and backs up all changes since the last full.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-3-04',
    topicId: 'topic-c2-4-3',
    type: 'single_choice',
    stem: 'The 3-2-1 backup rule requires that data be stored in which configuration?',
    choices: ch(
      '3 full backups, 2 incremental backups, 1 differential backup',
      '3 copies of data, on 2 different media types, with 1 copy offsite',
      '3 local copies, 2 cloud copies, 1 tape archive',
      '3 daily backups, 2 weekly backups, 1 monthly backup',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'The 3-2-1 rule states: keep 3 copies of data, on 2 different media types, with 1 copy offsite. Example: original data on workstation (copy 1), local NAS backup (copy 2, different media), cloud backup (copy 3, offsite). This protects against local hardware failure, media-specific failure, and site-level disasters. This rule appears directly on the A+ exam.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-3-05',
    topicId: 'topic-c2-4-3',
    type: 'single_choice',
    stem: 'A user\'s Windows system became unstable after a driver installation. The technician uses System Restore to roll back to a restore point from before the driver install. Which statement about System Restore is accurate?',
    choices: ch(
      'System Restore also recovers any personal documents deleted since the restore point',
      'System Restore rolls back system files, drivers, and registry settings but does NOT restore personal user files',
      'System Restore requires a full system image created with Windows Backup',
      'System Restore is only available if the system can boot normally',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'System Restore creates restore points containing Windows system files, drivers, and registry settings. It does NOT back up or restore personal files such as documents, photos, or email. This is an important distinction: System Restore is not a substitute for full backup. Restore points are created automatically before Windows Updates, driver installs, and application installs, and can also be created manually.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-3-06',
    topicId: 'topic-c2-4-3',
    type: 'single_choice',
    stem: 'An organization\'s backup policy states an RPO of 4 hours. What does this mean operationally?',
    choices: ch(
      'The organization must restore all systems within 4 hours of a failure',
      'Backups must complete within 4 hours or they are considered failed',
      'The organization can tolerate losing no more than 4 hours of data, so backups must run at least every 4 hours',
      'The organization must retain 4 hours of transaction logs',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'RPO (Recovery Point Objective) is the maximum acceptable amount of data loss, measured in time. An RPO of 4 hours means the organization can tolerate losing up to 4 hours of data — therefore backups must run at least every 4 hours. RTO (Recovery Time Objective) is the maximum acceptable time to restore service after an incident. RPO drives backup frequency; RTO drives restore speed requirements.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-3-07',
    topicId: 'topic-c2-4-3',
    type: 'single_choice',
    stem: 'A technician creates a system image of a Windows workstation. What is the key difference between a system image and a File History backup?',
    choices: ch(
      'A system image can only be stored on tape media',
      'A system image captures a sector-by-sector snapshot of the entire drive including OS, applications, and settings; File History backs up user files only',
      'File History requires more storage space than a system image',
      'A system image cannot be restored to a different machine',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A system image is a sector-by-sector snapshot of an entire drive — OS, applications, settings, and data all captured together — enabling a complete bare-metal restore. File History continuously backs up selected user folders (Documents, Desktop, Pictures, etc.) to an external drive or network location and keeps version history, but does NOT back up the OS, applications, or settings.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-3-08',
    topicId: 'topic-c2-4-3',
    type: 'single_choice',
    stem: 'In the GFS (Grandfather-Father-Son) backup rotation scheme, which backup set represents the "Son"?',
    choices: ch(
      'Monthly full backup retained for one year',
      'Weekly full backup retained for one month',
      'Daily backup (typically incremental or differential) retained for one week',
      'Quarterly full backup retained for three years',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'In GFS rotation: Son = daily backup (typically incremental or differential), retained through the current week. Father = weekly full backup, retained for the current month. Grandfather = monthly full backup, retained for a year or longer. GFS balances storage cost with recovery flexibility — you can restore to any day this week, any week this month, and any month in the past year.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.4 Safety Procedures (8 questions) ─────────────────────────────────────

  {
    id: 'q-c2-4-4-01',
    topicId: 'topic-c2-4-4',
    type: 'single_choice',
    stem: 'A technician is installing RAM into a workstation. Which action BEST prevents ESD damage to the components?',
    choices: ch(
      'Work on a carpeted floor to cushion the components if dropped',
      'Wear an antistatic wrist strap connected to an unpainted metal surface on the chassis',
      'Hold RAM by the gold connector contacts for a firm grip',
      'Work quickly to minimize exposure time',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'An antistatic wrist strap clipped to an unpainted metal chassis surface provides continuous equalization of charge between the technician and the equipment, preventing ESD damage. Carpeted surfaces generate significant static and should be avoided. Components should be held by their edges — never by the gold contacts or IC chips. The 1 MΩ resistor in the wrist strap limits current if the technician contacts a live circuit.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-4-02',
    topicId: 'topic-c2-4-4',
    type: 'single_choice',
    stem: 'At what voltage level can ESD damage occur to electronic components, even without a visible spark or sensation to the technician?',
    choices: ch(
      '3,000 volts (the human perception threshold)',
      '30 volts or less — well below human perception',
      '120 volts (standard US line voltage)',
      '500 volts minimum',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Electronic components can be damaged by ESD at as little as 30 volts. Humans typically cannot feel a static discharge below about 3,000 volts. This means a technician can damage a CPU, RAM stick, or network card without any sensation of a discharge. This type of sub-threshold damage is called "latent damage" and may cause intermittent failures rather than immediate visible failure.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-4-03',
    topicId: 'topic-c2-4-4',
    type: 'single_choice',
    stem: 'A technician is called to service a CRT monitor that has been unplugged for several hours. What is the primary electrical safety concern with this equipment?',
    choices: ch(
      'CRT monitors cannot be damaged by ESD so no precautions are needed',
      'The flyback transformer and capacitors inside a CRT can hold charges of 25,000 volts or more even hours after being turned off and unplugged',
      'Unplugged CRTs are safe to open since there is no active power source',
      'CRT monitors contain mercury that must be handled with gloves',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'CRT monitors are extremely dangerous even when completely unplugged. The flyback transformer and capacitors can hold charges of 25,000 volts or more for hours or even days after the monitor is turned off and unplugged. This lethal charge can discharge through a person. CRTs should never be opened unless you are specifically trained to do so — this is a key A+ exam safety topic.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-4-04',
    topicId: 'topic-c2-4-4',
    type: 'single_choice',
    stem: 'A server rack in the data center catches fire due to an electrical fault. Which fire extinguisher class is appropriate for this electrical fire?',
    choices: ch(
      'Class A — water extinguisher',
      'Class B — foam extinguisher',
      'Class C — CO2 or dry chemical extinguisher',
      'Class K — wet chemical extinguisher',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Class C extinguishers are designed for electrical fires — they use non-conductive agents such as CO2 or dry chemical. Using water (Class A) on an electrical fire is extremely dangerous because water conducts electricity. CO2 extinguishers are often preferred in IT environments because they leave no residue that could damage electronics, unlike dry chemical (ABC) which leaves a corrosive powder.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-4-05',
    topicId: 'topic-c2-4-4',
    type: 'single_choice',
    stem: 'A laser printer toner cartridge breaks and spills toner powder across the floor. What is the correct cleanup procedure?',
    choices: ch(
      'Use a regular household vacuum to quickly clean up the fine powder',
      'Use compressed air to blow the toner into a corner for easier cleanup',
      'Use a toner-specific or HEPA-filter vacuum and clean skin contact with cold water',
      'Wipe the area with a dry cloth and dispose of it in regular trash',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Toner is an extremely fine powder that is a respiratory hazard if inhaled. A regular vacuum\'s filters do not capture particles this small — the toner passes through and is dispersed into the air. A toner-specific vacuum or HEPA-filter vacuum must be used. Skin contact with toner should be cleaned with cold water — hot water fuses toner to skin. Compressed air should never be used on toner spills.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-4-06',
    topicId: 'topic-c2-4-4',
    type: 'single_choice',
    stem: 'A technician needs to move a server that weighs approximately 60 lbs from one rack to another. What is the correct safety approach?',
    choices: ch(
      'Lift with back bent to keep the center of gravity low',
      'Ask a second person to assist, use a wheeled equipment cart, and lift with legs not back',
      'Drag the server across the floor to avoid the risk of dropping it',
      'One technician can safely lift up to 100 lbs if they use a back brace',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Anything above approximately 50 lbs requires a second person. The correct lifting technique uses legs (not the back), keeps the back straight, gets close to the load, and avoids twisting. Wheeled equipment carts and server rack rails exist precisely to minimize manual lifting. Improper lifting technique causes back injuries that can be career-ending.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-4-07',
    topicId: 'topic-c2-4-4',
    type: 'single_choice',
    stem: 'Where must an SDS (Safety Data Sheet) be available for every chemical substance used in a workplace?',
    choices: ch(
      'Only in the hazardous materials storage room',
      'Only in the HR office for regulatory compliance',
      'Accessible to all employees who may work with or near those chemicals',
      'Only online at the chemical manufacturer\'s website',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Every workplace that uses chemicals is legally required to have SDS documents (formerly called MSDS) accessible to all employees who may work with or near those chemicals. An SDS contains 16 standardized sections including hazard identification, first-aid measures, PPE requirements, and disposal information. In IT, common chemicals requiring SDS include toner, isopropyl alcohol, and battery electrolytes.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-4-08',
    topicId: 'topic-c2-4-4',
    type: 'single_choice',
    stem: 'A technician is replacing a toner cartridge and notices loose toner dust near the printer. Which PPE combination is most appropriate?',
    choices: ch(
      'Safety glasses and steel-toed boots',
      'ESD wrist strap and ear protection',
      'N95 respirator mask and nitrile gloves',
      'Safety glasses and ESD wrist strap',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Toner is a respiratory hazard (fine particulate) and a skin irritant. An N95 respirator mask prevents inhalation of toner dust, and nitrile gloves protect the skin from contact. Safety glasses are appropriate for tasks involving flying fragments or compressed air. ESD straps are for electronic component handling. Ear protection is for loud server rooms. Multiple PPE types may apply simultaneously in some scenarios.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.5 Environmental Controls (8 questions) ────────────────────────────────

  {
    id: 'q-c2-4-5-01',
    topicId: 'topic-c2-4-5',
    type: 'single_choice',
    stem: 'A data center manager wants to implement the standard rack layout that prevents hot exhaust air from mixing with cold supply air. What configuration should be used?',
    choices: ch(
      'Side-by-side aisle layout',
      'Hot aisle / cold aisle configuration',
      'Raised floor cooling with uniform airflow',
      'In-row cooling with downflow units',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Hot aisle / cold aisle is the standard rack layout for server rooms. Server rack fronts face each other in the cold aisle (where cool air is supplied) and rack rears face each other in the hot aisle (where exhaust heat is returned to the HVAC). This prevents hot and cold air from mixing, which wastes cooling capacity and creates hot spots. Hot aisle containment with curtains or doors further improves efficiency.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-5-02',
    topicId: 'topic-c2-4-5',
    type: 'single_choice',
    stem: 'A power outage occurs and the office UPS units keep workstations running for several minutes. What is the PRIMARY purpose of a UPS during a power outage?',
    choices: ch(
      'Protect against voltage spikes on the power line',
      'Provide battery backup power to allow graceful shutdown or bridge the gap until a generator starts',
      'Filter electrical noise from the power line',
      'Provide unlimited runtime until utility power is restored',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A UPS (Uninterruptible Power Supply) provides battery backup during a power outage, giving runtime for a graceful shutdown or to bridge the gap until a generator starts (typically 10–30 seconds). A surge protector protects against voltage spikes but provides no battery backup. A line conditioner filters power noise but has no battery. UPS runtime is measured in minutes, not hours — it is not designed to replace utility power long-term.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-5-03',
    topicId: 'topic-c2-4-5',
    type: 'single_choice',
    stem: 'What is the recommended relative humidity range for a server room or data center to minimize both condensation and ESD risk?',
    choices: ch(
      '10–20% RH',
      '25–35% RH',
      '40–60% RH',
      '70–80% RH',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'The recommended relative humidity range for computing environments is approximately 40–60% RH (ASHRAE guidance is 45–55%). Below 40%, low humidity dramatically increases electrostatic buildup and ESD risk. Above 60%, condensation can form on components and in connectors, causing corrosion and shorts. Temperature target is 64–80°F (18–27°C) for server-class equipment.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-5-04',
    topicId: 'topic-c2-4-5',
    type: 'single_choice',
    stem: 'A power surge damages a surge protector connected to a workstation. After replacing the surge protector, the workstation is operational. What important fact about the old surge protector should the technician communicate to the user?',
    choices: ch(
      'The surge protector can be repaired by replacing its fuse',
      'A surge protector that has absorbed its rated joule capacity is no longer providing protection and must be replaced after any significant surge event',
      'Surge protectors automatically reset after a surge and are still protective',
      'Only surge protectors with a red indicator light need replacement after a surge',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Surge protectors are rated in joules — the amount of energy they can absorb. After a major surge event, a surge protector may have consumed its rated capacity. It will still pass power, but the MOVs (Metal Oxide Varistors) inside that absorb spikes may be depleted, providing no protection. Replace any surge protector after a significant surge event regardless of whether it appears to be functioning.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-5-05',
    topicId: 'topic-c2-4-5',
    type: 'single_choice',
    stem: 'Which UPS type provides the best power quality with zero transfer time because power always flows through the inverter from the battery?',
    choices: ch(
      'Standby (offline) UPS',
      'Line-interactive UPS',
      'Online / double-conversion UPS',
      'Surge-only UPS',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'An online (double-conversion) UPS always runs power through the battery/inverter system, providing zero transfer time on power failure and the best power quality. Standby UPS has a 4–8ms transfer delay when switching to battery. Line-interactive UPS uses an autotransformer to regulate voltage but still has a brief switchover time on full failure. Online UPS is preferred for servers and equipment with active PFC power supplies.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-5-06',
    topicId: 'topic-c2-4-5',
    type: 'single_choice',
    stem: 'An old CRT monitor and a laptop with a lithium battery both need to be disposed of. Which disposal method is correct for both?',
    choices: ch(
      'Both can be placed in regular office trash',
      'Both must go to a certified e-waste recycler or manufacturer take-back program — neither can be thrown in regular trash',
      'Only the CRT requires recycling; lithium batteries can go in regular trash',
      'Both items can be donated to charity without any special handling',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'CRT monitors contain several pounds of lead and must go to a certified e-waste recycler. Lithium batteries are regulated for disposal — they cannot go in regular trash due to fire hazard and toxic materials. Lithium batteries should go to retail drop-off locations (Best Buy, Staples, Home Depot) or manufacturer take-back programs. All data storage must be wiped before disposal for security and compliance reasons.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-5-07',
    topicId: 'topic-c2-4-5',
    type: 'single_choice',
    stem: 'Several unused rack unit slots in a server rack have no equipment installed. A data center technician notices the rack is running hotter than others. What airflow management fix should be applied?',
    choices: ch(
      'Add a second CRAC unit to the hot aisle',
      'Install blanking panels in all unused rack unit slots to prevent hot exhaust air from recirculating to the front',
      'Increase the cold aisle supply temperature',
      'Rotate the rack to face the opposite direction',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Blanking panels fill unused rack unit slots to prevent hot exhaust air from recirculating from the rear of the rack to the front intake. Empty slots create a short-circuit path for hot air, warming the intake air and reducing cooling efficiency. Blanking panels are a simple, inexpensive fix that significantly improves rack cooling and is a best practice in any data center.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-5-08',
    topicId: 'topic-c2-4-5',
    type: 'single_choice',
    stem: 'The EU directive that requires manufacturers to take back and recycle electronic products at end of life, and requires retailers to accept old equipment when selling new equivalents, is known as:',
    choices: ch(
      'GDPR',
      'PCI DSS',
      'WEEE Directive',
      'HIPAA',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'The WEEE Directive (Waste Electrical and Electronic Equipment) is the EU regulation that requires manufacturers to take back and recycle products at end of life, and requires retailers to accept old equipment when selling new equivalents. In the US, e-waste is regulated by EPA rules under RCRA for certain materials, and many states have their own mandatory e-waste recycling laws with penalties for non-compliance.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.6 Policies & Licensing (8 questions) ──────────────────────────────────

  {
    id: 'q-c2-4-6-01',
    topicId: 'topic-c2-4-6',
    type: 'single_choice',
    stem: 'An employee is terminated and their personal smartphone, which was enrolled in the company\'s MDM system for work email access, is wiped remotely by IT. The employee complains that personal photos and apps were also erased. What policy should have informed the employee of this risk?',
    choices: ch(
      'Acceptable Use Policy (AUP)',
      'Data Loss Prevention (DLP) policy',
      'BYOD (Bring Your Own Device) policy',
      'Chain of custody policy',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'The BYOD policy governs the use of personally-owned devices to access corporate resources. It should explicitly inform employees that enrolling in MDM grants the organization the ability to perform remote wipe, which may erase personal data alongside corporate data. Employees must understand and accept this risk before enrolling. This is a direct exam scenario for BYOD policy implications.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-6-02',
    topicId: 'topic-c2-4-6',
    type: 'single_choice',
    stem: 'A technician discovers that a workstation has Microsoft Office installed with a product key that is also installed on 15 other machines, violating the single-user license. What is this called?',
    choices: ch(
      'Open source violation',
      'EULA compliance',
      'Software piracy',
      'Volume licensing',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Installing a single-user license on multiple machines is software piracy — making unauthorized copies of software in violation of copyright law and the EULA. This is a criminal offense with civil liability. Legitimate multi-machine deployments use volume licensing (MAK or KMS) or subscription licensing that covers the required number of seats.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-6-03',
    topicId: 'topic-c2-4-6',
    type: 'single_choice',
    stem: 'A user purchases a new laptop and Windows is pre-installed by the manufacturer. The laptop\'s motherboard fails and must be replaced with a different model. Can the Windows license be transferred to the new motherboard configuration?',
    choices: ch(
      'Yes, Windows licenses are always transferable to new hardware',
      'No — this is an OEM license, which is tied to the original hardware and cannot be transferred when the motherboard is replaced',
      'Yes, if the user contacts Microsoft support and explains the situation',
      'Only if the replacement motherboard is from the same manufacturer',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'OEM (Original Equipment Manufacturer) licenses are hardware-bound — they are tied to the specific machine they shipped with and cannot be transferred. Replacing the motherboard with a different model effectively creates a "different computer" and the OEM license does not follow. Retail (FPP) licenses CAN be transferred to new hardware. OEM license portability is a frequently tested A+ exam concept.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-6-04',
    topicId: 'topic-c2-4-6',
    type: 'single_choice',
    stem: 'A large enterprise uses a server on their internal network to activate Windows on all employee workstations without each machine contacting Microsoft\'s activation servers. What activation method is this?',
    choices: ch(
      'MAK (Multiple Activation Key)',
      'EULA activation',
      'OEM bundling',
      'KMS (Key Management Service)',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'KMS (Key Management Service) is an on-premises activation server that activates Windows machines within the organization without requiring internet access to Microsoft. Machines must check in with the KMS server every 180 days to renew activation. This is the preferred method for large enterprise environments. MAK uses a single key with a fixed number of activations validated against Microsoft\'s servers — suitable for smaller deployments.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-6-05',
    topicId: 'topic-c2-4-6',
    type: 'single_choice',
    stem: 'Which open source license requires that any software derived from or incorporating the licensed code must also be released under the same license, preventing inclusion in proprietary software?',
    choices: ch(
      'MIT License',
      'Apache 2.0 License',
      'GNU GPL (General Public License)',
      'BSD License',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'The GNU GPL (General Public License) is a copyleft license requiring that derivatives must also be released under the GPL — they cannot be incorporated into proprietary software. This is called "copyleft." MIT and Apache 2.0 are permissive licenses that allow use, modification, and redistribution including in proprietary software (with certain attribution requirements). Apache 2.0 also includes a patent grant.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-6-06',
    topicId: 'topic-c2-4-6',
    type: 'single_choice',
    stem: 'A technician discovers what appears to be illegal content on a company device while performing routine maintenance. What is the correct action?',
    choices: ch(
      'Delete the content immediately to protect the company from liability',
      'Continue investigating the device to gather more evidence before reporting',
      'Document what was observed, preserve the device in its current state, and immediately report up the escalation chain',
      'Confront the device owner directly and ask for an explanation',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A+ technicians are not investigators. When potential illegal content or policy violations are discovered, the correct response is: document what was observed, do NOT continue using or altering the device, do NOT delete anything, and immediately report up the escalation chain (supervisor → IT security → HR → legal → law enforcement if needed). Deleting content or investigating independently could compromise a legal investigation and violate chain of custody.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-6-07',
    topicId: 'topic-c2-4-6',
    type: 'single_choice',
    stem: 'Which regulation specifically governs the handling of protected health information (PHI) by healthcare providers and their business associates in the United States?',
    choices: ch(
      'GDPR',
      'FERPA',
      'PCI DSS',
      'HIPAA',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'HIPAA (Health Insurance Portability and Accountability Act) governs the handling of protected health information (PHI) by healthcare providers, insurers, and their business associates in the US. GDPR covers EU personal data broadly. FERPA covers student education records at institutions receiving federal funding. PCI DSS governs payment card data globally for any entity processing card transactions.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-6-08',
    topicId: 'topic-c2-4-6',
    type: 'single_choice',
    stem: 'A company\'s DLP (Data Loss Prevention) system blocks an employee from emailing a file containing 16-digit numbers formatted like credit card numbers to an external address. What DLP control is this an example of?',
    choices: ch(
      'USB port blocking',
      'Print controls',
      'Email scanning with data classification rules',
      'Network DLP with deep packet inspection',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Email scanning DLP inspects outbound email for sensitive data patterns such as SSNs, credit card number formats, or proprietary keywords, and blocks or quarantines suspicious messages. DLP systems must be configured with data classification rules — patterns that define what "sensitive" looks like (e.g., 16-digit credit card format, 9-digit SSN format). This is a DLP email scanning control.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.7 Professionalism (8 questions) ───────────────────────────────────────

  {
    id: 'q-c2-4-7-01',
    topicId: 'topic-c2-4-7',
    type: 'single_choice',
    stem: 'A frustrated user calls the help desk and starts venting about how the IT department never fixes anything properly. What is the FIRST action the technician should take?',
    choices: ch(
      'Interrupt the user to clarify the technical issue immediately',
      'Let the user vent fully without interrupting, remain calm, and then acknowledge their frustration before transitioning to problem-solving',
      'Transfer the call to a supervisor to avoid escalation',
      'Apologize and admit the IT department made a mistake',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'When handling a difficult or frustrated user, the first step is to allow them to vent completely without interruption. Users need to feel heard before they can shift to problem-solving mode. After they finish, acknowledge and empathize without admitting fault: "I understand this has been really disruptive." Do not argue, do not match their frustration, and do not transfer prematurely. Then transition to clarifying the problem.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-7-02',
    topicId: 'topic-c2-4-7',
    type: 'single_choice',
    stem: 'While working on a user\'s computer, the technician\'s personal cell phone rings. What is the professionally correct response?',
    choices: ch(
      'Answer the call quickly since it will only take a moment',
      'Let it go to voicemail — personal calls should not be answered during a support interaction with a user',
      'Ask the user if it is okay to take the call briefly',
      'Step out of the room to answer the call without telling the user',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Personal calls, text messages, and other personal interruptions should not occur during a support interaction. The user in front of you deserves your full attention. The technician should silence their phone before beginning any user-facing work and let calls go to voicemail. This is a direct CompTIA A+ exam topic — personal interruptions during customer interaction are unprofessional and signal that the user\'s issue is not a priority.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-7-03',
    topicId: 'topic-c2-4-7',
    type: 'single_choice',
    stem: 'A technician tells a user: "Your DIMM is failing and you\'re experiencing memory-related BSoDs due to bad sectors." The user looks confused. What communication principle did the technician violate?',
    choices: ch(
      'Active listening',
      'Proper escalation',
      'Avoiding technical jargon when speaking with end users',
      'Setting expectations',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Technical jargon such as "DIMM," "BSoD," and "bad sectors" is appropriate when communicating with IT colleagues but confusing to end users. When speaking with non-technical users, technicians should use plain language: "Your computer\'s memory is going bad and it\'s causing crashes — we need to replace it." Note that "bad sectors" is a hard drive issue, not memory, making the original statement doubly problematic.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-7-04',
    topicId: 'topic-c2-4-7',
    type: 'single_choice',
    stem: 'A technician resolves a user\'s issue and closes the ticket. The next day, the same issue recurs for the user. What practice would BEST have prevented the user from feeling abandoned?',
    choices: ch(
      'Leaving the ticket open for one week before closing',
      'Following up after resolution to confirm the user is satisfied and to catch any lingering issues before they escalate',
      'Escalating all issues to senior technicians to ensure better resolution',
      'Requiring the user to sign off on the resolution before the ticket closes',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Following up after resolution — a brief email or callback the next day — confirms the user is satisfied, catches any recurrence before it becomes a new incident, and builds trust and goodwill. This is a professionalism best practice the A+ exam tests. It also demonstrates genuine commitment to service rather than just closing tickets as fast as possible.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-7-05',
    topicId: 'topic-c2-4-7',
    type: 'single_choice',
    stem: 'A technician begins investigating a user\'s email account during a support call and notices a private message on screen. What is the correct action?',
    choices: ch(
      'Read the message since access to the account was authorized for the support call',
      'Take a screenshot of the message as documentation',
      'Avoid reading beyond what is necessary to solve the problem and do not mention or share what was inadvertently seen',
      'Inform the user that their private messages were visible during the session',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Technicians routinely have access to sensitive personal information during support interactions. The professional obligation is to not read personal files, emails, or documents beyond what is strictly necessary to solve the problem. If sensitive information is inadvertently seen, it should not be mentioned, shared, or used. Confidentiality is both an ethical obligation and often a legal requirement.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-7-06',
    topicId: 'topic-c2-4-7',
    type: 'single_choice',
    stem: 'A user reports that their issue will affect a major presentation in two hours. The technician does not yet know how long the fix will take. What is the professionally correct response?',
    choices: ch(
      'Tell the user "no problem, we\'ll have it fixed in time" to reduce their anxiety',
      'Say nothing until you have a firm estimate to avoid creating false expectations',
      'Set a realistic expectation even if uncertain — communicate what you know now and commit to providing an update by a specific time',
      'Escalate immediately to a senior technician without explaining the situation to the user',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Uncertainty causes the most user frustration — not the problem itself. When you do not have a firm estimate, the correct approach is to communicate what you know and commit to a follow-up: "I\'m investigating now and will have a diagnosis for you within 30 minutes. I understand the timeline is critical." Making promises you cannot keep ("we\'ll have it fixed in time") destroys trust when those promises are not met. Proactive communication preserves trust even when the news is not good.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-7-07',
    topicId: 'topic-c2-4-7',
    type: 'single_choice',
    stem: 'A technician encounters a problem that is beyond their technical skill level. What is the correct escalation behavior?',
    choices: ch(
      'Continue attempting to resolve it to avoid looking incompetent',
      'Tell the user the issue cannot be fixed',
      'Document all steps already tried, brief the next-tier technician, and inform the user who will handle it and when',
      'Close the ticket and ask the user to submit a new one',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Knowing when and how to escalate is a professional skill — not a failure. Proper escalation involves: documenting everything already tried, contacting the next-tier technician or appropriate team before the handoff with a full brief (user, issue, steps tried, findings), and informing the user who will handle it and by when. Never leave the user without knowing what happens next.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-7-08',
    topicId: 'topic-c2-4-7',
    type: 'single_choice',
    stem: 'After completing a repair, the technician tells the user: "Everything is fixed. Let me know if it happens again." What important step did the technician skip?',
    choices: ch(
      'Updating the CMDB with the new component information',
      'Verifying resolution with the user by confirming everything is working as expected before leaving',
      'Filing a post-implementation review with the CAB',
      'Creating a knowledge base article about the repair',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Before closing any support interaction, the technician should verify resolution by asking the user to confirm everything is working — "Is everything working the way it should now?" Do not assume it is fixed because you believe you fixed it. Additionally, the technician should explain what was done in plain language and provide any preventive education. Assuming it is fixed without verification risks the issue recurring without a chance to address it immediately.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.8 Scripting (8 questions) ─────────────────────────────────────────────

  {
    id: 'q-c2-4-8-01',
    topicId: 'topic-c2-4-8',
    type: 'single_choice',
    stem: 'An IT administrator needs to create 500 new user accounts in Active Directory from a CSV file. Which scripting tool is best suited for this task?',
    choices: ch(
      'VBScript (.vbs)',
      'Bash (.sh)',
      'Python (.py)',
      'PowerShell (.ps1)',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'PowerShell is the primary scripting platform for Windows administration with deep integration into Active Directory. The New-ADUser cmdlet combined with Import-Csv and a ForEach loop can create hundreds of accounts from a CSV in seconds. PowerShell\'s object-oriented pipeline and AD modules make it the definitive tool for Active Directory automation tasks.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-8-02',
    topicId: 'topic-c2-4-8',
    type: 'single_choice',
    stem: 'A Linux server administrator needs to schedule a backup script to run automatically every night at 2:00 AM. Which scheduling mechanism should be used?',
    choices: ch(
      'Windows Task Scheduler',
      'PowerShell scheduled jobs',
      'Cron job (crontab)',
      'Python\'s schedule library',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Cron is the standard scheduler for Linux/Unix systems. Scripts are scheduled by editing the crontab with `crontab -e`. The cron entry `0 2 * * * /scripts/backup.sh` runs the backup script at 2:00 AM every day. Cron runs unattended and is built into every Linux system. Windows Task Scheduler is the Windows equivalent. PowerShell scheduled jobs are Windows-specific.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-8-03',
    topicId: 'topic-c2-4-8',
    type: 'single_choice',
    stem: 'A technician needs to write a cross-platform script that connects to multiple network switches via SSH and pulls configuration data from a REST API. Which scripting language is BEST suited for this task?',
    choices: ch(
      'VBScript',
      'Python with libraries such as Paramiko/Netmiko and requests',
      'PowerShell',
      'Bash',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Python is the best choice for cross-platform network automation involving SSH connections and REST API interaction. The Paramiko and Netmiko libraries handle SSH connections to network devices, while the requests library handles REST API calls. Python runs identically on Windows, macOS, and Linux, and has the most comprehensive ecosystem of networking and automation libraries. VBScript is Windows-only and legacy.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-8-04',
    topicId: 'topic-c2-4-8',
    type: 'single_choice',
    stem: 'A technician tries to run a PowerShell script on a new Windows workstation and receives an error: "running scripts is disabled on this system." What setting controls this behavior?',
    choices: ch(
      'User Account Control (UAC)',
      'PowerShell execution policy',
      'Windows Defender script protection',
      'NTFS permissions on the script file',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'PowerShell\'s execution policy controls whether scripts can run. The default on new installations is "Restricted," which prevents all scripts from running. The policy can be checked with `Get-ExecutionPolicy` and changed with `Set-ExecutionPolicy RemoteSigned` (requires admin rights). RemoteSigned allows local scripts to run unsigned while requiring downloaded scripts to be signed by a trusted publisher.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-8-05',
    topicId: 'topic-c2-4-8',
    type: 'single_choice',
    stem: 'Which scripting language uses the file extension .vbs and is considered a legacy Windows automation language largely replaced by PowerShell on modern systems?',
    choices: ch(
      'Python',
      'Bash',
      'VBScript',
      'JavaScript',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'VBScript (.vbs) is a legacy Windows scripting language that was once common for Windows automation and login scripts. It has been largely replaced by PowerShell on modern Windows systems. VBScript was also commonly used in early malware. The A+ exam may reference VBScript in the context of legacy environments. It is not used for new development.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-8-06',
    topicId: 'topic-c2-4-8',
    type: 'single_choice',
    stem: 'In a PowerShell script, what is the purpose of the `ForEach` loop construct?',
    choices: ch(
      'It defines a reusable block of code that can be called with different parameters',
      'It executes a block of code repeatedly for each item in a collection',
      'It evaluates a condition and executes different code paths based on the result',
      'It handles errors when a command fails',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A loop (ForEach/for/while) repeats a block of code for each item in a collection or while a condition is true. In PowerShell, `ForEach ($user in $users) { New-ADUser ... }` creates an AD account for each user in the $users collection. Functions are reusable named code blocks. Conditionals (if/else) execute different paths based on a condition. Error handling (try/catch) manages failures.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-8-07',
    topicId: 'topic-c2-4-8',
    type: 'single_choice',
    stem: 'A technician needs to parse a 500 MB log file to extract all lines containing the word "ERROR" and count occurrences by error type. Which scripting tool is best for this task?',
    choices: ch(
      'PowerShell',
      'VBScript',
      'Python',
      'Bash with basic commands',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Python excels at log file parsing and data processing. Its file handling, string operations, and data structures make it ideal for reading large text files, filtering lines by pattern, and aggregating counts. Python is cross-platform and handles large files efficiently. While PowerShell and Bash can also parse logs, Python is considered the best tool for complex log analysis, especially when the results need further processing or reporting.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-8-08',
    topicId: 'topic-c2-4-8',
    type: 'single_choice',
    stem: 'What is the first line in a Bash script called, and what does `#!/bin/bash` specify?',
    choices: ch(
      'A comment line that explains the script\'s purpose',
      'A shebang line that tells the OS which interpreter to use to run the script',
      'A variable declaration for the script path',
      'A function definition for the main execution block',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'The shebang line (`#!`) is the first line of a script and tells the operating system which interpreter to use. `#!/bin/bash` means use the Bash interpreter at /bin/bash, even if the user\'s default shell is something different (like zsh or sh). Without the shebang, the OS may use the wrong interpreter, causing the script to fail or behave unpredictably.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.9 Remote Access (8 questions) ─────────────────────────────────────────

  {
    id: 'q-c2-4-9-01',
    topicId: 'topic-c2-4-9',
    type: 'single_choice',
    stem: 'A Windows administrator wants to remotely manage a Windows Server from their Windows 10 workstation using a full graphical desktop session. Which protocol and port should be used?',
    choices: ch(
      'VNC on TCP port 5900',
      'SSH on TCP port 22',
      'RDP on TCP port 3389',
      'Telnet on TCP port 23',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'RDP (Remote Desktop Protocol) provides full graphical desktop access to remote Windows machines, operating on TCP port 3389. It is built into Windows and accessed via the Remote Desktop Connection client (mstsc.exe). The remote host must run Windows Pro, Enterprise, or Server — Windows Home does not support incoming RDP connections. VNC on port 5900 is cross-platform but less efficient for Windows-to-Windows.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-9-02',
    topicId: 'topic-c2-4-9',
    type: 'single_choice',
    stem: 'A Linux server administrator needs to securely manage a remote Linux server over the internet using command-line access. Which protocol should be used?',
    choices: ch(
      'RDP (port 3389)',
      'Telnet (port 23)',
      'SSH (port 22)',
      'VNC (port 5900)',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'SSH (Secure Shell) on TCP port 22 provides encrypted terminal (command-line) access to remote Linux and Unix systems. SSH is the standard for Linux server management and network device configuration. Telnet provides no encryption — all data including passwords are transmitted in plaintext and should never be used over the internet. RDP provides GUI access and is Windows-centric. VNC provides GUI access but lacks built-in encryption.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-9-03',
    topicId: 'topic-c2-4-9',
    type: 'single_choice',
    stem: 'An IT security team recommends against exposing RDP (port 3389) directly to the internet. What is the recommended alternative that protects RDP access?',
    choices: ch(
      'Change RDP to use port 80 to appear as web traffic',
      'Require VPN access first, then RDP to the machine\'s internal IP address',
      'Enable Windows Firewall on the RDP host',
      'Use VNC instead since it uses a different port',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Exposing RDP (port 3389) directly to the internet is one of the most common attack vectors for ransomware and brute-force attacks. The recommended approach is to require VPN first — the user connects to the VPN, then RDPs to the machine\'s internal IP. The internet only sees encrypted VPN traffic; port 3389 is never exposed publicly. Microsoft\'s RD Gateway (which proxies RDP over HTTPS port 443) is another valid alternative.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-9-04',
    topicId: 'topic-c2-4-9',
    type: 'single_choice',
    stem: 'A help desk technician uses a tool that allows them to see and control a remote user\'s screen without needing to configure firewall rules, by relaying the connection through the vendor\'s cloud servers. Which category of tool is this?',
    choices: ch(
      'RDP with Network Level Authentication',
      'Third-party remote support tool (such as TeamViewer or AnyDesk)',
      'VNC with SSH tunneling',
      'RMM platform',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Third-party remote support tools like TeamViewer and AnyDesk work through NAT and firewalls by making outbound connections to the vendor\'s relay servers — no inbound port configuration is required. They are designed for ad-hoc support scenarios and are optimized for ease of use. The remote user runs a small client and shares an ID/password. This is distinct from RMM platforms, which are fleet management tools for MSPs.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-9-05',
    topicId: 'topic-c2-4-9',
    type: 'single_choice',
    stem: 'What is the primary security concern with using standard VNC without any additional configuration over an untrusted network?',
    choices: ch(
      'VNC uses excessive bandwidth compared to RDP',
      'Basic VNC uses minimal or no encryption, transmitting screen data and credentials in cleartext',
      'VNC requires a commercial license for business use',
      'VNC is incompatible with Windows operating systems',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Basic VNC (using the RFB protocol) uses minimal or no encryption by default. Screen contents and authentication credentials can be captured by an attacker with network access. The recommended approach for VNC over untrusted networks is to tunnel the connection over SSH, which adds encryption. RDP has built-in TLS encryption. VNC operates on TCP port 5900 and is cross-platform (Windows, macOS, Linux).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-9-06',
    topicId: 'topic-c2-4-9',
    type: 'single_choice',
    stem: 'An MSP (Managed Service Provider) needs a platform to monitor CPU, memory, and disk health across 500 client endpoints, deploy patches automatically, and run scripts remotely on all managed devices simultaneously. What type of tool should they use?',
    choices: ch(
      'TeamViewer for each endpoint',
      'SSH access to each endpoint',
      'RMM (Remote Monitoring and Management) platform',
      'Windows Remote Assistance',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'RMM (Remote Monitoring and Management) platforms are designed for MSPs and IT departments to manage large device fleets. Key capabilities include real-time health monitoring, automated alerting, patch management across all endpoints, remote script execution on hundreds of machines simultaneously, asset inventory, and integrated remote access. Common platforms include ConnectWise Automate, NinjaRMM, Datto RMM, and Kaseya VSA.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-9-07',
    topicId: 'topic-c2-4-9',
    type: 'single_choice',
    stem: 'A remote worker\'s VPN is configured in "split tunnel" mode. What does this mean for their internet traffic?',
    choices: ch(
      'All traffic — both corporate and internet — routes through the VPN',
      'Only corporate-destined traffic goes through the VPN; internet traffic goes directly to the internet',
      'The VPN connection is split across two ISPs for redundancy',
      'Corporate traffic is encrypted but internet traffic is not',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Split tunnel VPN sends only traffic destined for corporate networks through the VPN tunnel; internet traffic goes directly to the internet without going through the corporate infrastructure. This improves performance and reduces corporate bandwidth consumption. Full tunnel routes ALL traffic through the VPN, allowing corporate security tools to inspect all traffic. Split tunnel is a security risk because internet traffic bypasses corporate security controls.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-9-08',
    topicId: 'topic-c2-4-9',
    type: 'single_choice',
    stem: 'A user needs to securely copy files from their local machine to a remote Linux server. Which protocol should be used instead of FTP to ensure the transfer is encrypted?',
    choices: ch(
      'FTPS',
      'SFTP (SSH File Transfer Protocol)',
      'Telnet file transfer',
      'SMB over port 445',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'SFTP (SSH File Transfer Protocol) runs over SSH on port 22 and provides encrypted file transfer. It is not the same as FTP or FTPS. SCP (Secure Copy) is another SSH-based file transfer option. Both SFTP and SCP are standard for secure file transfers to Linux/Unix servers. FTP transmits data and credentials in plaintext. FTPS adds TLS to FTP but is more complex to configure through firewalls.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.10 Artificial Intelligence (8 questions) ──────────────────────────────

  {
    id: 'q-c2-4-10-01',
    topicId: 'topic-c2-4-10',
    type: 'single_choice',
    stem: 'An LLM-based AI assistant confidently provides a PowerShell command to a technician. The technician runs it on a production server and the command fails, causing an outage. The AI fabricated the command. What AI concept describes this behavior?',
    choices: ch(
      'AI bias',
      'Hallucination',
      'Supervised learning error',
      'Reinforcement learning failure',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'AI hallucination occurs when an LLM generates text that sounds correct and authoritative but is factually inaccurate or entirely fabricated. LLMs are optimized to generate plausible text, not to access verified facts. Hallucinated output can include fabricated commands, non-existent documentation, incorrect procedures, or made-up CVEs. AI output should always be verified against official documentation before implementation in production.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-10-02',
    topicId: 'topic-c2-4-10',
    type: 'single_choice',
    stem: 'A technician uses a public AI chatbot to help troubleshoot a HIPAA-covered patient database issue. They paste a sample of patient records into the chat to give the AI context. What policy concern does this raise?',
    choices: ch(
      'No concern — AI tools are covered under IT support exceptions to HIPAA',
      'A concern only if the AI tool is not certified by the vendor',
      'Entering PHI into public AI tools may expose sensitive data beyond the technician\'s control and violate HIPAA and privacy regulations',
      'A minor concern that can be addressed by deleting the chat history after the session',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Entering PHI (Protected Health Information), PII, proprietary code, or confidential business data into public AI tools (ChatGPT, Gemini, Claude in free tier) is a serious policy and compliance violation. Many public AI services use user inputs to improve their models. This may expose sensitive data beyond your control and violate HIPAA, GDPR, or CCPA. Data should be anonymized or sanitized before input. Enterprise-tier AI tools with contractual data protection commitments should be used for sensitive work.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-10-03',
    topicId: 'topic-c2-4-10',
    type: 'single_choice',
    stem: 'An IT support organization deploys an AI chatbot on their help desk portal that handles password resets, account unlocks, and FAQ answers without human involvement. What tier of support does this represent?',
    choices: ch(
      'Tier 1 support',
      'Tier 2 support',
      'Tier 0 (self-service) support',
      'Tier 3 support',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'AI-powered chatbots that handle routine requests without human involvement represent Tier-0 (self-service) support. They are available 24/7 with no staffing cost and handle the high volume of simple requests (password resets, account unlocks, status updates, FAQ answers, ticket creation) that would otherwise consume Tier-1 help desk capacity. This frees human agents to handle more complex issues requiring judgment.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-10-04',
    topicId: 'topic-c2-4-10',
    type: 'single_choice',
    stem: 'Which machine learning training type trains a model on examples that include both the input data and the correct answer labels?',
    choices: ch(
      'Unsupervised learning',
      'Reinforcement learning',
      'Supervised learning',
      'Transfer learning',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Supervised learning trains a model on labeled data — each training example includes the input and the correct answer. Example: a spam filter trained on emails labeled "spam" or "not spam." Unsupervised learning finds patterns without labeled answers (e.g., clustering similar support tickets). Reinforcement learning trains via rewards and penalties (e.g., AI that learns chess by winning or losing games).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-10-05',
    topicId: 'topic-c2-4-10',
    type: 'single_choice',
    stem: 'An endpoint security platform detects a new type of malware that has no known signature in its database, based only on behavioral patterns. Which AI concept enables this capability?',
    choices: ch(
      'LLM-based text generation',
      'AI hallucination detection',
      'ML-based behavioral analysis that identifies malware behavior patterns rather than relying on known signatures',
      'Supervised learning with static signature databases',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Modern endpoint security tools use ML-based behavioral analysis to detect threats by identifying suspicious behavior patterns rather than relying solely on known malware signatures. This enables detection of zero-day malware and fileless malware that have no signatures in traditional databases. The model is trained on normal and malicious behavioral patterns and can identify new threats exhibiting similar malicious behaviors.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-10-06',
    topicId: 'topic-c2-4-10',
    type: 'single_choice',
    stem: 'GPT-4, Claude, and Gemini are examples of what type of AI model?',
    choices: ch(
      'Expert systems',
      'Large Language Models (LLMs)',
      'Convolutional Neural Networks (CNNs)',
      'Supervised classification models',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'GPT-4 (ChatGPT), Claude (Anthropic), Gemini (Google), Llama (Meta), and Microsoft Copilot are all Large Language Models (LLMs) — a specific type of ML model trained on massive amounts of text data. LLMs learn statistical patterns of language and can perform a wide range of tasks from a text prompt with no task-specific fine-tuning: answering questions, writing, summarizing, coding, and translation.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-10-07',
    topicId: 'topic-c2-4-10',
    type: 'single_choice',
    stem: 'A network security team deploys an AI system that establishes what "normal" network traffic looks like and automatically flags connections to unknown IP addresses and unusual data transfer volumes. What AI application is this?',
    choices: ch(
      'Ticket routing and classification',
      'Predictive hardware failure analysis',
      'AI-powered anomaly detection for security monitoring',
      'AI chatbot for user self-service',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'AI-powered anomaly detection for security establishes a baseline of normal network behavior (typical login times, normal data transfer volumes, known outbound connections) and flags deviations. This enables detection of threats that don\'t trigger signature-based rules — unusual login times, unexpected data exfiltration, new outbound connections to unknown IPs. AI can respond automatically by quarantining devices or blocking processes faster than any human.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-4-10-08',
    topicId: 'topic-c2-4-10',
    type: 'single_choice',
    stem: 'Which statement BEST describes the key difference between scripting/automation and AI-based approaches in IT operations?',
    choices: ch(
      'Scripts are always faster than AI for any task',
      'AI requires no training data and works immediately on any problem',
      'Scripts follow explicit hand-written rules and are predictable; AI learns patterns from data and can handle ambiguous or novel situations but is less predictable',
      'AI replaces scripting entirely in modern IT environments',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Scripting/automation follows explicit hand-written rules — predictable, deterministic, but fails on inputs it was not written to handle and requires manual updates. AI/ML learns patterns from data — can handle ambiguous or novel inputs and improves with more data, but may behave unexpectedly and is less predictable. The approaches complement each other: AI classifies and prioritizes tickets while scripting executes the resulting automated actions.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

]
