// CompTIA A+ 220-1201 Practice Questions — Batch 2
// Core 1 Domain 4: Virtualization and Cloud Computing (topics 4.1–4.2)
// Core 1 Domain 5: Hardware and Network Troubleshooting (topics 5.1–5.6)
// 8 questions per topic × 8 topics = 64 questions total

const NOW = new Date().toISOString()

type Choice = { id: string; text: string; isCorrect: boolean }

function ch(a: string, b: string, c: string, d: string, correct: 'a' | 'b' | 'c' | 'd'): string {
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: correct === 'a' },
    { id: 'b', text: b, isCorrect: correct === 'b' },
    { id: 'c', text: c, isCorrect: correct === 'c' },
    { id: 'd', text: d, isCorrect: correct === 'd' },
  ] as Choice[])
}

function chMulti(a: string, b: string, c: string, d: string, correct: Array<'a' | 'b' | 'c' | 'd'>): string {
  const ids = new Set(correct)
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: ids.has('a') },
    { id: 'b', text: b, isCorrect: ids.has('b') },
    { id: 'c', text: c, isCorrect: ids.has('c') },
    { id: 'd', text: d, isCorrect: ids.has('d') },
  ] as Choice[])
}

const ca = (id: 'a' | 'b' | 'c' | 'd') => JSON.stringify(id)
const cam = (...ids: Array<'a' | 'b' | 'c' | 'd'>) => JSON.stringify(ids)

export const BATCH2_QUESTIONS = [

  // ─── 4.1 Virtualization Concepts (8 questions) ────────────────────────────

  {
    id: 'q-c1-4-1-01',
    topicId: 'topic-c1-4-1',
    type: 'single_choice',
    stem: 'Which type of hypervisor runs directly on the physical hardware with no host operating system underneath it?',
    choices: ch('Type 2 hypervisor', 'Type 1 hypervisor', 'Hosted hypervisor', 'Container runtime', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A Type 1 hypervisor (also called a bare-metal hypervisor) runs directly on the physical hardware with no underlying host OS. Examples include VMware ESXi, Microsoft Hyper-V, KVM, and Xen. Because there is no host OS overhead, Type 1 hypervisors deliver higher performance and are used in enterprise data centers. Type 2 (hosted) hypervisors run as applications on top of a host OS.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-02',
    topicId: 'topic-c1-4-1',
    type: 'single_choice',
    stem: 'A developer wants to run Windows virtual machines on their macOS laptop alongside other applications. Which hypervisor type is most appropriate for this use case?',
    choices: ch('Type 1 — VMware ESXi', 'Type 1 — Microsoft Hyper-V', 'Type 2 — VMware Fusion', 'Type 2 — KVM', 'c'),
    correctAnswer: ca('c'),
    explanation: 'VMware Fusion is a Type 2 (hosted) hypervisor that runs as an application on top of macOS, making it ideal for a developer who needs to run Windows VMs while continuing to use their Mac for other work. Type 1 hypervisors like ESXi require dedicated hardware with no general-purpose OS. KVM is a Linux-based solution, not macOS. Type 2 is the correct category for desktop development use.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-03',
    topicId: 'topic-c1-4-1',
    type: 'single_choice',
    stem: 'A technician attempts to create a 64-bit virtual machine and receives the error "VT-x is not available." What is the MOST LIKELY cause and fix?',
    choices: ch('The host CPU does not support 64-bit processing; replace the CPU', 'CPU virtualization extensions are disabled in BIOS/UEFI; enable Intel VT-x in BIOS setup', 'The virtual disk format is incompatible; convert to VMDK', 'The guest OS ISO is corrupted; re-download the image', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The error "VT-x is not available" means Intel Virtualization Technology (VT-x) is disabled in the system\'s BIOS/UEFI settings. Modern CPUs support virtualization but many motherboards ship with the feature disabled by default. The fix is to reboot, enter BIOS/UEFI setup (typically Del or F2), navigate to CPU Configuration, and enable Intel Virtualization Technology (or AMD-V / SVM Mode for AMD systems), then save and exit.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-04',
    topicId: 'topic-c1-4-1',
    type: 'single_choice',
    stem: 'A VM is configured in NAT networking mode. Which of the following accurately describes the network behavior?',
    choices: ch('The VM receives its own IP address from the physical network DHCP server and is visible to all other devices on the LAN', 'The VM can only communicate with other VMs on the same host; it has no internet access', 'The VM shares the host\'s IP address and can access the internet, but external devices cannot initiate connections to the VM', 'The VM can communicate with the host only and is completely isolated from the physical network', 'c'),
    correctAnswer: ca('c'),
    explanation: 'In NAT mode, the hypervisor performs Network Address Translation — the VM shares the host\'s public/LAN IP address to communicate outbound to the internet. The hypervisor\'s built-in DHCP gives the VM a private IP, but external devices on the network cannot initiate connections to the VM without explicit port forwarding. Bridged mode gives the VM its own IP visible on the LAN. Host-only restricts to host communication. Internal network isolates VMs from the host.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-05',
    topicId: 'topic-c1-4-1',
    type: 'single_choice',
    stem: 'Before applying a potentially risky software update to a production virtual machine, a technician wants to create a restore point. Which virtualization feature is BEST suited for this purpose?',
    choices: ch('Thin provisioning', 'VM snapshot', 'VM migration (vMotion)', 'OVA export', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A VM snapshot captures the complete state of a virtual machine at a point in time — including RAM contents, disk state, and configuration. If the update causes problems, the technician can instantly revert to the snapshot. Thin provisioning is a disk allocation strategy. VM migration (vMotion) moves a running VM between hosts. An OVA export is a full backup but is slower and intended for archiving or moving VMs, not quick rollback.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-06',
    topicId: 'topic-c1-4-1',
    type: 'single_choice',
    stem: 'Which virtual disk format is used natively by VMware products and has the file extension .vmdk?',
    choices: ch('VHD', 'QCOW2', 'VMDK', 'VHDX', 'c'),
    correctAnswer: ca('c'),
    explanation: 'VMDK (Virtual Machine Disk) is VMware\'s native virtual disk format, used by VMware Workstation, Fusion, and ESXi. VHD is the older Microsoft Hyper-V format. VHDX is the improved Microsoft format supporting up to 64 TB with better performance. QCOW2 is the QEMU/KVM format that supports snapshots and compression.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-07',
    topicId: 'topic-c1-4-1',
    type: 'single_choice',
    stem: 'How do containers differ from virtual machines in terms of OS architecture?',
    choices: ch('Containers include a full guest OS kernel and user space, making them more isolated than VMs', 'Containers share the host OS kernel and are isolated at the OS process level, making them lighter than VMs', 'Containers require a Type 1 hypervisor to run, while VMs can run on either Type 1 or Type 2', 'Containers are slower to start than VMs because they must load a complete operating system', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Containers (such as Docker containers) share the host OS kernel and are isolated using OS-level namespaces and cgroups. They do not include a full guest OS, which makes them much lighter (MBs vs GBs) and faster to start (milliseconds vs seconds). VMs each run a full guest OS with their own kernel, providing stronger isolation at the hardware level via the hypervisor. The tradeoff is that a kernel exploit on the host could affect all containers, while VMs are isolated at the hardware level.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-08',
    topicId: 'topic-c1-4-1',
    type: 'single_choice',
    stem: 'A technician creates a 200 GB virtual disk but only 5 GB of actual data is stored on it. The disk consumes approximately 5 GB of host storage space. Which provisioning method was used?',
    choices: ch('Thick provisioning (eager zeroed)', 'Thick provisioning (lazy zeroed)', 'Thin provisioning', 'Dynamic provisioning with deduplication', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Thin provisioning allocates disk space on demand as data is written, rather than reserving all space upfront. A 200 GB thin-provisioned disk only consumes host storage equal to the data actually written — in this case, approximately 5 GB. Thick provisioning (eager or lazy zeroed) allocates the full 200 GB on the host immediately regardless of how much data the VM has written. Thin provisioning maximizes storage efficiency but can cause problems if the storage pool fills unexpectedly.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 4.2 Cloud Computing (8 questions) ───────────────────────────────────

  {
    id: 'q-c1-4-2-01',
    topicId: 'topic-c1-4-2',
    type: 'single_choice',
    stem: 'A company migrates its on-premises servers to Amazon EC2, managing the operating system, middleware, and applications themselves. Which cloud service model does this represent?',
    choices: ch('SaaS (Software as a Service)', 'PaaS (Platform as a Service)', 'IaaS (Infrastructure as a Service)', 'DaaS (Desktop as a Service)', 'c'),
    correctAnswer: ca('c'),
    explanation: 'IaaS (Infrastructure as a Service) provides virtualized computing resources — servers, storage, and networking. The customer manages the operating system, runtime, middleware, and applications, while the provider manages the physical hardware, virtualization layer, and data center. Amazon EC2, Azure Virtual Machines, and Google Compute Engine are classic IaaS examples. PaaS would abstract away the OS management; SaaS delivers a complete ready-to-use application.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-02',
    topicId: 'topic-c1-4-2',
    type: 'single_choice',
    stem: 'A development team wants to deploy web applications without managing servers or operating systems, focusing only on writing and deploying code. Which cloud service model BEST fits this need?',
    choices: ch('IaaS', 'PaaS', 'SaaS', 'FaaS', 'b'),
    correctAnswer: ca('b'),
    explanation: 'PaaS (Platform as a Service) provides a development and deployment platform — the OS, runtime, and middleware are managed by the provider. Developers only need to write and deploy their application code and manage their data. Examples include AWS Elastic Beanstalk, Google App Engine, Heroku, and Azure App Service. IaaS would still require them to manage the OS. SaaS is a finished application, not a deployment platform.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-03',
    topicId: 'topic-c1-4-2',
    type: 'single_choice',
    stem: 'A healthcare organization must keep patient data on infrastructure it controls exclusively due to HIPAA compliance requirements, but wants cloud-like management capabilities. Which cloud deployment model BEST fits this requirement?',
    choices: ch('Public cloud', 'Community cloud', 'Private cloud', 'Hybrid cloud', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A private cloud provides cloud infrastructure provisioned for exclusive use by a single organization. It can be located on-premise or at a third-party facility but is not shared with other organizations. This gives the healthcare organization full control over data, hardware, and security posture necessary for strict HIPAA compliance. Community cloud is shared among several organizations with common compliance needs. Public cloud uses shared infrastructure. Hybrid cloud combines private and public.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-04',
    topicId: 'topic-c1-4-2',
    type: 'single_choice',
    stem: 'Under the shared responsibility model, which security task is ALWAYS the customer\'s responsibility regardless of whether they use IaaS, PaaS, or SaaS?',
    choices: ch('Patching the operating system', 'Securing the physical data center', 'Protecting customer data and managing user access', 'Managing the hypervisor and virtualization layer', 'c'),
    correctAnswer: ca('c'),
    explanation: 'In the cloud shared responsibility model, the customer is always responsible for their own data classification and protection, as well as identity and access management (user accounts, permissions, MFA) — regardless of the service model. The provider always handles physical data center security and the hypervisor. OS patching is the customer\'s responsibility in IaaS but the provider\'s in PaaS and SaaS. Data protection and IAM remain with the customer at every layer.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-05',
    topicId: 'topic-c1-4-2',
    type: 'single_choice',
    stem: 'Users at a branch office complain that the company\'s cloud-hosted application is very slow. The local internet connection speed test shows 500 Mbps down. Which is the NEXT BEST troubleshooting step?',
    choices: ch('Replace the branch office router with a higher-end model', 'Check the latency from the branch office to the cloud provider\'s region and verify the correct geographic region is selected', 'Upgrade the cloud VM to a larger instance type', 'Configure RAID on the cloud storage volumes', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When bandwidth is adequate but cloud applications are slow, latency is the most likely culprit. High latency to the cloud provider\'s region (especially if the wrong region was selected) causes slow response times even with fast bandwidth. The troubleshooting sequence for slow cloud apps includes: check bandwidth (already done), check latency (ping the cloud region), verify the correct geographic region is selected, and check for proxy/firewall inspection adding overhead. Upgrading the VM instance may help if the application is compute-bound, but latency should be investigated first.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-06',
    topicId: 'topic-c1-4-2',
    type: 'single_choice',
    stem: 'Which NIST cloud characteristic describes the ability to automatically scale resources up during peak demand and release them when demand drops?',
    choices: ch('On-demand self-service', 'Broad network access', 'Rapid elasticity', 'Measured service', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Rapid elasticity is the NIST characteristic that describes the ability to provision and release resources elastically — sometimes automatically — to scale with demand. This is what differentiates cloud from traditional hosting: resources scale up during peak load and scale down (releasing resources and reducing costs) when demand drops. On-demand self-service means users can provision without human interaction. Broad network access means accessible from any device. Measured service means usage is tracked and billed.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-07',
    topicId: 'topic-c1-4-2',
    type: 'single_choice',
    stem: 'A user edited a shared document on two different devices before the cloud storage service synced. The service creates two copies of the file with slightly different names. What is this called?',
    choices: ch('Data deduplication', 'A synchronization conflict', 'A RAID parity error', 'Cache invalidation', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When the same file is edited on two devices before the cloud service has synchronized changes, a synchronization conflict occurs. Most cloud storage services (OneDrive, Dropbox, Google Drive) resolve this by keeping both versions, appending a note to one filename such as "document (John\'s MacBook\'s conflicted copy).docx." The user must then manually merge or choose which version to keep.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-08',
    topicId: 'topic-c1-4-2',
    type: 'single_choice',
    stem: 'An organization runs sensitive workloads on its private on-premises infrastructure but uses AWS to handle spikes in demand during peak seasons. Which cloud deployment model does this describe?',
    choices: ch('Community cloud', 'Public cloud only', 'Private cloud only', 'Hybrid cloud', 'd'),
    correctAnswer: ca('d'),
    explanation: 'A hybrid cloud combines private and public cloud infrastructure. In this scenario, the organization uses its private on-premises infrastructure (private cloud) for sensitive, steady-state workloads and "bursts" to AWS (public cloud) during peak demand — a classic hybrid cloud use case. The two environments remain distinct but are connected for data and workload portability. Community cloud involves multiple organizations sharing infrastructure.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.1 Troubleshoot Motherboards, RAM, CPUs, Power (8 questions) ────────

  {
    id: 'q-c1-5-1-01',
    topicId: 'topic-c1-5-1',
    type: 'single_choice',
    stem: 'A computer is turned on and the fans spin, but there is no display output, no beep codes, and no POST activity. A technician removes all RAM modules and powers the system on — the system now produces a continuous beep. What does this indicate?',
    choices: ch('The CPU has failed and must be replaced', 'The system speaker and POST process are functional; RAM was preventing POST from completing', 'The power supply is failing and should be replaced immediately', 'The CMOS battery is dead; replace it and re-insert the RAM', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When the system produces beep codes after RAM is removed, this confirms the speaker and POST process are working correctly. The original symptom (fans spin, no POST, no beep with RAM installed) indicates the RAM was the likely failure — either a bad module was preventing POST from signaling, or the modules were not properly seated. The technician should now try reseating each module individually, test one stick at a time in the primary DIMM slot, and use MemTest86 to identify any faulty modules.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-1-02',
    topicId: 'topic-c1-5-1',
    type: 'single_choice',
    stem: 'Every time a computer is powered on, it shows the correct time for a few minutes then the clock falls behind, and BIOS settings reset to factory defaults after each cold boot. What is the MOST LIKELY cause?',
    choices: ch('The operating system is corrupted and needs to be reinstalled', 'The CMOS battery is dead and needs to be replaced', 'The power supply is providing insufficient voltage to the motherboard', 'The CPU thermal paste has dried out and the CPU is overheating', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The CMOS battery (typically a CR2032 3V coin cell) powers the real-time clock and maintains BIOS/UEFI settings when the computer is unplugged. Classic symptoms of a dead CMOS battery include: date/time resetting to a default value (e.g., January 1, 2000) after each cold boot, BIOS settings reverting to factory defaults, and a "CMOS checksum error" message during POST. Replacing the CR2032 battery resolves the issue.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-1-03',
    topicId: 'topic-c1-5-1',
    type: 'single_choice',
    stem: 'A workstation runs stably at idle but crashes with a BSOD (MEMORY_MANAGEMENT) only when running video encoding or other memory-intensive tasks. Which tool is BEST for diagnosing this problem?',
    choices: ch('CrystalDiskInfo', 'HWiNFO temperature monitor', 'MemTest86 run from a bootable USB drive', 'Prime95 in CPU-only mode', 'c'),
    correctAnswer: ca('c'),
    explanation: 'MEMORY_MANAGEMENT (0x0000001A) is a Windows BSOD stop code directly indicating faulty RAM. MemTest86 is the gold standard for RAM testing — it boots independently of the OS from a USB drive and runs comprehensive tests of all address lines, data lines, and read/write patterns, detecting both hard and intermittent failures. The crash only under load suggests a RAM cell that fails when thermally stressed. CrystalDiskInfo tests storage health. Prime95 in CPU-only mode stresses the CPU. HWiNFO monitors temperatures.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-1-04',
    topicId: 'topic-c1-5-1',
    type: 'single_choice',
    stem: 'A user reports their gaming PC has become very slow during extended gaming sessions and sometimes shuts off completely. After restarting it is initially fine, then slows down again. What is the MOST LIKELY cause?',
    choices: ch('The PSU wattage is insufficient for the GPU', 'The CPU is thermally throttling due to inadequate cooling', 'A RAM module is failing under load', 'The GPU driver is outdated', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Thermal throttling occurs when a CPU reaches its temperature limit and automatically reduces its clock speed to prevent damage — causing the observed performance slowdown under load. If temperatures exceed the critical threshold, the motherboard\'s thermal protection triggers an automatic shutdown. The system works normally after restart because the CPU has cooled down. Common causes include dried thermal paste, a clogged heatsink, or improper cooler seating. The technician should clean dust from the heatsink, reapply thermal paste, and verify the cooler is fully seated.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-1-05',
    topicId: 'topic-c1-5-1',
    type: 'single_choice',
    stem: 'A technician wants to verify whether a suspect power supply unit can power on independently before reinstalling it in a system. Which test should be performed?',
    choices: ch('Connect the PSU to a multimeter and measure AC input voltage', 'Perform the paperclip test by jumping the green wire to a ground wire on the 24-pin ATX connector', 'Check the PSU fan RPM using a tachometer', 'Run Prime95 with the PSU connected to the motherboard only', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The paperclip test verifies whether a PSU will power on without being connected to a motherboard. The technician disconnects the PSU from all components, finds the 24-pin ATX connector, and bends a paperclip to bridge the green wire (PS_ON, pin 16) to any black wire (ground). Plugging the PSU into the wall should cause its fan to spin, confirming the PSU can power on. Note: this only confirms power-on under no load; a multimeter check of the voltage rails (+12V, +5V, +3.3V) provides more complete verification.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-1-06',
    topicId: 'topic-c1-5-1',
    type: 'single_choice',
    stem: 'A Windows 10 workstation suddenly displays a blue screen with the stop code IRQL_NOT_LESS_OR_EQUAL after a driver update was applied the previous day. What is the BEST first troubleshooting step?',
    choices: ch('Replace the RAM immediately', 'Roll back the recently installed driver using Device Manager', 'Reinstall Windows from scratch', 'Run chkdsk /f on the system drive', 'b'),
    correctAnswer: ca('b'),
    explanation: 'IRQL_NOT_LESS_OR_EQUAL (0x0000000A) indicates a driver or kernel attempted to access memory at an improper IRQL level — commonly caused by a faulty or incompatible driver. Since the BSOD started after a driver update, rolling back the driver (Device Manager → right-click device → Properties → Driver tab → Roll Back Driver) is the most targeted and least disruptive first step. If the rollback resolves the issue, the new driver version is incompatible. RAM replacement and full OS reinstall are escalating steps taken after driver issues are ruled out.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-1-07',
    topicId: 'topic-c1-5-1',
    type: 'single_choice',
    stem: 'A DDR4-3200 RAM kit is installed in a new build but CPU-Z reports the RAM is running at 2133 MHz. The system is stable. What must the technician do to run the RAM at its rated 3200 MHz speed?',
    choices: ch('Return the RAM — it is a defective batch and will not run at rated speed', 'Enable XMP (or EXPO for AMD) in the BIOS/UEFI settings', 'Increase the CPU base clock (BCLK) manually to 150 MHz', 'Install the RAM in slots A1 and B1 instead of A2 and B2', 'b'),
    correctAnswer: ca('b'),
    explanation: 'DDR4 (and DDR5) kits are manufactured to run at their advertised speed (3200 MHz) only when XMP (Extreme Memory Profile for Intel) or EXPO (Extended Profiles for Overclocking for AMD) is enabled in BIOS. By default, all DDR4 RAM runs at the JEDEC baseline speed of 2133 MHz or 2666 MHz regardless of its rated speed, which is why CPU-Z shows 2133 MHz. Enabling XMP/EXPO in BIOS/UEFI automatically configures the correct frequency, voltage, and timings for the RAM kit.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-1-08',
    topicId: 'topic-c1-5-1',
    type: 'single_choice',
    stem: 'A technician observes cylindrical capacitors on a motherboard that have visible bulging at the top and brown residue around their base. The system experiences random reboots. What is the correct action?',
    choices: ch('Clean the capacitors with isopropyl alcohol to remove the residue; the system should stabilize', 'The capacitors have failed (blown capacitors); the motherboard must be repaired or replaced', 'Apply more thermal paste to the CPU heatsink to stop the reboots', 'Update the BIOS firmware to patch the instability issue', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Bulging at the top of cylindrical electrolytic capacitors and brown residue around the base are definitive signs of failed (blown) capacitors. The electrolyte inside has vaporized and the capacitor can no longer maintain proper voltage filtering. This causes system instability including random reboots, failure to POST, and data corruption. Cleaning cannot fix a failed capacitor. The only repair is desoldering and replacing the capacitors (requires skill) or replacing the motherboard entirely.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.2 Troubleshoot Storage & RAID (8 questions) ───────────────────────

  {
    id: 'q-c1-5-2-01',
    topicId: 'topic-c1-5-2',
    type: 'single_choice',
    stem: 'A user reports that their hard drive is making a loud clicking noise that started this morning. What is the MOST appropriate immediate action?',
    choices: ch('Run chkdsk /r to repair bad sectors on the drive', 'Power off the system immediately and do not attempt to use the drive further until data is recovered', 'Defragment the drive to resolve the head alignment issue', 'Update the storage controller driver in Device Manager', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A clicking or ticking sound from an HDD (the "click of death") indicates the read/write head is failing to find or read tracks — a sign of imminent catastrophic failure. Every additional rotation risks further platter damage and overwriting potentially recoverable data. The correct immediate action is to power off the system, then image the drive with a tool like ddrescue or Clonezilla to recover data before the drive fails completely. Running chkdsk or defragmenting a failing drive can cause additional writes that destroy data.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-2-02',
    topicId: 'topic-c1-5-2',
    type: 'single_choice',
    stem: 'CrystalDiskInfo reports a "Caution" status on a drive with a non-zero Reallocated Sectors Count. The drive currently functions normally. What should the technician do?',
    choices: ch('The drive is functioning normally; Caution status is informational only and no action is needed', 'Back up the drive\'s data immediately and plan for drive replacement in the near future', 'Run a full format to clear the reallocated sectors and restore the drive to Good status', 'The S.M.A.R.T. data is inaccurate; reinstall the CrystalDiskInfo software', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A non-zero Reallocated Sectors Count means the drive\'s firmware has remapped bad sectors to spare sectors. While the drive may function normally now, any reallocated sectors are a serious warning sign that the drive is beginning to fail. The spare sector pool is finite — when it is exhausted, read/write errors will surface to the OS. The correct action is to immediately back up all data and plan for drive replacement. A full format cannot clear physical bad sectors; it may hide them temporarily but does not repair them.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-2-03',
    topicId: 'topic-c1-5-2',
    type: 'single_choice',
    stem: 'A server with a four-drive RAID 5 array alerts that one drive has failed. The array is still operational. Which statement BEST describes the current state and correct next action?',
    choices: ch('RAID 5 cannot survive any drive failure; the array has already lost data. Begin full restoration from backup immediately.', 'The array is in degraded mode with no fault tolerance. Replace the failed drive as soon as possible to restore redundancy.', 'The array is operating normally with full redundancy. No action is needed until a second drive fails.', 'The array should be powered off immediately and all drives replaced before any data is lost.', 'b'),
    correctAnswer: ca('b'),
    explanation: 'RAID 5 uses distributed parity and can survive exactly one drive failure. After one drive fails, the array enters degraded mode — it remains operational and data is intact (reconstructed from parity), but there is now zero fault tolerance. If a second drive fails during this degraded period, the entire array fails and all data is lost. The critical action is to replace the failed drive as quickly as possible to allow the RAID controller to rebuild parity and restore full redundancy. RAID 5 rebuild is actually the highest-risk period for data loss.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-2-04',
    topicId: 'topic-c1-5-2',
    type: 'single_choice',
    stem: 'A Windows workstation shows "BOOTMGR is missing" when starting up. The hard drive was recently working. What is the MOST LIKELY fix?',
    choices: ch('Run bootrec /fixmbr from the Windows Recovery Environment to repair the Windows boot manager', 'Replace the hard drive as BOOTMGR errors always indicate physical drive failure', 'Enter BIOS and change the SATA mode from AHCI to IDE', 'Run MemTest86 to check for RAM errors that corrupted BOOTMGR', 'a'),
    correctAnswer: ca('a'),
    explanation: '"BOOTMGR is missing" is the Windows Vista/7/8/10/11 error indicating the Windows Boot Manager file is missing or corrupted on the system partition. The fix is to boot from Windows installation media, enter the Recovery Environment, open the Command Prompt, and run "bootrec /fixmbr" and/or "bootrec /rebuildbcd" to repair the boot configuration. This is a software/boot record issue, not a physical drive failure. Changing SATA mode would cause additional issues. MemTest86 tests RAM, not boot files.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-2-05',
    topicId: 'topic-c1-5-2',
    type: 'single_choice',
    stem: 'Which RAID level provides NO fault tolerance and will result in complete data loss if any single drive fails?',
    choices: ch('RAID 1', 'RAID 5', 'RAID 0', 'RAID 6', 'c'),
    correctAnswer: ca('c'),
    explanation: 'RAID 0 (striping) distributes data across all drives with no parity and no mirroring. Every piece of data requires all drives to reconstruct — if any single drive fails, the entire array\'s data is lost. RAID 0 offers performance benefits (parallel read/write) and full capacity utilization, but provides absolutely no data protection. It is appropriate only for scratch data or caches where speed matters and data loss is acceptable. RAID 1 mirrors data (1 drive failure tolerated), RAID 5 uses parity (1 drive failure tolerated), and RAID 6 uses dual parity (2 drive failures tolerated).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-2-06',
    topicId: 'topic-c1-5-2',
    type: 'single_choice',
    stem: 'An SSD that was working normally is no longer detected by either the BIOS or the operating system after a reboot. No physical changes were made to the system. What is the MOST LIKELY explanation?',
    choices: ch('The SSD has entered read-only mode due to wear, which prevents BIOS detection', 'The SSD controller has failed, causing the drive to disappear from the system entirely', 'A S.M.A.R.T. error was detected; the OS disabled the drive automatically', 'The SATA data cable has failed; replace the cable first', 'd'),
    correctAnswer: ca('d'),
    explanation: 'When an SSD suddenly disappears from both BIOS and OS with no physical changes, the most common physical cause is a failed SATA data cable (SATA cables fail more often than expected) or a loose connection. SSD controller failure can also cause sudden disappearance, but cable failure is the first thing to test because it is the simplest and cheapest fix. Try a different SATA cable and a different SATA port. If the drive still does not appear, the SSD controller has likely failed. SSDs in read-only mode are still detected by BIOS — only writes are blocked.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-2-07',
    topicId: 'topic-c1-5-2',
    type: 'single_choice',
    stem: 'A RAID 10 array consists of four drives: A1, A2 (mirrored pair A), and B1, B2 (mirrored pair B). Drives A1 and A2 both fail simultaneously. What is the result?',
    choices: ch('The array enters degraded mode but remains operational using pair B', 'The array fails completely — all data is lost because an entire mirrored pair has failed', 'The array automatically rebuilds using RAID 5 parity from drives B1 and B2', 'The array can survive this failure because RAID 10 tolerates up to two drive failures', 'b'),
    correctAnswer: ca('b'),
    explanation: 'RAID 10 (stripe of mirrors) survives drive failures only when the failures come from DIFFERENT mirrored pairs. If one drive from each pair fails, the array continues operating (each pair still has one good drive). However, if BOTH drives in the same mirrored pair fail simultaneously (A1 and A2 in this scenario), that pair\'s data is completely unrecoverable — the entire array fails. RAID 10 does not use parity, so pair B cannot reconstruct pair A\'s data. This is the critical vulnerability of RAID 10.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-2-08',
    topicId: 'topic-c1-5-2',
    type: 'single_choice',
    stem: 'A technician is recovering data from a failing HDD that still spins and is partially readable. Which approach is MOST appropriate to maximize data recovery?',
    choices: ch('Run chkdsk /r on the failing drive to repair bad sectors before copying files', 'Use ddrescue or Clonezilla to create a sector-by-sector image of the failing drive to another drive, then recover files from the image', 'Defragment the drive to consolidate readable sectors before attempting recovery', 'Copy important files directly off the failing drive using Windows Explorer', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The cardinal rule of data recovery is: do not write to a failing drive. Every write operation risks overwriting recoverable data. The correct approach is to first create a complete sector-by-sector image (clone) of the failing drive using ddrescue or Clonezilla, which are designed to handle read errors and skip unreadable sectors. File recovery is then performed on the image file, leaving the original drive untouched. Running chkdsk /r, defragmenting, or copying files directly all involve writes to the failing drive and risk data loss.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.3 Troubleshoot Display Issues (8 questions) ───────────────────────

  {
    id: 'q-c1-5-3-01',
    topicId: 'topic-c1-5-3',
    type: 'single_choice',
    stem: 'A laptop display appears completely dark when the laptop is on. A technician shines a flashlight at the screen and can faintly see the desktop image. What does this finding indicate?',
    choices: ch('The GPU has failed and is not sending a video signal to the display panel', 'The display panel has failed completely and must be replaced', 'The backlight has failed, but the display panel and GPU are functioning correctly', 'The laptop\'s HDMI port is conflicting with the internal display output', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Seeing a faint image when a flashlight is shone at the screen is definitive evidence that the display panel and GPU are working — the image is being produced correctly. The problem is that the backlight is not illuminating the panel. On older CCFL-backlit laptops, the inverter board (which converts 12V DC to high-voltage AC for the CCFL tube) commonly fails. On LED-backlit displays, the LED driver circuit has failed. The fix is to replace the inverter board (CCFL) or the display assembly (LED), depending on the design.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-3-02',
    topicId: 'topic-c1-5-3',
    type: 'single_choice',
    stem: 'A desktop computer with a discrete GPU shows no video output on startup. The POST LED on the motherboard is stuck on the VGA indicator. What should the technician do FIRST?',
    choices: ch('Replace the GPU with a known-good unit immediately', 'Power off, reseat the GPU firmly in the PCIe x16 slot until the retention clip clicks, and reconnect all power connectors', 'Connect the monitor to the motherboard\'s integrated graphics output and update the GPU driver', 'Clear CMOS by removing the CMOS battery for 30 seconds', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A POST LED stuck on the VGA/GPU indicator means POST cannot detect or initialize the graphics card. Before replacing the GPU, the simplest and most common fix is to reseat it — GPUs can become partially unseated during shipping, case movement, or thermal cycling. Proper reseating requires pressing the card firmly into the PCIe x16 slot until the retention clip audibly clicks, and confirming all power connectors (6-pin, 8-pin) are fully seated. This resolves many "no video" issues without needing a replacement GPU.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-3-03',
    topicId: 'topic-c1-5-3',
    type: 'single_choice',
    stem: 'A user reports that their monitor displays vivid, random blocks of corrupted colors during 3D gaming, but the desktop looks normal. What is the MOST LIKELY cause?',
    choices: ch('The monitor\'s display panel is failing due to age', 'The GPU\'s VRAM is failing, causing texture corruption under load', 'The monitor cable is damaged, causing signal interference during rendering', 'The display driver has incorrect color profile settings', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Random blocks of corrupted colors, wrong textures, or scattered colored pixels during 3D applications — while the 2D desktop appears normal — are classic symptoms of failing VRAM. VRAM cells that fail under the thermal and electrical stress of 3D rendering produce texture corruption. The desktop is unaffected because 2D operations use far less VRAM. The technician should monitor GPU temperatures, run a FurMark stress test to reproduce the artifacts, and check if underclocking the GPU memory stabilizes the issue. Persistent artifacts indicate GPU hardware failure.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-3-04',
    topicId: 'topic-c1-5-3',
    type: 'single_choice',
    stem: 'A laptop display flickers when the lid is moved to different angles but displays a stable image when held still at a specific angle. What is the MOST LIKELY cause?',
    choices: ch('The GPU is overheating and throttling when the lid moves', 'The display driver is incompatible with the current Windows version', 'The internal display flex cable (eDP/LVDS) running through the hinge is damaged', 'The screen\'s refresh rate is set too high for the panel to handle', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Flickering that changes with lid angle is a classic symptom of a damaged internal display cable. The eDP (or LVDS on older laptops) cable connects the GPU output on the motherboard to the display panel and runs through the laptop hinge. Repeated flexing from opening and closing the lid causes individual wire strands to break internally, creating an intermittent connection. When held at a specific angle, the break makes contact. Replacement requires disassembling the display lid assembly to access the hinge area and replace or re-route the cable.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-3-05',
    topicId: 'topic-c1-5-3',
    type: 'single_choice',
    stem: 'A monitor displays all colors but text appears blurry even at the highest resolution available in Windows Display Settings. The "(Recommended)" label is not shown for any resolution. What is MOST LIKELY causing this?',
    choices: ch('The GPU does not support the monitor\'s native resolution', 'The correct GPU driver is not installed — Windows is using the generic Microsoft Basic Display Adapter', 'The monitor has a defective LCD panel causing blurry rendering', 'The DPI scaling setting is set too high', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When the Windows Display Settings does not show a "(Recommended)" resolution and is limited to generic low resolutions, the GPU-specific driver is not installed — Windows is using the Microsoft Basic Display Adapter (generic driver). Without the proper GPU driver, Windows cannot detect the monitor\'s native resolution via EDID, cannot enable hardware acceleration, and is limited to a subset of standard resolutions. Installing the correct driver (from Intel, AMD, or Nvidia) allows Windows to detect and recommend the native resolution, eliminating the blur caused by non-native scaling.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-3-06',
    topicId: 'topic-c1-5-3',
    type: 'single_choice',
    stem: 'A projector is connected to a laptop via HDMI but shows no image. The projector power light is on and it was previously working. What is the FIRST step the technician should take?',
    choices: ch('Replace the HDMI cable with a new one', 'Press Fn+F5 (or Win+P) on the laptop to enable or toggle the external display output', 'Restart the projector and wait for it to fully warm up', 'Reinstall the graphics driver on the laptop', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The most common reason a laptop does not send video to a projector or external display is that the laptop is not configured to output to the external display. Using Fn+F5 (or the dedicated display toggle key, varies by laptop model) or Win+P in Windows cycles through display modes: PC screen only, Duplicate, Extend, and Second screen only. The laptop may have been set to PC screen only from a previous session. This should be checked before replacing cables or reinstalling drivers.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-3-07',
    topicId: 'topic-c1-5-3',
    type: 'single_choice',
    stem: 'A monitor displays a single, always-green pixel in the same location regardless of what is displayed. This pixel is fully bright even on an all-black test screen. How should this be classified?',
    choices: ch('A dead pixel — the transistor has lost power to that pixel', 'A stuck pixel — one or more sub-pixel elements are stuck in the ON state', 'Normal pixel variation — all LCD panels have minor brightness inconsistencies', 'A hot pixel — all three sub-pixel elements are stuck on at full brightness', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A pixel that is always one specific color (red, green, or blue) is a stuck pixel — a sub-pixel element is stuck in the ON state. A dead pixel is always black (the transistor receives no power). A hot pixel is white (all three color sub-pixels stuck on). The always-green pixel indicates the green sub-pixel element is permanently energized. Stuck pixels can sometimes be resolved with pixel-refresher software tools like JScreenFix, which rapidly cycles colors. Dead pixels cannot be fixed with software.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-3-08',
    topicId: 'topic-c1-5-3',
    type: 'single_choice',
    stem: 'A laser printer produces pages where the print smears when rubbed with a finger immediately after printing. Which component in the laser printing process is MOST LIKELY responsible?',
    choices: ch('Primary Charge Roller (PCR)', 'Fuser assembly', 'Transfer roller', 'Laser scanning unit', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Toner that smears when rubbed immediately after printing indicates the fuser has not properly bonded the toner to the paper. The fuser assembly uses heat (~200°C) and pressure to melt the toner particles into the paper fibers. If the fuser is not reaching the correct temperature (due to a failing heating element or thermistor) or if the fuser rollers are worn, toner will not fuse and will smear. The fuser assembly must be replaced. Note: this question is in the 5.3 display section but covers the laser printing process which overlaps with printer troubleshooting concepts.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.4 Troubleshoot Mobile Devices (8 questions) ────────────────────────

  {
    id: 'q-c1-5-4-01',
    topicId: 'topic-c1-5-4',
    type: 'single_choice',
    stem: 'A smartphone battery shows 85% charge but the phone suddenly powers off during normal use. After plugging in the charger, the phone powers back on showing 85%. What is the MOST LIKELY cause?',
    choices: ch('The charging port is faulty and not properly delivering power', 'The battery has degraded and can no longer deliver adequate current at low state-of-charge', 'A background app is consuming excessive power and causing thermal shutdown', 'The phone\'s OS has a bug in the battery reporting algorithm', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Unexpected shutdowns at seemingly high battery percentages (20–40% or even higher) are a hallmark symptom of a degraded lithium-ion battery. As Li-ion cells age, they lose actual capacity while the reported percentage becomes inaccurate — the phone shuts off because the battery voltage drops below the minimum threshold under load, even though the fuel gauge reports remaining charge. Battery health below 80% (iOS) or confirmed by third-party tools (AccuBattery on Android) confirms this diagnosis. Battery replacement resolves the issue.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-4-02',
    topicId: 'topic-c1-5-4',
    type: 'single_choice',
    stem: 'A user\'s smartphone back cover is visibly bulging outward. What is the MOST LIKELY cause and the appropriate immediate response?',
    choices: ch('The internal storage has expanded due to being nearly full; delete files and the swelling will subside', 'The Li-ion battery is swollen due to gas buildup and is a fire hazard; store safely and replace the battery immediately', 'The phone\'s motherboard has warped due to overheating; replace the motherboard', 'The user accidentally activated water-resistance seals; press the back cover firmly to reseat the seals', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A bulging or puffed-out back cover on a smartphone is caused by a swollen lithium-ion battery. Electrolyte decomposition during overcharging, heat damage, or manufacturing defects causes gas to build up inside the battery pouch, causing it to expand. A swollen Li-ion battery is a serious fire and explosion hazard — it should not be punctured, compressed, or heated. The device should be stored in a fireproof container and the battery replaced by a qualified technician as soon as possible. Storage should not be near flammable materials.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-4-03',
    topicId: 'topic-c1-5-4',
    type: 'single_choice',
    stem: 'A touchscreen is responding to touches that the user is not making — apps open randomly and text types itself. The screen is not cracked. What is the MOST LIKELY cause?',
    choices: ch('The phone\'s proximity sensor is malfunctioning, triggering random touches', 'Ghost touches caused by moisture under the screen shorting digitizer traces, or a failing digitizer', 'The phone has malware that is controlling the UI remotely', 'The screen protector is too thick and is generating false touch signals from the frame', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Ghost touches — the screen responding to non-existent touches — are most commonly caused by moisture or liquid inside the device shorting the digitizer\'s capacitive traces, a cracked or failing digitizer, or a loose digitizer ribbon cable connector. First steps are to remove the screen protector and test, then check for water damage. If a digitizer connector is accessible, reseating it may help. In most cases, the digitizer or full display assembly must be replaced. The proximity sensor manages screen-off during calls, not random touch events.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-4-04',
    topicId: 'topic-c1-5-4',
    type: 'single_choice',
    stem: 'A user dropped their phone in a sink. They want to check if it still works. What is the correct sequence of immediate actions?',
    choices: ch('Turn on the phone immediately to verify functionality, then dry it', 'Power off immediately, remove the SIM card, pat dry with a cloth, and place in silica gel packets for 24–48 hours before attempting to power on', 'Place the phone in a bag of uncooked rice overnight to absorb the moisture', 'Use a hair dryer on low heat to dry the ports and then power on', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Correct water damage response: immediately power off (do not attempt to use or charge — shorting causes permanent damage), remove the SIM card tray, gently shake out visible water, pat dry with a cloth (do not rub — this pushes water deeper), and place in a container with silica gel desiccant packets for 24–48 hours. Rice is a persistent myth — it is a poor desiccant and dust can enter ports. A hair dryer\'s heat can damage battery, plastic, and adhesives. Powering on with moisture present is the most damaging action.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-4-05',
    topicId: 'topic-c1-5-4',
    type: 'single_choice',
    stem: 'A user has strong cellular signal bars but cannot access mobile data even though their data plan is active. Other devices on the same carrier work fine. What should the technician check FIRST?',
    choices: ch('The carrier network is experiencing an outage; wait for service to restore', 'The phone\'s APN (Access Point Name) settings are incorrect or missing', 'The phone\'s battery is too low, throttling the cellular radio', 'The SIM card needs to be replaced as it is worn out', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Having cellular signal (bars) but no data connectivity while voice works — especially when other devices work fine — is a classic symptom of incorrect APN (Access Point Name) settings. APN settings tell the phone how to connect to the carrier\'s data network, and incorrect settings result in failed data sessions despite good signal. APN settings are usually provisioned automatically when a SIM is inserted, but can become corrupted or may need manual configuration for certain MVNOs. Check iOS: Settings → Cellular → Cellular Data Network, or Android: Settings → Network → Mobile Network → APNs.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-4-06',
    topicId: 'topic-c1-5-4',
    type: 'single_choice',
    stem: 'A user\'s iPhone screen displays images but does not respond to any touch input anywhere on the screen. The phone has not been physically damaged. What is the BEST first step?',
    choices: ch('Replace the digitizer assembly immediately — touch failure is always a hardware problem', 'Perform a force restart: press and release Volume Up, press and release Volume Down, then hold the Side button until the Apple logo appears', 'Restore the iPhone to factory settings via iTunes/Finder', 'Remove and reinsert the SIM card to reset the connection', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When an iPhone touchscreen completely stops responding with no physical damage, a software or firmware glitch is often the cause. The force restart (iPhone 8 and later: Volume Up, Volume Down, then hold Side/Power button) is the appropriate first step — it is non-destructive (no data is lost) and resolves many transient touch and OS issues by clearing the memory state. If the force restart does not restore touch, the digitizer assembly may have failed and hardware repair is needed. Factory restore is a more invasive step taken after simpler solutions fail.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-4-07',
    topicId: 'topic-c1-5-4',
    type: 'single_choice',
    stem: 'A user\'s phone battery drains completely in about 4 hours under normal use. Battery health shows 71%. The phone is 3 years old. What is the BEST solution?',
    choices: ch('Perform a factory reset to clear software issues causing battery drain', 'Replace the battery — at 71% health it has significantly degraded beyond the 80% service threshold', 'Disable all cellular and Wi-Fi radios to extend battery life', 'Install a battery optimization app from the Play Store', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A battery at 71% health means it can only hold 71% of its original capacity — a significant degradation. Apple recommends service when battery health falls below 80%; at 71%, the battery is significantly degraded and will not support a full day of use. Battery replacement is the correct solution. Factory reset cannot increase battery capacity. Disabling radios is a workaround that significantly impairs phone functionality. Third-party battery optimization apps cannot physically restore degraded battery chemistry.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-4-08',
    topicId: 'topic-c1-5-4',
    type: 'single_choice',
    stem: 'A user\'s phone GPS is not acquiring a location fix even outdoors. Location Services are enabled. What setting should the technician enable on Android to improve GPS acquisition speed?',
    choices: ch('Enable Bluetooth scanning to assist GPS triangulation', 'Enable High Accuracy mode (uses GPS, Wi-Fi, and cellular for position)', 'Enable Developer Options and increase the GPS polling rate', 'Disable automatic time zone detection to prevent GPS conflicts', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Android\'s High Accuracy location mode uses GPS satellites, Wi-Fi positioning, and cellular network data together for the fastest and most accurate location fix. GPS alone (Device Only mode) relies solely on satellite signals and can take 1–5 minutes for a cold fix. High Accuracy mode also uses A-GPS (Assisted GPS), which downloads current satellite ephemeris data via cellular/Wi-Fi, dramatically reducing time-to-first-fix. Bluetooth scanning can help with indoor positioning but is not the primary solution for GPS acquisition outdoors.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.5 Troubleshoot Network Issues (8 questions) ────────────────────────

  {
    id: 'q-c1-5-5-01',
    topicId: 'topic-c1-5-5',
    type: 'single_choice',
    stem: 'A Windows PC runs ipconfig and shows an IP address of 169.254.47.23. The user cannot access any network resources or the internet. What does this address indicate?',
    choices: ch('The PC has been assigned a valid private IP address from the 169.254.0.0 corporate subnet', 'The PC failed to obtain an IP address from a DHCP server and assigned itself an APIPA address', 'The PC\'s DNS server is unreachable and Windows fell back to the APIPA DNS range', 'The PC is connected to the internet through a VPN that uses the 169.254.x.x range', 'b'),
    correctAnswer: ca('b'),
    explanation: '169.254.x.x is an APIPA (Automatic Private IP Addressing) address in the 169.254.0.0/16 range. Windows automatically assigns itself an APIPA address when it cannot reach a DHCP server after attempting to obtain an IP. An APIPA address means the device has no default gateway, no DNS server, and cannot communicate beyond its local network segment. Common causes: no cable connection, DHCP server down, DHCP scope exhausted, or wrong VLAN assignment. Fix with ipconfig /release then ipconfig /renew after resolving the underlying DHCP issue.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-5-02',
    topicId: 'topic-c1-5-5',
    type: 'single_choice',
    stem: 'A user can access websites by entering IP addresses (e.g., http://8.8.8.8) but cannot reach any site by domain name (e.g., http://google.com). Which command should be used to diagnose this issue?',
    choices: ch('ipconfig /flushdns', 'ping 127.0.0.1', 'nslookup google.com', 'tracert 8.8.8.8', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The described symptom — IP access works but domain name access fails — is a classic DNS failure. The nslookup command directly tests DNS name resolution by querying the configured DNS server for a hostname. It shows whether the DNS server responds, what IP it returns, and which server is being queried. If nslookup fails, the DNS server is unreachable or returning incorrect results. ipconfig /flushdns clears the local DNS cache (a fix step, not a diagnostic), ping 127.0.0.1 tests the TCP/IP stack, and tracert traces routing paths.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-5-03',
    topicId: 'topic-c1-5-5',
    type: 'single_choice',
    stem: 'A network connection is established (link LEDs lit, valid IP assigned) but transfer speeds between a PC and a switch are extremely slow with many retransmissions observed. What network condition is MOST LIKELY responsible?',
    choices: ch('The DNS server is overloaded, causing slow name resolution for all transfers', 'A duplex mismatch exists between the PC\'s NIC and the switch port', 'The DHCP lease time is too short, causing frequent IP renewals that interrupt transfers', 'The cable is too long, exceeding the 100-meter maximum for Cat5e Ethernet', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A duplex mismatch (one side set to full duplex, the other to half duplex) causes severe performance degradation through excessive late collisions. The half-duplex device uses CSMA/CD and interprets simultaneous traffic from the full-duplex side as collisions, triggering constant retransmissions. The link appears established and a valid IP is assigned, but throughput is severely degraded. Diagnostic signs include late collisions in switch port statistics. The fix is to hardcode both sides to the same speed and duplex, or ensure auto-negotiation is enabled on both sides simultaneously.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-5-04',
    topicId: 'topic-c1-5-5',
    type: 'single_choice',
    stem: 'A user\'s PC obtains a valid IP address but cannot ping the default gateway. Other PCs on the same subnet can reach the gateway. The cable and NIC link LED are lit. What should the technician check NEXT?',
    choices: ch('Replace the default gateway router as it is likely failing', 'Check if the subnet mask is configured incorrectly on the affected PC', 'Run ipconfig /flushdns to clear the DNS cache', 'Reinstall the network adapter driver on the PC', 'b'),
    correctAnswer: ca('b'),
    explanation: 'If other PCs on the same subnet can reach the gateway but this specific PC cannot, despite having a valid IP and active link, the most likely cause is an incorrect subnet mask on the affected PC. A wrong subnet mask causes the PC to miscalculate which addresses are local vs. remote — it may think the gateway is on a different network and route gateway-bound traffic incorrectly. Check ipconfig to verify the subnet mask matches other working PCs. For example, if the network uses /24 (255.255.255.0) and this PC shows /25 (255.255.255.128), it would be unable to reach gateways outside its perceived subnet.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-5-05',
    topicId: 'topic-c1-5-5',
    type: 'single_choice',
    stem: 'A new employee\'s PC is connected to a network port in a conference room but receives an IP address from the wrong subnet (192.168.20.x instead of the expected 192.168.10.x). The conference room port previously worked for a different device. What is the MOST LIKELY cause?',
    choices: ch('The DHCP server has run out of addresses in the 192.168.10.x pool', 'The switch port is configured for the wrong VLAN (VLAN 20 instead of VLAN 10)', 'The PC has a static IP configured that conflicts with the DHCP assignment', 'The network cable between the conference room and the switch is damaged', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Receiving an IP from a wrong subnet (192.168.20.x instead of 192.168.10.x) after connecting to a switch port is the textbook symptom of a VLAN misconfiguration. The switch port is assigned to VLAN 20, which has its own DHCP scope (192.168.20.x), instead of VLAN 10 where the PC should be. This commonly occurs when a port is inadvertently changed during network maintenance or when a device is moved to a port that happens to be in a different VLAN. Fix: access the switch management and configure the correct access VLAN on that port.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-5-06',
    topicId: 'topic-c1-5-5',
    type: 'single_choice',
    stem: 'A user can ping 8.8.8.8 successfully but cannot load any websites. Which command should be run next to isolate the problem?',
    choices: ch('ping 127.0.0.1', 'ipconfig /release', 'nslookup google.com', 'tracert 192.168.1.1', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Successful ping to 8.8.8.8 (Google\'s DNS IP) confirms internet connectivity is working at the IP level. Failure to load websites despite working IP connectivity is a classic DNS failure symptom — the browser cannot resolve domain names to IP addresses. Running nslookup google.com will immediately confirm whether DNS resolution is working. If nslookup fails, the configured DNS server is unreachable or not functioning. The fix is to change the DNS server settings (e.g., to 8.8.8.8 or 1.1.1.1) or run ipconfig /flushdns to clear a stale cache.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-5-07',
    topicId: 'topic-c1-5-5',
    type: 'single_choice',
    stem: 'A wired network connection drops out for a few seconds every few minutes. The switch logs show repeated "link down/link up" events on the same port. What is the MOST LIKELY cause?',
    choices: ch('The switch port is configured with an incorrect VLAN, causing periodic renegotiation', 'The PC\'s network adapter driver needs updating', 'The network cable is damaged or has a faulty RJ-45 connector causing port flapping', 'The DHCP server is issuing leases with too-short durations, requiring frequent renewal', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Repeated link down/link up events on a switch port — known as port flapping — most commonly indicate a physical cable problem. A damaged cable with a broken conductor or a faulty RJ-45 crimp causes intermittent loss of the physical connection. The switch port detects the link drop and comes back up when contact is briefly restored. To diagnose: flex and move the cable while watching the connection; if the problem changes with cable movement, the cable is the cause. Replace the cable. Other causes include a failing NIC or switch port, but the cable is the first thing to test.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-5-08',
    topicId: 'topic-c1-5-5',
    type: 'single_choice',
    stem: 'A technician is troubleshooting a PC with no network connectivity. Following the OSI bottom-up approach, what is the CORRECT order for the first three diagnostic steps?',
    choices: ch('Check DNS settings → ping the gateway → check physical cable and link LED', 'Check physical cable and link LED → run ipconfig to check IP address → ping the default gateway', 'Run nslookup → run tracert → ping 127.0.0.1', 'Check IP address → check DNS → check physical connection', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The OSI bottom-up troubleshooting approach starts at Layer 1 (Physical) and works upward. Step 1 (Layer 1): Check the physical cable — is it connected? Are the link LEDs lit on the NIC and switch port? Step 2 (Layer 3): Run ipconfig to check the IP address — is it a valid IP or an APIPA 169.254.x.x address? Step 3 (Layer 3): Ping the default gateway to test local network routing. Problems at lower layers block all upper layers, so it is inefficient to check DNS (Layer 5-7) before confirming the physical connection is working.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 5.6 Troubleshoot Printers (8 questions) ──────────────────────────────

  {
    id: 'q-c1-5-6-01',
    topicId: 'topic-c1-5-6',
    type: 'single_choice',
    stem: 'A laser printer produces pages where a faint duplicate image of content from higher up the page appears slightly lower on the same page. Which component is MOST LIKELY failing?',
    choices: ch('Fuser assembly', 'Transfer roller', 'Drum unit or cleaning blade', 'Primary Charge Roller (PCR)', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Ghosting — a faint repeated image offset lower on the page — is caused by residual toner left on the drum after the cleaning step. The cleaning blade should wipe the drum clean after each rotation, but a worn or damaged cleaning blade (or a worn drum) leaves behind toner that prints again on the next pass. This appears as a faint "ghost" of earlier content lower on the same page. A fuser issue causes smearing, not ghosting. The PCR failure causes charging problems leading to blank or all-black pages.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-6-02',
    topicId: 'topic-c1-5-6',
    type: 'single_choice',
    stem: 'Multiple users are unable to print to a shared network printer. The printer is powered on, the ping to its IP address succeeds, and the printer panel shows Ready. What should the technician check FIRST on the print server?',
    choices: ch('Reinstall the printer driver on each user\'s workstation', 'Restart the Print Spooler service on the print server — a crashed spooler stops all printing', 'Replace the network printer\'s NIC as the ping may be unreliable', 'Check each user\'s printer permissions in Active Directory', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When multiple users cannot print to a shared printer that is online and reachable (ping succeeds, panel says Ready), the most common server-side cause is a crashed or hung Windows Print Spooler service. The spooler manages all print jobs; if it crashes, all printing stops immediately for all users sharing that printer. Restarting the spooler (services.msc → Print Spooler → Restart, or net stop/start spooler) is the fastest fix. If a stuck job is blocking the queue, stop the spooler, delete files from C:\\Windows\\System32\\spool\\PRINTERS\\, then restart the spooler.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-6-03',
    topicId: 'topic-c1-5-6',
    type: 'single_choice',
    stem: 'An office network printer showed as offline yesterday after working fine. The printer panel shows Ready. A technician runs ping 192.168.1.50 and gets replies. What is the MOST LIKELY cause of the offline status?',
    choices: ch('The printer\'s IP address has changed since it was added to Windows, and the configured port still points to the old IP', 'The printer driver has become corrupted and needs to be reinstalled', 'The printer is in energy-saving mode and must be woken up manually', 'The Ethernet port on the switch has failed; move the printer to a different switch port', 'a'),
    correctAnswer: ca('a'),
    explanation: 'When a network printer shows offline in Windows but is reachable by ping, the most common cause is that the printer\'s IP address has changed (e.g., after a DHCP lease renewal) and the Windows printer port still points to the old IP address. The printer responds to ping at its new IP, but Windows cannot communicate with it at the old IP it has stored. Fix options: update the printer port IP in Devices and Printers → Printer Properties → Ports → Configure Port; or better, configure a DHCP reservation on the router to ensure the printer always gets the same IP.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-6-04',
    topicId: 'topic-c1-5-6',
    type: 'single_choice',
    stem: 'An inkjet printer is producing output with horizontal white streaks at regular intervals across the page. The ink cartridges have recently been replaced. What is the MOST LIKELY cause and fix?',
    choices: ch('The paper is too thick for this printer; switch to standard 20 lb paper', 'The printhead nozzles are clogged; run the printhead cleaning utility from the printer software', 'The ink cartridges are not seated properly; remove and re-insert them', 'The print resolution is too low; increase DPI in the print settings', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Horizontal banding — regular white streaks across the page — is the classic symptom of clogged inkjet printhead nozzles. Nozzles that are partially or fully blocked cannot deposit ink in their assigned areas, leaving white bands where ink is missing. This occurs even with new cartridges because the nozzles may have dried ink from sitting unused. Run the printhead cleaning utility (available in the printer driver\'s maintenance tab or the printer\'s control panel) 1–3 times, then print a nozzle check pattern to verify improvement. Excessive cleaning wastes ink; allow the printer to sit if repeated cleaning fails.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-6-05',
    topicId: 'topic-c1-5-6',
    type: 'single_choice',
    stem: 'A thermal receipt printer produces faded, barely legible output even though the paper roll was just replaced. A technician scratches the paper with a fingernail and a dark mark appears on the smooth side. What does this indicate, and what is the fix?',
    choices: ch('The printhead is overheating; clean the paper path and reduce the print speed setting', 'The paper is loaded correctly (smooth/thermal side faces the printhead); the printhead itself is dirty and should be cleaned with isopropyl alcohol', 'The paper is loaded backward — the non-thermal side is facing the printhead; flip the paper roll so the smooth side faces the printhead', 'The printhead has burned out; replace the thermal printhead assembly', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The fingernail scratch test identifies the thermal-sensitive side of thermal paper — the side that produces a dark mark when scratched is the thermal side. The mark appearing on the smooth side confirms the smooth side IS the thermal side, and thus the paper IS loaded correctly (smooth/thermal side should face the printhead). Since paper orientation is correct but output is faded, the likely cause is a dirty printhead — residue from thermal paper coatings accumulates on the printhead heating elements and reduces heat transfer. Clean the printhead with an isopropyl alcohol swab.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-6-06',
    topicId: 'topic-c1-5-6',
    type: 'single_choice',
    stem: 'A laser printer produces completely blank pages — no text or image at all. The toner cartridge was recently replaced. What should the technician check FIRST?',
    choices: ch('Replace the fuser assembly as fuser failure causes blank output', 'Verify the sealing tape or protective strip was removed from the new toner cartridge', 'Check that the paper type matches the fuser temperature setting', 'Inspect the laser scanning unit for dust on the lens', 'b'),
    correctAnswer: ca('b'),
    explanation: 'New toner cartridges come with a plastic sealing strip or tape that protects the toner during shipping and storage. If this strip is not removed before installing the cartridge, the toner cannot reach the drum and the printer produces completely blank pages. This is the most common cause of blank output immediately after cartridge replacement. The sealing strip must be pulled out and discarded before installing the cartridge. If the strip was removed and pages are still blank, then drum failure, PCR issues, or laser unit problems should be investigated.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-6-07',
    topicId: 'topic-c1-5-6',
    type: 'single_choice',
    stem: 'A user can print to an office printer from their laptop but other users on the network cannot. The printer is shared from the user\'s laptop. What is the MOST LIKELY reason others cannot print?',
    choices: ch('The printer driver on the other users\' machines is the wrong version', 'The host laptop must be powered on and awake for others to use the shared printer; the laptop may be in sleep mode', 'The printer\'s network cable has been connected to the wrong switch port', 'The printer requires a dedicated print server for network sharing', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When a printer is shared using Windows peer-to-peer printer sharing (not a dedicated print server), all print jobs from other users are processed through the sharing host computer. If the host laptop is powered off, sleeping, or hibernating, other users cannot reach the shared printer — they will see it as offline or unavailable. The user whose laptop hosts the printer can always print locally regardless of the laptop\'s sleep state. Solutions: configure the laptop to never sleep while on AC power, or move to a dedicated print server or network-attached printer.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-5-6-08',
    topicId: 'topic-c1-5-6',
    type: 'single_choice',
    stem: 'A laser printer jams frequently even with new paper. The paper picks up from the tray initially but jams midway through the print path. Which component is MOST LIKELY worn?',
    choices: ch('The fuser assembly rollers are worn and not pulling paper through properly', 'The primary charge roller is contaminated, causing paper to stick to the drum', 'The pickup roller is glazed and failing to reliably feed paper from the tray', 'The paper tray spring tension is too high, over-feeding paper', 'a'),
    correctAnswer: ca('a'),
    explanation: 'A jam that occurs midway through the print path (not at pickup) points to the fuser assembly rollers. The fuser uses heated rollers to press the paper through and fuse the toner. When the fuser rollers are worn or contaminated, they lose their grip on the paper mid-path, causing the paper to stop and jam. This is distinct from pickup roller failure, which would prevent paper from being picked up from the tray at all. Worn fuser rollers also cause toner smearing as a secondary symptom. The fuser assembly should be replaced.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

]
