// CompTIA A+ Practice Questions — All Topics (both exams)
// Core 1 Domain 3 originals + batch imports for all remaining topics

import { BATCH1_QUESTIONS } from './questions-batch1'
import { BATCH2_QUESTIONS } from './questions-batch2'
import { BATCH3_QUESTIONS } from './questions-batch3'
import { BATCH4_QUESTIONS } from './questions-batch4'
import { BATCH5_QUESTIONS } from './questions-batch5'
import { BATCH6_QUESTIONS } from './questions-batch6'
import { BATCH7_QUESTIONS } from './questions-batch7'
import { BATCH8_QUESTIONS } from './questions-batch8'
import { BATCH9_QUESTIONS } from './questions-batch9'
import { BATCH10_QUESTIONS } from './questions-batch10'
import { BATCH11_QUESTIONS } from './questions-batch11'
import { BATCH12_QUESTIONS } from './questions-batch12'
import { BATCH13A_QUESTIONS } from './questions-batch13a'
import { BATCH13B_QUESTIONS } from './questions-batch13b'
import { BATCH14A_QUESTIONS } from './questions-batch14a'
import { BATCH14B_QUESTIONS } from './questions-batch14b'
import { BATCH15_QUESTIONS } from './questions-batch15'
import { BATCH16_QUESTIONS } from './questions-batch16'
import { BATCH17_QUESTIONS } from './questions-batch17'

const NOW = new Date().toISOString()

type Choice = { id: string; text: string; isCorrect: boolean }

function ch(a: string, b: string, c: string, d: string, correct: 'a' | 'b' | 'c' | 'd'): string {
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: correct === 'a' },
    { id: 'b', text: b, isCorrect: correct === 'b' },
    { id: 'c', text: c, isCorrect: correct === 'c' },
    { id: 'd', text: d, isCorrect: correct === 'd' },
  ] as Choice[])
}

function chMulti(
  a: string, b: string, c: string, d: string,
  correct: Array<'a' | 'b' | 'c' | 'd'>
): string {
  const ids = new Set(correct)
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: ids.has('a') },
    { id: 'b', text: b, isCorrect: ids.has('b') },
    { id: 'c', text: c, isCorrect: ids.has('c') },
    { id: 'd', text: d, isCorrect: ids.has('d') },
  ] as Choice[])
}

const ca = (id: 'a' | 'b' | 'c' | 'd') => JSON.stringify(id)
const cam = (...ids: Array<'a' | 'b' | 'c' | 'd'>) => JSON.stringify(ids)

const CORE1_D3_QUESTIONS = [

  // ─── 3.1 Display Components (12 questions) ────────────────────────────────

  {
    id: 'q-c1-3-1-01',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'Which LCD panel technology offers the widest viewing angles and most accurate color reproduction?',
    choices: ch('TN (Twisted Nematic)', 'IPS (In-Plane Switching)', 'VA (Vertical Alignment)', 'CCFL backlit TN', 'b'),
    correctAnswer: ca('b'),
    explanation: 'IPS (In-Plane Switching) panels provide viewing angles up to 178° and the most accurate color reproduction among standard LCD types, making them ideal for graphic designers and video editors. TN panels are fastest but have narrow viewing angles. VA panels offer the best contrast ratio but fall between TN and IPS on color and viewing angle.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-02',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'A competitive gamer wants the monitor with the lowest possible pixel response time to minimize ghosting. Which panel type should they choose?',
    choices: ch('IPS', 'VA', 'TN', 'OLED', 'c'),
    correctAnswer: ca('c'),
    explanation: 'TN (Twisted Nematic) panels have the fastest pixel response time, often as low as 1ms, making them the traditional choice for competitive gaming where ghosting must be minimized. IPS panels have improved but typically run 4-10ms. VA panels are typically 8-20ms.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-03',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'Which display technology can achieve true black by completely turning off individual pixels, resulting in an effectively infinite contrast ratio?',
    choices: ch('IPS LCD', 'VA LCD', 'TN LCD', 'OLED', 'd'),
    correctAnswer: ca('d'),
    explanation: 'OLED (Organic Light-Emitting Diode) is a self-emissive technology where each pixel produces its own light and can turn completely off. This enables true black and an infinite contrast ratio. All LCD variants (IPS, VA, TN) use a backlight that leaks through even when pixels appear black, limiting contrast.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-04',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'Which video connector transmits only an analog signal and uses a 15-pin DE-15 (HD-15) connector?',
    choices: ch('DVI-D', 'HDMI', 'VGA', 'DisplayPort', 'c'),
    correctAnswer: ca('c'),
    explanation: 'VGA (Video Graphics Array) uses the DE-15 (also called HD-15) connector with 15 pins in three rows. It carries only analog video — no audio. VGA is a legacy standard and cannot natively drive digital flat panels without an active DAC converter.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-05',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'Which display connector supports daisy-chaining multiple monitors from a single port using Multi-Stream Transport (MST)?',
    choices: ch('HDMI', 'VGA', 'DVI-I', 'DisplayPort', 'd'),
    correctAnswer: ca('d'),
    explanation: 'DisplayPort supports Multi-Stream Transport (MST), which allows multiple monitors to be connected in a daisy-chain from a single DisplayPort output on the GPU. HDMI does not natively support daisy-chaining in the same manner.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-06',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'Display brightness is measured in which unit?',
    choices: ch('Hz', 'DPI', 'Nits (cd/m²)', 'Lumens', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Nits (candelas per square meter, cd/m²) measure the brightness of a display. A typical office monitor is 250-350 nits. High-brightness displays for HDR can reach 1000+ nits. Hz measures refresh rate; DPI measures print/image resolution; lumens measure projector brightness.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-07',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'A user has a monitor with a DVI port that accepts both analog and digital signals. Which DVI type is this?',
    choices: ch('DVI-A', 'DVI-D', 'DVI-I', 'DVI-S', 'c'),
    correctAnswer: ca('c'),
    explanation: 'DVI-I (Integrated) supports both digital and analog signals. DVI-D is digital only, and DVI-A is analog only. The "I" in DVI-I stands for Integrated, meaning it includes pins for both signal types. DVI-S does not exist.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-08',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'What is the resolution of a standard 4K Ultra HD display?',
    choices: ch('1920×1080', '2560×1440', '3840×2160', '7680×4320', 'c'),
    correctAnswer: ca('c'),
    explanation: '4K UHD (Ultra High Definition) has a resolution of 3840×2160 pixels (also referred to as 2160p). 1920×1080 is Full HD (1080p), 2560×1440 is QHD/1440p, and 7680×4320 is 8K UHD.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-09',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'A monitor is rated at 144 Hz. What does this specification describe?',
    choices: ch('The monitor renders 144 megapixels per second', 'The backlight flickers at 144 times per second', 'The display refreshes its image 144 times per second', 'The monitor supports 144-bit color depth', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Refresh rate (measured in Hz) is how many times per second the monitor updates the displayed image. A 144 Hz monitor redraws the image 144 times per second compared to 60 times for a standard 60 Hz monitor, resulting in smoother motion especially in fast games.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-10',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'A laptop user notices the screen looks washed out and colors shift dramatically when viewed from a slight angle. Which panel type is the laptop most likely using?',
    choices: ch('IPS', 'OLED', 'TN', 'VA', 'c'),
    correctAnswer: ca('c'),
    explanation: 'TN (Twisted Nematic) panels have narrow viewing angles (typically 140° horizontal, 130° vertical). When viewed off-axis, colors shift and wash out noticeably. IPS and OLED maintain color accuracy at wide angles. TN is still common in budget laptops due to its lower cost and fast response time.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-11',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'Which LCD panel type is known for having the highest contrast ratio, making it suitable for watching movies in dark rooms?',
    choices: ch('TN', 'IPS', 'VA', 'CCFL', 'c'),
    correctAnswer: ca('c'),
    explanation: 'VA (Vertical Alignment) panels offer the highest contrast ratio of standard LCD types — typically 3000:1 or higher — making dark scenes appear darker compared to IPS (1000:1) and TN (800:1). This makes VA excellent for movies and content consumption. CCFL is a backlight technology, not a panel type.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-1-12',
    topicId: 'topic-c1-3-1',
    type: 'single_choice',
    stem: 'What is the standard widescreen aspect ratio for most modern computer monitors and HDTVs?',
    choices: ch('4:3', '5:4', '16:10', '16:9', 'd'),
    correctAnswer: ca('d'),
    explanation: '16:9 is the standard widescreen aspect ratio for modern monitors, HDTVs, and most multimedia content. 4:3 was the old standard (CRT era). 5:4 was common in older LCD workstation monitors. 16:10 is used in some professional and productivity monitors and provides slightly more vertical space.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.2 Cables and Connectors (14 questions) ─────────────────────────────

  {
    id: 'q-c1-3-2-01',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'What is the maximum data transfer speed of Cat6a Ethernet cable at a distance of 100 meters?',
    choices: ch('1 Gbps', '5 Gbps', '10 Gbps', '40 Gbps', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Cat6a (Augmented Category 6) supports 10 Gbps at distances up to 100 meters and operates at 500 MHz. Cat6 can also achieve 10 Gbps but only at 55 meters or less. Cat5e is limited to 1 Gbps. Cat8 can reach 40 Gbps but only up to 30 meters.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-02',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'USB 3.2 Gen 1 (previously called USB 3.0) transfers data at what speed?',
    choices: ch('480 Mbps', '5 Gbps', '10 Gbps', '20 Gbps', 'b'),
    correctAnswer: ca('b'),
    explanation: 'USB 3.2 Gen 1 (the original USB 3.0, also called SuperSpeed USB) transfers at 5 Gbps. USB 2.0 runs at 480 Mbps. USB 3.2 Gen 2 runs at 10 Gbps. USB 3.2 Gen 2×2 runs at 20 Gbps. USB 3.x ports are typically identified by their blue color.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-03',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'A technician needs to run fiber optic cable across a 10-kilometer campus. Which fiber type should be used?',
    choices: ch('OM1 Multimode (orange)', 'OM4 Multimode (aqua)', 'Single-mode (yellow)', 'Cat6a with SFP adapter', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Single-mode fiber (identifiable by its yellow jacket) is designed for long-distance runs of many kilometers, using a single light path with a laser. Multimode fiber (OM1/OM4) is used for short distances up to ~500 meters within buildings. The color coding is standardized: yellow = single-mode, orange/aqua = multimode.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-04',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'Which USB connector type is reversible and can be inserted in either orientation?',
    choices: ch('USB-A', 'USB-B', 'USB Micro-B', 'USB-C', 'd'),
    correctAnswer: ca('d'),
    explanation: 'USB-C (USB Type-C) has a symmetrical oval shape allowing it to be inserted in either orientation — there is no "wrong way." USB-A is the flat rectangular connector that only goes in one way. USB-B and Micro-B are also orientation-specific. USB-C also supports higher speeds (USB 3.2, USB4, Thunderbolt) and can carry power and video.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-05',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'Thunderbolt 3 and Thunderbolt 4 both use which physical connector form factor?',
    choices: ch('Mini DisplayPort', 'USB-A', 'USB-C', 'HDMI Type A', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Thunderbolt 3 and 4 use the USB-C physical connector, providing 40 Gbps bandwidth. Thunderbolt 1 and 2 used the Mini DisplayPort connector form factor. Thunderbolt is backward compatible with USB devices when using a Thunderbolt 3/4 port. Look for the lightning bolt icon to identify Thunderbolt ports.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-06',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'A SATA III data cable has how many pins?',
    choices: ch('4', '7', '15', '40', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The SATA data connector has 7 pins and is L-shaped to prevent incorrect insertion. A separate 15-pin SATA power connector provides power to the drive. The older IDE/PATA standard used 40-pin ribbon cables. 4-pin Molex is a legacy power connector.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-07',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'What is the maximum speed of Cat5e Ethernet cable?',
    choices: ch('100 Mbps', '1 Gbps', '10 Gbps', '5 Gbps', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Cat5e (Category 5 Enhanced) supports 1 Gbps (1000BASE-T) at distances up to 100 meters and operates at 100 MHz. It replaced the original Cat5 which was limited to 100 Mbps. Cat5e is still widely deployed in existing infrastructure. Cat6 and above are needed for 10 Gbps.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-08',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'SC, ST, and LC are types of connectors used with which cable medium?',
    choices: ch('Coaxial (RG-6)', 'STP Cat6', 'Fiber optic', 'eSATA', 'c'),
    correctAnswer: ca('c'),
    explanation: 'SC (Subscriber Connector — square push-pull), ST (Straight Tip — round bayonet), and LC (Lucent Connector — small square push-pull) are fiber optic connectors. LC is the most common in modern data centers due to its small form factor. MTRJ is another common fiber connector type used in patch panels.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-09',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'What is the data transfer speed of USB 2.0?',
    choices: ch('12 Mbps (Full Speed)', '60 Mbps', '480 Mbps (Hi-Speed)', '5 Gbps', 'c'),
    correctAnswer: ca('c'),
    explanation: 'USB 2.0 (Hi-Speed USB) transfers at 480 Mbps. Note that USB 2.0 also has Low Speed (1.5 Mbps) and Full Speed (12 Mbps) modes for legacy devices. USB 1.1 was 12 Mbps maximum. USB 3.2 Gen 1 (USB 3.0) brought speeds up to 5 Gbps.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-10',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'A GPU outputs only digital signals via HDMI and DisplayPort. A legacy monitor has only a VGA input. What type of adapter is required to connect them?',
    choices: ch('Passive HDMI-to-VGA cable adapter', 'Active HDMI-to-VGA adapter (with DAC)', 'DVI-I cable', 'HDCP converter', 'b'),
    correctAnswer: ca('b'),
    explanation: 'HDMI is a digital signal; VGA is analog. Converting digital to analog requires an active adapter containing a Digital-to-Analog Converter (DAC). A passive cable adapter will NOT work for this conversion. Active adapters have their own circuitry powered by USB or the signal itself to perform the conversion.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-11',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'Which Thunderbolt version first switched from the Mini DisplayPort connector to the USB-C connector?',
    choices: ch('Thunderbolt 1', 'Thunderbolt 2', 'Thunderbolt 3', 'Thunderbolt 4', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Thunderbolt 3 (released 2015) was the first version to adopt the USB-C physical connector form factor, running at 40 Gbps. Thunderbolt 1 and 2 used the Mini DisplayPort connector. Thunderbolt 4 (2020) also uses USB-C and maintains 40 Gbps while adding stricter requirements (PCIe 3.0 x4, mandatory docking support).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-12',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'A coaxial cable used for cable TV and internet service in residential installations is which type?',
    choices: ch('RG-59', 'RG-6', 'RG-11', 'RG-8', 'b'),
    correctAnswer: ca('b'),
    explanation: 'RG-6 is the standard coaxial cable used for cable television (CATV) and cable internet in homes, using an F-type connector. RG-59 is thinner and used for short CCTV/analog video runs. RG-11 is thicker for long outdoor runs. RG-8 is used for amateur radio. The "RG" designation stands for "Radio Guide."',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-13',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'A DVI cable only carries digital signals with no analog pins. Which DVI type is this?',
    choices: ch('DVI-A (Analog)', 'DVI-D (Digital)', 'DVI-I (Integrated)', 'DVI-P (Passive)', 'b'),
    correctAnswer: ca('b'),
    explanation: 'DVI-D carries only digital signal and lacks the 4 analog pins present on DVI-I. It connects digital source to digital display with no analog capability. DVI-A is analog only. DVI-I has both digital and analog pins. DVI-P does not exist. If you need to connect to an analog VGA monitor, you need a DVI-I port (not DVI-D).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-2-14',
    topicId: 'topic-c1-3-2',
    type: 'single_choice',
    stem: 'The 24-pin ATX connector from the power supply connects to which component?',
    choices: ch('CPU', 'GPU (graphics card)', 'Motherboard main power connector', 'Storage drives', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The 24-pin ATX connector provides main power to the motherboard, delivering +3.3V, +5V, +12V, and -12V rails. The CPU uses a separate 8-pin EPS (4+4 pin) connector. GPUs use 6-pin or 8-pin PCIe power connectors. Storage drives use 15-pin SATA power or 4-pin Molex connectors.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.3 RAM Characteristics (12 questions) ───────────────────────────────

  {
    id: 'q-c1-3-3-01',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'How many pins does a standard DDR4 desktop DIMM module have?',
    choices: ch('184', '240', '288', '294', 'c'),
    correctAnswer: ca('c'),
    explanation: 'DDR4 DIMM (used in desktops) has 288 pins. DDR3 had 240 pins, DDR2 had 240 pins, and DDR1 had 184 pins. DDR5 also uses 288 pins but has a different notch position, making DDR4 and DDR5 physically incompatible despite having the same pin count.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-02',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'Which type of RAM is designed to detect and correct single-bit memory errors, commonly used in servers?',
    choices: ch('DDR5', 'Registered DIMM', 'ECC (Error Correcting Code)', 'LPDDR', 'c'),
    correctAnswer: ca('c'),
    explanation: 'ECC (Error Correcting Code) RAM uses extra chips on the module to detect and correct single-bit errors in real time. This prevents random data corruption and is essential for servers, workstations, and any system where reliability is critical. ECC RAM typically requires server/workstation chipsets and is slightly slower and more expensive than non-ECC.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-03',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'SO-DIMM memory modules are used in which type of device?',
    choices: ch('Desktop tower computers', 'Server rack units', 'Laptops and small form factor computers', 'Mainframe systems', 'c'),
    correctAnswer: ca('c'),
    explanation: 'SO-DIMM (Small Outline DIMM) is a smaller version of the DIMM module used in laptops, mini-PCs, and other space-constrained devices. DDR4 SO-DIMM has 260 pins (vs 288 for DIMM). DDR5 SO-DIMM has 262 pins. They are physically incompatible with standard DIMM desktop slots.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-04',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'Compared to DDR4, which statement about DDR5 RAM is accurate?',
    choices: ch('DDR5 uses 1.35V, same as DDR4', 'DDR5 uses 1.1V and offers higher bandwidth than DDR4', 'DDR5 is interchangeable with DDR4 slots', 'DDR5 has fewer pins than DDR4', 'b'),
    correctAnswer: ca('b'),
    explanation: 'DDR5 operates at 1.1V (vs DDR4 at 1.2V), providing better power efficiency. DDR5 starts at 4800 MT/s (vs DDR4 at 3200 MT/s maximum standard), offering significantly higher bandwidth. DDR5 uses 288 pins like DDR4 but has a different notch position making them physically incompatible. DDR5 also includes on-die ECC.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-05',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'A technician installs two identical 8GB RAM sticks in alternating slots (A1 and B1) on a motherboard. What feature does this enable?',
    choices: ch('ECC memory protection', 'Dual-channel memory', 'Quad-channel memory', 'Overclocked XMP profile', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Installing matching RAM sticks in the paired slots (typically every other slot, designated A1/B1 or 1/3 on a 4-slot board) enables dual-channel mode, which doubles the memory bus width from 64-bit to 128-bit, increasing memory bandwidth by up to 2×. The motherboard manual specifies which slots to populate for dual-channel.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-06',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'DDR4 and DDR5 DIMMs both have 288 pins. Why can they NOT be used in the same motherboard slot?',
    choices: ch('They run at different voltages', 'The notch (key) is in a different position', 'DDR5 requires a different number of memory channels', 'They have incompatible clock controllers', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Although both DDR4 and DDR5 DIMMs have 288 pins, the physical key notch is in a different position, preventing the wrong generation from being physically inserted into a slot. This is intentional to prevent damage from installing the wrong memory type. Additionally, the memory controller on the CPU/motherboard is generation-specific.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-07',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'A server administrator needs maximum RAM capacity with error correction. Which RAM type should be selected?',
    choices: ch('Non-ECC DDR4 3200 MHz', 'Registered ECC DDR4 (RDIMM)', 'LPDDR5', 'Gaming DDR4 with XMP', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Registered (Buffered) ECC RAM (RDIMM) includes both error correction (ECC) and a register chip between the memory controller and RAM chips. This reduces electrical load on the memory controller, allowing higher capacities per channel (up to 256GB per DIMM). Essential for enterprise servers needing reliability and large RAM configurations.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-08',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'A DDR4 SO-DIMM laptop module has how many pins?',
    choices: ch('200', '204', '260', '288', 'c'),
    correctAnswer: ca('c'),
    explanation: 'DDR4 SO-DIMM (used in laptops) has 260 pins. DDR3 SO-DIMM had 204 pins. DDR2 SO-DIMM had 200 pins. DDR5 SO-DIMM has 262 pins. SO-DIMMs are about half the length of full-size DIMMs, making them suitable for the tight spaces inside laptops.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-09',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'A system experiences random crashes and memory-related BSOD errors (such as MEMORY_MANAGEMENT) during intensive workloads. Which component should be tested FIRST?',
    choices: ch('CPU thermal paste', 'Storage drive (S.M.A.R.T.)', 'RAM modules', 'Power supply', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Memory-related BSOD stop codes such as MEMORY_MANAGEMENT, PAGE_FAULT_IN_NONPAGED_AREA, and SYSTEM_SERVICE_EXCEPTION are strongly indicative of faulty RAM. Test with Windows Memory Diagnostic or MemTest86 (boot-time tool). Reseat RAM first, then test one stick at a time to isolate the failing module.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-10',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'What does LPDDR stand for?',
    choices: ch('Large Page Double Data Rate', 'Low Power Double Data Rate', 'Logical Partitioned Double Data Rate', 'Licensed Protocol DDR', 'b'),
    correctAnswer: ca('b'),
    explanation: 'LPDDR (Low Power Double Data Rate) is a variant of DDR RAM optimized for mobile devices such as smartphones, tablets, and ultra-thin laptops. It uses less power than standard DDR by operating at lower voltages (e.g., LPDDR5 at 1.05V vs DDR5 at 1.1V). LPDDR is typically soldered onto the board rather than in a removable module.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-11',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'A desktop motherboard has 4 RAM slots currently populated with 2×8GB sticks. What is the best upgrade approach to reach 32GB while maintaining dual-channel?',
    choices: ch('Remove both sticks, install one 32GB stick', 'Add two more 8GB sticks in the empty slots', 'Replace both sticks with two 16GB sticks', 'Enable XMP to effectively double current capacity', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Adding two identical 8GB sticks in the two empty slots fills all 4 slots with matching modules. This maintains dual-channel operation (4×8GB = 32GB in dual-channel). Installing a single 32GB stick would give 32GB but only in single-channel, reducing bandwidth. XMP is an overclocking profile that does not change RAM capacity.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-3-12',
    topicId: 'topic-c1-3-3',
    type: 'single_choice',
    stem: 'A RAM module labeled "DDR4-3200" transfers data at what rate?',
    choices: ch('3200 MHz base clock (6400 MT/s effective)', '3200 MT/s (megatransfers per second)', '3200 MB/s bandwidth', '3200 ns latency', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The number in DDR4-3200 represents the data transfer rate in megatransfers per second (MT/s). DDR (Double Data Rate) transfers data on both the rising and falling clock edges, so a 1600 MHz base clock produces 3200 MT/s. The maximum theoretical bandwidth is 3200 MT/s × 8 bytes = 25,600 MB/s per channel.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.4 Storage Devices (14 questions) ───────────────────────────────────

  {
    id: 'q-c1-3-4-01',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'Which storage interface uses the PCIe bus to achieve significantly faster speeds than SATA?',
    choices: ch('SAS (Serial Attached SCSI)', 'eSATA', 'NVMe (Non-Volatile Memory Express)', 'SCSI', 'c'),
    correctAnswer: ca('c'),
    explanation: 'NVMe (Non-Volatile Memory Express) is a protocol designed specifically for flash storage that uses the PCIe bus. NVMe SSDs on PCIe 4.0 achieve ~7,000 MB/s read speeds, compared to ~550 MB/s for SATA SSDs. SATA is limited by its 6 Gbps interface. NVMe drives typically plug into M.2 slots or U.2 connectors.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-02',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'What is the minimum number of drives required to implement RAID 5?',
    choices: ch('2', '3', '4', '5', 'b'),
    correctAnswer: ca('b'),
    explanation: 'RAID 5 requires a minimum of 3 drives. It uses striping with distributed parity, meaning parity information is spread across all drives. With 3 drives, usable capacity is 2/3 of total (n-1 drives). RAID 5 can survive the failure of any single drive. RAID 6 requires 4 drives and can survive 2 simultaneous failures.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-03',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'An M.2 SSD labeled "2280" has what dimensions?',
    choices: ch('22mm × 42mm', '22mm × 60mm', '22mm × 80mm', '20mm × 80mm', 'c'),
    correctAnswer: ca('c'),
    explanation: 'M.2 drive names encode their dimensions: the first two digits are width in mm, the remaining digits are length in mm. So "2280" = 22mm wide × 80mm long. 2280 is the most common M.2 length. Other lengths exist: 2242 (42mm), 2260 (60mm), and 22110 (110mm for enterprise). All M.2 modules are 22mm wide.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-04',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'Which RAID level provides maximum read/write performance through striping but offers NO fault tolerance?',
    choices: ch('RAID 0', 'RAID 1', 'RAID 5', 'RAID 10', 'a'),
    correctAnswer: ca('a'),
    explanation: 'RAID 0 (striping) splits data evenly across all drives with no parity or mirroring, providing maximum performance (both read and write speeds improve). However, if any single drive fails, ALL data is lost because there is no redundancy. RAID 0 also increases the total storage capacity (all drives combined).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-05',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'What is the theoretical maximum data transfer speed of SATA III?',
    choices: ch('1.5 Gbps', '3.0 Gbps', '6.0 Gbps', '12.0 Gbps', 'c'),
    correctAnswer: ca('c'),
    explanation: 'SATA III (also called SATA 6Gb/s or SATA Revision 3.0) has a theoretical maximum of 6 Gbps. In real-world testing, the effective throughput is approximately 550 MB/s due to encoding overhead. SATA I was 1.5 Gbps and SATA II was 3 Gbps. SAS can achieve 12 Gbps, and NVMe goes far beyond this.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-06',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'A user wants redundancy so their data is safe if one drive fails. Which RAID level creates an exact copy (mirror) of data on two drives?',
    choices: ch('RAID 0', 'RAID 1', 'RAID 5', 'RAID 6', 'b'),
    correctAnswer: ca('b'),
    explanation: 'RAID 1 (mirroring) writes identical data to two drives simultaneously. If one drive fails, the other contains a complete copy. Usable capacity equals one drive (50% efficiency). Read performance can improve slightly (reads can come from either drive) but write performance does not improve. It is the simplest form of hardware redundancy.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-07',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'What does S.M.A.R.T. stand for in the context of storage drives?',
    choices: ch('System Management and Real-time Technology', 'Self-Monitoring, Analysis, and Reporting Technology', 'Solid-state Memory Advanced Reliability Tracking', 'Sequential Mechanical Analysis and Recovery Testing', 'b'),
    correctAnswer: ca('b'),
    explanation: 'S.M.A.R.T. (Self-Monitoring, Analysis, and Reporting Technology) is a monitoring system built into HDDs and SSDs that tracks various health metrics (reallocated sectors, spin-up time, temperature, etc.) to predict failures before they occur. Tools like CrystalDiskInfo can read S.M.A.R.T. data. A failing S.M.A.R.T. status should trigger immediate backup.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-08',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'RAID 10 is a combination of which two RAID levels?',
    choices: ch('RAID 0 and RAID 5', 'RAID 1 and RAID 5', 'RAID 0 and RAID 1', 'RAID 1 and RAID 6', 'c'),
    correctAnswer: ca('c'),
    explanation: 'RAID 10 (also written RAID 1+0) combines mirroring (RAID 1) and striping (RAID 0). Minimum 4 drives. Data is first mirrored across pairs, then striped across pairs, providing both performance and redundancy. It can survive one drive failure per mirrored pair. RAID 10 has better write performance than RAID 5 but 50% storage efficiency.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-09',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'An M.2 SSD does NOT require which of the following that a 3.5-inch HDD requires?',
    choices: ch('A PCIe connection', 'A driver', 'A separate data cable and separate power connector', 'Firmware', 'c'),
    correctAnswer: ca('c'),
    explanation: 'M.2 SSDs receive both data connectivity and power directly through the M.2 slot on the motherboard — no separate data cable (SATA or otherwise) and no separate power connector are needed. This makes M.2 drives much cleaner to install. 3.5-inch HDDs need a SATA data cable and a SATA or Molex power connector.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-10',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'A single-layer Blu-ray disc holds how much data?',
    choices: ch('4.7 GB', '8.5 GB', '25 GB', '50 GB', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A single-layer Blu-ray disc holds 25 GB. A dual-layer Blu-ray holds 50 GB. Compare this to DVD: single-layer 4.7 GB, dual-layer 8.5 GB. Blu-ray uses a blue-violet laser (405nm wavelength, hence the name) which has a shorter wavelength than the red laser used by DVDs, allowing higher data density.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-11',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'A company needs a RAID configuration where performance is critical AND the array can survive the failure of any TWO drives simultaneously. Which RAID level meets this requirement?',
    choices: ch('RAID 5', 'RAID 6', 'RAID 1', 'RAID 0', 'b'),
    correctAnswer: ca('b'),
    explanation: 'RAID 6 uses dual distributed parity, meaning two parity blocks are written per stripe. It can survive any two simultaneous drive failures. Minimum 4 drives required. RAID 5 can only survive one drive failure. RAID 6 has slightly lower write performance than RAID 5 due to calculating two parity sets, but provides higher fault tolerance.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-12',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'A drive is reporting S.M.A.R.T. errors. What is the MOST important immediate action?',
    choices: ch('Run disk defragmentation', 'Perform a full format of the drive', 'Back up all data from the drive immediately', 'Install the latest drivers', 'c'),
    correctAnswer: ca('c'),
    explanation: 'S.M.A.R.T. errors indicate drive health is deteriorating and failure may be imminent. The immediate priority is backing up all data before the drive fails completely. After backing up, you can diagnose further, run chkdsk, or replace the drive. Defragmentation can stress a failing drive further, and reformatting risks completing data loss.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-13',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'What is a "hot spare" in a RAID array?',
    choices: ch('A drive that runs at higher temperature for performance', 'A standby drive that automatically begins rebuilding when another drive fails', 'A drive removed while the system is running', 'An SSD used for caching alongside HDDs', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A hot spare is an unallocated drive in the RAID enclosure that automatically starts rebuilding the array when a drive fails, without requiring human intervention. This minimizes the time the array is in a degraded (vulnerable) state. Hot-pluggable drive bays allow the failed drive to be replaced while the system continues running.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-4-14',
    topicId: 'topic-c1-3-4',
    type: 'single_choice',
    stem: 'Compared to a SATA SSD, a NVMe PCIe 4.0 SSD is approximately how much faster in sequential read speed?',
    choices: ch('About the same speed', 'About 2× faster (1,100 vs 550 MB/s)', 'About 13× faster (7,000 vs 550 MB/s)', 'About 100× faster', 'c'),
    correctAnswer: ca('c'),
    explanation: 'SATA SSDs are limited to approximately 550 MB/s read by the SATA III interface (6 Gbps). NVMe SSDs on PCIe 4.0 typically achieve 6,000–7,000 MB/s sequential read, making them roughly 12–13× faster. PCIe 3.0 NVMe drives achieve ~3,500 MB/s (~6× faster). For random IOPS performance, NVMe also far exceeds SATA.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.5 Motherboards, CPUs, Add-on Cards (14 questions) ──────────────────

  {
    id: 'q-c1-3-5-01',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'What are the dimensions of a Mini-ITX motherboard?',
    choices: ch('305mm × 244mm', '244mm × 244mm', '170mm × 170mm', '150mm × 150mm', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Mini-ITX measures 170mm × 170mm and is the smallest common consumer motherboard form factor. Micro-ATX is 244mm × 244mm. Standard ATX is 305mm × 244mm. Mini-ITX typically has only one PCIe x16 slot, limiting expansion. It is used in small form factor (SFF) builds, HTPCs, and compact workstations.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-02',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'What component on the motherboard maintains BIOS/UEFI settings (time, date, boot order) when the computer is unplugged?',
    choices: ch('TPM chip', 'Northbridge', 'CMOS memory backed by a CR2032 battery', 'Flash ROM (non-volatile)', 'c'),
    correctAnswer: ca('c'),
    explanation: 'CMOS (Complementary Metal-Oxide-Semiconductor) is a small amount of memory that stores BIOS settings. It is kept powered by a CR2032 coin cell battery on the motherboard. When this battery dies (typically after 5-10 years), the system loses time/date settings and BIOS customizations on each power cycle. UEFI settings are still stored in CMOS.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-03',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'Which PCIe slot configuration provides the most bandwidth and is used for discrete graphics cards?',
    choices: ch('PCIe x1', 'PCIe x4', 'PCIe x8', 'PCIe x16', 'd'),
    correctAnswer: ca('d'),
    explanation: 'PCIe x16 provides the most lanes (16) and highest bandwidth, making it the standard slot for discrete GPUs. PCIe 4.0 x16 delivers 32 GB/s. PCIe x1 slots are for sound cards, NICs, and other low-bandwidth add-in cards. PCIe x4 is used for NVMe add-in cards and some smaller GPUs. Higher-number slots are physically longer.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-04',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'AMD Ryzen 7000 series processors use which CPU socket?',
    choices: ch('AM4', 'AM5', 'TR4 (TRX40)', 'LGA1700', 'b'),
    correctAnswer: ca('b'),
    explanation: 'AMD Ryzen 7000 series (Zen 4 architecture) uses the AM5 socket, introduced in 2022. AM5 is the first AMD consumer socket to use LGA (Land Grid Array) with pins on the socket rather than the CPU. AM4 was used for Ryzen 1000-5000 series. AM5 is expected to have a long lifespan through multiple CPU generations.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-05',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'Which UEFI security feature prevents booting from unsigned or unauthorized operating systems to protect against bootkit malware?',
    choices: ch('TPM 2.0', 'Fast Boot', 'Secure Boot', 'BIOS Password', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Secure Boot is a UEFI feature that verifies digital signatures of bootloaders, OS kernels, and drivers during the boot process. If a signature is not recognized, the system refuses to boot, blocking bootkits and rootkits that target the pre-OS environment. Secure Boot was required for the "Designed for Windows 8" logo and is required for Windows 11.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-06',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'What is the primary function of a TPM (Trusted Platform Module) chip on a motherboard?',
    choices: ch('Increase CPU processing speed', 'Store cryptographic keys securely and enable hardware-based encryption', 'Control motherboard fan speeds', 'Allocate PCIe bandwidth dynamically', 'b'),
    correctAnswer: ca('b'),
    explanation: 'TPM (Trusted Platform Module) is a dedicated hardware security chip that generates, stores, and manages cryptographic keys in a tamper-resistant way. It powers features like BitLocker drive encryption (Windows), measured boot (integrity verification), and platform authentication. TPM 2.0 is required for Windows 11. It is separate from the CPU and operates independently.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-07',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'POST (Power-On Self-Test) runs at which point in the boot sequence?',
    choices: ch('After the OS begins loading', 'When a user logs into Windows', 'Immediately when the computer is powered on, before the OS loads', 'Only after a hardware change is detected', 'c'),
    correctAnswer: ca('c'),
    explanation: 'POST (Power-On Self-Test) is the initial diagnostic routine executed by the BIOS/UEFI firmware the moment the computer receives power, before any OS begins loading. It tests the CPU, RAM, storage controllers, and other hardware. POST results are communicated through beep codes or on-screen messages. If POST fails, the system will not boot.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-08',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'How does bandwidth per lane in PCIe 4.0 compare to PCIe 3.0?',
    choices: ch('Same bandwidth per lane', '1.5× more bandwidth (12 Gbps vs 8 Gbps)', '2× more bandwidth (16 Gbps vs 8 Gbps)', '4× more bandwidth (32 Gbps vs 8 Gbps)', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Each PCIe generation doubles the bandwidth per lane: PCIe 3.0 provides 8 Gbps per lane, PCIe 4.0 provides 16 Gbps per lane, PCIe 5.0 provides 32 Gbps per lane. A PCIe 4.0 x16 slot provides 256 Gbps total bidirectional bandwidth. This progression allows newer GPUs and NVMe drives to fully utilize faster connections.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-09',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'Intel 12th generation (Alder Lake) and 13th generation (Raptor Lake) processors use which socket?',
    choices: ch('LGA1151', 'LGA1200', 'LGA1700', 'LGA1851', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Intel LGA1700 was introduced with 12th generation (Alder Lake) in late 2021 and continued through 13th and 14th generation (Raptor Lake). LGA1700 has 1700 contact points vs 1200 for the previous LGA1200 platform. Intel LGA1851 was introduced for Core Ultra 200 series (Arrow Lake) in 2024. LGA1151 was for 6th–9th gen.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-10',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'A user reports the computer clock keeps resetting to January 2000 on every boot. What is the most likely cause?',
    choices: ch('Corrupted OS installation', 'Bad RAM causing CMOS data corruption', 'Dead CMOS battery (CR2032)', 'Malware modifying system time', 'c'),
    correctAnswer: ca('c'),
    explanation: 'When the CMOS battery dies, the CMOS loses its stored settings including date and time on every power cycle. The system reverts to a default date (often January 1, 1980 or 2000 depending on BIOS). Replacing the CR2032 coin cell battery (typically under $2) and resetting date/time in UEFI will permanently fix this issue.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-11',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'A workstation has a PCIe x16 slot (GPU) and a PCIe x4 slot (NVMe). A network adapter needs to be installed. Which slot should be used?',
    choices: ch('PCIe x16 (remove the GPU)', 'PCIe x4 (move the NVMe drive)', 'PCIe x1 slot', 'PCI slot (legacy)', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A standard NIC (network adapter) requires only PCIe x1 bandwidth, as gigabit or even 10 GbE networking does not need more than 10 Gbps bandwidth. Installing it in a PCIe x1 slot leaves the GPU and NVMe in their optimal slots. PCIe cards can always be installed in a larger slot (a x1 card fits in x4 or x16) but cannot go smaller.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-12',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'What is the standard ATX motherboard size?',
    choices: ch('244mm × 244mm', '305mm × 244mm', '170mm × 170mm', '330mm × 305mm', 'b'),
    correctAnswer: ca('b'),
    explanation: 'ATX (Advanced Technology eXtended) motherboards measure 305mm × 244mm. This is the most common desktop motherboard form factor, offering the most expansion slots (up to 7 PCIe/PCI slots). ATX cases are designed to fit ATX boards. Micro-ATX (244×244mm) and Mini-ITX (170×170mm) are smaller alternatives that fit in ATX cases with mounting adapters.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-13',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'Which statement BEST describes the role of the chipset on a modern motherboard?',
    choices: ch('It executes application instructions faster than the CPU', 'It manages communication between the CPU, RAM, storage, and peripheral buses', 'It stores BIOS firmware and cryptographic keys', 'It supplies power regulation to the CPU', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The chipset (now typically a single PCH — Platform Controller Hub — on modern boards) manages the communication pathways between the CPU and other motherboard components including SATA controllers, USB controllers, PCIe lanes for non-GPU devices, and the management engine. The CPU communicates with the chipset via a high-speed DMI (Direct Media Interface) link.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-5-14',
    topicId: 'topic-c1-3-5',
    type: 'single_choice',
    stem: 'The front panel connector block (F_PANEL) on a motherboard includes connectors for which functions?',
    choices: ch('HDMI output and USB-C', 'Power switch, reset switch, power LED, and HDD activity LED', 'SATA data cables and CPU power', 'Audio output and microphone input', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The F_PANEL (front panel connector) area on the motherboard has small 2-pin headers for the power button (PWR_SW), reset button (RST_SW), power LED (PWR_LED), and HDD activity LED (HDD_LED). The exact layout varies by manufacturer — always consult the motherboard manual. Incorrect connections will result in buttons/LEDs not working but will not damage hardware.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.6 Power Supply (10 questions) ──────────────────────────────────────

  {
    id: 'q-c1-3-6-01',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'What efficiency percentages (at 20%, 50%, and 100% load) must a PSU achieve to earn the 80 Plus Gold certification?',
    choices: ch('80% / 80% / 80%', '82% / 85% / 82%', '87% / 90% / 87%', '90% / 92% / 89%', 'c'),
    correctAnswer: ca('c'),
    explanation: '80 Plus Gold requires 87% efficiency at 20% load, 90% at 50% load, and 87% at 100% load. The certifications in order are: 80 Plus (80/80/80), Bronze (82/85/82), Silver (85/88/85), Gold (87/90/87), Platinum (90/92/89), Titanium (92/94/90). Higher efficiency means less electricity wasted as heat.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-6-02',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'How many pins does the main ATX power connector (from PSU to motherboard) have?',
    choices: ch('20', '24', '8', '6', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The main ATX motherboard power connector is 24 pins. Older ATX 1.x standards used a 20-pin connector; the extra 4 pins were added in ATX12V 2.x to provide additional +12V current. Most modern motherboards and PSUs use the 24-pin connector, though some PSUs have a 20+4 pin connector that separates for backward compatibility.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-6-03',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'What connector from the PSU supplies power directly to the CPU?',
    choices: ch('24-pin ATX main connector', '6-pin PCIe connector', '8-pin EPS (4+4 pin) CPU connector', 'SATA power connector', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The 8-pin EPS (ATX12V) connector — also sold as 4+4 pin for flexibility — connects from the PSU to the CPU power header on the motherboard near the CPU socket. It provides the +12V dedicated to the CPU. High-end enthusiast motherboards may have two 8-pin CPU connectors for extreme overclocking, requiring a PSU with two EPS connectors.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-6-04',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'An 8-pin PCIe power connector can supply how much power to a graphics card?',
    choices: ch('75 W', '100 W', '150 W', '300 W', 'c'),
    correctAnswer: ca('c'),
    explanation: 'An 8-pin PCIe connector (often sold as 6+2 pin) can deliver 150W to a GPU. A 6-pin PCIe connector provides 75W. The PCIe slot itself provides an additional 75W, so a GPU with one 8-pin connector can receive up to 225W total. High-end GPUs use two 8-pin connectors (300W from connectors + 75W from slot = 375W). The newer PCIe 5.0 16-pin connector provides up to 600W.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-6-05',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'What is the primary advantage of a fully modular PSU compared to a non-modular PSU?',
    choices: ch('Higher maximum wattage output', 'Better efficiency rating (higher 80 Plus tier)', 'All cables are detachable, reducing cable clutter and improving airflow', 'Lower cost due to fewer components', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A fully modular PSU has no permanently attached cables — all cables plug into the PSU only when needed. This reduces cable clutter inside the case, improves airflow, and makes cable management easier. Non-modular PSUs have all cables hardwired. Semi-modular has fixed essential cables (24-pin, CPU) with modular peripheral cables. Fully modular PSUs are typically more expensive, not cheaper.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-6-06',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'Which voltage rail on an ATX power supply provides power to the CPU and GPU motors?',
    choices: ch('+3.3V', '+5V', '+12V', '-12V', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The +12V rail is the most important rail in a modern ATX PSU, powering the CPU (via 8-pin EPS connector), GPU (via PCIe connectors), and motor-driven devices (HDD spindle motors, case fans). +3.3V and +5V power logic circuits and older devices. -12V is a small rail for legacy serial port circuitry. Modern systems draw 90%+ of their power from the +12V rail.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-6-07',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'What is the purpose of the +5VSB (standby) voltage rail?',
    choices: ch('Powers USB 3.0 during full operation', 'Provides standby power for Wake-on-LAN and scheduled start features when the system is "off"', 'Acts as a secondary CPU power rail', 'Powers the PCIe x16 slot', 'b'),
    correctAnswer: ca('b'),
    explanation: '+5VSB (5 Volt Standby) remains active even when the computer is in a "soft off" (S5) or sleep state. It powers the power button circuit, Wake-on-LAN network adapter, USB wake capability, and real-time clock. This is why you can wake a computer by pressing the power button, moving a USB mouse, or receiving a magic packet over the network, even when it appears to be off.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-6-08',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'A system has a CPU with 125W TDP and a GPU with 250W TDP. Other components (RAM, drives, fans) consume approximately 50W. What is the MINIMUM recommended PSU wattage?',
    choices: ch('350W', '425W', '550W', '750W', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Total consumption: 125W + 250W + 50W = 425W. Adding a 20–30% headroom factor: 425W × 1.30 = 552.5W. A 550W PSU is the minimum practical choice. Running a PSU near 100% capacity is inefficient and stresses the unit. A 650W PSU would provide more headroom. 350W and 425W are insufficient; 750W is acceptable but larger than needed.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-6-09',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'A 6-pin PCIe power connector can deliver how many watts to a graphics card?',
    choices: ch('30W', '50W', '75W', '150W', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A 6-pin PCIe power connector provides up to 75W. Combined with the 75W from the PCIe x16 slot itself, a GPU with only a 6-pin connector can receive up to 150W total. Entry-level and mid-range GPUs often require only a single 6-pin connector. The 8-pin (6+2) PCIe connector provides 150W, while the newer 16-pin PCIe 5.0 connector delivers up to 600W.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-6-10',
    topicId: 'topic-c1-3-6',
    type: 'single_choice',
    stem: 'At what load percentage do PSUs typically operate at their highest efficiency?',
    choices: ch('100% (full load)', '75%', '50%', '20% (low load)', 'c'),
    correctAnswer: ca('c'),
    explanation: 'PSUs are most efficient at approximately 50% of their rated load — this is why the 80 Plus certification tests at 20%, 50%, and 100%. A 650W PSU runs best when powering a ~325W system. This is one reason to buy a slightly oversized PSU: a 650W unit in a 300W system runs efficiently and has headroom for upgrades.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.7 Printers and MFDs (13 questions) ─────────────────────────────────

  {
    id: 'q-c1-3-7-01',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'In the laser printing process, which step uses heat and pressure to permanently bond toner particles into the paper fibers?',
    choices: ch('Transferring', 'Developing', 'Fusing', 'Charging', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The fusing step uses a heated fuser assembly (150–200°C) and pressure rollers to melt the toner particles and embed them into the paper fibers, creating a permanent bond. This is why laser-printed pages come out warm. The transfer step only moves toner from the drum to the paper electrostatically; without fusing, the toner would simply wipe off.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-02',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'What is the FIRST step in the laser printing process?',
    choices: ch('Charging (applying charge to drum)', 'Processing (converting data to bitmap)', 'Exposing (writing with laser)', 'Transferring (moving toner to paper)', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The first step is Processing: the printer\'s formatter board (RIP — Raster Image Processor) converts the print job data into a raster bitmap the printer engine can use. The complete sequence is: 1.Processing → 2.Charging → 3.Exposing → 4.Developing → 5.Transferring → 6.Fusing → 7.Cleaning. Some sources list 6 steps by combining processing with the sequence start.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-03',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'Which inkjet technology uses heat to form a vapor bubble that forces a droplet of ink through the nozzle?',
    choices: ch('Piezoelectric', 'Thermal / Bubble Jet', 'Continuous flow', 'Laser toner', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Thermal inkjet (also called bubble jet, popularized by Canon and HP) heats the ink rapidly to over 300°C, creating a vapor bubble that expands and forces an ink droplet through the nozzle. Piezoelectric inkjet (used by Epson) uses a piezo crystal that changes shape when electrically charged to eject ink without heat, allowing more ink types and finer droplets.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-04',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'An office needs to print multi-part forms (carbon copies) for invoices. Which printer type is the ONLY one that can do this?',
    choices: ch('Laser printer', 'Inkjet printer', 'Thermal printer', 'Impact (dot matrix) printer', 'd'),
    correctAnswer: ca('d'),
    explanation: 'Impact printers (dot matrix) physically strike an ink ribbon against the paper with pins, creating enough physical pressure to simultaneously print through multiple layers of carbon/carbonless paper forms. No other printer type can produce multi-part forms through physical impact. Impact printers are noisy but still used in environments requiring carbon copies (shipping, auto parts, warehouses).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-05',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'A receipt printer at a retail store uses no ink cartridges or ribbons. What type of printer is this?',
    choices: ch('Laser printer', 'Inkjet printer', 'Direct thermal printer', 'Thermal transfer printer', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Direct thermal printers use heat-sensitive paper that darkens when exposed to the printhead\'s heat — no ink, toner, or ribbon required. This makes them low-maintenance and compact, ideal for receipts, shipping labels, and wristbands. The trade-off is that thermal paper can fade over time with heat or UV exposure. Do not confuse with thermal transfer printers, which do use a ribbon.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-06',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'In the laser printing transfer step, what does the transfer roller apply to the paper to attract toner from the drum?',
    choices: ch('A negative charge matching the drum', 'Toner directly', 'A positive charge opposite the drum', 'UV light to activate toner', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The transfer roller or corona wire applies a positive charge to the back of the paper. Since the toner particles on the drum are negatively charged, they are electrostatically attracted to the positively charged paper, pulling toner off the drum and onto the paper. The paper then passes to the fuser where the toner is permanently bonded.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-07',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'FDM is a common 3D printing technology. What does FDM stand for?',
    choices: ch('Fast Digital Modeling', 'Fused Deposition Modeling', 'Flexible Display Manufacturing', 'Fiber Deposition Method', 'b'),
    correctAnswer: ca('b'),
    explanation: 'FDM (Fused Deposition Modeling) is the most common 3D printing process. A heated nozzle (extruder) melts thermoplastic filament (typically PLA or ABS) and deposits it layer by layer on a build platform following a 3D model. FDM printers are affordable and widely available. SLA (stereolithography) uses UV resin cured by a laser and produces higher resolution prints.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-08',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'In a laser printer, the primary charge roller (corona wire) performs which function?',
    choices: ch('Transfers toner from the drum to paper', 'Fuses toner to paper with heat', 'Applies a uniform negative charge across the photosensitive drum surface', 'Writes the image on the drum using laser light', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The primary charge roller (or corona wire in older printers) applies a uniform high-voltage negative charge (approximately -600V) to the entire surface of the photosensitive drum. This prepares the drum for the exposing step where the laser selectively reduces the charge in image areas to approximately -100V, creating the latent electrostatic image that attracts toner.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-09',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'What does the laser beam create on the photosensitive drum during the exposing step?',
    choices: ch('Physical grooves in the drum surface', 'A heat pattern that melts toner', 'An electrostatic latent image (pattern of discharged areas)', 'Visible light reflected onto paper', 'c'),
    correctAnswer: ca('c'),
    explanation: 'During the exposing step, the laser beam scans across the drum and selectively reduces the negative charge from -600V to approximately -100V in areas that should print. This creates an invisible electrostatic latent image on the drum. In the developing step, toner (which is negatively charged) is repelled from -600V areas and attracted to the -100V (laser-exposed) areas.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-10',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'Which printer type uses small pins that strike an ink-soaked ribbon to form characters?',
    choices: ch('Laser', 'Inkjet', 'Thermal transfer', 'Dot matrix (impact)', 'd'),
    correctAnswer: ca('d'),
    explanation: 'Dot matrix printers (impact printers) have a printhead with a grid (matrix) of small metal pins. The pins fire rapidly to strike an ink ribbon against paper, forming characters from patterns of dots. They are slow and noisy but can print multi-part forms and work in dusty/greasy environments where other printers fail (industrial, automotive).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-11',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'What does "automatic duplex printing" refer to?',
    choices: ch('Printing two identical copies simultaneously', 'Automatically printing on both sides of each sheet', 'Printing at double the resolution', 'Using two print heads for faster output', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Duplex printing means printing on both sides of a sheet of paper. "Automatic" duplex means the printer can flip the paper and print the reverse side without manual intervention (compared to manual duplex where the user must flip pages). Duplex printing can cut paper usage by up to 50%, saving costs in high-volume environments.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-12',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'MFD stands for which term in the context of office devices?',
    choices: ch('Multiple Feed Device', 'Multifunction Device', 'Multi-Format Display', 'Modular Fax Device', 'b'),
    correctAnswer: ca('b'),
    explanation: 'An MFD (Multifunction Device, also called MFP — Multifunction Printer) combines multiple functions in one unit: typically printing, scanning, copying, and faxing. MFDs reduce desk space, cost less than buying separate devices, and simplify management. Network-connected MFDs allow scan-to-email and scan-to-folder workflows.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-7-13',
    topicId: 'topic-c1-3-7',
    type: 'single_choice',
    stem: 'A technician needs to share a single network printer with 10 computers without installing a dedicated server. What is the most practical method?',
    choices: ch('Connect with USB and share through one PC (print server)', 'Use a parallel port hub', 'Use the printer\'s built-in Ethernet or WiFi network connectivity', 'Purchase separate printers for each user', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Most modern printers have built-in Ethernet (wired) or WiFi network adapters. Connecting the printer directly to the network switch and assigning it an IP address allows all 10 computers to print without a dedicated server. Each computer installs the printer using a TCP/IP port with the printer\'s IP. This is more reliable than sharing through one PC, which would require that PC to stay on.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.8 Printer Maintenance (11 questions) ───────────────────────────────

  {
    id: 'q-c1-3-8-01',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'A laser printer produces pages with a faint, repeated ghost image appearing a few inches below the original text on every page. Which component is MOST likely failing?',
    choices: ch('Toner cartridge (low toner)', 'Fuser assembly or drum unit', 'Transfer belt assembly', 'Paper feed roller', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Ghosting (a faint duplicate image offset from the main print) is typically caused by a failing drum unit that retains a residual charge from the previous rotation, or a fuser assembly not fully erasing the electrical image. The offset distance equals the circumference of the drum or fuser roller. If the ghost appears at regular intervals, measure the interval to identify which roller is failing.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-02',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'Every page from a laser printer has a faint vertical white line running from top to bottom. What is the MOST likely cause?',
    choices: ch('Paper loaded incorrectly', 'Low toner level', 'A scratch on the photosensitive drum or dirt on the laser lens', 'Incorrect paper type setting', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Consistent vertical white lines on every page are caused by a scratch, gouge, or contamination on the photosensitive drum. The damaged area cannot hold the electrostatic charge needed to attract toner, resulting in a permanent white line at that position. A dirty laser lens or mirror can cause similar lines. This typically requires replacing the drum/imaging unit.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-03',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'After replacing an inkjet printer\'s ink cartridge, print quality shows streaks and missing sections. What should be done FIRST?',
    choices: ch('Replace the cartridge with a different brand', 'Run the printhead cleaning utility in the printer software', 'Reinstall the printer driver', 'Run a full system restore', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Streaks and missing sections after a cartridge replacement are typically caused by air bubbles in the ink supply or dried ink residue around the nozzles from the new cartridge installation. Running the automated printhead cleaning cycle (accessible from printer preferences or the printer\'s control panel) purges the nozzles and primes the ink lines. This should be tried 1-3 times before further diagnosis.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-04',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'What is the purpose of running a calibration on a color laser printer?',
    choices: ch('Increase print speed', 'Align the four toner colors (CMYK) for accurate color reproduction', 'Clean the fuser assembly', 'Reset the page count for billing', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Color calibration (also called color registration) adjusts the alignment of the four toner colors (Cyan, Magenta, Yellow, and Key/Black) so they precisely overlap to produce accurate colors. If calibration is off, you may see color fringes around text or color casts in images. Calibration should be run after replacing a toner cartridge, drum, or transfer belt, and periodically in high-volume environments.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-05',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'An inkjet printer that has not been used for three weeks is now producing output with visible gaps and missing colors. What is the MOST likely cause?',
    choices: ch('Empty ink cartridges', 'Clogged print nozzles from dried ink', 'Driver corruption', 'Mechanical paper jam', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When inkjet printers sit unused, ink can dry and clog the microscopic nozzles in the printhead. Running the printhead cleaning cycle (multiple times if needed) should dissolve the dried ink and restore normal output. Some printers have a capping station that seals the printhead when idle to prevent drying. Severe clogs may require manual cleaning with distilled water.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-06',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'What should be used to clean the heating element/printhead of a direct thermal printer?',
    choices: ch('Dry paper towel', 'Isopropyl alcohol (IPA) swab', 'Compressed air only', 'Warm water and soap', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The printhead and heating element of a thermal printer should be cleaned with isopropyl alcohol (70% or higher) on a lint-free swab. IPA removes thermal paper residue, dust, and label adhesive without leaving moisture that could damage electronics. Always allow the printhead to cool completely before cleaning. Clean the platen roller with IPA as well to prevent paper skew.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-07',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'Which laser printer component contains the heat source that melts toner onto paper and must be replaced after a certain page count?',
    choices: ch('Photosensitive drum unit', 'Transfer belt', 'Fuser assembly', 'Primary corona wire', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The fuser assembly contains heated rollers and pressure rollers that melt toner into paper. It has the highest operating temperature of any printer component (up to 200°C) and is subject to significant wear. Laser printer maintenance kits include a replacement fuser assembly (and often rollers) for a specific page count, such as every 150,000 or 200,000 pages. A failing fuser causes smearing prints.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-08',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'A laser printer produces output where text smears and wipes off when touched with a finger. Which component is MOST likely causing this problem?',
    choices: ch('Empty or low toner cartridge', 'Failed fuser assembly (not melting toner properly)', 'Dirty photosensitive drum', 'Incorrect paper size setting', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Smearing toner that wipes off indicates the toner was transferred to the paper (transfer step worked) but was NOT properly fused (melted) into the paper fibers. A failing fuser assembly — where the heating element or pressure rollers are no longer functioning correctly — is the primary cause of this symptom. Replace the fuser assembly to resolve it.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-09',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'Paper frequently jams in the same location inside a laser printer. Which component is MOST likely worn?',
    choices: ch('Fuser assembly', 'Drum unit', 'Pickup/feed rollers', 'Transfer belt', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Pickup rollers (also called feed rollers) grab paper from the input tray and move it through the printer. Over time, rubber rollers wear smooth and lose their grip, failing to advance paper reliably or causing it to feed at an angle, leading to repeated jams in the same area. Pickup roller replacement kits are available for most printers and are included in maintenance kits.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-10',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'Toner accidentally spills onto a surface. What is the recommended cleaning method?',
    choices: ch('Use a regular household vacuum cleaner', 'Use cold water and blot with a cloth (avoid heat)', 'Use a toner-rated vacuum or dry cloth; cold water only on skin', 'Use compressed air to blow it away', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Regular vacuums allow fine toner particles to pass through filters back into the air. Use a vacuum with a HEPA filter or a toner-specific vacuum. For skin contact, use cold water only — hot water will fuse the toner into fabric/skin. Compressed air will disperse toner into the air and lungs. Toner is not toxic in small amounts but should not be inhaled.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-3-8-11',
    topicId: 'topic-c1-3-8',
    type: 'single_choice',
    stem: 'An impact (dot matrix) printer is producing increasingly faint text. What maintenance is needed?',
    choices: ch('Clean the platen roller', 'Replace the ribbon cartridge', 'Adjust the printhead gap closer to the platen', 'Reinstall the printer driver', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Dot matrix printers use an ink-soaked ribbon cartridge. As the ribbon ages and the ink depletes from repeated impacts, print output becomes progressively lighter. Replacing the ribbon cartridge is the standard maintenance action. The ribbon is a consumable item, similar to ink cartridges in inkjet printers. Printhead gap adjustment addresses different symptoms (too dark / too light uniformly).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
]

export const SEED_QUESTIONS = [
  ...CORE1_D3_QUESTIONS,
  ...BATCH1_QUESTIONS,
  ...BATCH2_QUESTIONS,
  ...BATCH3_QUESTIONS,
  ...BATCH4_QUESTIONS,
  ...BATCH5_QUESTIONS,
  ...BATCH6_QUESTIONS,
  ...BATCH7_QUESTIONS,
  ...BATCH8_QUESTIONS,
  ...BATCH9_QUESTIONS,
  ...BATCH10_QUESTIONS,
  ...BATCH11_QUESTIONS,
  ...BATCH12_QUESTIONS,
  ...BATCH13A_QUESTIONS,
  ...BATCH13B_QUESTIONS,
  ...BATCH14A_QUESTIONS,
  ...BATCH14B_QUESTIONS,
  ...BATCH15_QUESTIONS,
  ...BATCH16_QUESTIONS,
  ...BATCH17_QUESTIONS,
]
