// 48 verified practice questions for CompTIA A+ 220-1202 Core 2 Domain 1: Operating Systems
// Covers objectives 1.1–1.6 with accurate, exam-representative content

const NOW = new Date().toISOString()

type Choice = { id: string; text: string; isCorrect: boolean }

function ch(a: string, b: string, c: string, d: string, correct: 'a' | 'b' | 'c' | 'd'): string {
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: correct === 'a' },
    { id: 'b', text: b, isCorrect: correct === 'b' },
    { id: 'c', text: c, isCorrect: correct === 'c' },
    { id: 'd', text: d, isCorrect: correct === 'd' },
  ] as Choice[])
}

function chMulti(
  a: string, b: string, c: string, d: string,
  correct: Array<'a' | 'b' | 'c' | 'd'>
): string {
  const ids = new Set(correct)
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: ids.has('a') },
    { id: 'b', text: b, isCorrect: ids.has('b') },
    { id: 'c', text: c, isCorrect: ids.has('c') },
    { id: 'd', text: d, isCorrect: ids.has('d') },
  ] as Choice[])
}

const ca = (id: 'a' | 'b' | 'c' | 'd') => JSON.stringify(id)
const cam = (...ids: Array<'a' | 'b' | 'c' | 'd'>) => JSON.stringify(ids)

export const BATCH3_QUESTIONS = [

  // ─── 1.1 Common OS Types (8 questions) ─────────────────────────────────────

  {
    id: 'q-c2-1-1-01',
    topicId: 'topic-c2-1-1',
    type: 'single_choice',
    stem: 'A company needs an operating system for a fleet of low-cost laptops where employees only use web applications and cloud storage. Which OS is the best fit?',
    choices: ch('Windows 10 Home', 'macOS', 'ChromeOS', 'Ubuntu Desktop', 'c'),
    correctAnswer: ca('c'),
    explanation: 'ChromeOS is purpose-built for web-centric workflows. It boots in seconds from a read-only partition, runs web and Android apps, costs less to manage (via Google Admin console), and hardware is inexpensive. It is the dominant OS for K-12 and web-only enterprise deployments.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-1-02',
    topicId: 'topic-c2-1-1',
    type: 'single_choice',
    stem: 'Which OS category is best characterized by ARM processors, battery optimization, touch-first interfaces, and sandboxed application environments?',
    choices: ch('Server OS', 'Workstation OS', 'Mobile OS', 'Embedded OS', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Mobile operating systems (iOS, Android) are designed for smartphones and tablets. They run on ARM-based processors, are optimized for battery life, use touch-first user interfaces, and run applications in sandboxed environments to protect user data and system stability.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-1-03',
    topicId: 'topic-c2-1-1',
    type: 'single_choice',
    stem: 'An industrial robot on a factory floor requires an OS that can respond to sensor inputs within microseconds. Which OS type is most appropriate?',
    choices: ch('Windows Server', 'Ubuntu Desktop', 'Android', 'RTOS (Real-Time Operating System)', 'd'),
    correctAnswer: ca('d'),
    explanation: 'A Real-Time Operating System (RTOS) is designed for applications that require deterministic, predictable response times within strict time constraints. Examples include VxWorks, FreeRTOS, and QNX. General-purpose OSes like Windows or Linux cannot guarantee microsecond response times.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-1-04',
    topicId: 'topic-c2-1-1',
    type: 'single_choice',
    stem: 'On a 64-bit Windows installation, where are 32-bit application DLLs stored?',
    choices: ch('C:\\Windows\\System32', 'C:\\Windows\\SysWOW64', 'C:\\Program Files', 'C:\\Windows\\Drivers', 'b'),
    correctAnswer: ca('b'),
    explanation: 'On 64-bit Windows, System32 holds 64-bit DLLs and SysWOW64 holds 32-bit DLLs. "WOW64" stands for Windows 32-bit On Windows 64-bit. The naming is counterintuitive but historical. 32-bit applications are typically installed under C:\\Program Files (x86).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-1-05',
    topicId: 'topic-c2-1-1',
    type: 'single_choice',
    stem: 'Which statement about macOS is correct?',
    choices: ch(
      'macOS can run on any x86-64 PC with compatible drivers',
      'macOS is based on a Unix/BSD foundation and ships with POSIX compliance',
      'macOS uses NTFS as its default file system',
      'macOS supports running Windows 64-bit applications natively',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'macOS is built on a Unix/BSD foundation (Darwin kernel), providing POSIX compliance, a full terminal, native SSH support, and developer tooling. It runs exclusively on Apple hardware. Its default file system is APFS, not NTFS. macOS cannot run Windows applications natively.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-1-06',
    topicId: 'topic-c2-1-1',
    type: 'single_choice',
    stem: 'A company wants to allow IT administrators to remotely wipe lost employee smartphones and enforce screen lock PINs across both iPhone and Android devices. What technology makes this possible?',
    choices: ch('iCloud Backup', 'MDM (Mobile Device Management)', 'App Store restrictions', 'Google Workspace email filtering', 'b'),
    correctAnswer: ca('b'),
    explanation: 'MDM (Mobile Device Management) allows IT administrators to enforce security policies, push configurations, remotely wipe devices, and manage app deployment across a fleet of mobile devices. Both iOS and Android support MDM enrollment — it is not OS-specific.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-1-07',
    topicId: 'topic-c2-1-1',
    type: 'single_choice',
    stem: 'What is the maximum amount of RAM a 32-bit operating system can address?',
    choices: ch('2 GB', '4 GB', '8 GB', '16 GB', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A 32-bit OS can address a maximum of 2^32 bytes = 4 GB of RAM. In practice, only about 3.2 GB is typically usable because some address space is reserved for hardware and memory-mapped I/O. A 64-bit OS has a theoretical limit of 18.4 exabytes.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-1-08',
    topicId: 'topic-c2-1-1',
    type: 'single_choice',
    stem: 'A technician needs to deploy a web server on a budget. Which OS is the most appropriate choice and is the dominant platform for web hosting globally?',
    choices: ch('Windows Server 2022', 'macOS Server', 'Linux (e.g., Ubuntu Server or RHEL)', 'ChromeOS', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Linux powers over 96% of the world\'s top web servers and nearly all cloud infrastructure. It is free (for community editions), stable, secure, and highly customizable. Ubuntu Server and RHEL are the most common enterprise web server distributions.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.2 OS Installations & Upgrades (8 questions) ─────────────────────────

  {
    id: 'q-c2-1-2-01',
    topicId: 'topic-c2-1-2',
    type: 'single_choice',
    stem: 'A user reports that their machine has a severe malware infection and is behaving erratically. Which installation method is recommended?',
    choices: ch('In-place upgrade', 'Clean install', 'Repair install using Windows Recovery', 'System Restore to an earlier point', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A clean install wipes the existing OS and data, eliminating malware, misconfiguration, and accumulated problems. An in-place upgrade preserves files and settings — including any malware. System Restore and repair installs may not remove deeply embedded malware.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-2-02',
    topicId: 'topic-c2-1-2',
    type: 'single_choice',
    stem: 'After performing an in-place upgrade from Windows 10 to Windows 11, a user wants to roll back to Windows 10. What is the default window during which this is possible?',
    choices: ch('7 days', '10 days', '30 days', '60 days', 'b'),
    correctAnswer: ca('b'),
    explanation: 'After an in-place upgrade, Windows creates a Windows.old folder containing the previous installation. The rollback option appears in Settings > Recovery > Go back and remains available for 10 days. After 10 days, the option disappears and Windows.old can be removed via Disk Cleanup.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-2-03',
    topicId: 'topic-c2-1-2',
    type: 'single_choice',
    stem: 'An organization needs to deploy the same OS image to 200 machines simultaneously without physical media at each desk. Which technology makes this possible?',
    choices: ch('Rufus USB imaging', 'PXE (Preboot Execution Environment) with WDS', 'DVD duplication', 'USB hub broadcasting', 'b'),
    correctAnswer: ca('b'),
    explanation: 'PXE (Preboot Execution Environment) allows machines to boot from the network and load an OS image. Combined with Windows Deployment Services (WDS), a technician can deploy images to hundreds of machines simultaneously. The NIC must support PXE and the boot order must list Network before the local drive.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-2-04',
    topicId: 'topic-c2-1-2',
    type: 'single_choice',
    stem: 'A user tries to copy a 6 GB video file to a USB drive formatted as FAT32, but the copy fails even though 20 GB of free space is available. What is the cause?',
    choices: ch('The USB drive is write-protected', 'FAT32 has a maximum file size of 4 GB', 'The file is corrupt', 'The USB port is USB 2.0 and too slow', 'b'),
    correctAnswer: ca('b'),
    explanation: 'FAT32 has a hard maximum file size limit of 4 GB. A 6 GB file exceeds this limit regardless of available free space. The solution is to reformat the drive as exFAT, which supports files up to 128 PB and is cross-platform compatible.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-2-05',
    topicId: 'topic-c2-1-2',
    type: 'single_choice',
    stem: 'A technician is installing Windows on a new 4 TB hard drive using UEFI mode. Which partition scheme must be used?',
    choices: ch('MBR', 'GPT', 'Either MBR or GPT', 'FAT32', 'b'),
    correctAnswer: ca('b'),
    explanation: 'UEFI requires GPT. Attempting to install in UEFI mode on an MBR disk will fail. Additionally, MBR supports a maximum disk size of 2 TB, so a 4 TB drive must use GPT regardless. The modern standard is UEFI + GPT.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-2-06',
    topicId: 'topic-c2-1-2',
    type: 'single_choice',
    stem: 'Which file system is native to Windows and provides journaling, NTFS permissions, EFS encryption, and compression?',
    choices: ch('FAT32', 'exFAT', 'NTFS', 'ext4', 'c'),
    correctAnswer: ca('c'),
    explanation: 'NTFS (New Technology File System) is the native Windows file system and provides journaling (crash recovery), granular ACL permissions, EFS (Encrypting File System), native file and folder compression, and disk quotas. It is required for Windows system volumes.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-2-07',
    topicId: 'topic-c2-1-2',
    type: 'single_choice',
    stem: 'Which tool is used to create an XML answer file that automates the Windows installation wizard responses for unattended deployments?',
    choices: ch('Rufus', 'Windows System Image Manager (SIM)', 'balenaEtcher', 'Windows Media Creation Tool', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Windows System Image Manager (SIM), part of the Windows ADK (Assessment and Deployment Kit), is used to create unattend.xml answer files. These files pre-populate installation responses (language, key, partition layout, account names) for fully automated deployments.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-2-08',
    topicId: 'topic-c2-1-2',
    type: 'single_choice',
    stem: 'Before capturing a Windows image with DISM for enterprise deployment, which command must be run first and why?',
    choices: ch(
      'ipconfig /release — to clear the network configuration',
      'sysprep /generalize — to remove machine-specific identifiers including the SID',
      'chkdsk /f — to repair any file system errors',
      'sfc /scannow — to verify system file integrity',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Sysprep /generalize must be run before capturing an image. It removes machine-specific information including the Security Identifier (SID), hardware identifiers, and activation state. Without this step, every deployed machine would have the same SID, causing conflicts in Active Directory environments.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.3 Windows Editions (8 questions) ────────────────────────────────────

  {
    id: 'q-c2-1-3-01',
    topicId: 'topic-c2-1-3',
    type: 'single_choice',
    stem: 'A small business employee needs to connect their Windows 10 laptop to the company\'s Active Directory domain. Which edition is the minimum requirement?',
    choices: ch('Windows 10 Home', 'Windows 10 Pro', 'Windows 10 S Mode', 'Any edition supports domain join', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Domain join (connecting to Active Directory) requires Windows Pro or higher. Windows 10 Home cannot join a domain — it is the most fundamental reason businesses must license Pro or Enterprise. Home machines can connect to network shares but cannot be centrally managed through Active Directory.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-3-02',
    topicId: 'topic-c2-1-3',
    type: 'single_choice',
    stem: 'A technician needs to enable BitLocker full-disk encryption on a laptop. The laptop is running Windows 10 Home. What is the correct course of action?',
    choices: ch(
      'Enable BitLocker from Control Panel > BitLocker Drive Encryption',
      'Enable BitLocker from Settings > Update & Security',
      'BitLocker is not available on Home; the edition must be upgraded to Pro or higher',
      'Install the BitLocker feature from Turn Windows Features On or Off',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'BitLocker is not available on Windows Home edition. It requires Windows Pro, Pro for Workstations, Enterprise, or Education. The machine must be upgraded to Pro (or higher) before BitLocker can be enabled.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-3-03',
    topicId: 'topic-c2-1-3',
    type: 'single_choice',
    stem: 'Which Windows editions can act as a Remote Desktop HOST, accepting incoming RDP connections? (Choose the most accurate answer.)',
    choices: ch(
      'All editions including Home',
      'Home and Pro only',
      'Pro, Pro for Workstations, Enterprise, and Education (not Home)',
      'Enterprise and Education only',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Remote Desktop hosting requires Pro or higher. All Windows editions can be a Remote Desktop CLIENT (connecting to another machine using mstsc.exe), but only Pro, Pro for Workstations, Enterprise, and Education can HOST incoming RDP connections. Home users needing remote access must use third-party tools like TeamViewer.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-3-04',
    topicId: 'topic-c2-1-3',
    type: 'single_choice',
    stem: 'What additional hardware requirements does Windows 11 have compared to Windows 10 that most commonly cause upgrade failures?',
    choices: ch(
      'At least 8 GB RAM and a dedicated GPU',
      'TPM 2.0 chip and Secure Boot capability',
      'A solid-state drive and USB 3.0 ports',
      'DirectX 12 GPU and HDMI 2.0 output',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Windows 11 requires TPM 2.0 and Secure Boot capability. These are the requirements that most commonly cause upgrade failures on older hardware. TPM may be present but disabled in UEFI settings (look for PTT on Intel systems or fTPM on AMD systems). Windows 11 also requires a 64-bit dual-core CPU at 1 GHz+, 4 GB RAM, and 64 GB storage.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-3-05',
    topicId: 'topic-c2-1-3',
    type: 'single_choice',
    stem: 'Which Windows feature allows IT administrators to whitelist or blacklist specific applications by publisher, path, or file hash?',
    choices: ch('Group Policy', 'Windows Defender SmartScreen', 'AppLocker', 'BitLocker', 'c'),
    correctAnswer: ca('c'),
    explanation: 'AppLocker allows administrators to define rules controlling which applications users are allowed to run, based on publisher certificate, file path, or file hash. AppLocker is available only in Enterprise and Education editions — not Home or Pro.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-3-06',
    topicId: 'topic-c2-1-3',
    type: 'single_choice',
    stem: 'A technician on a Windows 10 Home machine tries to open gpedit.msc to configure a local Group Policy setting. What happens?',
    choices: ch(
      'The Group Policy editor opens normally',
      'The Group Policy editor opens in read-only mode',
      'Windows prompts for a Pro license key',
      'Windows cannot find gpedit.msc — it is not available on Home edition',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'gpedit.msc (Local Group Policy Editor) does not exist on Windows Home edition. Technicians must use the Settings app, Registry Editor (regedit), or third-party tools to make changes that would otherwise be done through Group Policy on Pro/Enterprise.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-3-07',
    topicId: 'topic-c2-1-3',
    type: 'single_choice',
    stem: 'Hyper-V is Microsoft\'s built-in hypervisor. Which hypervisor type is it, and which minimum Windows edition is required?',
    choices: ch(
      'Type 2 (hosted); available on Home and Pro',
      'Type 1 (bare-metal); requires Pro or higher (64-bit)',
      'Type 2 (hosted); requires Enterprise only',
      'Type 1 (bare-metal); available on all editions',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Hyper-V is a Type 1 (bare-metal) hypervisor — when enabled, Windows itself runs as a privileged VM on the hypervisor. It requires Windows Pro, Pro for Workstations, Enterprise, or Education (64-bit), a CPU with SLAT (Intel EPT or AMD RVI), and virtualization extensions enabled in UEFI.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-3-08',
    topicId: 'topic-c2-1-3',
    type: 'single_choice',
    stem: 'A user on Windows 10 Pro wants to safely test a suspicious installer without risking the host system. Which built-in feature should they use?',
    choices: ch('Hyper-V with a new VM', 'Windows Sandbox', 'Windows Defender quarantine', 'System Restore', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Windows Sandbox creates an isolated, temporary Windows desktop environment. Every time it opens, it starts from a clean Windows state. When closed, all content inside is permanently deleted. It requires Pro or higher and uses hardware virtualization. It is the fastest option for safely testing untrusted software without creating a full VM.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.4 Windows Tools (8 questions) ───────────────────────────────────────

  {
    id: 'q-c2-1-4-01',
    topicId: 'topic-c2-1-4',
    type: 'single_choice',
    stem: 'A user notices that several programs are launching at login and slowing boot time. In Windows 10/11, which tool and tab should the technician use to disable startup programs?',
    choices: ch(
      'msconfig — Services tab',
      'Task Manager — Startup tab',
      'services.msc — Startup type column',
      'regedit — HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'In Windows 10 and 11, the Startup tab in Task Manager is the recommended location to manage startup programs. It shows each program\'s startup impact (Low/Medium/High). Right-click any entry to Disable it. This replaced the msconfig Startup tab used in Windows 7 and earlier.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-4-02',
    topicId: 'topic-c2-1-4',
    type: 'single_choice',
    stem: 'In Device Manager, what does a yellow exclamation mark (!) next to a device indicate?',
    choices: ch(
      'The device has been disabled by the user',
      'The device is not connected',
      'There is a driver problem — the driver is missing, corrupt, or conflicting',
      'The device is functioning normally but has a firmware update available',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A yellow exclamation mark (!) in Device Manager indicates a driver problem — the device is present but the driver is missing, corrupt, or in conflict with another device. The fix is typically to update, reinstall, or roll back the driver. A red X indicates the device is disabled.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-4-03',
    topicId: 'topic-c2-1-4',
    type: 'single_choice',
    stem: 'A technician wants to convert a disk from MBR to GPT without destroying any data. Which tool allows this on Windows 10 version 1703 or later?',
    choices: ch('Disk Management (diskmgmt.msc)', 'diskpart convert gpt', 'mbr2gpt.exe', 'format /gpt', 'c'),
    correctAnswer: ca('c'),
    explanation: 'mbr2gpt.exe (available in Windows 10 version 1703+) can convert a disk from MBR to GPT while Windows is running and without data loss. Disk Management and diskpart require deleting all partitions first (destroying all data) before converting.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-4-04',
    topicId: 'topic-c2-1-4',
    type: 'single_choice',
    stem: 'A technician needs to find which Windows event log contains failed login attempts. Which log should they check?',
    choices: ch('Application log', 'System log', 'Security log', 'Setup log', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The Security log in Event Viewer records logon/logoff events, privilege use, and security audit successes and failures. Event ID 4625 is a failed logon. Event ID 4624 is a successful logon. The System log records OS component events; Application log records application events.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-4-05',
    topicId: 'topic-c2-1-4',
    type: 'single_choice',
    stem: 'A technician uses msconfig to put the system into Diagnostic Startup mode. What is the effect?',
    choices: ch(
      'Windows boots with only basic drivers and services — similar to Safe Mode',
      'Windows boots with networking support enabled',
      'Windows uninstalls recently added programs',
      'Windows restores to the last known good configuration',
      'a'
    ),
    correctAnswer: ca('a'),
    explanation: 'Diagnostic Startup in msconfig loads only basic Windows drivers and services — similar to Safe Mode but through the normal boot process. It is used to isolate startup problems by eliminating third-party drivers and services. After troubleshooting, change back to Normal Startup.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-4-06',
    topicId: 'topic-c2-1-4',
    type: 'single_choice',
    stem: 'A user cannot print. The technician suspects the Print Spooler service has stopped. Which command opens the Services console to check and restart it?',
    choices: ch('taskmgr', 'services.msc', 'devmgmt.msc', 'compmgmt.msc', 'b'),
    correctAnswer: ca('b'),
    explanation: 'services.msc opens the Services console, which lists all Windows services with their current status and startup type. The Print Spooler service must be running for printing to work. If stopped, right-click it and choose Start. The Recovery tab can be configured to restart the service automatically on failure.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-4-07',
    topicId: 'topic-c2-1-4',
    type: 'single_choice',
    stem: 'Which of the following registry hives contains settings that apply to all users on the local machine, including hardware and software configuration?',
    choices: ch('HKEY_CURRENT_USER (HKCU)', 'HKEY_LOCAL_MACHINE (HKLM)', 'HKEY_CLASSES_ROOT (HKCR)', 'HKEY_CURRENT_CONFIG (HKCC)', 'b'),
    correctAnswer: ca('b'),
    explanation: 'HKEY_LOCAL_MACHINE (HKLM) stores hardware and software settings that apply to all users on the system, including driver configuration, installed software settings, and system-wide security policies. HKEY_CURRENT_USER (HKCU) stores settings for only the currently logged-in user.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-4-08',
    topicId: 'topic-c2-1-4',
    type: 'single_choice',
    stem: 'A technician needs to quickly determine whether a system is booting in Legacy BIOS mode or UEFI mode without opening BIOS settings. Which tool provides this information?',
    choices: ch('Device Manager', 'Task Manager — Performance tab', 'System Information (msinfo32)', 'Disk Management', 'c'),
    correctAnswer: ca('c'),
    explanation: 'System Information (msinfo32) shows the BIOS Mode field in the System Summary section, displaying either "Legacy" or "UEFI." It also shows Secure Boot State, installed RAM, exact OS build number, and processor details — making it the fastest read-only snapshot tool for an unfamiliar system.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.5 Windows CLI Tools (8 questions) ───────────────────────────────────

  {
    id: 'q-c2-1-5-01',
    topicId: 'topic-c2-1-5',
    type: 'single_choice',
    stem: 'A user\'s computer shows an IP address of 169.254.43.12. What does this indicate, and what commands should the technician run to resolve it?',
    choices: ch(
      'The IP was assigned by DHCP; run ipconfig /flushdns',
      'DHCP assignment failed (APIPA address); run ipconfig /release then ipconfig /renew',
      'The network adapter is disabled; run ipconfig /all',
      'The DNS server is down; run nslookup 169.254.43.12',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A 169.254.x.x address is an APIPA (Automatic Private IP Addressing) address, assigned automatically when a device cannot reach a DHCP server. To resolve it, run ipconfig /release to drop the current lease, then ipconfig /renew to request a new IP from the DHCP server. If it persists, the DHCP server or network connection is the problem.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-5-02',
    topicId: 'topic-c2-1-5',
    type: 'single_choice',
    stem: 'A technician runs "ping 8.8.8.8" successfully but "ping google.com" fails. What is the most likely cause?',
    choices: ch('The default gateway is unreachable', 'DNS resolution is failing', 'The NIC is disabled', 'ICMP is blocked by the firewall', 'b'),
    correctAnswer: ca('b'),
    explanation: 'If pinging an IP address (8.8.8.8) succeeds but pinging a hostname (google.com) fails, the network connectivity is working but DNS resolution is broken. Run nslookup google.com to confirm. Solutions include flushing the DNS cache (ipconfig /flushdns), changing DNS servers, or restarting the DNS Client service.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-5-03',
    topicId: 'topic-c2-1-5',
    type: 'single_choice',
    stem: 'Which command displays all active TCP connections along with their process IDs (PIDs) and uses numeric addresses instead of resolving hostnames?',
    choices: ch('netstat -a', 'netstat -b', 'netstat -ano', 'netstat -r', 'c'),
    correctAnswer: ca('c'),
    explanation: 'netstat -ano combines three flags: -a (all connections and listening ports), -n (numeric addresses, no DNS resolution), -o (show the PID for each connection). The PID can then be matched to a process in Task Manager\'s Details tab to identify which program is using a specific port.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-5-04',
    topicId: 'topic-c2-1-5',
    type: 'single_choice',
    stem: 'A technician runs "sfc /scannow" from a standard (non-elevated) command prompt and gets an error that the scan cannot be run. What is the correct fix?',
    choices: ch(
      'Run the command again with the /force flag',
      'Disable Windows Defender first, then run sfc',
      'Close all applications and retry',
      'Reopen the command prompt as Administrator and run sfc /scannow again',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'sfc /scannow requires an elevated (Administrator) command prompt. Running it from a standard prompt will fail. To run elevated: search for cmd, right-click, choose "Run as administrator," confirm the UAC prompt, then run sfc /scannow. Ctrl+Shift+Enter from Start search also launches elevated.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-5-05',
    topicId: 'topic-c2-1-5',
    type: 'single_choice',
    stem: 'A technician runs "chkdsk C: /f" and is told Windows cannot run the check because the volume is in use. What will happen next?',
    choices: ch(
      'The command runs immediately in the background',
      'Windows schedules chkdsk to run before the next OS load on reboot',
      'The command fails and must be run from a bootable USB',
      'Windows dismounts C: automatically and runs chkdsk immediately',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'When chkdsk /f is run on the active system drive (C:), it cannot access the volume while Windows is running. Windows schedules it to run at the next reboot, before the OS fully loads. The user sees a countdown screen during the next boot showing chkdsk progress.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-5-06',
    topicId: 'topic-c2-1-5',
    type: 'single_choice',
    stem: 'A technician needs to immediately restart a remote computer named WORKSTATION01 from the command line, forcing all open applications to close without warning. Which command is correct?',
    choices: ch(
      'shutdown /r /t 0 /m \\\\WORKSTATION01 /f',
      'shutdown /s /m \\\\WORKSTATION01',
      'restart /force \\\\WORKSTATION01',
      'net stop \\\\WORKSTATION01',
      'a'
    ),
    correctAnswer: ca('a'),
    explanation: 'shutdown /r restarts, /t 0 sets the delay to zero seconds (immediate), /m \\\\WORKSTATION01 specifies the remote computer, and /f forces closure of running applications without warning. Administrative rights are required on the remote machine.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-5-07',
    topicId: 'topic-c2-1-5',
    type: 'single_choice',
    stem: 'A new Group Policy Object was applied to a machine but the settings have not taken effect. Which command forces an immediate reapplication of all Group Policy settings?',
    choices: ch('gpresult /r', 'gpupdate /force', 'gpupdate /target:computer', 'net gpupdate /all', 'b'),
    correctAnswer: ca('b'),
    explanation: 'gpupdate /force reapplies ALL Group Policy settings, even those that have not changed since the last refresh. Without /force, gpupdate only processes changed settings. gpresult /r is used to view applied policies, not to refresh them.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-5-08',
    topicId: 'topic-c2-1-5',
    type: 'single_choice',
    stem: 'A technician needs to copy an entire directory tree from C:\\Data to D:\\Backup, including empty subdirectories, with automatic retry on failure and a log file. Which command is most appropriate?',
    choices: ch(
      'xcopy C:\\Data D:\\Backup /e /h /c',
      'copy C:\\Data D:\\Backup /s',
      'robocopy C:\\Data D:\\Backup /E /R:3 /W:5 /LOG:backup.log',
      'xcopy C:\\Data D:\\Backup /MIR',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'robocopy is preferred over xcopy for production file copy jobs. /E copies all subdirectories including empty ones, /R:3 retries failed files 3 times, /W:5 waits 5 seconds between retries, and /LOG:backup.log writes a log file. robocopy handles network interruptions gracefully; xcopy does not.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 1.6 Windows Settings (8 questions) ────────────────────────────────────

  {
    id: 'q-c2-1-6-01',
    topicId: 'topic-c2-1-6',
    type: 'single_choice',
    stem: 'A user needs to join a Windows 10 Pro machine to a domain. Which tool and tab contains the domain join option?',
    choices: ch(
      'Settings app — Accounts — Your info',
      'System Properties (sysdm.cpl) — Computer Name tab',
      'Control Panel — Network and Sharing Center',
      'Device Manager — Network Adapter properties',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Domain join is performed in System Properties (sysdm.cpl) on the Computer Name tab by clicking "Change..." next to domain or workgroup. A reboot is required after joining. Alternatively, Settings > System > About > Advanced system settings opens the same System Properties dialog.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-6-02',
    topicId: 'topic-c2-1-6',
    type: 'single_choice',
    stem: 'A laptop user wants maximum battery life during a long flight. Which power plan should they select?',
    choices: ch('High performance', 'Balanced', 'Power saver', 'Ultimate Performance', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Power saver reduces CPU performance and other hardware to their minimum to conserve maximum battery power. Balanced scales CPU speed with demand and is the default. High performance prevents throttling for maximum performance. Ultimate Performance is for workstations and is not shown by default.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-6-03',
    topicId: 'topic-c2-1-6',
    type: 'single_choice',
    stem: 'What is the difference between Sleep (S3) and Hibernate (S4) power states?',
    choices: ch(
      'Sleep saves RAM contents to disk; Hibernate keeps RAM powered',
      'Sleep keeps RAM powered for fast resume; Hibernate saves RAM contents to disk and powers off completely',
      'Both are identical except Hibernate uses less power',
      'Sleep is available on desktops only; Hibernate is for laptops only',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Sleep (S3) keeps RAM powered, enabling a 1-2 second resume but consuming some power. Hibernate (S4) saves all RAM contents to hiberfil.sys on disk and powers off completely (uses no power), but takes 10-30 seconds to resume. Hybrid Sleep saves to both RAM and disk simultaneously.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-6-04',
    topicId: 'topic-c2-1-6',
    type: 'single_choice',
    stem: 'Security patches and bug fixes are released on Patch Tuesday. What type of Windows Update are these, and when does Patch Tuesday occur?',
    choices: ch(
      'Feature updates; first Tuesday of every month',
      'Quality updates; second Tuesday of every month',
      'Definition updates; every Tuesday',
      'Driver updates; second Tuesday of every month',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Quality updates contain security patches, bug fixes, and reliability improvements. They are released on Patch Tuesday — the second Tuesday of every month. Feature updates deliver major OS version changes and are released approximately once or twice per year.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-6-05',
    topicId: 'topic-c2-1-6',
    type: 'single_choice',
    stem: 'Windows Security shows a red shield icon in the system tray. What does this most likely indicate?',
    choices: ch(
      'Windows Update is downloading updates in the background',
      'Real-time protection (antivirus) has been disabled',
      'The firewall has blocked an incoming connection',
      'A virus was found and quarantined successfully',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A red shield in the system tray indicates that Windows Security protection is compromised — most commonly that real-time protection has been disabled. Windows Security displays warnings and the red shield until protection is restored. A quarantined virus would show a notification, not a persistent red shield.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-6-06',
    topicId: 'topic-c2-1-6',
    type: 'single_choice',
    stem: 'A standard user tries to install software and Windows displays a prompt asking for an administrator username and password. What feature is generating this prompt?',
    choices: ch('Windows Defender SmartScreen', 'User Account Control (UAC)', 'Windows Security Center', 'Local Group Policy', 'b'),
    correctAnswer: ca('b'),
    explanation: 'User Account Control (UAC) generates the credential prompt when a standard user attempts to perform an action requiring elevated privileges, such as installing software. If the user is already an administrator, UAC only asks for confirmation (yes/no). UAC prevents unauthorized changes to the system.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-6-07',
    topicId: 'topic-c2-1-6',
    type: 'single_choice',
    stem: 'Windows Defender Firewall uses three network profiles. Which profile is applied when a computer is connected to an untrusted public Wi-Fi network?',
    choices: ch('Domain profile', 'Private profile', 'Public profile', 'Guest profile', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The Public profile applies the most restrictive firewall rules and is used when the computer is on an untrusted public network (coffee shop, airport, hotel). The Domain profile applies when connected to a corporate domain network. The Private profile applies when on a trusted home or work network.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-1-6-08',
    topicId: 'topic-c2-1-6',
    type: 'single_choice',
    stem: 'Windows Search is returning stale and incorrect results. What is the recommended fix in Indexing Options?',
    choices: ch(
      'Uninstall and reinstall the Windows Search feature',
      'Add the entire C: drive to the indexed locations list',
      'Rebuild the search index from Advanced options in Indexing Options',
      'Run sfc /scannow to repair the search index files',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'When Windows Search returns stale or incorrect results, the index is likely corrupted. In Control Panel > Indexing Options > Advanced, click Rebuild to delete and recreate the index. The rebuild can take minutes to hours depending on file count, and results may be incomplete until it finishes.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

]
