// CompTIA A+ 220-1201 — Core 1 Domain 4: Virtualization & Cloud Computing
// 84 questions across 2 topics (42 per topic)

const NOW = new Date().toISOString()

type Choice = { id: string; text: string; isCorrect: boolean }

function ch(a: string, b: string, c: string, d: string, correct: 'a' | 'b' | 'c' | 'd'): string {
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: correct === 'a' },
    { id: 'b', text: b, isCorrect: correct === 'b' },
    { id: 'c', text: c, isCorrect: correct === 'c' },
    { id: 'd', text: d, isCorrect: correct === 'd' },
  ] as Choice[])
}

function chMulti(a: string, b: string, c: string, d: string, correct: Array<'a' | 'b' | 'c' | 'd'>): string {
  const ids = new Set(correct)
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: ids.has('a') },
    { id: 'b', text: b, isCorrect: ids.has('b') },
    { id: 'c', text: c, isCorrect: ids.has('c') },
    { id: 'd', text: d, isCorrect: ids.has('d') },
  ] as Choice[])
}

const ca = (id: 'a' | 'b' | 'c' | 'd') => JSON.stringify(id)
const cam = (...ids: Array<'a' | 'b' | 'c' | 'd'>) => JSON.stringify(ids)

export const BATCH11_QUESTIONS = [
  // ── topic-c1-4-1: Virtualization Concepts (q-c1-4-1-09 through q-c1-4-1-50) ──

  // --- easy (13) ---
  {
    id: 'q-c1-4-1-09',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'What is a hypervisor?',
    choices: ch(
      'A physical server used exclusively for storage',
      'Software that creates and manages virtual machines',
      'A network switch that connects VMs to the internet',
      'A backup utility for cloning hard drives',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A hypervisor (also called a Virtual Machine Monitor) is software that creates, runs, and manages virtual machines by abstracting the underlying physical hardware. It is not a storage server, network switch, or backup utility.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-10',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Which hypervisor type runs directly on the physical hardware without a host operating system?',
    choices: ch(
      'Type 1 (bare-metal)',
      'Type 2 (hosted)',
      'Type 3 (containerized)',
      'Type 4 (emulated)',
      'a'
    ),
    correctAnswer: ca('a'),
    explanation: 'A Type 1 (bare-metal) hypervisor installs directly on the physical hardware and manages all hardware resources without needing a host OS. Type 2 runs on top of an existing operating system. There are no Type 3 or Type 4 hypervisor classifications.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-11',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Oracle VirtualBox is an example of which type of hypervisor?',
    choices: ch(
      'Type 1 (bare-metal)',
      'Type 2 (hosted)',
      'Container runtime',
      'Hardware emulator',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Oracle VirtualBox is a Type 2 (hosted) hypervisor that runs as an application on top of a host operating system such as Windows, macOS, or Linux. It does not install directly on hardware like a Type 1 hypervisor.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-12',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'What does a snapshot of a virtual machine capture?',
    choices: ch(
      'Only the virtual disk contents',
      'Only the current RAM state',
      'The complete state including disk, RAM, and VM configuration',
      'Only the network configuration of the VM',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A VM snapshot captures the complete state of the virtual machine at a specific point in time, including the contents of RAM, the state of all virtual disks, and the VM configuration settings. This allows a full rollback to that exact point.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-13',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'What is the primary advantage of server consolidation through virtualization?',
    choices: ch(
      'Eliminates the need for any physical servers',
      'Runs multiple virtual servers on a single physical host, reducing hardware costs',
      'Makes all servers immune to malware',
      'Removes the need for network switches',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Server consolidation allows multiple virtual servers to run on a single physical host, reducing hardware purchases, power consumption, and cooling costs. Virtualization still requires physical servers and does not eliminate malware risk or network hardware needs.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-14',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Which VM networking mode gives the virtual machine its own IP address on the physical network, making it appear as a separate host?',
    choices: ch(
      'NAT',
      'Host-only',
      'Bridged',
      'Internal',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'In bridged mode, the VM connects directly to the physical network and obtains its own IP address from the network DHCP server, appearing as a separate host. NAT shares the host IP, host-only restricts traffic to host-VM communication, and internal limits communication to VMs only.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-15',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'What is a vNIC?',
    choices: ch(
      'A virtual network interface card assigned to a VM',
      'A physical NIC dedicated to virtualization',
      'A verification tool for network interface compatibility',
      'A VLAN network interface controller on a physical switch',
      'a'
    ),
    correctAnswer: ca('a'),
    explanation: 'A vNIC (virtual network interface card) is a software-based network adapter assigned to a virtual machine. The hypervisor connects vNICs to virtual switches, which in turn connect to the physical network. Each VM appears on the network with its own MAC address through its vNIC.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-16',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Which CPU feature must be enabled in BIOS/UEFI to run virtual machines?',
    choices: ch(
      'Hyper-Threading',
      'Intel VT-x or AMD-V',
      'Turbo Boost',
      'Power management (SpeedStep)',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Hardware virtualization extensions — Intel VT-x or AMD-V (SVM) — must be enabled in BIOS/UEFI for hypervisors to run VMs efficiently. Hyper-Threading enables logical cores, Turbo Boost raises clock speed, and SpeedStep manages power — none of these are virtualization prerequisites.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-17',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'What is the key difference between an emulator and a hypervisor?',
    choices: ch(
      'An emulator is faster than a hypervisor',
      'A hypervisor simulates different hardware architectures while an emulator does not',
      'An emulator translates instructions for a different CPU architecture while a hypervisor runs the same architecture natively',
      'There is no difference; the terms are interchangeable',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'An emulator translates every instruction to simulate a completely different hardware architecture (e.g., ARM on x86), which is very slow. A hypervisor runs guest operating systems on the same CPU architecture as the host, using hardware extensions for near-native speed.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-18',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Which virtual disk provisioning method allocates all storage space upfront when the disk is created?',
    choices: ch(
      'Thin provisioning',
      'Thick provisioning',
      'Dynamic provisioning',
      'Sparse provisioning',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Thick provisioning allocates the entire specified disk space immediately on creation — a 100 GB thick disk consumes 100 GB on the host right away. Thin provisioning allocates space on demand as data is written, starting much smaller than the maximum size.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-19',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'What is the primary reason containers start faster than virtual machines?',
    choices: ch(
      'Containers use more RAM',
      'Containers share the host OS kernel instead of booting a full guest OS',
      'Containers require Type 1 hypervisors',
      'Containers do not use any storage',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Containers share the host operating system kernel and only package the application and its dependencies, so they start in milliseconds. Virtual machines must boot a complete guest OS (kernel plus userspace), which takes seconds to minutes.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-20',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'VMware ESXi is classified as which hypervisor type?',
    choices: ch(
      'Type 2 (hosted)',
      'Type 1 (bare-metal)',
      'Container engine',
      'Hardware emulator',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'VMware ESXi is an enterprise Type 1 (bare-metal) hypervisor that installs directly on server hardware with no host OS underneath. It provides the highest performance and is managed via web interface or VMware vCenter.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-21',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'In VM networking, which mode allows the VM to access the internet through the host but prevents external devices from initiating connections to the VM?',
    choices: ch(
      'Bridged',
      'NAT',
      'Host-only',
      'Internal',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'NAT (Network Address Translation) mode lets the VM reach the internet through the host IP address, but external devices cannot initiate inbound connections to the VM without port forwarding. Bridged mode exposes the VM on the physical network, while host-only and internal modes have no internet access.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // --- medium (21) ---
  {
    id: 'q-c1-4-1-22',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'A technician needs to assign a physical GPU directly to a virtual machine for high-performance graphics. Which CPU extension is required for PCI passthrough?',
    choices: ch(
      'Intel VT-x / AMD-V',
      'Intel VT-d / AMD IOMMU',
      'Intel EPT / AMD NPT',
      'Intel Hyper-Threading / AMD SMT',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'PCI passthrough (assigning a physical PCIe device directly to a VM) requires Intel VT-d or AMD IOMMU, which provide hardware-level I/O virtualization. VT-x/AMD-V enable CPU virtualization, EPT/NPT handle memory virtualization, and Hyper-Threading/SMT create logical CPU cores.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-23',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'After taking a snapshot, a technician notices the VM disk performance has degraded. What is the most likely cause?',
    choices: ch(
      'The snapshot encrypted the disk',
      'The snapshot chain creates delta disks that add I/O overhead',
      'Snapshots disable the virtual CPU',
      'The host automatically reduces RAM allocation after a snapshot',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'When a snapshot is taken, the current disk becomes read-only and a delta (differencing) disk records all subsequent changes. Long snapshot chains require the hypervisor to traverse multiple delta files for read operations, degrading performance. Snapshots do not encrypt disks or affect CPU/RAM allocation.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-24',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'A company wants to test potentially malicious software in an isolated environment. Which virtualization approach is BEST suited for this purpose?',
    choices: ch(
      'Running the software on a production VM with bridged networking',
      'Running the software in a sandbox VM with host-only or no networking',
      'Running the software directly on the hypervisor host',
      'Running the software in a container with full network access',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A sandbox VM with host-only or no networking provides strong isolation — the malicious software is contained within the VM and cannot reach the production network. Running on bridged networking exposes the network, running on the host is dangerous, and containers share the host kernel providing weaker isolation.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-25',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'A hypervisor host has 8 physical CPU cores, but the administrator has allocated a total of 16 vCPUs across all VMs. What is this practice called?',
    choices: ch(
      'CPU throttling',
      'Overcommitment (overprovisioning)',
      'Hyper-Threading',
      'CPU pinning',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Overcommitment (also called overprovisioning) is the practice of assigning more virtual resources than physically available. The hypervisor time-slices the physical cores among the vCPUs. Hyper-Threading is a CPU feature, throttling reduces clock speed, and pinning locks vCPUs to specific cores.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-26',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Which virtual disk format is native to VMware products?',
    choices: ch(
      'VHD',
      'VHDX',
      'VMDK',
      'QCOW2',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'VMDK (Virtual Machine Disk) is VMware\'s native virtual disk format. VHD and VHDX are Microsoft formats used by Hyper-V. QCOW2 is the format used by QEMU/KVM on Linux.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-27',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'A technician tries to start a 64-bit VM and receives the error "VT-x is not available." What should the technician do FIRST?',
    choices: ch(
      'Install a 32-bit guest OS instead',
      'Add more RAM to the host',
      'Enable the CPU virtualization extension in BIOS/UEFI settings',
      'Reinstall the hypervisor software',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'The "VT-x is not available" error means Intel VT-x is disabled in BIOS/UEFI. The technician should reboot, enter BIOS/UEFI setup, navigate to CPU configuration, enable the virtualization setting, save, and exit. This is a common issue since many systems ship with VT-x disabled by default.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-28',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'What function does a virtual switch (vSwitch) perform in a virtualization environment?',
    choices: ch(
      'Routes traffic between different physical data centers',
      'Connects VMs to each other and to the physical network at Layer 2',
      'Provides DHCP addresses to the physical network',
      'Encrypts all traffic leaving the hypervisor',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A virtual switch operates like a physical Layer 2 network switch but entirely in software within the hypervisor. It connects VMs to each other and to the physical network via the host\'s physical NIC. VMs on the same vSwitch can communicate without traffic leaving the host.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-29',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'An administrator wants to move a running VM from one physical host to another with no downtime. What is this process called?',
    choices: ch(
      'Cold migration',
      'Snapshot revert',
      'Live migration (vMotion)',
      'VM cloning',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Live migration (called vMotion in VMware environments) moves a running VM from one physical host to another without shutting it down, ensuring no service interruption. Cold migration requires powering off the VM, snapshot revert rolls back state, and cloning creates a copy.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-30',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Which of the following is a security concern specific to containers compared to virtual machines?',
    choices: ch(
      'Containers consume too much disk space',
      'Containers cannot run on Linux',
      'A kernel exploit could affect all containers on the host since they share the host kernel',
      'Containers require a dedicated Type 1 hypervisor',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Containers share the host OS kernel, so a kernel-level vulnerability could potentially compromise all containers on that host. VMs each have their own isolated kernel, providing stronger isolation. Containers are lightweight (not disk-heavy), run natively on Linux, and do not require a hypervisor.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-31',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'What is the purpose of a VM template?',
    choices: ch(
      'To take a snapshot of a running VM',
      'To provide a pre-configured base image for rapidly deploying new VMs',
      'To monitor VM performance metrics',
      'To encrypt virtual disk files',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A VM template is a master copy of a pre-configured virtual machine (with an OS installed and configured) that serves as a base image for rapidly deploying new VMs. Unlike a snapshot, a template is not a point-in-time backup but a reusable blueprint for provisioning.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-32',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'A technician uses thin provisioning for virtual disks. What risk does this introduce?',
    choices: ch(
      'VMs will boot more slowly',
      'The host storage pool may fill up unexpectedly as VMs write data',
      'VMs cannot take snapshots',
      'Virtual NICs will lose connectivity',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Thin-provisioned disks allocate storage on demand, so the total promised disk space across all VMs can exceed physical storage. As VMs write data, the host storage can fill up unexpectedly, potentially causing I/O errors for all VMs. This does not affect boot speed, snapshots, or networking.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-33',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Microsoft Hyper-V installs inside Windows, yet it is classified as a Type 1 hypervisor. Why?',
    choices: ch(
      'Because it is free software',
      'Because when enabled, the Hyper-V hypervisor runs on bare metal and Windows runs inside a partition it manages',
      'Because it only supports Microsoft operating systems',
      'Because it requires a dedicated GPU',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'When Hyper-V is enabled, the hypervisor layer inserts itself between the hardware and Windows. Windows itself then runs as a privileged partition managed by the Hyper-V hypervisor, making it technically a Type 1 (bare-metal) hypervisor despite appearing to install within Windows.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-34',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Which file format provides a portable, cross-platform way to package and distribute virtual machines?',
    choices: ch(
      'VMDK',
      'VHDX',
      'OVA/OVF',
      'QCOW2',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'OVA (Open Virtualization Appliance) and OVF (Open Virtualization Format) are cross-platform standards for packaging VMs that can be imported into different hypervisors. VMDK is VMware-specific, VHDX is Microsoft-specific, and QCOW2 is QEMU/KVM-specific.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-35',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'In a VDI (Virtual Desktop Infrastructure) environment, what component routes users to their assigned desktop VM?',
    choices: ch(
      'Virtual switch',
      'Thin client',
      'Connection broker',
      'Display protocol',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'The connection broker is responsible for authenticating users and routing them to the correct desktop VM in a VDI environment. A thin client is the endpoint device, a virtual switch handles networking, and display protocols (RDP, PCoIP) deliver the remote display.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-36',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'A VM host has 32 GB of physical RAM, and the administrator allocates 12 GB to each of three VMs. What issue is most likely to occur?',
    choices: ch(
      'The VMs will refuse to start because of CPU limitations',
      'The host will swap VM memory to disk, severely degrading performance',
      'The virtual switches will stop functioning',
      'Snapshots will be automatically deleted',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Three VMs at 12 GB each need 36 GB, exceeding the 32 GB physical RAM. The host must swap VM memory to disk, causing catastrophic performance degradation. Unlike CPU overcommitment, RAM overcommitment without sufficient physical backing leads to heavy disk swapping.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-37',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Which technology allows VLANs to be configured on a virtual switch to segment VM network traffic?',
    choices: ch(
      'Port groups with VLAN tags on the vSwitch',
      'NAT mode on each VM',
      'Physical NIC teaming',
      'Host-only adapter configuration',
      'a'
    ),
    correctAnswer: ca('a'),
    explanation: 'Virtual switches support port groups that can be assigned different VLAN tags, just like trunk ports on a physical switch. This segments VM traffic at Layer 2 without needing separate physical switches. NAT mode, NIC teaming, and host-only adapters do not provide VLAN segmentation.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-38',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'What is the purpose of Intel EPT (Extended Page Tables) and AMD NPT (Nested Page Tables)?',
    choices: ch(
      'To encrypt VM disk files',
      'To accelerate memory address translation between guest and host',
      'To allow USB passthrough to VMs',
      'To enable snapshot functionality',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Intel EPT and AMD NPT (also called RVI — Rapid Virtualization Indexing) provide hardware-accelerated memory virtualization by directly translating guest virtual addresses to host physical addresses. This reduces the overhead of maintaining shadow page tables in software.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-39',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'A technician needs to create an exact duplicate of an existing VM including all its data and configuration. Which operation should be used?',
    choices: ch(
      'Snapshot',
      'Template conversion',
      'VM cloning',
      'Live migration',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'VM cloning creates an exact duplicate of an existing VM, including its disk contents and configuration. A snapshot saves the VM state for rollback but does not create a separate VM. Template conversion creates a reusable base image, and live migration moves a VM between hosts.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-40',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Why are VM snapshots NOT considered proper backups?',
    choices: ch(
      'Snapshots cannot capture the current RAM state',
      'Snapshots are stored on the same storage as the VM and are lost if that storage fails',
      'Snapshots only work on Type 1 hypervisors',
      'Snapshots expire automatically after 24 hours',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Snapshots reside on the same storage as the VM. If the underlying storage fails, both the VM and all its snapshots are lost. True backups export VM data to a separate, independent storage location. Snapshots do capture RAM state, work on both hypervisor types, and do not automatically expire.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-41',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Docker containers run natively on Linux. How does Docker run on Windows and macOS?',
    choices: ch(
      'Docker translates Linux system calls to the host OS in real-time',
      'Docker runs inside a lightweight Linux VM on the host',
      'Docker requires a Type 1 hypervisor on Windows and macOS',
      'Docker containers cannot run on Windows or macOS',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'On Windows and macOS, Docker Desktop runs a lightweight Linux virtual machine (using Hyper-V or WSL 2 on Windows, and the Apple Hypervisor framework on macOS) and runs Linux containers inside that VM. The containers still use the Linux kernel, not the host OS kernel directly.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-42',
    topicId: 'topic-c1-4-1',
    type: 'single_choice' as const,
    stem: 'Which VDI display protocol is associated with VMware Horizon?',
    choices: ch(
      'RDP',
      'ICA/HDX',
      'PCoIP',
      'VNC',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'PCoIP (PC over IP) is the display protocol used by VMware Horizon for VDI. RDP is Microsoft\'s protocol, ICA/HDX is Citrix\'s protocol, and VNC is an open-source remote desktop protocol not specifically tied to VDI platforms.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // --- hard (8) ---
  {
    id: 'q-c1-4-1-43',
    topicId: 'topic-c1-4-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are characteristics of a Type 1 (bare-metal) hypervisor? (Select TWO)',
    choices: chMulti(
      'Runs directly on physical hardware without a host OS',
      'Installs as an application on Windows or macOS',
      'Provides the highest VM performance due to no host OS overhead',
      'Is primarily used for desktop testing and development',
      ['a', 'c']
    ),
    correctAnswer: cam('a', 'c'),
    explanation: 'Type 1 hypervisors install directly on hardware (no host OS) and deliver the highest performance because there is no host OS overhead. Type 2 hypervisors install as applications on a host OS and are commonly used for desktop testing and development.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-44',
    topicId: 'topic-c1-4-1',
    type: 'multiple_choice' as const,
    stem: 'A network administrator is setting up isolated test labs using virtualization. Which TWO VM networking modes provide NO internet access? (Select TWO)',
    choices: chMulti(
      'NAT',
      'Bridged',
      'Host-only',
      'Internal',
      ['c', 'd']
    ),
    correctAnswer: cam('c', 'd'),
    explanation: 'Host-only mode restricts the VM to communicating with the host and other VMs on the same host-only network — no internet. Internal mode is even more isolated, allowing VMs to communicate only with each other, not even with the host. NAT and bridged modes both provide internet access.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-45',
    topicId: 'topic-c1-4-1',
    type: 'multiple_choice' as const,
    stem: 'Which THREE of the following are valid reasons to use VM snapshots? (Select THREE)',
    choices: chMulti(
      'Before applying operating system updates',
      'As a long-term replacement for backups',
      'Before making configuration changes',
      'Before testing new software installations',
      ['a', 'c', 'd']
    ),
    correctAnswer: cam('a', 'c', 'd'),
    explanation: 'Snapshots are ideal before OS updates, configuration changes, and software installations because they allow quick rollback if something goes wrong. However, snapshots are NOT a replacement for backups — they reside on the same storage and long chains degrade performance.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-46',
    topicId: 'topic-c1-4-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are advantages of containers over traditional virtual machines? (Select TWO)',
    choices: chMulti(
      'Stronger security isolation through separate kernels',
      'Faster startup time measured in milliseconds',
      'Smaller resource footprint since they share the host kernel',
      'Built-in hardware emulation for cross-architecture support',
      ['b', 'c']
    ),
    correctAnswer: cam('b', 'c'),
    explanation: 'Containers start in milliseconds (vs. seconds-to-minutes for VMs) and have a much smaller footprint because they share the host kernel rather than booting a full OS. VMs provide stronger isolation (separate kernels), not containers. Containers do not provide hardware emulation.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-47',
    topicId: 'topic-c1-4-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO features are required for live migration (vMotion) of a running VM between hosts? (Select TWO)',
    choices: chMulti(
      'Shared storage accessible by both source and destination hosts',
      'Identical monitor resolutions on both hosts',
      'Compatible CPU architectures on both hosts',
      'Matching desktop wallpapers on both hypervisors',
      ['a', 'c']
    ),
    correctAnswer: cam('a', 'c'),
    explanation: 'Live migration requires shared storage (so both hosts can access the VM disk files) and compatible CPU architectures (so the VM can continue executing instructions on the destination). Monitor resolution and desktop settings are irrelevant to hypervisor-level migration.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-48',
    topicId: 'topic-c1-4-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following virtual disk formats are specific to Microsoft Hyper-V? (Select TWO)',
    choices: chMulti(
      'VMDK',
      'VHD',
      'QCOW2',
      'VHDX',
      ['b', 'd']
    ),
    correctAnswer: cam('b', 'd'),
    explanation: 'VHD (Virtual Hard Disk) and VHDX (improved VHD supporting up to 64 TB) are both Microsoft formats used by Hyper-V. VMDK is VMware\'s native format and QCOW2 is the QEMU/KVM format used on Linux.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-49',
    topicId: 'topic-c1-4-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are drawbacks of VDI (Virtual Desktop Infrastructure)? (Select TWO)',
    choices: chMulti(
      'Data is stored on endpoint devices rather than centrally',
      'Requires a reliable, low-latency network connection',
      'Graphics-intensive applications may perform poorly without GPU virtualization',
      'Cannot be accessed remotely from any location',
      ['b', 'c']
    ),
    correctAnswer: cam('b', 'c'),
    explanation: 'VDI requires a reliable, low-latency network because all display data is streamed from the server. Graphics-intensive tasks may suffer without virtualized GPUs. VDI actually keeps data centralized (not on endpoints) and supports remote access from anywhere — those are benefits, not drawbacks.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-1-50',
    topicId: 'topic-c1-4-1',
    type: 'multiple_choice' as const,
    stem: 'An organization is evaluating whether to use containers or VMs for a new microservices deployment. Which TWO factors favor containers in this scenario? (Select TWO)',
    choices: chMulti(
      'Need for OS-level isolation between services',
      'Rapid deployment and scaling of individual microservices',
      'Minimal resource overhead per service instance',
      'Requirement to run different kernel versions per service',
      ['b', 'c']
    ),
    correctAnswer: cam('b', 'c'),
    explanation: 'Containers excel at rapid deployment and scaling of microservices because they start in milliseconds and consume minimal resources. OS-level isolation and different kernel versions per service require full VMs since containers share the host kernel.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ── topic-c1-4-2: Cloud Computing (q-c1-4-2-09 through q-c1-4-2-50) ──

  // --- easy (13) ---
  {
    id: 'q-c1-4-2-09',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which cloud service model delivers a complete, ready-to-use application over the internet?',
    choices: ch(
      'IaaS',
      'PaaS',
      'SaaS',
      'DaaS',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'SaaS (Software as a Service) delivers fully functional applications over the internet that users access through a web browser. IaaS provides infrastructure, PaaS provides a development platform, and DaaS provides virtual desktops.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-10',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Microsoft 365, Google Workspace, and Salesforce CRM are all examples of which cloud service model?',
    choices: ch(
      'IaaS',
      'PaaS',
      'SaaS',
      'FaaS',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Microsoft 365, Google Workspace, and Salesforce CRM are all SaaS applications — complete software products delivered over the internet that users access without managing any underlying infrastructure, platform, or deployment.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-11',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which cloud deployment model uses infrastructure shared among multiple organizations with similar compliance or security requirements?',
    choices: ch(
      'Public cloud',
      'Private cloud',
      'Hybrid cloud',
      'Community cloud',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'A community cloud is shared by several organizations that have common concerns such as compliance, security, or mission requirements. Public cloud is open to anyone, private cloud serves one organization, and hybrid cloud combines public and private.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-12',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which NIST essential characteristic of cloud computing means users can provision resources without contacting the provider?',
    choices: ch(
      'Broad network access',
      'On-demand self-service',
      'Measured service',
      'Resource pooling',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'On-demand self-service means users can provision computing resources such as servers or storage automatically without requiring human interaction with the service provider. Broad network access refers to availability across devices, measured service means usage is tracked, and resource pooling is multi-tenant sharing.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-13',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'In the IaaS cloud model, which of the following is the CUSTOMER responsible for managing?',
    choices: ch(
      'Physical data center security',
      'The hypervisor layer',
      'The operating system and applications',
      'The network infrastructure hardware',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'In IaaS, the customer manages the operating system, middleware, applications, and data. The cloud provider manages the physical infrastructure, networking hardware, and hypervisor. This is a key aspect of the shared responsibility model.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-14',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which cloud file storage service is developed by Apple and integrates tightly with iOS and macOS?',
    choices: ch(
      'OneDrive',
      'Google Drive',
      'Dropbox',
      'iCloud Drive',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'iCloud Drive is Apple\'s cloud storage service, tightly integrated with iOS and macOS devices. OneDrive is Microsoft\'s service, Google Drive is Google\'s, and Dropbox is a cross-platform third-party service.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-15',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'What does "rapid elasticity" mean in cloud computing?',
    choices: ch(
      'Resources can only be scaled up, never down',
      'Resources can be quickly provisioned and released to match demand',
      'The cloud provider guarantees 100% uptime',
      'All data is automatically replicated across continents',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Rapid elasticity is a NIST essential cloud characteristic meaning resources can be elastically and quickly provisioned and released — sometimes automatically — to scale up or down with demand. It does not guarantee uptime or require global replication.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-16',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which cloud deployment model is owned and operated by a cloud provider and shared among multiple unrelated customers?',
    choices: ch(
      'Public cloud',
      'Private cloud',
      'Hybrid cloud',
      'Community cloud',
      'a'
    ),
    correctAnswer: ca('a'),
    explanation: 'A public cloud is owned and operated by a cloud provider (such as AWS, Azure, or GCP) and shared among multiple tenants. Resources are delivered over the public internet. Private cloud serves one organization, hybrid combines models, and community cloud serves organizations with shared concerns.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-17',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Amazon EC2 and Azure Virtual Machines are examples of which cloud service model?',
    choices: ch(
      'SaaS',
      'PaaS',
      'IaaS',
      'DaaS',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Amazon EC2 and Azure Virtual Machines provide virtualized computing infrastructure (servers, storage, networking) where the customer manages the OS and applications. This is the IaaS (Infrastructure as a Service) model.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-18',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'What is "measured service" in the context of cloud computing?',
    choices: ch(
      'The cloud provider measures the physical size of server racks',
      'Usage of cloud resources is automatically monitored, controlled, and billed',
      'The speed of network connections is measured and guaranteed',
      'The provider measures customer satisfaction through surveys',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Measured service (also called metered service) means cloud systems automatically monitor, control, and report resource usage, enabling pay-per-use billing. This transparency benefits both provider and consumer by tracking compute, storage, and bandwidth consumption.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-19',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which cloud service model allows developers to deploy code without managing the underlying operating system or infrastructure?',
    choices: ch(
      'IaaS',
      'PaaS',
      'SaaS',
      'FaaS',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'PaaS (Platform as a Service) provides a platform with the OS, runtime, and middleware managed by the provider. Developers deploy their application code and data without managing servers or operating systems. In IaaS, you manage the OS; in SaaS, the application is pre-built.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-20',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'A company wants full control over their cloud infrastructure to meet strict regulatory requirements. Which deployment model should they choose?',
    choices: ch(
      'Public cloud',
      'Private cloud',
      'Community cloud',
      'Hybrid cloud',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A private cloud is provisioned for exclusive use by a single organization, providing full control over data, hardware, and security. This makes it ideal for meeting strict compliance and regulatory requirements that may prohibit data on shared infrastructure.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-21',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'What NIST cloud characteristic allows cloud services to be accessed from any device — phones, tablets, and laptops — over the network?',
    choices: ch(
      'On-demand self-service',
      'Broad network access',
      'Resource pooling',
      'Rapid elasticity',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Broad network access means cloud resources are available over the network and can be accessed through standard mechanisms from heterogeneous client platforms including phones, tablets, laptops, and workstations.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // --- medium (21) ---
  {
    id: 'q-c1-4-2-22',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'In the shared responsibility model, which security area is ALWAYS the customer\'s responsibility regardless of the cloud service model (IaaS, PaaS, or SaaS)?',
    choices: ch(
      'Physical data center security',
      'Hypervisor patching',
      'Data classification and protection',
      'Network infrastructure maintenance',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Data classification and protection is always the customer\'s responsibility in every cloud model. The customer decides what data to store, how to classify it, and how to protect it. Physical data center security, hypervisor patching, and network infrastructure are managed by the provider.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-23',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'A company runs production workloads on-premise but uses AWS for disaster recovery. Which cloud deployment model does this describe?',
    choices: ch(
      'Public cloud',
      'Private cloud',
      'Hybrid cloud',
      'Community cloud',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Using both on-premise infrastructure and a public cloud provider (AWS) for different purposes while maintaining connectivity between them defines a hybrid cloud. The company keeps production private while leveraging public cloud for DR.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-24',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which NIST cloud characteristic describes the provider\'s resources being shared among multiple consumers using a multi-tenant model?',
    choices: ch(
      'Rapid elasticity',
      'On-demand self-service',
      'Resource pooling',
      'Measured service',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Resource pooling means the provider\'s computing resources are pooled to serve multiple consumers (multi-tenant model), with different physical and virtual resources dynamically assigned and reassigned according to demand. Consumers generally have no control over the exact location of resources.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-25',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'A developer wants to deploy a web application without configuring servers, operating systems, or runtime environments. Which cloud service model is MOST appropriate?',
    choices: ch(
      'IaaS — Amazon EC2',
      'PaaS — Heroku',
      'SaaS — Microsoft 365',
      'IaaS — Azure Virtual Machines',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'PaaS platforms like Heroku handle the OS, runtime, and middleware so developers only deploy code. IaaS (EC2, Azure VMs) requires the developer to manage the OS. SaaS (Microsoft 365) is a pre-built application, not a deployment platform.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-26',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'What is the primary advantage of a cloud SLA (Service Level Agreement)?',
    choices: ch(
      'It guarantees the cloud provider will never experience an outage',
      'It defines the provider\'s uptime commitments and remedies if targets are not met',
      'It eliminates all security risks for the customer',
      'It ensures unlimited free storage for all customers',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'An SLA defines the cloud provider\'s guaranteed uptime (e.g., 99.99%) and specifies remedies such as service credits if those targets are not met. SLAs do not guarantee zero outages, eliminate security risks, or provide unlimited storage.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-27',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'An organization connects its on-premise data center to AWS using a dedicated private circuit rather than the public internet. What is this service called?',
    choices: ch(
      'AWS Site-to-Site VPN',
      'AWS Direct Connect',
      'Amazon CloudFront',
      'AWS VPC Peering',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'AWS Direct Connect provides a dedicated private network connection from an organization\'s data center to AWS, bypassing the public internet for more consistent latency and higher bandwidth. Site-to-Site VPN uses encrypted tunnels over the internet, CloudFront is a CDN, and VPC Peering connects VPCs.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-28',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'A user reports that files appear on their work laptop even though they only saved them on their home computer. What cloud feature explains this?',
    choices: ch(
      'Cloud load balancing',
      'Cloud file synchronization',
      'Cloud-based antivirus',
      'VPN tunneling',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Cloud file synchronization services (OneDrive, Google Drive, Dropbox, iCloud) automatically sync files across all devices linked to the same account. Changes made on one device are uploaded to the cloud and downloaded to other devices.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-29',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which common cloud security misconfiguration has caused numerous data breaches by exposing data to the public internet?',
    choices: ch(
      'Enabling MFA on admin accounts',
      'Setting S3 buckets or storage containers to public access',
      'Using encrypted connections to the cloud',
      'Implementing role-based access control',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Misconfiguring cloud storage (such as AWS S3 buckets) with public access has caused many high-profile data breaches. This is a customer responsibility under the shared responsibility model. Enabling MFA, using encryption, and implementing RBAC are all security best practices, not misconfigurations.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-30',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'What is multitenancy in cloud computing?',
    choices: ch(
      'Using multiple cloud providers simultaneously',
      'Multiple customers sharing the same physical infrastructure with logical isolation',
      'Running multiple operating systems on the same virtual machine',
      'Having multiple administrators manage a single cloud account',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Multitenancy means multiple customers (tenants) share the same physical infrastructure, with each tenant\'s resources logically isolated from others. This is fundamental to the public cloud\'s cost efficiency. It is not about using multiple providers or running multiple OSes on one VM.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-31',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which cloud storage feature shows placeholder files in the local file system that are downloaded only when opened, saving local disk space?',
    choices: ch(
      'Always Available (synced locally)',
      'On-demand / Online-only',
      'Full backup mode',
      'Archive tier storage',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'On-demand (online-only) mode shows placeholder files in the local file system that exist only in the cloud until opened. This saves local storage space. Always Available downloads all files locally for offline access. This is not a backup or archive feature.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-32',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Users in a remote office complain that cloud applications are slow. Which troubleshooting step should a technician try FIRST?',
    choices: ch(
      'Migrate all workloads to a private cloud',
      'Check available bandwidth and latency to the cloud provider\'s region',
      'Disable the cloud application firewall',
      'Switch to a different cloud service model',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Slow cloud application performance is commonly caused by insufficient bandwidth or high latency. The technician should first run speed tests and measure latency to the cloud region. Migrating to private cloud, disabling firewalls, or changing service models would not address a basic connectivity issue.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-33',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'What type of cloud service is DaaS (Desktop as a Service)?',
    choices: ch(
      'A cloud-hosted virtual desktop environment delivered over the internet',
      'A physical desktop computer leased from a cloud provider',
      'A cloud-based disk drive storage solution',
      'A SaaS application for database management',
      'a'
    ),
    correctAnswer: ca('a'),
    explanation: 'DaaS (Desktop as a Service) delivers cloud-hosted virtual desktop environments over the internet. Users connect to a full desktop experience running in the cloud, similar to VDI but managed by a cloud provider rather than internal IT. It is not physical hardware, disk storage, or database software.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-34',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which cloud cost model converts large upfront capital expenditures (CapEx) into smaller ongoing operational expenditures (OpEx)?',
    choices: ch(
      'On-premise data center deployment',
      'Cloud pay-per-use pricing',
      'Purchasing extended hardware warranties',
      'Leasing dedicated fiber connections',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Cloud pay-per-use pricing eliminates large upfront hardware purchases (CapEx) and replaces them with monthly usage-based fees (OpEx). On-premise deployment requires significant CapEx. Warranties and fiber leases are separate costs that do not convert the overall spending model.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-35',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'What is a VPC (Virtual Private Cloud)?',
    choices: ch(
      'A VPN connection between two physical offices',
      'An isolated virtual network within a public cloud where you control networking configurations',
      'A private cloud owned exclusively by one organization',
      'A type of firewall appliance for cloud environments',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A VPC is an isolated virtual network within a public cloud (AWS, Azure, GCP) where the customer controls IP ranges, subnets, route tables, and gateways. It is not a VPN tunnel, a physical private cloud, or a firewall appliance.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-36',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'A website loads fast for local users but slowly for users across the country. Which cloud service would BEST address this?',
    choices: ch(
      'Moving to a larger IaaS instance',
      'Deploying a CDN (Content Delivery Network)',
      'Upgrading to a PaaS platform',
      'Adding more RAM to the server',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A CDN caches content at edge servers distributed geographically, serving users from the nearest location to reduce latency. A larger instance or more RAM does not solve geographic distance. PaaS is a development model, not a content delivery solution.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-37',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'When two users edit the same cloud-synced file on different devices before it syncs, what typically happens?',
    choices: ch(
      'One version is permanently deleted',
      'The cloud service creates a conflict copy preserving both versions',
      'Both versions merge automatically without any conflicts',
      'The cloud account is locked until an administrator intervenes',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Most cloud sync services (OneDrive, Dropbox, Google Drive) resolve synchronization conflicts by keeping both versions, with the second copy marked as a "conflicted copy" in the filename. No data is lost, no accounts are locked, and automatic merging is not performed on binary files.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-38',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'In a PaaS model, which layer does the customer NOT manage?',
    choices: ch(
      'Application code',
      'Customer data',
      'Operating system and runtime',
      'User access settings',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'In PaaS, the provider manages the operating system, runtime, middleware, and all underlying infrastructure. The customer only manages their application code, data, and user access. This is the key distinction between PaaS and IaaS, where the customer does manage the OS.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-39',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'What is the primary advantage of cloud elasticity over traditional on-premise scaling?',
    choices: ch(
      'Cloud resources never fail',
      'Resources can scale up in minutes instead of weeks to procure hardware',
      'Cloud resources are always cheaper than on-premise',
      'Elasticity eliminates the need for capacity planning',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Cloud elasticity enables provisioning additional resources in minutes, whereas on-premise scaling requires purchasing, shipping, and installing hardware — a process that takes weeks or months. Cloud resources can still fail, are not always cheaper, and capacity planning is still recommended.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-40',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'A company has unpatched virtual machines running in AWS. Under the shared responsibility model, who is responsible for applying OS patches?',
    choices: ch(
      'AWS (the cloud provider)',
      'The customer',
      'Both equally',
      'Neither — patches are applied automatically',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'In IaaS, the customer manages the operating system, which includes applying patches and updates. AWS manages the underlying infrastructure and hypervisor, but OS-level maintenance on customer VMs is the customer\'s responsibility under the shared responsibility model.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-41',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'Which cloud file storage service provides 15 GB of free storage and integrates with the Google Workspace ecosystem?',
    choices: ch(
      'OneDrive',
      'iCloud Drive',
      'Google Drive',
      'Dropbox',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Google Drive offers 15 GB of free storage and integrates with Google Workspace (Docs, Sheets, Slides, Gmail). OneDrive provides 5 GB free (Microsoft), iCloud Drive provides 5 GB free (Apple), and Dropbox provides only 2 GB free.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-42',
    topicId: 'topic-c1-4-2',
    type: 'single_choice' as const,
    stem: 'What is the primary concern when an organization considers moving sensitive data to a public cloud?',
    choices: ch(
      'Public clouds have no internet access',
      'Data resides on shared infrastructure and regulatory requirements may prohibit this',
      'Public clouds do not support encryption',
      'Public cloud providers do not offer SLAs',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'In a public cloud, data resides on shared (multi-tenant) infrastructure. Some regulatory frameworks (HIPAA, PCI-DSS, government standards) may restrict where sensitive data can be stored. Public clouds do have internet access, support encryption, and offer SLAs.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // --- hard (8) ---
  {
    id: 'q-c1-4-2-43',
    topicId: 'topic-c1-4-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are NIST essential characteristics of cloud computing? (Select TWO)',
    choices: chMulti(
      'Rapid elasticity',
      'Guaranteed zero downtime',
      'Measured service',
      'Free unlimited storage',
      ['a', 'c']
    ),
    correctAnswer: cam('a', 'c'),
    explanation: 'The five NIST essential characteristics are: on-demand self-service, broad network access, resource pooling, rapid elasticity, and measured service. Zero downtime and free unlimited storage are not NIST characteristics — they are marketing claims not guaranteed by the cloud model.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-44',
    topicId: 'topic-c1-4-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are benefits of a hybrid cloud deployment model? (Select TWO)',
    choices: chMulti(
      'Flexibility to run sensitive workloads on private infrastructure',
      'Eliminates all need for on-premise hardware',
      'Ability to burst non-sensitive workloads to public cloud during peak demand',
      'Simplifies management by using a single provider for everything',
      ['a', 'c']
    ),
    correctAnswer: cam('a', 'c'),
    explanation: 'Hybrid cloud provides flexibility to keep sensitive data on private infrastructure while bursting to public cloud during peak demand for cost optimization. It does NOT eliminate on-premise hardware (that is the private portion) and is actually more complex to manage, not simpler.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-45',
    topicId: 'topic-c1-4-2',
    type: 'multiple_choice' as const,
    stem: 'In the shared responsibility model, which TWO security tasks are ALWAYS the customer\'s responsibility across all cloud service models? (Select TWO)',
    choices: chMulti(
      'Physical data center access control',
      'Data classification and encryption',
      'Identity and access management for users',
      'Hypervisor security patching',
      ['b', 'c']
    ),
    correctAnswer: cam('b', 'c'),
    explanation: 'Data protection (classification and encryption) and identity/access management are always customer responsibilities regardless of whether the model is IaaS, PaaS, or SaaS. Physical data center security and hypervisor patching are always the cloud provider\'s responsibility.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-46',
    topicId: 'topic-c1-4-2',
    type: 'multiple_choice' as const,
    stem: 'Which THREE of the following are common customer misconfigurations that lead to cloud security breaches? (Select THREE)',
    choices: chMulti(
      'Setting storage buckets to public access',
      'Not enforcing MFA on administrator accounts',
      'Using the provider\'s managed encryption service',
      'Leaving IaaS virtual machines unpatched',
      ['a', 'b', 'd']
    ),
    correctAnswer: cam('a', 'b', 'd'),
    explanation: 'Public storage buckets, missing MFA on admin accounts, and unpatched VMs are all common customer misconfigurations that lead to breaches. Using the provider\'s managed encryption service is a security best practice, not a misconfiguration.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-47',
    topicId: 'topic-c1-4-2',
    type: 'multiple_choice' as const,
    stem: 'A company is comparing on-premise to cloud deployment. Which TWO factors favor cloud over on-premise? (Select TWO)',
    choices: chMulti(
      'Lower upfront capital expenditure',
      'More predictable fixed monthly costs for steady workloads',
      'Ability to scale resources up or down in minutes',
      'Complete independence from internet connectivity',
      ['a', 'c']
    ),
    correctAnswer: cam('a', 'c'),
    explanation: 'Cloud eliminates large upfront hardware purchases (lower CapEx) and enables rapid scaling in minutes. On-premise actually offers more predictable fixed costs for steady workloads, and cloud requires internet connectivity — independence from internet favors on-premise.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-48',
    topicId: 'topic-c1-4-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO advantages does a dedicated connection (AWS Direct Connect / Azure ExpressRoute) provide over a site-to-site VPN? (Select TWO)',
    choices: chMulti(
      'More consistent and predictable latency',
      'No cost to the customer',
      'Higher available bandwidth',
      'No need for any networking equipment on-premise',
      ['a', 'c']
    ),
    correctAnswer: cam('a', 'c'),
    explanation: 'Dedicated connections bypass the public internet, providing more consistent latency and higher bandwidth (up to 10 Gbps or more). They are not free — they cost significantly more than VPN — and still require on-premise networking equipment to terminate the connection.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-49',
    topicId: 'topic-c1-4-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following describe the difference between scalability and elasticity in cloud computing? (Select TWO)',
    choices: chMulti(
      'Scalability is the ability to handle increased workload by adding resources',
      'Elasticity is the ability to automatically scale resources up AND down based on demand',
      'Scalability only applies to storage, not compute',
      'Elasticity requires manual intervention to adjust resources',
      ['a', 'b']
    ),
    correctAnswer: cam('a', 'b'),
    explanation: 'Scalability is the ability to increase capacity by adding resources (scale up or out). Elasticity adds the dimension of automatically scaling down when demand decreases, ensuring you only pay for what you use. Scalability applies to all resources, and elasticity is specifically about automatic adjustment.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c1-4-2-50',
    topicId: 'topic-c1-4-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO CDN benefits help during a distributed denial-of-service (DDoS) attack? (Select TWO)',
    choices: chMulti(
      'Distributed infrastructure absorbs attack traffic across many edge servers',
      'CDN encrypts all origin server data at rest',
      'Content remains available from edge caches even if the origin server is overwhelmed',
      'CDN automatically patches all application vulnerabilities',
      ['a', 'c']
    ),
    correctAnswer: cam('a', 'c'),
    explanation: 'A CDN\'s geographically distributed edge servers absorb DDoS traffic across many points of presence, preventing the attack from overwhelming a single origin. Edge caches continue serving content even if the origin is under load. CDNs do not encrypt data at rest or patch application vulnerabilities.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
]
