// CompTIA A+ 220-1202 Practice Questions — Batch 6
// Core 2 Domain 2: Security (topics 2.7–2.11) + Domain 3: Software Troubleshooting
// 8 questions × 9 topics = 72 questions total

const NOW = new Date().toISOString()

type Choice = { id: string; text: string; isCorrect: boolean }

function ch(a: string, b: string, c: string, d: string, correct: 'a' | 'b' | 'c' | 'd'): string {
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: correct === 'a' },
    { id: 'b', text: b, isCorrect: correct === 'b' },
    { id: 'c', text: c, isCorrect: correct === 'c' },
    { id: 'd', text: d, isCorrect: correct === 'd' },
  ] as Choice[])
}

const ca = (id: 'a' | 'b' | 'c' | 'd') => JSON.stringify(id)

export const BATCH6_QUESTIONS = [

  // ─── 2.7 Workstation Hardening (8 questions) ──────────────────────────────

  {
    id: 'q-c2-2-7-01',
    topicId: 'topic-c2-2-7',
    type: 'single_choice',
    stem: 'A security policy requires that user accounts be locked after repeated failed login attempts to stop online brute-force attacks. Which two Group Policy settings work together to enforce this? (Choose the pair that best describes the mechanism.)',
    choices: ch(
      'Minimum password length and password history',
      'Account lockout threshold and lockout duration',
      'Maximum password age and minimum password age',
      'Password complexity and password history',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'The account lockout threshold defines how many failed attempts (typically 3–5) trigger the lockout, and the lockout duration defines how long the account remains locked (typically 30 minutes). Together they stop online brute-force attempts. Password length and complexity are important but do not directly address locking the account after failed attempts.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-7-02',
    topicId: 'topic-c2-2-7',
    type: 'single_choice',
    stem: 'An administrator wants to prevent users on domain workstations from cycling through old passwords immediately after a forced reset. Which two password policy settings must be configured together to accomplish this?',
    choices: ch(
      'Password complexity and minimum password length',
      'Maximum password age and lockout duration',
      'Password history and minimum password age',
      'Account lockout threshold and lockout observation window',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Password history prevents reuse of recently used passwords (e.g., the last 10–24). However, without a minimum password age of at least 1 day, users can change their password repeatedly in a single session to cycle back to their original password and bypass the history requirement. Both settings must be set together.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-7-03',
    topicId: 'topic-c2-2-7',
    type: 'single_choice',
    stem: 'A user steps away from their workstation without locking it and returns to find a coworker has accessed their files. Which control would have BEST prevented this unauthorized access?',
    choices: ch(
      'BitLocker drive encryption',
      'Host-based firewall with inbound rules',
      'Screensaver with password lock after inactivity timeout',
      'Antivirus with real-time protection',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A screensaver configured to require a password after an inactivity period (e.g., 5–15 minutes) would have locked the session while the user was away, preventing the coworker from accessing the files. BitLocker protects data if the drive is physically removed but does not lock a live, logged-in session. A firewall and antivirus address network and malware threats, not physical access by a local user.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-7-04',
    topicId: 'topic-c2-2-7',
    type: 'single_choice',
    stem: 'An organization uses WSUS to manage Windows updates. What is the PRIMARY advantage of deploying updates through WSUS rather than having each workstation connect directly to Microsoft Update?',
    choices: ch(
      'WSUS patches third-party applications like Chrome and Java automatically',
      'Administrators can approve, schedule, and control which updates are deployed across the organization',
      'WSUS applies zero-day patches faster than Microsoft Update',
      'WSUS encrypts update packages to prevent tampering in transit',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'WSUS (Windows Server Update Services) centralizes update management, allowing administrators to approve updates, test them before broad deployment, schedule maintenance windows, and manage bandwidth. This prevents uncontrolled updates and allows staged rollouts. WSUS does not patch third-party applications — those require separate patch management tools.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-7-05',
    topicId: 'topic-c2-2-7',
    type: 'single_choice',
    stem: 'Which of the following BEST describes the principle of least privilege as it applies to workstation user accounts?',
    choices: ch(
      'Users should share a single administrator account to simplify password management',
      'Users perform daily tasks with a standard account and use a separate admin account only for elevated tasks',
      'Administrator accounts should be password-protected but used for all daily work',
      'All users should have administrator rights so they can install software without contacting IT',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Least privilege means granting only the access required to perform a job function. Users should run with a standard (non-admin) account for all daily work — email, browsing, documents. If an elevated task is needed, a separate administrator account is used for that specific task. This limits malware damage because malware inherits the permission level of the account it runs under.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-7-06',
    topicId: 'topic-c2-2-7',
    type: 'single_choice',
    stem: 'A technician is hardening a Windows workstation and wants to prevent malicious programs from executing automatically when a USB drive is inserted. Which setting should the technician disable?',
    choices: ch(
      'BitLocker To Go',
      'AutoRun and AutoPlay',
      'Windows Defender real-time protection',
      'Remote Registry service',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'AutoRun automatically executes programs when removable media is inserted; AutoPlay presents a dialog asking what to do with the media. Both can be exploited — a malicious USB drive can run malware automatically if AutoRun is enabled. Disabling these via Group Policy (Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies) prevents automatic execution from USB drives.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-7-07',
    topicId: 'topic-c2-2-7',
    type: 'single_choice',
    stem: 'How does EDR (Endpoint Detection and Response) differ from traditional antivirus software?',
    choices: ch(
      'EDR only scans email attachments while antivirus scans the file system',
      'EDR relies solely on signature matching while antivirus uses behavioral analysis',
      'EDR monitors system behavior and records telemetry to detect novel threats; antivirus relies primarily on signature matching',
      'EDR requires an internet connection to function while antivirus works offline',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Traditional antivirus detects known-bad files by matching them against a database of signatures. EDR goes further by monitoring system behavior (process creation, network connections, file modifications) and using behavioral analysis to detect novel threats — including fileless malware and living-off-the-land attacks — that have no known signature. EDR also records telemetry for forensic investigation after an incident.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-7-08',
    topicId: 'topic-c2-2-7',
    type: 'single_choice',
    stem: 'A Windows workstation stores sensitive business data. The organization requires that the data be unreadable if the drive is physically removed and placed in another computer. Which feature fulfills this requirement?',
    choices: ch(
      'NTFS permissions on the drive',
      'BitLocker full-drive encryption',
      'A strong Windows login password',
      'Windows Defender Firewall',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'BitLocker full-drive encryption encrypts all data on the drive using AES. If the drive is physically removed and placed in another computer, the data cannot be read without the BitLocker recovery key — NTFS permissions are enforced by the OS and are bypassed when the drive is accessed from a different OS. A Windows password does not protect the drive if it is removed. A firewall protects network access, not stored data.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.8 Mobile Security (8 questions) ───────────────────────────────────

  {
    id: 'q-c2-2-8-01',
    topicId: 'topic-c2-2-8',
    type: 'single_choice',
    stem: 'A corporate security policy requires the strongest screen lock method for all company-issued smartphones. Which method provides the HIGHEST security?',
    choices: ch(
      'Swipe to unlock',
      'Four-digit PIN',
      'Pattern lock on a 3x3 grid',
      'Alphanumeric password',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'An alphanumeric password (combining letters, numbers, and symbols of any length) provides the highest security among common screen lock methods. A 4-digit PIN has only 10,000 combinations. Pattern locks are vulnerable to smudge attacks — the oil residue on the screen can reveal the pattern. Swipe provides no authentication at all.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-8-02',
    topicId: 'topic-c2-2-8',
    type: 'single_choice',
    stem: 'An employee reports that their company-issued phone was stolen at an airport. The device contains sensitive customer data. What is the FIRST action an IT administrator should take using the MDM platform?',
    choices: ch(
      'Reset the employee\'s network password',
      'Issue a remote wipe command to erase all data on the device',
      'Disable the employee\'s MDM enrollment certificate',
      'Change the device\'s SSID configuration',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'When a corporate device containing sensitive data is confirmed stolen, the immediate action is to issue a remote wipe from the MDM platform. This erases all data on the device (or selectively removes corporate data with a selective wipe). The device must be connected to the internet to receive the wipe command. Resetting the network password does not protect the data on the device.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-8-03',
    topicId: 'topic-c2-2-8',
    type: 'single_choice',
    stem: 'Which mobile screen lock type is most vulnerable to a smudge attack, where an attacker can use the oil residue on the screen to reconstruct the unlock method?',
    choices: ch(
      'Six-digit PIN',
      'Fingerprint biometric',
      'Pattern lock',
      'Alphanumeric password',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Pattern locks are specifically vulnerable to smudge attacks. When a user draws their pattern on a 3x3 grid, the oil from their finger leaves residue on the screen that traces the exact pattern. An attacker can hold the phone at an angle under bright light to see the residue and replicate the pattern. PINs and passwords leave scattered key impressions that are much harder to reconstruct.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-8-04',
    topicId: 'topic-c2-2-8',
    type: 'single_choice',
    stem: 'A company implements a BYOD policy and must ensure that if an employee leaves, corporate data can be removed from their personal device without erasing personal photos and apps. Which MDM capability accomplishes this?',
    choices: ch(
      'Full device wipe',
      'Selective wipe of the corporate work container',
      'Remote lock with a custom message',
      'Jailbreak detection and quarantine',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A selective wipe removes only the corporate data and MDM work container (apps, email, configurations) while leaving personal data — photos, personal apps, personal accounts — untouched. This is the key BYOD benefit: employees are more willing to enroll personal devices knowing IT can only wipe corporate data, not their personal content. A full wipe erases everything.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-8-05',
    topicId: 'topic-c2-2-8',
    type: 'single_choice',
    stem: 'An Android user wants to install a popular game that is not available in the Google Play Store. They find the APK file on a third-party website. What is the PRIMARY security risk of sideloading this application?',
    choices: ch(
      'The app will consume more battery than Play Store apps',
      'The APK may contain malware because it bypasses Google\'s security review process',
      'Sideloaded apps cannot access device hardware like the camera',
      'The app will not receive future updates automatically',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'The primary security risk of sideloading is that the APK has bypassed Google Play\'s security review process. Google scans apps submitted to the Play Store for malware. Sideloaded APKs — especially those from unofficial sites claiming to offer "free" versions of paid apps — frequently contain spyware, adware, or banking trojans packaged with the legitimate app content.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-8-06',
    topicId: 'topic-c2-2-8',
    type: 'single_choice',
    stem: 'Why should jailbroken iOS devices or rooted Android devices be prohibited from connecting to corporate networks?',
    choices: ch(
      'These devices cannot install MDM profiles or enforce corporate policies',
      'Jailbreaking and rooting remove OS security sandboxing, allowing any app to access any data and bypassing MDM controls',
      'These devices run slower and would affect network performance',
      'Jailbroken devices cannot use Wi-Fi — they rely only on cellular data',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Jailbreaking (iOS) or rooting (Android) removes the OS-level security sandbox. Any installed app can then access any data on the device, app signing requirements are bypassed, and MDM profiles can be removed by the user. This makes them unacceptable security risks — corporate data on a jailbroken device has no reliable access controls, and compliance enforcement via MDM is unreliable.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-8-07',
    topicId: 'topic-c2-2-8',
    type: 'single_choice',
    stem: 'Which VPN configuration tunnels only traffic from corporate apps through the VPN while allowing personal browsing to go directly to the internet?',
    choices: ch(
      'Always-on VPN',
      'Per-app VPN',
      'Split tunneling',
      'IKEv2 full-tunnel VPN',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Per-app VPN (also called app-level VPN) routes only traffic from specified corporate applications through the VPN tunnel while personal browsing bypasses the VPN and goes directly to the internet. This is common in enterprise MDM configurations and reduces VPN server load. Always-on VPN routes all traffic through the VPN. Split tunneling routes some traffic through VPN and some direct — typically configured at the network level, not per-app.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-8-08',
    topicId: 'topic-c2-2-8',
    type: 'single_choice',
    stem: 'A user receives a text message claiming to be from their bank asking them to click a link to verify their account. What type of attack is this, and what is the correct response?',
    choices: ch(
      'Bluesnarfing — turn off Bluetooth immediately',
      'Smishing — do not click the link; contact the bank directly through a verified number',
      'Vishing — report the call to the FTC',
      'SIM swapping — contact the carrier immediately',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'This is smishing — SMS-based phishing. The attacker sends a fraudulent text message with a link that leads to a credential-harvesting page designed to look like the bank\'s site. The correct response is to not click the link and instead contact the bank directly using the phone number on the back of the bank card or on the official website — not any number or link in the text message.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.9 Data Destruction (8 questions) ──────────────────────────────────

  {
    id: 'q-c2-2-9-01',
    topicId: 'topic-c2-2-9',
    type: 'single_choice',
    stem: 'A healthcare organization is retiring a fleet of laptops with traditional spinning hard drives that contain patient PHI. They need to ensure the data cannot be recovered and must comply with HIPAA. Which destruction method is MOST appropriate and provides the highest assurance?',
    choices: ch(
      'Deleting all files and emptying the Recycle Bin',
      'Performing a quick format of the drives',
      'Physical shredding of the drives by a certified destruction vendor with a Certificate of Destruction',
      'Degaussing the drives and reusing them for another department',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Physical shredding by a certified vendor provides the highest assurance — the drive is reduced to fragments too small to reconstruct data from. For regulated PHI data, HIPAA requires purging or physical destruction with documented chain of custody. A Certificate of Destruction provides the compliance documentation needed for audits. Deleting files and quick formatting leave data recoverable. Degaussing destroys the drive permanently but provides no reuse option and no documentation unless paired with a CoD.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-9-02',
    topicId: 'topic-c2-2-9',
    type: 'single_choice',
    stem: 'A technician is disposing of several SSDs that contained confidential business data. Why is degaussing NOT an effective data destruction method for SSDs?',
    choices: ch(
      'SSDs are too small for degaussing equipment to target accurately',
      'SSDs store data using flash memory cells with no magnetic domains — degaussing has no effect on them',
      'Degaussing only works on drives larger than 1 TB',
      'SSDs encrypt data automatically so degaussing is redundant',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Degaussing works by generating a powerful magnetic field that disrupts the magnetic domains on magnetic media, destroying the data. SSDs (and USB flash drives, SD cards, and NVMe drives) store data in NAND flash memory cells using electrical charge — not magnetic domains. A magnetic field has no effect on flash storage. For SSDs, the correct software method is ATA Secure Erase (or NVMe format with secure erase), or physical destruction.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-9-03',
    topicId: 'topic-c2-2-9',
    type: 'single_choice',
    stem: 'The DoD 5220.22-M standard specifies a 7-pass overwrite for data sanitization. A technician applies this standard to an SSD. What is the problem with this approach?',
    choices: ch(
      'Seven passes take too long — the standard requires only 3 passes for SSDs',
      'Overwriting is unreliable on SSDs because wear leveling means the SSD controller may not overwrite all cells that held the original data',
      'The DoD standard only applies to classified government systems, not commercial SSDs',
      'SSDs do not support the overwrite command at the ATA level',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'SSDs use wear leveling — the SSD controller distributes writes across flash cells to prevent premature wear. When an OS-level overwrite command is issued, the controller decides which physical cells to write, and may leave previously used cells containing original data untouched. This means traditional file-level or volume-level overwriting cannot guarantee all data cells are erased on an SSD. ATA Secure Erase or physical destruction are the correct methods for SSDs.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-9-04',
    topicId: 'topic-c2-2-9',
    type: 'single_choice',
    stem: 'An organization\'s encrypted SSD needs to be repurposed for a new employee. The drive used BitLocker with a TPM. What is the FASTEST and most effective way to ensure the previous data cannot be recovered?',
    choices: ch(
      'Perform a 7-pass DoD overwrite of the SSD',
      'Run ATA Secure Erase using the manufacturer\'s tool',
      'Perform a cryptographic wipe by deleting the BitLocker key protectors, then reformat',
      'Physically drill through the SSD chips before reuse',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Cryptographic wipe (crypto erase) is the fastest and most effective method for an already-encrypted drive. By deleting the BitLocker key protectors, the encryption key is destroyed. All remaining data on the SSD is AES-encrypted ciphertext that is permanently unreadable without the key. The drive can then be reformatted and reused. This is nearly instantaneous compared to ATA Secure Erase, and drilling destroys the drive permanently.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-9-05',
    topicId: 'topic-c2-2-9',
    type: 'single_choice',
    stem: 'What is the purpose of a Certificate of Destruction issued by a data destruction vendor?',
    choices: ch(
      'It certifies that the destruction vendor\'s equipment meets NSA specifications',
      'It is documentation proving specific devices were destroyed by a specific method on a specific date, used for regulatory compliance',
      'It grants the organization liability immunity from any future data breaches',
      'It is required by the vendor\'s insurance and has no compliance value for the organization',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A Certificate of Destruction (CoD) is a formal document that records the organization name, device serial numbers, destruction method, date, and the vendor\'s information. It serves as evidence of due diligence in regulatory compliance audits (HIPAA, PCI DSS, GDPR). If a data breach investigation occurs, the CoD demonstrates that specific devices were properly destroyed and cannot be the source of a leak.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-9-06',
    topicId: 'topic-c2-2-9',
    type: 'single_choice',
    stem: 'According to NIST SP 800-88, which category of data sanitization is achieved by performing a 7-pass overwrite of a traditional hard drive?',
    choices: ch(
      'Clear',
      'Purge',
      'Destroy',
      'Sanitize',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'NIST SP 800-88 defines three categories: Clear (overwriting with patterns — protects against casual recovery but not laboratory analysis), Purge (ATA Secure Erase, degaussing, cryptographic erase — resistant to laboratory analysis), and Destroy (physical destruction — the media cannot be reused). A 7-pass DoD overwrite applied to an HDD meets the Purge standard — it is resistant to laboratory forensic recovery.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-9-07',
    topicId: 'topic-c2-2-9',
    type: 'single_choice',
    stem: 'A technician needs to destroy an old LTO tape that contains archived financial records. Which destruction method would be effective for magnetic tape?',
    choices: ch(
      'ATA Secure Erase',
      'Cryptographic wipe using NVMe format',
      'Degaussing with an industrial degausser',
      'Quick format using the tape management software',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Magnetic tape (LTO, DLT) stores data using magnetic domains — the same technology as traditional hard drives. Degaussing is effective for magnetic tape because the strong magnetic field disrupts the magnetic domains, destroying the data. ATA Secure Erase is an ATA drive command that does not apply to tape. Cryptographic wipe only works if the tape was encrypted. A quick format does not erase the underlying data.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-9-08',
    topicId: 'topic-c2-2-9',
    type: 'single_choice',
    stem: 'What is a significant side effect of degaussing a traditional hard disk drive (HDD)?',
    choices: ch(
      'The drive\'s warranty is voided but the drive still functions normally',
      'The HDD is permanently rendered unusable because the servo tracks that guide the read/write heads are also destroyed',
      'The drive must be reformatted before it can be reused, which takes approximately 24 hours',
      'Only the partition table is destroyed; the raw data on the platters remains readable',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'HDDs rely on servo tracks — magnetically encoded timing and positioning information — to guide the read/write heads precisely across the platters. A degausser destroys all magnetic information on the drive, including these servo tracks. Without servo tracks, the drive controller cannot position the heads, making the drive permanently unusable. There is no way to reformat or reuse a degaussed HDD.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.10 SOHO Network Security (8 questions) ─────────────────────────────

  {
    id: 'q-c2-2-10-01',
    topicId: 'topic-c2-2-10',
    type: 'single_choice',
    stem: 'A small business owner sets up a new Wi-Fi router and connects it to the internet. What is the MOST critical first security step before any other configuration?',
    choices: ch(
      'Enable WPS for easy device pairing',
      'Configure MAC address filtering for all devices',
      'Change the default administrator username and password',
      'Hide the SSID so neighboring devices cannot see the network',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Default router credentials (admin/admin, admin/password) are publicly documented for every router model and are the first thing automated scanners test. An attacker who gains access to the router admin interface can reconfigure all security settings. Changing the default credentials is the single most critical first step for any network device. WPS should actually be disabled, not enabled.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-10-02',
    topicId: 'topic-c2-2-10',
    type: 'single_choice',
    stem: 'WPS (Wi-Fi Protected Setup) is enabled on a SOHO router that uses a strong WPA2-AES passphrase. A neighbor uses the tool Reaver to attack the network and gains access in under 24 hours despite the strong passphrase. Why was this possible?',
    choices: ch(
      'Reaver cracked the WPA2-AES passphrase using a dictionary attack',
      'WPS has a design flaw where its 8-digit PIN can be brute-forced in under 11,000 attempts, then used to retrieve the WPA2 passphrase',
      'The router firmware was outdated and contained a known vulnerability',
      'Reaver exploited weak WPA2-TKIP encryption that was running alongside AES',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'WPS\'s 8-digit PIN is validated in two halves (first 4 digits, then last 4 digits), which reduces the effective combinations from 100,000,000 to approximately 11,000. Tools like Reaver exploit this by brute-forcing each half separately. Once the PIN is found, the router provides the full WPA2 passphrase — no matter how strong it is. WPS completely bypasses passphrase strength. The only fix is to disable WPS entirely.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-10-03',
    topicId: 'topic-c2-2-10',
    type: 'single_choice',
    stem: 'A router is configured with WPA2. The administrator can choose between TKIP and AES (CCMP) as the cipher. Which should they select and why?',
    choices: ch(
      'TKIP, because it is more compatible with older devices',
      'AES (CCMP), because TKIP has known vulnerabilities and AES provides stronger encryption',
      'Both should be enabled simultaneously to support all client types',
      'TKIP, because AES requires additional hardware not present in consumer routers',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'WPA2-AES (using the CCMP cipher) is the correct choice. TKIP was a transitional cipher designed to work on older WEP hardware — it has known cryptographic weaknesses. Modern routers and all modern clients support AES/CCMP. Enabling both simultaneously (sometimes called WPA2-Mixed) introduces TKIP weakness back into the network. Always select WPA2-AES exclusively.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-10-04',
    topicId: 'topic-c2-2-10',
    type: 'single_choice',
    stem: 'An administrator disables SSID broadcast on a SOHO router believing this will hide the network from attackers. Which statement accurately describes the security value of this action?',
    choices: ch(
      'It completely hides the network — passive scanning tools cannot detect it',
      'It provides strong protection by preventing unauthorized users from knowing the network exists',
      'It is security through obscurity only — hidden SSIDs are still discoverable with passive Wi-Fi scanning tools that detect probe requests',
      'Disabling SSID broadcast also disables WPS, providing a secondary security benefit',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Hiding the SSID is a common misconception of security. When SSID broadcast is disabled, the access point still sends probe responses, and client devices send probe requests for the network — both of which reveal the SSID to any passive Wi-Fi scanner. The network is only hidden from the basic "Available Networks" list in Windows, not from an attacker using a Wi-Fi analysis tool. Real security comes from WPA3/WPA2-AES and a strong passphrase.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-10-05',
    topicId: 'topic-c2-2-10',
    type: 'single_choice',
    stem: 'A SOHO office has several IoT devices — smart thermostats, IP cameras, and smart speakers. The office router supports guest network isolation. What is the BEST practice for these IoT devices?',
    choices: ch(
      'Connect IoT devices to the main network for the fastest speeds',
      'Connect IoT devices to the guest network to isolate them from the main internal network and business computers',
      'Disable all IoT devices as they are inherently too insecure for any business environment',
      'Create individual VLANs for each IoT device type for maximum segmentation',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'IoT devices often run unpatched firmware, have hardcoded credentials, and are frequent botnet targets. Placing them on the guest network isolates them from the main internal network — a compromised IoT device cannot reach business computers, file shares, or the router admin interface. This limits the "blast radius" of any IoT compromise. The guest network provides internet access for device functionality while blocking internal network access.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-10-06',
    topicId: 'topic-c2-2-10',
    type: 'single_choice',
    stem: 'UPnP (Universal Plug and Play) is enabled on a SOHO router. Why do security best practices recommend disabling UPnP?',
    choices: ch(
      'UPnP increases power consumption and shortens the router\'s lifespan',
      'UPnP slows down the router because it continuously broadcasts on the network',
      'Malware can abuse UPnP to automatically open inbound firewall port-forwarding rules without user interaction',
      'UPnP is only compatible with IPv6 and causes conflicts on IPv4 networks',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'UPnP allows devices on the network to automatically request port-forwarding rules on the router. While convenient for gaming and some applications, malware can exploit UPnP to open ports that allow attackers direct inbound access to infected machines. Because UPnP requires no authentication from the requesting device, any malware on the local network can create forwarding rules. Disabling UPnP prevents this unauthorized port opening.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-10-07',
    topicId: 'topic-c2-2-10',
    type: 'single_choice',
    stem: 'What is the key security improvement WPA3 provides over WPA2 regarding passphrase attacks?',
    choices: ch(
      'WPA3 uses a longer IV (initialization vector) to prevent replay attacks',
      'WPA3 uses SAE (Simultaneous Authentication of Equals), which prevents offline brute-force attacks against captured handshakes',
      'WPA3 requires a minimum 20-character passphrase, making dictionary attacks impractical',
      'WPA3 uses MAC address verification as a second factor of authentication',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'WPA2 uses a PSK (Pre-Shared Key) handshake that, if captured, can be attacked offline — an attacker can capture the 4-way handshake and then run a dictionary or brute-force attack against it at any speed without being connected to the network. WPA3 uses SAE (Simultaneous Authentication of Equals), which prevents offline attacks. Even if the handshake is captured, it cannot be cracked offline — each authentication attempt requires interaction with the network.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-10-08',
    topicId: 'topic-c2-2-10',
    type: 'single_choice',
    stem: 'A technician configures a port forwarding rule on a SOHO router to allow remote desktop access to a specific internal PC. Later, the admin wants a more secure alternative that doesn\'t require permanently open ports. What should be configured instead?',
    choices: ch(
      'Enable the DMZ and place the PC in it for full external access',
      'Enable MAC address filtering to only allow the remote user\'s MAC address',
      'Configure a VPN on the router so remote users connect to the VPN first, then access the PC through the secure internal network',
      'Enable WPS to allow quick pairing from the remote location',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A VPN (Virtual Private Network) configured on the router allows remote users to establish an encrypted tunnel into the internal network before accessing the remote desktop. This avoids permanently open port-forwarding rules exposed to the internet, which are a common attack surface. Remote desktop through VPN is a best practice — no RDP port needs to be exposed to the internet. DMZ exposure is the opposite of more secure.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.11 Browser Security (8 questions) ─────────────────────────────────

  {
    id: 'q-c2-2-11-01',
    topicId: 'topic-c2-2-11',
    type: 'single_choice',
    stem: 'A user is browsing in Chrome\'s Incognito mode and believes their internet traffic is hidden from their employer\'s network monitoring. Which statement is accurate?',
    choices: ch(
      'Incognito mode encrypts all traffic, making it invisible to network monitoring',
      'Incognito mode only prevents the local browser from saving history and cookies — network traffic is still visible to the employer\'s monitoring tools and ISP',
      'Incognito mode hides the user\'s IP address from websites they visit',
      'Incognito mode routes traffic through Google\'s servers, hiding the source from employers',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Private/Incognito browsing only prevents the browser from saving local history, cookies, and form data on the device. It does nothing to hide network traffic — the employer\'s network monitoring, the ISP, and the visited websites all see the same traffic as in a normal session. To hide traffic from network monitoring, a VPN is required. To be truly anonymous, additional tools beyond just a VPN are needed.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-11-02',
    topicId: 'topic-c2-2-11',
    type: 'single_choice',
    stem: 'A user visits an internal company web server and receives the error "Your connection is not private — NET::ERR_CERT_AUTHORITY_INVALID." The certificate is signed by the company\'s internal CA. What is the correct fix?',
    choices: ch(
      'Replace the internal server\'s certificate with a public Let\'s Encrypt certificate',
      'Add the company\'s internal root CA certificate to the Trusted Root Certification Authorities store on the user\'s workstation',
      'Click "Proceed anyway" as internal sites are always safe',
      'Disable certificate checking in the browser settings for internal sites',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'The browser cannot validate the internal CA because it is not in the browser\'s trusted root store by default. The correct fix is to deploy the organization\'s internal root CA certificate to all workstations\' Trusted Root Certification Authorities store — typically via Group Policy in a domain environment. This tells the browser to trust certificates signed by that CA. Clicking "Proceed anyway" repeatedly is poor practice and bypasses security validation.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-11-03',
    topicId: 'topic-c2-2-11',
    type: 'single_choice',
    stem: 'A user clicks on a link in an email and their browser displays a certificate error stating the hostname does not match the certificate. What does this error indicate?',
    choices: ch(
      'The website\'s SSL certificate has expired and needs renewal',
      'The certificate was issued by an untrusted Certificate Authority',
      'The certificate is valid but was issued for a different domain — this may indicate a misconfiguration or a man-in-the-middle attack',
      'The browser does not support the encryption algorithm used by the certificate',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'A hostname mismatch means the domain in the URL does not match the domain(s) on the certificate (the Common Name or Subject Alternative Names). This can indicate a misconfigured server redirect, or it can be a sign of a man-in-the-middle (MITM) attack where an attacker is intercepting traffic with a certificate issued for a different domain. The user should not proceed, especially for sites handling sensitive information.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-11-04',
    topicId: 'topic-c2-2-11',
    type: 'single_choice',
    stem: 'A user reports that their browser homepage has changed to an unknown search engine, a new toolbar appeared, and searches redirect to unfamiliar sites. What is the MOST likely cause, and what is the correct first step to resolve it?',
    choices: ch(
      'The browser update changed the default settings — restore them via Settings',
      'The user\'s router was compromised — change the router admin password',
      'Browser hijacking by malware or a malicious extension — remove unknown extensions and run an anti-malware scan',
      'The user accidentally enabled the browser\'s experimental features — disable them in flags',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Homepage changes, unexpected toolbars, and search redirects are the classic symptoms of browser hijacking — malware or a malicious browser extension that modifies browser settings without consent. The correct approach is to: (1) remove unknown extensions from the browser, (2) run an anti-malware scan with Windows Defender or Malwarebytes, (3) use the browser\'s built-in reset function to restore defaults, and (4) clear cookies and cache. Simply restoring settings without removing the malware allows it to reapply the hijacking.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-11-05',
    topicId: 'topic-c2-2-11',
    type: 'single_choice',
    stem: 'A user visits a banking website and sees a pop-up in their browser saying "WARNING: Your computer is infected with 3 viruses! Call Microsoft Support at 1-888-XXX-XXXX immediately to fix." What type of attack is this?',
    choices: ch(
      'A legitimate Windows Defender alert displayed through the browser',
      'A phishing email that opened in the browser',
      'Scareware — a social engineering attack delivered through a malicious website designed to frighten users into calling a fraudulent support number',
      'A DNS hijacking attack that redirected the bank\'s legitimate alert system',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'This is scareware (also called a tech support scam). It is a webpage or browser pop-up — not a real system alert — designed to create panic and convince the user to call a fraudulent phone number. Legitimate security software (Windows Defender, etc.) never delivers alerts through a web browser pop-up. The web browser has no ability to scan the system for malware. The correct response is to close the browser tab or kill the browser process, not call the number.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-11-06',
    topicId: 'topic-c2-2-11',
    type: 'single_choice',
    stem: 'A browser extension requests permission to "Read and change all your data on all websites." What is the security concern with granting this permission?',
    choices: ch(
      'The extension will significantly slow browser performance by reading every page',
      'The extension gains access to the content of every website visited, including banking, email, and credentials — a malicious extension can steal this data',
      'The extension can modify the browser\'s source code and disable security features',
      'The permission only applies to http sites, not https, so financial sites are safe',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'A browser extension with "Read and change all your data on all websites" can read and modify the content of every page you visit — including banking sites, webmail, and any page where you enter credentials. Malicious extensions published to official stores have used this permission to steal session cookies, capture form data including passwords, and inject malicious scripts. Only install extensions from trusted developers and review permissions before installing.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-11-07',
    topicId: 'topic-c2-2-11',
    type: 'single_choice',
    stem: 'What is the security advantage of using a dedicated password manager\'s autofill compared to manually typing passwords?',
    choices: ch(
      'Password managers encrypt the autofilled data at a higher level than the browser\'s TLS',
      'Password managers autofill only on the exact matching domain, protecting against phishing sites with similar-looking URLs',
      'Password managers automatically change passwords every 30 days to prevent reuse',
      'Password managers bypass MFA requirements for trusted sites',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Password managers autofill credentials only when the domain exactly matches where the credentials were saved. If credentials were saved for "paypal.com" and a phishing site at "paypa1.com" or "paypal-secure.com" is visited, the password manager will not autofill because the domain doesn\'t match. This is a built-in phishing defense. A user manually typing their password might not notice the URL difference, but the password manager catches it.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-11-08',
    topicId: 'topic-c2-2-11',
    type: 'single_choice',
    stem: 'Which browser security feature — built into Microsoft Edge and Google Chrome — checks URLs and downloaded files against a database of known malicious addresses and file hashes in real time?',
    choices: ch(
      'HTTPS-only mode',
      'Certificate pinning',
      'SmartScreen (Edge) / Safe Browsing (Chrome)',
      'Third-party cookie blocking',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Microsoft SmartScreen (built into Edge and Internet Explorer) and Google Safe Browsing (Chrome, Firefox, Safari) are real-time URL and file reputation services. They check every URL visited and every file downloaded against databases of known phishing URLs, malware sites, and malicious file hashes. When a match is found, the browser displays a warning page before loading the site. Both should remain enabled — they are on by default and have negligible performance overhead.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.1 Troubleshoot Windows OS (8 questions) ────────────────────────────

  {
    id: 'q-c2-3-1-01',
    topicId: 'topic-c2-3-1',
    type: 'single_choice',
    stem: 'A user\'s Windows 10 workstation displays a blue screen with stop code MEMORY_MANAGEMENT and then reboots. This happens approximately 20 minutes after every boot. Where are the minidump files stored that a technician would analyze to identify the faulting module?',
    choices: ch(
      'C:\\Windows\\System32\\Logs\\',
      'C:\\Windows\\Minidump\\',
      'C:\\ProgramData\\Microsoft\\Windows\\WER\\',
      'C:\\Users\\[Username]\\AppData\\Local\\CrashDumps\\',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Windows writes minidump (.dmp) files to C:\\Windows\\Minidump\\ automatically after a BSOD. These files contain the stop code, the list of loaded modules, and the call stack at the time of the crash. A technician uses WinDbg (Windows Debugger) to open the .dmp file and identify the faulting module. MEMORY_MANAGEMENT errors that occur consistently after the same amount of runtime strongly suggest a faulty RAM stick.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-1-02',
    topicId: 'topic-c2-3-1',
    type: 'single_choice',
    stem: 'A user complains that Windows 10 takes 4 minutes to boot. The PC has 16 GB of RAM, a clean SSD, and no malware. Task Manager shows 22 startup programs enabled. What is the MOST likely cause and the BEST first step?',
    choices: ch(
      'The SSD needs to be defragmented — run Disk Defragmenter',
      'The system needs more RAM — upgrade to 32 GB',
      'Too many startup programs are loading — disable non-essential entries in Task Manager\'s Startup tab',
      'Windows Update is downloading updates in the background — pause updates',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Excessive startup programs are the most common cause of slow boot on consumer PCs. With 22 startup programs, Windows must load each one during boot, significantly extending startup time. The fix is to open Task Manager > Startup tab, review each entry, and disable non-essential programs. The "Startup impact" column helps prioritize which ones to disable first. SSDs should never be defragmented — this would be incorrect and potentially harmful.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-1-03',
    topicId: 'topic-c2-3-1',
    type: 'single_choice',
    stem: 'A technician runs sfc /scannow and receives the message "Windows Resource Protection found corrupt files but was unable to fix some of them." What should the technician do NEXT?',
    choices: ch(
      'Run chkdsk /f /r to repair the file system errors before retrying sfc',
      'Run DISM /Online /Cleanup-Image /RestoreHealth to repair the component store, then re-run sfc /scannow',
      'Reinstall Windows immediately — sfc failure means the OS is unrecoverable',
      'Delete the corrupt files manually from C:\\Windows\\System32 and run sfc again',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'SFC (System File Checker) replaces corrupted system files using files from the Windows Component Store. If the component store itself is corrupted, sfc cannot source the replacement files and reports it cannot fix errors. The fix is to run DISM /Online /Cleanup-Image /RestoreHealth first — DISM repairs the component store by downloading correct files from Windows Update. After DISM completes successfully, re-running sfc /scannow will be able to repair the corrupted files.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-1-04',
    topicId: 'topic-c2-3-1',
    type: 'single_choice',
    stem: 'A Windows 10 PC fails to boot and displays the error "BOOTMGR is missing." The technician boots into the Windows Recovery Environment (WinRE) and opens a Command Prompt. Which sequence of commands will MOST likely resolve this?',
    choices: ch(
      'sfc /scannow followed by DISM /Online /Cleanup-Image /RestoreHealth',
      'bootrec /fixmbr followed by bootrec /fixboot followed by bootrec /rebuildbcd',
      'chkdsk C: /f /r followed by a reboot',
      'diskpart followed by format c: /q',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: '"BOOTMGR is missing" indicates the Master Boot Record, boot sector, or Boot Configuration Data is corrupted or missing. The standard repair sequence from WinRE Command Prompt is: bootrec /fixmbr (writes new MBR), bootrec /fixboot (writes new boot sector to the active partition), and bootrec /rebuildbcd (rebuilds the Boot Configuration Data). Running sfc from WinRE targets the offline Windows installation and does not repair the boot files. chkdsk would check disk errors but not fix boot configuration.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-1-05',
    topicId: 'topic-c2-3-1',
    type: 'single_choice',
    stem: 'A user reports that every time they log in, their desktop icons are missing, settings haven\'t saved, and they receive the message "You\'ve been signed in with a temporary profile." What is the MOST likely cause?',
    choices: ch(
      'Malware deleted the user\'s profile folder',
      'The user\'s profile is stored on a network share that is currently offline',
      'The user\'s profile registry hive (NTUSER.DAT) is corrupted, causing Windows to load a temporary profile instead',
      'Windows Update changed the user\'s profile location during an automatic update',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'The "signed in with a temporary profile" message means Windows could not load the user\'s actual profile registry hive (NTUSER.DAT). This is typically caused by corruption of NTUSER.DAT from improper shutdown, disk errors, or permission changes. Windows creates a temporary profile for the session, but nothing saves between logins because the temporary profile is deleted at logout. The fix involves creating a new user account and migrating the user\'s data from the old profile folder.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-1-06',
    topicId: 'topic-c2-3-1',
    type: 'single_choice',
    stem: 'A user\'s Windows PC fails to install a cumulative update. The error code shown in Windows Update history is 0x80070002. After running the Windows Update Troubleshooter with no result, what is the NEXT recommended step?',
    choices: ch(
      'Roll back Windows to the previous version',
      'Clear the SoftwareDistribution\\Download cache by stopping the Windows Update service, deleting the folder contents, and restarting the service',
      'Disable Windows Defender Firewall temporarily and retry the update',
      'Upgrade to Windows 11 to resolve the update engine issue',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'The SoftwareDistribution\\Download folder is where Windows Update caches downloaded update packages. If a download becomes corrupted, the Update service gets stuck trying to use the bad cached file. The fix is to stop the Windows Update service (net stop wuauserv), delete the contents of C:\\Windows\\SoftwareDistribution\\Download, and restart the service (net start wuauserv). Windows will re-download the update fresh. This resolves many common update error codes.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-1-07',
    topicId: 'topic-c2-3-1',
    type: 'single_choice',
    stem: 'A technician installs a new driver for a network card and the PC immediately becomes unstable with frequent BSODs. The technician wants to quickly return to the previously working driver. What is the FASTEST method?',
    choices: ch(
      'Run sfc /scannow to restore the original driver from the component store',
      'Use Device Manager to roll back the driver to the previous version',
      'Boot into WinRE and use System Image Recovery',
      'Use Windows Update to uninstall the latest driver update',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Device Manager maintains a record of the previously installed driver version for each device. Right-clicking the device in Device Manager > Properties > Driver tab > Roll Back Driver reverts to the previous driver version immediately — no media or reinstallation required. This is the fastest method when a driver update causes instability. The "Roll Back Driver" button is grayed out if there is no previous version stored.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-1-08',
    topicId: 'topic-c2-3-1',
    type: 'single_choice',
    stem: 'A Windows workstation boots normally but a critical application crashes every time it is launched. Event Viewer shows an entry in the Application log with the faulting module "VCRUNTIME140.dll." What is the MOST likely fix?',
    choices: ch(
      'Run sfc /scannow to replace the DLL from the Windows component store',
      'Reinstall the Microsoft Visual C++ Redistributable package that provides the missing DLL',
      'Download VCRUNTIME140.dll from a third-party DLL repository website and place it in System32',
      'Upgrade Windows to resolve the incompatible DLL version',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'VCRUNTIME140.dll is part of the Microsoft Visual C++ 2015-2022 Redistributable package. When an application crashes because this DLL is missing or corrupted, the fix is to download and reinstall the appropriate Visual C++ Redistributable from Microsoft\'s official site. Never download DLLs from third-party "DLL fix" websites — these are a primary malware distribution vector. SFC manages Windows system files, not application runtime redistributables.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.2 Troubleshoot Mobile OS & Apps (8 questions) ─────────────────────

  {
    id: 'q-c2-3-2-01',
    topicId: 'topic-c2-3-2',
    type: 'single_choice',
    stem: 'A user\'s Android smartphone has a social media app that crashes immediately every time they open it. Other apps work fine. What is the CORRECT troubleshooting sequence from least disruptive to most disruptive?',
    choices: ch(
      'Factory reset the phone, then reinstall the app',
      'Force stop the app, then clear the app cache, then clear app data, then uninstall and reinstall',
      'Uninstall the app immediately — reinstalling always fixes crash issues',
      'Clear all app data for all apps simultaneously to resolve any caching issue',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'App crash troubleshooting should proceed from least to most disruptive: Force stop (closes stuck processes), then clear cache (removes temporary corrupted data without losing user data), then clear data (resets app to factory state — warns user first as this deletes app data like saved progress), then uninstall and reinstall (resolves corrupted installation files). Starting with a factory reset is excessive and destroys all user data.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-2-02',
    topicId: 'topic-c2-3-2',
    type: 'single_choice',
    stem: 'A customer calls and says their Android phone "suddenly started talking" and now every tap requires two taps to open anything, and the phone reads the name of everything she touches out loud. What accessibility feature was most likely accidentally enabled?',
    choices: ch(
      'Magnification (Zoom) was enabled via triple-tap',
      'TalkBack was enabled, which is a screen reader that reads UI elements aloud and changes the interaction model to tap-to-select and double-tap-to-activate',
      'Switch Control was enabled via the accessibility shortcut',
      'High Contrast mode was turned on, which alters how the phone reads color values',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'TalkBack is Android\'s built-in screen reader for visually impaired users. When enabled, it reads the name of every UI element aloud and changes the touch interaction model: a single tap selects the item (and the phone reads it), and a double-tap activates it. Users often describe it as "the phone is broken" or "everything needs to be tapped twice." It is commonly activated accidentally via a volume key shortcut. To disable: Settings > Accessibility > TalkBack > Off (use two-finger swipe to navigate with TalkBack on).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-2-03',
    topicId: 'topic-c2-3-2',
    type: 'single_choice',
    stem: 'An iOS user attempts to update to the latest iOS version and receives an error that the update cannot be installed. The iPhone has 2 GB of free storage, 15% battery, and is connected to cellular data. Which of these factors is causing the update failure?',
    choices: ch(
      'The 2 GB of free storage — iOS requires at least 5 GB free for updates',
      'The 15% battery — iOS requires at least 50% battery charge or the device must be plugged in',
      'The cellular data connection — major iOS updates require Wi-Fi',
      'Both the battery level and cellular connection are preventing the update',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'iOS update failures are often caused by multiple unmet prerequisites simultaneously. iOS requires at minimum 50% battery (or the device plugged in) to prevent an interrupted update from bricking the device. Major iOS updates also require a Wi-Fi connection — they cannot be installed over cellular data due to their size and reliability requirements. Both conditions must be met: charge the device to 50%+ and connect to Wi-Fi before the update will proceed.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-2-04',
    topicId: 'topic-c2-3-2',
    type: 'single_choice',
    stem: 'A user\'s smartphone battery drains from 100% to 20% in under 3 hours, which is significantly worse than before. The phone has not been physically damaged. What is the BEST first diagnostic step?',
    choices: ch(
      'Replace the battery immediately — reduced battery life always indicates hardware failure',
      'Perform a factory reset to restore battery performance',
      'Review battery usage statistics in Settings to identify which app is consuming excessive power in the background',
      'Enable airplane mode permanently to reduce battery drain',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Before assuming hardware failure, check the battery usage statistics (Settings > Battery on iOS; Settings > Battery > Battery Usage on Android). This shows which apps have consumed battery over the last 24-48 hours. A recently installed app, a background sync gone wrong, or an app stuck in a crash-restart loop will show as a disproportionate consumer. Identifying and fixing the software culprit is the correct first step — battery replacement is only appropriate after confirming the battery has degraded.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-2-05',
    topicId: 'topic-c2-3-2',
    type: 'single_choice',
    stem: 'A user\'s work email stopped syncing on their Android phone after they changed their email password on their laptop. Other apps on the phone work fine. What is the MOST likely cause?',
    choices: ch(
      'The mail app has a bug that requires reinstalling after any password change',
      'The phone\'s mail app still has the old password cached and needs to be updated with the new credentials',
      'The Android OS needs to be updated before it can sync with the new password',
      'The Exchange server rejected the phone because its certificate has changed',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'When an email password is changed on another device or via the web, mobile devices that still store the old password will fail to authenticate and sync will stop. The fix is to go to the mail account settings on the phone and update the stored password. This is a very common sync troubleshooting scenario: sync that worked previously and stopped after a password change is almost always a stale credentials issue, not an app bug or OS issue.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-2-06',
    topicId: 'topic-c2-3-2',
    type: 'single_choice',
    stem: 'A user\'s phone is extremely slow, crashes frequently, and has no free storage space. What is the correct sequence of initial steps to resolve this?',
    choices: ch(
      'Immediately perform a factory reset to restore performance',
      'Identify the largest storage consumers in Settings > Storage, delete unused apps and media, then restart the device',
      'Install a third-party RAM cleaner app to free memory',
      'Add a microSD card — the lack of internal storage will be resolved by adding expandable storage',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Storage pressure is a primary cause of sluggish performance and app crashes on mobile devices. When storage is nearly full, the OS cannot create temporary files needed for normal operations, app updates fail, and virtual memory (swap) becomes unavailable. The correct approach is to identify what is consuming storage (Settings > Storage shows a breakdown), then free space by deleting unused apps, offloading photos to cloud storage, and clearing cached content. A factory reset is a last resort, and RAM cleaner apps have no proven benefit on modern mobile OSes.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-2-07',
    topicId: 'topic-c2-3-2',
    type: 'single_choice',
    stem: 'An iPhone displays "Cannot Connect to Server" errors for all apps, including email and browser, despite showing full Wi-Fi signal. What should a technician check FIRST?',
    choices: ch(
      'Reset all network settings on the iPhone',
      'Check if the device\'s date and time are set correctly — incorrect system time breaks HTTPS certificate validation and causes connection failures across all apps',
      'Remove the phone from MDM enrollment and re-enroll',
      'Forget the Wi-Fi network and reconnect',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'An incorrect device clock is a commonly overlooked cause of widespread connection failures across multiple apps. HTTPS connections require TLS certificate validation, which includes checking that the current time falls within the certificate\'s validity period. If the device clock is significantly wrong (e.g., due to settings corruption), certificate validation fails for every HTTPS connection — making it appear that no apps can reach the internet, even with a working Wi-Fi connection. Setting date and time to automatic resolves this instantly.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-2-08',
    topicId: 'topic-c2-3-2',
    type: 'single_choice',
    stem: 'On an iPhone, what is the difference between clearing app cache and clearing app data? Which option is available on iOS for most apps?',
    choices: ch(
      'Both options are available on iOS; cache clears temporary files and data clears user settings',
      'iOS exposes per-app cache clearing but not data clearing — data clearing requires using iTunes',
      'iOS does not expose a per-app cache clear in Settings — reinstalling the app achieves the same result as clearing cache and data',
      'iOS has a "Clear All Caches" button in Settings > General that clears all apps at once',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Unlike Android (which has explicit "Clear Cache" and "Clear Data" buttons per app in Settings > Apps), iOS does not expose these controls individually in the Settings interface. If an iOS app needs its cache cleared, the equivalent action is to offload or uninstall and reinstall the app. "Offload App" in iOS Settings removes the app binary but keeps documents and data; reinstalling restores a clean installation.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.3 Troubleshoot Mobile Security (8 questions) ──────────────────────

  {
    id: 'q-c2-3-3-01',
    topicId: 'topic-c2-3-3',
    type: 'single_choice',
    stem: 'A user notices their monthly cellular data usage has jumped from 3 GB to over 12 GB with no change in their browsing habits. They did not install any new apps. What is the MOST likely security-related cause?',
    choices: ch(
      'A recent carrier software update increased data usage tracking accuracy',
      'A video streaming app began autoplaying content in higher quality',
      'Spyware or malware on the device may be exfiltrating data in the background, especially with spikes in overnight data usage',
      'The iCloud or Google Photos backup began uploading higher-resolution photos',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Unexpected high cellular data usage — especially background data spikes when the device should be idle, such as overnight — is a behavioral indicator of spyware or malware. Legitimate apps are generally predictable in their data consumption. The investigation should include reviewing per-app data usage in Settings to identify any app with disproportionate consumption, looking for apps that were not user-installed, and running a security scan. If an unknown app is consuming data, uninstall it immediately.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-3-02',
    topicId: 'topic-c2-3-3',
    type: 'single_choice',
    stem: 'A user\'s browser on their Android phone shows a full-screen pop-up saying "CRITICAL ALERT FROM GOOGLE: Your device has been compromised. Tap OK to clean now." The user cannot navigate away from the page. What should they do?',
    choices: ch(
      'Tap OK immediately — Google security alerts are legitimate and ignoring them could result in data loss',
      'Force close the browser app using the Recent Apps button, then clear the browser\'s history and website data',
      'Factory reset the device — a full-screen alert from Google means the OS is compromised',
      'Tap Cancel to dismiss the alert and check for system updates',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'This is scareware — a social engineering attack delivered through a malicious or compromised website. Legitimate security alerts from Google appear as system notifications, not browser pop-ups. The browser has no ability to scan the device for malware. The correct response is to force close the browser (not tap any button inside the pop-up, as fake "Cancel" buttons can redirect to malicious sites), then clear browser history and website data to prevent the page from reopening. No factory reset is needed.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-3-03',
    topicId: 'topic-c2-3-3',
    type: 'single_choice',
    stem: 'A user is notified by HaveIBeenPwned.com that their email address and password appeared in a recent data breach. What is the IMMEDIATE response the technician should advise?',
    choices: ch(
      'Change the password on that specific site only, then monitor for suspicious activity',
      'Change the breached password on that site, change it on any other site where the same password was reused, and enable MFA on all affected accounts',
      'Wait for the affected company to notify users officially before taking action',
      'Delete the email account and create a new one to prevent further exposure',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Password reuse is the critical amplifier of credential breaches — attackers use breached credentials in automated "credential stuffing" attacks against hundreds of sites. The correct response is: (1) immediately change the compromised password on the affected site, (2) change it on every other site where the same password was used, (3) enable Multi-Factor Authentication on all affected and related accounts. Simply changing it on one site while leaving the same password on other sites leaves those accounts vulnerable.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-3-04',
    topicId: 'topic-c2-3-3',
    type: 'single_choice',
    stem: 'A user\'s Google account shows login activity from an IP address in another country. The user did not authorize this access. After the user regains account access, what action should they take to prevent the attacker from regaining access through OAuth-authorized apps?',
    choices: ch(
      'Change their Google account password and that is sufficient to revoke all access',
      'Enable Google\'s "Enhanced Safe Browsing" feature',
      'Review and revoke all connected third-party apps and OAuth authorizations, then review email forwarding rules for unauthorized forwarding addresses',
      'Contact Google support to freeze the account for 30 days',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Attackers who gain account access commonly add OAuth-authorized applications to maintain persistent access — even after a password change, OAuth tokens for connected apps remain valid. The complete response requires: (1) regain access, (2) change password, (3) enable MFA, (4) review and revoke all connected/authorized third-party apps in account settings, (5) check email forwarding rules for unauthorized rules that forward copies of email to the attacker. Changing the password alone does not revoke existing OAuth tokens.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-3-05',
    topicId: 'topic-c2-3-3',
    type: 'single_choice',
    stem: 'A user\'s mobile carrier bill shows $47 in premium SMS charges for services they did not subscribe to. The user\'s Android phone had "Install unknown apps" enabled for several months. What is the MOST likely cause?',
    choices: ch(
      'The carrier made a billing error — premium SMS charges cannot originate from apps',
      'A sideloaded app containing malware silently sent text messages to premium-rate numbers, generating per-message charges',
      'The user\'s account was used by a family member who subscribed to a premium SMS service',
      'A recent Android update incorrectly enabled premium SMS subscriptions',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Premium SMS fraud occurs when malware silently sends text messages to premium-rate numbers, which generate charges billed to the carrier account. This was more prevalent before tighter Play Store controls and is still a risk with sideloaded apps — APKs installed from outside the Play Store that had no security review. The "Install unknown apps" setting being enabled is a key indicator. The investigation should check the carrier bill details, identify the premium SMS service, dispute the charges, and audit installed apps for anything unrecognized.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-3-06',
    topicId: 'topic-c2-3-3',
    type: 'single_choice',
    stem: 'A user reviews their Android app permissions and notices their weather app has been granted "Location (Always)" and "Microphone" permissions. What action should the technician advise?',
    choices: ch(
      'These permissions are standard for weather apps — no action needed',
      'Location (Always) could be appropriate for weather, but microphone access is a red flag for a weather app and should be revoked; consider uninstalling the app',
      'Revoke only the microphone permission and grant "Location (While in use)" instead of "Always"',
      'Both permissions are excessive for a weather app and should be revoked; consider replacing the app with one that requests only necessary permissions',
      'd'
    ),
    correctAnswer: ca('d'),
    explanation: 'Applying the principle of least privilege to apps: a weather app has no legitimate need for microphone access (it should only need location to show local weather). "Location (Always)" — meaning it can track location in the background even when not in use — is also excessive for weather; "While in use" is sufficient. Both permissions should be revoked. The app requesting excessive permissions suggests it may be collecting data beyond its stated function. Using a replacement app with minimal permissions is the best long-term solution.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-3-07',
    topicId: 'topic-c2-3-3',
    type: 'single_choice',
    stem: 'A corporate MDM-enrolled iPhone shows as "Non-compliant" in the Intune console because it is running iOS 15.6 and the policy requires iOS 16.0 or later. The user\'s corporate email access is blocked. What is the correct resolution?',
    choices: ch(
      'Contact Microsoft to request a compliance exception for this device',
      'Remove the device from MDM enrollment to restore email access',
      'Update the iPhone to iOS 16.0 or later to bring the device into compliance, restoring email access',
      'Disable the minimum OS version policy in Intune as it is too restrictive',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'MDM compliance policies exist to ensure all enrolled devices meet security baselines. When a device is non-compliant, the MDM restricts access to corporate resources as a security control. The correct resolution is to bring the device into compliance — in this case, update the iOS version to meet the minimum requirement. Removing MDM enrollment removes all corporate security controls and is not an acceptable workaround. Disabling the policy defeats the purpose of the minimum OS version requirement.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-3-08',
    topicId: 'topic-c2-3-3',
    type: 'single_choice',
    stem: 'A user on an untrusted public Wi-Fi network visits a website they use daily and receives a certificate warning: "Your connection is not private — the certificate is issued for a different domain." What is the MOST concerning explanation for this error in this context?',
    choices: ch(
      'The website\'s domain recently changed and the certificate has not been updated yet',
      'The user\'s phone date is set incorrectly, causing certificate validation to fail',
      'A man-in-the-middle (MITM) attack may be intercepting traffic on the public Wi-Fi and presenting a fraudulent certificate',
      'The captive portal for the public Wi-Fi is redirecting all traffic before authentication',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'On a trusted network, a hostname mismatch could indicate a server misconfiguration. However, on an untrusted public Wi-Fi network, this type of certificate error is a significant red flag for a man-in-the-middle attack. An attacker on the same Wi-Fi can intercept unencrypted traffic and attempt to intercept HTTPS traffic by presenting their own certificate — which will fail hostname validation. The user should disconnect from the Wi-Fi immediately and use cellular data or a VPN. Captive portals typically only redirect HTTP traffic before authentication, not HTTPS traffic.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 3.4 Troubleshoot PC Security Issues (8 questions) ───────────────────

  {
    id: 'q-c2-3-4-01',
    topicId: 'topic-c2-3-4',
    type: 'single_choice',
    stem: 'A user\'s PC is running very slowly, the CPU is at 90-100% utilization by an unknown process, and the computer generates a lot of heat. The user recently downloaded what appeared to be a free video editing program from an unofficial website. What type of malware is MOST likely responsible?',
    choices: ch(
      'Ransomware — the unknown process is encrypting files',
      'Adware — the process is generating advertisements in the background',
      'Cryptominer — the malware is using the PC\'s CPU to mine cryptocurrency for the attacker',
      'A rootkit — the process is hiding system files from the user',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'High CPU utilization (90-100%) from an unknown background process, accompanied by excessive heat, after installing software from an unofficial source are the classic symptoms of a cryptominer. Cryptominers use the victim\'s CPU (or GPU) to mine cryptocurrency — all profit goes to the attacker. This is a common payload for "free" cracked software downloads. Ransomware would show encrypted files and a ransom note; adware shows popup advertisements; rootkits focus on stealth rather than CPU consumption.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-4-02',
    topicId: 'topic-c2-3-4',
    type: 'single_choice',
    stem: 'A user\'s workstation has Windows Defender disabled and cannot be re-enabled. The user also cannot install Malwarebytes — the installer runs but immediately closes without installing. What type of malware is MOST likely present?',
    choices: ch(
      'Adware — adware programs disable security tools to prevent removal of popup software',
      'A rootkit or advanced trojan that specifically disables and blocks security software to maintain persistence',
      'Ransomware — ransomware disables security tools before encrypting files',
      'A browser hijacker — hijackers block security software to prevent detection',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'The inability to re-enable Windows Defender and the blocking of security software installation are strong indicators of a rootkit or an advanced trojan. These malware types specifically target security software — they disable antivirus, prevent installation of removal tools, and sometimes block access to antivirus vendor websites. This is because remaining undetected and persistent is their primary goal. The correct response is to boot into Safe Mode (which may prevent malware from loading) or use a bootable rescue disk that runs outside the infected OS.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-4-03',
    topicId: 'topic-c2-3-4',
    type: 'single_choice',
    stem: 'A user reports that their browser is constantly redirecting searches to an unfamiliar search engine and new tabs open to an advertising site. Windows Defender shows no threats. What is the BEST approach to resolve this?',
    choices: ch(
      'Reinstall Windows — browser-level threats cannot be removed without an OS reinstall',
      'Run Windows Defender in full scan mode again — the previous scan missed the threat',
      'Remove unknown browser extensions, use the browser\'s built-in reset function, and run a scan with Malwarebytes to detect PUPs',
      'Change the default browser to a different one — the malware only affects the current browser',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Browser redirect malware typically exists as a browser extension or as a Potentially Unwanted Program (PUP) that modifies browser settings. Windows Defender may not detect PUPs by default. The correct approach is: (1) manually review and remove unknown browser extensions, (2) use the browser\'s built-in "Reset settings" function to restore homepage, search engine, and default settings, (3) run Malwarebytes (which has better PUP detection than Defender), and (4) check Task Scheduler and startup items for persistence mechanisms.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-4-04',
    topicId: 'topic-c2-3-4',
    type: 'single_choice',
    stem: 'A user\'s PC has been confirmed to be infected with a rootkit. The technician attempts to run removal tools but the infection keeps returning after each reboot. What is the correct course of action?',
    choices: ch(
      'Continue running additional removal tools — enough scans will eventually eradicate the rootkit',
      'Boot into Safe Mode and run the removal tools from there',
      'Perform a full OS reinstall (nuke and pave) — rootkits modify kernel-level components and cannot be reliably removed by cleaning tools',
      'Run sfc /scannow and DISM to restore the corrupted kernel files and remove the rootkit',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'Rootkits operate at the kernel level — they modify the OS itself, hide their presence from scanning tools, and can survive removal attempts. When a rootkit is confirmed and persists after multiple removal attempts, the correct answer on the A+ exam is OS reinstall ("nuke and pave"). The OS cannot be trusted to verify its own integrity when a rootkit is present. SFC and DISM operate within the OS and cannot reliably remove kernel-level rootkit components. Safe Mode helps in some cases but not against all rootkits.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-4-05',
    topicId: 'topic-c2-3-4',
    type: 'single_choice',
    stem: 'A user finds that all their Word documents, photos, and spreadsheets have been renamed with a .locked extension and a note has appeared on the desktop saying their files have been encrypted and demanding payment in cryptocurrency. What type of malware is this, and what is the correct first response?',
    choices: ch(
      'Adware — pay the demanded amount to have the ads removed',
      'Ransomware — immediately disconnect the infected machine from the network to prevent spreading to shared network drives, then restore files from a clean offline backup',
      'A worm — run antivirus to remove the worm and the files will be automatically restored',
      'Spyware — change all account passwords from another device and then run a removal tool',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'Encrypted files with a ransom note are the definitive indicators of ransomware. The correct immediate response is to disconnect the machine from the network (unplug ethernet, disable Wi-Fi) to prevent the ransomware from spreading to network shares and other connected machines. Do NOT pay the ransom — there is no guarantee of receiving a working decryption key. The proper resolution is restoration from a clean, offline, pre-infection backup. Cloud-synced backups may be compromised if they synced the encrypted files.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-4-06',
    topicId: 'topic-c2-3-4',
    type: 'single_choice',
    stem: 'A technician is investigating a potentially compromised workstation. Which Windows tool and Event IDs should be reviewed to detect unauthorized successful logons and newly created user accounts?',
    choices: ch(
      'Task Manager — filter for processes with elevated privileges',
      'Event Viewer > Windows Logs > Security — filter for Event ID 4624 (successful logon), 4625 (failed logon), and 4720 (user account created)',
      'Resource Monitor — review network connections for unauthorized destinations',
      'Device Manager — check for recently installed unknown devices',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'The Windows Security event log (Event Viewer > Windows Logs > Security) records authentication events. Event ID 4624 is a successful logon; 4625 is a failed logon; 4720 is a new user account creation; 4728 is a member added to a security-enabled group. An investigation for unauthorized access should filter for these IDs, looking for logons at unusual times (e.g., 3 AM), logons from unfamiliar IP addresses, new account creation, or accounts being added to administrator groups.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-4-07',
    topicId: 'topic-c2-3-4',
    type: 'single_choice',
    stem: 'A user reports that multiple HTTPS websites are suddenly showing certificate errors, including sites they visit daily that have always worked. The system clock shows the date is January 1, 2000. What is the MOST likely cause and resolution?',
    choices: ch(
      'The user\'s internet connection is being intercepted by a MITM attack — disconnect immediately',
      'A Windows Update corrupted the certificate store — run certmgr.msc to restore it',
      'The CMOS battery has failed, causing the system clock to reset to a default date; correcting the date/time will resolve the certificate errors',
      'The antivirus software is performing SSL inspection and introduced certificate errors',
      'c'
    ),
    correctAnswer: ca('c'),
    explanation: 'TLS certificate validation checks that the current date falls within the certificate\'s validity period (between "Not Before" and "Not After" dates). If the system clock resets to year 2000 (the typical default when a CMOS battery dies), every modern certificate appears to be "not yet valid" or "in the future," causing widespread certificate failures across all HTTPS sites. Correcting the system clock to the actual date immediately resolves all the certificate errors. A dead CMOS battery should then be replaced to prevent the issue from recurring.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-3-4-08',
    topicId: 'topic-c2-3-4',
    type: 'single_choice',
    stem: 'During a malware removal procedure, a technician removes all detected threats, reboots the PC, and the malware reappears the next day. Which persistence mechanism did the technician MOST likely fail to check?',
    choices: ch(
      'The malware is stored in the browser cache and reinstalls itself each time the browser opens',
      'A scheduled task or startup folder entry is re-downloading and executing the malware payload after each reboot',
      'The malware is stored in the Windows component store and sfc is restoring it on reboot',
      'The antivirus quarantine folder is releasing the malware automatically on reboot',
      'b'
    ),
    correctAnswer: ca('b'),
    explanation: 'When malware returns after removal and reboot, a persistence mechanism was missed. Common persistence mechanisms include: scheduled tasks (Task Scheduler — taskschd.msc), startup folder entries (shell:startup and shell:common startup), registry run keys (HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run), and browser extensions. The malware\'s persistence component re-downloads or re-executes the payload on each boot. A complete removal must check and clean all of these locations, not just run a scan that removes the active malware files.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

]
