// questions-batch14a.ts
// Core 2 Domain 2 — Security Part 1
// Topics: c2-2-1 (Security Measures), c2-2-2 (Windows Security Settings), c2-2-3 (Wireless Security)
// 126 questions across 3 topics (Part 1 of 2)

const NOW = new Date().toISOString()

type Choice = { id: string; text: string; isCorrect: boolean }

function ch(a: string, b: string, c: string, d: string, correct: 'a' | 'b' | 'c' | 'd'): string {
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: correct === 'a' },
    { id: 'b', text: b, isCorrect: correct === 'b' },
    { id: 'c', text: c, isCorrect: correct === 'c' },
    { id: 'd', text: d, isCorrect: correct === 'd' },
  ] as Choice[])
}

function chMulti(a: string, b: string, c: string, d: string, correct: Array<'a' | 'b' | 'c' | 'd'>): string {
  const ids = new Set(correct)
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: ids.has('a') },
    { id: 'b', text: b, isCorrect: ids.has('b') },
    { id: 'c', text: c, isCorrect: ids.has('c') },
    { id: 'd', text: d, isCorrect: ids.has('d') },
  ] as Choice[])
}

const ca = (id: 'a' | 'b' | 'c' | 'd') => JSON.stringify(id)
const cam = (...ids: Array<'a' | 'b' | 'c' | 'd'>) => JSON.stringify(ids)

export const BATCH14A_QUESTIONS = [
  // ── topic-c2-2-1: Security Measures — Physical and Logical (09–50) ──

  // --- easy (13) ---
  {
    id: 'q-c2-2-1-09',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which physical security control prevents tailgating into a secure area?',
    choices: ch('Badge reader', 'Mantrap / access control vestibule', 'Security camera', 'Motion sensor', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A mantrap (also called an access control vestibule) uses two locked doors where the first must close before the second opens, preventing unauthorized persons from following an authorized user. A badge reader authenticates but does not physically prevent tailgating. Cameras and motion sensors are detective controls, not preventive.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-10',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'What is the primary purpose of a cable lock on a laptop?',
    choices: ch('Prevent data theft via USB ports', 'Physically tether the laptop to a desk or fixture', 'Encrypt the hard drive contents', 'Lock the keyboard to prevent unauthorized typing', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A cable lock physically secures a laptop to a desk, table, or other fixture using a steel cable attached to the Kensington-style lock slot. It does not encrypt data, block USB ports, or lock the keyboard.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-11',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which security principle states that users should only have the minimum access necessary to perform their job functions?',
    choices: ch('Separation of duties', 'Principle of least privilege', 'Need-to-know basis', 'Mandatory access control', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The principle of least privilege ensures users are granted only the permissions required for their specific duties and nothing more. Separation of duties splits tasks among multiple people. Need-to-know limits information access. Mandatory access control is a system-enforced classification model.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-12',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A user is required to enter both a password and a fingerprint to log in. What type of authentication is this?',
    choices: ch('Single-factor authentication', 'Multifactor authentication', 'Single sign-on', 'Mutual authentication', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Multifactor authentication (MFA) requires two or more factors from different categories: something you know (password) and something you are (fingerprint). Single-factor uses only one category. SSO allows one login for multiple applications. Mutual authentication verifies both parties.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-13',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'What does the acronym AAA stand for in network security?',
    choices: ch('Authentication, Authorization, Accounting', 'Access, Administration, Auditing', 'Authentication, Access, Auditing', 'Authorization, Access, Accounting', 'a'),
    correctAnswer: ca('a'),
    explanation: 'AAA stands for Authentication (verifying identity), Authorization (granting permissions), and Accounting (tracking activity). This framework is fundamental to network access control and is commonly implemented via RADIUS or TACACS+ protocols.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-14',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which physical security measure helps prevent shoulder surfing?',
    choices: ch('Cable lock', 'Privacy screen / screen filter', 'Security camera', 'Badge reader', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A privacy screen (screen filter) narrows the viewing angle of a display so only the person directly in front can read it, preventing shoulder surfing. Cable locks prevent physical theft. Cameras are detective. Badge readers control entry.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-15',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'What is the purpose of an Acceptable Use Policy (AUP)?',
    choices: ch('Define how employees may use company IT resources', 'Specify network IP address ranges', 'Configure firewall rules for the organization', 'List approved hardware vendors', 'a'),
    correctAnswer: ca('a'),
    explanation: 'An Acceptable Use Policy (AUP) defines the rules and guidelines for how employees are permitted to use company IT resources, including computers, networks, and internet access. It does not configure technical settings or specify hardware vendors.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-16',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which type of door lock uses a numeric keypad for entry?',
    choices: ch('Deadbolt', 'Cipher lock', 'Biometric lock', 'Magnetic lock', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A cipher lock (also called a combination lock or keypad lock) requires a numeric code to be entered on a keypad to unlock the door. A deadbolt is a mechanical lock using a key. A biometric lock uses physical characteristics. A magnetic lock uses electromagnets.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-17',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A company requires employees to remove all papers and removable media from their desks at the end of each day. What is this policy called?',
    choices: ch('Data retention policy', 'Clean desk policy', 'Acceptable use policy', 'Incident response policy', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A clean desk policy requires employees to clear sensitive materials from their desks when not in use, reducing the risk of unauthorized disclosure. Data retention policies govern how long data is stored. AUP governs IT resource use. Incident response covers breach procedures.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-18',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which authentication technology allows a user to log in once and gain access to multiple applications without re-entering credentials?',
    choices: ch('Multifactor authentication', 'RADIUS', 'Single sign-on (SSO)', 'LDAP', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Single sign-on (SSO) lets users authenticate once and then access multiple applications or services without re-entering credentials. MFA adds extra verification factors. RADIUS is an AAA protocol. LDAP is a directory service protocol used for lookups.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-19',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'What is the purpose of a visitor badge in a secured facility?',
    choices: ch('Grant permanent building access', 'Visually identify non-employees in the building', 'Replace the need for an escort', 'Provide Wi-Fi access credentials', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Visitor badges provide a visual indicator that a person is not a regular employee, making it easier for staff and security to identify outsiders. They do not grant permanent access, replace escorts where required, or provide network credentials.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-20',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'What is the primary purpose of CCTV cameras in a data center?',
    choices: ch('Prevent physical intrusion', 'Monitor and record activity for review', 'Authenticate personnel entering the facility', 'Block tailgating at entry points', 'b'),
    correctAnswer: ca('b'),
    explanation: 'CCTV cameras are a detective control used to monitor and record activity for later review. They do not physically prevent intrusion (that requires barriers or locks), authenticate personnel (that requires badge readers or biometrics), or block tailgating (that requires mantraps).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-21',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A Non-Disclosure Agreement (NDA) is designed to protect which of the following?',
    choices: ch('Physical hardware from theft', 'Confidential information from unauthorized disclosure', 'Networks from intrusion', 'User accounts from lockout', 'b'),
    correctAnswer: ca('b'),
    explanation: 'An NDA is a legal agreement that protects confidential information by prohibiting the signer from disclosing it to unauthorized parties. It is a legal control, not a technical control for hardware, networks, or account management.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // --- medium (21) ---
  {
    id: 'q-c2-2-1-22',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A technician needs to track which employees accessed a server room over the weekend. Which physical security tool would provide this information?',
    choices: ch('Motion sensor', 'Sign-in log / access log', 'Cable lock', 'Privacy screen', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A sign-in log or electronic access log records who entered a secured area and when, providing an audit trail. Motion sensors detect movement but do not identify individuals. Cable locks secure equipment. Privacy screens limit screen visibility.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-23',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which security principle requires that no single person can complete a critical transaction alone?',
    choices: ch('Principle of least privilege', 'Need-to-know', 'Separation of duties', 'Mandatory access control', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Separation of duties divides critical tasks among multiple people so that no single individual has enough access to commit fraud or cause significant damage alone. Least privilege limits access scope. Need-to-know limits information access. MAC enforces classifications.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-24',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A company configures its Active Directory to lock user accounts after five failed login attempts. Which account policy setting controls this behavior?',
    choices: ch('Password complexity', 'Account lockout threshold', 'Password expiration', 'Minimum password age', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The account lockout threshold specifies the number of failed login attempts before an account is locked. Password complexity defines character requirements. Password expiration sets maximum password age. Minimum password age prevents rapid password cycling.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-25',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which protocol is commonly used to provide centralized AAA services for network access?',
    choices: ch('SNMP', 'RADIUS', 'DNS', 'DHCP', 'b'),
    correctAnswer: ca('b'),
    explanation: 'RADIUS (Remote Authentication Dial-In User Service) provides centralized Authentication, Authorization, and Accounting for network access. SNMP manages network devices. DNS resolves domain names. DHCP assigns IP addresses.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-26',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'An organization classifies its data into four tiers: public, internal, confidential, and restricted. Which classification level typically contains trade secrets or legally protected data?',
    choices: ch('Public', 'Internal', 'Confidential', 'Restricted', 'd'),
    correctAnswer: ca('d'),
    explanation: 'Restricted is the highest classification tier and typically contains trade secrets, legally protected data, or information whose exposure would cause severe damage. Confidential is sensitive but below restricted. Internal is for employees only. Public is freely available.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-27',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A company uses RFID tags on all laptop assets. What is the primary purpose of this practice?',
    choices: ch('Encrypt data stored on the laptops', 'Track and locate physical assets', 'Prevent unauthorized software installation', 'Authenticate users to the device', 'b'),
    correctAnswer: ca('b'),
    explanation: 'RFID (Radio Frequency Identification) tags are used for asset tracking, allowing organizations to locate and inventory physical equipment. They do not provide encryption, software control, or user authentication.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-28',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which directory service protocol is used by Active Directory to query and modify objects in the directory?',
    choices: ch('LDAP', 'RADIUS', 'Kerberos', 'TACACS+', 'a'),
    correctAnswer: ca('a'),
    explanation: 'LDAP (Lightweight Directory Access Protocol) is the protocol used to query and modify directory service objects in Active Directory. RADIUS and TACACS+ are AAA protocols. Kerberos is the authentication protocol used by AD, but LDAP handles the directory queries.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-29',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A technician discovers a hard drive containing sensitive client data that must be disposed of. Which method ensures the data is irrecoverable?',
    choices: ch('Quick format the drive', 'Delete all files and empty the Recycle Bin', 'Degauss or physically shred the drive', 'Move files to an encrypted folder', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Degaussing (for magnetic drives) or physical shredding renders data irrecoverable. A quick format only removes file system metadata. Deleting files and emptying the Recycle Bin leaves data recoverable with forensic tools. Moving to an encrypted folder does not destroy the data.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-30',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which MDM (Mobile Device Management) feature allows an administrator to erase all data from a lost corporate smartphone?',
    choices: ch('Geofencing', 'Remote wipe', 'Application whitelisting', 'Screen lock enforcement', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Remote wipe allows an MDM administrator to erase all data on a lost or stolen device to prevent data breaches. Geofencing defines geographic boundaries for alerts. Application whitelisting controls allowed apps. Screen lock enforcement requires a passcode.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-31',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'An employee finds a USB flash drive in the parking lot and plugs it into their work computer. Which type of social engineering attack does this represent?',
    choices: ch('Phishing', 'Baiting', 'Tailgating', 'Shoulder surfing', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Baiting involves leaving malicious media (such as a USB drive) in a location where a target will find it and plug it in out of curiosity. Phishing uses fraudulent emails. Tailgating is following someone through a secured door. Shoulder surfing is observing someone\'s screen.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-32',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which security concept ensures that evidence collected during an incident investigation maintains a documented chain showing who handled it and when?',
    choices: ch('Data retention policy', 'Chain of custody', 'Incident response plan', 'Change management', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Chain of custody is the documented record of who collected, handled, and stored evidence and when. It is essential for legal proceedings. Data retention governs how long data is stored. Incident response is the overall process. Change management tracks system changes.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-33',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'An ACL on a network resource grants the Sales group Read access and the Marketing group Read/Write access. A user belongs to both groups. What effective permission does the user have?',
    choices: ch('Read only', 'Read/Write', 'No access', 'Full Control', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When a user belongs to multiple groups, the effective permissions are the cumulative (most permissive) combination of all group permissions, unless an explicit Deny overrides them. Since Marketing grants Read/Write, the user receives Read/Write.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-34',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A biometric lock that scans a fingerprint to unlock a door is an example of which authentication factor?',
    choices: ch('Something you know', 'Something you have', 'Something you are', 'Somewhere you are', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A fingerprint is a biometric characteristic categorized as "something you are." Something you know includes passwords and PINs. Something you have includes tokens and smart cards. Somewhere you are refers to location-based authentication.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-35',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A security policy requires passwords to be at least 12 characters and include uppercase, lowercase, numbers, and symbols. Which policy setting enforces this?',
    choices: ch('Account lockout policy', 'Password complexity requirements', 'Password history', 'Audit policy', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Password complexity requirements define the minimum length and character types that passwords must include. Account lockout locks accounts after failed attempts. Password history prevents password reuse. Audit policy tracks security events.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-36',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which security measure would BEST protect sensitive documents locked in a server room from fire damage?',
    choices: ch('Security guard', 'Locking cabinet / fireproof safe', 'Motion sensor', 'Visitor badge system', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A fireproof safe or locking cabinet provides physical protection against fire and unauthorized access. Security guards, motion sensors, and visitor badges help control access but offer no fire protection for stored materials.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-37',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'A data retention policy states that financial records must be kept for seven years. What happens to those records after the retention period expires?',
    choices: ch('They are automatically encrypted', 'They are moved to a public share', 'They are securely destroyed per the disposal policy', 'They are transferred to the CEO', 'c'),
    correctAnswer: ca('c'),
    explanation: 'After the retention period expires, records should be securely destroyed in accordance with the organization\'s disposal policy to prevent unauthorized access. Records are not simply encrypted, made public, or transferred to individuals.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-38',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which of the following describes a change management process in the context of security?',
    choices: ch('Resetting user passwords on a regular schedule', 'Documenting, approving, and testing changes before implementing them in production', 'Installing all available patches without testing', 'Granting temporary admin access to all users', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Change management requires that all changes to systems and configurations be documented, approved by stakeholders, and tested before deployment to prevent unintended security vulnerabilities. Password resets, untested patches, and blanket admin access are not change management.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-39',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'Which of the following is the FIRST step in the incident response process?',
    choices: ch('Containment', 'Identification', 'Eradication', 'Recovery', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The incident response process begins with Identification — detecting and confirming that a security incident has occurred. Containment, eradication, and recovery follow in sequence after the incident has been identified and characterized.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-40',
    topicId: 'topic-c2-2-1',
    type: 'single_choice' as const,
    stem: 'GPS tracking on company-issued laptops is an example of which type of asset tracking?',
    choices: ch('RFID tracking', 'Location-based tracking', 'Cable lock security', 'Biometric tracking', 'b'),
    correctAnswer: ca('b'),
    explanation: 'GPS (Global Positioning System) tracking uses satellite signals to determine the real-time geographic location of a device. RFID uses radio frequency tags for proximity detection. Cable locks physically tether devices. Biometric tracking identifies individuals, not devices.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-41',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are deterrent physical security controls rather than detective controls? (Select TWO)',
    choices: chMulti('Perimeter lighting', 'CCTV camera system', 'Security guard presence', 'Motion-sensor recording system', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Perimeter lighting and a visible security guard presence are deterrent controls that discourage malicious activity before it occurs. CCTV cameras and motion-sensor recording systems are detective controls that capture evidence of events for later review rather than discouraging them.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-42',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are capabilities typically provided by a Mobile Device Management (MDM) solution? (Select TWO)',
    choices: chMulti('Enforce device encryption and PIN requirements', 'Replace the corporate firewall', 'Push application installs and updates to managed devices', 'Provide physical security for the data center', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'MDM solutions enforce security policies (encryption, PIN requirements) and manage applications (push installs, updates, and removals) on enrolled devices. MDM does not replace network firewalls or provide physical security for data centers — those are separate infrastructure concerns.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // --- hard (8) ---
  {
    id: 'q-c2-2-1-43',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are examples of multifactor authentication? (Select TWO)',
    choices: chMulti('Password + security token code', 'Username + password', 'Fingerprint + iris scan', 'PIN + smart card', ['a', 'd']),
    correctAnswer: cam('a', 'd'),
    explanation: 'MFA requires two or more factors from different categories: something you know, something you have, and something you are. Password + security token = know + have. PIN + smart card = know + have. Username + password is single-factor (two "something you know" items). Fingerprint + iris scan is also single-factor (two biometrics = two "something you are" items).',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-44',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'A company is developing its incident response plan. Which TWO phases come AFTER containment in the standard incident response lifecycle? (Select TWO)',
    choices: chMulti('Identification', 'Eradication', 'Preparation', 'Recovery', ['b', 'd']),
    correctAnswer: cam('b', 'd'),
    explanation: 'The standard incident response lifecycle is: Preparation, Identification, Containment, Eradication, Recovery, and Lessons Learned. Eradication (removing the threat) and Recovery (restoring systems) both follow Containment. Identification and Preparation both precede Containment.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-45',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following physical security controls are considered preventive rather than detective? (Select TWO)',
    choices: chMulti('Mantrap / access control vestibule', 'CCTV security camera', 'Deadbolt door lock', 'Motion-activated alarm', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Preventive controls stop unauthorized actions before they occur. A mantrap physically prevents tailgating, and a deadbolt prevents door entry. CCTV cameras record events (detective) and motion-activated alarms alert after detection (detective). Prevention and detection serve different roles in a layered security model.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-46',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are functions of a RADIUS server in an enterprise network? (Select TWO)',
    choices: chMulti('Authenticate users attempting to access the network', 'Assign IP addresses to client devices', 'Track user session data for billing and auditing', 'Resolve domain names to IP addresses', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'RADIUS provides Authentication (verifying user credentials) and Accounting (tracking session data for billing and auditing) as part of the AAA framework. IP address assignment is handled by DHCP. Domain name resolution is performed by DNS.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-47',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following MDM features help protect data when a corporate device is lost? (Select TWO)',
    choices: chMulti('Remote wipe', 'Application whitelisting', 'Full device encryption', 'Push notification service', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Remote wipe erases all data on a lost device, and full device encryption ensures data is unreadable without the decryption key even if the device is physically accessed. Application whitelisting controls which apps are installed. Push notifications deliver messages but do not protect data.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-48',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'A security auditor is reviewing logical access controls. Which TWO of the following are logical (not physical) security controls? (Select TWO)',
    choices: chMulti('Access Control Lists on a file server', 'Security guard at the front desk', 'Account lockout policy after failed login attempts', 'CCTV camera in the server room', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'ACLs on a file server and account lockout policies are logical (software-based) security controls that govern digital access. A security guard and CCTV camera are physical security controls that protect the facility itself.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-49',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are considered administrative security controls rather than technical controls? (Select TWO)',
    choices: chMulti('Acceptable Use Policy (AUP)', 'Firewall rule configuration', 'Security awareness training', 'Intrusion detection system', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Administrative (managerial) controls include policies, procedures, and training — such as an AUP and security awareness training. Firewall rules and intrusion detection systems are technical controls implemented through hardware or software.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-50',
    topicId: 'topic-c2-2-1',
    type: 'multiple_choice' as const,
    stem: 'During digital forensics, which TWO actions are critical for maintaining chain of custody of a seized hard drive? (Select TWO)',
    choices: chMulti('Create a forensic hash of the drive before analysis', 'Immediately format the drive to prevent tampering', 'Document every person who handles the evidence and when', 'Clone the drive to the suspect\'s personal computer', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Creating a forensic hash (e.g., MD5 or SHA-256) provides an integrity baseline to prove the evidence was not altered. Documenting every handler maintains the chain of custody. Formatting the drive would destroy evidence. Cloning to a suspect\'s computer would compromise the investigation.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ── topic-c2-2-2: Windows Security Settings (09–50) ──

  // --- easy (13) ---
  {
    id: 'q-c2-2-2-09',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which built-in Windows feature provides real-time antivirus and antimalware protection?',
    choices: ch('Windows Firewall', 'Windows Defender Antivirus', 'BitLocker', 'User Account Control', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Windows Defender Antivirus (part of Windows Security) provides built-in real-time protection against viruses and malware. Windows Firewall controls network traffic. BitLocker encrypts drives. UAC manages elevation of privileges.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-10',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'What is the purpose of User Account Control (UAC) in Windows?',
    choices: ch('Encrypt files on the hard drive', 'Prompt users before allowing elevated (administrative) actions', 'Scan for malware in real time', 'Manage wireless network connections', 'b'),
    correctAnswer: ca('b'),
    explanation: 'UAC prompts users for confirmation or administrator credentials before allowing actions that require elevated privileges, preventing unauthorized system changes. File encryption is handled by BitLocker/EFS. Malware scanning is handled by Windows Defender. Wireless management is in Network Settings.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-11',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which Windows tool is used to manage local user accounts and group memberships?',
    choices: ch('Device Manager', 'Local Users and Groups (lusrmgr.msc)', 'Disk Management', 'Task Manager', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Local Users and Groups (lusrmgr.msc) allows administrators to create, modify, and delete local user accounts and manage group memberships. Device Manager handles hardware. Disk Management handles storage. Task Manager monitors processes.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-12',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which Windows feature encrypts an entire drive and requires a TPM chip or USB startup key?',
    choices: ch('EFS', 'BitLocker', 'Windows Defender', 'Controlled Folder Access', 'b'),
    correctAnswer: ca('b'),
    explanation: 'BitLocker encrypts entire volumes and typically uses a TPM (Trusted Platform Module) chip to store encryption keys, though a USB startup key can be used as an alternative. EFS encrypts individual files. Windows Defender is antivirus. Controlled Folder Access prevents ransomware.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-13',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Windows Firewall operates with three network profiles. Which profile is applied when connected to a corporate domain?',
    choices: ch('Public', 'Private', 'Domain', 'Enterprise', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Windows Firewall uses three profiles: Domain (when connected to an Active Directory domain), Private (trusted home or work networks), and Public (untrusted networks like coffee shops). There is no Enterprise profile.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-14',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which MMC snap-in is used to configure local password policies and account lockout policies on a Windows workstation?',
    choices: ch('gpedit.msc', 'secpol.msc', 'devmgmt.msc', 'compmgmt.msc', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Local Security Policy (secpol.msc) is used to configure security settings including password policies, account lockout policies, and audit policies. gpedit.msc is the Group Policy Editor (broader scope). devmgmt.msc is Device Manager. compmgmt.msc is Computer Management.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-15',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'What does Windows Hello allow users to do?',
    choices: ch('Encrypt entire drives', 'Sign in using biometrics such as fingerprint or facial recognition', 'Remotely wipe a lost device', 'Monitor network traffic', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Windows Hello provides biometric authentication, allowing users to sign in with a fingerprint, facial recognition, or a PIN as an alternative to traditional passwords. Drive encryption is BitLocker. Remote wipe is an MDM function. Network monitoring uses other tools.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-16',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which Windows feature stores saved passwords for websites and network resources?',
    choices: ch('Credential Manager', 'Windows Defender', 'BitLocker', 'Local Security Policy', 'a'),
    correctAnswer: ca('a'),
    explanation: 'Credential Manager stores saved usernames and passwords for websites (Web Credentials) and network resources (Windows Credentials). Windows Defender is antivirus. BitLocker encrypts drives. Local Security Policy manages security settings.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-17',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which NTFS permission allows a user to read, write, and modify files but NOT change permissions or take ownership?',
    choices: ch('Read', 'Full Control', 'Modify', 'Write', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The Modify permission includes Read, Write, Execute, and Delete, but does not include the ability to change permissions or take ownership — those are reserved for Full Control. Read is view-only. Write allows creating files but not modifying existing ones.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-18',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which Windows feature protects designated folders from unauthorized changes by untrusted applications, helping to guard against ransomware?',
    choices: ch('Windows Sandbox', 'Controlled Folder Access', 'Exploit Protection', 'Smart App Control', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Controlled Folder Access monitors applications and only allows trusted apps to make changes to files in protected folders, providing ransomware protection. Windows Sandbox runs untrusted apps in isolation. Exploit Protection mitigates exploit techniques. Smart App Control blocks untrusted apps.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-19',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'When both NTFS and share permissions are applied to a shared folder, which rule determines the user\'s effective access?',
    choices: ch('NTFS permissions always override share permissions', 'Share permissions always override NTFS permissions', 'The most restrictive combination of both applies', 'The least restrictive combination of both applies', 'c'),
    correctAnswer: ca('c'),
    explanation: 'When accessing a resource over the network, both NTFS and share permissions are evaluated, and the most restrictive effective permission from the combination applies. Neither set of permissions automatically overrides the other.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-20',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which Windows tool allows running applications in a lightweight, isolated desktop environment that is discarded when closed?',
    choices: ch('Windows Sandbox', 'Hyper-V', 'Windows Defender', 'BitLocker', 'a'),
    correctAnswer: ca('a'),
    explanation: 'Windows Sandbox provides a temporary, isolated desktop environment for safely running untrusted applications. Everything in the sandbox is discarded when it is closed. Hyper-V is a full virtualization platform. Windows Defender is antivirus. BitLocker encrypts drives.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-21',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Tamper Protection in Windows Security prevents which of the following?',
    choices: ch('Users from changing the desktop wallpaper', 'Malware or users from disabling Windows Defender features', 'Unauthorized USB devices from connecting', 'Applications from accessing the internet', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Tamper Protection prevents malware and unauthorized users from disabling or modifying Windows Defender Antivirus settings, real-time protection, and other security features. It does not control wallpaper, USB devices, or internet access.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // --- medium (21) ---
  {
    id: 'q-c2-2-2-22',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'A user on a Public Wi-Fi network notices that Windows Firewall is blocking file sharing. Which firewall profile is responsible?',
    choices: ch('Domain profile', 'Private profile', 'Public profile', 'Home profile', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The Public firewall profile is the most restrictive and blocks file sharing, network discovery, and other services by default to protect the system on untrusted networks. The Domain profile applies on corporate networks. The Private profile is for trusted home/work networks. There is no Home profile.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-23',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'A Windows administrator needs to require all users to change their passwords every 90 days. Which policy setting should be configured in secpol.msc?',
    choices: ch('Minimum password length', 'Maximum password age', 'Enforce password history', 'Account lockout duration', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Maximum password age defines how many days a password can be used before the system requires the user to change it. Minimum password length sets how many characters are required. Enforce password history prevents reusing old passwords. Account lockout duration sets how long a locked account stays locked.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-24',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'EFS (Encrypting File System) encrypts files on which type of file system?',
    choices: ch('FAT32', 'exFAT', 'NTFS', 'ReFS', 'c'),
    correctAnswer: ca('c'),
    explanation: 'EFS is a feature of NTFS that allows per-user, per-file encryption. It is not available on FAT32 or exFAT. While ReFS is a Microsoft file system, EFS is specifically tied to NTFS volumes.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-25',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'An administrator wants to set UAC to the highest level so that all elevation requests require explicit user approval, even for Windows settings changes. Which UAC level should be selected?',
    choices: ch('Never notify', 'Notify me only when apps try to make changes (do not dim desktop)', 'Notify me only when apps try to make changes (default)', 'Always notify', 'd'),
    correctAnswer: ca('d'),
    explanation: 'The "Always notify" level is the most restrictive UAC setting, prompting the user for approval whenever any program or Windows setting change requires elevation. The default level only notifies for app changes. "Never notify" disables UAC prompts entirely.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-26',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'A security administrator reviews Event Viewer and sees multiple Event ID 4625 entries for a user account. What does this event indicate?',
    choices: ch('Successful logon', 'Failed logon attempt', 'Account was locked out', 'Special privileges were assigned', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Event ID 4625 in the Windows Security log indicates a failed logon attempt. Event ID 4624 indicates a successful logon. Account lockout is Event ID 4740. Special privileges assigned at logon is Event ID 4672.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-27',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which Group Policy setting prevents users from installing software from unknown sources on a Windows Pro workstation?',
    choices: ch('Software Restriction Policies / AppLocker', 'Windows Update settings', 'Power Management settings', 'Folder Redirection', 'a'),
    correctAnswer: ca('a'),
    explanation: 'Software Restriction Policies and AppLocker (available in Windows Pro/Enterprise via gpedit.msc) can block the installation and execution of unauthorized software. Windows Update manages patches. Power Management controls energy settings. Folder Redirection moves user folders to network locations.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-28',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'A user encrypts a file with EFS on their Windows workstation. Another administrator logs in to the same machine and tries to open the file. What happens?',
    choices: ch('The file opens normally because administrators have full access', 'The administrator receives an Access Denied error', 'The file is automatically decrypted for any administrator', 'The file is moved to the Recycle Bin', 'b'),
    correctAnswer: ca('b'),
    explanation: 'EFS encryption is per-user — only the user who encrypted the file (and designated recovery agents) can decrypt it. Other administrators cannot access the file without the user\'s private key or a recovery agent certificate, and will receive an Access Denied error.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-29',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which Windows Security log Event ID indicates a successful user logon?',
    choices: ch('4624', '4625', '4648', '4672', 'a'),
    correctAnswer: ca('a'),
    explanation: 'Event ID 4624 indicates a successful account logon. Event ID 4625 is a failed logon. Event ID 4648 is a logon using explicit credentials. Event ID 4672 indicates special privileges were assigned to a new logon.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-30',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'A user\'s BitLocker-protected laptop fails to boot and requests a recovery key. Where can this recovery key typically be found?',
    choices: ch('In the Windows Registry', 'In the user\'s Microsoft account, Active Directory, or a printed copy', 'In the EFS certificate store', 'In the Windows Firewall settings', 'b'),
    correctAnswer: ca('b'),
    explanation: 'BitLocker recovery keys can be saved to a Microsoft account, backed up to Active Directory/Azure AD, saved to a USB drive, or printed during initial setup. They are not stored in the Registry, EFS certificate store, or Firewall settings.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-31',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'NTFS permission inheritance means that files in a subfolder will, by default, receive permissions from which source?',
    choices: ch('The root of the C: drive only', 'The immediate parent folder', 'The user who created the file', 'The local Administrators group', 'b'),
    correctAnswer: ca('b'),
    explanation: 'NTFS permission inheritance flows from parent folders to child objects by default. Files and subfolders inherit the permissions of their immediate parent folder. Inheritance can be blocked or overridden at any level. Permissions are not automatically derived from the drive root, file creator, or Administrators group.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-32',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which audit policy setting in Local Security Policy must be enabled to log both successful and failed logon events to the Security log?',
    choices: ch('Audit account management', 'Audit logon events', 'Audit object access', 'Audit policy change', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Audit logon events must be enabled (for both Success and Failure) to record logon attempts in the Security log. Audit account management tracks user/group changes. Audit object access tracks file/folder access. Audit policy change tracks security policy modifications.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-33',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'A Windows firewall exception has been created to allow inbound traffic on port 3389. Which service does this exception support?',
    choices: ch('File sharing (SMB)', 'Remote Desktop Protocol (RDP)', 'DNS lookups', 'Web browsing (HTTPS)', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Port 3389 is used by Remote Desktop Protocol (RDP). SMB file sharing uses port 445. DNS uses port 53. HTTPS uses port 443. Allowing port 3389 through the firewall enables remote desktop connections to the computer.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-34',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'An administrator wants to prevent users from reusing any of their last 10 passwords. Which password policy setting should be configured?',
    choices: ch('Minimum password length', 'Maximum password age', 'Enforce password history', 'Password complexity requirements', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Enforce password history remembers a specified number of previous passwords and prevents users from reusing them. Setting it to 10 means the last 10 passwords cannot be reused. Minimum length sets character count. Maximum age sets expiration. Complexity requires character types.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-35',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which tool provides the Group Policy Editor on Windows Pro and Enterprise editions?',
    choices: ch('secpol.msc', 'gpedit.msc', 'lusrmgr.msc', 'regedit.exe', 'b'),
    correctAnswer: ca('b'),
    explanation: 'gpedit.msc opens the Local Group Policy Editor, available only on Windows Pro, Enterprise, and Education editions. secpol.msc opens Local Security Policy. lusrmgr.msc manages local users and groups. regedit.exe edits the Windows Registry directly.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-36',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'A user has Read permission on a folder via NTFS and Full Control via the share permission. When accessing the folder over the network, what is the effective permission?',
    choices: ch('Full Control', 'Read', 'Modify', 'No access', 'b'),
    correctAnswer: ca('b'),
    explanation: 'When accessing a shared folder over the network, the most restrictive combination of NTFS and share permissions applies. NTFS grants Read, share grants Full Control, and the most restrictive result is Read. NTFS permissions alone apply when accessing locally.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-37',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which Exploit Protection setting in Windows Security helps prevent buffer overflow attacks by randomizing the memory addresses used by system processes?',
    choices: ch('Data Execution Prevention (DEP)', 'Address Space Layout Randomization (ASLR)', 'Control Flow Guard (CFG)', 'Structured Exception Handling Overwrite Protection (SEHOP)', 'b'),
    correctAnswer: ca('b'),
    explanation: 'ASLR randomizes the memory locations where system executables and libraries are loaded, making buffer overflow exploits unpredictable. DEP prevents code execution from data segments. CFG validates indirect call targets. SEHOP prevents exception handler overwrite attacks.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-38',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which Windows Security log Event ID indicates that special privileges were assigned to a new logon session?',
    choices: ch('4624', '4625', '4648', '4672', 'd'),
    correctAnswer: ca('d'),
    explanation: 'Event ID 4672 is logged when special privileges (such as SeDebugPrivilege or SeBackupPrivilege) are assigned to a new logon session, typically for administrator accounts. Event 4624 is a successful logon. Event 4625 is a failed logon. Event 4648 is a logon using explicit credentials.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-39',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Smart App Control in Windows 11 blocks which type of applications?',
    choices: ch('Applications that require administrator privileges', 'Untrusted and potentially dangerous applications based on cloud intelligence', 'Applications that are older than two years', 'All applications not installed from the Microsoft Store', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Smart App Control uses cloud-based intelligence and code signing to evaluate applications and block untrusted or potentially dangerous ones. It does not simply block all non-Store apps, old apps, or apps requiring admin privileges.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-40',
    topicId: 'topic-c2-2-2',
    type: 'single_choice' as const,
    stem: 'Which User Rights Assignment setting determines which users or groups can log on through Remote Desktop Services?',
    choices: ch('Allow log on locally', 'Allow log on through Remote Desktop Services', 'Access this computer from the network', 'Log on as a service', 'b'),
    correctAnswer: ca('b'),
    explanation: 'The "Allow log on through Remote Desktop Services" user right assignment specifies which users or groups can establish an RDP session. "Allow log on locally" controls console logon. "Access this computer from the network" controls network access. "Log on as a service" allows running as a Windows service.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-41',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following Windows security tools are used to apply and standardize security configurations across multiple machines? (Select TWO)',
    choices: chMulti('Security templates (.inf files)', 'Windows Sandbox', 'Group Policy (gpedit.msc)', 'Credential Manager', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Security templates are .inf files containing predefined security settings that can be imported into machines, and Group Policy (gpedit.msc) can deploy these settings across multiple workstations in a domain. Windows Sandbox runs isolated app instances. Credential Manager stores saved passwords.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-42',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO account lockout policy settings work together to define how many failed attempts trigger a lockout and how long the lockout lasts? (Select TWO)',
    choices: chMulti('Account lockout threshold', 'Minimum password length', 'Account lockout duration', 'Enforce password history', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Account lockout threshold defines the number of failed login attempts before an account is locked, and account lockout duration defines how many minutes the account remains locked. Minimum password length and enforce password history are password policy settings, not lockout settings.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // --- hard (8) ---
  {
    id: 'q-c2-2-2-43',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following Windows features provide full-volume encryption? (Select TWO)',
    choices: chMulti('BitLocker', 'EFS', 'BitLocker To Go', 'Controlled Folder Access', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'BitLocker encrypts entire internal volumes and BitLocker To Go encrypts removable drives (USB flash drives, external HDDs). Both provide full-volume encryption. EFS encrypts individual files and folders, not entire volumes. Controlled Folder Access protects folders from unauthorized app changes but does not encrypt them.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-44',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO Event Viewer Security log Event IDs should a security analyst monitor for signs of brute-force password attacks? (Select TWO)',
    choices: chMulti('4624 — successful logon', '4625 — failed logon attempt', '4648 — logon using explicit credentials', '4672 — special privileges assigned', ['b', 'c']),
    correctAnswer: cam('b', 'c'),
    explanation: 'Event ID 4625 (failed logon) in large quantities indicates brute-force attempts. Event ID 4648 (logon using explicit credentials) can indicate credential stuffing or pass-the-hash attacks. Event 4624 (successful logon) and 4672 (special privileges) are normal operational events that alone do not indicate brute-force activity.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-45',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'A technician needs to configure the most secure local account policy. Which TWO settings should be implemented together? (Select TWO)',
    choices: chMulti('Account lockout threshold set to 5 attempts', 'Maximum password age set to 0 (passwords never expire)', 'Enforce password history set to 24 passwords remembered', 'Minimum password length set to 4 characters', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Setting an account lockout threshold (e.g., 5 attempts) prevents brute-force attacks, and enforcing password history (24 passwords) prevents password reuse. Passwords that never expire reduce security over time. A minimum length of 4 characters is far too short for security.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-46',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following statements about NTFS and share permissions are correct? (Select TWO)',
    choices: chMulti('NTFS permissions apply to both local and network access', 'Share permissions apply only when accessing a folder over the network', 'Share permissions override NTFS permissions in all cases', 'NTFS permissions have no effect on network access', ['a', 'b']),
    correctAnswer: cam('a', 'b'),
    explanation: 'NTFS permissions apply regardless of access method (local or network). Share permissions only apply to network access. When both are in effect (network access), the most restrictive combination applies — neither overrides the other. NTFS permissions absolutely affect network access.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-47',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO Windows security features help mitigate ransomware attacks? (Select TWO)',
    choices: chMulti('Controlled Folder Access', 'Windows Sandbox', 'Credential Manager', 'Tamper Protection', ['a', 'd']),
    correctAnswer: cam('a', 'd'),
    explanation: 'Controlled Folder Access prevents untrusted applications from modifying files in protected folders, directly mitigating ransomware. Tamper Protection prevents malware from disabling Windows Defender, which is critical for ransomware detection. Windows Sandbox isolates apps but does not directly protect existing files. Credential Manager stores passwords.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-48',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'An administrator needs to enable BitLocker on a Windows workstation without a TPM chip. Which TWO steps are required? (Select TWO)',
    choices: chMulti('Enable the Group Policy setting "Require additional authentication at startup"', 'Install a TPM 2.0 module from a third-party vendor', 'Configure BitLocker to use a USB startup key or password', 'Downgrade to Windows Home edition', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Without a TPM, the administrator must enable the Group Policy setting that allows BitLocker without a compatible TPM ("Require additional authentication at startup") and then configure BitLocker to use a USB startup key or startup password instead. Installing a third-party TPM is a hardware change, not a software configuration. BitLocker is not available on Home edition.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-49',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following audit policy settings would help detect unauthorized file access on a Windows file server? (Select TWO)',
    choices: chMulti('Audit object access', 'Audit logon events', 'Audit privilege use', 'Audit process tracking', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'Audit object access logs attempts to access files, folders, and registry keys, directly detecting unauthorized file access. Audit privilege use logs when special privileges are exercised, helping identify escalation. Audit logon events tracks logons but not file access specifically. Audit process tracking monitors process creation, not file access.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-50',
    topicId: 'topic-c2-2-2',
    type: 'multiple_choice' as const,
    stem: 'Which TWO differences between EFS and BitLocker are correct? (Select TWO)',
    choices: chMulti('EFS encrypts individual files while BitLocker encrypts entire volumes', 'EFS requires a TPM chip while BitLocker does not', 'BitLocker protects data at rest even if the drive is removed from the machine', 'EFS protects data if the hard drive is removed and connected to another computer', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'EFS encrypts individual files/folders on NTFS and is tied to the user account, not the hardware. BitLocker encrypts entire volumes and protects data even if the physical drive is removed — the data remains encrypted without the TPM/recovery key. EFS does not require a TPM (BitLocker optionally does). EFS-encrypted files can be read if the user\'s key is accessible on another system, but the drive itself is not encrypted.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ── topic-c2-2-3: Wireless Security (09–50) ──

  // --- easy (13) ---
  {
    id: 'q-c2-2-3-09',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which wireless security protocol is considered deprecated due to its use of the weak RC4 cipher and short initialization vectors?',
    choices: ch('WPA2', 'WPA3', 'WEP', 'WPA', 'c'),
    correctAnswer: ca('c'),
    explanation: 'WEP (Wired Equivalent Privacy) is deprecated because it uses the weak RC4 stream cipher with short 24-bit initialization vectors, making it easily crackable. WPA improved on WEP with TKIP. WPA2 uses AES/CCMP. WPA3 adds SAE and forward secrecy.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-10',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which encryption protocol does WPA2 use to provide strong wireless security?',
    choices: ch('RC4', 'TKIP', 'AES/CCMP', 'DES', 'c'),
    correctAnswer: ca('c'),
    explanation: 'WPA2 uses AES (Advanced Encryption Standard) with CCMP (Counter Mode with CBC-MAC Protocol) for strong encryption. RC4 is used by WEP. TKIP was used by WPA as a transitional improvement over WEP. DES is an outdated symmetric cipher not used in Wi-Fi.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-11',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'What does PSK stand for in the context of WPA2-Personal?',
    choices: ch('Private Secure Key', 'Pre-Shared Key', 'Public Secret Key', 'Protected Session Key', 'b'),
    correctAnswer: ca('b'),
    explanation: 'PSK stands for Pre-Shared Key, a passphrase shared among all users to authenticate to a WPA2-Personal network. It is simpler than Enterprise mode but less secure for large organizations since everyone shares the same key.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-12',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which wireless security mode uses a RADIUS server for authentication instead of a shared passphrase?',
    choices: ch('WPA2-Personal', 'WPA2-Enterprise', 'WEP Open', 'WPS', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPA2-Enterprise uses 802.1X authentication with a RADIUS server to authenticate individual users with unique credentials. WPA2-Personal uses a pre-shared key. WEP Open has no authentication. WPS is a simplified setup method, not a security mode.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-13',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which attack involves setting up a fake wireless access point that mimics a legitimate network to intercept user traffic?',
    choices: ch('War driving', 'Evil twin attack', 'Bluesnarfing', 'Disassociation attack', 'b'),
    correctAnswer: ca('b'),
    explanation: 'An evil twin attack creates a rogue access point with the same SSID as a legitimate network, tricking users into connecting to the attacker\'s AP. War driving is scanning for networks while moving. Bluesnarfing steals data via Bluetooth. Disassociation attacks disconnect clients from their AP.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-14',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Hiding the SSID of a wireless network provides which level of security?',
    choices: ch('Strong encryption-based security', 'Minimal security — SSIDs can still be discovered with network scanning tools', 'Complete invisibility from all wireless devices', 'The same security as WPA2 encryption', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Hiding the SSID only removes it from beacon frames; wireless scanning tools can still detect the network through probe requests and responses. It provides minimal security through obscurity and should never be relied upon as a primary security measure.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-15',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'WPA3 improves upon WPA2 by replacing the PSK handshake with which protocol?',
    choices: ch('TKIP', 'SAE (Simultaneous Authentication of Equals)', 'RC4', 'EAP-TLS', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPA3 uses SAE (Simultaneous Authentication of Equals), which provides stronger key exchange and forward secrecy, replacing the WPA2 four-way handshake with PSK. TKIP was used by WPA. RC4 was used by WEP. EAP-TLS is an Enterprise authentication method.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-16',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which Bluetooth attack involves sending unsolicited messages to a Bluetooth-enabled device?',
    choices: ch('Bluesnarfing', 'Bluejacking', 'Evil twin', 'War driving', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Bluejacking sends unsolicited messages (such as vCards or text) to a Bluetooth device. While annoying, it does not steal data. Bluesnarfing is the unauthorized access of data from a Bluetooth device. Evil twin involves rogue Wi-Fi APs. War driving scans for wireless networks.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-17',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'What is the primary security risk of Wi-Fi Protected Setup (WPS)?',
    choices: ch('It uses WEP encryption by default', 'The WPS PIN can be brute-forced due to its limited keyspace', 'It does not support AES encryption', 'It requires an open network with no password', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPS uses an 8-digit PIN that is validated in two halves, reducing the effective keyspace and making it vulnerable to brute-force attacks. WPS does support WPA2/AES but the PIN vulnerability compromises the security regardless of the encryption method used.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-18',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which wireless security best practice involves creating a separate network for visitors that cannot access internal corporate resources?',
    choices: ch('MAC address filtering', 'Guest network isolation', 'SSID hiding', 'WPS push-button setup', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Guest network isolation creates a separate wireless network for visitors that is logically segmented from the internal corporate network, preventing guests from accessing sensitive resources. MAC filtering restricts by hardware address. SSID hiding obscures the network name. WPS simplifies connections.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-19',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which Bluetooth attack involves unauthorized access to steal data such as contacts, calendars, and messages from a victim\'s device?',
    choices: ch('Bluejacking', 'Bluesnarfing', 'NFC skimming', 'War driving', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Bluesnarfing exploits Bluetooth vulnerabilities to steal data from a device without the owner\'s knowledge. Bluejacking only sends unsolicited messages. NFC skimming targets near-field communication. War driving scans for Wi-Fi networks.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-20',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'What does the 802.1X standard provide in a wireless enterprise environment?',
    choices: ch('Wireless frequency regulation', 'Port-based network access control and authentication', 'Automatic channel selection', 'Wireless signal amplification', 'b'),
    correctAnswer: ca('b'),
    explanation: '802.1X provides port-based network access control, requiring users to authenticate (typically via a RADIUS server) before gaining network access. It is used in WPA2/WPA3-Enterprise deployments. It does not handle frequency regulation, channel selection, or signal amplification.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-21',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which Wi-Fi standard introduced the 5 GHz frequency band with a maximum data rate of 54 Mbps?',
    choices: ch('802.11b', '802.11a', '802.11g', '802.11n', 'b'),
    correctAnswer: ca('b'),
    explanation: '802.11a operates on the 5 GHz band with a maximum rate of 54 Mbps. 802.11b uses 2.4 GHz at 11 Mbps. 802.11g uses 2.4 GHz at 54 Mbps. 802.11n (Wi-Fi 4) uses both 2.4 GHz and 5 GHz with speeds up to 600 Mbps.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // --- medium (21) ---
  {
    id: 'q-c2-2-3-22',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'A wireless administrator discovers that clients on channels 1, 6, and 11 experience no co-channel interference on the 2.4 GHz band. Why are these channels recommended?',
    choices: ch('They are the only channels available on 2.4 GHz', 'They are non-overlapping channels that do not interfere with each other', 'They provide the highest data rates', 'They are required by FCC regulation', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Channels 1, 6, and 11 are the three non-overlapping channels in the 2.4 GHz band (which has 11 channels in the US). Using these channels prevents co-channel interference between nearby access points. Other channels overlap and cause degraded performance.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-23',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which EAP type requires both the server and the client to present digital certificates for mutual authentication?',
    choices: ch('PEAP', 'EAP-TLS', 'EAP-TTLS', 'EAP-FAST', 'b'),
    correctAnswer: ca('b'),
    explanation: 'EAP-TLS requires both server and client certificates for mutual authentication, making it the most secure EAP type but also the most complex to deploy. PEAP uses a server certificate and tunnels the inner authentication. EAP-TTLS also uses a server certificate with tunneled authentication. EAP-FAST uses protected access credentials.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-24',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'A technician notices that a company\'s wireless network uses TKIP encryption. Which wireless security protocol is most likely in use?',
    choices: ch('WEP', 'WPA', 'WPA2', 'WPA3', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPA (Wi-Fi Protected Access) was designed as a transitional improvement over WEP and uses TKIP (Temporal Key Integrity Protocol). WPA2 replaced TKIP with the stronger AES/CCMP. WEP uses RC4 directly. WPA3 uses SAE with AES.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-25',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'What type of wireless attack forces clients to disconnect from their access point by sending forged deauthentication frames?',
    choices: ch('Evil twin attack', 'Disassociation attack', 'War driving', 'Bluejacking', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A disassociation (deauthentication) attack sends forged deauth frames to disconnect clients from their access point. This can be used as a precursor to an evil twin attack, forcing clients to reconnect to the attacker\'s AP. War driving passively scans for networks. Bluejacking targets Bluetooth.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-26',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'An administrator configures MAC address filtering on a wireless access point. Why is this NOT considered a strong security measure?',
    choices: ch('MAC addresses are encrypted and cannot be read', 'MAC addresses can be easily spoofed by an attacker', 'MAC filtering only works on wired networks', 'MAC filtering disables WPA2 encryption', 'b'),
    correctAnswer: ca('b'),
    explanation: 'MAC addresses are transmitted in plaintext in wireless frames and can be captured and cloned (spoofed) by an attacker using readily available tools. MAC filtering should only be used as a supplementary measure, not as a primary security control.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-27',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'A company hotel provides internet access through a web page that requires guests to accept terms before browsing. What is this technology called?',
    choices: ch('RADIUS authentication', 'Captive portal', 'WPS setup', 'MAC address filtering', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A captive portal redirects clients to a web page for authentication, terms acceptance, or payment before allowing internet access. RADIUS provides backend authentication. WPS simplifies network connections. MAC filtering restricts by hardware address.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-28',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which key security improvement does WPA3 provide over WPA2?',
    choices: ch('Use of TKIP instead of AES', 'Forward secrecy — past sessions cannot be decrypted even if the password is later compromised', 'Removal of the four-way handshake entirely', 'Support for WEP backward compatibility', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPA3 provides forward secrecy through SAE, meaning that even if the network password is later compromised, previously captured encrypted sessions cannot be decrypted. WPA3 still uses AES (not TKIP), still performs a handshake (SAE-based), and does not support WEP.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-29',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'A wireless site survey reveals areas with signal strength below -80 dBm. What is the likely result for users in these areas?',
    choices: ch('Optimal performance with maximum data rates', 'Poor connectivity with slow speeds or dropped connections', 'Automatic switch to a wired connection', 'Improved security due to lower signal leakage', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Signal strength below -80 dBm is generally too weak for reliable Wi-Fi connectivity, resulting in slow speeds, high latency, and dropped connections. Optimal performance typically requires -65 dBm or better. Weak signals do not trigger automatic wired connections or meaningfully improve security.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-30',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'What is war driving?',
    choices: ch('Physically breaking into a building to access network equipment', 'Driving around while scanning for wireless networks using a laptop and antenna', 'Sending deauthentication frames to disconnect users', 'Brute-forcing WPA2 passwords using cloud computing', 'b'),
    correctAnswer: ca('b'),
    explanation: 'War driving is the practice of driving (or walking) around with a wireless-enabled device to detect and map wireless networks, their SSIDs, encryption types, and signal strengths. It is a reconnaissance technique that can identify vulnerable networks.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-31',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'PEAP (Protected Extensible Authentication Protocol) secures the inner authentication by doing what?',
    choices: ch('Encrypting the entire wireless signal', 'Creating a TLS tunnel between the client and the RADIUS server', 'Using WEP encryption for the handshake', 'Requiring the client to present a digital certificate', 'b'),
    correctAnswer: ca('b'),
    explanation: 'PEAP creates a TLS tunnel using the server\'s certificate, and the client authenticates inside this encrypted tunnel (typically with MS-CHAPv2). Unlike EAP-TLS, PEAP does not require a client certificate. It does not encrypt the entire wireless signal or use WEP.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-32',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which 802.11 standard is also known as Wi-Fi 6 and supports OFDMA and improved performance in dense environments?',
    choices: ch('802.11ac', '802.11n', '802.11ax', '802.11g', 'c'),
    correctAnswer: ca('c'),
    explanation: '802.11ax (Wi-Fi 6) introduces OFDMA (Orthogonal Frequency Division Multiple Access), improved MU-MIMO, and better performance in dense environments. 802.11ac is Wi-Fi 5. 802.11n is Wi-Fi 4. 802.11g is an older 2.4 GHz standard.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-33',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'A technician is securing a small office wireless network. Which WPA2 mode is appropriate for a network with fewer than 20 users and no RADIUS server?',
    choices: ch('WPA2-Enterprise', 'WPA2-Personal (PSK)', 'WPA2-Open', 'WPA2-PEAP', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPA2-Personal (PSK) is appropriate for small networks without a RADIUS infrastructure, as it uses a shared passphrase for authentication. WPA2-Enterprise requires a RADIUS server. There is no "WPA2-Open" mode (Open networks have no encryption). PEAP is an EAP type used within Enterprise mode.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-34',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'NFC (Near Field Communication) operates at a maximum range of approximately how far?',
    choices: ch('10 centimeters (about 4 inches)', '10 meters (about 33 feet)', '100 meters (about 328 feet)', '1 meter (about 3.3 feet)', 'a'),
    correctAnswer: ca('a'),
    explanation: 'NFC operates at a maximum range of approximately 10 cm (4 inches), requiring very close proximity between devices. This short range provides a degree of inherent security, but NFC is still vulnerable to eavesdropping and relay attacks within that range.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-35',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which security best practice should be applied to unused wireless interfaces on a laptop?',
    choices: ch('Set them to the strongest encryption level', 'Disable them to prevent unauthorized connections', 'Configure them with MAC address filtering', 'Hide their SSID', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Unused wireless interfaces (Wi-Fi, Bluetooth, NFC) should be disabled to reduce the attack surface and prevent unauthorized connections or data leakage. Encryption, MAC filtering, and SSID hiding apply to active access points, not client interfaces.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-36',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'WEP can use either 64-bit or 128-bit key lengths. What is the actual user-configurable key length for 64-bit WEP after subtracting the initialization vector?',
    choices: ch('24 bits', '40 bits', '56 bits', '64 bits', 'b'),
    correctAnswer: ca('b'),
    explanation: 'In 64-bit WEP, the 24-bit initialization vector (IV) is prepended to the user key, so the actual user-configurable key length is only 40 bits (64 - 24 = 40). For 128-bit WEP, the user key is 104 bits (128 - 24 = 104). The short IV is a major contributor to WEP\'s weakness.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-37',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'A network administrator needs to determine optimal access point placement and identify sources of interference. Which process should be performed?',
    choices: ch('Port scan', 'Wireless site survey', 'Vulnerability assessment', 'Penetration test', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A wireless site survey maps signal strength, identifies interference sources (microwaves, neighboring APs, Bluetooth), and determines optimal AP placement for coverage and performance. Port scans identify open ports. Vulnerability assessments find security weaknesses. Penetration tests simulate attacks.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-38',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'Which advantage does WPA2-Enterprise have over WPA2-Personal for a large organization?',
    choices: ch('Simpler configuration with no server required', 'Individual user authentication with unique credentials via RADIUS', 'Higher encryption strength using TKIP', 'Faster wireless speeds', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPA2-Enterprise authenticates each user individually through a RADIUS server with unique credentials, providing accountability and the ability to revoke individual access. WPA2-Personal shares one passphrase among all users, making individual revocation impossible. Enterprise does not use TKIP or improve speeds.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-39',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'During Bluetooth pairing, a PIN or passkey exchange is used to establish a secure connection. What is the primary security concern with simple 4-digit Bluetooth PINs?',
    choices: ch('They are transmitted in plaintext', 'They have a small keyspace (only 10,000 combinations) and can be brute-forced', 'They disable encryption on the Bluetooth link', 'They are visible to all nearby devices', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A 4-digit numeric PIN has only 10,000 possible combinations (0000-9999), making it vulnerable to brute-force attacks. Modern Bluetooth versions use more secure pairing methods like Secure Simple Pairing (SSP) with Numeric Comparison or Passkey Entry to mitigate this risk.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-40',
    topicId: 'topic-c2-2-3',
    type: 'single_choice' as const,
    stem: 'EAP-TTLS (Extensible Authentication Protocol - Tunneled TLS) differs from EAP-TLS in which key way?',
    choices: ch('EAP-TTLS requires client certificates while EAP-TLS does not', 'EAP-TTLS only requires a server certificate, not a client certificate', 'EAP-TTLS does not use encryption', 'EAP-TTLS is used only with WEP networks', 'b'),
    correctAnswer: ca('b'),
    explanation: 'EAP-TTLS only requires a server-side certificate, creating a TLS tunnel within which the client authenticates using simpler methods (like passwords). EAP-TLS requires both server and client certificates. Both use strong encryption. Neither is associated with WEP.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-41',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'A rogue access point is discovered on the corporate network. Which TWO actions should the security team take FIRST? (Select TWO)',
    choices: chMulti('Disconnect the rogue AP from the network immediately', 'Upgrade all clients to WPA3', 'Identify which port or switch the rogue AP is connected to', 'Change the corporate SSID name', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'The immediate priorities are to disconnect the rogue AP to stop unauthorized access and to identify the physical port/switch connection to understand how it was introduced. Upgrading to WPA3 and changing the SSID do not address the immediate threat of an unauthorized device on the network.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-42',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are features introduced by the 802.11n (Wi-Fi 4) standard? (Select TWO)',
    choices: chMulti('Dual-band operation on both 2.4 GHz and 5 GHz', 'OFDMA (Orthogonal Frequency Division Multiple Access)', 'MIMO (Multiple Input Multiple Output) antenna technology', 'Exclusive 60 GHz band operation', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: '802.11n introduced dual-band operation (2.4 GHz and 5 GHz) and MIMO antenna technology, enabling theoretical speeds up to 600 Mbps. OFDMA was introduced by 802.11ax (Wi-Fi 6). 60 GHz operation is associated with 802.11ad (WiGig).',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // --- hard (8) ---
  {
    id: 'q-c2-2-3-43',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are vulnerabilities specific to WPS (Wi-Fi Protected Setup)? (Select TWO)',
    choices: chMulti('PIN brute-force attack due to split PIN validation', 'Weak RC4 encryption cipher', 'Physical push-button method can be exploited if an attacker has physical access', 'Lack of support for AES encryption', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'WPS is vulnerable because the 8-digit PIN is validated in two halves (reducing brute-force time to about 11,000 attempts) and the push-button method can be exploited if an attacker gains momentary physical access to the router. Weak RC4 and lack of AES are WEP issues, not WPS issues.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-44',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'Which TWO wireless security measures should be implemented together to provide the strongest protection for a corporate network? (Select TWO)',
    choices: chMulti('WPA2-Enterprise with 802.1X/RADIUS', 'MAC address filtering as the primary control', 'EAP-TLS with mutual certificate authentication', 'SSID hiding as the primary security mechanism', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'WPA2-Enterprise with 802.1X/RADIUS provides per-user authentication, and EAP-TLS with mutual certificates provides the strongest available EAP authentication. MAC filtering and SSID hiding provide minimal security and should never be used as primary controls.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-45',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'Which TWO statements about WPA3 are correct? (Select TWO)',
    choices: chMulti('WPA3 uses SAE to provide forward secrecy', 'WPA3 replaces AES with TKIP', 'WPA3 protects against offline dictionary attacks on the handshake', 'WPA3 requires WPS to be enabled', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'WPA3 uses SAE (Simultaneous Authentication of Equals) which provides forward secrecy — past sessions remain protected even if the password is later compromised. SAE also protects against offline dictionary attacks because the handshake does not expose enough information for offline cracking. WPA3 continues to use AES, not TKIP, and does not require WPS.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-46',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following Bluetooth security threats involve unauthorized data access? (Select TWO)',
    choices: chMulti('Bluejacking', 'Bluesnarfing', 'NFC relay attack', 'Bluetooth impersonation attack (BIAS)', ['b', 'd']),
    correctAnswer: cam('b', 'd'),
    explanation: 'Bluesnarfing steals data (contacts, messages, files) from a Bluetooth device without permission. BIAS (Bluetooth Impersonation Attack) exploits the authentication process to impersonate a previously paired device, potentially gaining unauthorized access. Bluejacking only sends unsolicited messages without accessing data. NFC relay attacks target NFC, not Bluetooth.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-47',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are differences between TKIP and CCMP/AES? (Select TWO)',
    choices: chMulti('TKIP was designed as a firmware upgrade for WEP hardware', 'CCMP/AES requires dedicated hardware support', 'TKIP provides stronger encryption than CCMP/AES', 'CCMP/AES is the mandatory encryption for WPA2', ['a', 'd']),
    correctAnswer: cam('a', 'd'),
    explanation: 'TKIP was designed to work with existing WEP hardware through firmware/driver updates, providing a stopgap improvement. CCMP/AES is the mandatory encryption standard for WPA2 and provides significantly stronger security than TKIP. TKIP is weaker than CCMP/AES. While AES can benefit from hardware acceleration, many devices implement it in software.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-48',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'A security team suspects an evil twin attack is targeting the corporate Wi-Fi. Which TWO indicators would confirm this? (Select TWO)',
    choices: chMulti('Two access points broadcasting the same SSID with different BSSIDs', 'Clients experiencing frequent disconnections followed by automatic reconnection', 'The corporate SSID is hidden from beacon frames', 'All clients are using WPA3 encryption', ['a', 'b']),
    correctAnswer: cam('a', 'b'),
    explanation: 'An evil twin attack involves a rogue AP broadcasting the same SSID with a different BSSID (MAC address). Frequent disconnections (possibly from deauth attacks) followed by reconnection to the rogue AP is a common attack pattern. A hidden SSID or WPA3 usage would not confirm an evil twin.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-49',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'Which TWO security benefits does WPA2-Enterprise provide that WPA2-Personal does not? (Select TWO)',
    choices: chMulti('Individual user authentication and accountability', 'Ability to revoke access for a single user without changing everyone\'s credentials', 'Stronger AES encryption', 'Support for the 5 GHz frequency band', ['a', 'b']),
    correctAnswer: cam('a', 'b'),
    explanation: 'WPA2-Enterprise authenticates individual users via RADIUS, providing accountability and the ability to revoke individual access without affecting other users. WPA2-Personal uses a shared passphrase — if one user leaves, the passphrase must be changed for everyone. Both modes use the same AES encryption and support the same frequency bands.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-50',
    topicId: 'topic-c2-2-3',
    type: 'multiple_choice' as const,
    stem: 'Which TWO of the following are recommended actions when performing a wireless site survey for a new office deployment? (Select TWO)',
    choices: chMulti('Map signal strength throughout the space to identify dead zones', 'Set all access points to the same channel for consistency', 'Identify sources of interference such as microwaves and neighboring APs', 'Disable all encryption during the survey for easier testing', ['a', 'c']),
    correctAnswer: cam('a', 'c'),
    explanation: 'A proper wireless site survey involves mapping signal strength to find dead zones and coverage gaps, and identifying interference sources (microwaves, Bluetooth, neighboring APs on overlapping channels). Using the same channel on all APs would cause severe co-channel interference. Encryption should remain enabled during surveys.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // topics c2-2-4 through c2-2-6 will be added by a second subagent
]
