// 48 verified practice questions for CompTIA A+ 220-1202 Core 2 Domain 2: Security
// Covers objectives 2.1–2.6 with accurate, exam-representative content

const NOW = new Date().toISOString()

type Choice = { id: string; text: string; isCorrect: boolean }

function ch(a: string, b: string, c: string, d: string, correct: 'a' | 'b' | 'c' | 'd'): string {
  return JSON.stringify([
    { id: 'a', text: a, isCorrect: correct === 'a' },
    { id: 'b', text: b, isCorrect: correct === 'b' },
    { id: 'c', text: c, isCorrect: correct === 'c' },
    { id: 'd', text: d, isCorrect: correct === 'd' },
  ] as Choice[])
}

const ca = (id: 'a' | 'b' | 'c' | 'd') => JSON.stringify(id)

export const BATCH5_QUESTIONS = [

  // ─── 2.1 Security Measures (8 questions) ──────────────────────────────────

  {
    id: 'q-c2-2-1-01',
    topicId: 'topic-c2-2-1',
    type: 'single_choice',
    stem: 'A data center wants to prevent tailgating at its main entrance. Which physical security control is specifically designed to stop an unauthorized person from following an authorized employee through a secure door?',
    choices: ch('CCTV camera', 'Cable lock', 'Mantrap', 'RFID badge reader', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A mantrap is a two-door airlock where the first door must fully close before the second door opens. This prevents tailgating because only one person can pass through at a time. CCTV records but does not prevent entry. Cable locks secure equipment. RFID badge readers authenticate users but do not physically prevent a second person from slipping through an open door.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-02',
    topicId: 'topic-c2-2-1',
    type: 'single_choice',
    stem: 'An employee uses a fingerprint scanner to unlock their workstation. Which MFA factor category does a fingerprint represent?',
    choices: ch('Something you know', 'Something you have', 'Something you are', 'Somewhere you are', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A fingerprint is a biometric trait and falls under the "something you are" factor category. "Something you know" includes passwords and PINs. "Something you have" includes hardware tokens, smart cards, and authenticator apps. "Somewhere you are" refers to location-based factors like GPS or IP address. True MFA requires factors from at least two different categories.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-03',
    topicId: 'topic-c2-2-1',
    type: 'single_choice',
    stem: 'A security policy states that each user account should only have permissions required to perform their specific job function. Which security principle does this describe?',
    choices: ch('Zero Trust', 'Defense in depth', 'Principle of least privilege', 'Mandatory Access Control', 'c'),
    correctAnswer: ca('c'),
    explanation: 'The principle of least privilege states that users and systems should be granted only the minimum permissions required to perform their job — nothing more. Excess privilege amplifies the damage of a compromised account. Zero Trust is a broader model (never trust, always verify). Defense in depth layers multiple controls. MAC is an access control model based on classification labels.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-04',
    topicId: 'topic-c2-2-1',
    type: 'single_choice',
    stem: 'Which access control model grants access based on a user\'s job function rather than the individual user identity or data classification labels?',
    choices: ch('DAC (Discretionary Access Control)', 'MAC (Mandatory Access Control)', 'RBAC (Role-Based Access Control)', 'Zero Trust', 'c'),
    correctAnswer: ca('c'),
    explanation: 'RBAC (Role-Based Access Control) grants access based on the user\'s assigned job role — e.g., all members of the "HR" role get access to the HRIS system. DAC lets the resource owner decide who has access. MAC uses classification labels (Top Secret, Secret, etc.) set by policy. Zero Trust is a security model, not an access control model per se.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-05',
    topicId: 'topic-c2-2-1',
    type: 'single_choice',
    stem: 'A user works at a coffee shop and is concerned that someone nearby might read their laptop screen. Which physical security control directly mitigates this threat?',
    choices: ch('Cable lock', 'Privacy screen', 'CCTV camera', 'RFID badge', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A privacy screen is a polarized overlay that makes the display unreadable from side angles, directly countering shoulder surfing. A cable lock prevents the laptop from being physically stolen. CCTV records events. An RFID badge controls access to facilities, not screen visibility.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-06',
    topicId: 'topic-c2-2-1',
    type: 'single_choice',
    stem: 'Which security model operates on the principle of "never trust, always verify," treating every access request as potentially hostile regardless of whether it originates inside or outside the corporate network?',
    choices: ch('Defense in depth', 'Zero Trust', 'Mandatory Access Control', 'Network segmentation', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Zero Trust rejects the traditional assumption that internal network traffic is inherently trustworthy. Every request must be explicitly verified — identity, device health, location, and context — before access is granted. It applies least privilege access and assumes breach at all times. This model is especially relevant with cloud resources and remote work where there is no traditional perimeter.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-07',
    topicId: 'topic-c2-2-1',
    type: 'single_choice',
    stem: 'A technician sets up a new wireless router for a small business. The router still has its factory default username and password configured. What is the most important first security step?',
    choices: ch('Enable WPA2 encryption', 'Change the default credentials', 'Disable the SSID broadcast', 'Enable MAC address filtering', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Default credentials for network devices are publicly documented by vendors and are the first thing attackers try. Changing default credentials must be done before deploying any network device. While enabling WPA2 is also important, leaving default credentials in place allows anyone to log into the router\'s admin interface regardless of wireless security settings.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-1-08',
    topicId: 'topic-c2-2-1',
    type: 'single_choice',
    stem: 'An organization requires employees to use both a password and a one-time code from an authenticator app to log into the corporate VPN. The password is forgotten but the authenticator app is still on the user\'s phone. Which factor category does the authenticator app represent?',
    choices: ch('Something you know', 'Something you have', 'Something you are', 'Somewhere you are', 'b'),
    correctAnswer: ca('b'),
    explanation: 'An authenticator app (such as Google Authenticator or Microsoft Authenticator) that generates one-time codes is a "something you have" factor — possession of the physical phone is required. The password is "something you know." Together they constitute true MFA because they come from two different factor categories.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.2 Windows Security Settings (8 questions) ─────────────────────────

  {
    id: 'q-c2-2-2-01',
    topicId: 'topic-c2-2-2',
    type: 'single_choice',
    stem: 'A user tries to install a new application on Windows and a prompt appears asking for administrator approval. Which Windows security feature is generating this prompt?',
    choices: ch('Windows Defender Antivirus', 'BitLocker', 'User Account Control (UAC)', 'Windows Hello', 'c'),
    correctAnswer: ca('c'),
    explanation: 'User Account Control (UAC) generates the elevation prompt when any action requires administrator privileges, such as installing software or modifying system settings. It is designed to prevent unauthorized or accidental changes to the OS. Windows Defender scans for malware. BitLocker encrypts drives. Windows Hello handles biometric and PIN authentication.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-02',
    topicId: 'topic-c2-2-2',
    type: 'single_choice',
    stem: 'BitLocker full-disk encryption is enabled on a laptop. A technician needs to move the drive to another machine to recover files. What will happen when the drive is placed in the new machine?',
    choices: ch('Files are accessible immediately because BitLocker only locks the boot drive', 'BitLocker prompts for the 48-digit recovery key because the TPM from the original machine is absent', 'BitLocker disables automatically when the drive is moved', 'Files are accessible after entering the Windows login password', 'b'),
    correctAnswer: ca('b'),
    explanation: 'BitLocker uses the TPM chip on the motherboard to protect the encryption key. When the drive is moved to a different machine, the TPM is absent and BitLocker requires the 48-digit recovery key to unlock the drive. This is precisely why BitLocker protects against data theft — removing the drive from a stolen laptop does not bypass encryption without the recovery key.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-03',
    topicId: 'topic-c2-2-2',
    type: 'single_choice',
    stem: 'A technician attempts to enable BitLocker on a Windows laptop but the option is grayed out. The laptop is running Windows Home edition. What is the most likely reason BitLocker is unavailable?',
    choices: ch('The hard drive must be formatted as FAT32 to support BitLocker', 'BitLocker requires a minimum of 8 GB RAM', 'BitLocker is not available on Windows Home edition', 'The TPM chip must be version 2.0 or higher for BitLocker', 'c'),
    correctAnswer: ca('c'),
    explanation: 'BitLocker is only available on Windows Pro, Enterprise, and Education editions — it is not included in Windows Home. This is a commonly tested distinction on the A+ exam. If a customer on Windows Home needs full-disk encryption, they must upgrade their Windows edition or use a third-party solution like VeraCrypt.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-04',
    topicId: 'topic-c2-2-2',
    type: 'single_choice',
    stem: 'A user belongs to two groups. Group A has Allow Read on a folder. Group B has Deny Read on the same folder. What is the user\'s effective NTFS permission for Read?',
    choices: ch('Allow — Allow takes precedence over Deny', 'Deny — Deny overrides Allow', 'No permission — conflicting settings cancel out', 'It depends on which group was applied first', 'b'),
    correctAnswer: ca('b'),
    explanation: 'In NTFS permissions, Deny always overrides Allow. Even if a user receives Allow Read from one group membership, a Deny Read from any other group or direct assignment will take precedence. This is why Deny should be used sparingly — it can produce unexpected results when users belong to multiple groups.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-05',
    topicId: 'topic-c2-2-2',
    type: 'single_choice',
    stem: 'A Windows technician needs to configure the minimum password length and account lockout threshold on a standalone (non-domain) Windows Pro machine. Which tool is used?',
    choices: ch('Task Manager', 'Device Manager', 'Local Security Policy (secpol.msc)', 'Registry Editor (regedit)', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Local Security Policy (secpol.msc) provides a centralized interface for configuring Account Policies (password policy and account lockout policy) on standalone Windows Pro and higher machines. It is available only on Pro, Enterprise, and Education editions. Task Manager monitors processes; Device Manager manages hardware drivers; Registry Editor requires manual key edits without a policy-guided UI.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-06',
    topicId: 'topic-c2-2-2',
    type: 'single_choice',
    stem: 'Which Windows Defender scan type boots the computer into a clean environment before Windows fully loads, making it effective against malware that hides from the running OS?',
    choices: ch('Quick scan', 'Full scan', 'Custom scan', 'Windows Defender Offline scan', 'd'),
    correctAnswer: ca('d'),
    explanation: 'Windows Defender Offline scan reboots the computer into a minimal, clean environment and performs the scan before the main OS loads. This prevents active malware from hiding itself from the scanner. It is particularly useful when malware is actively blocking normal scans or when a rootkit is suspected. Quick and full scans run inside the live OS and can be evaded by active malware.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-07',
    topicId: 'topic-c2-2-2',
    type: 'single_choice',
    stem: 'EFS (Encrypting File System) is enabled on a user\'s files. The user\'s Windows profile is accidentally deleted. What happens to the EFS-encrypted files?',
    choices: ch('The files are automatically decrypted when the profile is deleted', 'Another administrator can open the files using their own credentials', 'The files may become permanently inaccessible if the user\'s certificate was not backed up', 'The files are protected by the TPM and can be recovered at any time', 'c'),
    correctAnswer: ca('c'),
    explanation: 'EFS encryption is tied to the user\'s certificate stored in their profile. If the profile is deleted and the certificate was not backed up (or a Data Recovery Agent was not configured), the encrypted files may be permanently inaccessible. This is a critical limitation of EFS compared to BitLocker. Administrators cannot decrypt EFS files using their own credentials without being a designated recovery agent.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-2-08',
    topicId: 'topic-c2-2-2',
    type: 'single_choice',
    stem: 'A user sets up Windows Hello with a PIN on their work laptop. A coworker learns the PIN. Can the coworker use the PIN to log into the user\'s Microsoft account from a different device?',
    choices: ch('Yes — the PIN is the same as the account password', 'No — a Windows Hello PIN is device-specific and only works on the device it was created on', 'Yes — the PIN syncs across all devices linked to the Microsoft account', 'No — PINs require biometric verification on every device', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A Windows Hello PIN is device-specific. It is stored locally on the device and protected by the TPM when available. It only functions on the specific device it was configured on. Even if someone knows your PIN, they cannot use it to access your account from any other machine. This makes a PIN actually more secure than a password in many respects — a stolen password works everywhere, a stolen PIN does not.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.3 Wireless Security (8 questions) ──────────────────────────────────

  {
    id: 'q-c2-2-3-01',
    topicId: 'topic-c2-2-3',
    type: 'single_choice',
    stem: 'Which wireless security protocol should NEVER be used because it can be cracked in under 10 minutes using freely available tools?',
    choices: ch('WPA2', 'WPA3', 'WEP', 'WPA', 'c'),
    correctAnswer: ca('c'),
    explanation: 'WEP (Wired Equivalent Privacy), introduced in 1999, is completely broken. It uses RC4 with a flawed IV implementation that allows statistical cryptanalysis — an attacker passively capturing enough traffic can crack the key in under 10 minutes. There is no scenario where WEP should be deployed. Devices that only support WEP must be replaced.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-02',
    topicId: 'topic-c2-2-3',
    type: 'single_choice',
    stem: 'WPA2 uses which encryption protocol as its default cipher suite?',
    choices: ch('RC4 with TKIP', 'AES with CCMP', 'DES with CBC', '3DES with ECB', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPA2 uses AES-CCMP (Advanced Encryption Standard — Counter Mode with Cipher Block Chaining Message Authentication Code Protocol) as its encryption cipher. AES is a block cipher used by the US government for classified data. WPA (original) used TKIP which is RC4-based. This AES/CCMP pairing is the key fact to memorize for WPA2 on the exam.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-03',
    topicId: 'topic-c2-2-3',
    type: 'single_choice',
    stem: 'A corporate network requires every wireless user to authenticate with their individual domain credentials rather than a shared passphrase. Which wireless configuration supports this?',
    choices: ch('WPA2-Personal (PSK)', 'WEP with 128-bit key', 'WPA2-Enterprise with 802.1X/RADIUS', 'WPA3-Personal with SAE', 'c'),
    correctAnswer: ca('c'),
    explanation: 'WPA2-Enterprise uses 802.1X with a RADIUS server to authenticate each user with individual credentials (username/password or certificates). This allows per-user authentication, enables account revocation without changing the network passphrase, and provides stronger identity assurance. WPA2-Personal (PSK) uses a single shared passphrase for all users — appropriate for home networks but not for enterprise environments.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-04',
    topicId: 'topic-c2-2-3',
    type: 'single_choice',
    stem: 'WPA3-Personal replaces the pre-shared key (PSK) handshake with which protocol that provides forward secrecy and resistance to offline dictionary attacks?',
    choices: ch('TKIP (Temporal Key Integrity Protocol)', 'SAE (Simultaneous Authentication of Equals)', 'EAP-TLS (Extensible Authentication Protocol - Transport Layer Security)', 'RADIUS (Remote Authentication Dial-In User Service)', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPA3-Personal uses SAE (Simultaneous Authentication of Equals), also called Dragonfly. Unlike WPA2-PSK where an attacker who captures the handshake can run it through an offline password cracker, SAE requires real-time interaction with the access point for each guess, making offline attacks impractical. SAE also provides forward secrecy — past session traffic cannot be decrypted even if the passphrase is later compromised.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-05',
    topicId: 'topic-c2-2-3',
    type: 'single_choice',
    stem: 'In an 802.1X wireless deployment, what is the role of the RADIUS server?',
    choices: ch('It assigns IP addresses to wireless clients via DHCP', 'It encrypts wireless traffic between the client and access point', 'It verifies client credentials and tells the access point to allow or deny network access', 'It broadcasts the wireless SSID and manages channel selection', 'c'),
    correctAnswer: ca('c'),
    explanation: 'In an 802.1X deployment, the RADIUS server is the authentication server. The client (supplicant) sends credentials to the access point (authenticator), which forwards them to the RADIUS server. The RADIUS server validates the credentials against its database and instructs the access point to grant or deny access. Without a valid RADIUS authentication, the client cannot pass any network traffic.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-06',
    topicId: 'topic-c2-2-3',
    type: 'single_choice',
    stem: 'Which EAP type requires both the client and the server to present digital certificates for mutual authentication, making it the most secure EAP method?',
    choices: ch('LEAP', 'PEAP', 'EAP-TLS', 'EAP-TTLS', 'c'),
    correctAnswer: ca('c'),
    explanation: 'EAP-TLS requires both the authentication server AND the client device to present digital certificates, providing mutual authentication. This is the most secure EAP method because there is no shared secret that can be guessed or stolen — both sides must have a valid certificate from a trusted CA. The tradeoff is the overhead of managing a PKI and deploying certificates to every client. PEAP only requires a server certificate; LEAP is deprecated; EAP-TTLS is similar to PEAP with more flexible inner protocols.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-07',
    topicId: 'topic-c2-2-3',
    type: 'single_choice',
    stem: 'A network administrator needs to authenticate administrators who are logging into Cisco routers and switches via SSH. Which AAA protocol is most appropriate for this use case?',
    choices: ch('RADIUS on UDP port 1812', 'TACACS+ on TCP port 49', 'EAP-TLS via 802.1X', 'WPA2-Enterprise', 'b'),
    correctAnswer: ca('b'),
    explanation: 'TACACS+ (Terminal Access Controller Access Control System Plus) is the correct protocol for authenticating administrators managing network devices. It runs over TCP port 49 and encrypts the entire payload. RADIUS is used for end-user network access (Wi-Fi, VPN) and runs over UDP. TACACS+ separates authentication, authorization, and accounting into distinct functions, giving granular control over which commands each admin can run.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-3-08',
    topicId: 'topic-c2-2-3',
    type: 'single_choice',
    stem: 'A technician is upgrading an office wireless network from WPA to WPA2. Which statement correctly describes the key difference in encryption between WPA and WPA2?',
    choices: ch('WPA uses AES; WPA2 uses TKIP', 'WPA uses TKIP (RC4-based); WPA2 uses AES-CCMP', 'WPA uses DES; WPA2 uses 3DES', 'WPA and WPA2 both use AES but with different key lengths', 'b'),
    correctAnswer: ca('b'),
    explanation: 'WPA uses TKIP (Temporal Key Integrity Protocol), which is built on the RC4 cipher that WEP used. TKIP added per-packet key mixing and a message integrity check to patch WEP\'s worst flaws, but RC4 itself is fundamentally weak. WPA2 replaced TKIP with AES-CCMP, a completely different and vastly stronger block cipher. This is the single most important WPA vs WPA2 distinction for the exam.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.4 Malware (8 questions) ────────────────────────────────────────────

  {
    id: 'q-c2-2-4-01',
    topicId: 'topic-c2-2-4',
    type: 'single_choice',
    stem: 'A malware outbreak spreads to over 200 machines on a network overnight without anyone clicking a link or opening an attachment. Which type of malware best describes this behavior?',
    choices: ch('Virus', 'Worm', 'Trojan', 'Ransomware', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A worm is the defining malware type that spreads automatically across networks without any user interaction. It exploits network vulnerabilities or services to copy itself to other reachable machines. A virus requires a user to execute an infected file. A Trojan requires the user to install it (disguised as legitimate software). Ransomware encrypts files but is not defined by self-propagation — though some ransomware (like WannaCry) combines ransomware with worm behavior.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-4-02',
    topicId: 'topic-c2-2-4',
    type: 'single_choice',
    stem: 'A user downloads what appears to be a free video editing application. After installation, the app works normally, but the attacker now has a remote backdoor into the machine. Which malware type is this?',
    choices: ch('Worm', 'Rootkit', 'Trojan', 'Adware', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A Trojan (Trojan horse) disguises itself as legitimate or useful software to convince the user to install it. Unlike worms, Trojans do not self-replicate — they rely on social engineering. Once installed, the Trojan\'s hidden payload (in this case a backdoor) activates. The legitimate functionality is the "bait" that makes the user trust the application.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-4-03',
    topicId: 'topic-c2-2-4',
    type: 'single_choice',
    stem: 'A user suddenly cannot open any files on their workstation. A message on the desktop demands payment in Bitcoin to restore access. Which malware type is responsible?',
    choices: ch('Spyware', 'Ransomware', 'Rootkit', 'Logic bomb', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Ransomware encrypts the victim\'s files and demands payment (typically cryptocurrency) in exchange for the decryption key. Key indicators include: sudden inability to open files, file extensions changed (.locked, .encrypted, .crypt), and a ransom note appearing on the desktop or in folders. The correct recovery approach is to restore from a clean offline backup — paying the ransom does not guarantee recovery of the decryption key.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-4-04',
    topicId: 'topic-c2-2-4',
    type: 'single_choice',
    stem: 'A technician runs a full antivirus scan on a suspected infected machine but the scan completes without detecting anything. However, the machine continues to exhibit suspicious behavior. Which malware type is most likely evading detection by hiding in the OS kernel?',
    choices: ch('Adware', 'Keylogger', 'Rootkit', 'Cryptominer', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A rootkit embeds itself at the kernel level of the operating system and intercepts OS calls to hide its own files, processes, and network connections from standard tools — including antivirus scanners running inside the infected OS. This is why a clean scan does not rule out a rootkit. Removal requires a bootable scanner (Windows Defender Offline, Kaspersky Rescue Disk) or, in severe cases, a complete OS reinstall.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-4-05',
    topicId: 'topic-c2-2-4',
    type: 'single_choice',
    stem: 'A manager notices that every time they log into the company banking portal, fraudulent transactions appear shortly after. A hardware inspection of the manager\'s workstation reveals a small device plugged between the keyboard and the USB port. What is this device?',
    choices: ch('USB hub', 'Hardware keylogger', 'Software keylogger', 'Botnet agent', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A hardware keylogger is a physical device that sits between the keyboard and the computer, silently recording every keystroke to internal memory for later retrieval by the attacker. Unlike software keyloggers, hardware keyloggers leave no software footprint and cannot be detected by antivirus scans — only physical inspection will find them. They are a risk on any machine accessible to unauthorized individuals.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-4-06',
    topicId: 'topic-c2-2-4',
    type: 'single_choice',
    stem: 'An infected machine appears to function normally for the user, but network monitoring reveals it is sending large volumes of traffic to an external IP address and participating in distributed denial-of-service (DDoS) attacks. Which malware classification describes this machine?',
    choices: ch('Ransomware victim', 'Botnet node (zombie)', 'Fileless malware host', 'Cryptominer', 'b'),
    correctAnswer: ca('b'),
    explanation: 'A machine enrolled in a botnet (called a bot or zombie) is remotely controlled by an attacker via a command-and-control (C2) server. Botnets are used for spam campaigns, DDoS attacks, credential stuffing, and cryptocurrency mining. Individual bots often show minimal user-visible symptoms by design — they are intended to remain hidden while the attacker profits from the compromised resources.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-4-07',
    topicId: 'topic-c2-2-4',
    type: 'single_choice',
    stem: 'An investigation finds that malicious code was hidden inside a payroll application by a disgruntled developer. The code activates only on the last day of the fiscal year and deletes payroll records. Which malware type is this?',
    choices: ch('Worm', 'Rootkit', 'Logic bomb', 'RAT', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A logic bomb is malicious code planted inside otherwise legitimate software that activates when a specific trigger condition is met — a date, a user action, a database event, or any other programmable condition. It remains dormant and undetected until triggered. Logic bombs are often planted by insiders (disgruntled employees, malicious developers) with access to the codebase. They are difficult to detect before activation.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-4-08',
    topicId: 'topic-c2-2-4',
    type: 'single_choice',
    stem: 'Security analysts detect malicious activity originating from PowerShell processes on a workstation. A thorough file scan finds no malicious executables on disk. Which malware type does this describe?',
    choices: ch('Virus', 'Fileless malware', 'Adware', 'Spyware', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Fileless malware never writes executable code to disk. It loads directly into memory and typically leverages legitimate OS tools like PowerShell, WMI, or the Windows registry to execute malicious actions. Because traditional antivirus engines scan files on disk, fileless malware can evade file-based detection entirely. Indicators include suspicious PowerShell activity, unusual WMI subscriptions, and processes spawned from Office applications.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.5 Social Engineering (8 questions) ────────────────────────────────

  {
    id: 'q-c2-2-5-01',
    topicId: 'topic-c2-2-5',
    type: 'single_choice',
    stem: 'An employee receives an email that appears to come from their bank, stating "Your account has been suspended. Click here immediately to restore access." The email contains a link that goes to a lookalike site. Which attack type is this?',
    choices: ch('Vishing', 'Phishing', 'Smishing', 'Whaling', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Phishing is a fraudulent email that impersonates a trusted organization and attempts to steal credentials or install malware by directing the victim to a malicious site or attachment. Key indicators here include urgency ("immediately"), a threat ("account suspended"), and a mismatched URL. Vishing uses voice/phone. Smishing uses SMS. Whaling is phishing targeted specifically at executives.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-5-02',
    topicId: 'topic-c2-2-5',
    type: 'single_choice',
    stem: 'A CFO receives an email that appears to come from the CEO, referencing a real ongoing merger deal and requesting an urgent wire transfer to a new vendor account before the close of business. The email domain is slightly different from the real CEO\'s. What type of attack is this?',
    choices: ch('Phishing', 'Vishing', 'Whaling', 'Smishing', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Whaling is a highly targeted form of spear phishing aimed specifically at C-suite executives (CEO, CFO, board members). Attackers use personal details about the target and their organization to craft convincing emails, often requesting large wire transfers or access to sensitive data. The authority of the apparent sender (CEO) and urgency are classic manipulation tactics. BEC (Business Email Compromise) is a closely related category.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-5-03',
    topicId: 'topic-c2-2-5',
    type: 'single_choice',
    stem: 'A user receives a text message claiming to be from a delivery company saying "Your package is held — click to confirm delivery details." The link leads to a credential-harvesting site. What is the name of this attack?',
    choices: ch('Phishing', 'Vishing', 'Smishing', 'Spear phishing', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Smishing (SMS phishing) uses text messages to deliver malicious links or requests. The name combines "SMS" and "phishing." Common smishing lures include fake package delivery notifications, bank alerts, and government messages. The defense is to never click links in unsolicited SMS messages — navigate directly to the official website instead.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-5-04',
    topicId: 'topic-c2-2-5',
    type: 'single_choice',
    stem: 'An attacker calls an employee, claims to be from the IT help desk, and says there is a security incident requiring the employee\'s login credentials to investigate. What social engineering attack is this?',
    choices: ch('Phishing', 'Vishing', 'Tailgating', 'Pretexting', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Vishing (voice phishing) uses phone calls to manipulate victims. The attacker impersonates a trusted authority (IT support, bank, government) to extract credentials or information. The correct response is to never provide credentials by phone — hang up and call the organization back on a number you independently look up. Pretexting (creating a fabricated scenario) is an element of this attack but vishing is the specific vector.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-5-05',
    topicId: 'topic-c2-2-5',
    type: 'single_choice',
    stem: 'An attacker carries boxes through a secure entrance immediately behind an authorized employee who holds the door open out of courtesy. What is the specific term for this physical attack?',
    choices: ch('Tailgating', 'Piggybacking', 'Impersonation', 'Dumpster diving', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Piggybacking is when an authorized person actively holds the door open for the attacker — often because the attacker appears to need assistance (carrying boxes, appearing to struggle). Tailgating is when the attacker slips through behind someone without the authorized person\'s knowledge or cooperation. Both bypass physical access controls but piggybacking involves the victim\'s unwitting participation. The best controls are mantraps and a strong challenge policy.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-5-06',
    topicId: 'topic-c2-2-5',
    type: 'single_choice',
    stem: 'An attacker searches through a company\'s outdoor trash bins and finds printed employee directories, internal memos, and a sticky note with a password. Which social engineering technique is this?',
    choices: ch('Shoulder surfing', 'Dumpster diving', 'Vishing', 'Watering hole', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Dumpster diving involves searching discarded documents and equipment for sensitive information useful in an attack — employee names, phone numbers, account numbers, internal diagrams, and even printed credentials. The defense is to cross-cut shred all documents containing any sensitive information and to physically destroy or wipe storage media before disposal. Strip-cut shredders are insufficient because the strips can be reassembled.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-5-07',
    topicId: 'topic-c2-2-5',
    type: 'single_choice',
    stem: 'A security researcher discovers that attackers have compromised a legitimate industry news website that the target organization\'s engineers are known to visit regularly. The attackers deliver malware to visitors through the site. What is this attack called?',
    choices: ch('Phishing', 'Smishing', 'Watering hole attack', 'Spear phishing', 'c'),
    correctAnswer: ca('c'),
    explanation: 'A watering hole attack compromises a website that the target group is known to visit (like a watering hole where prey gather). Instead of going directly after the well-defended target organization, attackers infect a trusted third-party site to passively deliver malware to victims. Defenses include keeping all software patched, endpoint protection, and browser-based exploit mitigations.',
    difficulty: 3,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-5-08',
    topicId: 'topic-c2-2-5',
    type: 'single_choice',
    stem: 'Which of the following is the MOST effective long-term defense against social engineering attacks in an organization?',
    choices: ch('Deploying a next-generation firewall', 'Enabling multi-factor authentication on all accounts', 'Ongoing security awareness training with simulated phishing exercises', 'Installing email filtering software', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Social engineering targets human psychology, not technology — so technical controls alone cannot fully prevent it. Ongoing security awareness training, including simulated phishing exercises that provide immediate feedback when employees click, consistently produces the highest return on investment. MFA is an excellent compensating control (even if credentials are stolen, it limits damage), but it does not address physical social engineering or scenarios where users are tricked into performing actions directly. Training addresses the root cause: human behavior.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

  // ─── 2.6 Malware Removal (8 questions) ───────────────────────────────────

  {
    id: 'q-c2-2-6-01',
    topicId: 'topic-c2-2-6',
    type: 'single_choice',
    stem: 'According to the CompTIA A+ malware removal process, what is the FIRST step a technician should take when a machine is suspected of being infected?',
    choices: ch('Quarantine the infected system by disconnecting it from the network', 'Disable System Restore', 'Investigate and verify malware symptoms', 'Run an antivirus scan immediately', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Step 1 of the CompTIA 8-step malware removal process is to investigate and verify malware symptoms. The technician should first confirm that the symptoms observed are consistent with a malware infection and document everything — what symptoms are present, when they started, and what the user was doing. This documentation becomes the baseline for verifying successful remediation. Quarantine (step 2) comes next, then disabling System Restore (step 3).',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-6-02',
    topicId: 'topic-c2-2-6',
    type: 'single_choice',
    stem: 'After confirming a malware infection, a technician disconnects the machine from the network. Why is network disconnection a critical immediate step?',
    choices: ch('It forces the malware to stop executing', 'It prevents the malware from spreading to other machines and cuts off command-and-control communication', 'It causes Windows to automatically quarantine infected files', 'It allows antivirus to run faster without network overhead', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Quarantining the infected system (step 2) by disconnecting all network connections accomplishes two critical goals: it prevents the malware from spreading laterally to other machines on the network, and it cuts off command-and-control (C2) communication that many malware variants require to receive instructions or exfiltrate data. This limits damage and gives the technician control of the situation before remediation begins.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-6-03',
    topicId: 'topic-c2-2-6',
    type: 'single_choice',
    stem: 'Why must System Restore be disabled BEFORE scanning and cleaning a malware infection?',
    choices: ch('System Restore uses excessive disk space that antivirus needs during scanning', 'Restore points may contain copies of the malware, allowing it to be restored even after cleaning', 'System Restore conflicts with antivirus definitions and causes false positives', 'Antivirus cannot run while System Restore is enabled', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Step 3 of the CompTIA malware removal process is to disable System Restore before scanning. System Restore creates point-in-time snapshots of system files. If the malware existed before these snapshots were taken, those restore points contain the malware. Without disabling System Restore first, a user could restore a "clean" snapshot and inadvertently restore the infection. System Restore is re-enabled in step 6, after the system is confirmed clean.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-6-04',
    topicId: 'topic-c2-2-6',
    type: 'single_choice',
    stem: 'A technician is remediating an infected machine. The malware is blocking the antivirus software from running. Which technique should the technician try next?',
    choices: ch('Reinstall the antivirus software', 'Boot into Safe Mode to prevent the malware from loading with the OS', 'Disable System Restore', 'Document the findings and close the ticket', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Safe Mode starts Windows with a minimal set of drivers and services, preventing most malware from loading. This allows antivirus tools to run without the malware actively blocking them. Safe Mode with Networking allows downloading updated scanner definitions during the process. If Safe Mode is insufficient, a bootable AV rescue tool (Kaspersky Rescue Disk, Windows Defender Offline) that loads a completely separate OS should be used.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-6-05',
    topicId: 'topic-c2-2-6',
    type: 'single_choice',
    stem: 'After successfully removing malware from a workstation, what is the CORRECT next action according to the CompTIA 8-step process?',
    choices: ch('Immediately re-enable System Restore and create a clean restore point', 'Schedule scans and run all available updates', 'Educate the end user about how the infection occurred', 'Document findings and close the ticket', 'b'),
    correctAnswer: ca('b'),
    explanation: 'Step 5 of the CompTIA malware removal process is to schedule scans and run updates. After the initial cleaning (step 4), the technician should run a full scan to verify nothing was missed, then immediately apply all Windows updates, update antivirus definitions, and update all other software. The machine was likely infected through an unpatched vulnerability, so patching is essential to prevent immediate reinfection. Step 6 (re-enable System Restore) follows after updates are confirmed.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-6-06',
    topicId: 'topic-c2-2-6',
    type: 'single_choice',
    stem: 'A workstation is confirmed to have a rootkit infection. Multiple cleaning attempts have failed to remove it. What is the recommended course of action?',
    choices: ch('Run Malwarebytes in Safe Mode with Networking', 'Perform a Windows System Restore to the last known good point', 'Wipe the drive and reinstall the operating system from clean media', 'Disable the rootkit\'s startup entries using Autoruns and reboot', 'c'),
    correctAnswer: ca('c'),
    explanation: 'Rootkits operate at the kernel level and modify the OS itself. You cannot trust an infected OS to accurately report what is still running or what has been cleaned. After a confirmed rootkit infection, the recommended action is to wipe the drive and reinstall the OS from known-clean media. System Restore restore points may themselves contain the rootkit. The Sysinternals Autoruns tool can sometimes help but cannot guarantee complete removal of a kernel-mode rootkit.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-6-07',
    topicId: 'topic-c2-2-6',
    type: 'single_choice',
    stem: 'A user\'s files have been encrypted by ransomware. The user asks whether they should pay the ransom. What is the CompTIA-recommended response?',
    choices: ch('Pay the ransom immediately with a gift card to get the decryption key', 'Pay the ransom only if the files are business-critical', 'Do not pay; restore from a clean offline backup instead', 'Format the drive and pay the ransom for the key before reinstalling Windows', 'c'),
    correctAnswer: ca('c'),
    explanation: 'CompTIA and law enforcement agencies consistently advise against paying ransoms. Payment does not guarantee delivery of a working decryption key, it funds criminal operations, and it marks the organization as a target willing to pay. The proper recovery path is to restore from a clean backup that pre-dates the infection and was not network-connected (network-attached backups are often encrypted by ransomware too). Free decryptors are also available for some strains at NoMoreRansom.org.',
    difficulty: 1,
    tags: null,
    createdAt: NOW,
  },
  {
    id: 'q-c2-2-6-08',
    topicId: 'topic-c2-2-6',
    type: 'single_choice',
    stem: 'According to the CompTIA malware removal process, what is the LAST step after a system has been fully remediated?',
    choices: ch('Re-enable System Restore and create a clean restore point', 'Schedule recurring antivirus scans', 'Educate the end user', 'Document findings, actions taken, and outcomes', 'd'),
    correctAnswer: ca('d'),
    explanation: 'Step 8, the final step of the CompTIA malware removal process, is to document findings, actions taken, and outcomes. This includes recording what malware was found, how it likely entered the system, what tools were used, all changes made, and the final outcome. Documentation supports recurring infection analysis, organizational learning, compliance requirements, and demonstrates due diligence. Educating the user (step 7) and re-enabling System Restore (step 6) occur before the final documentation step.',
    difficulty: 2,
    tags: null,
    createdAt: NOW,
  },

]
